### ISSUE TITLE
No device found with specified name on Windows11

### ISSUE THREAD

**Issue by igameta** [alvr-org/ALVR#1006]
## Description

I could connect my HMD with my computer running ALVR Server,but HMD displayed only green screen and ALVR Server threw "No device found with specified name" error.
I assume that only video outputs are wrong because Controllers and Tracking worked.

I apologize for my bad English.
If you couldn't understand my English,please translate Japanese text below.

HMDとALVRを起動したパソコンとの接続は行えるが、HMDは深緑色の画面のみを表示し、ALVR Serverでは"No device found with specified name"エラーが発生。
コントローラとトラッキングは正常に動作しているため、恐らくビデオ出力のみの問題であると考えられる。

## General Troubleshooting
- [✔︎] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [✔︎] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
Quest2
ALVR(installed from SideQuest)
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen7 3700X
**GPU**:
RTX2060
**Audio**:
Arctis7
### Installation
**ALVR Version**:
18.2.1
**SteamVR Version**:
1.21.11
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [✔︎] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows11 21H2

**Comment by zarik5** [comment]
I think the error message is for audio. Either disable audio or in the advanced settings select the audio device by index, then try each index in order (1,2,3,...) until audio works again.

**Comment by igameta** [comment]
> I think the error message is for audio. Either disable audio or in the advanced settings select the audio device by index, then try each index in order (1,2,3,...) until audio works again.

Thank you.
ALVR Server is no longer throw No device…… error,but video problem is still alive.
May I have to close this issue and open new issue about video problem?

**Comment by zarik5** [comment]
There are countless open issues about the video not working. You can put a comment in one of those, but as you can imagine this is hard to solve, most often than not it's a problem with the hardware, not software.

**Comment by igameta** [comment]
I see.
I could connect HMD and computer.
The green out is caused by RDP connection.
