### ISSUE TITLE
Quest 2 tracks fine, nothing being streamed. Stuck in white void.

### ISSUE THREAD

**Issue by thatpix3l** [alvr-org/ALVR#1007]
## Description

On my Oculus Quest 2, ALVR connects fine, tracks fine (at least in SteamVR Home on my monitor), but the screen in the headset is stuck. No video is being streamed to it, just stuck in the white void. In the server logging, I noticed this error:
`error in encoder thread: Failed to find encoder libx264`

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Quest 2
ALVR (v18.2.1, Linux portable version)

### Hardware
[Hardware Probe Link](https://linux-hardware.org/?probe=c9b7431269)

**CPU**: Ryzen 7 4800H

**GPU**: GTX 1660 Ti Mobile

**Audio**:...Laptop Speakers?

### Installation
**ALVR Version**: 18.2.1 (alvr_server_linux_portable)

**SteamVR Version**: 1.21.11

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
openSUSE Tumbleweed (All packages updated to latest at time of issue and posting)

**Comment by ColdIce1605** [comment]
You need to install the x264 dependency it seems.

**Comment by 20PercentRendered** [comment]
Install `libx264`. If you have nvidia control panel (Nvidia X Server Settings), go to VDPAU information and check if your gpu supports H264.
Also, run steam with your dedicated gpu, as you seem to have integrated graphics. (With `prime-run steam`).

**Comment by thatpix3l** [comment]
I was finally able to get past the "Stream will begin soon" message by finding and placing all required libraries in my ~/lib64 directory, but now I am stuck in a green screen void. I feel so close to Linux gaming, but I need help to get past this last (I assume) obstacle.

**Comment by silveropensource** [comment]
I'm having the exact same issue, and possibly due to flatpak steam, not sure though.

**Comment by ColdIce1605** [comment]
Could you try native steam not flatpak?

**Comment by thatpix3l** [comment]
@ColdIce1605 I would _really_ not like to, since normal Steam dumps all its contents all over my filesystem. It also helps that I can simply drag and drop my `~/.var/app/com.valvesoftware.Steam` onto a new Linux installation, and have everything work as if on a  previous system, which is exactly what I did after nuking my original Tumbleweed install for unrelated reasons...

Also, although not applicable to me since I run Tumbleweed, users of distros like Fedora Silverblue and openSUSE MicroOS with immutable filesystems have an even harder time setting up dependencies for this, having to reboot for each and every update.

I hope that, someday, users like mentioned above will be considered for this project.

**Comment by ColdIce1605** [comment]
One problem, ALVR cannot work with how flatpaks guarantees security.

**Comment by thatpix3l** [comment]
At least for this project, what does flatpak specifically do to "guarantee" security? If the answer is file isolation, then technically that would by a non-issue because one could instead modify the RPATH of the executable and portable libraries to point towards a folder containing all other runtime sub-dependencies just for ALVR. In fact, that is exactly what I have done to have ALVR even start inside of Steam's flatpak folder.

**Comment by ColdIce1605** [comment]
sandboxing.

**Comment by JacekJagosz** [comment]
It is still a problem for me, unfortunately.

**Comment by JacekJagosz** [comment]
I have been packaging it for Solus from source, because I wanted to include it in its repos too. I tried the nightly many times but stopped trying some time ago, because there hasn't been any update on this issue.
Was there any commit that was supposed to fix it?
