### ISSUE TITLE
Quest2 stuck at "The stream will begin soon Please wait.." using UDP and remote PC

### ISSUE THREAD

**Issue by rejdzu** [alvr-org/ALVR#1008]
## Description
I'm trying to connect Quest2 to remote PC via Internet. All ports are open on router according to documentation. Headset is stuck at "The stream will begin soon Please wait.." message. 
If I run the same ALVR app locally everything works fine and I can connect easily. I've tested that with a friend on two PCs and two headsets. From what we see it seems that UDP is only working locally. When we switch to TCP then we can connect to each other remotely.

Extra info: When we were restarting server or disabling port forwarding on a router then it was showing status correctly (The server is restarting\nPlease wait... or The server has disconnected.)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
Windows 10
Oculus Quest 2 v37

### Hardware
**CPU**:
AMD Ryzen 5 and 9

**GPU**:
AMD
NVIDIA

**Audio**:

### Installation
**ALVR Version**:
18.2.1
18.1.1

**SteamVR Version**:
1.21.11

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**
Windows 10 21H2

**Comment by matthew42904** [comment]
im having the same issue. i have a xeon e5 2650 v2 and a 1650 super
