### ISSUE TITLE
Constant error 203 when starting to stream

### ISSUE THREAD

**Issue by Kirottu** [alvr-org/ALVR#1014]
## Description
SteamVR itself starts up fine, but whenever I try to connect with the client all I see is a distorted view and soon SteamVR runs into the error code 203. After that SteamVR also refuses to shut down cleanly, requiring a forced shutdown.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=069ce018ad)

### Installation
**ALVR Version**: 18.2.1

**SteamVR Version**: 1.21.12

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by Kirottu** [comment]
Update: after downgrading to ALVR 18.0.0 that no longer happens.

**Comment by Arr4y** [comment]
I've seen posts of this working on other distributions other than Arch Linux (I run Garuda Linux; Arch-Based). Looking at the output logs, the error seems to come from "alvr/sockets/src/control_socket.rs" at line 32 ("let packet_bytes = self"). I'm not a Rust developer so I can't tell if that specific line is actually the culprit or if lines (33-37) might be the culprit.

Not sure how you got it to work but I also downgraded to ALVR 18.0.0 and I still got the same (-203) error.

**Comment by parkerlreed** [comment]
Yeah same here no matter the version, no matter the settings, just 203 every time with RX 480. Latest release I can get consistent working tracking and no 203 but the video still fails in the exact same way. On 18.0.0 video fails, and tracking fails after about 4 seconds into the 203 error.

**Comment by sethseth6** [comment]
Having this same problem, v18.2.1 on EndeavourOS with an RX 470. I have also experienced #958 and did what was suggested there to make video not crash.

**Comment by octinhuh** [comment]
Same issue on Arch with RX 580. I've tried X and Wayland and see the same error. No ALVR errors, however.

**Comment by SkyyWasTaken** [comment]
Same issue over here. Arch, RX 580.

**Comment by kamaji420** [comment]
Same issue happening for me. Manjaro, RX 560

**Comment by Arr4y** [comment]
This issue seems to happen on Arch-based systems. I wonder what could be causing it.

**Comment by SkyyWasTaken** [comment]
Found the solution! It only affects Arch-based distros + AMD (afaik, there could be more.)
Basically, it's something with Arch's version of ffmpeg. Downloading the Linux portable build fixes it; do not use the aur repository if you're on Arch with an AMD processor.
