### ISSUE TITLE
please bring back Tracking Space Settings (local)

### ISSUE THREAD

**Issue by matcham** [alvr-org/ALVR#1031]
## Description
I'm missing tracking space settings !
before ALVR v18.x , I used to set it to 'local' mode : 
`Local means that the anchor between the virtual and real worlds is movable: if you press and hold the Oculus button the world will rotate and translate depending on your position and heading at that moment.`

it perfectly fited my needs : I'm using 3 quest2 in a shared space, and it was easy to calibrate and sync the 3 HMDs : place and orient the Quest in the center of the space, and press & hold Oculus button. repeat this step for each HMD, and voila.

Now Tracking Space settings is gone... the position and orientation of each HMD depends of the gardian settings of each Quest, no way to make them match perfectly ; and quite often, when turning off / on the quest, the forward direction is turned (90 degrees) ; 
`To choose the forward direction with the room scale guardian, redo the guardian setup and select “Confirm” when facing the preferred forward direction.`
this doesn't seem to work. The forward direction visible in steamVR do not match the direction the direction I'm facing when confirming the guardian setup...

Please, bring back tracking space setting with local mode, i used to work much better IMHO !

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Installation
**ALVR Version**: 18.2.1

**SteamVR Version**: 1.22.5

**Comment by zarik5** [comment]
For the average user, if they need to reorient the view often, setting the guardian as stationary is an acceptable compromise. In your case you have a more complex setup and i suggest you to use some tool like [OpenVR Space Calibrator](https://github.com/pushrax/OpenVR-SpaceCalibrator). I still plan to add back the option in ALVR but it's currently low priority for me. We already discussed this on Discord and maybe @sctanf can give this a try.

**Comment by matcham** [comment]
Thanks for your feedback.
I tried OpenVR Space Calibrator, but I can't see how it can help in my case. :-s

SteamVR "reset standing position" button does what I need, but as it has to be clicked in VR, I must wear the HMD to activate it... and to make an accurate calibration, the Quest needs to be placed in an exact position (for example on a table with marks on it, or on a stand, in order to be able to do the exact same calibration for the 3 HMDs).
That's why the _"press and hold the Oculus button the world will rotate and translate depending on your position and heading at that moment"_ was just perfect for my needs ! Quick and easy, no need to edit the gardian..

setting the gardian as stationary is not an option as I need to move in a large room, and the gardian is very useful to prevent collisions with walls and obstacles...

**Comment by silveropensource** [comment]
You could possibly press the button in VR while the headset is on a table if you disable the proximity sensor. Just need to make sure the button is visible straight on and you can see it on the pc stream window (definitely more complicated than what you described but not impossible).

**Comment by zarik5** [comment]
Merged February 1st.
