### ISSUE TITLE
AUR application fails to install ALVR

### ISSUE THREAD

**Issue by GoldenAJF** [alvr-org/ALVR#1035]
## Description
My Add/Remove Software (My AUR) recieves the error "Failed to prepare transaction" then asks me to edit the build files.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and **have not** successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
Manjaro KDE Plasma

### Hardware
[**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=3d9af3df5a

### Installation
**ALVR Version**: alvr 18.2.1.r0.gd37a4b9b-1

**SteamVR Version**: 1.21.12

**Install Type**:
AUR

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):  Manjaro Linux

**Comment by silveropensource** [comment]
Try building it with yay it worked fine for me.

**Comment by GoldenAJF** [comment]
I've tried using yay, and during the install process (or some sort of process) it just freezes.
![Screenshot_20220419_192057](https://user-images.githubusercontent.com/34905857/164121968-ce9c731b-4d87-493f-b23d-e45054c31bae.png)

**Comment by silveropensource** [comment]
That library takes quite a while to build, just try waiting for it to get it done.

**Comment by GoldenAJF** [comment]
ALVR does appear to be working now, thank you.
