### ISSUE TITLE
ALVR Dashboard not loading

### ISSUE THREAD

**Issue by Croldfish** [alvr-org/ALVR#1037]
## Description
After I launch alvr_launcher and it does its thing, it tries ot open the alvr dashboard, but it doesn't load. the screen is competly white. 

## General Troubleshooting
- [ x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=bbaa6e145b 

### Installation
**ALVR Version**:18.2.1.r0.gd37a4b9b-1

**SteamVR Version**: latest as of april 11th????????

**Install Type**:
- [ x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x ] Source
I tried it on both, and still same issues
**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
endeavourOS (arch basically)

**Comment by silveropensource** [comment]
Have you tried opening it manually in a browser with 127.0.0.1:8082 in address bar?
