### ISSUE TITLE
Oculus quest crash

### ISSUE THREAD

**Issue by thisleo** [alvr-org/ALVR#1041]
## Description

When running the server on Windows, the Client crashes almost immediately after displaying a status message (like "Waiting for server" or "Stream will begin soon", depending on the server's state) for a brief moment on my (up-to-date) Oculus Quest 2.

Here's what the Dashboard log says:
`17:09:33.864943400	[INFO]	ClientConnected
17:09:33.865527700	[INFO]	Serial Number: 1WMGH000XX0000
17:09:33.865537900	[INFO]	Model Number: Miramar
17:09:33.865546000	[INFO]	Render Target: 2688 1440
17:09:33.865557700	[INFO]	Seconds from Vsync to Photons: 0.005000
17:09:33.865564900	[INFO]	Refresh Rate: 72
17:09:37.511508100	[INFO]	ClientDisconnected
17:09:37.511539000	[INFO]	Client disconnected. Cause: At alvr\sockets\src\control_socket.rs:32: remote host forced closed an occoured connection. (os error 10054)`

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Intel(R)_Xeon(R) CPU E5-2620 v3

**GPU**:
NVIDIA GeForce GTX 1660 SUPER

**Audio**:

### Installation
**ALVR Version**:
18.2.2 on both client and server
**SteamVR Version**:

**Install Type**:
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10

**Comment by vayneli** [comment]
May I ask you how to solve this problem?
