### ISSUE TITLE
alvr_launcher is unable to detect SteamVR installed via flatpak-installed Steam

### ISSUE THREAD

**Issue by mardab** [alvr-org/ALVR#1042]
## Description
It is exact problem as reported before in #904 , only that some people, myself included, have no option not to use flatpak-based installation. As far as I know the main difference is location of directories, which I'd like to help patch into next version of ALVR 

## General Troubleshooting
- [:white_check_mark:] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [:white_check_mark:] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
results from hw-probe (also exclusively available in flatpak format for me): 
https://linux-hardware.org/?probe=f203fe95e5
**CPU**:
AMD Ryzen 2500U
**GPU**:
AMD Polaris 11
**Audio**:
Pulse/Pipewire+JACK2
### Installation
**ALVR Version**:
v18.2.1
**SteamVR Version**:
v1.21.12 (1647034158)
**Install Type**:
[:white_check_mark:] Packaged (`exe`, `deb`, `rpm`, etc)
**OS Name and Version** :
Funtoo Linux (@funtoo)
**Feature Requests:**
Perhaps this could be fixed by enabling manual specification of path to required SteamVR components?

**Comment by ColdIce1605** [comment]
The flatpak version will not work as it needs to be a native app.

**Comment by matteoturini** [comment]
please reopen, still an issue

**Comment by ColdIce1605** [comment]
> I have been able to get ALVR running inside of steam's flatpak, by moving it to the steam directory within the flatpak, entering the flatpak with the command `flatpak enter com.valvesoftware.Steam bash`, navigating to that folder and running it with steam open.
> 
> Steam then detects ALVR, and ALVR can connect to the headset, but flatpak doesn't have the necessary ffmpeg encoders to get it working.

Wdym, flatpak doesn't have the necessary ffmpeg encoders explain it better.

**Comment by xDShot** [comment]
Install Flatseal and provide Filesystem accesses for Steam flatpak app.

**Comment by famellad** [comment]
> Wdym, flatpak doesn't have the necessary ffmpeg encoders explain it better.

I'm no expert in this, but basically flatpaks work by running inside sandboxed containers, they have their own libraries and directory structures they use to operate without having access to most of your OS, there are several reasons for this but in practice it means that flatpaks will only be able to see things installed in their own environment, the most notable example of this is flatpak apps not recognizing your system theme (unless, of course, the theme is also installed in the flatpak environment).

**Comment by matteoturini** [comment]
still an issue

**Comment by jmaris** [comment]
> > I have been able to get ALVR running inside of steam's flatpak, by moving it to the steam directory within the flatpak, entering the flatpak with the command `flatpak enter com.valvesoftware.Steam bash`, navigating to that folder and running it with steam open.
> > Steam then detects ALVR, and ALVR can connect to the headset, but flatpak doesn't have the necessary ffmpeg encoders to get it working.
> 
> Wdym, flatpak doesn't have the necessary ffmpeg encoders explain it better.

flatpak ships a copy of FFMPEG, which is the software used to encode the video and audio streams from games. The issue is that this copy of FFMPEG does not have the codecs used by ALVR so ALVR cannot encode content. At least that is what I understood from the output.

Concerning accessing data inside a flatpak, it isn't as impossible as one might expect, I've put some pointers in  #1095
