### ISSUE TITLE
Can't compile. Cargo: wrng arguments.

### ISSUE THREAD

**Issue by Zuhaitza** [alvr-org/ALVR#1043]
## Description

What I get:

**Finished dev [unoptimized + debuginfo] target(s) in 1.86s
Running `target/debug/alvr_xtask build-server --release --bundle-ffmpeg`

Wrong arguments.

cargo xtask
Developement actions for ALVR.

USAGE:
    cargo xtask <SUBCOMMAND> [FLAG] [ARGS]**

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
Terminal: gnome-terminal

### Hardware
Host: GF65 Thin 10UE REV:1.0

**CPU**:
Intel i7-10750H (12) @ 5.000GHz

**GPU**:
Intel UHD Graphics
NVIDIA 01:00.0 NVIDIA Corporation Device 2520

**Audio**:

### Installation
**ALVR Version**:
Last from GIT, downloaded today april 16 2022.

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [*] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ubuntu 20.04.4 LTS x86_64 
Kernel: 5.13.0-39-generic

**Comment by Zuhaitza** [comment]
I tried again fater using INSTALLATION SCRIPT (is it necessary to run it before?) and it worked for a while, now I obtain this:

  cargo:warning=cpp/platform/linux/generated/avutil_loader.h:13:10: fatal error: libavutil/hwcontext_vulkan.h: No such file or directory
  cargo:warning=   13 | #include <libavutil/hwcontext_vulkan.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.

**Comment by silasalves** [comment]
I haven't been successful in compiling it from source myself, but anyway here is my two-cent worth.

I believe that the option `--bundle-ffmpeg` is not used anymore (maybe it was replaced by the `--gpl` option?), so take a look at that. You can run it with `--help` to see the actual options.

With regard to this error:

```
cargo:warning=cpp/platform/linux/generated/avutil_loader.h:13:10: fatal error: libavutil/hwcontext_vulkan.h: No such file or directory
(...)
```

It seems like you are missing some dependencies (in this case, FFMPEG). Take a look at the [instructions to see which dependencies to install](https://github.com/alvr-org/ALVR/wiki/Building-From-Source#dependencies) on Ubuntu 20.04.

ALVR also comes with [pre-compiled binaries for Ubuntu 20.04](https://github.com/alvr-org/ALVR/wiki/Installation#debian--ubuntu--pop-os), so unless you want to change the code I would recommend you to use that instead.
