### ISSUE TITLE
[Linux] Dashboard dies after VRmonitor shows up

### ISSUE THREAD

**Issue by Fancy2209** [alvr-org/ALVR#1044]
## Description

When I open alvr launcher, it shows for the time of waiting the server to connect and before the VRMonitor shows, but as quickly as the monitor shows, the webserver seems to die

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[`hw-probe`](https://linux-hardware.org/?probe=0c4c081e71)

### Installation
**ALVR Version**:
v18 Stable Compiled

**SteamVR Version**:
Latest Beta
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [X] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Pop!_OS 21.10

**Comment by Fancy2209** [comment]
doing it before the crash seems to half work

**Comment by daxime** [comment]
Hi, i have the same issue.
On the Quest 1 ALVR is waiting me to click on "Trust" but on PC there is no window...
I use Garuda (but i will migrate to an other distro soon).

**Comment by margusre123** [comment]
daxime, you must use the localhost:8082 to do setup, and there should be "Trust" button on there
