### ISSUE TITLE
Client crashes and is slow(Reminder to zarik)

### ISSUE THREAD

**Issue by ColdIce1605** [alvr-org/ALVR#1047]
Client will sometimes crash on connection or disconnection, client also has terrible performance with decoding.
(Git branch)

**Comment by ColdIce1605** [comment]
@zarik5 is it possible to make it unspoiliable.

**Comment by Vixea** [comment]
Still happens just to have a update on this

**Comment by zarik5** [comment]
This is probably not relevant anymore.

**Comment by Vixea** [comment]
yep, irrelevant
