### ISSUE TITLE
build 18.2.1 source code, Rust Dependency cannot be downloaded

### ISSUE THREAD

**Issue by DarthAhsoka** [alvr-org/ALVR#1051]
![image](https://user-images.githubusercontent.com/48704370/165213089-027a3ee5-5971-4fc7-8410-364b8ece53ef.png)

I want complier  the ALVR 18.2.1 , but  run command "cargo xtask prepare-deps --platform windows"    in windows cmd,  an error has occurred

**Comment by ArchOwlen** [comment]
Same happening with 18.2.2
![image](https://user-images.githubusercontent.com/69368336/167744494-75af81ce-8ed8-4fa7-9913-3fc92925506e.png)
