### ISSUE TITLE
Remove broken link to python USB script.

### ISSUE THREAD

**Issue by Bad-At-Usernames** [alvr-org/ALVR#1053]
The link on the wiki's broken.
Can you either remove the 'canary' from 'canary.discord.com', or just put the script in a gist like the bat script (please).
(I made [a gist](https://gist.github.com/Bad-At-Usernames/684784f42cbb69e22688a21173ec263d) before I realised I can't edit the wiki, but feel free to make another one).

**Comment by zarik5** [comment]
Thanks, I linked to your gist.
