### ISSUE TITLE
error in encoder thread: failed to initialize vulkan Cannot allocate memory

### ISSUE THREAD

**Issue by Techlinious** [alvr-org/ALVR#1055]
## Description
Tracking seems to work fine according to SteamVR Viewer, but the quest app freezes in the white void with "stream will begin soon".
Logs show one error stating: "error in encoder thread: failed to initialize vulkan Cannot allocate memory" 
When I try to switch between h264 and HVEC codecs, I get the same error.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
(https://linux-hardware.org/?probe=773f69d63b)

**CPU**:
Ryzen 5 3600 6-core

**GPU**:
GTX 1080 8GB

**RAM**:
32GB 3200mhz

### Installation
**ALVR Version**:
v18.2.1

**SteamVR Version**:
v1.21.12

**Install Type**:
- [x] Portable (`zip`)

**OS Name and Version** 
Ubuntu 22.04 LTS

**Comment by stsichler** [comment]
I do also and still have this issue with ALVR v19.0.0 on SteamVR 1.24.6 and Ubuntu 20.04 / Mint 20.3
