### ISSUE TITLE
Can't connect to ALVR

### ISSUE THREAD

**Issue by GoldenAJF** [alvr-org/ALVR#1057]
## Description
I opened ALVR on my pc, and paired my headset, but when I open the app on my headset, it gets stuck on "Stream will start soon, please wait". And when I take off my headset to look at my pc, it's just a black screen with my cursor. I've waited and nothing happened, and tried interacting with my pc, and I couldn't do anything besides move the mouse around. This forces me to manually restart my pc.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
KDE Plasma Version: 5.24.4

### Hardware
https://linux-hardware.org/?probe=3d9af3df5a

### Installation
**ALVR Version**: v18.2.1

**SteamVR Version**: 1.21.12

**Install Type**:
AUR (Add/Remove Software)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Manjaro Linux

**Comment by gattila** [comment]
Is there any way to provide a little bit more detailed diagnostic information during the initialization? I facing with a similar issue since I moved from Ubuntu 20.04 to 22.04 and I can't see any information in the console log, just one line message that the initialization was failed, but there is no any more information about the cause.

**Comment by GoldenAJF** [comment]
Since my post, I have moved over to Windows to handle my (hopefully temporarily) handle my vr, but I have noticed that since I last used stream vr, my router must have changed or something, because now I am not availalbe to do that anymore and I assume that's what this problem is.
