### ISSUE TITLE
SteamVR crashes after connecting with the client.

### ISSUE THREAD

**Issue by arminask** [alvr-org/ALVR#1059]
After opening up ALVR and SteamVR on PC and opening ALVR client on Quest 2, it get's stuck on "The stream will begin soon", video:
https://www.youtube.com/shorts/t5sptzvDlMc

This is what happens on PC after connecting with the client:
![Screenshot from 2022-05-08 15-11-31](https://user-images.githubusercontent.com/72100724/167295834-773dd7fd-1cd3-4d40-b296-b2d23c9aa058.png)

ALVR logging:
![Screenshot from 2022-05-08 15-11-42](https://user-images.githubusercontent.com/72100724/167295846-0d64a6de-46c9-4dd2-906a-0a302a3771ac.png)

I set OpenXR runtime to SteamVR:
![Screenshot from 2022-05-08 12-59-01](https://user-images.githubusercontent.com/72100724/167291622-5ef869c4-1a08-4672-80e9-181f4596135b.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**:
AMD Ryzen 5 3600x
**GPU**:
AMD RX 580 8GB
**Audio**:
ALSA
### Installation
**ALVR Version**:
v18.2.1
**SteamVR Version**:
1.21.12
**Install Type**:
aur alvr (yay -S alvr)

**OS Name and Version**:
OS: Manjaro Linux x86_64
Kernel: 5.15.32-1-MANJARO
DE: GNOME 41.5

**Comment by octinhuh** [comment]
This looks like the same issue as [this one](https://github.com/alvr-org/ALVR/issues/1014), so be sure to watch it. I'm not sure if anyone knows why it is, unfortunately. It seems to affect Arch-based distros.
