### ISSUE TITLE
127.0.0.1 problem

### ISSUE THREAD

**Issue by Emoflia** [alvr-org/ALVR#1062]
When i run ALVR Dashboard, it say's me like: "127.0.0.1 can't be reached" I've tried reinstall programm, flush dns etc, but nothing fixed my problem. (ALVR worked fine up to some point)

### Hardware

**CPU**:Intel Core 2 Quad Q8400

**GPU**:GTS 450

### Installation
**ALVR Version**:18.0.0 - 18.2.3

**SteamVR Version**:1.22.11(last)

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version**:Windows 10 Pro 21H2

**Comment by ashwad3** [comment]
I have experienced the same issue with v18.2.0. My firewall, including the Win 10 firewall, is disabled. The issue occurs after my device has been in sleep or hibernation. When I open ALVR the error mentioned above occurs. I can confirm that neither ALVR or Chrome are opened during the sleep or hibernation period. Power-cycling the router and/or refreshing the network connection does not fix it. Only a reinstall and reboot works.

**Comment by Emoflia** [comment]
> I have experienced the same issue with v18.2.0. My firewall, including the Win 10 firewall, is disabled. The issue occurs after my device has been in sleep or hibernation. When I open ALVR the error mentioned above occurs. I can confirm that neither ALVR or Chrome are opened during the sleep or hibernation period. Power-cycling the router and/or refreshing the network connection does not fix it. Only a reinstall and reboot works.

wdym

**Comment by crapStone** [comment]
Does a reboot fix the problem?

**Comment by Emoflia** [comment]
> Does a reboot fix the problem?

no
![1](https://user-images.githubusercontent.com/104817815/191716033-ee7fa35c-d22b-48a5-9f28-4719413c6384.png)
![2](https://user-images.githubusercontent.com/104817815/191716050-69a394d0-4122-44d7-816a-eac328f99bd8.png)
(pictures of problem, 127.0.0.1 screen are rare now)

**Comment by Emoflia** [comment]
another screenshot
![image](https://user-images.githubusercontent.com/104817815/194018722-b46a5443-8f97-46cf-a675-6ce4d506132c.png)

**Comment by Josh-65** [comment]
unlblock alvr_server and restart steamVR

**Comment by Emoflia** [comment]
> unblock alvr_server and restart steamVR

tried this since midsummer, steamvr just automatically blocks alvr_server

**Comment by Josh-65** [comment]
It will most likely be a SteamVR issue then. They do have a community support page that you can ask

**Comment by Emoflia** [comment]
UPD: problems after problems
![image](https://user-images.githubusercontent.com/104817815/194713152-a487da18-da2c-4d8d-ac53-8c8edcb5e4e4.png)

**Comment by Emoflia** [comment]
.

**Comment by Emoflia** [comment]
> UPD: problems after problems ![image](https://user-images.githubusercontent.com/104817815/194713152-a487da18-da2c-4d8d-ac53-8c8edcb5e4e4.png)

happens only on versions 18.0.0 and older. in versions above, (for example - 18.2.3) steamvr blocks alvr_server.

**Comment by Emoflia** [comment]
![image](https://user-images.githubusercontent.com/104817815/204000084-a0ab5f99-b992-4c70-91a8-778656ae0bb3.png)
newest nightly version

**Comment by zarik5** [comment]
The javascript dashboard has been replaced with a egui/OpenGL one. Closing.
