### ISSUE TITLE
 127.0.0.1 Not valid...?

### ISSUE THREAD

**Issue by JKCrzWasTaken** [alvr-org/ALVR#1067]
## Description
For some reason, now when I try to apply the 127.0.0.1 IP to my oculus quest 2, it says it's not a valid IPv4 Formatted address.

![image](https://user-images.githubusercontent.com/105897745/169435888-14416f4d-3577-4e12-848d-b3badad88929.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:  Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**GPU**: Intel(R) UHD Graphics Card 630 / NVIDIA GTX 1060

**Audio**: Muted Speaker/Headphones Realtek(R) Audio, so that it plays only on my Quest 2.

### Installation
**ALVR Version**: ALVR v18.2.3

**SteamVR Version**: SteamVR Beta Updated 1.22.12 (Current)

**Install Type**:
- [x] Portable (`zip`)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): OS Built 19043. 1706.

**Comment by parkerlreed** [comment]
Do you accidentally have a space in there? Unable to reproduce just typing it out

![image](https://user-images.githubusercontent.com/841440/169494385-4ce9c956-ada8-4656-95f4-f4586fa4698f.png)
