### ISSUE TITLE
Stuck on loading the stream

### ISSUE THREAD

**Issue by sudoxyz** [alvr-org/ALVR#1069]
hi, i am using a oculus quest 2 and im on arch linux. when i try to use alvr (im using it from the install command `yay -S alvr`) steam vr says "a key component of steam vr isnt working properly"  (error 307) and when on my oculus it is stuck on loading the stream. 

what should i do?

**Comment by parkerlreed** [comment]
Use the portable build. Much less headache and pain (Bundles the proper ffmpeg and all that jazz)

**Comment by sudoxyz** [comment]
I will give that a shot

**Comment by sudoxyz** [comment]
Yo, so I built ffmpeg and exported it to ld_path_library. Alvr from the portable version doesnt display anything (nothing pops up when I run it from terminal) steam is also not popping a error

**Comment by sudoxyz** [comment]
ok, so im using the portable version and it still says 

> "a key component of steamvr isn't working properly." (error 307)

![image](https://user-images.githubusercontent.com/75932948/169557851-64c30197-1306-46ad-8539-720a4eff5000.png)

**Comment by parkerlreed** [comment]
What settings and hardware? Vulkan installed and setup?

**Comment by sudoxyz** [comment]
> What settings and hardware? Vulkan installed and setup?

I'm on arch and I have a 6700xt gpu
I have Vulkan-Radeon installed

**Comment by sudoxyz** [comment]
I will take a photo of the settings soon

**Comment by sethseth6** [comment]
I am also having this issue, and I'm on arch using the portable build with an RX 470 using vulkan-radeon.
