### ISSUE TITLE
Linux workaround for SteamVR error 303

### ISSUE THREAD

**Issue by depau** [alvr-org/ALVR#1082]
## Description

Like many people I was experiencing a "Something is wrong" SteamVR message with error code 303. After some debugging and reverse engineering of steam's `vrcompositor` I determined that they were incorrectly using the 
`vkGetPhysicalDeviceDisplayPropertiesKHR` vulkan API.

This has been reported to Valve and you can see the details here: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/510

Since I've got no response I'd like to let you know about this as well so that maybe a workaround can be implemented (see the patch in the linked issue). This isn't a pull request since I don't really understand the API completely, all I did was determine where it was crashing, see that the Khronos docs say that a null pointer is allowed, see that valve was not expecting one, then patch the vulkan layer to make sure it's not null. Though I can resubmit as a PR if you think it's okay.

After applying this patch SteamVR no longer crashes, and as of today it successfully starts, starts streaming the audio and it seems to correctly track the controllers; however the VR view is glitchy and nothing is displayed in VR. Though that's for another issue :)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement

- Arch Linux
-`alvr-git` AUR package building alvr `94f640b3` + the ugly patch
- Mesa: `22.1.0-1`
- Linux: `5.17.9-arch1-1`

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=95af0fa349

**NOTE!!** Do not consider the nvidia GPU in the report! I use it for VM VFIO passthrough, no driver is loaded, it's not functional on this installation. Only the AMD GPU works.

**CPU**: AMD Ryzen 5 3600X

**GPU**: AMD Radeon RX 5700 XT

**Audio**: pipewire w/ pipewire-pulse...?

```
pipewire
Compiled with libpipewire 0.3.51
Linked with libpipewire 0.3.51
```

### Installation
**ALVR Version**: `94f640b3` (`master` as I'm writing this)

**SteamVR Version**: 1.22.13 (1654131162)

**Install Type**:
- [x] Source (AUR git + my patch)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): I use arch btw :p
ah you may be interested in the fact that I'm on wayland / sway.

**Comment by ayunami2000** [comment]
bump, dont let this issue go stale please

**Comment by dev-sda1** [comment]
Would this also have the potential to fix Error 307?

**Comment by Enovale** [comment]
not stale!

**Comment by ayunami2000** [comment]
N O T  S T A L E

**Comment by crapStone** [comment]
> bump, dont let this issue go stale please

now it won't

**Comment by sllide** [comment]
Thanks for the patch, you are a life saver.

**Comment by Vixea** [comment]
Can anyone confirm this is still an issue?

**Comment by depau** [comment]
I no longer have that GPU, I switched to an NVIDIA RTX 3070 and it's not an issue on that GPU.

I think it's an issue with AMD GPUs though.

<small>*(Since this is no longer an issue for me I'll unsubscribe from notifications, if you need info specifically from me please `@` me)*</small>

**Comment by Vixea** [comment]
Given that I run an amdgpu and have never had this issue and that I haven't seen anyone who has had this issue I'm going to assume it's been resolved at least somewhere that isn't SteamVR etc

**Comment by joselemk** [comment]
uhh I am now getting the error

**Comment by GarmenCZE** [comment]
I am also getting this error after steamvr updated to 2.16, going back to the prevoius build fixed it for me.

**Comment by Alex-Shen-CMU** [comment]
I am getting the same issue with meta quest 3 on cachyos via ALVR, can also confirm that reverting steamvr to previous mar 27 2026 build solves this issues

**Comment by Pi-Man** [comment]
I just started getting this issue recently to, will see if I can downgrade steamvr

**Comment by Pi-Man** [comment]
downgrading steamvr to 2.12.14 (dated March 27th) did indeed work.

**Comment by Pi-Man** [comment]
and yes I also have an AMD GPU

**Comment by EnderActually** [comment]
I'm getting the same issue on my nvidia card, downgrading fixed things.

**Comment by schmilly** [comment]
Can also confirm that this is an issue now. Downgrading work.

**Comment by df4l** [comment]
Downgrading to "previous" version of SteamVR from 28 March 2026 solved both SteamVR error 303 and the extreme stuttering for me. (Linux Mint/Nvidia RTX 4070)

**Comment by glitchifyed** [comment]
The previous version also seemed to solve the issue for me.

**Comment by CaptainDeSync** [comment]
Still a problem. I had a disconnect loop and it wouldn't connect. But downgrading to the previous version fixed this.
