### ISSUE TITLE
Debug build issue: Crash on vr::VRSettings()->GetFloat in OvrHMD.cpp 

### ISSUE THREAD

**Issue by arnoutdekimo** [alvr-org/ALVR#1086]
Hi,

I tried to build ALVR in debug mode to step through the code. I did this by removing the  `--release`  flag  in ` cargo xtask build-server --release `
( https://github.com/alvr-org/ALVR/wiki/Building-From-Source )

This builds, but the resulting build crashes. 
After patching ALVR\alvr\server\build.rs to enable debugbuild of the cpp files, it shows that the crash happens in 

![image](https://user-images.githubusercontent.com/61543845/172823680-3f8f4c9c-9285-45c4-a8f3-472c82997264.png)
![image](https://user-images.githubusercontent.com/61543845/172823926-b1b6c996-82a1-451d-b641-9b938b038733.png)

**alvr\server\cpp\alvr_server\OvrHMD.cpp**

This piece of code seams to be dead, and is probably optimized away in non-debug builds, but crashes otherwise.
When simply removing the code, the debugbuild does work.

Kind regards,
Arnout

**Comment by zarik5** [comment]
Thanks. I have a crashing problem on debug mode too. I'm glad you pin-pointed the issue. Can you make a PR with the fix? You would help me since i'm working on something else at the moment.
