### ISSUE TITLE
How does ALVR mute sound?

### ISSUE THREAD

**Issue by Donovan22** [alvr-org/ALVR#1087]
Hello,
After I installed ALVR (18.2.3) from the AUR repo on Manjaro and successfully got it working, I decided to check the option to "Stream Game Audio" and then, after hearing the audio come through my laptop as well, I enabled "Mute Output While Streaming". 
It did the job, only problem is my front left and front right speakers will not work at all anymore (others like sub-woofer still work).
Does anyone know how ALVR mutes speakers or how I could fix this?
Thanks in advance!

**Comment by zarik5** [comment]
The mute option does not actually work on linux. The code is conditionally compiled only on Windows. I'm not sure how you got any effect out of it.

**Comment by Donovan22** [comment]
That is very odd timing then... I did try muting it in the system settings around the same time. I'm going to assume it isn't ALVR and close this issue for now.

I'll comment here if I find another cause or maybe solution.
Thanks!
