### ISSUE TITLE
Really bad lag with alvr on arch linux

### ISSUE THREAD

**Issue by ikfir** [alvr-org/ALVR#1088]
I'm using arch linux and Oculus quest 2 and wifi 5
GPU: GTX 1070
Ram: 32GB
CPU: Intel i5-7600k

I need help with settings because it lagging so bad and when I try to use other disk with windows and oculus link it worked well

any help?

**Comment by parkerlreed** [comment]
What was the fix?

**Comment by ikfir** [comment]
playing with settings alot took hours but it change for each gpu so if you need help message me at discord

Thebotgame#4812
