### ISSUE TITLE
[LINUX] headset not detected on rig where ALVR previously worked

### ISSUE THREAD

**Issue by Patola** [alvr-org/ALVR#1089]
## Description
ALVR starts SteamVR which says headset not detected.

Larger description: On an Arch Linux installation where in the past I already had ALVR working, when I start it with alvr_launcher, only the "Waiting for server to load..." dialog appears, the ALVR main screen never shows up. SteamVR shows the following message: "Headset Not Detected. Make sure your headset is connected properly, then reset it below."  (of course, resetting doesn't do anything). On SteamVR configuration. startup/shutdown, "choose startup overlays", alvr does not appear, although it _does_ appear in the advanced configuration, manage overlays.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
- [X] google-chrome (and also chromium) are installed, all vulkan libraries are there, there is no firewall on the server, both client and server are version 18.2.3. Server is gc1c251c4, not sure about client hash.
- [X] reinstalled the client apk to match 18.2.3 (it already was at this version)

## Environement
Arch Linux x64, alvr from aur/alvr -- 18.2.3.r0.gc1c251c4-1
Also tried with alvr stable compiled locally (via PKGBUILD/makepkg -si), same result.

### Hardware
My hardware: https://linux-hardware.org/?probe=e33ea31f97

**CPU**:
Ryzen 7 5800H (Note: AMD embedded GPU is disabled via UEFI)

**GPU**:
NVIDIA RTX 3070 mobile

**Audio**:
NVIDIA Corporation GA104 High Definition Audio Controller

### Installation
**ALVR Version**: 18.2.3.r0.gc1c251c4-1

**SteamVR Version**: 1.22.13

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch linux

Note: log of alvr_launcher startup by redirecting stdout and stderr attached
[alvr.log](https://github.com/alvr-org/ALVR/files/8892256/alvr.log)

**Comment by Patola** [comment]
[vrmonitor.txt](https://github.com/alvr-org/ALVR/files/8893010/vrmonitor.txt)
[vrclient_steam.txt](https://github.com/alvr-org/ALVR/files/8893011/vrclient_steam.txt)

**Comment by Patola** [comment]
Well... The Linux Portable tar.gz worked. Weird.

**Comment by traverseda** [comment]
Does chromium run on it's own?

**Comment by korejan** [comment]
> Facing a similar problem, I think I've got it figured out though. Does chromium run on it's own for you? I'm getting issues related to `libSvtAv1Enc.so.0`.

I posted this in the discord server announcements channel:

> 
> For Arch Linux users only, if you have the svt-av1 package installed (you may have it without even knowing), this package had a major version number bump recently (from 0.* to 1.*). If you installed ffmpeg-vulkan (either via AUR or cargo xtask) before this, you will need to rebuild it otherwise you may end up with a missing dependency.
> 
> The result of this is the ALVR launcher waiting forever, this is because the OpenVR driver for ALVR (a shared library loaded by SteamVR/vrserver) will fail to load because of the missing dependency (libSvtAv1Enc.so.0) from ffmpeg-vulkan.

**Comment by Patola** [comment]
> 

Thanks, that was definitely the problem. Recompiling the package with `mkdir tmp && cd tmp && paru -G ffmpeg-vulkan && cd ffmpeg-vulkan && makepkg -si` solved this particular problem of the headset not being detected. Both the headset and controls appear correctly in VR now.

The second problem still persists, though: the alvr interface with the settings and everything does not appear on screen. I have brave (`/usr/bin/brave`), chrome (`/usr/bin/google-chrome-stable`) and chromium (`/usr/bin/chromium`) installed, all of them work when called in the command line, but the ALVR interface does not show.

**Comment by korejan** [comment]
> 
> The second problem still persists, though: the alvr interface with the settings and everything does not appear on screen. I have brave (`/usr/bin/brave`), chrome (`/usr/bin/google-chrome-stable`) and chromium (`/usr/bin/chromium`) installed, all of them work when called via command line, but the ALVR interface does not show.

This happens randomly sometimes and it goes away after a restart, but if it's persistent for you, all I can suggest is you delete _~/alvr/sessions.json_ (you will loose your settings) and possible do steam file verify on SteamVR as well.
