### ISSUE TITLE
程序运行时一直停止在Waitingforservertoload...界面

### ISSUE THREAD

**Issue by fouable** [alvr-org/ALVR#1090]
## Description

在Win7环境下，网络连接使用安卓手机的USB共享网络，我下载ALVR安装包并在此系统上安装，但在运行时，ALVR保持停止在Waitingforservertoload...界面，经过长时间的等待、重启等等行为任然无法使ALVR渡过这个界面
## General Troubleshooting
- I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:  i7-11700@2.50GHz
**GPU**:  RTX3060
**Audio**:

### Installation
**ALVR Version**:  V1.8.2.3
**SteamVR Version**:  V1.23.1
**Install Type**:
- Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):  Windows7旗舰版  Service Pack1

**Comment by jinzouningen** [comment]
To get it work on windows 7, you have to download the software "cff explorer" from the web, and then,you have to go to the folder where you have installed alvr and go to the folder "bin/win64"... There, you have to edit "driver_alvr_server.dll" with cff explorer and go to "import directory", you will see many dll imports. There, you have to rename "api-ms-win-shcore-scaling-l1-1-1.dll" to "user32.dll" and rename  "SetProcessDpiAwareness" to "SetProcessDPIAware" . After that, you save and the software should start without issues. Keep in mind you have to install a chromium based browser like chrome to get it work. With windows 7, it works great alvr thanks to vulkan (I think? It didn't work at all few months ago).

**Comment by zarik5** [comment]
Windows 7 is officially unsupported. @jinzouningen can you please show the source where you found this workaround?

**Comment by fouable** [comment]
> 要使其在Windows 7上工作，您必须从网上下载软件“cff explorer”，然后，您必须转到安装了alvr的文件夹，然后转到文件夹“bin/ win64”...在那里，您必须使用cff资源管理器编辑“driver_alvr_server.dll”并转到“导入目录”，您将看到许多dll导入。在那里，您必须将“api-ms-win-shcore-scaling-l1-1-1.dll”重命名为“user32.dll”，并将“SetProcessDpiAwareness”重命名为“SetProcessDPIAware”。之后，您保存，软件应该可以正常启动。请记住，您必须安装基于铬的浏览器，如chrome才能使其正常工作。使用Windows 7，alvr由于vulkan而工作得很好（我想？几个月前它根本不起作用）。我遇到了一些问题，例如您必须禁用“流游戏音频”，否则它会给我一个错误“找不到设备”

谢谢你，我现在试一试

**Comment by fouable** [comment]
> To get it work on windows 7, you have to download the software "cff explorer" from the web, and then,you have to go to the folder where you have installed alvr and go to the folder "bin/win64"... There, you have to edit "driver_alvr_server.dll" with cff explorer and go to "import directory", you will see many dll imports. There, you have to rename "api-ms-win-shcore-scaling-l1-1-1.dll" to "user32.dll" and rename "SetProcessDpiAwareness" to "SetProcessDPIAware" . After that, you save and the software should start without issues. Keep in mind you have to install a chromium based browser like chrome to get it work. With windows 7, alvr works great thanks to vulkan (I think? It didn't work at all few months ago). There are some issues I encountered, for example you have to disable "stream game audio", otherwise it throws me an error "can't find the device"

api-ms-win-shcore-scaling-l1-1-1.dll 我已经修改了它的名字，但是我在“import directory” 中并没有发现现“SetProcessDpiAwareness”，我需要在哪里去找到SetProcessDpiAwareness呢

**Comment by jinzouningen** [comment]
> Windows 7 is officially unsupported. @jinzouningen can you please show the source where you found this workaround?

There isn't any source, I discovered it by myself.

**Comment by zarik5** [comment]
@jinzouningen can you write detailed instructions (with download links) for your workaround? So we can add it to the wiki.

**Comment by jinzouningen** [comment]
> @jinzouningen can you write detailed instructions (with download links) for your workaround? So we can add it to the wiki.

Yes, as soon as I come back home, I will write the workaround

**Comment by jinzouningen** [comment]
Ok, I will explain how to get it work on windows 7... Keep in mind it is a workaround, so I don't know if it is going to work for you or not... First, you have to install a chromium based browser (like chrome). Then, you have to go to this site and download this software
https://ntcore.com/?page_id=388
after you downloded and installed that, you have to go to the folder where you have installed alvr, in my case it is my drive/programs/alvr/bin/win64
there, you have to open "driver_alvr_server.dll" with cff explorer and go to the section "import directory" as you see in the picture... 
![Immagine](https://user-images.githubusercontent.com/39618686/173605095-c816295f-49e8-44f2-8428-7dd3c333c9d6.png)

There, you have to click to "api-ms-win-shcore-scaling-l1-1-1.dll". Than, rename "api-ms-win-shcore-scaling-l1-1-1.dll" to "user32.dll". After that, you have to rename "SetProcessDpiAwareness" to "SetProcessDPIAware"... 
![a](https://user-images.githubusercontent.com/39618686/173605148-dbf638ed-6a49-4b84-b1b3-c088967d715c.png)

After that, you have to save the changes and the software should start without issues. 

I advise you to disable "stream audio game" in the audio section to avoid an error...
![b](https://user-images.githubusercontent.com/39618686/173605461-342f8602-6a04-40ba-a1c4-e29d24798a4e.png)
 I will try to see if I resolve that, in case, I update this thread with a workaround.

**Comment by zarik5** [comment]
Thanks

**Comment by zarik5** [comment]
This actually looks like a problem with only the dashboard, it's related to resolution scaling. The main ALVR page lists Windows 8 as the minimum required OS because of a limitation of the encoder. Are you actually able to use hardware encoding on Windows 7 or does it fall back to software encoding?

**Comment by jinzouningen** [comment]
> This actually looks like a problem with only the dashboard, it's related to resolution scaling. The main ALVR page lists Windows 8 as the minimum required OS because of a limitation of the encoder. Are you actually able to use hardware encoding on Windows 7 or does it fall back to software encoding?

I don't know, this evening, when I try, I will see it. I think it is hardware encoding, but now I'm not sure lol... When I tried to run alvr months ago, it throws me some errors about video encoding, in fact it didn't work at all, but now it works. Now it is running with vulkan, right? I think it is that it make it works. I'm using "h264 video codec" because "hevc video codec" shows me some green glitches, I have to test it this evening when I have time.
![er](https://user-images.githubusercontent.com/39618686/173613214-0828a5b5-fd0d-4289-be20-f48f5924eef5.png)
Here are my video settings.

**Comment by zarik5** [comment]
@jinzouningen sounds like you are running on the software encoder. Software HEVC is known to now work.

**Comment by jinzouningen** [comment]
> 感谢你，我已经可以正常运行ALVR了！！！非常感谢！！！ @jinzouningen

I'm glad it works :) How does it work? Is it fast?

**Comment by fouable** [comment]
> > 感谢你，我已经可以正常运行ALVR了！！！非常感谢！！！ @jinzouningen
> 
> I'm glad it works :) How does it work for you? Is it fast?

yes!Is very fast!

**Comment by jinzouningen** [comment]
> > > 感谢你，我已经可以正常运行ALVR了！！！非常感谢！！！ @jinzouningen
> > 
> > 
> > I'm glad it works :) How does it work for you? Is it fast?
> 
> yes!Is very fast!

It's a good thing. Can you try to use h265 codec and see if it works for you? Yesterday I didn't have time to test more, try it and see if it works

**Comment by fouable** [comment]
> 

OK,  I'll give it a go.

**Comment by fouable** [comment]
> > > > 感谢你，我已经可以正常运行ALVR了!!!非常感谢!!! @jinzouningen
> > > 
> > > 
> > > 我很高兴它能:)它如何为您工作？它快吗？
> > 
> > 
> > 是的！非常快！
> 
> 这是一件好事。你能尝试使用h265编解码器，看看它是否适合你吗？昨天我没有时间测试更多，尝试一下，看看它是否有效

请问 h265 codec 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器

**Comment by jinzouningen** [comment]
> 请问 h265 codec 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器

I don't know if have undestood your question, but to activate h265 codec, you have to go to settings/video of alvr... There, you can select the codec.

**Comment by fouable** [comment]
> > 请问 h265 编解码器 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器
> 
> 我不知道是否已经不理解您的问题，但是要激活h265编解码器，您必须转到alvr的设置/视频...在那里，您可以选择编解码器。



> > 请问 h265 codec 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器
> 
> I don't know if have undestood your question, but to activate h265 codec, you have to go to settings/video of alvr... There, you can select the codec.

ok

**Comment by fouable** [comment]
> > 请问 h265 codec 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器
> 
> I don't know if have undestood your question, but to activate h265 codec, you have to go to settings/video of alvr... There, you can select the codec.

我正在测试h265编码器，但是在出现SteamVR报错：输入设置错误的问题，原本我使用Unity打包出来的使用SteamVRAPI开发的项目不会出现这个问题导致程序无法运行，我怀疑是win7系统的问题，  我正准备回到Win10系统测试一下这个VR应用程序

**Comment by fouable** [comment]
> > 请问 h265 codec 是如何使用的，我原来的目的是使用ALVR推流Win7PC端的VR应用程序到我的OculusQuest2设备上，我没有使用过h265解编码器
> 
> I don't know if have undestood your question, but to activate h265 codec, you have to go to settings/video of alvr... There, you can select the codec.

经过我的测试，我发现现在在win7上可以正常运行了，但是我的OculusQuest2设备右眼是黑色的，也就是右眼没有渲染任何画面，而左眼则可以正常运行
