### ISSUE TITLE
ALVR server GUI crash after connecting to SteamVR on Linux portable version

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [alvr-org/ALVR#1091]
## Description
Having no luck with [ALVR provided by the AUR](https://aur.archlinux.org/packages/alvr), so I am using the portable version of ALVR server. After SteamVR starts up and shows it detects the Quest 2 headset and controllers, the ALVR GUI shuts off without warning. The Quest 2 still sees the server and is waiting for me to trust it, but it is not possible because the ALVR server GUI refuses to start up again, until the system restarts.

I installed the portable version by downloading from [here](https://github.com/alvr-org/ALVR/releases/download/v18.2.3/alvr_server_linux_portable.tar.gz), then copying all the contents into `/usr/local`. `which alvr_launcher` outputs: `/usr/local/bin/alvr_launcher`

output when running `alvr_launcher > /tmp/debug.log 2>&1`: [debug.log](https://github.com/alvr-org/ALVR/files/8911330/debug.log)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=e00b8334dd

### Installation
**ALVR Version**: 18.2.3

**SteamVR Version**: 1.22.13

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Antergos Linux (Using Arch Linux repos)

**Comment by CyrilPaulus** [comment]
I have a similar problem with the AUR version, the GUI just close once Steam VR is started.

In the meantime I was able to access the UI by browsing the URL displayed in the log.

In your case it's http://127.0.0.1:8082/index.html 

I guess you're probably already doing this, but in the case you've missed it I hope it'll help you.

**Comment by traverseda** [comment]
Does chromium run? Try rebuilding ffmpeg-vulkan.

**Comment by crapStone** [comment]
do you have chromium installed?

**Comment by gareth-anthony-hulse** [comment]
Installing Chromium fixed the issue.
