### ISSUE TITLE
[Quest 1] Unplugging headphones causes all audio to silence

### ISSUE THREAD

**Issue by marc-weber1** [alvr-org/ALVR#1092]
## Description
Steps to reproduce:
- Open ALVR on Quest 1 (or quest 2?), connect it to a server on desktop, make sure an audio device is being routed to the headset, and then unplug headphones from the headset or plug them in

## General Troubleshooting
- [ x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Software
Windows 10 Pro 21H2 build 19044.1766
SteamVR Beta 1.23.2
ALVR Server v18.2.3

### Hardware
AMD High Definition Audio Sound Card (?)
AMD Ryzen 5 2400G with Radeon Vega Graphics 3.60 GHz
Radeon RX 580 Series

**Install Type**:
- [ x ] Packaged (`exe`, `deb`, `rpm`, etc)

**Comment by zarik5** [comment]
This is expected, although maybe it should be fixed.

**Comment by Vixea** [comment]
Wait wasn't this fixed?

**Comment by zarik5** [comment]
This was fixed but in a private fork. The change was not mine so I can't port it upstream just yet. I need to ask for permission.

**Comment by Vixea** [comment]
Zarik have you got permission to do so?

**Comment by zarik5** [comment]
Yeah, I never got around merging it.
