### ISSUE TITLE
ALVR prefers GPU Intel UHD to Nvdia rtx3050？

### ISSUE THREAD

**Issue by osdalong** [alvr-org/ALVR#1096]
Hi sirs：
this week，I played steam vr game （a free game Cyber Car） though ALVR.
My Computer is：
win 10
ALVR Version is 18.3
cpu i7 11800H（with Intel gpu UHD Graphics Xe）
gpu rtx3050

I have found  total latency time is about 200ms . 
encode time about 10ms
decode time about 10ms
translation time about 10ms
render time >100ms

usage
gpu UHD  100%
gpu rtx3050 about 35%

I had disabled the intel gpu UHD .
the usage of gpu rtx3050 is about 60%，total latency time is about 100ms .
Unfortunately，error frame was showed in HMD。ALL frames were wrong.

**Comment by yuckdevchan** [comment]
Have you tried settings the NVIDIA card as the primary display adaptor in device manager or disabling the intel gpu for use as a display adaptor.

**Comment by androettop** [comment]
You can go to the graphics settings in windows 10/11 and set alvr to high performance. 

![image](https://user-images.githubusercontent.com/17651502/176023940-bd3e91cc-12b0-4ded-872c-e1586c0f7645.png)

**Comment by osdalong** [comment]
> Have you tried settings the NVIDIA card as the primary display adaptor in device manager or disabling the intel gpu for use as a display adaptor?

yuckdevchan: Thank you for your reply. after I had disabled the intel gpu, the usage of gpu rtx3050 is about 60%，total latency time is about 100ms. but ALL frames of the game were wrong.
