### ISSUE TITLE
ALVR Linux through USB?

### ISSUE THREAD

**Issue by yuckdevchan** [alvr-org/ALVR#1100]
info:
Arch Linux x86_x64
Quest 2
NVIDIA GTX 1650
i5 9th gen

On linux, for me the only option to use my quest 2 with steamvr is alvr but when running higher spec games my PC doesn't encode the video stream as well for alvr and so doesn't look great when playing better games. (my wifi connection is not the bottleneck)

I'm not sure if this is possible or if it will help my problem but I was wondering how to use ALVR through USB for the video stream and not use wifi for it.

https://github.com/alvr-org/ALVR/wiki/Use-ALVR-through-a-USB-connection

I saw this article but wasn't sure what information I needed for what I want to do or if it's even relevant.

**Comment by MonkeySaint** [comment]
Same as on windows.
adb start-server
adb forward tcp:9943 tcp:9943
adb forward tcp:9944 tcp:9944
