### ISSUE TITLE
ALVR panicked, message "Unavailable"

### ISSUE THREAD

**Issue by ElDavoo** [alvr-org/ALVR#1107]
## Description
ALVR panics at startup

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: i7-10875H

**GPU**: RTX 3070 Laptop

**Audio**: Realtek

### Installation
**ALVR Version**: ALVR v18.0.0-dev04+nightly.2022.06.27
Also tried stable 18.2.3

**SteamVR Version**: 1.22.13

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
W11 22H2 25145.1011

![image](https://user-images.githubusercontent.com/7345120/176250393-80352798-2e3f-4e91-9e8f-4cedd378a1e1.png)
[crash_log.txt](https://github.com/alvr-org/ALVR/files/9003681/crash_log.txt)

**Comment by ElDavoo** [comment]
"It worked" means the app launched. But I keep getting other problems. 
1) The app only launches one time. Which means, when I close and reopen it, I will get a grey screen with edge trying to load 127.0.0.1. With devtools I can see the web server is not responding.

2) Internet stops working on the PC until I disconnect and reconnect from the network

3) Firefox hangs at startup for some reason

4) Clicking "Trust", nothing happens.

Of course, tried with nightly and stable alike

**Comment by ElDavoo** [comment]
The program did actually work with the headset connecting to the router (which is however unoptimal for me). The problem is then when I use the hotspots feature of windows and connect the headset to it. Oculus' Air Link also has similar hanging issues with hotspot, I therefore assume both oculus and alvr are affected by the same bug

**Comment by taotaotyq** [comment]
> I can't believe to say that it worked. Thank you.
> 
> What is going on? It is very strange
> 
> Is there a workaround? You know I kinda need Google Chrome lol

I don't the reason, just had the same issue and used Chrome uninstallation to fix. I also expect the official  patch.

**Comment by ElDavoo** [comment]
> The program did actually work with the headset connecting to the router (which is however unoptimal for me). The problem is then when I use the hotspots feature of windows and connect the headset to it. Oculus' Air Link also has similar hanging issues with hotspot, I therefore assume both oculus and alvr are affected by the same bug

the problem was salved in the recent insider preview build

**Comment by TheRealKamisama** [comment]
> > The program did actually work with the headset connecting to the router (which is however unoptimal for me). The problem is then when I use the hotspots feature of windows and connect the headset to it. Oculus' Air Link also has similar hanging issues with hotspot, I therefore assume both oculus and alvr are affected by the same bug
> 
> the problem was salved in the recent insider preview build

would you mind tell me where I can find a insider preview build? I had the same issue here.

**Comment by ElDavoo** [comment]
settings > windows update > windows insider program
