### ISSUE TITLE
Controller trigger not work in hl alyx

### ISSUE THREAD

**Issue by thankjura** [alvr-org/ALVR#1109]
## Description
Controller trigger works in steamvr home, but not work in hl alyx.
I think bug in 07aa513e1cf85240d34fac27f857b868099919db commit because build from 814618fc4051f352e6553cba8ae7f437b8102fcd is works 

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=cf8784ac23

### Installation
**ALVR Version**:
07aa513e1cf85240d34fac27f857b868099919db and above

**SteamVR Version**:
1.22.13

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Gentoo

**Comment by zarik5** [comment]
This bug has already been reported but I've not found a solution. is the touch sensor of the trigger not working or the value (how much it's pressed) that does not work?

**Comment by thankjura** [comment]
I can't click on any menu item after start game

**Comment by zarik5** [comment]
Which controller emulation are you using? does the problem go away after changing the emulation mode?

**Comment by thankjura** [comment]
"oculus quest 2", but I didn't try to change emulation mode. I'll try changing the emulation mode later

**Comment by thankjura** [comment]
The problem disappears if I set the emulation mode to "Valve Index"

**Comment by thankjura** [comment]
<details>
<summary>emulation mode: oculus quest 2</summary>

https://user-images.githubusercontent.com/2144212/177019573-bd7e0c3b-bc4a-43b2-829b-509c8177c61e.mp4
</details>

**Comment by thankjura** [comment]
The problem has disappeared with the latest commits. Thanks

**Comment by zarik5** [comment]
Thank you for the report!
