### ISSUE TITLE
Have any paln to adapte other  OpenXR device?

### ISSUE THREAD

**Issue by osdalong** [alvr-org/ALVR#1113]
Hi Sirs:

Have any paln to adapte other HMD which has supported OpenXR?

I guess we just need modify the android code ovr_context.cpp.

Thanks.

**Comment by korejan** [comment]
@osdalong I have a fork for a cross-platform (Win, Linux, Android, etc) & device OpenXR based client called ALXR, please check [here](https://github.com/korejan/ALVR/wiki/ALXR-Client). You can also find a link to my dev videos there.

**Comment by osdalong** [comment]
@korejan Glad to hear/see your reply.I will follow you and make some tests on ALXR project.Thank you so much!

**Comment by osdalong** [comment]
@korejan
Hi korejan. I have read the guide of the Alxr, I found the apk need:

Vulkan support, required extensions (check on [vulkan.gpuinfo](https://vulkan.gpuinfo.org/) and/or with [VulkanCapsViewer](https://vulkan.gpuinfo.org/download.php)):
VK_KHR_get_physical_device_properties2
VK_ANDROID_external_memory_android_hardware_buffer
VK_EXT_queue_family_foreign
VK_KHR_sampler_ycbcr_conversion

Unfortunately，My Development board ONLY support OpenGLES(I have check it again with the vendor), And I cant  find any codes in ALVR/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine. 

korejan, is there any way to make Alxr work on OpenGLES? Thank you so much.

by the way, my system is Android 12.

**Comment by korejan** [comment]
> @korejan Hi korejan. I have read the guide of the Alxr, I found the apk need:
> 
> Vulkan support, required extensions (check on [vulkan.gpuinfo](https://vulkan.gpuinfo.org/) and/or with [VulkanCapsViewer](https://vulkan.gpuinfo.org/download.php)): VK_KHR_get_physical_device_properties2 VK_ANDROID_external_memory_android_hardware_buffer VK_EXT_queue_family_foreign VK_KHR_sampler_ycbcr_conversion
> 
> Unfortunately，My Development board ONLY support OpenGLES(I have check it again with the vendor), And I cant find any codes in ALVR/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine.
> 
> korejan, is there any way to make Alxr work on OpenGLES? Thank you so much.
> 
> by the way, my system is Android 12.

Which device is it? I would be surprised that a system which provides Android 12 does not have a vulkan driver, not to say that it does not happen.

ALXR has partial support for OpenGL/ES and it's very barebones there, there's no code for rendering the video stream. I do plan to work on adding support but I don't have an ETA for that.

**Comment by osdalong** [comment]
@korejan
Hi korejan，the device is from luxshare_ict which is a chinese ODM company.

The source code of openxr-client, I have not found out. I guess the code may be Cpp(ALVR/alvr/openxr-client) , but in this diretory, there are only some rust code files. 
is it opened? 

Thanks a lot!
