### ISSUE TITLE
Stage tracking applies for only 5 seconds upon headset awaken

### ISSUE THREAD

**Issue by SkySpnc** [alvr-org/ALVR#1114]
## Description

The stage tracking on the Quest 2 does not apply once the headset has been active for roughly 5 seconds. This serves mostly as a reminder to Zarik,

## General Troubleshooting
- [1] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [1] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement

**CPU**:
AMD Ryzen 5 5600x

**GPU**:
NVIDIA RTX 3090 FE

**Audio**:
Razer Nari Essential, VBAduio VoiceMeeter Potato

### Installation
**ALVR Version**: 18.2.3

**SteamVR Version**:
Beta 1.23.4

**Install Type**:
- [exe ] Packaged
- [No] Portable (`zip`)
- [GitHub Releases] Source

**OS Name and Version**:
Windows 11 Pro 21H2 22000.739

**Comment by zarik5** [comment]
Ok thanks 😁

**Comment by Vixea** [comment]
Is this still relevant I forgot what tracking method we wrnt with
