### ISSUE TITLE
[Pop!_OS 20.04 (Ubuntu-based)] Installing dependencies for building from source removes packages that I don't want removed.

### ISSUE THREAD

**Issue by CodyMarkix** [alvr-org/ALVR#1125]
## Description

Basically, following the instructions for building from source on Ubuntu 20.04, when I paste in the command to install dependencies, apt tells me that:

    The following packages will be REMOVED:
    blender libasound2-plugins:i386 libjack-jackd2-0 libjack-jackd2-0:i386
    wine-stable wine-stable-i386:i386 winehq-stable winetricks`

But blender, wine and winetricks are _quite obviously_ packages I want to keep!

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and ~~successfully completed~~ **did not successfully complete** the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
**OS**: Pop!_OS Linux 20.04 LTS (Based on Ubuntu)

**Package Manager**: apt

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel i5-9300HF (8) @ 2.400GHz 

**GPU**: NVIDIA GeForce GTX 1050

**Audio**: NVIDIA Corporation GP107GL High Definition Audio Controller

### Installation
**ALVR Version**: [Commit 39078e3a27ff097007380609eb7876d81f840742](https://github.com/alvr-org/ALVR/commit/39078e3a27ff097007380609eb7876d81f840742) on the master branch 

**SteamVR Version**: 1.22.13

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Pop!_OS 20.04 LTS

**Comment by crapStone** [comment]
Are these packages in the default repositories of PopOS or did you install custom repositories?

**Comment by infidelus** [comment]
Also seeing something similar (see https://github.com/alvr-org/ALVR/discussions/1148 and https://github.com/alvr-org/ALVR/issues/1150) when trying to install the dependencies:

> The following packages were automatically installed and are no longer required:
>   gstreamer1.0-plugins-base:i386 libavahi-client3:i386
>   libavahi-common-data:i386 libavahi-common3:i386 libcdparanoia0:i386
>   libcups2:i386 libcurl3-gnutls:i386 libcurl4:i386 libdeflate0:i386
>   libdw1:i386 libexif12:i386 libgd3:i386 libglu1-mesa:i386 libgnutls30:i386
>   libgphoto2-6:i386 libgphoto2-port12:i386 libgstreamer-plugins-base1.0-0:i386
>   libgstreamer1.0-0:i386 libhogweed6:i386 libieee1284-3:i386 libjbig0:i386
>   libjpeg-turbo8:i386 libjpeg8:i386 liblcms2-2:i386 libldap-2.5-0:i386
>   libltdl7:i386 libnettle8:i386 libnghttp2-14:i386 libnspr4:i386 libnss3:i386
>   libodbc1:i386 libodbc2:i386 libodbccr2:i386 libopenal1:i386 libopengl0:i386
>   libopenjp2-7:i386 liborc-0.4-0:i386 libp11-kit0:i386 libpcap0.8:i386
>   libpoppler-glib8:i386 libpoppler118:i386 libpsl5:i386 librtmp1:i386
>   libsamplerate0:i386 libsane1:i386 libsasl2-2:i386 libsasl2-modules:i386
>   libsasl2-modules-db:i386 libsndio7.0:i386 libsqlite3-0:i386 libssh-4:i386
>   libtasn1-6:i386 libtheora0:i386 libtiff5:i386 libunwind8:i386
>   libusb-1.0-0:i386 libv4l-0:i386 libv4lconvert0:i386 libvisual-0.4-0:i386
>   libwebp7:i386 libxcomposite1:i386 libxpm4:i386 ocl-icd-libopencl1:i386

> The following packages will be REMOVED
>   libasound2-plugins:i386 libjack-jackd2-0 libjack-jackd2-0:i386 wine-devel
>   wine-devel-i386:i386 winehq-devel

Wine devel is obviously a custom repository to run the few remaining Windows applications that I still rely on, and I presume the sound and jack packages are related.  Definitely not something I'm going to remove.

**Comment by infidelus** [comment]
@CodyMarkix try omitting libjack-dev when you install the dependencies.  I tried this yesterday and have now managed to build the server without losing wine.

I don't know if leaving libjack will have any other negative side effects, but it should enable you to at least connect to your headset.

https://github.com/alvr-org/ALVR/discussions/1148#discussioncomment-3463706

**Comment by CodyMarkix** [comment]
> @CodyMarkix try omitting libjack-dev when you install the dependencies. I tried this yesterday and have now managed to build the server without losing wine.
> 
> I don't know if leaving libjack will have any other negative side effects, but it should enable you to at least connect to your headset.
> 
> [#1148 (reply in thread)](https://github.com/alvr-org/ALVR/discussions/1148#discussioncomment-3463706)

Omitting those helped me install the depenedencies but I have still ran into an issue while building, something related to CUDA.

I'll post the errors later, I'm not at my PC right now

**Comment by infidelus** [comment]
If you look at the link in my post it mentions cuda and how I got around that error.
