### ISSUE TITLE
controller stuttering (video in the description)

### ISSUE THREAD

**Issue by tahawael** [alvr-org/ALVR#1127]
## Description

So i have a quest 2 and everything runs smooth but the controllers, i dont know how to describe the problem but i got a video of it (the problem is on the steam 

https://user-images.githubusercontent.com/62266433/179437441-b868b1e4-35b3-4dbf-a1ed-24bcab4a38d5.mp4

https://user-images.githubusercontent.com/62266433/179438049-876b9a07-5a97-4fba-825d-54c59b0c6515.mp4

Video resolution is 75%, Refresh rate at 120hz, bitrate at 40 and the connection on TCP (also tried UDP and throttled UDP)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Ryzen 3 3100

**GPU**: GTX 1050 2gb

**Audio**: a headset?

### Installation
**ALVR Version**: v18.2.3

**SteamVR Version**: 1.22.13

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 11 22h2 (OS Build 25158.1000)

**Comment by tahawael** [comment]
Any help? :(

**Comment by crapStone** [comment]
You can go to the Discord Server and ask: https://discord.gg/ALVR.
Maybe there someone can help.

**Comment by Rinshun** [comment]
I'm having the same problem.
