### ISSUE TITLE
Head tracks incorrectly during reprojection

### ISSUE THREAD

**Issue by zulc22** [alvr-org/ALVR#1139]
## Description
In my setup, reprojection during lag spikes extremely overcompensates head movement in every program, it feels like it overcompensates the movement of my head by around 4 times, creating a very nauseating effect which doesn't necessarily last a very long time but is regardless very stressful to experience.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: AMD Ryzen 5 4600H

**GPU**: AMD Radeon(TM) RX 5600M

**Audio**: AMD/Realtek High Definition Audio

### Installation

**ALVR Version**: v18.2.3

**SteamVR Version**: beta 1.23.6

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Windows 11 (21H2; 22000.795)

**Comment by zulc22** [comment]
there's no field for it, but I use the SideQuest ALVR client on a Quest 2.

**Comment by crapStone** [comment]
Can you please provide a screenshot of the ALVR server status page?

**Comment by Meister1593** [comment]
I think i know what you mean, and this is very likely to be fixed in v19. Cant promise though, i myself wait to use it (using ALXR)
