### ISSUE TITLE
How to change the code to make the headset shake hands with the server through static IP? I'm a beginner of rust.

### ISSUE THREAD

**Issue by shengzhipeng** [alvr-org/ALVR#1143]
I want to simply add my IP address to the code, but I can't find the place to change the code in Connection.rs.

**Comment by shengzhipeng** [comment]
oh，i added my ip after "send to" on line 29 in ALVR-master\alvr\client_core\src\connection_untils.rs,but it not work. Do I need to change the code of the server？

**Comment by UFeindschiff** [comment]
Why would you want to hardcode your cleint IP? The ALVR server already supports clients with a static IP

**Comment by shengzhipeng** [comment]
> Why would you want to hardcode your cleint IP? The ALVR server already supports clients with a static IP

No,the IP is server IP, not Client IP.

**Comment by shengzhipeng** [comment]
I replaced BROADCAST with my IP in ALVR-master\alvr\client_core\src\connection_untils.rs ,and my server can discovery the headset, but It didn't work after I clicked the “Trust” button
