### ISSUE TITLE
ALVR Source Compile error "linking with cc failed: exit status: 1"

### ISSUE THREAD

**Issue by Setherz6104** [alvr-org/ALVR#1146]
## Description

I'm trying to compile ALVR from source on Ubuntu and I got to "391/392: alvr_server" in the build process, but it ends in error:
https://pastebin.com/gYMWdRHR

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=6fa2b142e4

**CPU**:
AMD Ryzen 7 1700X

**GPU**:
NVIDIA GeForce GTX 1050 Ti Windforce 4 GB

**Audio**:
Onboard (Motherboard: GIGABYTE B450 I AORUS PRO WIFI)

### Installation
**ALVR Version**:
18.2.3

**SteamVR Version**:
1.22.13

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Kubuntu 22.04.1 LTS

**Comment by ColdIce1605** [comment]
rerun this sometimes happens to me too.

**Comment by Setherz6104** [comment]
> rerun this sometimes happens to me too.

I've retried a few times already, also re-downloaded the git to run fresh, no luck :/

**Comment by ColdIce1605** [comment]
what compiler and linker are you using? also the flags

**Comment by Setherz6104** [comment]
> what compiler and linker are you using? also the flags

Rust, this is the command I run (I'm following ALVR documentation):
`cargo xtask build-server --release`

**Comment by ColdIce1605** [comment]
no what c compiler are you using also it seems like your missing some libraries.

**Comment by ColdIce1605** [comment]
also you need to run it with --gpl too

**Comment by Setherz6104** [comment]
> no what c compiler are you using also it seems like your missing some libraries.

Ah sorry dude I'm still new to the whole compiling scene, haha. I'm not sure what c compiler I'm using... how can I figure that out?

I kinda got that idea too, seeing "some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified", but I'm not sure which ones I'm missing

**Comment by Setherz6104** [comment]
> no what c compiler are you using also it seems like your missing some libraries.

I think I'm using gcc

**Comment by ColdIce1605** [comment]
yeah

**Comment by Setherz6104** [comment]
Running build command with --gpl ends in error:
`error: failed to run custom build command for `alvr_server v19.0.0-dev00 (/home/seth/Applications/ALVR/alvr/server)`

Caused by:
  process didn't exit successfully: `/home/seth/Applications/ALVR/target/release/build/alvr_server-c41a6966b8306b8f/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'assertion failed: ffmpeg_path.exists()', alvr/server/build.rs:20:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: command exited with non-zero code `cargo build --release --features gpl`: 101', alvr/xtask/src/build.rs:46:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by ColdIce1605** [comment]
ah forgot do this first
cargo xtask prepare-deps --platform linux --gpl

**Comment by Setherz6104** [comment]
You. Are. My. SAVIOR!

All good, it finished building! Now, do I need any of these files from the git or is the only thing I need for the program "./build/alvr_server_linux"?

**Comment by Setherz6104** [comment]
Ah shoot. I went the compiling route because I had issues with starting ALVR in the portable version, it sits at "connecting to 127.0.0.1:8082 at 127.0.0.1:8082" and never fully starts... that'd be a new issue for me to post though, haha!

Thanks for your help, though, I greatly appreciate it! :)

**Comment by ColdIce1605** [comment]
its build/alvr_server_linux/bin/alvr_launcher
