### ISSUE TITLE
Waiting for server to load...Forever (Fedora 36)

### ISSUE THREAD

**Issue by GitEmulate** [alvr-org/ALVR#1150]
## Description
Using [alvr_server_linux.tar.gz](https://github.com/alvr-org/ALVR/releases/download/v18.2.3/alvr_server_linux.tar.gz)

ALVR just says "Waiting for server to load" and SteamVR says "Headset not detected". Chromium is installed

## General Troubleshooting
- [Yes? No setup wizard on Linux] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [Yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 5 5600x

**GPU**: RX 6700 XT

**Audio**:

### Installation
**ALVR Version**: v18.2.3

**SteamVR Version**: 1.23.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [I used the regular tar.gz not the one labeled "portable"] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Latest update Fedora 36 Cinnamon

![screenshot](https://user-images.githubusercontent.com/102194165/184932310-24faef42-d19f-4db8-b385-6c08ed2ad3be.png)

**Comment by infidelus** [comment]
Pretty much my exact experience of ALVR so far on Linux Mint.  SteamVR doesn't detect my Quest 2 and after using SideQuest to install ALVR it just sits there waiting for server to load which, as you've mentioned, never happens.

**Comment by crapStone** [comment]
Thank you for the log.
It is a known issue that our "portable" builds aren't truly portable and I'm working on a solution for that.
But because ALVR is composed of so many languages this isn't the easiest task.

**Comment by infidelus** [comment]
Thanks.  Does this also include the builds not marked as portable?  alvr_server_linux.tar.gz for example?  They all seem to have the same problem.  Add to that I've been unable to compile from source either - see https://github.com/alvr-org/ALVR/discussions/1148.

**Comment by Espionage724** [comment]
ALVR and SteamVR load fine for me:

- Fedora 36 (5.19.9-200.fc36.x86_64)
- Radeon 6600 XT
- SteamVR beta 1.24.3
- ALVR v19.0.0-dev02+nightly.2022.09.19
