### ISSUE TITLE
alvr panicked >:(

### ISSUE THREAD

**Issue by Blessedsolaris** [alvr-org/ALVR#1151]
## Description

just crashes on my AMD gpu with the message unavalible. 0:wgpu_render_pass_execute_bundles and a lot of other stuff
## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
?
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 5  3600
**GPU**:
ryzen rx 6600
**Audio**:
idk
### Installation
**ALVR Version**:
literally the most up to date at this post
**SteamVR Version**:
most recent.
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11

**Comment by tmp64** [comment]
I noticed that the following happens every 2-5 mins (exact order unknown)
1) ALVR server shows the assertion failure dialog
2) ALVR client on Quest 2 crashes (sometimes the Quest UI freezes for 5-10 seconds after that)
3) Wi-Fi disconnects on Quest 2 side (sometimes)

Pressing the OK button resumes operation. Almost always ALVR client crashes one time after reconnecting, sometimes two times or connects without a crash.

**CPU**: AMD Ryzen 5 3600X
**GPU**: AMD Radeon RX 580 8 GB
**Audio**: Realtek ALC892
**ALVR Version**: 18.2.3
**SteamVR Version**: beta 1.24.1
**Install Type**: Packaged (`exe`)
**OS Name and Version**: Windows 10 21H2 (19044.1889)
**AMD Driver**: 22.8.1, yesterday updated from 22.6.1 (crash happens on both of them)

<details>
<summary>Panic dialog:</summary>

![unknown](https://user-images.githubusercontent.com/20199236/186113046-f5ff3fd8-0a5a-4b74-9882-ee571a896409.png)
</details>

**Comment by Blessedsolaris** [comment]
i will upload my crash log real quick, because that didnt help
[crash_log.txt](https://github.com/alvr-org/ALVR/files/9420384/crash_log.txt)
.

**Comment by Blessedsolaris** [comment]
looks like it wants to work now? i'll close this

**Comment by Blessedsolaris** [comment]
It seems to have come back, help me here.

**Comment by tmp64** [comment]
Try testing [the nightly version](https://github.com/alvr-org/ALVR-nightly/releases). Make sure to update it on both the PC and the headset.

**Comment by Blessedsolaris** [comment]
it works again apparently??? i dont know, but if you connect to http://127.0.0.1:8082/ it brings up the dashboard as normal

**Comment by Blessedsolaris** [comment]
again issue closed because i fixed it.. again.
