### ISSUE TITLE
Not Building (Fedora Based Distro (Nobara)

### ISSUE THREAD

**Issue by Gavin123-code** [alvr-org/ALVR#1153]
Trying to build ALVR to an RPM and I had to edit my /etc/os-release to get progress but i get these errors

2022-08-18 16:23:16 - Info: Preparing Fedora Linux 36 (fedora) to build ALVR server
2022-08-18 16:23:16 - Info: Copying spec file ...
2022-08-18 16:23:16 - Info: Mangling spec file version ...
2022-08-18 16:23:16 - Info: Building tarball ...
2022-08-18 16:23:17 - Info: Building RPMs ...
setting SOURCE_DATE_EPOCH=1627603200
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.nIFAIe
+ umask 022
+ cd /home/gavin/rpmbuild/BUILD
+ cd /home/gavin/rpmbuild/BUILD
+ /usr/bin/gzip -dc /home/gavin/rpmbuild/SOURCES/v19.0.0-dev00.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd /home/gavin/rpmbuild/BUILD
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.vMrG6C
+ umask 022
+ cd /home/gavin/rpmbuild/BUILD
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/home/gavin/rpmbuild/BUILD//home/gavin/rpmbuild/BUILD/.package_note-alvr-19.0.0-0.0.1dev00.x86_64.ld'
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ '[' -f /usr/lib/rpm/generate-rpm-note.sh ']'
+ /usr/lib/rpm/generate-rpm-note.sh alvr 19.0.0-0.0.1dev00 x86_64
/var/tmp/rpm-tmp.vMrG6C: line 40: /home/gavin/rpmbuild/BUILD//home/gavin/rpmbuild/BUILD/.package_note-alvr-19.0.0-0.0.1dev00.x86_64.ld: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.vMrG6C (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.vMrG6C (%build)
2022-08-18 16:23:17 - Critical Error: Failed to build Fedora Linux 36 (fedora) package!

**Comment by ZhenyaPav** [comment]
I'm having the same issue right now. Did you manage to fix it?
