### ISSUE TITLE
WiFi requirement for launching the app prevents from connecting via USB

### ISSUE THREAD

**Issue by phobos2077** [alvr-org/ALVR#1170]
I have an issue ever since I got my Quest 2 with a third-party link cable. Whenever I connect the wire - WiFi will disconnect and not reconnect whatever I do, until I physically unplug the cable. Not sure how common it is, but I never figured out how to fix it.

In my understanding, following the USB guide, the app connects directly to my PC over USB. So why does it require WiFi to launch?

I managed to run the app quickly enough after connecting the cable, running ADB commands, so that WiFi still worked when it launched. Surely enough, after a few more seconds, wifi disconnects, but the ALVR streaming keeps working perfectly. This proves that it doesn't really need a WiFi connection. So why require it in the first place?

**Comment by chowned** [comment]
This is more like a "Discussion" and not an "Issue", you need Wifi so the ALVR on the quest will start searching for the server, then when PC and Quest are connected, you switch the IP address to localhost (or 127.0.0.1). Without Wifi the app will simply close itself.
Then what you do is like saying "Ehi, this USB cable is like a Ethernet cable". I'm doing it simple, but you are creating a port forwarding on both the quest and the pc through USB.
Can it be avoided? Yes. Is it that big of an issue? No.
