### ISSUE TITLE
stuck in white void

### ISSUE THREAD

**Issue by AngelWasTaken** [alvr-org/ALVR#1176]
## Description

when i open ALVR on my headset it just goes straight to a white screen
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
core I5 4570
**GPU**:
GT 1030, ive read multiple statments saying it works
**Audio**:
default
### Installation
**ALVR Version**:
most recent, 1.23? i dont remeber
**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc) 'exe'
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
windows 10, most recent

**Comment by toomuchcodehelp** [comment]
@AngelWasTaken, it's likely that the GT 1030 will work, but most encoders wont work. Try
H.264, without microphone and game audio.

**Comment by AngelWasTaken** [comment]
i figured it out, running as admin made it work just fine
