### ISSUE TITLE
SteamVR Fail in Linux

### ISSUE THREAD

**Issue by DocMAX** [alvr-org/ALVR#1178]
GTX 1660 Ti, Arch Linux

![grafik](https://user-images.githubusercontent.com/5351323/190851826-49dd2de9-3256-4d52-8b02-7145fba9b666.png)

**Comment by Espionage724** [comment]
ALVR and SteamVR load fine for me:

- Fedora 36
- Radeon 6600 XT
- SteamVR beta 1.24.3
- ALVR v19.0.0-dev02+nightly.2022.09.19

**Comment by DocMAX** [comment]
Yeah, for me too with v19

**Comment by chowned** [comment]
But... does it work? Try to check integrity of steam vr via steam.
Working for me on:

- Manjaro
- Radeon 6800 XT
- last version of steamvr and ALVR
Working also via usb.. just try to fix steamvr via settings on steam

**Comment by DocMAX** [comment]
Yes v19 works (h264 only)

**Comment by amidg** [comment]
@Espionage724 what headset are you using it with? I can't get it to work on my system with any ALVR build

- Fedora 36
- 6900XT
- SteamVR (tried various versions)
- ALVR (18.2.3 +  nightly builds)
