### ISSUE TITLE
Using VB-Audio cable for mic sounds scratchy

### ISSUE THREAD

**Issue by OwlCacone** [alvr-org/ALVR#1184]
Using VB-Audio cable to project hmd mic to applications has scratchy/ poppy sounding result. Might be an issue with hardware. I just know that this works fine with any other use of Audio Cables (FL Studio for example) and the solution for Virtual Desktop works great too. I already tried increasing/ decreasing microphone latency to no avail.

**Comment by OwlCacone** [comment]
Issue completely on my end a restart fixed it, closing.

**Comment by OwlCacone** [comment]
Issue completely on my end a restart fixed it, closing.

**Comment by DevanWolf** [comment]
You could have used [Virtual Audio Cable Lite](http://software.muzychenko.net/freeware/vac470lite.zip) instead.
