### ISSUE TITLE
USB connection doesn't work on Linux

### ISSUE THREAD

**Issue by likeproblem** [alvr-org/ALVR#1187]
Hello everyone, today I tried connect with USB, but I did all steps and ALVR still using WIFI, because anything doesn't changed and then I turned off WIFI ALVR is stoped work.
But working with WIFI ok.
I didn't take screenshots, but if needed, I can show.

 [18.2.3 ] Portable
SteamOS 3.0 (Arch Linux), Steam Deck

**Comment by toomuchcodehelp** [comment]
as stated in the wiki,

>ALVR Client (Headset):
WiFi must be turned on and connected, otherwise ALVR will not search for the server.

**Comment by likeproblem** [comment]
> as stated in the wiki,
> 
> > ALVR Client (Headset):
> > WiFi must be turned on and connected, otherwise ALVR will not search for the server.

But before my try with usb I turned WIFI and successful connected, I turned off WIFI to test, usb is working? But, otherwise speed and without turning off WIFI didn't change:(

**Comment by likeproblem** [comment]
Oh, all working, just you need to connect to other wifi + forward ports in opposite way
