### ISSUE TITLE
Failed to run bin/alvr_launcher (Getting GLIBC errors)

### ISSUE THREAD

**Issue by IdlePhoenix1645** [alvr-org/ALVR#1193]
I followed the linux instructions as closely as I could with my limited knowledge. I ended up attempting to run the above file (as the tutorial says) when I get a returned errors. 
brenton@brenton-Reks:/$ /home/brenton/Downloads/ALVR/bin/alvr_launcher 

/home/brenton/Downloads/ALVR/bin/alvr_launcher: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/brenton/Downloads/ALVR/bin/alvr_launcher)

/home/brenton/Downloads/ALVR/bin/alvr_launcher: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/brenton/Downloads/ALVR/bin/alvr_launcher)

/home/brenton/Downloads/ALVR/bin/alvr_launcher: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/brenton/Downloads/ALVR/bin/alvr_launcher)

I run GalliumOS which is an ubuntu base I believe.
Please excuse my limited knowledge of the terminal (I have no clue what I am doing
![Screenshot_2022-10-02_14-22-38](https://user-images.githubusercontent.com/97568136/193472431-243854ab-7506-406a-b938-24b2e208a0ba.png)
)

**Comment by toomuchcodehelp** [comment]
either try the portable release, or make sure GLBIC is up-to-date or installed

**Comment by HoboDev** [comment]
> either try the portable release, or make sure GLBIC is up-to-date or installed

If you mean the AppImage, then it seems to be missing there, too.
