### ISSUE TITLE
ALVR Never opens Dashboard

### ISSUE THREAD

**Issue by ToasterCorporation** [alvr-org/ALVR#1194]
## Description
I open the ALVR Launcher and it shows Waiting for server to load for a moment, then opens SteamVR. The window then closes, SteamVR starts, and nothing else happens. My Quest says to press trust on the dashboard, but the dashboard never opens. I have Chromium installed.

## General Troubleshooting
- [ Y] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [Y ] I read the ALVR Wikis

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

Steam Deck

**CPU**: AMD Custom APU 0405

**GPU**: AMD Custom GPU 0405

### Installation
**ALVR Version**: 18.2.3

**SteamVR Version**: 1.23.7

**Install Type**:

- [Y ] Portable (`zip`)

**OS Name and Version**: SteamOS Holo Version 3.3.1

**Comment by toomuchcodehelp** [comment]
i had a similar experience on solus, but it opened a blank window. I just had to right-click it to show the dashboard.

**Comment by MAZzzeen** [comment]
Bro i was literally asking the same question yesterday what are the 
Anyways just download chromium browser or open alvr from terminal and open the link manually

**Comment by ToasterCorporation** [comment]
Awesome, I was able to launch the dashboard via that IP... Now I can get the headset to connect and track, but there's no stream in the headset.. Just froze on the server is connecting.

https://user-images.githubusercontent.com/53797687/194137219-38d60007-855d-4eba-9f0a-07a4b38eae46.mp4

**Comment by toomuchcodehelp** [comment]
> Awesome, I was able to launch the dashboard via that IP... Now I can get the headset to connect and track, but there's no stream in the headset.. Just froze on the server is connecting.


two things might be responsible.
1. you're doing HEVC software encoding, which sometimes happens after leaving hibernation (mainly nvidia cards).
2. Most likely "stream game audio" is on, which causes this problem 99% of the time for me.

**Comment by ToasterCorporation** [comment]
Neither HEVC or game audio is on according to the dashboard...

**Comment by toomuchcodehelp** [comment]
something odd is happening on the steam deck side of things it seems.
