### ISSUE TITLE
SteamVR Linux - Dashboard does not open

### ISSUE THREAD

**Issue by ryanrambharose** [alvr-org/ALVR#1195]
## Description
The SteamVR dashboard does not open when in VR. (The menu button on the left controller for Oculus Touch controllers.)

Apparently this was an issue with SteamVR for Linux but was closed according to:
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/491

## General Troubleshooting
- [-] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [-] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Not Applicable
**GPU**:
Not Applicable
**Audio**:
Not Applicable
### Installation
**ALVR Version**:
Nightly 2022.10.01
**SteamVR Version**:
1.23.7
**Install Type**:
- [-] AUR
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by EmerickH** [comment]
You need to install the `chromium` packet in order to have the dashboard window.
Alternatively you can just open `http://127.0.0.1:8082` in any other browser (like Firefox) when ALVR is launched to see the dashboard.

**Comment by ryanrambharose** [comment]
I am talking about the SteamVR dashboard I think you are referring to the ALVR dashboard. Here is a picture:

![steamvr-dashboard](https://user-images.githubusercontent.com/91802206/193955353-fe218fda-b50a-4f1b-a79b-94ed22e8c068.jpg)

**Comment by Vixea** [comment]
That wouldn't be a alvr issue then.

**Comment by ryanrambharose** [comment]
Hi @Vixea do you know where I could start to solve this issue?

**Comment by sol8712** [comment]
This issue doesnt seem to be with ALVR.

Some things you can try to fix this in Steam is, switch to the steam client beta and/or steamvr beta, uninstall and reinstall steamvr, verify data of steamvr.
Check the steamvr github for similar issues and report there if none.

**Comment by AndKe** [comment]
How do I use ALVR in Linux at all?  - I see only .exe downloads.

**Comment by ryanrambharose** [comment]
I was using KDE at the time when I reinstalled and switched to GNOME the dashboard opened. Closing because not ALVR related.
