### ISSUE TITLE
Support for OpenComposite?

### ISSUE THREAD

**Issue by stenwt** [alvr-org/ALVR#1196]
Would it make sense to support [OpenComposite](https://gitlab.com/znixian/OpenOVR) as an option instead of relying on SteamVR?

**Comment by korejan** [comment]
It doesn't, OpenComposite redirects game/app using OpenVR API calls to some other target runtime like OpenXR, it can't do anything for OpenVR drivers (SteamVR add-ons) which is what the ALVR server is.

The only way the server could be fully independent from SteamVR (or any other vendor specific runtime) is if the server is re-written as OpenXR runtime itself, either written from scratch or as add a driver for Monado. Then you could use OpenComposite on OpenVR games/apps for the server.
