### ISSUE TITLE
ALVR panicked

### ISSUE THREAD

**Issue by fantasyzhjk** [alvr-org/ALVR#1197]
## Description

when i open ALVR it panicked

![image](https://user-images.githubusercontent.com/57699176/194068754-b4760728-72df-47d1-8408-37843bdbd8fe.jpg)

[crash_log.txt](https://github.com/alvr-org/ALVR/files/9715889/crash_log.txt)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
AMD Ryzen 5 3600X 6-Core Processor 

**GPU**:
NVIDIA GeForce RTX 2060

**Audio**:
default

### Installation
**ALVR Version**:
ALVR v19.0.0-dev03+nightly.2022.10.04 / ALVR v18.2.3
(Both tried)

**SteamVR Version**:
1.24.6

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 22H2(22622.601)

**Comment by fantasyzhjk** [comment]
It seems to be a sound card driver issue
After i reinstalled the driver its okay now

**Comment by zarik5** [comment]
That's interesting, wgpu is only concerned with graphics.

**Comment by InsideCat02** [comment]
I actually have the same issue, I've been watching this for any updates, but I don't have any idea how to resolve this, as I see similar errors, if not straight up variations of them.
