### ISSUE TITLE
Not  connected via usb

### ISSUE THREAD

**Issue by denis-hik** [alvr-org/ALVR#1198]
use:
SIdeloader adb 
ALVR Server 18.2.3

adb command:
`adb forward tcp:9943 tcp:9943`
`adb forward tcp:9944 tcp:9944`

Error in ALVR>
<html>
<body>

18:52:40.598109500 | [WARN] | Handshake: At alvr\server\src\connection.rs:120: At alvr\sockets\src\control_socket.rs:78
-- | -- | --
18:52:41.599227400 | [WARN] | Handshake: At alvr\server\src\connection.rs:120: At alvr\sockets\src\control_socket.rs:78
18:52:42.600717600 | [WARN] | Handshake: At alvr\server\src\connection.rs:120: At alvr\sockets\src\control_socket.rs:78
18:52:43.601815700 | [WARN] | Handshake: At alvr\server\src\connection.rs:120: At alvr\sockets\src\control_socket.rs:78
18:52:44.602480000 | [WARN] | Handshake: At alvr\server\src\connection.rs:120: At alvr\sockets\src\control_socket.rs:78

</body>
</html>

**Comment by Artefact2** [comment]
I also get these warnings when the headset is sleeping (but streaming still works when I wake it up).
