### ISSUE TITLE
Strange behaviour after ~5-10 minutes of gameplay

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [alvr-org/ALVR#1199]
## Description
Getting an Ethernet cable to the PC is too much of a hassle, so its connected to the router (ASUS GT-AX11000 running on Merlin 386.7_2) via WiFi at 5GHz with 160MHz channel bandwidth, same with the Quest 2 headset. It worked correctly before I recently messed around with the settings to see if latency can be improved. Now the headset is only playable for a short amount of time.

Behaviour is different between UDP and TCP. Using UDP results in a visual corrupted mess after ~5-10 minutes. the ALVR Dashboard Monitor reports a huge amount of packet losses, with 'Receive',  'Send', 'Decode' and 'Client Idle' reporting 0ms of latency. Throttled UDP is pretty much the same. When the streaming protocol is set to TCP things start going wrong after roughly 5 minutes of game-play. Movements such as waving controllers in front of the headset or looking around are visually delayed by ~1 minute! When looking directly behind the image is flipped. ALVR Dashboard Monitor again reports 0ms of latency with the previously mentioned, but no packet losses.

Take the VR headset off to look at the game on the plain 2D computer monitor and it appears there are no issues: no visual glitches or delays with movement. Restarting the PC briefly corrects the issues, but only for several minutes of game-play then its back to square one. Restarting the VR headset has no effect.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**PC:** https://linux-hardware.org/?probe=2f0b4a72b3
**Router:** ASUS GT-AX11000
**VR Headset:** Meta Quest 2

### Installation
**ALVR Version**: 18.2.3
**SteamVR Version**: 1.24.6
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Antergos Linux (Using Arch Linux repos)

**ALVR Settings:** https://pastebin.com/raw/ZfjTG0Sa.

**Comment by gareth-anthony-hulse** [comment]
Setting the bitrate to 1Mbps, then restarting SteamVR after the latency starts spiking and it actually becomes somewhat playable. The delay is now near non-existent, but the picture quality is predictably terrible. But why would it run fine with a biterate of 110Mbps without a an issue up until now? Even setting it to 5Mbps results in an unacceptable increase in latency, until I turn PC off and on again.

**Comment by toomuchcodehelp** [comment]
according to the [original ALVR wiki,](https://github.com/polygraphene/ALVR/wiki/Supported-GPU) the GT 1030 isn't supported.

**Comment by gareth-anthony-hulse** [comment]
@toomuchcodehelp I have an AMD Radeon 6900XT.

**Comment by toomuchcodehelp** [comment]
sorry, i thought your router was a gpu.
I do notice that AMD cards don't play well with alvr for whatever reason.

**Comment by gareth-anthony-hulse** [comment]
Adding a config to disable WiFi power save seems to have solved the issue. I created the file `/etc/NetworkManager/conf.d/disable-wifi-powersave.conf` which contains:
```
[connection]
wifi.powersave = 2
```
Then, in a CLI ran `systemctl restart NetworkManager`. Simply restarting should also work.
