### ISSUE TITLE
[Meta] What features are planned for v19? Is there a progress tracker somewhere?

### ISSUE THREAD

**Issue by FriederHannenheim** [alvr-org/ALVR#1207]

**Comment by zarik5** [comment]
There are two main issues that are affecting the v19 release: the controller tracking logic changed and for some people it got drastically worse, and ALXR still does not support the v19 server.

**Comment by korejan** [comment]
> There are two main issues that are affecting the v19 release: the controller tracking logic changed and for some people it got drastically worse, and ALXR still does not support the v19 server.

@zarik5 ALXR has nothing to do with deploying a v19 release, it's not even part of the main repository and you was the one who made the all of the recent changes including controllers. I only changed the default values, you can undo that.

**Comment by zarik5** [comment]
I'm aware that it was me who made the changes for the controller tracking. I'm currently busy with other work and but i welcome anyone else to try a fix.

**Comment by korejan** [comment]
> I'm aware that it was me who made the changes for the controller tracking. I'm currently busy with other work and but i welcome anyone else to try a fix.

Why are you telling people that ALXR is blocking a v19 release, it has nothing to do with it

**Comment by zarik5** [comment]
> Why are you telling people that ALXR is blocking a v19 release, it has nothing to do with it

ALXR is part of the future of ALVR, at least regarding it's technologies, and so making the latest compatible server version go out of step seems like a bad idea. I would rather prefer waiting for ALXR to gain support for the server v19 (at least in a branch) and then making a synched release. This should be a one-time problem anyway, if ALXR adopts the alvr_client_core interface, so platform/common logic can get updated independently.

**Comment by korejan** [comment]
> > Why are you telling people that ALXR is blocking a v19 release, it has nothing to do with it
> 
> ALXR is part of the future of ALVR, at least regarding it's technologies, and so making the latest compatible server version go out of step seems like a bad idea. I would rather prefer waiting for ALXR to gain support for the server v19 (at least in a branch) and then making a synched release. This should be a one-time problem anyway, if ALXR adopts the alvr_client_core interface, so platform/common logic can get updated independently. FYI alvr_client_core is used successfully in the upcoming Google Cardboard support (the progress is promising but it again put in pause because of work).

You're making assumptions, not considering or taking into account various factors and certainly **not** talking on my behalf. I've already said/wrote multiple times I'm not making ALXR compitable with latest changes on the server until v19 has a stable release and been in use for at least a brief amount time. Do not wait for me to make a release, do not try to put this on me for holding the project back.

**Comment by zarik5** [comment]
Ok, it'll be like that then.
