### ISSUE TITLE
HEVC (H265) does not work

### ISSUE THREAD

**Issue by ArtemKuchin** [alvr-org/ALVR#1218]
PICO NEO 3 (chinese version).
Firmware 4.9.3

ALVR on Windows 10 18.2.3 from https://github.com/alvr-org/ALVR/releases
ALXR 0.10.0 from https://github.com/korejan/ALVR/releases
SteamVR beta 1.24.6 (tested others 1.24 release and 1.15)

When i turn on HEVC in ALVR on windows i get this
![Screenshot 2022-10-22 125855](https://user-images.githubusercontent.com/34375843/197340345-fddbe8dd-310e-449a-9b16-3af435901115.png)

After turning it off - everything is okay. 
Seems like PICO NEO 3 client does not support HEVC, but maybe something else is wrong. Don't know where to start digging.

**Comment by korejan** [comment]
hevc is definately supported. which GPU do you have?

**Comment by ArtemKuchin** [comment]
GPU is built in AMD Ryzen 5500 CPU. 
I know, that is is no even close to high end, but it works :) It does have H265 support.

**Comment by korejan** [comment]
It's hard find info on what exactly it is capable of (in terms of encoding), maybe you're using a setting that isn't support (too high resolution for example) or the server might be using a setting that this APU does not support in hevc mode.

**Comment by korejan** [comment]
By the way, not that this will fix the issue as it's a server-side problem but there nightly builds of alxr [here](https://github.com/korejan/ALXR-nightly/releases) I recommend trying as it has important fixes and supports foveated encoding option.

**Comment by toomuchcodehelp** [comment]
this looks _exactly_ what i see when i do software HEVC, i don't know if the APU supports hardware HEVC.

**Comment by toomuchcodehelp** [comment]
there should be a disclaimer when using software hevc to be honest.

**Comment by toomuchcodehelp** [comment]
the 5500 doesn't seem to support HEVC. Try using software h.264 or check your drivers.

**Comment by toomuchcodehelp** [comment]
we need a good solution to this.
