### ISSUE TITLE
H265 software encode

### ISSUE THREAD

**Issue by toomuchcodehelp** [alvr-org/ALVR#1221]
## Description

as seen in #1218, hevc does not work on software encoding.
This can happen if the GPU has no encoding engine (e.g. 6500xt), or the driver errors out (nvidia hibernation), where it will default to software, which causes said problem.
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 5 3600x, intel i5-10500F, Intel pentium silver n5000
**GPU**:
GTX 1660 ti, RTX 3060 ti, 6500xt, Intel UHD 360
**Audio**:
not enabled.

### Installation
**ALVR Version**:
current release and nightly
**SteamVR Version**:
1.18
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [x] Source
affects all the versions.

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Solus, Arch, Pop_OS, Ubuntu, Mint, Manjaro, might be windows too.

**Comment by toomuchcodehelp** [comment]
@zarik5 any plans to fix this?

**Comment by zarik5** [comment]
I'm not concerned with this part of the code, I can't really help you.

**Comment by toomuchcodehelp** [comment]
after doing some testing, i have found that the software encoder does not work on HEVC, no matter the hardware. This is **not** an ALVR issue, rather the encoder itself.
