### ISSUE TITLE
[v19.0.0] Failed to init OpenVR client to update Chaperone boundary! Error: 119

### ISSUE THREAD

**Issue by jacklul** [alvr-org/ALVR#1226]
## Description
SteamVR refuses to start throwing this error: `Failed to init OpenVR client to update Chaperone boundary! Error: 119`
This error happens only on the new v19.0.0 release - no such issue happens if I launch v18.2.3.
Running as administrator does not solve the issue.
Happens with `session.json` from the previous version and when launching without this file present.
It seems to not happen for some time after fresh boot but then eventually starts happening. Fast boot is disabled.

[session_log.txt](https://github.com/alvr-org/ALVR/files/9920767/session_log.txt)
[event.xml.txt](https://github.com/alvr-org/ALVR/files/9920779/event.xml.txt)

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: R5 2600
**GPU**: GTX 1060
**Audio**: Onboard Realtek

### Installation
**ALVR Version**: 19.0.0
**SteamVR Version**: 1.24.6

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Win10 21H1 19043.2130

**Comment by jacklul** [comment]
... and yet the issue is still persisting...

**Comment by zarik5** [comment]
Can you please do some bisection testing in the nightly releases history? Find the first nightly that manifests the issue.

**Comment by jacklul** [comment]
Why didn't I think about doing it sooner! Silly me!
I've tested all nightly builds since [ALVR v18.0.0-dev01+nightly.2022.05.11](https://github.com/alvr-org/ALVR-nightly/releases/tag/v18.0.0-dev01%2Bnightly.2022.05.11) and once I got to [ALVR v18.0.0-dev05+nightly.2022.07.01](https://github.com/alvr-org/ALVR-nightly/releases/tag/v18.0.0-dev05%2Bnightly.2022.07.01) the issue started happening ([ALVR v18.0.0-dev04+nightly.2022.06.28](https://github.com/alvr-org/ALVR-nightly/releases/tag/v18.0.0-dev04%2Bnightly.2022.06.28) is the last working).

**Comment by zarik5** [comment]
Not silly at all :) I've added a note in the issue template. I'll look at it soon.

**Comment by zarik5** [comment]
That's very strange, I can't see any changes related to the chaperone between June 28 and July 1. Can you try to build each commit in between separately to narrow down the issue even more? Also, did you try the latest nightly (v20)? There was a recent change about building the chaperone code when in debug mode.

**Comment by jacklul** [comment]
[ALVR v20.0.0-dev03+nightly.2022.12.20](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev03%2Bnightly.2022.12.20) launches without this issue, I will see if it continues to do so the following days

**Comment by zarik5** [comment]
Great!

**Comment by jacklul** [comment]
While this issue is gone I now encountered a new one - there is like a random chance that launching ALVR freezes my PC and produces audible coil whine coming from the PC... I think at this point I will stay with rock stable 18.2.3 and mark this as solved

**Comment by zarik5** [comment]
If you can, please open another issue and/or find the offending commit as before.
