### ISSUE TITLE
[ALVR v19] AMF SDK Update crashes AMD GPU driver

### ISSUE THREAD

**Issue by Timocop** [alvr-org/ALVR#1228]
## Description
For some weird reason, the newest AMF SDK does not like HEVC HW encoding on my machine at all.
I'm using Adrenalin 22.5.1 stable. Sadly, I'm unable to use any beta drivers because then Video Players in the game VRChat would crash the GPU driver instead *(confirmed by multiple people, I'm not alone in this)*.

The same exact issue happens when using the OBS-Studio HEVC HW encoder in the newest version.
When using AMD HEVC HW, it runs fine for like roughly ~15min and then indefinitely crashes my GPU driver if any 3D application is run. Until I restart my machine.
I have not tested AMD H.264 HW in ALVR v19 but I assume it's the same behavior as in OBS-Studio: It doesn't work, like in ALVR v18.

Older AMF SDKs seem to work perfectly fine. Such as ALVR v18 or OBS-Studio's older AMF plugins.

It would be nice to see commit c5cc8f05675d2ce8d50d460b970ae3893643de19 reverted until AMD patches this driver issue.
I'm surely not the only one that has this issue.

### Hardware
**CPU**: AMD Ryzen 7 5700X
**GPU**: AMD RX 6700 XT

### Installation
**ALVR Version**:

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Windows 10 21H2 (Build 19044.2130)

**Comment by deiteris** [comment]
I think the issue is that latest AMF SDK requires driver 22.7.1+. Could you try updating to any driver version after 22.7.1? Or anything past 22.5.1 causes issues with VRChat video players?
![image](https://user-images.githubusercontent.com/6103913/199970336-384b10ac-2ef1-4600-93ec-a9958454d759.png)

**Comment by Timocop** [comment]
Yes, the current beta driver (and the studio driver) crashes when videos play with the AVPro video player in VRChat. So the driver and the game crashes when I join a world that has a AVPro player in it, which is like every world now. That's why I can't use newer drivers until this crashing issue is fixed. Which has been months.

Is it possible to just use AMF SDK 1.4.24 (or 1.4.23) instead until the next stable driver release? 
I volunteer for testing.

![image](https://user-images.githubusercontent.com/22834512/200014002-43b340f7-b712-484d-abbd-cbc1dc8a0f61.png)

**Comment by Timocop** [comment]
I've build ALVR v19 with AMF SDK 1.4.18 so people like me that are on stable AMD GPU drivers can use ALVR v19.
If anyone is interested in testing, here are the binaries (windows only).
https://cdn.discordapp.com/attachments/721675451969306655/1038637827459665990/ALVR_v19_AMF_1.4.18.7z
_(could not upload the binaries on GitHub due to size limit)_

The server works with those clients: https://github.com/alvr-org/ALVR-nightly/releases/tag/v19.0.0-dev05%2Bnightly.2022.10.29
