### ISSUE TITLE
Encoding Artifacting on Software Encoding

### ISSUE THREAD

**Issue by wihi48** [alvr-org/ALVR#1231]
## Description

It works well with ALVR v18.2.3. I updated to v19 and I'm having this artifacting. It appears for 1 frame for about 5 sec then it updates into another frame and repeats. I tried turning down the resolution to 25% and turning off all the options on the video tab but no change.
[session_log.txt](https://github.com/alvr-org/ALVR/files/9934260/session_log.txt)
[vrcompositor.txt](https://github.com/alvr-org/ALVR/files/9934266/vrcompositor.txt)
[vrmonitor.txt](https://github.com/alvr-org/ALVR/files/9934267/vrmonitor.txt)
[vrserver.txt](https://github.com/alvr-org/ALVR/files/9934268/vrserver.txt)
![alvr client quest-20221103-200553](https://user-images.githubusercontent.com/75482397/199866782-989cc8f2-41e6-4cd8-839f-845379646330.jpg)
![alvr client quest-20221103-213410](https://user-images.githubusercontent.com/75482397/199866787-b31817a9-6a26-4508-ace9-c5abf01e530e.jpg)
![unknown](https://user-images.githubusercontent.com/75482397/199866790-0e37e092-cae4-41ab-a9f8-a4451b50efd1.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: AMD Ryzen 5 5600G

**GPU**: AMD RX 6400

**Audio**: Onboard Realtek

### Installation
**ALVR Version**: 19.0.0

**SteamVR Version**: 1.24.6

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version:** Windows 11 Version 22H2

**Comment by Timocop** [comment]
Try this nightly version (https://github.com/alvr-org/ALVR-nightly/releases/tag/v19.0.0-dev03%2Bnightly.2022.10.09). This was one commit before the AMF SDK update. Also, your GPU doesn't seem to support native HEVC encoding (only decoding). It does support H.264 encoding however try switching to H.264 instead.

**Comment by wihi48** [comment]
> your GPU doesn't seem to support native HEVC encoding (only decoding).
My GPU doesn't have hardware encoding (_I miss typed the title_).

I'm using CPU/software encoding. I have set it to software encode and H.264. I just tested the latest ALVR Nightly and the version you stated but the issue still remain.
