### ISSUE TITLE
Feature Req: Controller only mode 

### ISSUE THREAD

**Issue by admiralzeech** [alvr-org/ALVR#1233]
Hi, I was thinking the new self tracking Quest Pro controllers (especially paired with Quest 2) could be a good substitute for Index Knuckles as an alternative controller for MixedVR set ups.

Could ALVR run in a way where video/audio streaming doesn't happen, but the full controller data is still being transferred?

So you'd have a Quest 2 / Quest Pro sitting on a desk, running ALVR to send controller data for SteamVR.

**Comment by zarik5** [comment]
To do such a thing we need to avoid letting steamvr go into standby. Disabling steamvr standby is sort of broken. This is something i might be working on very soon anyway.
