### ISSUE TITLE
[ALVR v19] Client sends malformed packets to server on controller standby

### ISSUE THREAD

**Issue by Timocop** [alvr-org/ALVR#1237]
## Description
Controllers teleport to some weird location in SteamVR playspace when controllers go standby. 
Either when removing the battery of Quest controllers or opening the Dashboard on the Quest.
Pose position, orientation, velocity even battery life gets zeroed out on the server when the client sends the malformed packet.

However, this does not seem to happen with Quest hand tracking.

#

I have made a server side workaround to avoid teleporting. (bccb1250966a281a04d4a040e66630078dd7e727)

Test when removing batteries and opening quest dashboard:

https://user-images.githubusercontent.com/22834512/200198070-a9aac598-1a1b-46a6-b417-aab830e1f5b8.mp4

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: AMD Ryzen 7 5700X

**GPU**: AMD RX 6700 XT

### Installation
**ALVR Version**: ALVR v19

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 10 21H2 (Build 19044.2130)

**Comment by Timocop** [comment]
This happend on ALVR v18 as well, but it was only orientation that was broken.

**Comment by zarik5** [comment]
Is this a problem with the oculus sdk or with ALVR data handling? Did you check?

**Comment by Timocop** [comment]
Right now i don't have a Android environment so i could not test the client, i only tested the server, will do that later. But from what i've seen, it looks more like a ALVR issue because quest hand tracking does not seem to have this kind of issue.

I tried listening to the incoming motion packets and it seems like the client is reading data still from the controller when the controller is standby for some frames before it stop sending controller data.

I will do some more testing.

[session_log.txt](https://github.com/alvr-org/ALVR/files/9952323/session_log.txt)

In the log you can see at ``20:19:28.252672000`` in the log that the server still receives data from the client even tho the controller is in standby opening the quest dashboard, which contains zeroed data.
#
Just a side note, my Quest 1 still uses Oculus firmware v37, people reported the same with theirs, but with updated firmware. So i doubt its an firmware thing.

**Comment by Timocop** [comment]
I was looking at the old ALVR v18 android code. 
It seems like in v18 it was checking for ``VRAPI_TRACKING_STATUS_POSITION_TRACKED`` before pushing the motion data as seen here https://github.com/alvr-org/ALVR/blob/v18/alvr/client/android/app/src/main/cpp/ovr_context.cpp#L473.
Which is missing in the v19 code.

I guess we should add a check (``VRAPI_TRACKING_STATUS_ORIENTATION_TRACKED`` and ``VRAPI_TRACKING_STATUS_POSITION_TRACKED``) for position and orientation for Quest.
I assume the above return false if the controllers are out of view of the Quest cameras so maybe using  ``VRAPI_TRACKING_STATUS_POSITION_VALID`` and ``VRAPI_TRACKING_STATUS_ORIENTATION_VALID`` would be better?
