### ISSUE TITLE
(Idea) AMD FSR

### ISSUE THREAD

**Issue by toomuchcodehelp** [alvr-org/ALVR#1238]
This is mainly an idea, but **AMD FSR** could add some performance and quality when playing with a lower resolution, especially on the Steam Deck. I guess it would have to run on the client though, which has spotty OpenGL support.

**Comment by r57zone** [comment]
There is a project https://github.com/fholger/openvr_fsr , if can integrate it would be great

**Comment by toomuchcodehelp** [comment]
this looks promising, but **it doesn't have any form of linux support** _(.dll's are for windows only)._ Linux especially needs FSR right now due to the **lack of decent async reprojection and other key vr features** on NVIDIA cards to smooth out frames. I could probably try to get this to work on windows later though.

**Comment by toomuchcodehelp** [comment]
probably shouldn't have closed this- i think that openvr-fsr could be ported to linux later

**Comment by toomuchcodehelp** [comment]
#780 already mentioned this, but i have an idea as to how this could be done:
the client upscales, reducing bandwidth usage and performance associated with lower resolution. I assume that the switch can do it.

**Comment by KlowNJ420** [comment]
I'm pretty sure this has already been attempted. Video decoding is simply to taxing for FSR to be ran. I would love to see another attempt though!

**Comment by DonFlymoor** [comment]
The quest 2 has ~1200 GFLOPs, more then enough for running FSR. Since the GPU isn't being used much ( I assume), then game, encoding, and decoding latency can be greatly reduced in exchange for an amount of up-scaling latency. To reduce noise the encoder would have to be less lossy, but the smaller image size should more then make up for increase in quality.

**Comment by r57zone** [comment]
for the Oculus Quest client, there is no need to do FSR, you need to do FSR on the server so that it does upscaling after receiving the SteamVR image and sends the already updated image to the Quest
