### ISSUE TITLE
Using in-app recenter buttons causes flickering and white flashes

### ISSUE THREAD

**Issue by LuNeder** [alvr-org/ALVR#1246]
## Description
Using in-app recenter buttons causes lots of flickering and white flashes. Pressing oculus's recenter button ends the problem, but sets a wrong position.  (Seems to happen everywhere, tested on Yiffalicious and VR Paradise)

So, when you open a game you're in the wrong place, however if you use the recenter button it starts flickering a lot (on every single slight head movement (even breathing)) together with white lines that flash (lines are round and directed to the screen's edge).

## General Troubleshooting
- [ y] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [y ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

Here, but it's wrong. It detected KDE, but I use XFCE (even tho KDE and gnome are instaled, I do not use them): https://linux-hardware.org/?probe=4e0b0368b8

Here's a Neofetch with correct info:
luana@Luana-Z370XP-SLI 
---------------------- 
OS: openSUSE Tumbleweed x86_64 
Host: Z370XP SLI 
Kernel: 6.0.7-1-default 
Packages: 6290 (rpm), 37 (flatpak), 15 (snap) 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: Xfce 4.16 
WM: compiz 
Terminal: xfce4-terminal 
CPU: Intel i7-8700K (12) @ 4.700GHz 
GPU: NVIDIA GeForce GTX 1070 Ti 
Memory: 3541MiB / 32039MiB 

**Audio**: pipewire / jack

### Installation
**ALVR Version**: v19.0.0-dev02+nightly.2022.09.19 (cannot update because of #1248)

**SteamVR Version**: 1.24.6

**Install Type**:
[] Packaged (`exe`, `deb`, `rpm`, etc)
[y ] Portable (`zip`)
[] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): OpenSUSE Tumbleweed

**Comment by TheGreatMcPain** [comment]
I've ran into this issue quite a bit.  I found that lowering the video bitrate helps.

**Comment by LordJABA** [comment]
I'm having exactly the same issue in almost every game. Will try lowering the bitrate a bit

**Comment by LuNeder** [comment]
> I'm having exactly the same issue in almost every game. Will try lowering the bitrate a bit
> Edit:
> Lowering bitrate does not help. If i use recenter button in steam menu or if there is recenter option in the game head taking stops working, kinda - looks like its countering my head movements with a bit of lag, and sometimes doing random rolls etc. Using quest centring fixes the position tracking. But start position is off center and facing opposite way - menus behind my back

Oh, so the problem is still present on recent versions?

**Comment by LordJABA** [comment]
yes,
I will ask the obvious question(user error?):
what is the proper way to recenter the view while using alvr?
Should using the recenter button from the steamvr bottom bar work? Or maybe
I should not touch it and use oculus native recenter?
If it may be helpful I can record a short video.

sob., 24 gru 2022 o 02:03 Luana ***@***.***> napisał(a):

**Comment by LuNeder** [comment]
> yes,(edit: Version 19.0.0) I will ask the obvious question(user error?): what is the proper way to recenter the view while using alvr? Should using the recenter button from the steamvr bottom bar work? Or maybe I should not touch it and use oculus native recenter? If it may be helpful I can record a short video. sob., 24 gru 2022 o 02:03 Luana ***@***.***> napisał(a):
> […](#)

Well, as I stated, using Oculus’s recenter button doesn’t work. It puts you on the wrong place. The only way of going to the actual center is using the app’s button, but then you get this bug.

**Comment by LordJABA** [comment]
that wold not be such a a huge issue if not that I'm starting facing the opposite way - there is a workaround: turn around. But its not working for siting games

**Comment by TheGreatMcPain** [comment]
I did find that using stationary instead of room-scale within Oculus makes the Oculus re-center button work with Steam VR.

**Comment by Espionage724** [comment]
I'm using  [ALVR v20.0.0-dev03+nightly.2023.01.07](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev03%2Bnightly.2023.01.07) on Linux and re-centering is still seemingly broken (flickering, some kind of mirror or flipping randomly, jitter)

**Comment by LuNeder** [comment]
> Edit: Didn't see the above was from a fork

Hmmmm I don’t think that’s from a fork?

**Comment by Espionage724** [comment]
> > Edit: Didn't see the above was from a fork
> 
> Hmmmm I don’t think that’s from a fork?

Sorry I meant the commit fix above my post. I thought it should have been in official ALVR nighties but that commit with the fix is on a fork.

**Comment by LuNeder** [comment]
> > > Edit: Didn't see the above was from a fork
> > 
> > 
> > Hmmmm I don’t think that’s from a fork?
> 
> Sorry I meant the commit fix above my post. I thought it should have been in official ALVR nighties but that commit with the fix is on a fork.

Ohhh okay! 

Really hope they merge that #1353 pull request (tho I also hope #1248 gets fixed by then so I can use that fix lmao)

**Comment by LuNeder** [comment]
Hey, today I was able to test it again and it was not fixed (on [latest nightly](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev07%2Bnightly.2023.03.13))

I still get flickering and black square screen edges whenever I use the in-app recenter buttons (the black square edges are also visib


le when moving without recentering, but they’re WAY more subtle and there’s no flickering involved on this case. When the recenter button is used, flickering starts and the black space gets bigger and bigger (as if the VR view was actually a regular screen moving in front of me, but with a big delay before being able to do so))

Here's a video, everything here is on the latest nightly: https://user-images.githubusercontent.com/19750714/224873199-f51dc5af-8657-4115-8522-9734b0d8a54d.mp4

**Comment by LuNeder** [comment]
Hmmm, this MIGHT be a problem with proton games (note that I'm not really sure, since I do not have any native linux games with VR support (do let me know if there are any out there for me to try))

See, on SteamVR Home recentering doesn't make anything bad other than it normally does: https://user-images.githubusercontent.com/19750714/224877128-42412696-b539-4635-adb4-e5099d6aa46c.mp4



But after you use an in-game recenter button, the flickering will be (sometimes?) present even when you close the game and go back to SteamVR home: https://user-images.githubusercontent.com/19750714/224877436-963588b7-401e-4487-be10-da9a3ed2c07f.mp4

Lmk if I can find any relevant logs somewhere!

**Comment by TheGreatMcPain** [comment]
> Hmmm, this MIGHT be a problem with proton games (note that I'm not really sure, since I do not have any native linux games with VR support (do let me know if there are any out there for me to try))

Half Life: Alyx has a native Linux version.

**Comment by LuNeder** [comment]
> A workaround that worked for me was using the SteamVR recenter button instead of the in-app one: this puts you in the correct place and doesn’t gets buggy

Nevermind, I guess I was just lucky that day
