### ISSUE TITLE
ALVR v19.0.0-dev04+nightly >2022-10-20 does not start

### ISSUE THREAD

**Issue by svsdval** [alvr-org/ALVR#1257]
## Description
After start white window with message:
This 127.0.0.1 page can’t be found
No webpage was found for the web address: http://127.0.0.1:8082/
HTTP ERROR 404

## Environment
[env.txt](https://github.com/alvr-org/ALVR/files/10049980/env.txt)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=910d921a9d)

### Installation
**ALVR Versions**:
ALVR v20.0.0-dev01+nightly.2022.11.19
ALVR v20.0.0-dev01+nightly.2022.11.13
ALVR v20.0.0-dev01+nightly.2022.10.25
Previos versions like ALVR v19.0.0-dev03+nightly.2022.10.19 works fine.

**SteamVR Version**:
Build Nov 12 2022, 02:45:32
API v020
Version 1668654564

**Install Type**:
appimage & tar.gz

**OS Name and Version**
Debian GNU/Linux bookworm/sid

**Comment by M3TIOR** [comment]
Same here; though this seems like a duplicate of #1248

**Comment by M3TIOR** [comment]
I'm running on `PRETTY_NAME="Linux Mint 20.3"`

**Comment by svsdval** [comment]
interesting, if I extract the appimage (--appimage-extract) then 2022-11-20 and below works fine. But 2022-11-26 and abow crashes after i try to connect. Here is dumps.
[dumps.zip](https://github.com/alvr-org/ALVR/files/10125733/dumps.zip)

**Comment by svsdval** [comment]
Tested 2022-12-12, crached: 
![steamerror](https://user-images.githubusercontent.com/6585839/207411388-93b7870d-4ae1-497e-ba33-7a6f0430cc03.png)
[crash_20221214010208_2.dmp.zip](https://github.com/alvr-org/ALVR/files/10220907/crash_20221214010208_2.dmp.zip)

**Comment by svsdval** [comment]
mb, it wil helps, checked all new version same error, above 2022-11-20, after connection the sound was transmitted, steam assert says: "Thread Watchdog Abort - Render in RenderDistort /+/ 6.086465 second timeout",  all errors says: can't read data from socket

[dumpALVR v20.0.0-dev03+nightly.2022.12.10.zip](https://github.com/alvr-org/ALVR/files/10253744/dumpALVR.v20.0.0-dev03%2Bnightly.2022.12.10.zip)


> Enabling legacy input for system.generated.vrserver
> system.generated.vrserver (oculus_hmd) attempting to load default config from file:///home/svsdval/.steam/debian-installation/steamapps/common/SteamVR/resources/config/legacy_bindings_generic_hmd.json
> system.generated.vrserver (oculus_touch) attempting to load default config from file:///home/svsdval/.steam/debian-installation/steamapps/common/SteamVR/drivers/oculus/resources/input/legacy_bindings_touch.json
> Using existing HMD alvr_server.1WMGH000XX0000
> Read chaperone file /home/svsdval/.steam/steam/config/chaperone_info.vrchap
> Wrote chaperone data to /home/svsdval/.steam/steam/config/chaperone_info.vrchap
> Socket closed
> Unable to read message from socket: 0
> Process vrserver (45129) disconnected (Thread(0x0x7f88a00059f0/0x0x7f)
>
here as txt:
[assert.txt](https://github.com/alvr-org/ALVR/files/10253775/assert.txt)
