### ISSUE TITLE
Suggestion: An option to dump encoded video to disk 

### ISSUE THREAD

**Issue by officialnochill** [alvr-org/ALVR#1258]
This would be a great way to record high quality VR footage without affecting performance, as other methods have a performance hit due to the encoder already being used by ALVR itself.
Being able to save the video that is going to be transmitted to the headset to your PC's disk as well would make for a good no-performance hit recorder with better quality than recording on the headset itself, especially if foveated encoding is disabled on ALVR.

**Comment by zarik5** [comment]
This was implemented some days ago.
