### ISSUE TITLE
Low FPS on GNU/Linux and 3090Ti

### ISSUE THREAD

**Issue by svsdval** [alvr-org/ALVR#1260]
## Description
I checked for Windows there are no problems, everything works fast. FPS=72 holds on refresh rate on client side. But under Debian GNU/Linux FPS drops a lot.... Server side fps jump to 72 and drop to 30-40 (on steam where empty room with the horizon background image and on half life alyx place ), at the same time, both the video card and the processor are "resting" ... And other games on with 'vulkan' render engine same problem. For example OpenGL and Vulkan games i tested with ultra settings fps close in windows and linux, so this isn't a GPU or CPU promblem i think... So what could be the problem? and why Encoder Lanetncy always jump from 30ms to 70ms ?

### Statistics
![image](https://user-images.githubusercontent.com/6585839/202945960-ab0837e2-32d9-4508-9af1-f0b64bfab6e4.png)

### Video settings
![image](https://user-images.githubusercontent.com/6585839/202946449-089b0e3e-8f33-485b-9c76-97895620472e.png)

## Environment
[env.txt](https://github.com/alvr-org/ALVR/files/10049980/env.txt)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=910d921a9d)

### GPU Driver version
510.85.02

### Installation
**ALVR Versions**:
ALVR v20.0.0-dev01+nightly.2022.10.19

**SteamVR Version**:
Build Nov 12 2022, 02:45:32
API v020
Version 1668654564

**Install Type**:
appimage & tar.gz

**OS Name and Version**
Debian GNU/Linux bookworm/sid

**Comment by svsdval** [comment]
Here is testing on my Pico 4 (settings for pico 4) , and Oculus quest 2,

Encoder latency 7-10ms
Transport latency 8-10ms
Decoder latency: 9-12ms
So, does anyone know why the encoder latency is so BIG?

### ALVR settings Windows 10
![alvr_settings](https://user-images.githubusercontent.com/6585839/204087526-1d9fe42f-6638-4a6a-a8bb-6af911334c79.png)

### ALVR stats Windows 10 
![alvr_stats](https://user-images.githubusercontent.com/6585839/204087522-c1ecf7a5-3b69-4eb6-a34c-bf769e95ba2a.png)

**Comment by toomuchcodehelp** [comment]
@svsdval i feel like it's likely that you are encoding on the cpu (Ryzen 7 PRO 4750G), and the gpu isn't doing any work. (apart from game rendering) Check if ALVR is actually doing any intense GPU work, and if not, its likely an NVENC bug.

**Comment by toomuchcodehelp** [comment]
I had the _exact_ same bug with both a GTX 1660 TI and an RTX 3060 TI. The culprit was NVENC dying on boot for me.

**Comment by svsdval** [comment]
cpu is not used, (only loaded steam home with city 17 location )
![image](https://user-images.githubusercontent.com/6585839/204542033-2949381a-1307-4581-9841-61162e18f8c9.png)

**Comment by svsdval** [comment]
Still actual

**Comment by svsdval** [comment]
alvr update to 2023.01.30 and nvidia drivers to 520 solved this problem, still less than in windows but better than before ;)
