### ISSUE TITLE
Typo in GitHub issue labels.

### ISSUE THREAD

**Issue by orowith2os** [alvr-org/ALVR#1269]
In some ALVR issues that are flatpak-specific, they contain the label "flatpack" rather than using the correct spelling of "flatpak."

![image](https://user-images.githubusercontent.com/93224879/203469115-aeb95a8f-ea0c-4ec4-b358-93d95730a025.png)

**Comment by zarik5** [comment]
We don't even have a flatpak build, i deleted the label.
