### ISSUE TITLE
SteamVR error 307

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1271]
## Description
SteamVR error 307 error.
I tried ALVR v19.0.0 release, source build, remove llvmpipe, reinstall steam/steamVR/ALVR drivers, tried all soultion in discord channel (include pins)
But everyone not working and still 307 error.

No warning / error in ALVR Dashboard.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: Ryzen 9 5900HX

**GPU**: Radeon graphics (embedded)

[https://linux-hardware.org/?probe=d96c2be612](https://linux-hardware.org/?probe=d96c2be612)

### Installation
**ALVR Version**: v19.0.0

**SteamVR Version**: 1.24

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [x] Source

I tried all install types.

**OS Name and Version** : Ubuntu 22.04.1 LTS

**Comment by deividaspran** [comment]
Same issue, same OS

**Comment by Kieaer** [comment]
I'm tried change proton version, reinstall/change distro version (ubuntu/debian/centos/arch linux/etc...) but still 307 error.
This can never be solved by the user.

**Comment by Vixea** [comment]
Steamvr problem also we already have a thread for this so I'm closing this issue.

**Comment by deividaspran** [comment]
> 

Coukd you share the link please?

**Comment by Vixea** [comment]
Can you try again on the latest nightly?

**Comment by deividaspran** [comment]
Latest nightly fixed the issue for me.

**Comment by deividaspran** [comment]
Holy shit it works. Even the HEVC (NvEnc) finally works. Well done guys
