### ISSUE TITLE
Server FPS halved when game drops frames & legacy reprojection is turned on

### ISSUE THREAD

**Issue by Kirottu** [alvr-org/ALVR#1275]
## Description
The title says it all, here is a screenshot of the graphs where it is very clear how the server FPS dips.
![image](https://user-images.githubusercontent.com/56396750/203809980-4a67e8af-7e51-4665-acf3-60acbd6e7106.png)
This is quite problematic, as even if the frames drop a bit it isn't a big deal whereas 40FPS VR gameplay really is.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: Ryzen 5 3600

**GPU**: RX 570 8GB

**Audio**: Pipewire

### Installation
**ALVR Version**: latest nightly as of 24.11.2022

**SteamVR Version**: 1.25.1

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by toomuchcodehelp** [comment]
could possibly be a vsync bug
