### ISSUE TITLE
Linux 20.0.0-dev02 unable to creat encoder with NVDIA GPU

### ISSUE THREAD

**Issue by NicolaiVdS** [alvr-org/ALVR#1285]
## Description
Linux 20.0.0-dev02  is unable to create an NvEnc or VAAPI encoder 
```
{"timestamp":"14:18:45.274830001","event_type":{"id":"Log","data":{"severity":"Info","content":"failed to create NvEnc encoder"}}}
{"timestamp":"14:18:45.274944791","event_type":{"id":"Log","data":{"severity":"Info","content":"failed to create VAAPI encoder"}}}
```

Latest stable build (v19) works like it should

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=b6af703e1a

### Installation
**ALVR Version**:
20.0.0-dev02

**SteamVR Version**:
1.24.6

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source
alvr-git aur

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
EndeavourOS

**Comment by NicolaiVdS** [comment]
seems like encoder creations seems to be hit or miss so after some "testing" opening alvr letting it connect and getting into stemvr home then closing did this 10 time only 1 time it did manage to create the hw encoder

**Comment by nowrep** [comment]
Please post logs from SteamVR: set `%command% &> /path/to/log/file` as SteamVR launch command (adjust the logfile path as appropriate).

**Comment by NicolaiVdS** [comment]
> Please post logs from SteamVR: set `%command% &> /path/to/log/file` as SteamVR launch command (adjust the logfile path as appropriate).

here you go https://bitwarden.nvds.be/#/send/anoZcCbxSZ2DOMC4-rs06A/TmXiXLLKK7R0SCHLif1Xig

**Comment by NicolaiVdS** [comment]
thanks to @nowrep turned out that my bitrate was at 800 mbps wich is way to high
