### ISSUE TITLE
ALVR Cardboard client crashing, previous version works.

### ISSUE THREAD

**Issue by AMDBartek** [alvr-org/ALVR#1289]
## Description
Sorry for not following the issue template however the issue does not affect the server-side but the client-side.

The ALVR cardboard client is crashing for me after I grant permissions on the latest nightly version (v20.0.0-dev02+nightly.2022.11.30) however if I switch back to nightly version v20.0.0-dev01+nightly.2022.11.20 (latest one that works for me) it launches and works fine.

The phone I am using is a Google Pixel 6 with CalyxOS Android 13 on it.

Sidenote: I do not own any Oculus headsets so I cannot help with testing Oculus versions.

**Comment by zarik5** [comment]
Thank you for the report. That's interesting, I actually put that project on hold since the performance was so bas i was debating if it made sense to continue on it. I am thinking on switching to the old Daydream SDK instead of the Cardboard SDK since the former has support for reprojection.

**Comment by AMDBartek** [comment]
That's understandable, I just wanted to use the Cardboard client for a quick test to see how it works.

While the older cardboard client does open and "works", it glitches when it gets the stream from my computer (can provide screen recording). Tested on both Nvidia and AMD GPUs.

**Comment by AMDBartek** [comment]
[alvr_bug.webm](https://user-images.githubusercontent.com/46637209/205096289-48124d0f-ae20-438f-a999-c7231859bfab.webm)

**Comment by TheBricktop** [comment]
on my s8 it works pretty good, stream is fast as heck and responsive had to disable foveated encoding cause it was sending one pixel of video to my phone but other than that its best
