### ISSUE TITLE
what does ''NVDIA proprietary driver" mean? 

### ISSUE THREAD

**Issue by StevenKeXu** [alvr-org/ALVR#1298]
"Supported GPU Configurations 
AMD using radv is known to work, with hardware encoding
AMD using amdvlk does not work
NVIDIA using proprietary driver works, with hardware encoding.
Intel is untested"
Does proprietary driver mean Nvdia official drivers  here  https://www.nvidia.com/Download/driverResults.aspx/196723/en-us/ ?

**Comment by StevenKeXu** [comment]
> Yes, as opposed to nouveau which are the open source nvidia drivers. You should install those drivers via your distros package manager though. (apk, pacman, etc.)

thanks!

**Comment by Vixea** [comment]
As this has been answered I think its safe to close. ;)
