### ISSUE TITLE
Portable version for v19

### ISSUE THREAD

**Issue by Akhundzada** [alvr-org/ALVR#1300]
Hello. 
Sorry for possible incorrect placement of the issue. 
I have SteamDeck and would like to launch ALVR on it. Portable v18+ worked just fine. 
v19 doesn't has portable version, and simple linux version is not being worked correctly (stuck on launching). 

Client on Quest2 doesn't connect to the older server (Client v19, Server v18+), so this is the main issue.

**Comment by sol8712** [comment]
The latest version of ALVR that works on Linux seems to be the nightly from November 20th https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev01%2Bnightly.2022.11.20 i could not get the v19 release to work.
Make sure you uninstall Steamvr completely before you go through the ALVR install instructions again. 

Im on Pop! OS 22.04 (Ubuntu)
