### ISSUE TITLE
Changing playspace from couch to roomscale causes steamvr to restart

### ISSUE THREAD

**Issue by kruemmelbande** [alvr-org/ALVR#1301]
When i leave my couch playpace, and change it to roomscale, alvr restarts, causing steamvr to restart as well.
I dont think this is intended behaviour.

ALVR version 19
Steamvr version 1.24.6
Meta Quest 2
OS: windows 11 pro 22H2
CPU: Ryzen 5 5600x
RAM: 16gb 3200mts
GPU: GTX 1080

**Comment by TYTheBeast** [comment]
Having a similar correlated issue: turning off passthrough restarts ALVR and SteamVR, similarly to what's happening here.
