### ISSUE TITLE
[ERROR] Message: "Unavailable"

### ISSUE THREAD

**Issue by newhajinyoon** [alvr-org/ALVR#1303]
![image](https://user-images.githubusercontent.com/61103309/207038400-43c8cc43-54b4-4227-a1c3-3109130cc329.png)
`
20:50:45.197781100 [ERROR] Message: "Unavailable"
Backtrace:
   0: wgpu_render_bundle_insert_debug_marker
   1: <unknown>
   2: wgpu_render_bundle_insert_debug_marker
   3: wgpu_render_bundle_insert_debug_marker
   4: wgpu_render_bundle_insert_debug_marker
   5: wgpu_render_bundle_insert_debug_marker
   6: wgpu_render_pass_execute_bundles
   7: wgpu_render_pass_execute_bundles
   8: <unknown>
   9: HmdDriverFactory
  10: HmdDriverFactory
  11: <unknown>
  12: wgpu_render_bundle_insert_debug_marker
  13: BaseThreadInitThunk
  14: RtlUserThreadStart
`

why does this happens

**Comment by kuznetz** [comment]
Same error.
How does this happen:
1. ALVR starts to dashboard screen
2. waiting to start steamVR 2-3 sec
3. steamVR not starts, alvr is crush
If shutdown steam and start alvr, it automaticly start steamVR and sometimes (with 1-5 attempts) ALVR successfuly starts

**Comment by deiteris** [comment]
Try nightly version, it should have a more detailed error now.
