### ISSUE TITLE
Bitrate on AMD capped to 100Mbps

### ISSUE THREAD

**Issue by Rinshun** [alvr-org/ALVR#1308]
If I select any bitrate value above 100Mbps, it automatically reverts to about 20Mbps on AMD cards using the latest drivers (22.11.2).
If set to 100, it works properly.

## General Troubleshooting
- [Yes] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [Yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Ryzen 1600

**GPU**: AMD RX6700XT (22.11.2 Drivers)

### Installation
**ALVR Version**: 19

**SteamVR Version**: 1.24.6

**Install Type**:
- [Yes] Packaged (`exe`, `deb`, `rpm`, etc)
- [No] Portable (`zip`)
- [No] Source

**OS Name and Version** Windows 10 (22H2)

**Comment by Vixea** [comment]
Thats because AMF has it capped at 100 nothing ALVR can do.

**Comment by deiteris** [comment]
Related issue in AMF repo:
https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/364

**Comment by Rinshun** [comment]
While we wait for AMD to fix it, what are the best options to save bandwidth and improve visual quality? Did you guys have any luck with foveated encoding, color correction and pre processor component?

**Comment by Vixea** [comment]
Wdym any luck with foveated encoding and color correction doesn't change the bitrate requirements or anything to do with bitrate pre-processor only works with out 10 encoding i use 10 bit so I have no idea.

I can give you recommended settings if you would like?

**Comment by Rinshun** [comment]
Now that you mentioned it, I see it doesn't really make any sense for foveated encoding. It's the encoder that is limited to 100Mbps not the wifi bandwidth.

But the color correction and other settings, which ones can be used to improve visual quality without increasing the encoder bitrate usage? (or reducing it). If you can give me recommended settings It would help me a lot.

**Comment by deiteris** [comment]
If you're using the latest drivers, then pre-processor may significantly reduce the bitrate usage (and give better picture in general, but possibly blurry in some cases) but at the cost of higher GPU load. Color correction includes sharpness that can help to improve visual clarity and it's a simple shader that doesn't add any load.

**Comment by Artefact2** [comment]
CQP mode supposedly isn't affected by the bitrate cap, maybe it's worth testing in addition to CBR/VBR modes.

**Comment by Espionage724** [comment]
I was using 22.11.2 with HEVC and 200-500 Mbps transferred over from my PC to the Quest 2: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/364#issuecomment-1374635618

I used ALVR [nightly 2023.01.07](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev03%2Bnightly.2023.01.07) and Quest 2 with V47 firmware. ALVR statistics showed 200-500 Mbps bitrate, and Task Manager showed 200-500 Mbps load.

**Comment by deiteris** [comment]
A reminder that ALVR currently uses constant bitrate by default, and filler data is inserted with AMD. While it may actually show the said bitrate, effective bitrate will still be 30mbps and the rest is useless raw bytes.

**Comment by bernek9000** [comment]
> 

This is horrible news to hear if we get filler data. What driver is recommended then ? I use 22.2.3 ?

**Comment by zarik5** [comment]
Since driver version 23.2.2, the issue seems to be fixed 🎉
