### ISSUE TITLE
Quest Touch Pro controllers with Quest 2 headset

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [alvr-org/ALVR#1310]
Will the Quest Touch Pro controllers and Quest 2 headset work together with ALVR? And if so, is it seamless or will some settings need changing in the dashboard? Just want to know before deciding on buying them if they are worth it.

**Comment by zarik5** [comment]
I don't think this concerns ALVR at all. I didn't try this configuration myself, but ALVR works equally good on the Quest 2 and Quest Pro.

**Comment by gareth-anthony-hulse** [comment]
Got the Quest Touch Pro controllers and can confirm they work perfectly fine with the Quest 2 headset.

**Comment by zarik5** [comment]
Thanks for the report!
