### ISSUE TITLE
V19.0.0 triggers unwanted AFK when playing VRChat

### ISSUE THREAD

**Issue by TamakiRuri** [alvr-org/ALVR#1313]
It seems like at v19.0.0, ALVR will turn on AFK mode when the headset is not moving. However, its not ideal when you are lying down (like when watching videos) in VRChat because your avatar will suddenly turn to afk mode and block your view. It didn’t happen at v18.2.3 and I can’t find any settings to turn it off. This doesn’t happen at AirLink either.

Edit: added environment just in case.
Environment
Hardware
CPU: i7 11800H
GPU: RTX 3060 Laptop (MUX on dGPU mode)

Installation
ALVR Version: v19.0.0
SteamVR Version: 1.24.6

Install Type: Packaged (exe)

OS Name and Version Windows 11 (22H2) Build 22621.963

**Comment by Timocop** [comment]
Try disabling "Pause VR when headset is inactive" in SteamVR settings in ``Video``. Advanced Settings need to be enabled.

**Comment by TamakiRuri** [comment]
> 

Thanks for the reply, but it doesn’t work. This happens only when using V19.0.0 version of ALVR, V18.2.3 or AirLink doesn’t have this behavior

**Comment by zarik5** [comment]
@TamakiRuri can you please try nightly releases? do a bisection testing.

**Comment by zarik5** [comment]
I see what's happening. my "Input rewrite" PR forgot to handle the proximity sensor (nightly.2022.06.26), while later I removed the input completely from the steamvr driver on steamvr (nightly.2022.07.01). I think the solution is to add back the sensor input and force it to "true".

**Comment by Timocop** [comment]
Thats funny, i have been using v19 for months now. I probably never had the afk issue because i turned off vrc afk detection. The only thing i did noticed however was when no game is running and by not moving the HMD, SteamVR will go standby and stop transmitting data to ALVR client resulting in a cyan screen on my oculus. Never happened in games however.

**Comment by TamakiRuri** [comment]
> @TamakiRuri Ok, I pushed a commit with the fix, but's it's untested (i'm in a hurry). let me know how it goes with the next nightly.

@zarik5 I tried it and it works just fine. Is it okay to close this issue now?

**Comment by Vixea** [comment]
yes
