### ISSUE TITLE
endeavourOS steamvr fail 307

### ISSUE THREAD

**Issue by GekkoinenGittiAcco** [alvr-org/ALVR#1315]
## Description
cant connect, headset not showing up. steamvr fail 307
i tried nightly too. didnt work.

## General Troubleshooting
- [ x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
x11, 6.0.12-arch1-1
### Hardware
**Note**: https://linux-hardware.org/?probe=262a879a99

**CPU**:ryzen7

**GPU**:3060ti

**Audio**:

### Installation
**ALVR Version**: alvr-19.0.0.r0.g1215da95-1

**SteamVR Version**: 1.24.6

**Install Type**:
-aur
**Endeavouros

**Comment by iinattr** [comment]
me either'

**Comment by Vixea** [comment]
please try the nighties that should solve your issue.

**Comment by ModestTom** [comment]
Does not work for me either, even after trying nightly. SteamVR always fails with 307 error code

**Comment by KawaiiDinosaur** [comment]
Tried both nightly and stable appimages and have the same issue
