### ISSUE TITLE
Headset reconnecting gives a "Only one usage of each socket addr..."

### ISSUE THREAD

**Issue by elimerl** [alvr-org/ALVR#1322]
## Description

When you put your headset down and then put it back on, the ALVR client repeatedly auto reconnects and then says "The server disconnected.". On every auto-reconnect attempt the server gives an error about "Only one usage of each socket address".

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Windows 10 Home Build 19044

### Hardware

**CPU**: i7-10750H

**GPU**: GTX 1660 Ti

**Audio**: Irrelevant

### Installation
**ALVR Version**: v19

**SteamVR Version**: beta 1.25.2, might happen on stable too, will check

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): 21H2 Windows 10 Home

Thanks for any support, and the awesome project!

**Comment by elimerl** [comment]
Still happens on nightly 2022-12-24:

![image](https://user-images.githubusercontent.com/32183908/209454263-ab857826-2fcc-4078-8fbf-966fa3bd540c.png)

**Comment by elimerl** [comment]
I tried to build it myself but [bindgen](https://crates.io/crates/bindgen) is erroring because there's no libclang or something so if anyone else can reproduce it would be great. Thanks

**Comment by zarik5** [comment]
For your original issue, i think a restart of the PC should fix it. For compilation, follow the instructions in the wiki. You need to run `cargo xtask prepare-deps` which will also install libclang.

**Comment by elimerl** [comment]
Yeah restarting the PC or just SteamVR fixes it but then my game closes and this happens every time the headset is taken off, so it's hard to have a longer session. But it still streams fine until I take off the headset and it disconnects. Thanks, and happy holidays :)

**Comment by deiteris** [comment]
I think this should fix it https://github.com/alvr-org/ALVR/pull/1323.

**Comment by elimerl** [comment]
That PR seems to work fine, so I'm closing. Thank you guys for the extremely fast response on a holiday!
