### ISSUE TITLE
SteamVR fails with code -203 on Fedora

### ISSUE THREAD

**Issue by owu-1** [alvr-org/ALVR#1332]
## Description

SteamVR fails with code -203 and the Oculus Quest 2 screen is stuck on "The steam will begin soon Please wait..."

I have found that version ```ALVR v20.0.0-dev02+nightly.2022.11.26``` is the first nightly build to have this problem

```
ALVR v20.0.0-dev03+nightly.2022.12.27 - Fails on Laptop and Desktop
ALVR v20.0.0-dev02+nightly.2022.12.01 - Fails on Laptop
ALVR v20.0.0-dev02+nightly.2022.11.28 - Fails on Laptop
ALVR v20.0.0-dev02+nightly.2022.11.27 - Fails on Laptop
ALVR v20.0.0-dev02+nightly.2022.11.26 - Fails on Laptop and Desktop
ALVR v20.0.0-dev01+nightly.2022.11.20 - Works on Laptop and Desktop
ALVR v20.0.0-dev00+nightly.2022.10.30 - Works on Laptop
```

Running on Laptop as: ```__NV_PRIME_RENDER_OFFLOAD=1 ./ALVR-x86_64.AppImage```
Running on PC as: ```./ALVR-x86_64.AppImage```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
Laptop: https://linux-hardware.org/?probe=d1f63174e4
Desktop: https://linux-hardware.org/?probe=7aab4546f6

### Installation
**ALVR Version**: ALVR v20.0.0-dev03+nightly.2022.12.27

**SteamVR Version**: 1.24.7

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Fedora Linux 37 (Workstation Edition)

**Comment by deividaspran** [comment]
I have the same issue. Ubuntu 22.04.1, GPU: RTX 2060
I was only able to run 19.0.0 stable
