### ISSUE TITLE
ALVR Client on Pico 4 does not display any Interface

### ISSUE THREAD

**Issue by Omes-exception** [alvr-org/ALVR#1337]
I recently got my Pico 4 and wanted to use ALVR because streaming Assistant refused to Work, But when i installed the 
alxr-client-pico.apk from https://github.com/korejan/ALXR-nightly/releases/tag/v0.10.0%2Bnightly.2022.12.28
it did not display anything other than the two default cubes and the Alvr server also didn't detect it.
![Screenshot_com alvr alxr_client_2022 12 29-13 54 05 965_666](https://user-images.githubusercontent.com/94001672/209954129-cbf2b3c5-8b84-448d-8a4d-df77b16022dd.jpeg)

**Comment by zarik5** [comment]
The Pico 4 is not currently supported by ALVR. Support is in progress. You may want to open an issue on the ALXR repo for now instead.

**Comment by dunconio** [comment]
> I recently got my Pico 4 and wanted to use ALVR because streaming Assistant refused to Work, But when i installed the alxr-client-pico.apk from https://github.com/korejan/ALXR-nightly/releases/tag/v0.10.0%2Bnightly.2022.12.28 it did not display anything other than the two default cubes and the Alvr server also didn't detect it. ![Screenshot_com alvr alxr_client_2022 12 29-13 54 05 965_666](https://user-images.githubusercontent.com/94001672/209954129-cbf2b3c5-8b84-448d-8a4d-df77b16022dd.jpeg)

ALVR-v18.2.3 does work for me with Pico 4 and the ALXR-nightly pico client apk.  Haven't got sound streaming from PC though.
