### ISSUE TITLE
ALVR not working on Arch Linux (EndeavourOS)

### ISSUE THREAD

**Issue by Squidtito** [alvr-org/ALVR#1341]
I'm getting the error
SteamVR not installed: make sure you launched it at least once, then close it

I've done the instructions, it's not working still. It might be that I installed Steam through flatpak, but I'm not sure.

**Comment by elimerl** [comment]
You probably need to install steam "normally" as [recommended by Arch](https://wiki.archlinux.org/title/Steam), because flatpak sandboxes stuff into its own file system I think.

**Comment by Squidtito** [comment]
It worked, thanks ^^

**Comment by jarrard** [comment]
I was hoping this was fixed for flatpak.  Maybe a ALVR for flatpak can be released at some point.  Now I gotta unbundle my flatpak steam environment, damn.

**Comment by galister** [comment]
@Squidtito you might want to check out https://github.com/CharlieQLe/alvr-flatpak

**Comment by jarrard** [comment]
Cheers, will do. I've gone back to normal Steam for now just to test VR out and ensure it works. Hopefully AUR ALVR-git works with PICO-4.
