### ISSUE TITLE
Problem With Windows 7 avlr 2.4.0 Alpha:1 Support

### ISSUE THREAD

**Issue by STEEPERCREVE** [alvr-org/ALVR#1342]
## Description
I don't post issues in github much so I hope I didn't mess this up severly.

I open it [ALVR] and connect to my headset. It successfully connects, but says servers are down in the top right. I installed all drivers. As a preface I am running this on a fairly old machine and I may just be out of luck but I hope not. I Assume it would work fine if I could connect to the servers; the top right of the screen says: "Start Server" And "Server Is Down"

## General Troubleshooting
- [ ✔️ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ✔️ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Intel Core i7 920
**GPU**:
Nvidia Geforce 2070 Super
**Audio**:
N/A
### Installation
**ALVR Version**:
2.4.0 Alpha1
**SteamVR Version**:
1.24.7
**Install Type**:
- [ `exe` ] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Name: Windows 7 Home Premium
Ver: 6.1.7601 SP1 Build 7601 (Would've installed oculus app and used airlink, but have a glitch with the service packs and incompatability. As you can probably tell, I don't have much to work with on this old machine.)

**Comment by zarik5** [comment]
Please update your OS, ALVR does not support Windows 7 anymore.

**Comment by STEEPERCREVE** [comment]
Actually I got everything to work. Only one problem (which someone else is also having btw, not on windows 7) which is that the servers wont work and can't connect to the IP with the localhost config page. I'll post the file here and hopefully you or someone else can help, as it's not just me having this problem. Also, can't update to win 10. ![Capture](https://user-images.githubusercontent.com/99853221/210273157-f946d3bc-acc2-4686-aa3e-e4057bf20712.PNG)
ect

**Comment by parkerlreed** [comment]
Just because "another person" has something similar doesn't mean it's the same issue. 

Windows 7 is not supported anymore. Minimum OS as noted in README is 8 and even that's not ideal.

Microsoft still doesn't give much of a shit if you just install Windows 10 on top of 7. It will still use the old key.

**Comment by STEEPERCREVE** [comment]
I am aware that it is not supported. I believe it is a problem with something else, possibly the router. 2 other people from your discord server were working with me on this and we almost got it working. Also, I can't upgrade to windows 10 AT ALL because of hardware related problems and, because my dad still makes my money choices, I won't be able to in the forseeable future.

**Comment by deiteris** [comment]
>I can't upgrade to windows 10 AT ALL because of hardware related problems

Why do you think you can't? If it's due to CPU, then Core i7 920 should work with Windows 10 just fine.
