### ISSUE TITLE
Terrible FPS issues when using Quest Pro controllers on Quest 2 headset

### ISSUE THREAD

**Issue by Nyabloody** [alvr-org/ALVR#1378]
## Description
When using using Quest Pro controllers with ALVR there is a major FPS impact. Be it with any versions of ALVR currently. Curiously I noticed that using ALVR over USB does seems to improve a bit the FPS but the issue is still there and it's unplayable. The problem is gone as soon I was using Quest 2 controllers again.

## Steps to reproduce the issue
1. Fresh install of ALVR (any versions)
2. Initial setup and leaving default settings
3. Connect headset
4. Watch the beautiful FPS mess in SteamVR

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel i7-11700KF

**GPU**: RTX 3080Ti

**Audio**: 

### Installation
**ALVR Version**: Any

**SteamVR Version**: 1.24.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 22H2 build 19045.2486

**Comment by Nyabloody** [comment]
#1310 
I just noticed this closed issue where the user report they work perfectly fine. Why it doesn't for me? Also they didn't report their setup and specs which makes hard to identify where my issue could be.

**Comment by Nyabloody** [comment]
![chrome_2023-01-28_23-54-24](https://user-images.githubusercontent.com/4554232/216192102-76bf46c2-641a-415e-b964-8059c13409ad.png)

Basically the graph looks like this.

The main problem is the network latency, not visible on this screenshot cause it's hard to get with the horrible lag I'm facing.

Also in the logs tab I get spammed by a lot of:
[Warning] Video frame queue underflow!

And nope, I was wrong, even wired the issue is the same.

**Comment by galister** [comment]
@Nyabloody did it by any chance improve with the Feb 02 nightly?

**Comment by Nyabloody** [comment]
Apparently it's fixed. I just tested 20.0.0-dev07+nightly.2023.02.02 and also I disabled DFS on my router cause Airlink was complaining about it. Either one or another fixed that issue.

**Comment by Nyabloody** [comment]
Closing this issue. I can confirm it was a problem with DFS enabled on the router causing this issue. I did a quick test on alvr v19 and the problem is gone too there.
