### ISSUE TITLE
SteamVR applications not launching on Linux.

### ISSUE THREAD

**Issue by xslendix** [alvr-org/ALVR#1380]
## Description
SteamVR launches, tracking and video work, same with controller input. The
issue is that when I try to start a game or application, it gets stuck at
"Next Up". For example, the SteamVR Performance Test is stuck at preparing to
launch, or the SteamVR Home when I press Play, it just stops instantly. I did
verify the integrity of the files.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=25cf332260

### Installation
**ALVR Version**: ALVR server v19.0.0

**SteamVR Version**: Version 1.24.7 (1671750570)

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Gentoo GNU/Linux x86_64

**Comment by galister** [comment]
This is an issue with SteamVR on Linux, launching from the SteamVR dashboard does not work most of the time, not just on ALVR, but on natively supported headsets (Index, Vive, etc) either.

Try launching the titles from Steam's desktop window, or if you want to do it from the comfort of your headset, you can try [this overlay](https://github.com/galister/X11Overlay), which I created because I was just as annoyed with the state of the SteamVR dashboard as you are now.

**Comment by xslendix** [comment]
I get the same result by launching from the Steam window as well.

**Comment by galister** [comment]
Checking `~/.steam/steam/logs/vrclient_*` might shed some more light on this.

**Comment by Vixea** [comment]
Please use nightly, if you still error out send the logs

**Comment by Vixea** [comment]
Note i doubt your problem will go away be switching to nightly but there so many improvements in nightly for Linux that I just try to recommend it any chance I get

**Comment by xslendix** [comment]
Switched to nightly, no SSL version so I decided to use AppImage. No longer able to connect to PC, trying out building from source.

**Comment by xslendix** [comment]
Source didnt work, same issue.

**Comment by Vixea** [comment]
Have you built openssl?

**Comment by xslendix** [comment]
> Have you built openssl?

Oh definetly, how would I be doing HTTPS? OpenSSL is installed on my system, but I don't think the one that ALVR is linked to.

**Comment by frozht** [comment]
I think you can launch from the headset, but instead of directly from the main Steam dashboard. Try going to the app library which is basically Steam's Big Picture and the games should launch there.
