### ISSUE TITLE
Computer freeze and SteamVR crash on v20 nightly after initial setup

### ISSUE THREAD

**Issue by Nyabloody** [alvr-org/ALVR#1388]
## Description
ALVR v20 nightly freeze my computer for 5-10 seconds and then SteamVR crash just by closing and start ALVR again after the initial setup.

Also very weird, If I'm quick enough to put back the headset and connect to ALVR before SteamVR start the computer won't freeze.

I checked the Event Logs and noticed that vrserver.exe and ucrtbase.dll are mentionned.
Exception code : 0xc0000409
Error offset : 0x000000000007286e

## Steps to reproduce the issue
1. Fresh install of ALVR nightly (any builds)
2. Initial setup and leaving default settings
3. Connect headset
4. ALVR auto-restart
5. SteamVR open again
6. Close ALVR and start it again
7. Computer freeze for 5-10 seconds then SteamVR crash
8. The issue repeat again and again

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel i7-11700KF

**GPU**: RTX 3080Ti

**Audio**:

### Installation
**ALVR Version**: ALVR v20 nightly (any builds)

**SteamVR Version**: 1.24.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 22H2 build 19045.2486

**Comment by zarik5** [comment]
Does v19 crash for you? can you identify the first nightly build that crashes for you?

**Comment by Nyabloody** [comment]
v19 doesn't crash and yeah I'll test and find out

**Comment by Nyabloody** [comment]
Ok after some testing I can confirm ALVR v20.0.0-dev03+nightly.2022.12.10 and onward make my computer freeze and SteamVR crash with the error code I mentionned. Other nightly versions before work perfectly fine.

**Comment by Nyabloody** [comment]
Idk if it's related but I noticed on ALVR v20.0.0-dev02+nightly.2022.12.05 that there is a memory leak or something.

I got spammed with this when I connected:
15:14:50.526750600	[INFO]	Client 9686.client.alvr: [Warning] Video frame queue underflow!
15:14:50.540438100	[INFO]	Client 9686.client.alvr: [Warning] Video frame queue underflow!
15:14:50.624169800	[INFO]	Client 9686.client.alvr: [Warning] Video frame queue underflow!
15:14:50.693669300	[INFO]	Client 9686.client.alvr: [Warning] Video frame queue underflow!

Followed by this when I disconnected:
15:14:50.897439900	[INFO]	Client 9686.client.alvr: [Error] FIXME: Leaking Imagereader!
15:14:50.898716700	[INFO]	ClientDisconnected
15:14:50.898746300	[INFO]	Client disconnected. Cause: At alvr\sockets\src\control_socket.rs:36

**Comment by Vixea** [comment]
unrelated

**Comment by deiteris** [comment]
Can you build the server and client yourself? Or I could provide few versions excluding some commits to see if they work for you. There're only 3-4 commits that change some code between 2022.12.05 and 2022.12.10.

**Comment by Nyabloody** [comment]
I would prefer that you provide me said builds.

**Comment by deiteris** [comment]
Okay, here's one build just before https://github.com/alvr-org/ALVR/commit/46c7e977c22ee0ba2fe28376ac5d4f6066064c05.
[alvr_server_windows.zip](https://github.com/alvr-org/ALVR/files/10469309/alvr_server_windows.zip)
[alvr_client_quest.zip](https://github.com/alvr-org/ALVR/files/10469319/alvr_client_quest.zip)

**Comment by Nyabloody** [comment]
That build seems to works fine. Also there was nothing in the minidump folder.

**Comment by deiteris** [comment]
Could you also check whether Quest Pro controllers work for you well too? Maybe it's related to https://github.com/alvr-org/ALVR/issues/1378.

**Comment by Nyabloody** [comment]
Ok I test this build and yep this is the cause.

Also on both builds the Quest Pro controllers issue is still there. I guess it's related to another issue since even on v19 the problem is there.

**Comment by zarik5** [comment]
@Nyabloody Please test this server together with the last apk sent by @deiteris. The controller tracking will be wonky but it doesn't matter for testing sake.
[alvr_server_windows.zip](https://github.com/alvr-org/ALVR/files/10547090/alvr_server_windows.zip)

**Comment by Nyabloody** [comment]
Issue fixed in commit https://github.com/alvr-org/ALVR/commit/fb17bf762eeab6f041049f254d36396be0eb436a
