### ISSUE TITLE
I don't even know.

### ISSUE THREAD

**Issue by Xolverr** [alvr-org/ALVR#1396]
## Description
I recently installed ALVR to try with my Quest 2, and at first, everything launched fine but the visible framerate on the headset was like 0.5 fps, while the diagnostics page said it was 60 (what I had it set to). There were weird artifacts in the view (SteamVR Home) although audio was perfect. I tried both video encoders and H264 was even worse. It just showed a mess of green pink splotches and other colored lines; I could not see what I was supposed to at all. The SteamVR view looked as expected, so I'm assuming it's some sort of connection/networking issue. After taking the headset off, this monster of an error screen appeared and I had to use Ctrl+Alt+Del to open task manager and shut down the program. My mouse was glitching like crazy whilst this was happening and if I could I would've taken a screen recording.

![IMG_9891](https://user-images.githubusercontent.com/98428552/213815931-f76bb238-cadf-4620-99c2-c5cc4db0c53e.jpg)

### Hardware

**CPU**: Intel i7-1165G7 @ 2.80GHz

**GPU**: NVIDIA GeForce MX450

**RAM**: DDR4 16GB

### Installation
**ALVR Version**: v19.0.0

**SteamVR Version**: v1.24.7

**Install Type**:
- [x] Packaged (`exe`)

**OS Name and Version**: Windows 11 Home 22H2

**OS Build Number**: 22621.1105

**Comment by deiteris** [comment]
GeForce MX450 doesn't have hardware video encoder, so it falls back to software encoding on CPU (which is quite intensive task). What you experience is a bug with software encoding and you should try nightly where it is working https://github.com/alvr-org/ALVR-nightly.
