### ISSUE TITLE
Some games used Oculus Touch -> Vive controller Keys bindings instead of directly Oculus Touch

### ISSUE THREAD

**Issue by orangpelupa** [alvr-org/ALVR#141]
Pardon my english.

so for example while playing with Link, it will have proper bindings. But with ALVR, the bindings will bind oculus touch controllers to vive controller keys (as can be seen on Steam VR bindings menu)

So activating stuff = clicking analog stick, instead of face button. Trigger become grab. One of the face button become menu button.

Despite the controllers themselves are properly detected as oculus touch controller in Steam VR and in the game (the game will show oculus touch model)

**Comment by zarik5** [comment]
The option has been added to ALVR v12.1.0.

**Comment by zarik5** [comment]
A few controller emulation options have been implemented. I guess this can be closed.
