### ISSUE TITLE
ALVR on Oculus Quest 2 only shows gltiched colors like Green/White/Pink

### ISSUE THREAD

**Issue by lordcoover** [alvr-org/ALVR#1411]
Whenever I press ALVR on my Oculus Quest 2 it shows the white background and the black grid and it saying what it usually says. Then everything just changes into a colored glitched screen. Usually Green, then changes to white or pink. I can not seem to find a fix for this. I have a Radeon 6500 XT driver.

**Comment by deiteris** [comment]
RX 6500 video cards don't have hardware encoding, so it falls back to software encoding on CPU. It's broken in v19, but you can check out latest nightly version where it works: https://github.com/alvr-org/ALVR-nightly.
