### ISSUE TITLE
Where did the alvr-nightly AUR package go?

### ISSUE THREAD

**Issue by brakenium** [alvr-org/ALVR#1417]
## Description
There used to be an AUR package for ALVR called alvr-nightly. This package seems to have disappeared now, but is still mentioned on the wiki. Is it meant to be gone from the AUR?

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:
alvr-nightly

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch linux

**Comment by galister** [comment]
Have you tried `alvr-git`?

**Comment by brakenium** [comment]
Currently I am not at my computer, but I did try it and the build seemed to fail. If it helps I can try to build it again and send the logs in here

**Comment by renardroux** [comment]
You can run ALVR-x86_64.AppImage instead of building it.

**Comment by galister** [comment]
the build should work again as of https://github.com/alvr-org/ALVR/commit/2dab06b1cfb274c694d529bbc48caee40cfa3054

**Comment by unclamped** [comment]
> the build should work again as of [2dab06b](https://github.com/alvr-org/ALVR/commit/2dab06b1cfb274c694d529bbc48caee40cfa3054)
The AUR package site is deleted, how would that work?

**Comment by galister** [comment]
as i mentioned above, it's `alvr-git` now.

**Comment by unclamped** [comment]
> as i mentioned above, it's `alvr-git` now.

wouldn't a git package be for the latest commit pushed to the repo?

**Comment by galister** [comment]
which is also what the nightly pipeline builds once every 24h.

if you're looking for an aur that grabs the tar.gz binaries and installs them on your system, that most likely won't happen, as there are plans to discontinue the tar.gz binary builds. they are not compatible with some of the major distros and are a big cause of confusion for linux users.

the two main options are to build it yourself or to use the appimage. `alvr-git` will do the former for you.

**Comment by brakenium** [comment]
I just checked and `alvr-git` does seem to build again. So with that I'm closing this issue.

**Comment by DylanJOrr** [comment]
The problem is that in the installation guide, it references installing the `alvr-nightly` aur package, but that package no longer exists, so I suggest updating the guide to replace all mentions of it with `alvr-git`.
