### ISSUE TITLE
Encoding issues on Intel Arc and software encoding with latest ALVR nightly build

### ISSUE THREAD

**Issue by Alexolotal** [alvr-org/ALVR#1420]
# Encoding issues on Intel Arc and software encoding with latest ALVR nightly build

## Description

There are encoding artifacts and issues present when using ALVR (nightly build) on Intel Arc. In all cases shown, input and sound is correctly transmitted between the headset and computer (can be seen in SteamVR VR View, with controllers moving). All cases shown present same issues on both software encoding and hardware encoding with Intel Arc (Task Manager confirms that "force software encoding" actually toggles between these) and regardless of UDP or TCP connection. All test shown were done with a bitrate of 50Mbps, with adaptive bitrate off.

<details>
<summary>iPerf3 results</summary>

```-----------------------------------------------------------
Server listening on 5201
-----------------------------------------------------------
Accepted connection from 192.168.1.213, port 51182
[  5] local 192.168.1.39 port 5201 connected to 192.168.1.213 port 51184
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-1.00   sec  38.3 MBytes   322 Mbits/sec
[  5]   1.00-2.00   sec  43.4 MBytes   364 Mbits/sec
[  5]   2.00-3.00   sec  46.1 MBytes   385 Mbits/sec
[  5]   3.00-4.00   sec  44.5 MBytes   375 Mbits/sec
[  5]   4.00-5.00   sec  41.7 MBytes   350 Mbits/sec
[  5]   5.00-6.00   sec  44.9 MBytes   377 Mbits/sec
[  5]   6.00-7.00   sec  44.0 MBytes   369 Mbits/sec
[  5]   7.00-8.00   sec  44.7 MBytes   373 Mbits/sec
[  5]   8.00-9.00   sec  43.9 MBytes   369 Mbits/sec
[  5]   9.00-10.00  sec  43.9 MBytes   369 Mbits/sec
[  5]  10.00-10.04  sec  1.74 MBytes   411 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth
[  5]   0.00-10.04  sec  0.00 Bytes  0.00 bits/sec                  sender
[  5]   0.00-10.04  sec   437 MBytes   365 Mbits/sec                  receiver
```
</details>

- Reduce colour banding causes the VR stream to hang on the last frame shown:
![Colour Banding 1](https://user-images.githubusercontent.com/53259381/215303506-3a89f29e-ed53-4e21-a218-4720c3ec8f7b.mp4)
![Colour Banding 2](https://user-images.githubusercontent.com/53259381/215303502-7fce1c8f-ffcf-44b2-8d1b-9811afbfae72.mp4)

- HEVC/h265 encoding causes flashing colours to occur:
![h265](https://user-images.githubusercontent.com/53259381/215303675-daa4ecd8-2638-45df-8b22-82d699c79910.mp4)

- Resolution switching (SteamVR Performance Graph screenshots attached):
  Videos available on [Google Drive](https://drive.google.com/drive/folders/115HmKVeZM1QEQddtsHYvGOAAh8VQGUOq?usp=sharing)
  - 75%
![75](https://user-images.githubusercontent.com/53259381/215302845-a3abf518-0c93-48c8-8760-361c6055e8ed.png)
  - 100%
![100](https://user-images.githubusercontent.com/53259381/215302846-5a4b4a62-f1a0-4c8e-bb8c-70629c63920d.png)
  - 125%
![125](https://user-images.githubusercontent.com/53259381/215302843-ec893026-4f48-4fe9-b684-bc93b3c80b19.png)
  - 150%
![150](https://user-images.githubusercontent.com/53259381/215302847-794ccf04-8287-4c56-9c76-b29007f674aa.png)
  - 200% (ALVR Client crashed after a few seconds)
![200](https://user-images.githubusercontent.com/53259381/215302848-0e54b271-ab75-4403-b100-23fd73d2651a.png)

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: i5 13600k

**GPU**: Intel Arc A750 Limited Edition

**Audio**: 

### Installation
**ALVR Version**: ALVR server v20.0.0-dev06+nightly.2023.01.27

**SteamVR Version**: 1.24.7 (stable release) _and_ 1.25.3 (beta) (issues persists in both)

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11, version 22H2 build 22621.1105

**Comment by deiteris** [comment]
ALVR doesn't support hardware encoding on Intel Arc GPUs on Windows. Here's the quick rundown on all other problems encountered with the software encoding:

> Reduce colour banding causes the VR stream to hang on the last frame shown

I'm not sure, but it might be that Quest 2 decoder doesn't support H.264 10-bit decoding. This option only works with HEVC on all other encoders.

> HEVC/h265 encoding causes flashing colours to occur:

HEVC doesn't work properly with software encoding, and it's a known issue.

> Resolution switching (SteamVR Performance Graph screenshots attached)

The performance of the current software encoding code is not great, that's a known issue. It will be improved in my PR when it's merged https://github.com/alvr-org/ALVR/pull/1400.

**Comment by Alexolotal** [comment]
I just checked task manager, seems I confused decode with encode. Also, new-ish issue, the .29 nightly build now breaks intel arc, with all setting being the same, and rolling back to .27 results in everything working as before. I looked at the commit, its to do with the optimizing the performance graphs? I have no reason to think why that would break the actual encoding, especially when the graph isn't being shown.

**Comment by TheComputerNerd88** [comment]
The only thing that's changed between the 2023.01.29 and 2023.01.27 nightly release that could affect the encoding would be commit 58093df, which appears to rewrite portions of the encoding pipeline

**Comment by deiteris** [comment]
Yes, that's correct, this commit is currently breaking the software encoding. I'm working on the fix.

**Comment by Alexolotal** [comment]
Just tested with nightly 2023.02.09, looks like the encoding problems have been fixed if I use a high bitrate, 100 and 150 megabits at 150 percent seems to work great.
