### ISSUE TITLE
ALVR fails to start

### ISSUE THREAD

**Issue by KlowNJ420** [alvr-org/ALVR#1423]
## Description
After trying multiple versions of ALVR, multiple clean installs of SteamVR, and some trouble shooting spent in the Discord help channel, I've decided to make an issue. 

Launching ALVR simply sits on the "Waiting for server to load..." window, and SteamVR launches asking me to plug in my VR headset. "Reset drivers" button does not work.

Launching the executable in terminal does not give me any valuable information. SteamVR logs have printed out this:
 `Sun Jan 29 2023 21:53:19.583688 - Unable to load driver alvr_server from /home/azure/Desktop/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (libx264.so.163: cannot open shared object file: No such file or directory)`

And on app image and built from source:
`Mon Jan 30 2023 08:24:32.463160 - Not loading driver alvr_server because it was blocked by a previous safe mode event`
Unblocking the addon in settings does not work and continues to be blocked on start up.

I don't know if there's something wrong with my hardware or Linux install, it's a recently fresh install and runs other things perfectly fine so far, only ALVR is tripping up.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=8f3278e68a

### Installation
**ALVR Version**: v19 release, and multiple different versions of v20 nightly.

**SteamVR Version**: Beta 1.25.3 and Stable 1.24.7.

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [x] Source

^ I've tried both. (Is app image considered packaged? If so, throw that in there.)

**OS Name and Version**: Ubuntu 22.10

**Comment by Kieaer** [comment]
Same problem. May be you need install libx264.so.163
I tried install libray but still safe mode and no any logs.

**Comment by galister** [comment]
Can you confirm that 19.1 and the newer nightly AppImages also show this issue? (We stopped distributing portable tar.gz builds due to the number of similar compatibility issues)

**Comment by KlowNJ420** [comment]
I am no longer using linux for the time being, thank you for getting back
to me but I've just used windows for VR at this point.

**Comment by galister** [comment]
I see. Well, when you decide to give VR on Linux a chance, consider reaching out as we have a nice community to help fellow Linux VR users out. Going to close this for the meantime.

**Comment by sol8712** [comment]
I have this issue on Pop OS 22.04 (Ubuntu based) with a;vr 19.1. Im attempting the latest nightly now, then ill test older ones.

**Comment by sol8712** [comment]
The solution in my case, was to extract the .appimage with --appimage-extract in the terminal. Then go into the newly created folders and use spuashfs-root/usr/bin/alvr_launcher to run ALVR

`
./ALVR-x86_64.AppImage --appimage-extract
cd squashfs-root/usr/bin
./alvr_launcher

`

This is the only way ive ever been able to get alvr .appimages to work on Pop(Ubuntu) 20.04 as well as 22.04.

**Comment by Vixea** [comment]
do you have fuse2 installed?

**Comment by sol8712** [comment]
Yes i have libfuse2 v2.9.9 on my system

-------- Original Message --------
