### ISSUE TITLE
[Linux?] SteamVR crashes if controllers are disabled

### ISSUE THREAD

**Issue by galister** [alvr-org/ALVR#1425]
When using ALVR with controllers (the setting) disabled on Linux, SteamVR will crash with -301 after some 5~10 minutes of usage.

Have not confirmed if this is an issue on Windows.

This is on the `openxr-client` branch.

I made the following changes - to register the controllers even when they're disabled, but don't send any tracking data. IIRC this is what VD does as well, so that's where I got the idea.

https://github.com/galister/ALVR/commit/c1f735cc89f1e8eb05536232e7235accb967fde7

This fixed the crashes and works as expected, allowing the use of lighthouse-tracked controllers via Space Cal without issues. The untracked controllers never show up or affect bindings etc. I tested for 3 hours total and have not seen a single crash.

**Comment by zarik5** [comment]
I'm surprised we are even trying to set controller values if they are disabled. There is a commit pending in the openxr branch that does the same thing as your commit, but on the Rust side.

**Comment by galister** [comment]
I don't think it's been trying to set the values, because if it's not registered in SteamVR, it'll fall into this:
```
    if (this->object_id == vr::k_unTrackedDeviceIndexInvalid) {
        return false;
    }
```

**Comment by zarik5** [comment]
So the deal is to always enable controllers? How is that noone else hit this bug yet?

**Comment by galister** [comment]
Possibly Linux specific? I just fixed space cal the other day - both Linux forks were broken - so can't say that there were a lot of people using ALVR with space cal.

**Comment by zarik5** [comment]
I would add a new setting `enable_dummy_controllers`, outside of the `controllers` Switch block.

**Comment by Timocop** [comment]
This issue happens on Windows as well, especially when 3th party (non ALVR) controllers are added.
