### ISSUE TITLE
alvr_server Add-ons blocked

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1431]
## Description
![image](https://user-images.githubusercontent.com/44261958/216431470-6c381b22-afa9-47b5-b81e-ba91468fe4cf.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=d1da7498da
### Installation
**ALVR Version**: v17.0.0 ~ 20.0.0 nightly + last commit https://github.com/alvr-org/ALVR/commit/e2a19c3d1f11783c633f995fb3aac276808dc4ea

**SteamVR Version**: 1.24, 1.25.3 (beta), 1.14 (linux beta)

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [x] Source

**OS Name and Version**: Ubuntu 22.04, Ubuntu 22.04.1, Kubuntu 22.04.1, Kubuntu 22.10, Lubuntu 22.04, Lubuntu 22.04.1

## What I tried to solve this problem...
1. Reinstall SteamVR, Steam
2. Change ALVR Version
3. Self compile (many options) and compile Pull requests
4. Ubuntu 22.04.1 reinstall
5. Kubuntu 22.10 install (But it makes https://github.com/alvr-org/ALVR/issues/1423)
6. Install amdgpu-pro driver + Place amdgpu missing firmware

## Dumps files
[alvr_dumps.tar.gz](https://github.com/alvr-org/ALVR/files/10572786/alvr_dumps.tar.gz)

**Comment by Kieaer** [comment]
I found what's caused
amdgpu-pro Driver make ALVR crash.

**Comment by kulee10** [comment]
Hi @Kieaer, I got similar problem. Do you have any idea how to fix it?

**Comment by SomeoneFrom-Somewhere** [comment]
I have this same issue, except I'm using Debian 11.

**Comment by galister** [comment]
> I have this same issue, except I'm using Debian 11. The fix provided above did not solve the issue for me.

have you tried `rm ~/.config/alvr/session.json`?

**Comment by SomeoneFrom-Somewhere** [comment]
> > I have this same issue, except I'm using Debian 11. The fix provided above did not solve the issue for me.
> 
> have you tried `rm ~/.config/alvr/session.json`?

Just tried this, all I got was this error: cannot remove '/home/user/.config/alvr/session.json': No such file or directory

**Comment by galister** [comment]
what version of alvr? will also need your `~/.steam/steam/logs/vrserver.txt`

**Comment by SomeoneFrom-Somewhere** [comment]
I'm using version 19.1.0 
[vrserver.txt](https://github.com/alvr-org/ALVR/files/10829944/vrserver.txt)

**Comment by galister** [comment]
i can see the crash in the logs but not exactly clear on the why.
are you also getting the same with the latest nightly?

**Comment by SomeoneFrom-Somewhere** [comment]
> i can see the crash in the logs but not exactly clear on the why. are you also getting the same with the latest nightly?

Hmm, let me check

**Comment by SomeoneFrom-Somewhere** [comment]
> i can see the crash in the logs but not exactly clear on the why. are you also getting the same with the latest nightly?

I'm still getting the same results as before, but now I'm also getting this
![Screenshot at 2023-02-24 17-22-42](https://user-images.githubusercontent.com/70498097/221328308-54eab38e-b837-4a82-a600-b076c2bfef54.png)

**Comment by galister** [comment]
try this (will need to install gdb):
- get into `sudo -i` so that you won't be prompted the password, and unblock addons in steamvr before closing steamvr
- `for vrp in vrdashboard vrcompositor vrserver vrmonitor vrwebhelper vrstartup X11Overlay; do pkill -f -9 $vrp; done` to clear up any lingering steamvr processes
- prepare `gdb --pid $(pidof vrserver)` in your prompt
- start alvr and then run the gdb command 1-2 seconds after
- type `continue` in gdb
- give it a few seconds, you'll get some kind of SIGxxx message most likely.
- type `bt` and it should give you the backtrace. paste it here

**Comment by SomeoneFrom-Somewhere** [comment]
> try this (will need to install gdb):
> 
>     * get into `sudo -i` so that you won't be prompted the password, and unblock addons in steamvr before closing steamvr
> 
>     * `for vrp in vrdashboard vrcompositor vrserver vrmonitor vrwebhelper vrstartup X11Overlay; do pkill -f -9 $vrp; done` to clear up any lingering steamvr processes
> 
>     * prepare `gdb --pid $(pidof vrserver)` in your prompt
> 
>     * start alvr and then run the gdb command 1-2 seconds after
> 
>     * type `continue` in gdb
> 
>     * give it a few seconds, you'll get some kind of SIGxxx message most likely.
> 
>     * type `bt` and it should give you the backtrace. paste it here
> 
>     * once, done, ctrl-d in gdb to detach

Should I do this with the regular version of ALVR or nightly?

**Comment by galister** [comment]
whichever you have installed is fine.

**Comment by SomeoneFrom-Somewhere** [comment]
After typing `bt` all I got was this: `No stack.`

**Comment by galister** [comment]
did you get any messages before typing bt?

**Comment by SomeoneFrom-Somewhere** [comment]
> did you get any messages before typing bt?

```
[Thread 0x7fc2a41fd6c0 (LWP 55806) exited]
[Thread 0x7fc298dfb6c0 (LWP 55807) exited]
[Thread 0x7fc299dfd6c0 (LWP 55805) exited]
[Thread 0x7fc29adff6c0 (LWP 55799) exited]
[Thread 0x7fc29a5fe6c0 (LWP 55800) exited]
[Thread 0x7fc2a4ffe6c0 (LWP 55798) exited]
[Thread 0x7fc2a57ff6c0 (LWP 55797) exited]
[Thread 0x7fc2ad1536c0 (LWP 55792) exited]
[Thread 0x7fc2acd036c0 (LWP 55796) exited]
[Inferior 1 (process 55791) exited normally]
```

**Comment by galister** [comment]
what if you don't type continue after starting gdb but just wait for 10 seconds and then `bt`?

**Comment by SomeoneFrom-Somewhere** [comment]
> what if you don't type continue after starting gdb but just wait for 10 seconds and then `bt`?

I get this: 
```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
Backtrace stopped: Cannot access memory at address 0x7ffe038e3468
```

**Comment by SomeoneFrom-Somewhere** [comment]
After uninstalling a graphics card driver that was not meant to be used with my graphics card, ALVR launched without issues.
