### ISSUE TITLE
[Linux?] Headset does not receive video and shows blackscreen after connection

### ISSUE THREAD

**Issue by Luxuride** [alvr-org/ALVR#1433]
## Description

When I connect headset to ALVR server, the headset connects, and tracking in steamvr works. Even controllers are recognized in steamvr. But there is only blackscreen in headset. When I was running 2023.01.31 (different version than reported), it was not black screen but I could look around but the scene was mirrored behind, which is also broken, but differently.
Firewall is probably configured properly as the problem remains even when port forwarding through `adb`.
ALVR says, there are no packets sent.

Headset ADB log taken right after connection and black screen - https://pastebin.com/puQSMD7C
alvr_session_log.txt - https://pastebin.com/nrqJ4qJb
vrserver.txt - https://pastebin.com/EPuztFSd

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=8ae0d42e1a
Oculus Quest 1

### Installation
**ALVR Version**:
v20.0.0-dev07+nightly.2023.02.02

**SteamVR Version**:
1.24.7

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc) - **Appimage**
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Nobara Linux 37 (Thirty Seven)

**Comment by Luxuride** [comment]
When I launch alvr flatpak from cli, after the headset connects
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Bincode does not support Deserializer::deserialize_identifier")', alvr/dashboard/src/worker/mod.rs:116:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
gets written to stdout.

Then there is spam of
```
Error receiving event from event worker: receiving on a closed channel
```
messages to stdout.

I think this might be connected to the problem.

**Comment by Kirottu** [comment]
That's unrelated to the issue of video streaming, it's just an issue with the newer dashboard.
