### ISSUE TITLE
Extending ALVR to support alternative VR runtimes and HW encoding options

### ISSUE THREAD

**Issue by abn0mad** [alvr-org/ALVR#1436]
First off - my deepest respect and appreciation for the ALVR team. Fantastic work. ALVR is the best hope for owners of standalone HMDs to work with Linux.

While ALVR is great for playing Steam games, I would love to see it become the defacto connector / driver for work related applications as well.

XRDesktop promises to deliver a drop-in extension to traditional Linux desktops by allowing users to manipulate desktop windows directly in VR.

It can utilise both SteamVR and Monado as its VR runtime environment, with Monado being preferable (in my opinion) as it supports non-x86 platforms (ARM, RISC-V) apart from it making more sense to have a general purpose VR runtime running in work environments rather than the temptations of a gaming environment.

The option to have Monado as a VR runtime will also make it easier for users to run other / future applications, open source games (i.e. Quake 3, Doom 3, Jedi Knight) and emulators independently of SteamVR on non-x86 or performance constrained platforms.

Would the ALVR team consider adding the following two features to their roadmap:

1. Choice of runtime; specifically Monado. (Having ALVR optionally work with and autostart Monado instead of SteamVR)
2. Custom HW encoding acceleration options; i.e. h264_v4l2m2m on Raspberry Pi (arm64) and others; by allowing users to specify / customise FFMPEG encoding configuration

Adding these two features would make ALVR the ultimate solution for owners of standalone headsets working, playing and entertaining with Linux.

Thank you for reading and hopefully taking this request into consideration.

**Comment by zarik5** [comment]
> 1. Choice of runtime; specifically Monado. (Having ALVR optionally work with and autostart Monado instead of SteamVR)
> 2. Custom HW encoding acceleration options; i.e. h264_v4l2m2m on Raspberry Pi (arm64) and others; by allowing users to specify / customise FFMPEG encoding configuration

Both are planned but no ETA.

**Comment by abn0mad** [comment]
@zarik5 Thank you that is great news. I fully understand and appreciate that it will take considerable time and effort to implement, but it's on the roadmap at least. Thanks for reading and replying as well as all your efforts in bringing ALVR to the Linux community :)

**Comment by zarik5** [comment]
(I'd specify that I'm not the author of contributions targeting Linux, but yeah the community has been amazing!)

**Comment by abn0mad** [comment]
Well I've seen your activity all over the project and the discussions (i.e. [this one](https://github.com/alvr-org/ALVR/issues/183) since taking over ALVR from the original developer, so the compliment and appreciation to both yourself and the community are more than deserved :) Thanks to yourself and the ALVR community Linux users have a real chance to break the last chains tethering them to dual boot Windows and Linux. In my case VR is truly the last remaining reason to have Windows installed at all.
