### ISSUE TITLE
Flick actions don't work properly with ALVR nightly

### ISSUE THREAD

**Issue by gareth-anthony-hulse** [alvr-org/ALVR#1437]
## Description

I cannot properly perform actions that requires the flick of the arm or wrist using the nightly App Image. List of problems below...

- **Half Life: Alyx:** When trying to throw an object it just drops straight down to the floor. Gravity gloves don't work at all.
- **Blade & Sorcery:**  Spells that fire projectiles don't work. Cannot launch anything with telekinesis. Shock spell works fine, [NPC spawner mod](https://www.nexusmods.com/bladeandsorcery/mods/3716) also works as long as pointer is used. Can sort of throw objects while in hand.
- **H3VR Alpha:** I have set the controls in a way that work similar to Half Life: Alyx, where you bring in objects from an distance by holding grip and flicking the wrist. And like in Half Life: Alyx, it also doesn't work. Although, objects can be thrown while in hand.

Don't have issues like this with [v19.0.0](https://github.com/alvr-org/ALVR/releases/tag/v19.0.0), but I don't want to use the stable version because of latency (see #1320). I'll have a look through the nightly builds, to see which one caused this regression at some point this week.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=770e825eba

### Installation
**ALVR Version**: [v20.0.0-dev07+nightly.2023.02.03](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev07%2Bnightly.2023.02.03)

**SteamVR Version**: 1.24.7 and 1.25.3

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Antergos Linux

**ALVR config**: [session.zip](https://github.com/alvr-org/ALVR/files/10610367/session.zip)

**Comment by zarik5** [comment]
Thank you for the report

**Comment by gareth-anthony-hulse** [comment]
Issues are caused by [ALVR v20.0.0-dev07+nightly.2023.02.01](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev07%2Bnightly.2023.02.01). Downgrading to [ALVR v20.0.0-dev06+nightly.2023.01.31](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev06%2Bnightly.2023.01.31) causes the controller rotation to be wrong, but it fixes all the issues mentioned in the original post.
