### ISSUE TITLE
RFC: USB should force TCP

### ISSUE THREAD

**Issue by Vixea** [alvr-org/ALVR#1440]
USB traffic only supports TCP. Forcing it to TCP when using USB(detecting it probably though the ip). It should also only last for the session defaulting back to the users choice once disconnected, and if on re-connection should be forced back to TCP.

**Comment by zarik5** [comment]
I'm in favor on a PR for this, but I plan to implement direct USB support without ADB once we switch to the message-io socket (is supports custom transmission backends).

**Comment by Vixea** [comment]
Since we aren't switching to message-io what are the current plans on this @zarik5

**Comment by zarik5** [comment]
The main issue is that the current sockets code is async but the library is sync. I may decide to switch to message-io after all in place of libp2p, since this last one seems to be async-first and has poor support for sync mode.

**Comment by Meister1593** [comment]
Client now connects to localhost automatically, and if server has localhost client authorised, it connects
