### ISSUE TITLE
Show a blue background when launch/exit game in steamVR Home everytime.

### ISSUE THREAD

**Issue by Nidy** [alvr-org/ALVR#1444]
When I launch game in SteamVR Home, I saw a blue background everytime. It's only show like one second before disappear.

## Description

ScreenShot:
![image](https://user-images.githubusercontent.com/5267878/217403399-98f22d59-0bba-4233-b72d-675f6190b047.png)

### Hardware
Quest 2

### Installation
**ALVR Version**: Lastest version

**SteamVR Version**: 1.24.7

**Comment by zarik5** [comment]
Does the game launch at all? Did you try other games?

**Comment by Nidy** [comment]
Already sloved by myself, close this issue.
