### ISSUE TITLE
ALVR won't launch "thread 'main' panicked at 'called `Option::unwrap()` [Linux]

### ISSUE THREAD

**Issue by koalakoalabanana** [alvr-org/ALVR#1451]
## Description

Can't launch - a window opens and then immediately closes.

``$ alvr_launcher 'RUST_BACKTRACE=1'``
``[2023-02-11T19:39:00Z ERROR alvr_common::logging] At alvr/launcher/src/commands.rs:177: No such file or directory (os error 2)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/git/checkouts/egui-5e4507fa4153be06/311eb66/crates/egui-wgpu/src/winit.rs:110:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace``

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Intel Core i5-8400 @ 6x 4GHz
**GPU**:
NVIDIA GeForce GTX 1060 3GB

**Audio**:
KMix

### Installation
**ALVR Version**:
V19.00 (I think - installed from AUR)

**SteamVR Version**:
1.24

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc) 
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by m3fist0** [comment]
i have the same problem. ubuntu 22.10
