### ISSUE TITLE
Can the latest v19 branch work normally on Linux?

### ISSUE THREAD

**Issue by FUN3JF** [alvr-org/ALVR#1457]
## Description

I pulled the latest code of the v19 branch today, compiled it and ran it on Linux, a gray window will appear on the screen when starting up, and the game video will appear on the computer screen instead of the headset after connecting to quest2. Last year's code from the v19 branch didn't have this problem, so will the current code work fine on Linux?

Thanks for answering.

![image](https://user-images.githubusercontent.com/125360549/218718595-fadc9873-4359-4f55-8247-f4ea82ae91ce.png)
![image](https://user-images.githubusercontent.com/125360549/218718421-ec0d7c82-d859-4673-a5cc-d49a72862b95.png)

### Hardware

**GPU**:AMD RX 5500XT (RADV NAVI14)

**Comment by Vixea** [comment]
try enabling direct display mode, I've had that happen sometimes and sometimes it fixes it, I don't know exactly what causes it in the first place though

**Comment by galister** [comment]
Also, if neither the latest nightly, nor v19 end up tickling your fancy, I recommend trying the nightly from Jan 31.

It's the last one before nightly builds started using the OpenXR client, which introduced many changes.

Though it's not a solution to v19 not working, just putting it out there.
