### ISSUE TITLE
Client can't get video frame on Linux after updating to V19.1.0

### ISSUE THREAD

**Issue by StevenKeXu** [alvr-org/ALVR#1459]
After update to V19.1.0, there is an enable-direct-mode notice in SteamVR. After client connection the VR frames in SteamVR are normal. But there are no video frames on Quest client.   Enable direct mode in SteamVR  developer settngs is not working. So, how to fix it ?

### Installation
**ALVR Version**: V19.1.0

**SteamVR Version**:1.24.7

**Install Type**: building from source;

**OS Name and Version** : Ubuntu 20.04

**Comment by StevenKeXu** [comment]
SteamVR  log shows as blow, compositor can not enable Direct mode.

vrcompositor
Tried to find direct display through RandR: (nil)
vrcompositor
Looking for direct display through Vulkan WSI
vrcompositor
 - Vulkan output 0: 3648x1920 resolution, 20x20 dimensions - ALVR display
vrcompositor
Tried to find direct display through Vulkan WSI: 0x7f478c3a2ee6
vrcompositor
Trying to match desired rate of 90.000000Hz.
vrcompositor
1 modes on display:
vrcompositor
 - 0: 3648x1920@72.000000Hz
vrcompositor
Selected mode 0.
vrcompositor
Direct mode surface: 0x559c19ec1d30
vrcompositor
Requesting 9 device extensions:
vrcompositor
 - VK_KHR_swapchain
vrcompositor
 - VK_KHR_maintenance1
vrcompositor
 - VK_KHR_dedicated_allocation
vrcompositor
 - VK_KHR_get_memory_requirements2
vrcompositor
 - VK_KHR_external_memory
vrcompositor
 - VK_KHR_external_semaphore
vrcompositor
 - VK_EXT_display_control
vrcompositor
 - VK_KHR_external_memory_fd
vrcompositor
 - VK_KHR_external_semaphore_fd
vrcompositor
Global priority query enabled: 1
vrcompositor
Async support disabled by user setting
vrcompositor
m_pVkInstance : 0x559c1a029ea0
vrcompositor
m_pVkPhysicalDevice : 0x559c1a2a05d0
vrcompositor
m_pVkDevice : 0x559c1a509fb0
vrcompositor
m_pVkGraphicsQueue : 0x559c1a2a35b0
vrcompositor
m_pVkComputeQueue : (nil)
vrcompositor
HMD swapchain mode:2 count:3
vrcompositor
**CHmdWindowSDL::CreateSwapChainBufferResources - Invalid swapchain**
vrcompositor
HMD swapchain mode:1 count:4
vrcompositor
Direct mode: disabled
vrcompositor
Mirror swapchain mode:0 count:4
vrcompositor
CGraphicsDevice Init...
vrcompositor
Headset display is on desktop
vrcompositor
Initializing timing resources
vrcompositor
Using Vulkan Renderer
vrcompositor
Initializing CVulkanVRRenderer
vrcompositor
Debug markers: disabled, missing extension support. Is the Renderdoc layer enabled?
vrcompositor
Initialized Vulkan transfer ring buffer, mapped at offset 0x0x7f4760000000.
vrcompositor
Updated HMD Prop_DisplayFrequency_Float to 72.000000

**Comment by Vixea** [comment]
from one of my older talks with the person who fixed 
```
 CHmdWindowSDL::CreateSwapChainBufferResources - Invalid swapchain
 ```
 I remember him saying that if you compile the layer before and compile it again with the newer changes it is for whatever reason still using the old version which has that issue. - at least I'm hoping I got that right @nowrep 
 Now I don't remember how exactly you fix it

**Comment by nowrep** [comment]
It seemed to work with 19.0 so that's not the case. Please post `vrcompositor` backtrace (`coredumpctl gdb` after it crashes).

And also please try this patch:

```diff
diff --git a/alvr/vulkan_layer/layer/swapchain_api.cpp b/alvr/vulkan_layer/layer/swapchain_api.cpp
index 71f6d84f..205740b9 100644
--- a/alvr/vulkan_layer/layer/swapchain_api.cpp
+++ b/alvr/vulkan_layer/layer/swapchain_api.cpp
@@ -52,6 +52,7 @@ VKAPI_ATTR VkResult wsi_layer_vkCreateSwapchainKHR(
         }
         VkResult res = device_data.disp.CreateSwapchainKHR(device_data.device, pSwapchainCreateInfo,
                                                            pAllocator, pSwapchain);
+        return res;
 
         // Workaround vrcompositor requesting incompatible image format for mirror swapchain
         if (res != VK_SUCCESS) {
```

**Comment by StevenKeXu** [comment]
The patch doesn't work. vrcompositor log as follow, coredumpctl gdb also match nothing.
![2023-02-17 17-59-47屏幕截图](https://user-images.githubusercontent.com/8717369/219614088-47523139-911e-4b87-a179-869ea9a31b11.png)
revert code to all the commit, after this commit alvr server worked as a monitor not a headquest.
https://github.com/alvr-org/ALVR/commit/c79b61c32c697ed435dedcffef887525a9d44b5f#diff-5519b4c59c2cacc462dbf05036d8de21c72eca3a2cc69662e70f33b9b40a2d9d

**Comment by Vixea** [comment]
wdym by the patch doesn't work?

**Comment by nowrep** [comment]
Please try to bisect the bad commit `git bisect start -- alvr/vulkan_layer/`.

**Comment by StevenKeXu** [comment]
> wdym by the patch doesn't work?

yes, still get the same result after adding return res;
"
VKAPI_ATTR VkResult wsi_layer_vkCreateSwapchainKHR(
         }
         VkResult res = device_data.disp.CreateSwapchainKHR(device_data.device, pSwapchainCreateInfo,
                                                            pAllocator, pSwapchain);
       return res;
"

**Comment by StevenKeXu** [comment]
> Please try to bisect the bad commit `git bisect start -- alvr/vulkan_layer/`.

https://github.com/alvr-org/ALVR/commit/c79b61c32c697ed435dedcffef887525a9d44b5f#diff-5519b4c59c2cacc462dbf05036d8de21c72eca3a2cc69662e70f33b9b40a2d9d

Before this commit alvr server works well. So, this commit leads to this problem.

**Comment by nowrep** [comment]
What's your GPU and what driver/version you use?

**Comment by StevenKeXu** [comment]
liukang@steven:~/steven/ALVR$ glxinfo |grep -iE 'verdor:|device:|version:'
GLX version: 1.4
    Device: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.6, DRM 3.35, 5.4.0-139-generic) (0x7340)
    Version: 22.3.3
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2

**Comment by nowrep** [comment]
Please run `steam` from terminal and upload full output.

**Comment by StevenKeXu** [comment]
[](url)
[alvr.log](https://github.com/alvr-org/ALVR/files/10788817/alvr.log)
 Please check this log file.

**Comment by nowrep** [comment]
It's the timeline semaphore failing (when trying to export it to fd).
Can you try updating your kernel? 5.4 is very old.

**Comment by StevenKeXu** [comment]
Thinks！I will  update my kernel.  Btw, which kernal version is the most compatible ?

**Comment by Kirottu** [comment]
Just update to the latest LTS or something like that.

**Comment by StevenKeXu** [comment]
Great! works well updating to latest one. Thanks!

**Comment by StevenKeXu** [comment]
works well after updating to latest one！ Thanks for all!
