### ISSUE TITLE
[Linux] Stuck on SW encoding and low quality image because NvEnc encoder can't be found

### ISSUE THREAD

**Issue by Edward205** [alvr-org/ALVR#1476]
## Description
The image is low quality (see screenshot below) and I cannot enable H265 or raise the bitrate to improve the quality, due to it being stuck on SW encoding because it can't create NvEnc encoder.
![alvr client-20230221-024850](https://user-images.githubusercontent.com/52004020/220336952-1f4ad872-b67b-4963-bb99-60983870c182.jpg)
The log shows the following:
```
13:49:41.792332174 | [INFO] | CEncoder client connected, pid 15125, cmdline /home/edward/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
-- | -- | --
13:49:41.801121277 | [INFO] | Using Vulkan device NVIDIA GeForce RTX 3060
13:49:41.906221973 | [INFO] | Using device path /dev/dri/renderD128
13:49:41.913010682 | [INFO] | Encoder: Using device: NVIDIA GeForce RTX 3060
13:49:41.913029853 | [INFO] | Encoder: Alignments:
13:49:41.913032666 | [INFO] | Encoder:     optimalBufferCopyRowPitchAlignment: 1
13:49:41.913035030 | [INFO] | Encoder:     minMemoryMapAlignment:              64
13:49:41.913038581 | [INFO] | Encoder:     minImportedHostPointerAlignment:    4096
13:49:41.913041736 | [INFO] | Encoder: Using queue family 0 (queues: 1) for graphics compute transfers
13:49:41.920012734 | [INFO] | FrameRender: Input size 3584x1952
13:49:41.923116536 | [INFO] | FrameRender: Output size 3584x1952
13:49:41.924369597 | [INFO] | failed to create NvEnc encoder: Failed to find encoder hevc_nvenc
13:49:41.934520595 | [ERROR] | error in encoder thread: HEVC is not supported by SW encoder
13:49:42.718841590 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 82 times
13:49:42.718864035 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
13:49:43.723588108 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 90 times
```

## General Troubleshooting
- [YES] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [YES] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
- Installed `nvidia-utils` and `nvenc` packages

## Environment
Endeavour OS x86_64
XFCE (X11) - LightDM

### Hardware
https://linux-hardware.org/?probe=e8963c4e59

**CPU**:
Intel i7-10700k

**GPU**:
GeForce RTX 3060

**Audio**:
Scarlett Solo

### Installation
**ALVR Version**:
Nightly v20.0.0-dev07+nightly.2023.02.20

**SteamVR Version**:
SteamVR 1.24.7

**Install Type**:
Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
PRETTY_NAME=EndeavourOS (see [the hw-probe](https://linux-hardware.org/?probe=e8963c4e59) for more information)

**Comment by Edward205** [comment]
@Vixea This is what I installed: https://aur.archlinux.org/packages/nvenc

**Comment by Vixea** [comment]
What driver version are you using and what Cuda version?

**Comment by Edward205** [comment]
Driver Version: 525.89.02    CUDA Version: 12.0

**Comment by Vixea** [comment]
Also I doubt source is the correct install type if you're version is that. Did you use the app image or the tar file?

**Comment by Vixea** [comment]
Can you try this

`ffmpeg -y -hwaccel cuda -i input.file output.file`
Replace input and output file with something

**Comment by Edward205** [comment]
It appears CPU is being used, not GPU :/
![Screenshot_2023-02-21_14-48-58](https://user-images.githubusercontent.com/52004020/220349119-fdceff86-3d7d-46f2-8139-1bbd43d77486.png)

**Comment by Vixea** [comment]
Well then it's probably a dependency problem

**Comment by Vixea** [comment]
https://wiki.archlinux.org/title/NVIDIA#Hardware_accelerated_video_encoding_with_NVENC
See if you have the file and the module is loaded

**Comment by Vixea** [comment]
Also would recommend checking out more of this section
https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting
It will allow you to run Wayland when everyone moves off of it though hopefully Nvidia will have there shit together

**Comment by Edward205** [comment]
The `nvidia_urm` module seemes to be loaded correctly:
```
$ lsmod | grep nvidia
nvidia_drm             73728  7
nvidia_uvm           2908160  0
nvidia_modeset       1515520  10 nvidia_drm
nvidia              61444096  551 nvidia_uvm,nvidia_modeset
video                  65536  1 nvidia_modeset
```
I am not sure what you mean in your last comment. I am using xorg and I don't want to switch to Wayland.

**Comment by Edward205** [comment]
FFmpeg and OBS detect Hardware H264 encoding but not H265. ALVR is stuck on Software encoding. I would be fine with H264 if it was Hardware so I can increase the bitrate more, but it's not detected by ALVR.

**Comment by Vixea** [comment]
Can you try manually building it?

**Comment by Vixea** [comment]
no no, I need you to clone alvr and run
```
cargo xtask prepare-deps --platform linux --release
```
then
```
cargo xtask build-server --release
```

**Comment by Edward205** [comment]
I already had compiled ALVR myself yesterday but I did it again now and the same issue still occurs.

**Comment by Vixea** [comment]
than somethings else is wrong somewhere else that I do not know of you should probably create a issue on Nvidia's forums and hope for the best 
https://www.nvidia.com/en-us/forums/

**Comment by galister** [comment]
`nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  525.89.02  Wed Feb  1 23:09:40 UTC 2023`

Not necessarily related to this issue, but I'd recommend trying the Open Kernel driver @ `pacman -S nvidia-open-dkms`, the proprietary driver is known to have issues with SteamVR as well.

**Comment by Edward205** [comment]
Okay, @Vixea. I will post on the Nvidia forum. Keep this issue open in case I find a solution, so that if others have the same problem, they can refer to this thread for a solution.

**Comment by Edward205** [comment]
I reinstalled FFmpeg from the AUR and now it detects h264_nvenc and hevc_nvenc codecs. However, even after recompiling ALVR (latest commit) it still does not detect hevc_nvenc. @galister, I tried installing the Open Kernel driver but the same issue occurs. Check the log:
```
09:55:07.036408683 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 90 times
-- | -- | --
09:55:07.036432650 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
09:55:07.484373725 | [INFO] | CEncoder client connected, pid 43897, cmdline /home/edward/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
09:55:07.487159416 | [INFO] | Using Vulkan device NVIDIA GeForce RTX 3060
09:55:07.543403010 | [INFO] | Using device path /dev/dri/renderD128
09:55:07.543497787 | [INFO] | Encoder: Using device: NVIDIA GeForce RTX 3060
09:55:07.543504169 | [INFO] | Encoder: Alignments:
09:55:07.543506832 | [INFO] | Encoder:     optimalBufferCopyRowPitchAlignment: 1
09:55:07.543509479 | [INFO] | Encoder:     minMemoryMapAlignment:              64
09:55:07.543511984 | [INFO] | Encoder:     minImportedHostPointerAlignment:    4096
09:55:07.543515219 | [INFO] | Encoder: Using queue family 0 (queues: 1) for graphics compute transfers
09:55:07.547594389 | [INFO] | FrameRender: Input size 3584x1952
09:55:07.548721312 | [INFO] | FrameRender: Output size 1984x960
09:55:07.549487357 | [INFO] | failed to create NvEnc encoder: Failed to find encoder hevc_nvenc
09:55:07.562820838 | [ERROR] | error in encoder thread: HEVC is not supported by SW encoder
09:55:08.039770570 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 90 times
09:55:08.039793742 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
09:55:09.042971441 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 90 times
```

Also, this is the log when using H264:

10:02:43.838776248 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 88 times
```
-- | -- | --
10:02:43.838801108 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
10:02:44.842241249 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 90 times
10:02:44.842278189 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
10:02:45.236871153 | [INFO] | CEncoder client connected, pid 48406, cmdline /home/edward/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
10:02:45.239516280 | [INFO] | Using Vulkan device NVIDIA GeForce RTX 3060
10:02:45.298563496 | [INFO] | Using device path /dev/dri/renderD128
10:02:45.298675277 | [INFO] | Encoder: Using device: NVIDIA GeForce RTX 3060
10:02:45.298684160 | [INFO] | Encoder: Alignments:
10:02:45.298689428 | [INFO] | Encoder:     optimalBufferCopyRowPitchAlignment: 1
10:02:45.298694822 | [INFO] | Encoder:     minMemoryMapAlignment:              64
10:02:45.298698788 | [INFO] | Encoder:     minImportedHostPointerAlignment:    4096
10:02:45.298704220 | [INFO] | Encoder: Using queue family 0 (queues: 1) for graphics compute transfers
10:02:45.303196434 | [INFO] | FrameRender: Input size 2880x1568
10:02:45.303661214 | [INFO] | FrameRender: Output size 2880x1568
10:02:45.304476429 | [INFO] | failed to create NvEnc encoder: Failed to find encoder h264_nvenc
10:02:45.304646630 | [INFO] | Encoder: using SAR=1/1
10:02:45.307434559 | [INFO] | Encoder: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
10:02:45.310511282 | [INFO] | Encoder: profile Constrained Baseline, level 5.2, 4:2:0, 8-bit
10:02:45.314552399 | [INFO] | using SW encoder
10:02:45.317492065 | [INFO] | Encoder: CBR HRD requires constant bitrate
10:02:45.320609319 | [INFO] | Encoder: VBV parameters cannot be changed when NAL HRD is in use
10:02:45.387072755 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 49 times
10:02:45.387108188 | [INFO] | Client 0122.client.alvr: [Info] Decoder dequeue event: OutputBuffersChanged
10:02:45.387111244 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
10:02:45.390039716 | [INFO] | Client 0122.client.alvr: [Info] Decoder dequeue event: OutputFormatChanged
10:02:46.138007887 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
10:02:46.320379916 | [INFO] | Encoder: VBV parameters cannot be changed when NAL HRD is in use
10:02:47.174122152 | [INFO] | Client 0122.client.alvr: [Info] Last log line repeated 3 times
10:02:47.174149937 | [INFO] | Client 0122.client.alvr: [Warning] Timed out when waiting for frame!
10:02:47.331208271 | [INFO] | Encoder: VBV parameters cannot be changed when NAL HRD is in use
10:02:48.341621386 | [INFO] | Encoder: VBV buffer size cannot be smaller than one frame, using 1666 kbit
10:02:48.341639070 | [INFO] | Encoder: VBV parameters cannot be changed when NAL HRD is in use
```

**Comment by Vixea** [comment]
have you installed 
https://archlinux.org/packages/extra/any/ffnvcodec-headers/
I've just been reminded of that maybe thats the issue

**Comment by Edward205** [comment]
No, that is not installed.

**Comment by Vixea** [comment]
does installing then rebuilding deps and server fix the issue?

**Comment by Edward205** [comment]
After installing the ffnvcodec-headers and rebuilding, IT WORKED. Once... SteamVR is now blocking the ALVR add-on due to crashes, but that's a different issue which I will attempt to solve myself and if I can't I will open a new issue. This issue is solved. Thanks a lot for the quick replies!
