### ISSUE TITLE
Slow hand movements

### ISSUE THREAD

**Issue by oGrqpez** [alvr-org/ALVR#1484]
In previous versions of ALVR, you could choose the speed of your controllers when moving; now it's not there. How can I change it?

**Comment by galister** [comment]
Hi, try adjusting `Pose time offset (ms)` under the `Headset` tab of settings. A higher value will make the controllers more jumpy, while a lower value will make them move smoother.

**Comment by oGrqpez** [comment]
appologies for the late reply, i don't see post time offset in the headset advanced settings
I'm on 19.1.0

**Comment by zarik5** [comment]
Yes, it should be `trackingLatencyOffsetMs` on v19.1.0

**Comment by Vixea** [comment]
Closing as completed
