### ISSUE TITLE
This 127.0.0.1 page can’t be found

### ISSUE THREAD

**Issue by dekoth7** [alvr-org/ALVR#1488]
i dont understan how to fix this please help

## General Troubleshooting
ive tried reinstalling chromium and going to older version of alvr

### Hardware
steamdeck
**CPU**:AMD Van Gogh APU With Zen 2 CPU

**GPU**: RDNA 2 GPU Cores

**Audio**:

### Installation
**ALVR Version**:19..1.0

**SteamVR Version**: Latest

**Install Type**:
.appimage

**OS Name and Version* Steam os 3.0.0

**Comment by Timocop** [comment]
You have to enter the IP and PORT, not just the IP

**Comment by auwsom** [comment]
I have a similar issue on Ubuntu 22.04. ALVR opens a browser page to 127.0.0.1:8082, but is not reachable. I tried with firewall down. Not sure what else to try.

**Comment by VPetar** [comment]
@auwsom #metoo nothing happens really, and steamvr keeps on blocking alvr_server as well

**Comment by auwsom** [comment]
@VPetar Yeah, I went back to Immersed which works flawlessly (though the app is a little slow when logging in, and used `apt install v4l2loopback-source` for the dependency. It's free now and has a ton of features. :+1:

**Comment by auwsom** [comment]
@Vixea Just curious, why was this closed? It's still an issue. I'm actually back trying to troubleshoot it to get VR working through Steam on Ubuntu (the most popular Linux distribution).

I'm going to try it with Gnome or Arch, because it seems like most reports of it working seem to be with those. But it's not working on Ubuntu yet.
```

**Comment by Vixea** [comment]
It's because we removed the chromium based one I would recommend asking for support in the discord as that is a more appropriate place for this
