### ISSUE TITLE
"The stream will begin soon, please wait" Appimage on Manjaro

### ISSUE THREAD

**Issue by wereretot** [alvr-org/ALVR#1490]
## Description

When attempting to use the Appimage of the latest version, I will see in steam VR that indeed there is tracking, but when I look in my Oculus Quest 2, there's no video and it just says "The stream will begin soon, please wait".

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
AMD Ryzen 5 2600 Six-Core Processor

**GPU**:
XFX AMD Radeon™ RX 5500 XT 8GB GDDR6 THICC II Pro

**Audio**:
Pipewire

### Installation
**ALVR Version**:
v19.1.0

**SteamVR Version**:
1.24.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
 Manjaro Linux

**Comment by Vixea** [comment]
Manjaro does build mesa with H265 or H264 support enabled, switching distros is recommended. I suggest endeavoros for a similar experience.

**Comment by wereretot** [comment]
@Vixea I don't want to switch OS just to play VR.
