### ISSUE TITLE
Video doesn't work, failed to load libavcodec.so.58

### ISSUE THREAD

**Issue by CodyMarkix** [alvr-org/ALVR#1492]
## Description
Input works completely fine, but video does not work at all (Audio doesn't work either but I know why. I haven't installed the VB audio driver yet), video clip of the issue: https://imgur.com/a/bfVCTwU

I've dug into ALVR logs and found that `libavcodec.so.58` failed to load. Now that's weird because `libavcodec.so.58` is present in the installation.

<img src="https://cdn.discordapp.com/attachments/935455291896631306/1080914317249089606/image.png">

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
`hw-probe` Link: https://linux-hardware.org/?probe=2c6ad91981

### Installation
**ALVR Version**: 18.2.2

**SteamVR Version**: 1.24.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Pop!_OS 22.04 LTS

**Comment by Vixea** [comment]
Could you please try the latest release to see if this is still an issue?
