### ISSUE TITLE
ALVR v20.0.0-dev07+nightly.2023.03.06 Windows 10048 error on restart app on Pico4

### ISSUE THREAD

**Issue by KuDeSnik33ra** [alvr-org/ALVR#1495]
If I close ALVR on my Pico 4 and open it again - without restart of PC app - PC app start spaming popup error messages:
> At alvr\sockets\src\stream_socket\udp.rs:41: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
and I have to restart PC app to fix it. If close app on Pico4 - messages stops, start again = more messages.

**Comment by galister** [comment]
Shut down SteamVR, open task manager and on the Details tab, see if there's anything among these running:
```
vrserver
vrcompositor
vrmonitor
vrstartup
vrwebhelper
vrdashboard
```
(It's going to be `vrserver` 99% of the time.)
If you find something like that, just force stop them and then try launching ALVR again.

**Comment by KuDeSnik33ra** [comment]
vrserver should be running - I do not need it to be stopped. I just need to restart app on Pico4 = client on headset (~because it was crashed).

**Comment by Timocop** [comment]
Windows can be very weird with ports. Does your vrserver spawn any child processes? This error usually happens when the app that uses the port, spawns other processes. And even with the parent app closed, Windows will still "reserve" those ports for the child processes.

**Comment by KuDeSnik33ra** [comment]
Sounds weird, if you closesocket() = port is free for next opening. It looks like ALVR pc server just don't close it.
