### ISSUE TITLE
How to debug Windows

### ISSUE THREAD

**Issue by KuDeSnik33ra** [alvr-org/ALVR#1497]
Is there any possible way to debug the "driver_alvr_server.dll"? Some kind of 'attach' for 'cppvsdbg' in VSCode?
Can someone provide the launch.json to attach?

**Comment by zarik5** [comment]
You need to attach vrserver.exe. Load the pdb you find in the same folder as the dll.

**Comment by korejan** [comment]
Just to add you can do this in visual studio (i'm sure you can do the same with VSC), just note the `--keepalive` flag
![image](https://user-images.githubusercontent.com/64199710/224047061-802d9252-f62d-4c96-86f6-afe03dd83044.png)

Then run the debugger and then you need to start steamvr

**Comment by KuDeSnik33ra** [comment]
What project are you using? ALVR has no vcproj
