### ISSUE TITLE
ALVR over USB crashing Quest 2 client

### ISSUE THREAD

**Issue by not-nullptr** [alvr-org/ALVR#1498]
## Description

Attempting to start ALVR over USB once seems to crash the Quest 2 client. Doing this again will cause it to ask you to click 'trust' on the server, despite the client already being trusted. Closing and re-opening will repeat this. This issue also occurs on Windows on my hardware.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=69564be379

### Installation
**ALVR Version**:
latest

**SteamVR Version**:
latest

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**
Arch Linux

**Comment by Vixea** [comment]
Please switch to using TCP, I think that's your issue
