### ISSUE TITLE
Are there some ports  for Eye-Tracking ?

### ISSUE THREAD

**Issue by Hope10086** [alvr-org/ALVR#1503]
I would like to know if ALVR or ALXR  has reserved ports for VR headsets that can provide eye movement tracking? 
Our team is planning to use Pico neo3 Pro Eye or HTC VIVE Pro Eye to collect some user eye movement data while playing.

**Comment by zarik5** [comment]
ALVR does not support eye tracking. ALXR does support eye tracking. Please ask in their GitHub repository.

**Comment by zarik5** [comment]
As of the latest nightly, ALVR supports VRChat eye tracking (VRCFaceTracking support is planned)
