### ISSUE TITLE
Controller "jumps" to zero when losing tracking

### ISSUE THREAD

**Issue by mittorn** [alvr-org/ALVR#1510]
When controller fails to track, nightly version sends it as active, but with zero position. Client applies recenter/offset to this position and sends to SteamVR
Pre-OpenXR versions stopped sending position in this case, and losing button events, i fixed it locally by moving button processing  to OvrController::setButtons method

Now tracking position is send as zero. It is better because it keeps sending rotation (and even some predicted angular velocity), but SteamVR position should not be updated in that case. Temporary worked around by skipping m_pose update if position is zero  on c++ side and disabled recentering/offset on rust side, but it seems to better to preserve last position somewhere before calling onPoseUpdate, or add some flag to it to ignore position data

**Comment by zarik5** [comment]
Thanks for the report. I will make a patch soon.

**Comment by zarik5** [comment]
Done. Let me know how it goes for tomorrow's nightly.

**Comment by mittorn** [comment]
Seems to work correctly on actual client (rebuilt from source)
