### ISSUE TITLE
error in encoder thread: HEVC is not supported by SW encoder

### ISSUE THREAD

**Issue by wereretot** [alvr-org/ALVR#1512]
## Description
When attempting to use the standard "HEVC (256)" encoder codec I get the following error: "

"error in encoder thread: HEVC is not supported by SW encoder"

## Log:

20:17:20.160534261 | [INFO] | SessionUpdated
-- | -- | --
20:17:20.160620122 | [INFO] | Session
20:17:20.179536067 | [INFO] | SessionUpdated
20:17:20.179635323 | [INFO] | Session
20:17:20.192765976 | [INFO] | Initial TCP buffer size: send: 87040B, recv: 131072B
20:17:20.192819847 | [INFO] | New TCP buffer send size: 425984B
20:17:20.192826830 | [INFO] | New TCP buffer recv size: 425984B
20:17:20.192847639 | [INFO] | ClientConnected
20:17:20.193119519 | [INFO] | Serial Number: 1WMHH000X00000
20:17:20.193126692 | [INFO] | Model Number: Miramar
20:17:20.193131351 | [INFO] | Render Target: 3648 1920
20:17:20.193138264 | [INFO] | Seconds from Vsync to Photons: 0.005000
20:17:20.193142582 | [INFO] | Refresh Rate: 90
20:17:20.194527811 | [INFO] | CEncoder::Run
20:17:20.194593744 | [INFO] | CEncoder Listening
20:17:20.224736440 | [INFO] | CEncoder client connected, pid 2810, cmdline /home/rexommendation/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
20:17:20.306894996 | [INFO] | Using Vulkan device AMD Radeon RX 5500 XT
20:17:20.326283077 | [INFO] | Using device path /dev/dri/renderD128
20:17:20.328466793 | [INFO] | Encoder: Using device: AMD Radeon RX 5500 XT
20:17:20.328480950 | [INFO] | Encoder: Alignments:
20:17:20.328488333 | [INFO] | Encoder: optimalBufferCopyRowPitchAlignment: 1
20:17:20.328494114 | [INFO] | Encoder: minMemoryMapAlignment: 64
20:17:20.328499865 | [INFO] | Encoder: minImportedHostPointerAlignment: 4096
20:17:20.328506427 | [INFO] | Encoder: Using queue family 0 (queues: 1) for graphics compute transfers
20:17:20.334670280 | [INFO] | FrameRender: Input size 3648x1920
20:17:20.340978815 | [INFO] | FrameRender: Output size 3648x1920
20:17:20.342653757 | [INFO] | failed to create AMF encoder: AMFContext not valid
20:17:20.342756880 | [INFO] | Encoder: libva: VA-API version 1.17.0
20:17:20.342779112 | [INFO] | Encoder: libva: Trying to open /usr/lib/dri/radeonsi_drv_video.so
20:17:20.344026011 | [INFO] | Encoder: libva: Found init function __vaDriverInit_1_17
20:17:20.358276845 | [INFO] | Encoder: libva: va_openDriver() returns 0
20:17:20.358297133 | [INFO] | Encoder: Initialised VAAPI connection: version 1.17
20:17:20.358314646 | [INFO] | Encoder: VAAPI driver: Mesa Gallium driver 22.3.5 for AMD Radeon RX 5500 XT (navi14, LLVM 15.0.7, DRM 3.49, 6.1.12-1-MANJARO).
20:17:20.358321449 | [INFO] | Encoder: Driver not found in known nonstandard list, using standard behaviour.
20:17:20.368275211 | [INFO] | Encoder: Input surface format is nv12.
20:17:20.368305899 | [INFO] | Encoder: Compatible profile VAProfileHEVCMain (17) is not supported by driver.
20:17:20.368311189 | [ERROR] | Encoder: No usable encoding profile found.
20:17:20.368814343 | [INFO] | failed to create VAAPI encoder: Cannot open video encoder codec: Function not implemented
20:17:20.376778052 | [ERROR] | error in encoder thread: HEVC is not supported by SW encoder.

With this as video output:
![Screenshot_20230314_201908](https://user-images.githubusercontent.com/28990565/225171207-8a9e6414-fcc3-4eeb-9cc0-b257ab7a4a41.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
**CPU:**
AMD Ryzen 5 2600 Six-Core Processor

**GPU:**
XFX AMD Radeon™ RX 5500 XT 8GB GDDR6 THICC II Pro

**Audio:**
Pipewire

## Installation

**ALVR Version:**
alvr-19.1.0

**SteamVR Version:**
STEAMVR 1.24.7

**Install Type:**

Packaged (exe, deb, rpm, etc)
Portable (zip)
[ X] Source

**OS Name and Version (winver on Windows or grep PRETTY_NAME /etc/os-release on most Linux distributions):**
Manjaro Linux

**Comment by Vixea** [comment]
Manjaro is not supported because it doesn't build mesa with h264/5 encoding I would suggest moving distros as painful as that is endeavouros is recommended for a similar experience
