### ISSUE TITLE
AppImage glibc version problems on Ubuntu & PopOS 20.04

### ISSUE THREAD

**Issue by josephrocca** [alvr-org/ALVR#1517]
## Description
Here's what I get when I download the AppImage file for ALVR v20.0.0-dev07+nightly.2023.03.15:
```
$ ./ALVR-x86_64.AppImage
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./ALVR-x86_64.AppImage)
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./ALVR-x86_64.AppImage)
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./ALVR-x86_64.AppImage)
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ALVR-x86_64.AppImage)
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_ALVR-x4vjZyg/usr/bin/../lib/libcrypto.so.3)
./ALVR-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_ALVR-x4vjZyg/usr/bin/../lib/libcrypto.so.3)
```

```
$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

IIUC, it's not really possible for me to "manually" update my GLIBC version because a bunch of system stuff depends on it, and would break?

Recent GLIBC version history:

```
2023-02-01 | GLIBC 2.37
2022-08-01 | GLIBC 2.36
2022-02-03 | GLIBC 2.35
2021-08-02 | GLIBC 2.34
2021-02-01 | GLIBC 2.33
2020-08-05 | GLIBC 2.32
```

Related: https://github.com/alvr-org/ALVR/issues/669#issuecomment-938499907

### Installation
**ALVR Version**: ALVR v20.0.0-dev07+nightly.2023.03.15

**Install Type**:
ALVR-x86_64.AppImage

**OS Name and Version**:
Pop!_OS 20.04 LTS

**Comment by Roadhog360** [comment]
Getting the same issue on Ubuntu 20.04. https://stackoverflow.com/questions/72513993/how-to-install-glibc-2-29-or-higher-in-ubuntu-18-04 I followed Alex's answer to install a newer version of GLIBC but the answer lacks instructions on how to actually use the new GLIBC version with an application.

**Comment by zarik5** [comment]
This should be solved in tonight's nightly.

**Comment by Roadhog360** [comment]
I tried updating my system to 22.04 only to find the Ubuntu updater is temper-mental and does not let you update if you haven't updated... (???)

**Comment by josephrocca** [comment]
Hi @zarik5, I've just tried `ALVR-x86_64.AppImage` from [2023.03.19](https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev07%2Bnightly.2023.03.19) on an up-to-date version of Pop!_OS 20.04 LTS (which has GLIBC version `2.31`) and I got the same error as I pasted above.

**Comment by zarik5** [comment]
Yeah, i wasn't able to solve the issue. I'm not really sure what to do.

**Comment by Roadhog360** [comment]
Have you tried building on Ubuntu 20.04?

**Comment by zarik5** [comment]
@Roadhog360 Yes. I already told you on Discord that I tried and there were issues with Vulkan. I'm not competent enough to fix this.
