### ISSUE TITLE
You are missing the following 32-bit libraries, and Steam may not run

### ISSUE THREAD

**Issue by michaelngsh** [alvr-org/ALVR#1526]
when I  run the AppImage for ALVR v20.0.0-dev07+nightly.2023.03.21

it can connet the quest 2, but it display the ERROR:

“You are missing the following 32-bit libraries, and Steam may not run: 
libXrandr.so.2
libXrender.so.1
libgtk-x11-2.0.so.0
libgdk_pixbuf-2.0.so.0 ”

### Hardware：steam deck OS: 3.4.6

ALVR Version**:ALVR v20.0.0-dev07+nightly.2023.03.21

SteamVR Version**:1.25.6

**Comment by mittorn** [comment]
SteamVR itself runs?
try register alvr manually (via external_drivers in vrpaths) and use it without launcher

**Comment by Donald7392** [comment]
i'm having the same issues. can anyone run a stable alvr on steam deck using a quest 2?

**Comment by parkerlreed** [comment]
Steam OS 3.5 (Main branch) working with ALVR stable fine here.
