### ISSUE TITLE
OpenXR Client hangs sometimes on Quest2 and can only be stopped from android settings

### ISSUE THREAD

**Issue by mittorn** [alvr-org/ALVR#1528]
After upgrading to openxr, cannot restart freezed client normally

Both 38 and 50 firmwares affected.

Pre-openxr versions allowed to be killed from pause menu, now pressing oculus button just hides app (no menu shown) and only way to open it is open settings via oculus tv or some launcher and force-stop app, or am force-stop from adb

**Comment by zarik5** [comment]
This is known and will be fixed before the v20 stable release.
