### ISSUE TITLE
Latest nightly crashes SteamVR

### ISSUE THREAD

**Issue by f0rttnite** [alvr-org/ALVR#1529]
## Description
The latest nightly update for the PC server crashes SteamVR after launching, ranging from about 5 seconds after to crashing before SteamVR can even load, in the former it shows the popup about a critical error, the latter a notification about SteamVR missing files.
In addition, it seems to rarely semi-corrupt SteamVR, stopping ALVR from loading entirely until SteamVR is manually launched again

## General Troubleshooting
Have tried both Airlink and Virtual Desktop on two machines, AL and VD work fine on both but ALVR doesn't on either

### Hardware

**CPU**: Ryzen 5 2600X/Intel i5-8300H

**GPU**: GTX 1080/GTX 1050

### Installation
**ALVR Version**: V20.0.0-dev07+nightly.2023.03.22

**SteamVR Version**: 1.25.6

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** Windows 11 Pro/Home 22H2

**Comment by zarik5** [comment]
Can you narrow this down to a single nightly where the bug appears?

**Comment by f0rttnite** [comment]
well, i did put the version down as V20.0.0-dev07+nightly.2023.03.22

**Comment by f0rttnite** [comment]
https://github.com/alvr-org/ALVR/commit/7652ae835d844d506ef865bc70bce5168ac31d4b
i think it's this commit, since the nightly was working fine before it 
i'll test if if i can later but i don't really have the time to try loading the previous nightly onto my quest

**Comment by zarik5** [comment]
I pushed a fix, it will be live in the next nightly. Thanks for the report!

**Comment by f0rttnite** [comment]
awesome, thanks
