### ISSUE TITLE
Problem with capturing Server side textures

### ISSUE THREAD

**Issue by yingtian991221** [alvr-org/ALVR#1530]
Hi,

I'm trying to capture server side render results after compositing two eyes together, color correction and FFR in /server/cpp/platform/win32/FrameRender.cpp. My idea is that the the end stage of RenderFrame() after m_ffr is invoked and before returning, the context/texture are ready for view. However my problem comes from choosing the tools. 

The first approach I tried is including D3DX11tex.h from D3DX headers, but the build would not find the paths and I've no idea how D3DX will work together with other headers from system libs like /Windows/Kits/Include/d3d11.h. 
I've also tried ScreenGrab tools but there are linking errors when I copied ScreenGrab.h and ScreenGrab.cpp under /cpp/platform/win32 folder and included "ScreenGrab.h" in FrameRender.cpp

Are there any other tools suitable for capturing these D3D11Textures or should I go to other places to capture the RGB pixels?

**Comment by zarik5** [comment]
You need to add the appropriate dlls. you need to find out which dlls each tool needs.
