### ISSUE TITLE
Slow performance when hardware encoder enabled

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1535]
## Description
Using the software encoder, instead of increasing the cpu temperature, the fps is relatively stable at 30 to 50 fps.
Using the hardware encoder, the cpu clock drops below 800MHz, and the GPU usage also drops to fps 4 ~ 9 without exceeding 30%.

Using 5900HX, Embedded GPU and has 1.3GHz ~ 4.3GHz clock.
When I run the game without ALVR, the fps works between 30 ~ 60 fps.

Hardware encoding keeps the cpu fan speed down as it doesn't generate heat.
No heat is nice, but the CPU clock drops below 1GHz and performance is greatly reduced.

Hardware encoder
![image](https://user-images.githubusercontent.com/44261958/227871697-d935353f-4d12-4c0f-a85a-406a526b154b.png)

Software encoder
![image](https://user-images.githubusercontent.com/44261958/227871226-e647c037-362b-449d-9d6a-312db48ab9c6.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=d1da7498da

### Installation
**ALVR Version**: v20.0.0-dev07+nightly.2023.3.15

**SteamVR Version**: 1.25.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** : Ubuntu 22.04.1 LTS

**Comment by Vixea** [comment]
are you changing the power profile to vr this is going to be needed until kernel version 6.4 it seems at this point?

**Comment by Kieaer** [comment]
I'm not change power profile.
Linux 5.15 LTS is applied to this ubuntu version.
Do I need a kernel upgrade?

**Comment by Vixea** [comment]
no you need to change the power profile

**Comment by Vixea** [comment]
oh about the previous issue that I closed before use this one
https://github.com/alvr-org/ALVR-nightly/releases/tag/v20.0.0-dev07%2Bnightly.2023.03.25
as the latest has a regression that effects linux

**Comment by Vixea** [comment]
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/469
read this

**Comment by Vixea** [comment]
well at this case its your gpu not being powerful enough
