### ISSUE TITLE
Always running wine64-preloader and no controller

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1538]
## Description
All games are detected as a wine64-preloader, and the controller is unavailable, but headset tracking works.

This issue did not occur in nightly 2023.3.15

Also, nightly 2023.3.26 version can't be use because keep steamvr addon blocked.
and still https://github.com/alvr-org/ALVR/issues/1536

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=d1da7498da

### Installation
**ALVR Version**: v20.0.0-dev07+nightly.2023.3.25

**SteamVR Version**: 1.25.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** : Ubuntu 22.04.1 LTS

**Comment by Vixea** [comment]
Are you sure you're listing the right nightly as the one you are listing doesn't exist

**Comment by Kieaer** [comment]
typo mistake 2023.3.**2**6

**Comment by Vixea** [comment]
That is still not the latest and it had a regression with a previous commit fixed in later commits/nightlies.

**Comment by Vixea** [comment]
Also just to note wine-preloader is just always going to be there with proton and is not an ALVR bug
