### ISSUE TITLE
ALVR crash in Pico4 latest system version

### ISSUE THREAD

**Issue by Revolvor** [alvr-org/ALVR#1542]
I use pico4.
I update my system version to 5.5.2, the alvr had crash. I hope you mind this bug.

**Comment by Revolvor** [comment]
fix: not 5.5.2 ,is 5.5.0

**Comment by zarik5** [comment]
@galister Can you reproduce?

**Comment by galister** [comment]
works fine for me on 5.5.0 global oem. when does it crash for you, exactly?

**Comment by thankjura** [comment]
Same problem.
PICO 4:  5.5.0
ALVR: c374e34be2bc017f36fe4a887202deaba317acd4

ALVR client crash after connect.
Log:

`
Handshake error for 3615.client.alvr: At alvr/server/src/connection.rs:155: At alvr/sockets/src/control_socket.rs:69: Connection refused (os error 111)"
`
[alvr_session_log.txt](https://github.com/alvr-org/ALVR/files/11116452/alvr_session_log.txt)

**Comment by Revolvor** [comment]
> 

yes，it's because refresh rate, ths
