### ISSUE TITLE
Ghosts of Tabor will completely crash steamvr.

### ISSUE THREAD

**Issue by TandyTnd** [alvr-org/ALVR#1543]
## Description
<Tabor will completely crash steamvr, no logs are generated. Same thing with the nightly version.>

### Hardware
**CPU**:
 Ryzen 9 5900x
**GPU**:
RTX 3060
**Audio**:
Hyper X wireless headphones. I don't stream audio with alvr. 
### Installation
**ALVR Version**:
Last nightly version, It also affects 19.10, 19.0, 18.2.3 and the alxr client. 
Virtual Desktop doesn't crash, but suffers from significant stutters. 
**SteamVR Version**:
1.25.7. 
**Install Type**:
.exe

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
windows 11, haven't tested windows 10. 
Hardware accelerated gpu scheduling enabled or disabled.

**Comment by OscarZunigaLara** [comment]
This is the crash_log.txt 
{"timestamp":"22:47:39.220006400","event_type":{"id":"Log","data":{"severity":"Error","content":"What happened:\npanicked at 'Invalid JSON: Error(\"EOF while parsing a value\", line: 1, column: 0)', C:\\Users\\runneradmin\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\alcro-0.5.4\\src\\chrome.rs:250:62\n\nBacktrace:\n   0: wgpu_render_bundle_push_debug_group\n   1: set_device_openvr_props\n   2: wgpu_render_bundle_push_debug_group\n   3: wgpu_render_bundle_push_debug_group\n   4: wgpu_render_bundle_push_debug_group\n   5: wgpu_render_bundle_push_debug_group\n   6: wgpu_compute_pass_end_pipeline_statistics_query\n   7: wgpu_compute_pass_end_pipeline_statistics_query\n   8: set_device_openvr_props\n   9: HmdDriverFactory\n  10: HmdDriverFactory\n  11: HmdDriverFactory\n  12: wgpu_render_bundle_push_debug_group\n  13: BaseThreadInitThunk\n  14: RtlUserThreadStart\n"}}}

**Comment by tommy1735** [comment]
for me it not crashing but not show the game in VR but its running on desktop, also no tracking (head and hands)

**Comment by Vixea** [comment]
what browser are you using?

**Comment by tommy1735** [comment]
Chrome or u mean some vr browser? but don't know...

**Comment by TandyTnd** [comment]
I think that your game is no "hooking" into the steamvr runtime. That's why is not crashing.  I think you need to run the protected exe in the game files with admin privileges at least once(anticheat stuff) and then it will hook. You also need to disable the openxr toolkit in steamvr. This will (kinda) work for virtual desktop, but tabor still has a lot of stutters in VD that make it unplayable. ALVR will just crash stamvr.

**Comment by zarik5** [comment]
The crash is relative to the webview and will be solved once installing Chrome. Another possibility is to use the nightly ALVR version instead which has a new OpenGL dashboard.

**Comment by TandyTnd** [comment]
I am using the v20.0.0-dev11+nightly.2023.04.14 streamer.
I also have chrome installed.  
In my case, it only crashes steamvr when i try to launch Ghosts of Tabor or The Utility Room (both Unreal engine openxr games).

**Comment by 20PercentRendered** [comment]
An openxr/steamvr/some other update probably borked something, many VR games don't launch inside the headset. Pavlov beta also crashes, and with some configuring starts but doesn't show in the headset. This should be kept an eye on, and maybe some sort of "megathread" made of all the games that are borked.

**Comment by 20PercentRendered** [comment]
I guess the normal non-beta Pavlov uses openvr instead. I feel this issue could potentially be renamed "OpenXR games crash ALVR"

**Comment by 20PercentRendered** [comment]
Actually, seems like this is the same issue as [#1392](https://github.com/alvr-org/ALVR/issues/1392).

**Comment by TandyTnd** [comment]
Same issue, it's not openxr (bonelab is a unity game that uses openxr that won't crash and the godot openxr implementation works fine), it's just the unreal engine implementation.
