### ISSUE TITLE
The utility Room will completely crash steamvr

### ISSUE THREAD

**Issue by TandyTnd** [alvr-org/ALVR#1544]
<Utility Room will completely crash steamvr, no logs are generated. Same thing with the nightly version.>
Environment
Hardware

CPU:
Ryzen 9 5900x
GPU:
RTX 3060
Audio:
Hyper X wireless headphones. I don't stream audio with alvr.
Installation

ALVR Version:
Last nightly version, It also affects 19.10, 19.0, 18.2.3 and the alxr client.
Virtual Desktop doesn't crash, but suffers from significant stutters. 
SteamVR Version:
1.25.7.
Install Type:
.exe

OS Name and Version (winver on Windows or grep PRETTY_NAME /etc/os-release on most Linux distributions):
windows 11, haven't tested windows 10.
Hardware accelerated gpu scheduling enabled or disabled.

**Comment by OscarZunigaLara** [comment]
This is the crash_log.txt 
{"timestamp":"22:47:39.220006400","event_type":{"id":"Log","data":{"severity":"Error","content":"What happened:\npanicked at 'Invalid JSON: Error(\"EOF while parsing a value\", line: 1, column: 0)', C:\\Users\\runneradmin\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\alcro-0.5.4\\src\\chrome.rs:250:62\n\nBacktrace:\n   0: wgpu_render_bundle_push_debug_group\n   1: set_device_openvr_props\n   2: wgpu_render_bundle_push_debug_group\n   3: wgpu_render_bundle_push_debug_group\n   4: wgpu_render_bundle_push_debug_group\n   5: wgpu_render_bundle_push_debug_group\n   6: wgpu_compute_pass_end_pipeline_statistics_query\n   7: wgpu_compute_pass_end_pipeline_statistics_query\n   8: set_device_openvr_props\n   9: HmdDriverFactory\n  10: HmdDriverFactory\n  11: HmdDriverFactory\n  12: wgpu_render_bundle_push_debug_group\n  13: BaseThreadInitThunk\n  14: RtlUserThreadStart\n"}}}
