### ISSUE TITLE
White-screened settings page due to audio polling timeout - Linux

### ISSUE THREAD

**Issue by ElectricTriangle** [alvr-org/ALVR#1548]
If the ALSA device probe initiated by ALVR on startup takes too long, ALVR's configuration menu will timeout and present a white screen to the user. The probe can fail to complete in time if there are a large number of devices in the computer or in .asoundrc and related files

### Hardware
https://linux-hardware.org/?probe=ec45a753a5

### Installation
**ALVR Version**:
v20.0.0-dev02

**SteamVR Version**:
1.25.7

**Install Type**:
Source

**OS Name and Version**:
Devuan GNU/Linux 5 (daedalus/ceres)

![Screenshot_2023-04-01_19-57-33](https://user-images.githubusercontent.com/3101651/229323429-7b3c874b-c33d-4046-9488-f7fbc39ce475.png)
![Screenshot_2023-04-01_19-58-14](https://user-images.githubusercontent.com/3101651/229323430-3c5b45c7-37a4-4a3c-bbe6-daec1f40734c.png)

**Comment by zarik5** [comment]
Any reason you are using ALVR v20.0.0-dev02 instead of latest?
