### ISSUE TITLE
ALVR Getting Blocked By Steam! Any Tips?

### ISSUE THREAD

**Issue by TheOneAndOnlyLumi** [alvr-org/ALVR#1552]
## Description
Every time I launch ALVR, it always says “Due to a recent crash, Steam blocked a few add-ons.” not the exact thing, but it’s what I saw). So I go to SteamVR Settings and try to unblock ALVR Server and Gamepad, then restart SteamVR, but every single time I restart it, ALVR Server and Gamepad are still blocked. I uninstall SteamVR and reinstalled it, nothing happened. So I uninstall Steam itself, nothing also happened, then I uninstall ALVR, still nothing. If anyone who fixed this problem on Windows 10, I would be greatly grateful. I know I’m on Windows 10 and you may think I’ll be able to do airline or link cable on the Oculus Software, but no, my graphics card is incompatible. (Intel Radeon, which doesn’t support VR, sadly.). If anyone has tips, suggestions, or maybe even fixed this problem, then please tell me. 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: idk sorry

**CPU**: AMD or something like that.

**GPU**: Intel Radeon 5500 HD Graphics (At least I think so I’ll update when I see)

**Audio**: i don’t have one. someone deleted it.

### Installation
**ALVR Version**: latest version on windows

**SteamVR Version** idk 

**Install Type**: exe
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 10

**Comment by mittorn** [comment]
Add it to steamvr's  resources/safe_mode_driver_whitelist.json
Note that it will be rewrited on SteamVR update

**Comment by prolificpain** [comment]
is there a fix for this yet?
