### ISSUE TITLE
Everything works fine but no video on quest

### ISSUE THREAD

**Issue by LhymeFruit** [alvr-org/ALVR#1553]
It's not a spec issue because it was working perfectly fine the first three times I use the software but all of a sudden now it's not working,

What I have tried
Reinstalling
Different internet 
Bitrate at 1 
Resolution down
Ethernet 
Restarting

None of it works and there isn't a single help thread that is actually helpful 
My PC is very capable of this and it's NOT A SPEC ISSUE 

All I see on the quest is a stetched image

**Comment by mittorn** [comment]
What OS? Does vrcompositor window show (it should not)? Any logs?

**Comment by Redemption198** [comment]
Did you try to delete the config file? I don't know where it is on Windows.
