### ISSUE TITLE
UDP handshake listening error

### ISSUE THREAD

**Issue by ArranWool** [alvr-org/ALVR#1567]
I have a pico 4 with nightly ALXR from 2023.04.09 (alxr-client-pico-v4.apk). 
ALXR runs OK but only shows a blank screen with cubes representing the controllers (which are tracked). 

ALVR 19.1.0 installed on windows 10. Setup wizard completes OK. SteamVR runs OK and shows the headset active (but NOT controllers). ALVR shows the IP address of the client that I manually configured (which I think means 'connected') as trusted. Both PC and headset are on the same subnet. 

I get in ALVR very often the warning:

UDP handshake listening error: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself. (os error 10040)

Headset is pingable. Disabling firewall doesn't help.

In the ALVR connection tab, I tried changing connection to UDP and increasing buffer sizes but still blank screen in ALXR.

**Comment by zarik5** [comment]
ALVR v19 and v20 are not compatible with ALXR. Install both v20 client and streamer instead.

**Comment by ArranWool** [comment]
Thanks for the quick feedback!

I want to use ALXR for the passthrough. So I guess I need ALVR v18.2.3 for that ?

Or does the ALVR client support passthrough now ? Sorry, bit confused about the two different clients.

**Comment by zarik5** [comment]
Passthrough is planned but not yet implemented. In the meantime you should use ALXR + ALVR v18.
