### ISSUE TITLE
ALVR Relay application [Feature Request]

### ISSUE THREAD

**Issue by imetandy** [alvr-org/ALVR#1589]
Hi! 

I've been running some tests with ALVR and the feasibility of using it for LBE installations. 
The work I'm currently looking at is increasing throughput of VR users in shared space, so predominantly network focused for me. 

I have created a small router device from a Raspberry pi, that I have been testing with Vive Focus 3. I am able to stream from a PC, via my router wirelessly to the Raspberry pi, then route traffic from there to the headset via Ethernet. 

`PC >> My Wireless Router >> My Raspberry Pi >> Headset`

One of the points I want to look at is introducing some compute at the routers side, to potentially upscale the frames that are received from ALVR server, before they travel over the wire to the headset. This would mean lower data transmission rates wirelessly, to remove latency and increase the overall utilized bandwidth. 

I am not a developer, so my coding knowledge is effectively nil, but what I would want to discuss is: 

`Frame is rendered from PC > Frame is encoded by ALVR server > Frame is sent over wireless network > Frame is decoded by "device" > Frame is upscaled by device > Frame is encoded > Frame is sent to headset over wire > frame is decoded by VR headset. `

I understand there will most definitely be latency added by a decode/upscale/encode addition, but my interest is "does this latency here remove latency elsewhere e.g. network, encoding on PC (due to smaller initial frame size). 

This is potentially more of a discussion point rather than a direct feature request, if there is a particular channel on the Discord that this would be worth raising in then please let me know. 

Cheers for the great work so far on this application, its been great getting to grips with it.

**Comment by zarik5** [comment]
What you are asking is basically impossible. ALVR sends frames using h264 or HEVC NAL frames, which is a format compressed both spatially and temporally. if you want to have a device that intercepts frames you would need to decode, upscale and then re-encode and this wold basically double the latency, rendering the experience unusable. We are already pondering the feasibility of adding upscaling on the streamer or client.

**Comment by imetandy** [comment]
Thanks @zarik5 for your reply! I was always under the impression it would add latency, but wasn't aware by how much. 

Upscaling on the streamer end for single person use would be amazing, but in an LBE context would be hampered by network bandwidth when concerned with multiple clients competing for bandwidth. 
Upscaling on the client would definitely be the sweet spot, but then we are obviously hampered by each individual headsets ability to upscale on the available hardware. 

Following on in this case (which is where this rabbit hole of research is taking me) would be a Linux client receiver which would simply connect to the headset with a wired USB connection. This would remove the "relay" step as you described, but could also be utilized as an upscale device before frames hit the headset, but I'm aware this basically becomes an entirely different application from ALVRs current roadmap. 

I've tested ALVR over USB cable successfully in the past but have found it to disconnect during longer VR sessions.

**Comment by zarik5** [comment]
ALVR uses a module called alvr_client_core, used to receive packets form the server, which can run on any hardware and OS, but currently it can decode frames only on android. You could start from here, but there's quite a bit of work to do, among which a completely new client running on the headset.

**Comment by zarik5** [comment]
ALVR uses a module called alvr_client_core, used to receive packets form the server, which can run on any hardware and OS, but currently it can decode frames only on android. You could start from here, but there's quite a bit of work to do, among which a completely new client running on the headset.
