### ISSUE TITLE
VM or Docker image for quickstart

### ISSUE THREAD

**Issue by auwsom** [alvr-org/ALVR#1590]
These are the rough untested commands I used starting from an official Arch VM to be run once:
github.com/archlinux/arch-boxes
https://geo.mirror.pkgbuild.com/images/v20230404.140600/Arch-Linux-x86_64-basic-20230404.140600.qcow2
```
#!/bin/bash
set -xe

pacman -S pacman -Syu
pacman -S linux-firmware # for wifi cards
pacman -S ntfs-3g # for windows comaptible storage disks
pacman -S plasma-desktop sddm
pacman -S konsole kscreen plasma-nm gnome-disks-utility htop dolphin firefox vim wget bc dkms fuse
pacman -S steam
pacman -S --needed base-devel git make gcc # for nvidia drivers
pacman -S linux-headers # "ERROR: Unable to find the kernel source tree for the currently running kernel"
pacman -S mesa # amd drivers. https://wiki.archlinux.org/title/AMDGPU
pacman -S dnsmasq # for hotspot
pacman -S sidequest-git # for hotspot
  
git clone https://aur.archlinux.org/yay.git
cd yay && makepkg -si
yay -S proton # https://linuxhint.com/install_steam_arch_linux/

# nvidia-xconfig # 
# systemctl restart sddm # 
#sudo mv /usr/lib/libstfl.so* # “error: failed to commit transaction (conflicting files)” . # proton wouldnt build without replacing these
# steam-native-runtime?
```
Here is an Arch Docker container for Distrobox:
https://github.com/89luca89/distrobox/blob/main/docs/compatibility.md#host-distros
quay.io/toolbx-images/archlinux-toolbox

**Comment by ShootingKing-AM** [comment]
How is this intended to be useful for this repo ? I don't see you installing ALVR anywhere in the DockerFile. 
If you can make DockerFiles for windows n linux-flavours with SteamVR installed + Ports exposed for ALVR that would be awesome and very useful for E2E testing !

**Comment by auwsom** [comment]
I have been using the appimage form of ALVR nightly corresponding to an exact client version. So correct, you wouldn't see an installation for it.
