### ISSUE TITLE
[v20 nightly] SteamVR crash - Error writing IPC request. Error: The pipe has been closed.

### ISSUE THREAD

**Issue by thehhmdb** [alvr-org/ALVR#1593]
## Description
Using the v20 nightly build I'm frequently getting SteamVR crashes and the following error:
Error writing IPC request. Error: The pipe has been closed.
![image](https://user-images.githubusercontent.com/68663972/233799776-142aa05a-f6c1-44d6-b5b3-27af3ad74eac.png)

This doesn't happen when I go back to using the latest v18 build 

## Hardware
Intel CPU and Nvidia GPU, Pico 4 headset, Windows 11

**Comment by zarik5** [comment]
Did you close the issue because you resolved your problem? How did you fix it?

**Comment by thehhmdb** [comment]
I think it's working fine now as I haven't had a crash for a couple of days. I upgraded the ALVR server to a later version and I also noticed SteamVR updated too.

So hopefully it's fixed, but if it starts to error again I'll reopen.

Thanks

**Comment by Knowitall999** [comment]
Its still an issue.  It goes all kinds of messed up on linux after that warning.
