### ISSUE TITLE
I can't see my sceren/desktop in steam vr.

### ISSUE THREAD

**Issue by Corbsss** [alvr-org/ALVR#1595]
## Description
I can't see my computers screen/desktop when going to the "view desktop/screen" button in steam vr

## General Troubleshooting
- [Y] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [Y] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: 11th Gen Intel(R) Core(TM) i5-11300H

**GPU**: NVIDIA GeForce RTX 3050 Laptop GPU

**Audio**: Built in quest 2 speakers

### Installation
**ALVR Version**: Latest.

**SteamVR Version**: Latest.

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [Y] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 11, 22H2

**Comment by ThiagoRibas-dev** [comment]
I'm pretty sure that happens due to the GPU switching function of the notebook.
Does your model allow you to disable the IGPU in the bios? If so, try doing that.

**Comment by Vixea** [comment]
This isn't an ALVR bug as ALVR has no input there, closing
