### ISSUE TITLE
ALVR panic on startup

### ISSUE THREAD

**Issue by orangpelupa** [alvr-org/ALVR#1596]
## Description

Installed ALVR19 1 0, upgraded from 18 2 1. but at launch it shows a its panicked. https://imgur.com/a/gCASP6U

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
what i have not tried is building alvr from source by myself
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 5600x
**GPU**:
RTX 3070 LHR
**Audio**:
HDMI audio
DisplayPort Audio
VB virtual audio cables (there are 8)
Kinect microphone
Realtek digital output
dualsense audio output
dualsense mic
xbox 360 controller mic
### Installation
**ALVR Version**:
19.1.0
**SteamVR Version**:
1.25.7
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 Version 22H2 (0S Build 22621.1555)

**Comment by Vixea** [comment]
The image is too low quality to see what the error is
