### ISSUE TITLE
ALVR 15 Linux trouble

### ISSUE THREAD

**Issue by kst21** [alvr-org/ALVR#1598]
## Description

My system does not support glibc>2.28, I managed to install only ALVR 15.1. At startup, a message appears asking you to start SteamVR at least once. SteamVR is installed and I ran it. Maybe I'm doing something wrong? Sorry for my English)

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:
15.1/15.0
**SteamVR Version**:
1.14
**Install Type**:
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Debian buster

**Comment by zarik5** [comment]
We are still figuring out how to build ALVR with an earlier version of Ubuntu on CI (automated github build), there are issues with Vulkan headers.

**Comment by kst21** [comment]
> We are still figuring out how to build ALVR with an earlier version of Ubuntu on CI (automated github build), there are issues with Vulkan headers.

Thanks for your reply. Are there ways to run ALVR on glibc<=2.28 (debian 10 buster)

**Comment by Kirottu** [comment]
I don't see why you couldn't just build it yourself.

**Comment by kst21** [comment]
> I don't see why you couldn't just build it yourself.

Maybe I'm doing something wrong but alvr ~15.0 shows me to start SteamVR at least once (SteamVR is installed and I ran it). ALVR 16-17 from source shows an error about rhai. ALVR 18-20 portable versions and AppImages require glibc>2.28.  ALVR 18-20 from source shows an error about linking with 'cc'.

**Comment by kst21** [comment]
> ```shell
> cargo xtask build-streamer --release --platform linux
> ```

Thanks for the help.
It's my step-by-step:
1) Step: cargo xtask prepare-deps --platform linux --no-nvidia
1.1) first error: nasm/yasm not found or too old. Use --disable-x86asm for a crippled build
sudo apt-get install yasm
1.2) second error: ERROR: libdrm not found using pkg-config
sudo apt install libdrv-dev
1.3) Third error: ERROR: vulkan requested but not found
2) After that i'm going to install vulkan sdk from https://www.lunarg.com/vulkan-sdk/
2.1) I chose SDK Tarball 198 version cuz other versions require glibc>2.28 and install it https://vulkan.lunarg.com/doc/sdk/1.2.198.1/linux/getting_started.html
But it did not help
2.2) ln -s all files from /vulkan/1.2.198.1/x86_64/include/ to /usr/local/include helped solve the problem and cargo xtask prepare-deps --platform linux --no-nvidia finished with status Done
3) Next step: cargo xtask build-streamer --release --platform linux
3.1) First error: No package 'jack' found
sudo apt install libjack-dev
3.2) Second error: could not find system library 'alsa' required by the 'alsa-sys' crate
sudo apt-get install libasound2-dev
3.3) Third error: https://pastebin.com/djD3a7fz
sudo apt install libx264-dev
3.4) Next error: https://pastebin.com/yA2BESUQ
sudo apt install libclang-dev
3.5) And my favorite error https://pastebin.com/pRabUPvY

**Comment by Kirottu** [comment]
Welp, don't know about that. It could be that you just need to be on a distro with newer packages to use a recent version of ALVR.
