### ISSUE TITLE
Discord blocks ALVR

### ISSUE THREAD

**Issue by NintyS** [alvr-org/ALVR#1602]
## Description

When discord once turned on then ALVR dashboard will don't work on Linux, I tested on Ubuntu and Mint

I noticed that when I have open discord then ALVR don't opens or is white blank.

I noticed this when I tried to turn it on and dashboard was blank, but when I restart PC without turning on Discord ALVR works ( if I turn on ALVR and second Discord then everything is OK )

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
I9-9900K

**GPU**:
GTX1070

**Audio**:

### Installation
**ALVR Version**:
Appimage.

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Linux Min 21

PS. I will edit it later I do it when I remember - I wanted to do it weeks ago.

**Comment by b-derouet** [comment]
I'm using Linux Mint 21 and I never got this behavior 🤔

**Comment by zarik5** [comment]
Are you using v19 stable or v20 nightly? Please use the nightly version on linux.

**Comment by Vixea** [comment]
Closing this in prep on V20 release
