### ISSUE TITLE
Where do I find the pico apk? I only see apk for oculus and quest

### ISSUE THREAD

**Issue by AquaCobell** [alvr-org/ALVR#1607]

**Comment by zarik5** [comment]
In the nightly repo: https://github.com/alvr-org/ALVR-nightly/releases

**Comment by AquaCobell** [comment]
[alvr_client_android.apk](https://github.com/alvr-org/ALVR-nightly/releases/download/v20.0.0-dev11%2Bnightly.2023.05.04/alvr_client_android.apk) is for pico?

**Comment by zarik5** [comment]
Yes
