### ISSUE TITLE
SteamVR crashes on client connection (Kubuntu/Ubuntu)

### ISSUE THREAD

**Issue by wld4y** [alvr-org/ALVR#1611]
everything works great before that, alvr detects steam, steam detects the alvr headset. but if my quest connects, steamvr crashes with the "critical error" message. im on kubuntu 23.04 (basically just ubuntu 23.04 but with kde as the desktop environment) with an rtx 2060 (with nvidia drivers).

**Comment by Vixea** [comment]
Don you have cuda installed and modesetting enabled
