### ISSUE TITLE
About Eye Tracking 

### ISSUE THREAD

**Issue by Hope10086** [alvr-org/ALVR#1612]
I asked this question before ALVR did not support eye tracking and face tracking（#1503）. 
I would now like to know how eye tracking is currently supported and  how to use OpenXR extensions (e.g. XR_EXT_eye_gaze_interaction, XR_FB_face_tracking, XR_HTC_facial_tracking, etc.) in your latest version of ALVR. 
And if the current eye tracking functionality is fully usable, I plan to modify a visualization that transfers Gaze_Pose to the server for regions of interest.

A little more to add:  
I implemented the above functionality in korejan's ALXR last month, but I found that the server used in it (ALVR18.23) had a handle exception in some applications. We also had a need for screen recording using a new version of NVIDIA's Video coding SDK, so we wanted to do it again with the latest ALVR. However, I found that your clients were not compatible and the source code was quite different.

**Comment by zarik5** [comment]
Here is the code for the face tracking sinks: https://github.com/alvr-org/ALVR/blob/master/alvr/server/src/face_tracking.rs

We currently implement FB and HTC eye and face tracking extensions. The combined eye gaze extension is not implemented, since to enable it we have to destroy and recreate the XR session and I wasn't able to do it successfully. ALXR doesn't have this problem since it always enables everything (eye, face, passthrough) with significant more battery drain and worse performance.

**Comment by Hope10086** [comment]
I have found  your changes for eye tracking     by [Add support for logging eye and face tracking data](https://github.com/alvr-org/ALVR/commit/c598bd7633e0497798fda1ae1a68f2f595cd7bf0 )  and [Add support for VRChat Eye OSC + VRCFaceTracking (in progress)](https://github.com/alvr-org/ALVR/commit/8d9b5d613778d303229db8523e8ebeba4a90d935).  So you're using an eye tracking extension provided by Meta or HTC instead of khronos. I wonder if ALVR will also gradually use the OpenXR SDK? Meta has announced that it will no longer maintain the VR SDK. But there seems to be no need for ALXR.

**Comment by Hope10086** [comment]
A little more to add:
I implemented the above functionality in korejan's ALXR last month, but I found that the server used in it (ALVR18.23) had a handle exception in some applications. We also had a need for screen recording using a new version of NVIDIA's Video coding SDK, so we wanted to do it again with the latest ALVR. However, I found that your clients were not compatible and the source code was quite different.

**Comment by zarik5** [comment]
> So you're using an eye tracking extension provided by Meta or HTC instead of khronos. I wonder if ALVR will also gradually use the OpenXR SDK? Meta has announced that it will no longer maintain the VR SDK. But there seems to be no need for ALXR.

There is some confusion here. ALVR switched to OpenXR a while ago. ALVR is using XR_FB_face_tracking, XR_FB_eye_tracking_social , XR_HTC_facial_tracking, but not XR_EXT_eye_gaze_interaction.

> We also had a need for screen recording using a new version of NVIDIA's Video coding SDK, so we wanted to do it again with the latest ALVR.

ALVR supports video recoding since v20. you can access it from the Debug tab.
