### ISSUE TITLE
SteamVR Crashing On Launch

### ISSUE THREAD

**Issue by chaseyrt** [alvr-org/ALVR#1622]
## Description

SteamVR Crashes on launch after updating to most recent ALVR version. The SteamVR dump shows driver_alvr_server.dll as the image. (Dump Analysis Linked Here >[https://pastebin.com/vuZ3TRms](url))

## General Troubleshooting
- [ X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 5 2600
**GPU**:
GeForce GTX 1660 Super
**Audio**:
Voicemeeter Banana - Output
VB-CABLE - Input
### Installation
**ALVR Version**:
19.1.1
**SteamVR Version**:
1.25.8
**Install Type**:
- [ X] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 Build 19045

**Comment by Vixea** [comment]
Try reinstalling ALVR it looks like the file might be corrupted

**Comment by chaseyrt** [comment]
Tried reinstalling ALVR, Tried Reinstalling SteamVR. Haven't done both at the same time.

**Comment by chaseyrt** [comment]
@

**Comment by chaseyrt** [comment]
We also tried deleting the offending DLL and having ALVR repair itself, which also didn't work.
