### ISSUE TITLE
ALVR Launches to Blank Screen or not-found page:

### ISSUE THREAD

**Issue by Arucied** [alvr-org/ALVR#1625]
## Description
After launching once as described in the install instructions, i then attempt to run the .appimage file. This launches to a blank screen, or sometimes to a "page not found" usually suggesting the appimage crashes. Shortly thereafter steamVR comes up with an error saying that it may need to reinstall steamVR.
If it is a blank page, doing a refresh on it results in a not found page as seen. I included the steamVR error that happens after this as well.
![image](https://github.com/alvr-org/ALVR/assets/98767002/273d3207-ad47-4f45-a803-c9c12f59a7e9)

## General Troubleshooting
I've attempted changing to the linux-specific beta client, at which point it would crash faster.
I've verified cache and it did redownload the new file, launched steamVR by itself again, closed it, and then launched ALVR appimage to the same results.

I haven't found much information on this or other troubleshooting steps, outside of this suggesting ALVR is likely crashing doing whatever setup it needs with steamVR; as it never makes it to that dashboard page.

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 9 3900X 12-Core Processor            
    CPU Family:  0x17
    CPU Model:  0x71
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4672 Mhz
    24 logical processors
    12 physical processors

**GPU**:
Driver:  NVIDIA Corporation NVIDIA GeForce RTX 3090/PCIe/SSE2
    Driver Version:  4.6.0 NVIDIA 530.41.03
    OpenGL Version: 4.6
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 144 Hz

**Audio**: 

### Installation
**ALVR Version**: 19.1.1 (ALVR-x86_64.AppImage)

**SteamVR Version**: 1.25.8

**Install Type**: appimage
**OS Name and Version**:PikaOS 22.10

**Comment by Vixea** [comment]
Closing because it is a version out of date
