### ISSUE TITLE
Feature Request: Head rotation offset

### ISSUE THREAD

**Issue by bjoern-tantau** [alvr-org/ALVR#1626]
Would it be possible to make a head rotation offset configurable, like the head position? It would enable me to play on my Quest 1 while laying down. Entering some numbers in degrees would be ideal, but I'd also be comfortable if it used some other unit.

Laying down mode had just been added to the Quest 2 firmware and I was pretty bummed out that it wasn't available for the Quest 1. If it was added to ALVR I could at least have it in PCVR.

**Comment by zarik5** [comment]
ALVR added support for tilt mode in february, but you need to use the nightly v20 version.

**Comment by bjoern-tantau** [comment]
Great! Now I just have to get the nightly to run properly on my Linux system, but that's a different problem.
