### ISSUE TITLE
window size is unreasonably large with no way of changing it

### ISSUE THREAD

**Issue by Femratthecoolone** [alvr-org/ALVR#1627]
on the latest version of ALVR available for LINUX running on STEAMOS on the steamdeck
the window GUI elements are unreasonably large making it IMPOSSIBLE to even THINK of using the software
can i fix this issue?
it also persists into the nightly version

**Comment by bjoern-tantau** [comment]
![image](https://github.com/alvr-org/ALVR/assets/8307357/7a3a6b30-27b1-4c20-801f-ed59df9a8ff7)

Here's a screenshot from the current nightly Appimage. The output on the commandline is

```
$ ./ALVR-x86_64.AppImage 
[12:32:45.538711108 ERROR alvr_server_io] Error while extrapolating session. Old session.json is stored as session_old.json. At alvr/session/src/lib.rs:188
[12:32:45.636296884 INFO winit::platform_impl::platform::x11::window] Guessed window scale factor: 4.5
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
```

**Comment by bjoern-tantau** [comment]
As a workaround you can set `WINIT_X11_SCALE_FACTOR="1"` before running ALVR. See https://github.com/rust-windowing/winit/issues/2231

**Comment by zarik5** [comment]
Thank you! I might make a PR integrating this tomorrow.

**Comment by zarik5** [comment]
This should be fixed in the next nightly.

**Comment by zarik5** [comment]
@Femratthecoolone did you try the last nightly?

**Comment by Femratthecoolone** [comment]
> Member

not yet as of now i will in a bit right now im doing other things

**Comment by Vixea** [comment]
Ping

**Comment by Vixea** [comment]
Assuming as fixed makes no sense not to be anyway
