### ISSUE TITLE
hello alvr product i have an issue for the last alvr version 19.1.1.0 when i launch alvr it show this ( look down for it )

### ISSUE THREAD

**Issue by nicochocko** [alvr-org/ALVR#1631]
![help pls](https://github.com/alvr-org/ALVR/assets/134150847/37933cea-bae2-43c1-a638-44cf5e1f542f)

could you try to solve it because i really need to play in vr if you do that ill be happy

thx again

**Comment by zarik5** [comment]
This is solved by installing Chrome.

**Comment by nicochocko** [comment]
thx again
