### ISSUE TITLE
[WebPage Issue]: ALVR Website is broken or not found

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [alvr-org/ALVR#1638]
It look like there is a bug on website issue. https://alvr-org.github.io/ It look like it is broken or not found.

**Comment by zarik5** [comment]
The website was never really developed. I'm feeling like we don't need it for now.

**Comment by BrandonWanHuanSheng** [comment]
![Screenshot (1163)](https://github.com/alvr-org/ALVR/assets/118059864/41bd5641-e5b2-4652-98c1-383d8f04c741)
Can you remove the broken link or not found URL?

**Comment by zarik5** [comment]
Sure

**Comment by Vixea** [comment]
Closing now as it's about to be fixed
