### ISSUE TITLE
Green screen when didn't run ALVR first in quest

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1640]
## Description
![image](https://github.com/alvr-org/ALVR/assets/44261958/be824af6-ca44-4d99-958f-a919ca1e2292)

After running SteamVR in ALVR first, turning on Quest 2 and running ALVR keeps the green screen.
No error messages and logs.

This bug occurs both on Windows and Linux.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Ryzen 7 5800H

**GPU**: Radeon RX 5600M

### Installation
**ALVR Version**: v20.0.0-dev12+nightly.2023.05.09
Please don't tell me it's not nightly up to date.
This's an old bug, and many issues have become **stale**.

**SteamVR Version**: 1.25.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Windows 11, Ubuntu 18.04.2, Ubuntu 22.04, Ubuntu 22.10

**Comment by Vixea** [comment]
is this still an issue?

**Comment by Kieaer** [comment]
No. I haven't seen this issue happen since v20.

**Comment by dickredone** [comment]
![image](https://github.com/alvr-org/ALVR/assets/32758187/45ae24b0-74a0-497f-852d-4801a66d2d44)
我在连接时也出现了类似问题
