### ISSUE TITLE
ALVR Infinite loading when ALVR is close and restarted in Quest

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1641]
## Description
ALVR Infinite loading when ALVR is close and restarted in Quest.
Reproduction is also really simple and 100% bug reproduction success rate.
This bug is presumably from ALVR 1.8.0.0

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

Quest 2

### Installation
**ALVR Version**: v20.0.0-dev12+nightly.2023.05.09
Please don't tell me it's not nightly up to date.
This's an old bug, and many issues have become **stale**.

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**Comment by Kieaer** [comment]
Sound working but not work tracking and screen
ALVR log spams video overflow messages.

**Comment by zarik5** [comment]
I was trying really hard to reproduce this bug yesterday but I was unsuccessful. The funny thing is that i was able to reproduce this some other times, at random. I was testing on a Quest 2. Can you please share your hardware?

**Comment by zarik5** [comment]
I'm pretty sure this has been fixed for the v20 release.

**Comment by Kieaer** [comment]
In the week since ALVR v20, this issue has not reoccurred.
Solved
