### ISSUE TITLE
Very low bitrate when use adaptive mode

### ISSUE THREAD

**Issue by Kieaer** [alvr-org/ALVR#1647]
## Description
![image](https://github.com/alvr-org/ALVR/assets/44261958/a79a0077-2a85-49a4-88ee-f5347918a938)
![image](https://github.com/alvr-org/ALVR/assets/44261958/bc382c6e-3d26-4d01-8179-d99381b1ab73)

This problem seems to be related to https://github.com/alvr-org/ALVR/issues/1536.
Link speeds range from 860 Mbps to 1.2 Gbps on average.

Constant mode is fine.
However, like https://github.com/alvr-org/ALVR/issues/1536, the bitrate is not constant at 180Mbps, but equally drops from 0.01 to 5Mbps.

Reproduction is also really simple and 100% bug reproduction success rate.
This bug occurs both on Windows and Linux.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Ryzen 7 5800H

**GPU**: Radeon RX 5600M

### Installation
**ALVR Version**: v20.0.0-dev12+nightly.2023.05.09
Please don't tell me it's not nightly up to date.
This's an old bug, and many issues have become **stale**.

**SteamVR Version**: 1.25.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Windows 11

**Comment by Kieaer** [comment]
![image](https://github.com/alvr-org/ALVR/assets/44261958/75457173-f1ed-4d9f-9a10-a3e3cb01cb75)
![image](https://github.com/alvr-org/ALVR/assets/44261958/fb9a719b-a90f-4697-b0b1-c9846b874470)

Although this setting looks fine, the bitrate gets lower and lower when the headset is not moving, causing the same problem as above.

**Comment by Vixea** [comment]
You don't have filler data enabled, this is user error

**Comment by Kieaer** [comment]
@Vixea enable filter data isn't solve this problem.  So I set it to the default value.

**Comment by zarik5** [comment]
@Kieaer disable "Decoder latency fixer". This is the cause of the bitrate decreasing over time.

**Comment by Kieaer** [comment]
It was solved in disable decoder latency fixer.
