### ISSUE TITLE
Dashboard not scaled on 4k resolution

### ISSUE THREAD

**Issue by thankjura** [alvr-org/ALVR#1648]
## Description
Dashboard is small on 4k resolution

After remove [this line](https://github.com/alvr-org/ALVR/blob/92ec3d04a9d4ee4a553af1240a41bdb5ddccc8ad/alvr/dashboard/src/main.rs#L29) problem disappear

## Environment

Gnome 44, Gentoo linux

### Hardware
**HW**: https://linux-hardware.org/?probe=95231653d0

### Installation
**ALVR Version**: https://github.com/alvr-org/ALVR/commit/92ec3d04a9d4ee4a553af1240a41bdb5ddccc8ad

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [*] Source

**OS Name and Version**: Gentoo Linux

**Comment by Vixea** [comment]
This was a workaround for the steam deck the other solution would be to use Wayland

**Comment by Vixea** [comment]
Which I think can be done with this `WINIT_UNIX_BACKEND=wayland`

**Comment by Vixea** [comment]
Eh that's not necessary anymore it should now only do it on the Steamdeck

**Comment by Vixea** [comment]
In fact this can be closed
