### ISSUE TITLE
alvr appimage does not run(bindgen)

### ISSUE THREAD

**Issue by mrhedx** [alvr-org/ALVR#1649]
## Description
alvr does not start for me the appimage on slackware64 current  

Sat May 27 2023 23:49:27.505419 - Unable to load driver alvr_server from /tmp/.mount_ALVR-x9lyaWg/usr/lib64/alvr/bin/linux64/driver_alvr_server.so (/tmp/.mount_ALVR-x9lyaWg/usr/lib64/alvr/bin/linux64/driver_alvr_server.so: undefined symbol: x264_encoder_open_163)
Sat May 27 2023 23:49:27.505435 - ASSERT: "DriverManager alvr_server load error /tmp/.mount_ALVR-x9lyaWg/usr/lib64/alvr/bin/linux64/driver_alvr_server.so: undefined symbol: x264_encoder_open_163u" at /data/src/common/vrcommon/drivermanager.cpp:411.

it does not compile either for me i get this error

  --- stderr
  clang diag: cpp/alvr_server/bindings.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  thread 'main' panicked at '"AlvrButtonValue_(anonymous_union_at_cpp/alvr_server/bindings_h_88_5)" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
9

  stack backtrace:
     0:     0x5624373a4869 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd942f93f90a12975
     1:     0x5624373da2fe - core::fmt::write::h3e809fe7db83f902
     2:     0x5624373aef45 - std::io::Write::write_fmt::h77acc5d2ffbf81e5
     3:     0x5624373a4625 - std::sys_common::backtrace::print::h176438a467b8c44b
     4:     0x5624373b782f - std::panicking::default_hook::{{closure}}::h69845dc8ad8529e0
     5:     0x5624373b74ec - std::panicking::default_hook::h39ec3bc249e5a063
     6:     0x5624373b805c - std::panicking::rust_panic_with_hook::h74d15b4a49499fd9
     7:     0x5624373a5769 - std::panicking::begin_panic_handler::{{closure}}::he74bdd83890c6eaf
     8:     0x5624373a49bc - std::sys_common::backtrace::__rust_end_short_backtrace::h0ffc71765a8f6045
     9:     0x5624373b7bf2 - rust_begin_unwind
    10:     0x562436d92593 - core::panicking::panic_fmt::h03567d78a8d3dde9
    11:     0x5624372e5f64 - proc_macro2::fallback::validate_ident::h1149e736111cbcb7
    12:     0x5624372e5d79 - proc_macro2::fallback::Ident::_new::hc2d5038dbbd6587a
    13:     0x5624372e5dcf - proc_macro2::fallback::Ident::new::hed76381862844e01
    14:     0x5624372e2646 - proc_macro2::imp::Ident::new::hd44952c959901179
    15:     0x5624372f6778 - proc_macro2::Ident::new::h481ba49245001801
    16:     0x562436db658f - bindgen::ir::context::BindgenContext::rust_ident_raw::he51d5fbd11ce2512
    17:     0x562436db6225 - bindgen::ir::context::BindgenContext::rust_ident::h527e9755b6e9be88
    18:     0x562436e524e1 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hd4a73b55d9ac64ca
    19:     0x562436e8b81f - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::ha1c60d2d1d268432
    20:     0x562436e8b5f2 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
    21:     0x562436e55f4b - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hd4a73b55d9ac64ca
    22:     0x562436e8b81f - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::ha1c60d2d1d268432
    23:     0x562436e8b5f2 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
    24:     0x562436ed950a - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h2775387eb9e439ad
    25:     0x562436e0ebb0 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h658142632b5c11cd
    26:     0x562436e8b5d6 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
    27:     0x562436ee6ac8 - bindgen::codegen::codegen::{{closure}}::h5daf186aa0e479d5
    28:     0x562436db8c32 - bindgen::ir::context::BindgenContext::gen::hd9e5c4be0aa894c4
    29:     0x562436ee5ccd - bindgen::codegen::codegen::hb93f49e2d85874fe
    30:     0x562436f133f0 - bindgen::Bindings::generate::hbe105ad3958e03c7
    31:     0x562436f107f6 - bindgen::Builder::generate::hc82c7ed67649d80a
    32:     0x562436d955df - build_script_build::main::h14d55d1ab06cb196
    33:     0x562436d944c3 - core::ops::function::FnOnce::call_once::hf637f528b32b0291
    34:     0x562436d97659 - std::sys_common::backtrace::__rust_begin_short_backtrace::h470fe68a86da8509
    35:     0x562436d96fe9 - std::rt::lang_start::{{closure}}::hc729540c8d38f3ff
    36:     0x5624373b6654 - std::rt::lang_start_internal::h7324ac312930acbf
    37:     0x562436d96fc7 - std::rt::lang_start::h93ecb9463b08cd4d
    38:     0x562436d95e15 - main
    39:     0x7fe4313b76b7 - __libc_start_call_main
    40:     0x7fe4313b7775 - __libc_start_main_alias_1
    41:     0x562436d92bc1 - _start
                                 at /root/glibc-43b5a0678dbab633ca2647a0ebb9e353/glibc-2.37/csu/../sysdeps/x86_64/start.S:115
    42:                0x0 - <unknown>
bash-5.2#

**Comment by Vixea** [comment]
Whoo, Slackware I know that distro is still going but I have a small feeling it's either going to be easy or (sarcasm ahead) fun
(haven't looked past that)

**Comment by Vixea** [comment]
Your missing your system specs that would be helpful :D

**Comment by mrhedx** [comment]
linux-6.3.2-Sexytime #2 SMP PREEMPT_DYNAMIC Wed May 17 06:59:07 EDT 2023 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 33
model name      : AMD Ryzen 9 5900X 12-Core Processor
stepping        : 2
microcode       : 0xa20120a
cpu MHz         : 2200.000
cache size      : 512 KB
physical id     : 0
siblings        : 24
core id         : 0
cpu cores       : 12
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
bugs            : sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 8399.88
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]

**Comment by Vixea** [comment]
gpu?

**Comment by mrhedx** [comment]
amd radeon rx 6950 xt

**Comment by Vixea** [comment]
could u run vainfo?

**Comment by mrhedx** [comment]
vainfo
Trying display: wayland
Trying display: x11
vainfo: VA-API version: 1.18 (libva 2.18.2)
vainfo: Driver version: Mesa Gallium driver 23.1.1 for AMD Radeon RX 6950 XT (navi21, LLVM 16.0.4, DRM 3.52, 6.3.2-Sexytime)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
bash-5.2#

**Comment by Vixea** [comment]
Hmm unsure could you try building it yourself make sure it's the right version or it won't work

**Comment by mrhedx** [comment]
tried building it and i get 
--- stderr
clang diag: cpp/alvr_server/bindings.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
thread 'main' panicked at '"AlvrButtonValue_(anonymous_union_at_cpp/alvr_server/bindings_h_88_5)" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9
9

stack backtrace:
0: 0x5624373a4869 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd942f93f90a12975
1: 0x5624373da2fe - core::fmt::write::h3e809fe7db83f902
2: 0x5624373aef45 - std::io::Write::write_fmt::h77acc5d2ffbf81e5
3: 0x5624373a4625 - std::sys_common::backtrace::print::h176438a467b8c44b
4: 0x5624373b782f - std::panicking::default_hook::{{closure}}::h69845dc8ad8529e0
5: 0x5624373b74ec - std::panicking::default_hook::h39ec3bc249e5a063
6: 0x5624373b805c - std::panicking::rust_panic_with_hook::h74d15b4a49499fd9
7: 0x5624373a5769 - std::panicking::begin_panic_handler::{{closure}}::he74bdd83890c6eaf
8: 0x5624373a49bc - std::sys_common::backtrace::__rust_end_short_backtrace::h0ffc71765a8f6045
9: 0x5624373b7bf2 - rust_begin_unwind
10: 0x562436d92593 - core::panicking::panic_fmt::h03567d78a8d3dde9
11: 0x5624372e5f64 - proc_macro2::fallback::validate_ident::h1149e736111cbcb7
12: 0x5624372e5d79 - proc_macro2::fallback::Ident::_new::hc2d5038dbbd6587a
13: 0x5624372e5dcf - proc_macro2::fallback::Ident:new:hed76381862844e01
14: 0x5624372e2646 - proc_macro2:imp:Ident:new:hd44952c959901179
15: 0x5624372f6778 - proc_macro2::Ident:new:h481ba49245001801
16: 0x562436db658f - bindgen::ir::context::BindgenContext::rust_ident_raw::he51d5fbd11ce2512
17: 0x562436db6225 - bindgen::ir::context::BindgenContext::rust_ident::h527e9755b6e9be88
18: 0x562436e524e1 - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hd4a73b55d9ac64ca
19: 0x562436e8b81f - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::ha1c60d2d1d268432
20: 0x562436e8b5f2 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
21: 0x562436e55f4b - <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen::hd4a73b55d9ac64ca
22: 0x562436e8b81f - <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen::ha1c60d2d1d268432
23: 0x562436e8b5f2 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
24: 0x562436ed950a - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}::h2775387eb9e439ad
25: 0x562436e0ebb0 - <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::h658142632b5c11cd
26: 0x562436e8b5d6 - <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen::hab20553eb04547ef
27: 0x562436ee6ac8 - bindgen::codegen::codegen::{{closure}}::h5daf186aa0e479d5
28: 0x562436db8c32 - bindgen::ir::context::BindgenContext::gen::hd9e5c4be0aa894c4
29: 0x562436ee5ccd - bindgen::codegen::codegen::hb93f49e2d85874fe
30: 0x562436f133f0 - bindgen::Bindings::generate::hbe105ad3958e03c7
31: 0x562436f107f6 - bindgen::Builder::generate::hc82c7ed67649d80a
32: 0x562436d955df - build_script_build::main::h14d55d1ab06cb196
33: 0x562436d944c3 - core::ops::function::FnOnce::call_once::hf637f528b32b0291
34: 0x562436d97659 - std::sys_common::backtrace::__rust_begin_short_backtrace::h470fe68a86da8509
35: 0x562436d96fe9 - std::rt::lang_start::{{closure}}::hc729540c8d38f3ff
36: 0x5624373b6654 - std::rt::lang_start_internal::h7324ac312930acbf
37: 0x562436d96fc7 - std::rt::lang_start::h93ecb9463b08cd4d
38: 0x562436d95e15 - main
39: 0x7fe4313b76b7 - __libc_start_call_main
40: 0x7fe4313b7775 - __libc_start_main_alias_1
41: 0x562436d92bc1 - _start
at /root/glibc-43b5a0678dbab633ca2647a0ebb9e353/glibc-2.37/csu/../sysdeps/x86_64/start.S:115
42: 0x0 -

**Comment by Vixea** [comment]
this issue doesn't happen on any other distro could you try unsetting and c/C++ compiler flags(shrug)

**Comment by mrhedx** [comment]
seems like one of the errors are with vulkan   clang diag: layer/layer.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  thread 'main' panicked at '"VkLayerInstanceCreateInfo_(unnamed_union_at_/usr/include/vulkan/vk_layer_h_125_5)" is not a valid Ident', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.47/src/fallback.rs:756:9

**Comment by qqshnep** [comment]
I got the same error on win10 , and have solved it by downgrade llvm version from 16.0.3 to 15.0.7。 hope help。

choco uninstall llvm
choco install llvm --version 15.0.7

**Comment by mrhedx** [comment]
commpiled just fine with llvm-13-0.0.0 but broke compatibility with steam vrlibraries for me refuses to compile with anything above llvm-15

**Comment by zarik5** [comment]
@nowrep i think you should take a look at this.

@qqshnep can you please paste here the error you get with llvm 16?

**Comment by mrhedx** [comment]
> @nowrep i think you should take a look at this.
> 
> @qqshnep can you please paste here the error you get with llvm 16?

allready have above

**Comment by zarik5** [comment]
@mrhedx Don't worry, I was not talking to you, I was asking help to others.

**Comment by qqshnep** [comment]
@zarik5 here is the error, compiled by llvm 16.0.3

E:\dev\ALVR\ALVR-19.1.1\ALVR-19.1.1>cargo xtask build-server --release
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target\debug\alvr_xtask.exe build-server --release`
$ cargo build --release
   Compiling alvr_server v19.1.1 (E:\dev\ALVR\ALVR-19.1.1\ALVR-19.1.1\alvr\server)
error: failed to run custom build command for `alvr_server v19.1.1 (E:\dev\ALVR\ALVR-19.1.1\ALVR-19.1.1\alvr\server)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `E:\dev\ALVR\ALVR-19.1.1\ALVR-19.1.1\target\release\build\alvr_server-300d3bc8961fd906\build-script-build` (exit code: 101)
  --- stderr
  clang diag: cpp/alvr_server/bindings.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
  thread 'main' panicked at '"AlvrButtonValue_(anonymous_union_at_cpp/alvr_server/bindings_h_88_5)" is not a valid Ident', C:\Users\xxx\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-1.0.51\src\fallback.rs:752:9
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
     1: core::panicking::panic_fmt
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
     2: proc_macro2::fallback::is_ident_continue
     3: <proc_macro2::fallback::Group as core::fmt::Debug>::fmt
     4: proc_macro2::fallback::Ident::new
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
     8: bindgen::ir::context::BindgenContext::rust_ident
     9: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    13: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    17: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    18: bindgen::codegen::codegen::{{closure}}
    19: bindgen::ir::context::BindgenContext::gen
    20: bindgen::codegen::codegen
    21: <bindgen::BindgenOptions as core::default::Default>::default
    22: bindgen::Builder::generate
    23: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
    24: core::ops::function::FnOnce::call_once
    25: <core::ops::control_flow::ControlFlow<B,C> as core::ops::try_trait::FromResidual>::from_residual
    26: std::rt::lang_start::{{closure}}
    27: core::ops::function::impls::impl$2::call_once
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\ops\function.rs:287
    28: std::panicking::try::do_call
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:487
    29: std::panicking::try
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:451
    30: std::panic::catch_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panic.rs:140
    31: std::rt::lang_start_internal::closure$2
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\rt.rs:148
    32: std::panicking::try::do_call
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:487
    33: std::panicking::try
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:451
    34: std::panic::catch_unwind
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panic.rs:140
    35: std::rt::lang_start_internal
               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\rt.rs:148
    36: std::rt::lang_start
    37: main
    38: invoke_main
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    39: __scrt_common_main_seh
               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    40: BaseThreadInitThunk
    41: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: command exited with non-zero code `cargo build --release`: 101', alvr\xtask\src\build.rs:82:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\std\src\panicking.rs:579
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\panicking.rs:64
   2: core::result::unwrap_failed
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library\core\src\result.rs:1750
   3: enum2$<core::result::Result<tuple$<>,xshell::error::Error> >::unwrap<tuple$<>,xshell::error::Error>
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\result.rs:1090
   4: alvr_xtask::build::build_server
             at .\alvr\xtask\src\build.rs:80
   5: alvr_xtask::main
             at .\alvr\xtask\src\main.rs:182
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc\library\core\src\ops\function.rs:250
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-server --release` (exit code: 101)

E:\dev\ALVR\ALVR-19.1.1\ALVR-19.1.1>

**Comment by zarik5** [comment]
Ok. It seems there is nothing we can do for now. This is a bug with bindgen. You should stay on LLVM 15.

**Comment by Vixea** [comment]
bindgen has been bumped can you please retest
