### ISSUE TITLE
Ubuntu 22.04 Server not starting && Vulkan-Headers package as well as gcc8 and g++8 not availible

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [alvr-org/ALVR#1652]
## Description
As the title says, the ALVR Server will never start in ubutnu 22.04
and the addon doesn't appear in STEAMVR.
~~As well as, building from source being impossible, as the dependency packages g++ and gcc are not availible anymore for Ubuntu 22.04 as it seems.~~ 
The Packages are not Availible by Default, but they can be installed.
Appimage is still broken

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=d98102f69a
**CPU**: AMD Ryzen 7 5800X

**GPU**: ASUS NVIDIA RTX3060TI 

**Audio**: Onboard Audio (Gigabyte b450 Aorous Elite)

### Installation
**ALVR Version**: 19.1.1

**SteamVR Version**: 1.25.8

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): 
Ubuntu 22.04.2 LTS

**Comment by micsthepick** [comment]
@DisruptionSystemsINC how did you manage to compile from source?

**Comment by DisruptionSystemsINC** [comment]
> @DisruptionSystemsINC how did you manage to compile from source?

I am not using Ubuntu anymore, but if I recall correctly I downloaded the missing packages from the Ubuntu side from the 20.04 repos
