### ISSUE TITLE
Almost instant SteamVR crash in v20 only

### ISSUE THREAD

**Issue by korbykob** [alvr-org/ALVR#1663]
## Description
Connecting a client to ALVR will make SteamVR crash within seconds with even default settings, using it wired makes it crash even faster, same goes for nightly.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: AMD Ryzen 9 3900X

**GPU**: ZOTAC GAMING GeForce RTX 3060 Ti 6GB

**Audio**: VB Cable

### Installation
**ALVR Version**: v20.0.0

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 11 21H2

**Comment by zarik5** [comment]
Can you please identify the first nightly that causes the crash?

**Comment by 0x108** [comment]
Experiencing SteamVR crashes on V20 as well. E.g. starting vrchat while connected -> crash

**Comment by korbykob** [comment]
> Can you please identify the first nightly that causes the crash? A crash when the client connects may be caused by the encoder. Try to lower the resolution and try again.

v21.0.0-dev00+nightly.2023.06.02

**Comment by zarik5** [comment]
@korbykob are you sure this is the first nightly that causes the crash? Have you tried any v20 nightly?

**Comment by korbykob** [comment]
> @korbykob are you sure this is the first nightly that causes the crash? Have you tried any v20 nightly?

Not yet, I'll give it a try but judging v20 and v21 nightly are having the same issues, I'm not expecting any positive results, I'll let you know if it works when I can.

**Comment by SqueakingTrashPanda** [comment]
I'm having the same issue.

I'm usually able to play **VRChat** for maybe about **10 minutes to an hour before my SteamVR crashes and makes me reload everything**. When it does crash, it either sends me into the main menu where it shows the IP and host address or it freezes my screen and I would have to manually close SteamVR and ALVR.

SteamVR sees it as a **critical error** and shows that it has to restart SteamVR and unblock all my addons 
_(ALVR, OVR Toolkit, OVR Advanced Settings, OpenVR-SpaceCalibrator)._

If anyone has any idea if there is a fix I can do for myself, by all means, reply and I'll give it a go!

**Comment by 0x108** [comment]
Using the latest ALVR stable V20.1.0 I did no longer experience these crashes I had before.

**Comment by AGalan14** [comment]
I also used 20.1.0 and still have the same issue, I don't know what else to try

**Comment by CD912** [comment]
Im having this issue with wired only. Setting up wireless on my laptop is a pain, and wired crashes both alvr and steamvr a few seconds after connecting. I'm using 20.1.0 stable. Default settings, except my controller emulation and audio/microphone settings.

**Comment by Vixea** [comment]
You need to switch the network to be TCP

**Comment by CD912** [comment]
Oh yeah, forgot to mention, i did do that. It shows me nothing if i use udp

**Comment by Vixea** [comment]
Can you send me a video of the crash and your PCs specs?

**Comment by CD912** [comment]
Ryzen 9 6900x, RTX 3080 TI, inside a Razer Blade 14 with Windows 11 home. 16gb of ram. Here's the video.
https://drive.google.com/file/d/1Y9dceT_XPXv0aZQ8TbQW3CWQfXcVpKgu/view?usp=sharing
As soon as the stream crashes, steamvr says it has encountered a critical error. It does this every time, seemingly regardless of my settings.

**Comment by Vixea** [comment]
I meant your PC's side, and do you ryzen 9 6900hx? it might be trying to use your integrated GPU?

**Comment by CD912** [comment]
No, i set my pc to only use my dedicated GPU. Here, i'll get a video of the pc side.
https://drive.google.com/file/d/1rEkeivjggXk2qAQPS8dQ46q3YMUL8j4M/view?usp=sharing

**Comment by korbykob** [comment]
So many people are having this same issue, just crashes within seconds just like shown in the video for me too, on v20.1 wired and wireless, wireless only crashes after launching into vrchat for me.

**Comment by CD912** [comment]
Yeah, i don't know what is going on. Hopefully we can get to the bottom of it, though.

**Comment by korbykob** [comment]
One thing to note is that it spams timed out when waiting for frame.

**Comment by CD912** [comment]
Interesting. Maybe the USB connection is the issue? If it's timing out, that could definitely be the culprit

**Comment by CD912** [comment]
Any updates on this for anyone? I'm still struggling.

**Comment by CD912** [comment]
I figured it out! For me, the fix was as simple as setting the bitrate mode to Constant. I finally got VRChat up and running, along with all my steamvr addons!! Hope this fixes it for you guys too!

**Comment by cwrau** [comment]
> I figured it out! For me, the fix was as simple as setting the bitrate mode to Constant. I finally got VRChat up and running, along with all my steamvr addons!! Hope this fixes it for you guys too!

I have the same problem, but this did not fix it on my end 😕

**Comment by A-Mrpussycat43-cute** [comment]
I found it, you actually need to go to the version 19.1.1 on both devices

**Comment by korbykob** [comment]
As said in the title.
