### ISSUE TITLE
ALVR over USB broken on Quest v54 [Linux]

### ISSUE THREAD

**Issue by KunstDerFuge** [alvr-org/ALVR#1670]
## Description

On latest nightly build, ALVR cannot connect to headset via USB, following all instructions from [here](https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB)). I have tested the latest build as well as the ones from 6/1 and 5/30 which were working for me before the v54 update. I have tried changing the streaming port from 9944 to all ports thru 9949 with no success, but ADB commands work as usual.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
hw-probe info (note: reports Quest 2, I am using Quest Pro): 
https://linux-hardware.org/?probe=f4f543eaa6

**CPU**:
i7-13700KF

**GPU**:
4080 FE

**Audio**:
hda_intel?

### Installation
**ALVR Version**:
2023.06.07 nightly, 6/1 and 5/30

**SteamVR Version**:
1.25.8  and I believe also the beta

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

(AppImage version)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Manjaro Linux on kernel 6.1.31-2-MANJARO

**Comment by KunstDerFuge** [comment]
I just installed v55 on the PTC, and this issue remains the same. Per discussion on the discord, ALVR over USB is working on Quest 2 on v54, so this may be specifically a Quest Pro issue. Lots of complaints of network issues on v54 at r/QuestPro

**Comment by bakicelebi** [comment]
I have the same issue its just black screen.

**Comment by unknown321** [comment]
Same issue here, debian 12, 6.1.0-13-amd64, Quest 2 v59.

ALVR v21.0.0-dev00+nightly.2023.11.13

Stream protocol is TCP, discovery is off.

Client is stuck on "The stream will begin soon". 
Streamer log: [alvr.log](https://github.com/alvr-org/ALVR/files/13351354/alvr.log)

![2023-11-14-175107_607x296_scrot](https://github.com/alvr-org/ALVR/assets/1469658/59a0710e-da2b-4ef6-b5e3-bcc2e0c966b4)

```
$ ss -ltp '( sport = :9944  or sport = :9943 )'
State     Recv-Q    Send-Q       Local Address:Port        Peer Address:Port    Process                                                                         
LISTEN    0         4096             127.0.0.1:9943             0.0.0.0:*        users:(("adb",pid=59569,fd=12))                                                
LISTEN    0         4096             127.0.0.1:9944             0.0.0.0:*        users:(("adb",pid=59569,fd=9))   

$ adb version
Android Debug Bridge version 1.0.41
Version 29.0.6-debian
Installed as /usr/lib/android-sdk/platform-tools/adb
```

**Comment by Meister1593** [comment]
Known issue, latest nightly doesn't work on linux with cabled mode because of some refactors on connection side.
