### ISSUE TITLE
ALVR will Spawn infinite instances when built from source upon trying to close it on ubuntu 22.04

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [alvr-org/ALVR#1672]
## Description
I am unable to stop the ALVR launcher on ubuntu 22.04
It keeps reopening after closing it's SteamVR instance, trying to indefinitely reopen SteamVR upon "Ignoring" it
This does not seem like intended behaviour, as i would expect it to close when closing ALVR itself.

## General Troubleshooting
- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=baf1f44dc8

### Installation
**ALVR Version**:
ALVR 20.0.0
**SteamVR Version**:
1.25.8
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ubuntu 22.04.2 LTS

**Comment by Vixea** [comment]
I'm unsure what you are doing could you please send a video or detailed steps to reproduce this issue?

**Comment by DisruptionSystemsINC** [comment]
Here's what happens.
I don't know the exact reason why it happens. 
But it seems as if ALVR's sutomatic crash recovery is also setting in when ALVR/SteamVR is being closed via the close button
https://drive.google.com/file/d/1c2ohCazhafTCQauFAfiG_yYF5vWps0u4/view?usp=sharing

**Comment by Vixea** [comment]
could you try the latest commit?

**Comment by DisruptionSystemsINC** [comment]
After cloning the repo again, the installer WILL NOT launch ALVR when it's done downloading the AppImage for some reason.
No error, no nothing, just won't launch it
