### ISSUE TITLE
Why won't alvr(latest version 20.0.0) start for me? Bug or error drivers?

### ISSUE THREAD

**Issue by SashkaSashka23** [alvr-org/ALVR#1676]
## Description

Why won't alvr start for me? On the previous version, everything was fine and started, and now I delete the alvr folder in the "program files" folder and install installer alvr and run alvr, after a second it closes there just was just a white screen in the program. Windows 11 maybe not latest version windows. Driver nvidia on a latest version.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
i5-8400 2.10ghz

**GPU**:
RTX 2060 (6 GB)

**Audio**:
CABLE Input
Default headpones

### Installation
**ALVR Version**:
20.0.0 Latest

**SteamVR Version**:
Latest

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11

![image](https://github.com/alvr-org/ALVR/assets/136334161/6381c85c-449d-4727-92f5-5c9afc08c4b9)

**Comment by Emoflia** [comment]
what helped you?

**Comment by SashkaSashka23** [comment]
> what helped you?


Open the program many times until it opens normally
