### ISSUE TITLE
Black screen, direct display

### ISSUE THREAD

**Issue by NintyS** [alvr-org/ALVR#1677]
## Description

When I open steam and connect VR to to ALVR i have this:
![image](https://github.com/alvr-org/ALVR/assets/31569763/7e51e807-4b8e-461e-b0b6-cd7d9c7f7dfe)

And I thing this is the problem with then fire wall:"
![image](https://github.com/alvr-org/ALVR/assets/31569763/ef2a654d-7f05-460d-b578-158e917ccb6e)

But When I found a UDP port and unlock it, this didn't help.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
i9-9900K

**GPU**:
GTX1070

**Audio**:

### Installation
**ALVR Version**:
20.0.0
**SteamVR Version**:
1.25.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ubuntu 22.04

**Comment by Vixea** [comment]
This should be fixed soon assuming that you do have a firewall enabled which it looks like you do the temporary solution would be to pull ALVR yourself and run the script in packaging/firewall manually

**Comment by Vixea** [comment]
You also need to enable direct display mode
