### ISSUE TITLE
Does it support wired streaming? I don't use WIFI

### ISSUE THREAD

**Issue by TG-GOD** [alvr-org/ALVR#1680]
## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:R5 3600

**GPU**:1660s

**Audio**:

### Installation
**ALVR Version**:

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by TG-GOD** [comment]
I use win10

**Comment by yingtian991221** [comment]
You may follow this one:
https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB)
