### ISSUE TITLE
ALVR Handshake error for 0069.client.alvr: At alvr\\server\\src\\connection.rs:298: Control socket failed to connect

### ISSUE THREAD

**Issue by manolis07** [alvr-org/ALVR#1691]
## Description
alvr doesn't want to connect with usb or wireless and just throws an error code despite the correct ports being open

## General Troubleshooting
- [1] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [1] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz   3.60 GHz

**GPU**:Rog Strix Nvidia RTX 3060

**GPU Driver Version**:536.23

**Audio**:Realtek

### Installation
**ALVR Version**:V20

**SteamVR Version**:1.26.3 (beta)

**Install Type**:
- [1] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source
![Screenshot 2023-06-19 004035](https://github.com/alvr-org/ALVR/assets/73193074/570a5c9f-1eb9-4dd0-a4d9-bb050b953624)

**Comment by Vixea** [comment]
Your OS?

**Comment by Aclaez** [comment]
same problem
![Screenshot 2023-11-15 103637](https://github.com/alvr-org/ALVR/assets/55399348/ba0da634-598a-4073-8732-0fd803d8f6c8)

**Comment by manolis07** [comment]
> same problem ![Screenshot 2023-11-15 103637](https://user-images.githubusercontent.com/55399348/283038913-ba0da634-598a-4073-8732-0fd803d8f6c8.png)

I found the issue, apparently i renamed the mic from the vb audio driver to something of my own and it broke alvr, when I disabled the mic it worked and i just reinstalled the drivers
