### ISSUE TITLE
Instant white window with no crash log

### ISSUE THREAD

**Issue by Whale-Splas** [alvr-org/ALVR#1692]
### Description

When I start ALVR it gives me a unresponsive white window,then auto closed in two seconds,generate a empty crash_log.
The old version（v18）works fine

crash log is completely blank
I tried to uninstall the v18 first,no use

I cant remeber whats the last working nightly for me
but its not the new dash board version
I have a latest chrome installed

### General Troubleshooting

- [x]  I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard

- [x]  I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Environment

**Installation**

ALVR Version:v20.0.0.0(troubled);v21.0.0-dev00+nightly(troubled);v18.2.3.0(no problem)

Install Type:
- [x] Packaged (with v20)

   

- [x] Portable (with v21)

    

- [ ] Source

**OS Name and Version**
Windows10 22H2

**Comment by Vixea** [comment]
Could you please bisect to a merge request level of detail?

**Comment by Whale-Splas** [comment]
> Could you please bisect to a merge request level of detail?

After test,the last nightly i can boot (gives me setup) is v20.0.0-dev12+nightly5.9
but if i close it,it wont restart unless i delete the session.json

the last fully functional nightly for me is v20.0.0-dev12+nightly5.1

higher version simply wont boot

**Comment by Whale-Splas** [comment]
> Do you mean when you open the dashboard or start SteamVR after opening the dashboard?

open the dashboard

**Comment by zarik5** [comment]
@Whale-Splas The latest nightlies have also debug builds, please try that. Launch the dashboard from the command line and you should be able to read a more descriptive error.

**Comment by Whale-Splas** [comment]
> @Whale-Splas The latest nightlies have also debug builds, please try that. Launch the dashboard from the command line and you should be able to read a more descriptive error.

still no error code,but it exit at "Dashboard request: GetAudioDevices"

**Comment by zarik5** [comment]
can you try to debug with msvc?

**Comment by Whale-Splas** [comment]
> can you try to debug with msvc/Visual Studio?

vulkan-1.dll trying to read 0x0,and the alvr dashboard does showed up,but at the same time it throws thiis exception,so every thing just shut down,

**Comment by Whale-Splas** [comment]
dump file are too big to upload here

**Comment by zarik5** [comment]
I pushed a potential fix, you can try it when the new nightly builds, in 9 hours.

**Comment by Vixea** [comment]
https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.06.23
New release.

**Comment by Whale-Splas** [comment]
Yes it worked,Thanks for the help

**Comment by zarik5** [comment]
Interesting, another user on Discord had the same issue and this fix didn't help.
