### ISSUE TITLE
Is this the best projcet to stream desktop to VR

### ISSUE THREAD

**Issue by MarcWeber** [alvr-org/ALVR#1693]
I imagine a VR desktop to be bigger than a screen.
So is ALVR one way to get there ?

**Comment by Vixea** [comment]
Wdym?

**Comment by zarik5** [comment]
This is not the primary use-case for ALVR. You can use Virtual Desktop (Quest version) or Big Screen (pc version) + ALVR.

**Comment by zk-wz** [comment]
if you only want to stream desktop, moonlight will be a better choice (only among opensource projects and moonlight can't stream vr apps)
