### ISSUE TITLE
steam games are not detected when launching steamvr through ALVR [Arch linux] [steam VR]

### ISSUE THREAD

**Issue by KiwiHuman** [alvr-org/ALVR#1695]
## Description
when I connect my headset (quest 2) to my computer through ALVR with a usb cable or wireless steam vr loads however the steam app says Steam VR error SteamVR failed to initialize for unknown reasons. (Error:. Not initialized (109)(109)) whilst steam VR loads in the headset and shows the following  

![image](https://github.com/alvr-org/ALVR/assets/98422297/be85000d-9fa9-44dc-9e8e-2a5abf6d177f)

There seems to be an issue with the connection between steamVR and the Steam client when launching through ALVR 

### Hardware
https://linux-hardware.org/?probe=092370b958
### Installation
**ALVR Version**: V20.0.0

**ALVR Settings File**:

**SteamVR Version**: latest as of 20th June 2023

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source
ALVR is the appimage and steam is installed through pacman
**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux x86_64 

since there is a spot for a feature request it would be nice if there was a button or setting to run the adb commands to port forward when using ALVR in wired mode rather than having to do this manualy every time the headset re-connects.

**Comment by Vixea** [comment]
SteamVR bug, please leave comment a comment on Valve's issue tracker
