### ISSUE TITLE
ALVR fails to start with `thread 'main' panicked at 'Error in Surface::configure: Validation Error` with RX 6700 XT using amdgpu driver on Linux

### ISSUE THREAD

**Issue by Nebulon-BFrigateFTW** [alvr-org/ALVR#1698]
## Description
Starting from either the AppImage or bin/alvr_dashboard results in the following:
```
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Requested usage is not supported
', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:734:18
```
**The AppImage previously worked using a different GPU (an RTX 1060), so I suspect this to be a compatibility issue with certain AMD cards using the amdgpu driver.**

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Linux (OpenSUSE Tumbleweed 20230622)

### Hardware
https://linux-hardware.org/?probe=31d19c3462

**CPU**: Ryzen 5 5500

**GPU**: Radeon RX 6700 XT

**GPU Driver Version**: 

**Audio**:

### Installation
**ALVR Version**: 20.1.0

**ALVR Settings File**:

**SteamVR Version**: 

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [-] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): openSUSE Tumbleweed

**Comment by Vixea** [comment]
What driver are you using, mesa, amdvlk?

**Comment by Nebulon-BFrigateFTW** [comment]
> What driver are you using, mesa, amdvlk?

Mesa (radeonsi).

**Comment by Nebulon-BFrigateFTW** [comment]
Closing as it was clearly just an issue with OpenSUSE's setup. There should probably be mention to check Vulkan drivers in the installation information (only mention currently is about ffmpeg).
