### ISSUE TITLE
VB cable is never detected for mic use

### ISSUE THREAD

**Issue by Josh65-2201** [alvr-org/ALVR#1699]
## Description

When using v20 and selecting microphone to automatic it will never connect as it says it can't find VB cable. It is installed and worked on v19

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: AMD Ryzen 5 2600

**GPU**: EVGA RTX 3060 12GB

**GPU Driver Version**: 531.68

**Audio**: 

### Installation
**ALVR Version**: 20.1.0

**ALVR Settings File**: [session.txt](https://github.com/alvr-org/ALVR/files/11858108/session.txt)

**SteamVR Version**: 1.26.3

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 build 22621.1848

**Comment by Vixea** [comment]
Try manually selecting what virtual driver you use

**Comment by Josh65-2201** [comment]
It says it cant find the device
![image](https://github.com/alvr-org/ALVR/assets/26977075/7292c559-91ac-42fd-aa67-711bdc7cf550)

This is what I have it set to find
![image](https://github.com/alvr-org/ALVR/assets/26977075/be59dcee-a7d5-4867-8288-8b6424f27d23)

This is what it's named as in Windows
![image](https://github.com/alvr-org/ALVR/assets/26977075/835ded64-e0b6-481a-85d1-77654ca4fec1)

**Comment by Vixea** [comment]
Reset back to default and try all the drop downs in devices

**Comment by Vixea** [comment]
(the name field)

**Comment by Vixea** [comment]
Oh you're not even looking at the right setting

**Comment by Vixea** [comment]
That's for Linux my guy

**Comment by Vixea** [comment]
So disable it and scroll all the way to the top and look carefully for the first microphone also issue reports aren't for support they are for issues always ask in the discord or matrix to make sure it's actually an issue before making an issue this would've been solved quicker if you did

**Comment by Josh65-2201** [comment]
Alright, the top mic option doesn't change anything, Setting it to VB cable or automatic still has the cant find VB cable issue.

**Comment by Vixea** [comment]
Did you make sure the driver installed correctly and is currently running

**Comment by Josh65-2201** [comment]
Yes and I have tried reinstalling VB cable. Other programs can use the device it makes.

**Comment by Vixea** [comment]
Yes let's do that

**Comment by Vixea** [comment]
For anyone in the future who happens to run into this it was because the user was likely following Linux instructions DO NOT FOLLOW THEM if you're on windows, do NOT rename the driver's name it uses
