### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by MonkeyMayham** [alvr-org/ALVR#1700]
<Crashing when playing steamvr games>

## Description
<Crashing on unity games and UE5 games and some source games>

## General Troubleshooting
- [yes] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**:Intel(R) Core i5-4460 3.20GHz

**GPU**:NVIDIA Geforce RTX 3050

**GPU Driver Version**:31.0.15.3161

**Audio**:ASUS MX239

### Installation
**ALVR Version**:20.1.0

**ALVR Settings File**:don't know

**SteamVR Version**:1.25.8

**Install Type**:
- [yes} Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**:Windows 10 22H2

**Comment by Vixea** [comment]
Try disabling your IGPU in bios

**Comment by MonkeyMayham** [comment]
no
