### ISSUE TITLE
 After launching an APK in a headset, the application crashes instantly

### ISSUE THREAD

**Issue by Ruzevi** [alvr-org/ALVR#1705]
After installing a new version of the APK on the Pico Neo 3 headset, when you try to run it, an instant crash occurs. App won't launch at all
Hardware
Headseat: Pico Neo 3 

CPU: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz

GPU: NVIDIA TITAN X (Pascal) 12gb Driver Version 531.29

Audio: PHL 243V7 (2- NVIDIA High Definition Audio)

Installation
ALVR Version: ver. 21.0.0-dev12+ nightly.2023.06.26

SteamVR Version: 1.25.8

OS Name and Version (winver on Windows or grep PRETTY_NAME /etc/os-release on most Linux distributions):
Edition: Windows 10 Enterprise LTSC
Version 21H2
OS build 19044.2846

**Comment by Ruzevi** [comment]
https://github.com/alvr-org/ALVR/assets/134388483/ba7459bd-d953-4cad-948a-a0af385833d4

**Comment by zarik5** [comment]
@galister Can you reproduce this issue?

**Comment by Vixea** [comment]
Can the author of the issue confirm, the issue still happens

**Comment by Ruzevi** [comment]
Hi! Just checked version 21.0.0-dev00+nightly.2023.07.13 APK on Pico Neo 3 . It still close when i try to start app

**Comment by Vixea** [comment]
Could you try running adb logcat then open ALVR and see what it outputs you may need to disconnect the USB right after opening alvr or the log may get lost

**Comment by galister** [comment]
2023.07.13 nightly works fine for me on Pico 4, system version 5.6.0

**Comment by galister** [comment]
Actually scratch that, I was running the wrong version.
I checked again with local builds.
5ae730c9b1cb9e6efa47ba4dd23133665668b496 won't connect on TCP or UDP due to handshake error (11)
59b981a5df8eb1975d275a663e0a5ac56c634449 (should be Jul 04 nigtly) works fine

**Comment by Ruzevi** [comment]
HI! Checked on the same version. On Pico Neo 3 it still crashes. I check this version alvr  on Pico 4 does not have this problem.
Logcat form Pico Neo 3 attached below
[logcat.txt](https://github.com/alvr-org/ALVR/files/12093867/logcat.txt)

**Comment by galister** [comment]
@Ruzevi what are your system versions on the Pico 4 and Neo 3?

**Comment by Ruzevi** [comment]
@galister  pico 4 - 5.6.0  and Pico Neo 3 Pro - PUI 4.8.19

**Comment by galister** [comment]
PUI conforms to OpenXR 1.0 starting system version 5.2.0. ALVR won't work with versions below that.

**Comment by Ruzevi** [comment]
@galister The PUI 4.8.19 version on the Pico Neo 3 Pro is the latest, as stated on their official website. I understand correctly that support for Pico Neo 3 will be discontinued in the next version of Alvr?

**Comment by galister** [comment]
No, in fact the regular Pico Neo 3 is at 5.6.3 stable, 5.7.2 beta right now, and works very happily with ALVR. I'm not sure why Pico would discontinue the system updates for the Neo 3 Pro but not the regular Neo 3.

Maybe join [here](https://discord.gg/BSWfvH4cm8) and ask around about the firmware situation.

If you're locked to PUI 4.x then your only choice is ALXR, as it makes use of the older, Pico-specific XR headers.

ALVR only supports standard OpenXR, but headsets that support standard OpenXR will work with minimal maintenance effort, so I don't see the PN3 losing ALVR support.

**Comment by zarik5** [comment]
The Pico Neo 3 can be updated to 5.X, but the Pro version is locked to 4.X. I have the Pro and I can confirm this.

**Comment by galister** [comment]
I think you can upgrade the pro to 5.x if you disable the enterprise mode, but don't quote me on that.

**Comment by tcrass** [comment]
Hi,

as described in #1756, I also found the client to immediately crash after installing v20.1.0 on my Quest 2, but I suspect the reason was some kind of conflict with some leftovers from a previously installed ALVR client version since the apk package name had changed. Perhaps you also want to try to explicitly uninstall the old version before (re-)installing v20.1.0?

Cheers!

**Comment by StormyNotFound** [comment]
For anyone who finds this issue. Pico has updated the software of their pico neo 3 pro headsets to a comparable version.

**Comment by StupidRepo** [comment]
@StormyNotFound what version is it on now? literally bought a pico neo 3 pro like 2 days ago and hoping it works with alvr client 😅
