### ISSUE TITLE
(PR) Update Dashboard Tips For v21.0.0+

### ISSUE THREAD

**Issue by Kasuxae-Xaesys** [alvr-org/ALVR#1708]
I noticed a massive lack of information on what some of the ALVR settings do and their effects in addition to a lack of ALVR Relevant information on NVENC And AMF related settings when searching the web.
I understand and know what most settings do in ALVR. but some of these settings are newcomers since v16.0.0 or have had their names changed, Making new tips and information available may make the program more user friendly.

Related: #1703 

###### _I am unsure how to do pull requests._

**Comment by zarik5** [comment]
You can open a Pull Request as the one you linked. Look up online how to open a PR. But we should also consider removing that page as it's quite redundant. Instead we have the page "Settings tutorial" which describes more how to tune settings together to achieve certain goals. What do you think?

**Comment by Kasuxae-Xaesys** [comment]
I do agree that the "[Settings Tutorial](https://github.com/alvr-org/ALVR/wiki/Settings-tutorial)" page is decent for a pick up and go experience, But for people like me who like to squeeze every last drop of performance for any given hardware and software, it lacks any information, essentially, all I am advising is to make the "[Settings Guide](https://github.com/alvr-org/ALVR/wiki/Settings-guide)" more of a "Settings Dictionary".

**Comment by zarik5** [comment]
I'd also argue that maintaining the "Settings Guide" is hard because it often goes out of sync with the actual settings. So instead we should improve the tooltips on the dashboard itself. I can accept a PR moving the missing information from "Settings Guide" to the dashboard itself.

**Comment by Kasuxae-Xaesys** [comment]
Yeah, That seems agreeable! the only real question now is when? it would be more viable to add this in 21.0.0 rather than in the next patch because lots of things can change between now and then.

**Comment by Kasuxae-Xaesys** [comment]
Oh and i might be putting in an issue thread for a minor annoyance since 19.0.0.
Anyways have a great day! thanks for bearing with me

**Comment by zarik5** [comment]
Sorry for the late reply.

> Yeah, That seems agreeable! the only real question now is when? it would be more viable to add this in 21.0.0 rather than in the next patch because lots of things can change between now and then.

I think we should update the docs always as soon as possible, since the program changes constantly anyway.
