### ISSUE TITLE
Why don't you guys add it as a Linux package because I can't set it up correctly

### ISSUE THREAD

**Issue by Crodadjim** [alvr-org/ALVR#1709]

**Comment by Vixea** [comment]
we do have linux packages :|

**Comment by Crodadjim** [comment]
Well sorry I can't find them plus I technically can't use alvr it since it says I need a driver and I don't think I have one I tried everything to fix it but didn't work

**Comment by Vixea** [comment]
download the appimage or try the distrobox setup

**Comment by Vixea** [comment]
also what are you talking about ALVR is THE DRIVER

**Comment by Crodadjim** [comment]
Crap sorry typo

**Comment by Crodadjim** [comment]
It also might be because I'm used bottles to open alvr

**Comment by Vixea** [comment]
wait your using the windows version of alvr yea thats not going to work

**Comment by Crodadjim** [comment]
I couldn't figure out how to open the alvr dashboard plus I use Ubuntu 20.04

**Comment by Crodadjim** [comment]
I know I need the tar.gz file and know to extract it but don't know what to do next the guide wasn't helping me

**Comment by Vixea** [comment]
It's the one thing that is in the bin folder also this is a support question not an issue therefore I'm closing it(not that this last comment shouldn't completely resolve the support question)
