### ISSUE TITLE
20.1.0 very high gpu

### ISSUE THREAD

**Issue by C0ZM0comedy** [alvr-org/ALVR#1713]
20.1.0 causes very high gpu usage on my RX7900XTX with the program known as vr compositor being the app that uses 80-96% of my gpu this wasn't a problem till 20.1.0. this was also a problem on my 3060 and 1660 super.

**Comment by Vixea** [comment]
https://github.com/alvr-org/ALVR/pull/1685
could you try reverting this and retesting(anyway this is most likely an 7X00 series driver issue

**Comment by Vixea** [comment]
Ping @C0ZM0comedy
