### ISSUE TITLE
Glitchy green image on headset

### ISSUE THREAD

**Issue by EibrielInv** [alvr-org/ALVR#1717]
## Description

The image on the headset looks broken, with green stripes. Like a decoding or encoding error.

Everything works perfectly fine, except that the video on the Quest is glitched, with green horizontal stripes, like a decoding glitch.

I've changed lots of parameter on ALVR, including disabling phobeated rendering (all of them), and color correction.

Any combination of parameters result en exactly the same glitchy green image.

![image](https://github.com/alvr-org/ALVR/assets/172656/974d4d41-00d9-402a-a1b3-317fb429cedb)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=196daaa768

### Installation
**ALVR Version**: ALVR v20.1.0 (tested ALVR v20.0.0 also)

**ALVR Settings File**: 
[session.json.txt](https://github.com/alvr-org/ALVR/files/11919628/session.json.txt)

**SteamVR Version**: 1.25.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ubuntu 22.04.2 LTS

**Comment by auwsom** [comment]
I have the same problem on Ubuntu with both Quest 2 and Pico 4. Positive controls like VDesktop in Windows are working.

**Comment by Vixea** [comment]
The newest Ubuntu is required due to old Ubuntu not included the required packages for ALVR to work your best experience will be found on arch

**Comment by auwsom** [comment]
> The newest Ubuntu is required due to old Ubuntu not included the required packages for ALVR to work your best experience will be found on arch 

Yes, Arch did get past the green lines, but was more laggy than VD on my system. 

Which version of Ubuntu has the packages? I tried 22.04 LTS. Also, any idea which packages?.. because maybe I can upgrade just those and their dependencies. Thanks

**Comment by Vixea** [comment]
Look at the wiki, also do you mind sending me the logs from ALVR?

**Comment by EibrielInv** [comment]
Can't find a way to save the logs as text (can't find the "DebugLog" button referred on the wiki).
But here are the logs on image format.

![Selección_1340](https://github.com/alvr-org/ALVR/assets/172656/468c3384-1358-4836-b74b-520ec85c39c7)

![Selección_1341](https://github.com/alvr-org/ALVR/assets/172656/b43fc73c-172d-45ad-9bc0-f4c8b636d59a)

**Comment by Vixea** [comment]
You need to enable logging to file in settings and it should be in your home file

**Comment by Vixea** [comment]
Also do you have cuda installed?

**Comment by EibrielInv** [comment]
Yes, I do have cuda installed. This is the output from `nvidia-smi` . Hardware encoding should be working in my machine, I use it regularly on OBS.

![image](https://github.com/alvr-org/ALVR/assets/172656/85816b24-a443-455c-be73-e1e3a0b0405c)

Here are the logs: 
[alvr_session_log.txt](https://github.com/alvr-org/ALVR/files/11923485/alvr_session_log.txt)

**Comment by Vixea** [comment]
Do you not have modesetting enabled?

**Comment by EibrielInv** [comment]
Is working now! Thanks

Tried adding `nouveau.modeset=0` (didn't work), then `nvidia-drm.modeset=1` (didn't work).

Then I updated the NVidia drivers, and that did the trick!

![imagen](https://github.com/alvr-org/ALVR/assets/172656/9e5b079b-7ec5-4b6c-8636-3ddebd345444)

**Comment by Vixea** [comment]
Awesome

**Comment by Vixea** [comment]
You do need it at least nvidia_... Loaded, but an updated driver may have fixed some things
