### ISSUE TITLE
Getting the Encoded Frame

### ISSUE THREAD

**Issue by ForeverAT** [alvr-org/ALVR#1723]
## Description

I would like to extract an encoded frame/ an encoded video from the ALVR as I would like to present the encoded difference. However, no matter I used the ffmpeg or directly use VLC, it cannot decode the file I get. Here are some methods I have tried:
I have try to direct get it from the outputBitstream and also get the header from GetSequenceParams. I have also tried to save all the vPackets in VideoEncoderNvenc.cpp, but this does not work either. May I ask do you have other solution?

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by zarik5** [comment]
The only thing that worked for me was ffplay.

**Comment by ForeverAT** [comment]
Thank you for the reply. I get the encoded data now and decode it by multiple methods. The mistake I made was in getting the encoded data part, which I got in the wrong place.
