### ISSUE TITLE
my client wont show up

### ISSUE THREAD

**Issue by doge1311** [alvr-org/ALVR#1726]
my fucking client wont show up

**Comment by Vixea** [comment]
I'm going to need more info than that, have you ran the firewall rules setup? What version of ALVR are you using you completely skipped everything that you need to fill out, also that type of attitude isn't going to get you support, please create a new issue the correct way.

**Comment by doge1311** [comment]
exactly 1 year later, also sorry about the attitude i had, my anger issues were a lot worse back then
