### ISSUE TITLE
ALVR Handshake Error

### ISSUE THREAD

**Issue by Hydr4XVR** [alvr-org/ALVR#1727]
Everytime i Open ALVR And then Start it And Do the same Thing On my Oculus it says Handshake Error And then I just can't Play PCVR, thanks if someone Could Help :)

![ALVR bug](https://github.com/alvr-org/ALVR/assets/138728750/b7422cd7-5309-481d-883f-665f35fda245)

**Comment by J2Blade** [comment]
I had the same issue, for me the only thing that worked was switching the connection protocol from udp to tcp. hope this helps!

**Comment by SN626** [comment]
I had the same problem with v20.1, but after reinstalling v20.0, the problem went away! Maybe you could try an older version.

**Comment by 0rang3-31** [comment]
same here

**Comment by StormyNotFound** [comment]
I am having this issue from time to time and the only way to fix it is to restart my computer
