### ISSUE TITLE
No option to change emulated controller's tracking system name.

### ISSUE THREAD

**Issue by cxtch** [alvr-org/ALVR#1729]
There is no option to change the `TrackingSystemName` when using emulated controllers. It was a feature available in v19.
```rs
ControllersEmulationMode::ValveIndex => {
                    set_string(TrackingSystemName, "indexcontroller");
                    set_string(ManufacturerName, "Valve");
```
[source](https://github.com/alvr-org/ALVR/blob/00a19bf54f283fc8aaf816b7cb4b09c3a99369d2/alvr/server/src/openvr_props.rs#L308C9-L308C9)
It made calibration with OpenVRSpaceCalibrator much easier.

**Comment by zarik5** [comment]
I can add back the option. How would you like this option to behave? Should headset and controllers tracking system names always be the same? Does the specific name matters at all as long as it the same between headset and controllers? What is your specific use-case?

**Comment by cxtch** [comment]
Thank you! My specific use case is just to calibrate with OpenVRSpaceCalibrator and vive trackers. I believe having a toggle for the controllers and the headset to always have the same tracking system name would be great.

**Comment by zarik5** [comment]
Ok. I'm going to make an option "Use headset tracking system".

**Comment by Arenovas** [comment]
I will add my support for this since I've been trying to use my old Quest controllers as trackers but I can't calibrate them with OpenVRSpaceCalibrator using v20.
Although for some reason ALVR stops streaming the tracking data after 5 minutes, requiring me to restart the app which isn't great.

**Comment by Arenovas** [comment]
Just gonna give this a poke so it doesn't close.
Really would be a shame for this feature to remain stuck in an older version of ALVR, super handy being able to use old Quest controllers for FBT when using a lighthouse system for the headset.
