### ISSUE TITLE
Question about paralleling the rendering and encoding

### ISSUE THREAD

**Issue by viktor02** [alvr-org/ALVR#1731]
Hi. I have a two gpu in my pc.
Can I use my nvidia card for rendering and intel uhd graphics for encoding video stream? This would reduce the load from the main graphics card, increasing fps. Or, If intel is unsupported, may be I can use another nvidia card?

My specs:
Nvidia GTX 1080
Intel UHD 730

**Comment by zarik5** [comment]
I'd say it will probably not increase performance. Usually encoder cores are separate from graphics cores.
