### ISSUE TITLE
joystick movement problem

### ISSUE THREAD

**Issue by JAPON1029** [alvr-org/ALVR#1732]
## Description
hi I have small problem. Joystick movement isn't smoth like always. It started hapening when I instaled newest version of alvr and idk what to do?

## General Troubleshooting
-  I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
-  I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: intel core i5 10400f 

**GPU**: Geforce rtx 2060

**GPU Driver Version**:  31.0.15.3179

**Audio**: Nvidia high definition audio

### Installation
**ALVR Version**: 20.1.0

**ALVR Settings File**: 

**SteamVR Version**: newest

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Vixea** [comment]
It could be possible you just got unlucky and got stuck drift and it happened when you updated ALVR a quick way to check is to see if it happens in other apps like for example run vrchat's quest version

**Comment by JAPON1029** [comment]
I checked and problem disappears when I play on alvr v19.1.0 or older

**Comment by Vixea** [comment]
could you explain in detail what it feels like

**Comment by Vixea** [comment]
And fo you mean joystick or controller those are two different things

**Comment by JAPON1029** [comment]
moves that i made in game with **joystick** are not smoth. they are stoping every 2 seconds for like half a second. this is most noticeable when moving around in games. and its only hapening in alvr above 19.1.0
