### ISSUE TITLE
Linux - SteamVR enters direct display mode since the latest SteamVR update

### ISSUE THREAD

**Issue by CrazyVito11** [alvr-org/ALVR#1733]
## Description
It seems like the latest SteamVR update broke ALVR for Linux, as it now thinks it needs to go to direct display mode.
In the headset it doesn't show any picture, and the statistics screen is also stuck.

I'm not completely sure if this is a bug on the ALVR side or SteamVR, sadly my technical knowledge about both of them is very limited. If this is suspected to be a SteamVR bug, please let me know and then I'll create an issue for SteamVR.

If I go back to the old SteamVR version _(linux_v1.14)_, it launches properly again. 
But on the latest stable or beta release, it goes to direct display mode.

![image](https://github.com/alvr-org/ALVR/assets/31567466/58edeefa-bb16-41f5-af47-230a4e22fc09)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

ALVR has worked on this system before, last tested around 2 days ago. SteamVR was updated yesterday, so something in that update probably broke something. The older linux_v1.14 release does work properly.

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
AMD Ryzen 7 5700X

**GPU**:
AMD Radeon RX 7900XTX

**GPU Driver Version**:
23.1.3

**Audio**:
Pipewire

### Installation
**ALVR Version**:
20.1.0

**ALVR Settings File**:
[session.json.txt](https://github.com/alvr-org/ALVR/files/11985546/session.json.txt)

**SteamVR Version**:
1.26

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux _(KDE Plasma running on Wayland)_

**Comment by Vixea** [comment]
Do not go back to Linux 1.14

**Comment by Vixea** [comment]
`WAYLAND_DISPLAY='' %command%` is required in commandline options for steamvr to work with Wayland and alvr on most DEs (like gnome, hyprland) and until drm leasing gets added in a nightly kde

**Comment by CrazyVito11** [comment]
Adding `WAYLAND_DISPLAY='' %command%` seems to have fixed the issue for me, thanks!
