### ISSUE TITLE
[Feature Request] ALVR for Unity

### ISSUE THREAD

**Issue by ebellumat** [alvr-org/ALVR#1737]
Hello! The only reason that i still use Windows for my Oculus Quest Device is the Oculus Link through Unity. 

It's very handy to test the games without generate a build for every change. 

It's possible to make ALVR work in Unity on Linux?

Best Regards.

**Comment by parov0z** [comment]
@ebellumat 
you can use [SteamVR plugin for unity ](https://github.com/ValveSoftware/steamvr_unity_plugin)

**Comment by PurpleVoidEpic** [comment]
any updates on this?
