### ISSUE TITLE
packaging is missing

### ISSUE THREAD

**Issue by Krutonium** [alvr-org/ALVR#1738]
## Description
According to [this](https://github.com/alvr-org/ALVR/wiki/Building-From-Source) there should be a packaging/nix/shell.nix file. As far as I can tell, someone has deleted the packaging directory.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

**Comment by Vixea** [comment]
The nix stuff is completely out of date, instead you should use flatpak. No one that actively works with ALVR uses nix and the build was broken so it was removed. The Linux side wiki also doesn't get updated all the time because the main dev doesn't use it.

**Comment by Vixea** [comment]
@Krutonium are you ok with me closing this or do you have any more questions?

**Comment by Krutonium** [comment]
Could you point me at least at an old copy? I could see about fixing it and adding it to the Nix repos proper.

**Comment by Vixea** [comment]
The most recent thing would be the pr that's open
