### ISSUE TITLE
ALVR dashboard doesnt launch

### ISSUE THREAD

**Issue by treatmeniceplz** [alvr-org/ALVR#1747]
## Description

ALVR dashoard doesnt launch

## General Troubleshooting
- [no ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
11th gen intel i5-1135G7 @ 2.40 ghz
**GPU**:
iris xe integrated
**GPU Driver Version**:
latest
**Audio**:
not sure
### Installation
**ALVR Version**:
20.1.0
**ALVR Settings File**:
i just installed alvr to the computer
**SteamVR Version**:
latest
**Install Type**:
- [ yes] Packaged (`exe`, `deb`, `rpm`, etc)
- [ attempted] Portable (`zip`)
- [ github] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
windows 11 22h2

**Comment by treatmeniceplz** [comment]
to clarify the setup wizard doesnt show after install and no my quest is not connected

**Comment by treatmeniceplz** [comment]
I want a response

**Comment by treatmeniceplz** [comment]
Hello

**Comment by zarik5** [comment]
Have you tried the latest ALVR version?

**Comment by treatmeniceplz** [comment]
I’ll have to check since this was a while agoOn Dec 11, 2023, at 10:36 AM, zarik5 ***@***.***> wrote:﻿
Have you tried the latest ALVR version?
