### ISSUE TITLE
No Flatpak Builds for v20.1, no manifest in v20 branch to build flatpak

### ISSUE THREAD

**Issue by jmaris** [alvr-org/ALVR#1752]
## Description
I cannot use ALVR because if I try to build from the master git branch then it is incompatible with the latest client, and if I cannot build from the v20 git branch there is no build manifest. There are also no builds available on the releases page for flatpak.

## General Troubleshooting
- I followed the build instructions for flatpak

**Comment by Vixea** [comment]
I'm working on getting a point release out also you can go to alvr-nightly and get a flatpak bundle and match client apk there.

**Comment by jmaris** [comment]
My bad! I missed that! Thanks for all your hard work!
