### ISSUE TITLE
Controllers are overpredicted after specific commit

### ISSUE THREAD

**Issue by Meister1593** [alvr-org/ALVR#1755]
Environment: Arch Linux distrobox on Fedora Silverblue, Flatpak as well, steamvr 1.26.6
Prediction, velocity cutoffs default

With specific commit (8867dd28c66f1cb9d15c0c61cdbb82f3e75efe33) seems like controllers gets aggressively predicted forward in time, which makes using them very hard/unusable in fast motion. 

If you set both angular and linear velocities cutoff to max, it gets similar to what was before, but in fast motion completely incorrect.

For testing with nightly:
1. https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.07.03 (without overprediction)
2. https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.07.04 (with overprediction)

**Comment by issacdowling** [comment]
I got my dates mixed up with this issue and thought it came before that commit (when trying nightlies), but I was wrong. Just did a `git revert 8867dd28c66f1cb9d15c0c61cdbb82f3e75efe33` and it works perfectly, so not much to add but can confirm this is an issue and is solved by reverting that commit

**Comment by Meister1593** [comment]
Since Monado compatibility rewrite will anyway affect this part of code, and @zarik5 is fine with reverting this back, we can revert to original state for now.
