### ISSUE TITLE
v20.1.0 crashes immediately on Quest 2

### ISSUE THREAD

**Issue by tcrass** [alvr-org/ALVR#1756]
## Description

When launching v20.1.0 on my Meta Quest 2, the client app crashes immediately, and I'm back in my home environment.

## General Troubleshooting
- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
(PC side not relevant here...)

### Hardware
Meta Quest 2

### Installation
**ALVR Version**: v20.1.0

**Comment by tahawael** [comment]
did you fix it?

**Comment by tcrass** [comment]
Nope, unfortunately not... But I don't have any clue how to tackle this problem, anyway...

**Comment by tcrass** [comment]
OK, might have been a problem with an incomplete pre-20.x uninstall. When `adb shell`ing into the Quest, `pm list packages | grep alvr` showed me a remaining `alvr.client.quest` package. After removint this with `adb uninstall alvr.client.quest` and re-installing v20.1.0 (which lead to an `alvr.client` (without trailing `.quest`) package being present on the device), everything works perfectly again! :)
