### ISSUE TITLE
[Enhancement] Add a setting to support working with voicemeeter

### ISSUE THREAD

**Issue by ttofu-projects** [alvr-org/ALVR#1757]
There needs to be a setting which creates a virual audio playback device and a virtual microphone device which can be selected in voicemeeter.

**Comment by Vixea** [comment]
I am confused, what exactly are you asking we have presets for Voicemeeter.

**Comment by ttofu-projects** [comment]
> I am confused, what exactly are you asking we have presets for Voicemeeter.

I want a mode which just creates an audio playback device and a recording device and doesn't copy, overwrite or mirror any existing channels.

**Comment by Nytra** [comment]
This would be nice. Currently you cannot select the ALVR headset device as audio output target in VoiceMeeter.

**Comment by zarik5** [comment]
What the OP asks is creating our own windows audio driver. This has been tried and failed. I think it's safe to say ALVR will never get one, as it's way too complicated, and basically noone has the knowledge to do that.

**Comment by Nytra** [comment]
Virtual Desktop has this as part of its virtual audio driver, could be worth looking into
