### ISSUE TITLE
SteamVR crashes when attempting to connect Quest 2 via USB (Windows 10)

### ISSUE THREAD

**Issue by BlipBlorp** [alvr-org/ALVR#1765]
## Description

I am able to get the Quest 2 to connect to ALVR just fine if it's done wirelessly. Once I follow the instructions for ALVR via USB (set IP to 127.0.0.1, disable client discovery, set stream protocol to TCP) it still connects, enabling me to see about a second of SteamVR's menu before SteamVR reports a critical error and crashes.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel 13500

**GPU**: Nvidia RTX 2070

**GPU Driver Version**: 536.40

**Audio**: Realtek something or other built onto the motherboard. The audio works just fine.

### Installation
**ALVR Version**: 20.1.0

**ALVR Settings File**: Is it session.json? I've reinstalled so much that it's the install defaults anyway.

**SteamVR Version**: 1.26.7

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 version 22H2, Build 19045.3208

**Comment by korbykob** [comment]
Also getting this, launching vrchat wirelessly gives the same result, seems to crash at any tiny lag spike.

**Comment by zarik5** [comment]
Do you get any error inside crash.txt? (Probably not). In any case try downloading Visual Studio and attach a debugger to vrserver.exe as soon as SteamVR is launched, this will give you a stack trace of the crash.

**Comment by BlipBlorp** [comment]
Here are the contents of crash_log.txt from the ALVR folder, if that's what you mean by crash.txt

> {"timestamp":"15:44:43.138176200","event_type":{"id":"Log","data":{"severity":"Error","content":"Handshake error for 8895.client.alvr: Error while waiting for stream ack: At alvr\\sockets\\src\\control_socket.rs:41: At alvr\\sockets\\src\\control_socket.rs:41"}}}
{"timestamp":"14:44:09.089335200","event_type":{"id":"Log","data":{"severity":"Error","content":"Handshake error for 4694.client.alvr: At alvr\\server\\src\\connection.rs:298: Control socket failed to connect"}}}
{"timestamp":"14:53:59.141247300","event_type":{"id":"Log","data":{"severity":"Error","content":"Handshake error for 4694.client.alvr: At alvr\\server\\src\\connection.rs:298: Control socket failed to connect"}}}
{"timestamp":"14:55:40.624374300","event_type":{"id":"Log","data":{"severity":"Error","content":"Handshake error for 4694.client.alvr: At alvr\\server\\src\\connection.rs:298: Control socket failed to connect"}}}
{"timestamp":"22:53:16.610901600","event_type":{"id":"Log","data":{"severity":"Error","content":"Handshake error for 4694.client.alvr: At alvr\\server\\src\\connection.rs:298: Control socket failed to connect"}}}

As for Visual Studio, I've never touched the program in my life and I hope I've got what you're looking for zarik. If it isn't, please point me in the right direction and I'll try again.

> Unhandled exception at 0x00007FFD1D8ECF19 in vrserver.exe: Microsoft C++ exception: NVENCException at memory location 0x000000EF51B1CD20.

**Comment by zarik5** [comment]
@BlipBlorp ALVR shows nothing useful, but that's ok. With Visual Studio, you need to check the call stack.

**Comment by BlipBlorp** [comment]
Here's what I see in the call stack. I'm not sure what I'm supposed to be checking. Does it matter that alvr_server.pdb is not able to load symbols?
![call stack](https://github.com/alvr-org/ALVR/assets/141341434/60e6929f-cdac-49f9-81cc-d2b9fcd19960)

The only thing I could find that looked maybe useful was the contents of the output tab on the bottom there. Here are its contents:

[output log.txt](https://github.com/alvr-org/ALVR/files/12293985/output.log.txt)

**Comment by zarik5** [comment]
@BlipBlorp Hm, the symbols have been stripped... can you recompile ALVR in debug mode? (just don't add the --release flag)

**Comment by zarik5** [comment]
You could actually download the latest nightly `alvr_streamer_windows_debug.zip`.

**Comment by BlipBlorp** [comment]
I tried it with the nightly debug build, and I'm pretty sure I'm doing something wrong with Visual Studio. As it is, I'm getting everything set up with ALVR so that I'm right at the point where it crashes. I then load Visual Studio without code, go to the debug menu, attach the debugger to vrserver.exe, and then get the headset to connect via USB. SteamVR crashes, this is what visual studio looks like. 

![call stack attempt 2](https://github.com/alvr-org/ALVR/assets/141341434/91187c63-b8e1-4244-a59f-de94d2a36513)

I think I'm missing something that would allow visual studio to provide more information? I would like to emphasize that I have never used this program in my life and am not a coder, so unfortunately you're going to have to debug me first.

**Comment by zarik5** [comment]
Have you tried using a newer version of Visual Studio? I used VS 2022. Or maybe you could try loading the pdb file manually.

**Comment by BlipBlorp** [comment]
Yep, already using VS 2022, and I don't have a pdb file. Do I download it somewhere or create it somehow? Is there something packaged with VS 2022 that I didn't install maybe?

**Comment by zarik5** [comment]
The PDB file should be in the same directory as the ALVR driver. `\bin\win64\driver_alvr_server.pdb`. You can try copying it to the same directory of vrserver.exe instead.
When I cause a crash, I get correctly the stacktrace symbols without copying the pdb file around.

**Comment by BlipBlorp** [comment]
Alright, I completely reinstalled visual studio with absolutely every package that microsoft offers by default. I then tried to directly load the pdb file to get the symbols, and nope:
![no symbols here](https://github.com/alvr-org/ALVR/assets/141341434/f7708442-ef22-4ba8-92d3-4ce0c6d62117)

I then tried to load the pdb file into visual studio by itself, and this happens:
![what happens when I load the pdb file](https://github.com/alvr-org/ALVR/assets/141341434/dd346336-4630-4050-8500-eb5826d7563a)

It just displayed the file as hex after the warning message.

**Comment by zarik5** [comment]
I think you may need to compile ALVR from source. CI might be messing something in the binaries to prevent proper symbol loading.

**Comment by zarik5** [comment]
Same issue with a guy on Discord trying to debug. I'm pretty sure the pdbs are generated wrong. You your only option is to compile from source for now. You can follow the guide here https://github.com/alvr-org/ALVR/wiki/Building-From-Source
Feel free to ask me for help if you need.

**Comment by BlipBlorp** [comment]
I already found the guide last night, and I spent a bit of time trying to see if I could do it without having to start visual studio tutorials. I asked a programmer buddy of mine with Visual Studio experience to walk me through it, but it'll be a few days before we have free time at the same time. Thanks for the offer though, and I'll take you up on that if he can't make it.

**Comment by zarik5** [comment]
You don't need to use Visual Studio at all for building. Just follow the guide as it is. You just need to execute the commands from the command line.

**Comment by BlipBlorp** [comment]
Sorry for the delay. Emergencies happened.

But yeah, thank you for telling me that It's all just command line. I followed instructions and now we get a little bit more in Visual Studio!

![Call staaaack](https://github.com/alvr-org/ALVR/assets/141341434/801118d6-f290-471d-b79b-fe6a08b6b1c8)

Is this enough? Is there anything else I can do to help?

**Comment by zarik5** [comment]
Thank you for the report. I don't have much knowledge of this part of the code. If this crash happens especially during lag spikes as multiple people have reported, I suspect this is caused by a race condition inside SteamVR, where Present (and/or SubmitLayer) is called multiple times overlapping, which messes up our signaling system for the encoder. To work around this I've surrounded the Present and SubmitLayer calls with a mutex. You should be able to test this fix in the next nightly (2023.08.16)

**Comment by BlipBlorp** [comment]
Just tried most recent safe build of ALVR and everything works again! Thanks devs
