### ISSUE TITLE
[Linux][NVENC] Regression - Encoder: No capable devices found

### ISSUE THREAD

**Issue by FuzzyWuggzy** [alvr-org/ALVR#1771]
## Description
The nvenc encoder no longer works in v21.0.0-dev00 (compiled from source), even though it does in v20.0.0-dev00 (also from source) with the same settings (namely "Adapter index' changed to "1"). The h264 encoder still works but as the system I'm currently stuck with only has a i7-7700HQ the performance is abysmal.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: i7-7700HQ

**GPU**: Nvidia GTX 1060M

**GPU Driver Version**: 525.116.03 (CUDA 12.0)

**Audio**:  Intel CM238

### Installation
**ALVR Version**: v21.0.0-dev00

**ALVR Settings File**: [session.txt](https://github.com/alvr-org/ALVR/files/12267694/session.txt)

**SteamVR Version**: 1.26.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [X] Source

**OS Name and Version**: Nobara Linux 37 (Thirty Seven)

**Comment by Vixea** [comment]
This worked for in in v20?

**Comment by Vixea** [comment]
Could you please retest with the latest release

**Comment by Vixea** [comment]
@FuzzyWuggzy could you retest with the latest nightly going through the backlog of issues and there's been fixed for nvenc

**Comment by Mon-Ouie** [comment]
Doesn't work' for me with a GTX 1080, the only difference is that the message on newer version changed to "Provided device doesn't support required NVENC features". Not sure how to find out which features are missing. With the same hardware, HEVC encoding works great on windows.

**Comment by norman-knott** [comment]
Same for me at ALVR 20.6.1 (AppImage and zip distri), Ubuntu 22.04, GTX 1080, nivida driver 525, ffmpeg 4.4.2-0ubuntu0.22.04.1.

`ffmpeg -encoder` shows support for nvenc:

![grafik](https://github.com/alvr-org/ALVR/assets/18596176/5481e19e-bddd-440e-95f5-c1c72d200623)

But ALVR shows nvenc is not supported.

**Comment by norman-knott** [comment]
Same with nvidia driver 545

**Comment by le-si** [comment]
Same for 450 and 3060 RTX

**Comment by norman-knott** [comment]
Also for nvidia driver 550

**Comment by afsolano** [comment]
Also for nvidia driver 555

**Comment by ZGltYQ** [comment]
Same problem with 555 nvidia driver
