### ISSUE TITLE
20.0.1: How to find streamer C code build error 

### ISSUE THREAD

**Issue by panxy2013** [alvr-org/ALVR#1772]
Hi, i have download 20.0.1 and modify some changed. 

i meet ALVR server build error, but console can't see error message. how to solve it? thanks

Run command on windows: cargo xtask build-streamer

Console output:
 cargo xtask build-streamer
    Finished dev [unoptimized + debuginfo] target(s) in 0.37s
     Running `target\debug\alvr_xtask.exe build-streamer`
$ cargo build
   Compiling alvr_server v20.1.0 (D:\dev\20.1\ALVR-20.1.0\alvr\server)
error: failed to run custom build command for `alvr_server v20.1.0 (D:\dev\20.1\ALVR-20.1.0\alvr\server)`

Caused by:
  process didn't exit successfully: `D:\dev\20.1\ALVR-20.1.0\target\debug\build\alvr_server-1f9b4b61d3d71d51\build-script-build` (exit code: 1)
  --- stderr

  error occurred: Command "D:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Brepro" "-I" "cpp/openvr/headers" "-I" "cpp" "-W4" "/std:c++17" "/permissive-" "-DNOMINMAX" "-D_WINSOCKAPI_" "-D_MBCS" "-D_MT" "-FoD:\\dev\\20.1\\ALVR-20.1.0\\target\\debug\\build\\alvr_server-409d84b63bc6b9cc\\out\\cpp\\alvr_server\\alvr_server.o" "-c" "cpp\\alvr_server\\alvr_server.cpp" with args "cl.exe" did not execute successfully (status code exit code: 2).

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: command exited with non-zero code `cargo build`: 101', alvr\xtask\src\build.rs:83:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-streamer` (exit code: 101)

**Comment by zarik5** [comment]
This looks like an issue with your MSVC installation. Try to reinstall Visual Studio. Try also to clone ALVR on the C drive instead.

**Comment by panxy2013** [comment]
Sorry to interrupt, the issue has been fixed.

I misunderstood that 20.1.0 hide some c++ build error messages. I can find these build error messages in the console and fix the local build error.

**Comment by xujunjie12345** [comment]
How did you solve it? I'm also unable to see specific errors in the console.

![image](https://github.com/user-attachments/assets/f54e7571-8cdd-4272-922f-cf14cfdc61d7)

> Sorry to interrupt, the issue has been fixed.
> 
> I misunderstood that 20.1.0 hide some c++ build error messages. I can find these build error messages in the console and fix the local build error.

**Comment by zmerp** [comment]
@xujunjie12345 why are you using an old version of the server?

**Comment by xujunjie12345** [comment]
> @xujunjie12345 why are you using an old version of the server?

@zmerp 
I am using version 20.6.1, and I have also tried version 20.8.1, but both encounter the same issue during compilation.

**Comment by zmerp** [comment]
Can you provide the full terminal output?

**Comment by xujunjie12345** [comment]
![WXWorkCapture_17332291296089](https://github.com/user-attachments/assets/52e8a281-dbcd-4c1d-9e6b-2008c3581c8d)

**Comment by zmerp** [comment]
I would say you also need to reinstall Visual Studio

**Comment by treeknows** [comment]
@xujunjie12345 Hi, I met the same error with you. Have you solved this build error?
