### ISSUE TITLE
Support eye tracking on Pico 4 Enterprise

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#1774]
ALVR needs to support XR_EXT_eye_gaze_interaction.

**Comment by exstrim401** [comment]
Also present on Pico 4 Pro (chinese version)

**Comment by Meister1593** [comment]
I think extension is present on all pui 5+ even if there is no eye tracking, and maybe older 4.7 (pico neo 3 pro), but that might not run alvr properly right now.

**Comment by Meister1593** [comment]
Latest master now supports that and you can use it on pico 4 pro, enterprise. Works pretty well with vrchat osc.
