### ISSUE TITLE
eye pose is wrong in YVR （ALVR-nightly）

### ISSUE THREAD

**Issue by happychui** [alvr-org/ALVR#1778]
eye pose is wrong in YVR

When i use YVR, my visual height went straight to the floor.

![1111](https://github.com/alvr-org/ALVR/assets/2732229/0f710d0f-7d92-48c6-bcfb-9ff99a2029f3)

https://github.com/alvr-org/ALVR/assets/2732229/d0014861-3c70-4da5-ad76-fd159a173fc4

**Comment by zarik5** [comment]
Unfortunately I don't have a YVR to test. Is thing game breaking or does it affect only the lobby room?

**Comment by happychui** [comment]
This only happens after updating the latest firmware.

not only lobby room， also in the game.

![4d16dd70b42bc88ca2d445b90034701](https://github.com/alvr-org/ALVR/assets/2732229/8fe93e2c-cfc1-472a-806f-d19fc9bdb51a)

reset room setting will be correct. but restart app this bug appear again.

**Comment by zarik5** [comment]
What do you mean with "reset room"? Do you mean redoing the guardian boundaries or recentering? In any case if this is a bug that appeared after a firmware update there is nothing that ALVR can do, you need to wait for a new firmware with a bug fix.

**Comment by happychui** [comment]
yes, i must redoing the guardian boundaries or recentering. 
lobby correct affter alvr connected steamvr.
