### ISSUE TITLE
Cant create distrobox container

### ISSUE THREAD

**Issue by Borderpatrol1987** [alvr-org/ALVR#1787]
## Description

when running the script, it crashes when creating the distrobox due to multi ID's

 Checking dependencies...
 Fetching crun 1.8.4...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2764k  100 2764k    0     0  2231k      0  0:00:01  0:00:01 --:--:-- 3628k
 Fetching podman 4.5.0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 30.3M  100 30.3M    0     0  21.8M      0  0:00:01  0:00:01 --:--:-- 78.5M
 Unpacking Podman...
 Copying in /home/dc/ALVR-Distrobox-Linux-Guide-main/installation/podman...
 Configuring...
 Cleaning up...
Successfully installed to /home/dc/ALVR-Distrobox-Linux-Guide-main/installation/podman.
Be sure that /home/d/ALVR-Distrobox-Linux-Guide-main/installation/podman/bin is in your $PATH environment variable for it to work.
 : Installing distrobox
mkdir: cannot create directory ‘distrobox’: File exists
Cloning into 'distrobox-git'...
fatal: not a git repository (or any of the parent directories): .git
 Installation successful!
 Shell scripts are located in ../distrobox/bin
 Manpages are located in ../distrobox/share/man/man1
 Be sure that ../distrobox/bin is in your $PATH environment variable to be able to use distrobox without specifying the full path.
 : Phase 2
localuser:d being added to access control list
nvidia
Error: command required for rootless mode with multiple IDs: exec: "newuidmap": executable file not found in $PATH
 : Couldn't create distrobox container, please report it to maintainer.
 : GPU: nvidia; AUDIO SYSTEM: pulse

**Comment by Meister1593** [comment]
I will close this issue as it's pretty old anyway, but if you have any issues with new version - open issue here: 
https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues
