### ISSUE TITLE
ALVR 19.1.1 doesn't work on latest Meta OS update for Quest 2.

### ISSUE THREAD

**Issue by RomanVolvenkov** [alvr-org/ALVR#1789]
Hello!

As the title says, after the latest update on Quest 2, the ALVR 19.1.1 is not working anymore.
Is there anything we could do? We have an integration with this version and would like to stay with it.

Thanks in advance!

**Comment by qqshnep** [comment]
you should add a new permission in AndroidManifest.xml

<uses-permission android:name="android.permission.WAKE_LOCK"/>

**Comment by qqshnep** [comment]
you should add a new permission in AndroidManifest.xml

`<uses-permission android:name="android.permission.WAKE_LOCK"/>`

**Comment by RomanVolvenkov** [comment]
> 

It worked! Thank you!

**Comment by AntAngel** [comment]
where do i add that new permission, because im trying to fix it and i can't
