### ISSUE TITLE
ALVR appimage fails to start with " XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme"

### ISSUE THREAD

**Issue by stenwt** [alvr-org/ALVR#1793]
## Description

New install of ALVR, does not start. Ran it from the command line and got a rust backtrace, included below

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=fc789db4f9

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**: v20.1.0

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc) APPIMAGE
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

RUST_BACKTRACE=full ./ALVR-x86_64.AppImage 
[15:20:16.634211394 ERROR sctk_adwaita::config] XDG Settings Portal did not return response in time: timeout: 100ms, key: color-scheme
thread 'main' panicked at 'Error in Surface::configure: Validation Error

Caused by:
    Requested usage is not supported
', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.1/src/backend/direct.rs:734:18
stack backtrace:
   0:     0x56536b7962fc - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x56536b7962fc - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56536b7962fc - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x56536b7962fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x56536b491a6f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x56536b765d74 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x56536b797b0f - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x56536b797b0f - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x56536b79770e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x56536b798780 - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x56536b798780 - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x56536b798264 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x56536b7981c6 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x56536b7981b1 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x56536b0e3922 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x56536b94f2c0 - wgpu::backend::direct::Context::handle_error_fatal::hbac80efa83cea858
  16:     0x56536b94c4ca - <wgpu::backend::direct::Context as wgpu::context::Context>::surface_configure::hdb393267a295c92a
  17:     0x56536b578010 - egui_wgpu::winit::Painter::configure_surface::hd175a34b00ff7d73
  18:     0x56536b5779ac - egui_wgpu::winit::Painter::resize_and_generate_depth_texture_view_and_msaa_view::he5394754b314c4d7
  19:     0x56536b517cfb - pollster::block_on::he3f46034d773ceb1
  20:     0x56536b4ddfad - <eframe::native::run::wgpu_integration::WgpuWinitApp as eframe::native::run::WinitApp>::on_event::h16088a08ab5994ae
  21:     0x56536b520f89 - eframe::native::run::run_and_return::{{closure}}::h307fc594cb2270c3.22920
  22:     0x56536b4cb514 - eframe::native::run::run_and_return::h4350107e29c186e8
  23:     0x56536b2afb1c - alvr_dashboard::main::habac81a7c2eff736
  24:     0x56536b23c063 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3236efc1b52e9b2d
  25:     0x56536b2a97ed - main
  26:     0x7f015f829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  27:     0x7f015f829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  28:     0x56536b1135b5 - _start
  29:                0x0 - <unknown>

**Comment by Vixea** [comment]
Not sure if you're going to have much luck running alvr in a vm
