### ISSUE TITLE
Distrobox install script: Fails on phase 3 when using distribution without systemd

### ISSUE THREAD

**Issue by xenanthropy** [alvr-org/ALVR#1798]
Sourcemage GNU/Linux, OpenRC init system

Fails with error: 
`Error: OCI runtime error: unable to start container "ddbd012c06a7e5e973ace8620953c6ee5986fa22b539fbc41610ba21244e5353": crun: sd-bus call: The name org.freedesktop.systemd1 was not provided by any .service files: No route to host`

Attached setup.log below
[setup.log](https://github.com/alvr-org/ALVR/files/12385102/setup.log)

**Comment by xenanthropy** [comment]
This is still an issue, does not work without systemd

**Comment by Vixea** [comment]
Yes this is a requirement of distrobox it seems nothing we can do about it.

**Comment by Vixea** [comment]
You could try installing podman seems to complain about that multiple times maybe it will take a different path in which you do not need systemd

**Comment by xenanthropy** [comment]
Yeah I figured, ah well... Tis the price of not using systemd :) I'll live, I was struggling to get VR working on wayland anyway so this doesn't matter much.
