### ISSUE TITLE
Appimages for ALVR nightly broken (for me) as of July 3rd

### ISSUE THREAD

**Issue by xenanthropy** [alvr-org/ALVR#1799]
Not sure if this is the appropriate place to put this, but alvr-nightly doesn't have an issue tracker so:

Every appimage of alvr nightly fails to work for me as of the July 3rd release
([ALVR v21.0.0-dev00+nightly.2023.07.03](https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.07.03))

The last confirmed working appimage is July 1st (I cannot test July 2nd, as there is no appimage for it for some reason)
([ALVR v21.0.0-dev00+nightly.2023.07.01](https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.07.01))

The original error I got upon running them was that it could not find libthai (libs missing from the appimage perhaps?) I managed to install libthai and it's dependencies - now when I launch it (depending on the version, anywhere from July 3rd to today) it either hangs, or I get "segmentation fault".

I'm not sure if this is a problem with ALVR, or the appimage-making process going wrong somewhere.

**Comment by zarik5** [comment]
A fix was pushed, and reports say this has been fixed.

**Comment by xenanthropy** [comment]
Yep confirmed - as of my testing (version August 25th) it now works! Will mark as closed then

**Comment by DestyNova** [comment]
The latest stable release (v20.4.3) segfaults for me on POP!_OS.
