### ISSUE TITLE
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./alvr_dashboard)

### ISSUE THREAD

**Issue by xznhj8129** [alvr-org/ALVR#1811]
## Description
When trying to run either the tar.gz portable version or the appimage, app fails 
./alvr_dashboard: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./alvr_dashboard)

./alvr_dashboard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./alvr_dashboard)

./alvr_dashboard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./alvr_dashboard)

./alvr_dashboard: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./alvr_dashboard)

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
no instructions for linux, and i'm not an advanced builder/debugger
- [yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment/Hardware
OS: Linux Mint 20.3 x86_64
Kernel: 5.15.0-79-generic
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Nvidia RTX3060

**Comment by Nathan22211** [comment]
this is apparently an issue if you're running Ubuntu 20.04 the needed lib is only in 22.04 (which a newer version of mint uses). I'm on zorin OS so I need a workaround in order to even use ALVR as they're often a major version behind and I need a wayland distro which mint isn't
