### ISSUE TITLE
os error 997 (WSA_IO_PENDING) causes disconnection randomly

### ISSUE THREAD

**Issue by cathiecode** [alvr-org/ALVR#1814]
I tested with VRChat however probably causes with any applications.

## Description

The client randomly disconnects from the server with log os error 997.
According to [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2), Winsock error 997 is called WSA_IO_PENDING, which indicates requested system calls will be done lately. I think this is harmless, at least when I use UDP connections.
This may be caused by overload however my connection and system seem to have enough bandwidth for streaming. Anyway, I think WSA_IO_PENDING should be handled as a non-fatal disconnection.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 5 5500

**GPU**: Radeon RX 6600 XT

**GPU Driver Version**: 23.7.2

**Audio**: On-board configuration (High definition audio device)

**Network**: Windows 11 -> (Ethernet) -> Wi-fi router -> (5Ghz Wi-fi) -> Quest 2

### Installation
**ALVR Version**: 20.2.1 and [v21.0.0-dev00+nightly.2023.08.27](https://github.com/alvr-org/ALVR-nightly/releases/latest)

**ALVR Settings File**: Default setting, provided with the setup wizard. [session.json.txt](https://github.com/alvr-org/ALVR/files/12472395/session.json.txt)

**SteamVR Version**: 1.26.7

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc) - tested with stable
- [x] Portable (`zip`)  - tested with nigthly
- [x] Source

**OS Name and Version** : Windows 11 Home Build 22621.2134 (Japanese)

Log around error 997 from nightly: [session_log_around_error_997.txt](https://github.com/alvr-org/ALVR/files/12472466/session_log_around_error_997.txt)
Full Log: Too big to upload so I uploaded to Google Drive. [File](https://drive.google.com/file/d/1iTO2akLPzkXB0a_M27z1qDKQOY8JSoVV/view)
Translated error 997 log text from Japanese: `Client disconnected. Cause: Performing duplicate I/O operations. (os error 997)`
Log by local debug build: ![スクリーンショット 2023-08-30 181427](https://github.com/alvr-org/ALVR/assets/74973441/b08095da-1555-4850-8023-b890d359ab82)

Sorry for my poor English and scarce knowledge.

**Comment by cathiecode** [comment]
After some investigation, I realized it may be a regression made around 444d0874d2f7e944d046b922092dcc9eb0ed11dc - e440137dcc88d0d548abb45aa2c6c81300e8067a for synced socket.

**Comment by zarik5** [comment]
Thank you for your help. Are you able to find the exact commit of the regression?

**Comment by cathiecode** [comment]
I don't know how it works and disconnection occurs randomly so it will take a long time, But I'll try. Thanks for the huge effort in developing ALVR.

**Comment by cathiecode** [comment]
I bisected and I comfirmed this does not happen before 7/17 nightly and occurs in 20.2.1 Release, at least.
I tried to check 8/16 nightly, the log does not appears but crashes without log, so I gave up bisecting.
After inspecting several crash logs and codes, I'm suspecting changes around 803ffb5 causing this phenomenon.
I Sorry for unclear report.

**Comment by Vixea** [comment]
Nawh unstale
