### ISSUE TITLE
Controller tracking not work in Pico OS 5.8

### ISSUE THREAD

**Issue by zk-wz** [alvr-org/ALVR#1816]
After updating to Pico OS 5.8 beta system(Pico4), the controller tracking is not working properly. The specific issue is that the position of the controller cannot be updated, but the buttons on the controller are still functional.

I'm not sure if this is intended by Pico, but I have already provided them with feedback regarding this issue. 

If pico fix this problem, I'll promptly close this issue, otherwise I'll ensure to provide consistent updates on its status here.

**Comment by zarik5** [comment]
What is your total latency?
Maybe @galister or @Meister1593 can help.

**Comment by zk-wz** [comment]
Total latency is 70ms, I've tried my settings and defalut settings, neither worked.

**Comment by galister** [comment]
5.8 is not out for Pico 4 yet so can't test.

**Comment by barnabwhy** [comment]
I'm also getting this bug on 5.8.0. Pico OS 5.8 is still in a testing phase though iirc so it may be fixed by the time it releases. It could also, however be related to this part of the OpenXR spec https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_BD_controller_interaction

**Comment by zarik5** [comment]
@galister the interaction profile we are using at the moment is `/interaction_profiles/pico/neo3_controller`, which is nowhere documented in the OpenXR spec. So apparently Pico doesn't seem worried about breaking compatibility, the same way they broke compatibility by switching from their broken prediction system to following proper OpenXR spec for `xrEndFrame`.

**Comment by Meister1593** [comment]
> @galister the interaction profile we are using at the moment is `/interaction_profiles/pico/neo3_controller`, which is nowhere documented in the OpenXR spec. So apparently Pico doesn't seem worried about breaking compatibility, the same way they broke compatibility by switching from their broken prediction system to following proper OpenXR spec for `xrEndFrame`.

actually, i think they do have documented it
https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_BD_controller_interaction

**Comment by barnabwhy** [comment]
> To implement this fix, we need a way to detect if the hardware is a Pico Neo 3 or a Pico 4. Do they have a different model name? The model name can be read in the client entry on the server.

pico 4 model name is different, yes

**Comment by galister** [comment]
pico 4 sadly has a bunch of different model names and not all of them are known
WiVRn uses the following logic, but it's far from perfect
`ro.product.manufacturer == "Pico" && ro.product.model != "Pico Neo 3"`

**Comment by zarik5** [comment]
We can work with that. I can push a patch for this.

**Comment by galister** [comment]
Note i'm not sure if this covers all the PN3 editions. but as far as I've seen all pico 4 models follow the format of
```regex
A[0-9A-Z]{4}
```

**Comment by barnabwhy** [comment]
For a global Pico 4 this can be used as the identifier (just check it starts with Phoenix, iirc the chinese one is `Phoenix_cn`)
`[ro.product.name]: [Phoenix_ovs]`

You can also check any of these (any that say pico 4 you should probably do a regex for `/^PICO 4/` because of enterprise and pro models):
`[pxr.vendorhw.product.model]: [PICO 4]`
`[ro.product.odm.name]: [Phoenix_ovs]`
`[ro.product.system.name]: [Phoenix_ovs]`
`[ro.product.vendor.name]: [Phoenix_ovs]`
`[sys.pxr.product.name]: [PICO 4]`

also from my understanding `ro.product.model` may just always be `A8110` on PICO 4 (but pico 4 pro and pico 4 enterprise probably have different ones)

**Comment by zk-wz** [comment]
Guys I've noticed on Discord that your commit from yesterday appears to have fixed the issue, but the latest nightly build still can't get me to use the controller. And my feedback to Pico hasn't received any response 😟.

I'm using the Chinese 5.8 beta version of Pico OS. Could this be the root of the problem, or is it possible that there's simply more work to be done on your end?

**Comment by zk-wz** [comment]
Things seems to be weird, my friend told me that he has no problem with 7.17 nightly build, and I tried it, it seems to be working as well. Maybe one of the commits in between messed something up?🤔

**Comment by zk-wz** [comment]
We finally happy to see Pico fix this issue in the latest pui 5.8 beta, now everything works properly, the issue will be closed.
