### ISSUE TITLE
[Linux] [Audio] ALVR is looking for inputs to use as outputs and outputs to use as inputs.

### ISSUE THREAD

**Issue by Killrmemz** [alvr-org/ALVR#1821]
There are a number of bug reports related to audio in Linux, and it's historically only half-worked, even when the ALSA backend was implemented, but I think I've hit the root of the problem; exactly what the title says.
I have no idea how simple it will be to solve, but for the time being, I have created a workaround, that at minimum works for me. I am running EndeavourOS (Arch distro), Kernel 6.4.12-arch1-1, KDE Plasma X11, with Pipewire as my primary audio backend. I can't guarantee that it will work for you if you use a different Desktop Environment or PulseAudio instead of PipeWire.

1: Run the following commands to create virtual interfaces
`pactl load-module module-null-sink media.class=Audio/Sink sink_name=ALVR channel_map=stereo`
`pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=ALVR-mic channel_map=center`
2: Set them as default inputs and outputs.
3: Set your ALVR audio settings as follows:
Backend: ALSA, Game Audio: Set By index:1, Microphone: Set Sink By index: 1 and Source By index: 2

4: Install and Open Qpwgraph
5: Connect headset and start SteamVR
6: Two blocks labelled "PipeWire ALSA [vrserver]" will appear in Qpwgraph, connected to the virtual audio devices. Disconnect them, and connect them to the other virtual audio device.
7: Repeat step 6 every time the headset reconnects.
Reference images attached.
![image](https://github.com/alvr-org/ALVR/assets/13648914/cc250036-747e-475e-9b8b-d01f1dff3fff)
![image](https://github.com/alvr-org/ALVR/assets/13648914/eb5bf488-4ec5-4bd0-90f5-dc4939785d4a)
![image](https://github.com/alvr-org/ALVR/assets/13648914/23731d76-2218-48c2-a430-a5618ec2f3dc)
![image](https://github.com/alvr-org/ALVR/assets/13648914/864a7d1d-77f0-434b-bd62-db8fe311fbe4)
I am aware that there is a workaround script already on the wiki, but it creates two virtual devices for both input and output, effectively ignoring/bypassing the issue, so I feel that it's still relevant that I post this.

**Comment by Vamaka12** [comment]
Can confirm, I tried almost every combination of indexes, yet none of them landed on sink/source.
Guess I'll need to reconnect them manually each time too.

Arch linux + kde
Added audios the same way as OP

**Comment by alkeryn** [comment]
@Vamaka12 what script are you talking about ?

**Comment by Vamaka12** [comment]
@alkeryn [Here's how I got it working](https://github.com/alvr-org/ALVR/blob/d2100d0780d06f2ae6a54c982f54c54e27a4460c/wiki/Installation-guide.md#automatic-audio--microphone-setup)

P.S Game audio also works, but I use earbuds so I have it off

![image](https://github.com/alvr-org/ALVR/assets/71032898/c7d4e08a-38b4-45a1-ae13-e3bc92432b9f)

**Comment by alkeryn** [comment]
@Vamaka12 hey thanks, if that can prevent me from having to wire it up each time in the patchbay that's great !

**Comment by ConorVernon** [comment]
I have been really struggling to get the wiki script working correctly. With game audio and mic set to pipewire as per my settings in the following screenshot, I get these results (Kubuntu, .appimage):
- Default audio switches to the ALVR audio sink, but no desktop or game sound can be heard. 
- I hear an echo of my mic input in the headset coming from the mic sink
- If I switch my default device to the ALVR mic sink, all audio will play on the headset, but I can still hear my mic
![image](https://github.com/alvr-org/ALVR/assets/22355454/4012aab8-e1ef-475b-956f-51366e7bec8a)

I'm frankly just getting lost between all the possible combinations of settings to make it do the following:
- Capture mic input for games to use without it being echoed back
-  Play game audio in the headset

**Comment by ConorVernon** [comment]
Now that I've had some time away from it (sorry for the venting earlier) I've managed to edit the audio-setup script in a way that works for me.

In the `setup_mic()` function I use `pw-link` to link the audio sink and unlink the mic source as you would in qpwgraph. Any earlier and it doesn't work, I added a constant called `LISTEN_TO_MIC` at the top of the file to control the unlink behaviour if I wanted.

```
function setup_mic() {
  if [[ $USE_HEADSET_MIC == 1 ]]; then
    echo "Creating microphone sink & source and linking alvr playback to it"
    # This sink is required so that it persistently auto-connects to alvr playback later
    pactl load-module module-null-sink sink_name=ALVR-MIC-Sink media.class=Audio/Sink | tee -a /run/user/1000/alvr-audio
    # This source is required so that any app can use it as microphone
    pactl load-module module-null-sink sink_name=ALVR-MIC-Source media.class=Audio/Source/Virtual | tee -a /run/user/1000/alvr-audio
    # We link them together
    pw-link ALVR-MIC-Sink:monitor_FL ALVR-MIC-Source:input_FL
    pw-link ALVR-MIC-Sink:monitor_FR ALVR-MIC-Source:input_FR
    # And we assign playback of pipewire alsa playback to created alvr sink
    pactl move-sink-input "$(get_playback_sink_input_id alsa_playback.vrserver)" "$(get_sink_id_by_name ALVR-MIC-Sink)"
    if [[ $LISTEN_TO_MIC == 0 ]]; then
      # Unlink from alsa capture to prevent mic playback
      pw-link -d ALVR-MIC-Source:capture_FL alsa_capture.vrserver:input_FL
      pw-link -d ALVR-MIC-Source:capture_FR alsa_capture.vrserver:input_FR
    fi
    pactl set-default-source ALVR-MIC-Source
    if [[ $USE_HEADSET_AUDIO == 1 ]]; then
      # Manually link to alsa capture because something earlier in the mic setup appears to unlink it
      pw-link ALVR-AUDIO-Sink:monitor_FL alsa_capture.vrserver:input_FL
      pw-link ALVR-AUDIO-Sink:monitor_FR alsa_capture.vrserver:input_FR
    fi
  fi
}
```

This gets me the result I wanted: Computer audio is automatically played through the headset and the mic remains a usable source without being played back. However, I can't rule out that I needed to do this because I configured it wrong elsewhere or am just not fully understanding the script's prior behaviour.

**Comment by guysoft** [comment]
Similar issue on Ubuntu 23.10 with Pipewire.


This is the actual behavior (microphone goes in input, I can hear my PC microphone in the headset, and the game is played on the computer sound card speaker):

![gtfy](https://github.com/alvr-org/ALVR/assets/325670/6d7d8d49-bbb6-4d0b-8780-5eb08f5f7a0e)

This is expected (did it manually, the game audio input should go in the the input of the headset):
![vrvr2](https://github.com/alvr-org/ALVR/assets/325670/6faf7fbc-964c-4359-ba38-e7c14abc8678)

**Comment by guysoft** [comment]
@ConorVernon Do you have a fork with this to test? I am not sure to paste that and against what version

**Comment by boswelja** [comment]
This is still an issue, not stale

**Comment by cjmoran** [comment]
@ConorVernon Thank you, this worked perfectly and put an end to my 12-hour debugging session (NixOS). I let ALVR download its audio-setup script using the UI, as specified in the wiki, then pasted your `setup_mic` function over it and it's working as I expect (game audio no longer plays out of PC speakers, mic no longer plays back in my ears).

For anyone else running the portable ALVR on NixOS through `steam-run`, be sure you also change the shebang in that `audio-setup.sh` script to `#!/usr/bin/env bash`.

**Comment by GHOSTKJB** [comment]
I am trying to impliment this on Ubuntu but I really don't understand where to put the script
