### ISSUE TITLE
Disabling foveated rendering makes ALVR unusable

### ISSUE THREAD

**Issue by hazre** [alvr-org/ALVR#1834]
## Description

Since v20.x, disabling foveated rendering completely breaks ALVR. (Not a connection issue, router is less than a meter away from me)

I disable all foveated related settings (rendering, clientside, dynamic oculus).

- on x264 it becomes a gray screen.
- on hevc its like the bitrate becomes jumpy (changes from very low bitrate to high bitrate constantly).

Here's a few clips showing the issue,

x264, foveated related settings disabled:

https://github.com/alvr-org/ALVR/assets/37149950/a85aeb19-314d-488b-90fd-b460b583ee95

x264, foveated related settings enabled:

https://github.com/alvr-org/ALVR/assets/37149950/c719a299-7b90-4c16-ab62-2c23ce4ab64c

hevc, foveated related settings disabled:

https://github.com/alvr-org/ALVR/assets/37149950/0734c077-64ca-4680-bcb5-10b93d98cfc6

hevc, foveated related settings enabled:

https://github.com/alvr-org/ALVR/assets/37149950/0b189329-a277-4179-b402-7ecac2e198df

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**Headset**: Quest Pro

**CPU**: R9 5900X

**GPU**: RX 7900 XTX

**GPU Driver Version**: 23.9.1

**Audio**: VB-Audio

### Installation
**ALVR Version**: v20.04

**ALVR Settings File**: (Mostly default preset)
https://gist.github.com/hazre/cf907a2b5cb3a14375211510818b84c3

**SteamVR Version**: 1.27.5 Beta

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Windows 11 Pro 22H2 (22621.2215)

**Comment by Timocop** [comment]
By your config
```json
"eye_resolution_width": 2592,
"eye_resolution_height": 2848,
"target_eye_resolution_width": 2592,
"target_eye_resolution_height": 2848,
```

Thats some insane render resolution. Your Quest 2 probably cant even handle that without foveated rendering. Try with a lower/native Quest 2 resolution (1832x1920 per eye) and check if theres a difference.

**Comment by Timocop** [comment]
Ah youre using a Quest Pro my bad. Still, try with a lower res (native 1800x1920 per eye)

**Comment by Vixea** [comment]
Closing because of user error
