### ISSUE TITLE
High latency and artifacts on Pico 4 + Linux

### ISSUE THREAD

**Issue by ZhenyaPav** [alvr-org/ALVR#1835]
## Description
ALVR is unusable for me due to high (60ms+) latency and graphical artifacts.

According to the graphs, latency is mostly caused by Client VSync (30ms+)

The artifacts look like purple and black/white squares near any lines. I can't provide the video, as they do not seem to show up on the recording. SteamVR view looks fine, which could point to a client issue.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

I have installed VAAPI drivers for AMD GPU, tried lowering bitrate, changing codec to HVENC and disabling foveated rendering. None had any effect.

### Hardware
https://linux-hardware.org/?probe=afbaf99497

### Installation
**ALVR Version**:
21.0.0_dev00.r2607.c73046a0-1
**ALVR Settings File**:
https://gist.github.com/ZhenyaPav/cab170817fb6f087f5c25d47f600ae8d
**SteamVR Version**:
beta 1.27.5
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version**
Arch Linux

**Comment by Swinec** [comment]
First, do u try VR on linux on wired devices?
SteamVR on linux have a LOT issues. Read the steamvr git stream.
AMDGPU on MESA driver have a great glitch bug in steamvr overlay and steamVR home.  Сan’t say exactly who is to blame, Mesa or Valve.
Glitches should not be during the game.

**Comment by ZhenyaPav** [comment]
> First, do u try VR on linux on wired devices? SteamVR on linux have a LOT issues. Read the steamvr git stream. AMDGPU on MESA driver have a great glitch bug in steamvr overlay and steamVR home. Сan’t say exactly who is to blame, Mesa or Valve. Glitches should not be during the game. Do u turn gpu in VR mod in radeon-profile?

Pico 4 is the only headset I have right now, so I don't have anything else to compare to. I have tried setting the power profile to "Virtual Reality", it made no difference.

**Comment by ZhenyaPav** [comment]
A small update: As of v20.5.0, the issue with the graphical artifacts is gone, an the app is quite usable, though the latency still remains high (60+ ms)

**Comment by JaJeff11** [comment]
Have you found the solution with the client v sync latency?

**Comment by myghi63** [comment]
@ZhenyaPav @JaJeff11 apparently, the client vsync is present but not considered in other streaming softwares like virtual desktop, quest link or streaming assistant. This latency will increase if you lower the refresh rate of the headset too!

**Comment by Vixea** [comment]
https://docs.google.com/spreadsheets/d/1ZXIM9YBsKMSMXyA8Dg_0XOOqL5mFFTp6tY793r2CWkQ/edit#gid=0
you can compare this graph for click-to-photon latency of alvr compared to VD on Windows as you can see its basically the same.

**Comment by Vixea** [comment]
and on good days on linux I can regularly get 64 ms measured by alvr which assuming the same error which is assuming a lot given a completely different OS would be lower than VD on windows

**Comment by ZhenyaPav** [comment]
> @ZhenyaPav @JaJeff11 apparently, the client vsync is present but not considered in other streaming softwares like virtual desktop, quest link or streaming assistant. This latency will increase if you lower the refresh rate of the headset too! in practice, the latency of alvr is actually lower than we might think

After testing it out myself, I am inclined to believe that this is indeed the case, which makes the latency comparable to VD. The issue with artifacts seems to have been fixed a while back, so I think this issue should be closed.
