### ISSUE TITLE
after Sep 5, 2023  yvr won't be working in Nightly

### ISSUE THREAD

**Issue by happychui** [alvr-org/ALVR#1836]
yvr version: 1.2.5.238

After running the app, it shows a black screen.

![image](https://github.com/alvr-org/ALVR/assets/2732229/e0c8b6a0-a7f0-4ccd-9d5a-6c7809827554)

**Comment by zarik5** [comment]
There is an issue with registered buttons. I don'e have a YVR to test. Please try removing or adding buttons in this list: https://github.com/alvr-org/ALVR/blob/master/alvr/common/src/inputs.rs#L871

**Comment by happychui** [comment]
I'm gonna try.

**Comment by happychui** [comment]
It's already been resolved.
