### ISSUE TITLE
Can anyone tell me the detail meaning of the debug items?

### ISSUE THREAD

**Issue by RGAA-Software** [alvr-org/ALVR#1838]
These items, thank you...

![Snipaste_2023-09-19_11-23-19](https://github.com/alvr-org/ALVR/assets/122289026/6bfdbf41-5af1-42a9-8347-3d1ee5b552a0)

**Comment by zarik5** [comment]
Game render: time between tracking submission and the game finishing to render a frame
Streamer compositor: layer compositing + foveation encoding  + color correction
Encode: video encoder
Network: data transmission
Decoder: video decoding on the client
Decoder queue: idle time used for proper frame alignent and reduce stuttering
Client compositor: gamma correction + foveation decoding
Client vsync: VR runtime compositor time + idle. We don't have control on this time. This is the latency every Quest app has.

**Comment by RGAA-Software** [comment]
@zarik5 Thank you very much!!!

**Comment by chutoutian** [comment]
One following up question, does AlVR support to export those statistics information?
