### ISSUE TITLE
Did anyone find a fix for the glitchy screen as demonstrated here.

### ISSUE THREAD

**Issue by Thezkiller03** [alvr-org/ALVR#1840]
This bug effect VRchat in dark areas and ALVR in dark areas too
This issue has been previously reported but never was anyone giving possible solutions, if there is an old version I can use before foveated rendering that might help

## Description

https://github.com/alvr-org/ALVR/issues/1619#issue-1708418782

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Thezkiller03** [comment]
i was gonna say only a few games i've found still have the bug and i was surprised that ALVR still had it, is it something to do with the foveated rendering?

**Comment by zarik5** [comment]
Exactly. Foveated rendering is the culprit most likely.
