### ISSUE TITLE
ALVR Error, Driver does not support CBR RC mode

### ISSUE THREAD

**Issue by SlushUwU** [alvr-org/ALVR#1842]
## Description
Everytime I try to connect my Oculus manually with my ALVR Dash and It tries to connect I get the 
`Encoder: Driver does not support CBR RC mode (supported modes: CQP).`
error.

## General Troubleshooting
- [ X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=b047457fd1
**CPU**:
Intel | 11th Gen Core i5-1135G7 @ 2.40GHz
**GPU**:
/
**GPU Driver Version**:
/
**Audio**:
Intel Corporation | Tiger Lake-LP Smart Sound Technology Audio Controller
### Installation
**ALVR Version**:
latest
**ALVR Settings File**:
*Not found*
**SteamVR Version**:
latest
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ X] Source

 **OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

**Comment by SlushUwU** [comment]
Now I get somehome this issue:


![grafik](https://github.com/alvr-org/ALVR/assets/105487011/368c23a5-4aab-42aa-82dc-a874c7cd1439)

**Comment by Vixea** [comment]
What is your GPU?

**Comment by Vixea** [comment]
And the second issue is a no brainier just read it lol

**Comment by SlushUwU** [comment]
> What is your GPU?
Internal, intel iRISxe

**Comment by Vixea** [comment]
That's not powerful enough for VR nor is it going to work do to driver incompatibilities

**Comment by SlushUwU** [comment]
> That's not powerful enough for VR nor is it going to work due to driver incompatibilities 

During some tests it worked well

**Comment by Vixea** [comment]
And those tests were?
