### ISSUE TITLE
Can ALVR support eye tracking in quest pro?

### ISSUE THREAD

**Issue by WuZemyp** [alvr-org/ALVR#1846]
Hello, I just read the source code of ALVR, I wonder whether it can support for eye tracking in quest pro? If so, where is the code for getting the eye tracking information from hmd? Thank you in advance!

**Comment by zarik5** [comment]
ALVR support eye and face tracking for the Quest Pro. The code is scattered between client and server, depends on what you are looking for. You can grep for "face" or "eye".

**Comment by WuZemyp** [comment]
Thank you for your reply!

**Comment by WuZemyp** [comment]
Hello, Could I ask what is the difference of global eye and local eye. I saw a function tracking::to_local_eyes. Thank you in advance!

**Comment by zarik5** [comment]
Global eye pose if the pose returned by OpenXR and it's relative to the global reference frame, usually a point on the floor with direction aligned with your playspace. Local eye is the pose of the eyes relative to the head pose, looking straight ahead. The head pose is the mid point between the two eyes.

**Comment by WuZemyp** [comment]
Hello, it seems like alvr doesn't use the real eye gaze data to do FFR? I trace the code from sending the tracking information to server, and after the server received the tracking information. There is a function call (sink.send_tracking(face_data);), I saw the code in send_tracking, could you explain me more about the functions send_osc_message() and append_packet_vrcft(). Where the data would be sent to when using send_osc_message(), and where is the receving code of the osc message, what is the funcationality? Thank you so much!
