### ISSUE TITLE
Alvr build cannot detect cuda 

### ISSUE THREAD

**Issue by Hsky17** [alvr-org/ALVR#1848]
## Description
When you are building alvr on fedora 38 (I havent tested earlier versions), it fails to detect cuda unless you specify a version number. This could be a issue where fedora symlinks the cuda directory and when you change the version manually, it works.
This has been tested on Fedora 38 and Nobara 38 (Flavor of fedora)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 7 5700G

**GPU**: RTX 3070

**GPU Driver Version**: 535.104.05

**Audio**: Pulseaudio?

### Installation
**ALVR Version**: N/A (Couldn't build)

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): 
Nobara release 38 (Thirty Eight) x86_64

Here is a video of it not working, and the workaround (Mind the bad mic):
https://github.com/alvr-org/ALVR/assets/95394930/1117f1db-5e94-4efa-a78d-238034e7926d

**Comment by Toxblh** [comment]
It's not an issue here. We don't know which version you will install. 11? 12? 12.3 or 13 in future. That is why we use https://github.com/alvr-org/ALVR/blob/master/alvr%2Fxtask%2Fdeb%2Fcuda.pc as abstract configuration in real life.
