### ISSUE TITLE
[Linux] SteamVR streams, but games does not

### ISSUE THREAD

**Issue by rafael-aba** [alvr-org/ALVR#1853]
## Description
I have been able to get SteamVR stream to my Quest 2, but when I launch a game, it only opens in the PC and isn't streamed to the PC. I am not sure if this is a ALVR or SteamVR issue.

Other details: 
- SteamVR is always on that "limbo" view. But I can summon the menu and start a game from there. 
- Once the game opens, I does not receive input from controllers or headset. My best guess is that they don't even see each other.
- Did try with different games and got the same result 
- Using an AMD GPU, encoders installed 

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[`hw-probe`](https://linux-hardware.org/?probe=cf9e8e26c2)

### Installation
**ALVR Version**:
v20.4.2 & nightly

**ALVR Settings File**:
default

**SteamVR Version**:
latest

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Fedora Linux 38 (Workstation Edition)

**Comment by MadByteDE** [comment]
- Do you get to the Steam Home screen at some point?
- Also, did you see the "SteamVR requires superuser access to finish setup." dialog?

Sounds like something that would happen with a sandboxed flatpak install, have you tried the AppImage?

At least for me v20.4.2 as AppImage runs well on Fedora 38 (also Quest 2). I'm currently using an NVIDIA GPU, but previously my 5700XT worked fine as well.

**Comment by rafael-aba** [comment]
> * Do you get to the Steam Home screen at some point?

I did not get to Stream Home after 10 minutes of waiting.

>     * Also, did you see the "SteamVR requires superuser access to finish setup." dialog?

I have not seen that dialog yet. I'll try later Today again and search for it in case I missed it. 


> > But I can summon the menu and start a game from there
> 
> Meaning input works for the "limbo" screen but not for games?

Correct. ALVR has the status streaming, I was able to click Trust normally, and I can see SteamVR on my headset. But yes, I stay in that "limbo" page. By clicking the menu button the the left controller I can summon a window that allows me to start installed games.
I can start a game, it shows the "Next Up" dialog on the headset, but that is where I'm getting stuck. The game starts in the computer, but it doesn't get streamed to the Headset. 

It would make sense for it to be a missing permission on SteamVR side. I'll try later Today and get back here with the results! 
Thanks!

> At least for me v20.4.2 as AppImage runs well on Fedora 38 (also Quest 2). I'm currently using an NVIDIA GPU, but previously my 5700XT worked fine as well.

**Comment by rafael-aba** [comment]
Sadly, the issue still persists. 

I tried uninstalling/installing SteamVR, which prompted me the to approve the permission dialog you mentioned. 
Closed, opened ALVR, launched SteamVR, connected, streamed to headset, but again I get stuck on the same scenario of the game not getting streamed to the headset (while steamVR is).

**Comment by rafael-aba** [comment]
Found a fix. 

Haven't tried for all games yet, but for beatsaber it worked after I downgraded to version 1.31.1.

**Comment by clutwo** [comment]
I have the same problem.  Gave steam superuser access, no visible errors anywhere, SteamVR streams to quest but game never appears on quest. Did you ever get this fixed?

**Comment by Meister1593** [comment]
> I have the same problem. Gave steam superuser access, no visible errors anywhere, SteamVR streams to quest but game never appears on quest. Did you ever get this fixed?

What game? If it's openxr game like beat saber, make sure you set openxr runtime in steamvr settings
