### ISSUE TITLE
Linux needs to be First Party

### ISSUE THREAD

**Issue by peq42** [alvr-org/ALVR#1854]
This software is used mostly by Linux users trying to get their quest 2 and other headsets to connect to their PC, the fact that Linux support is in beta cannot be. It should be a first party.

For Windows and MacOS, people will always default to Virtual Desktop or Oculus' air, as they've much easier installation and/or are the default options. Don't compete with them, its a waste of time

**Comment by Vixea** [comment]
Ask Valve to support the required APIs 
🤷‍♂️

**Comment by peq42** [comment]
> Ask Valve to support the required APIs 🤷‍♂️ It's really the only thing missing(other than audio)

well the audio has been missing for a while. Looking through google, thats been an issue for at least a year

**Comment by Vixea** [comment]
Audio can be done using scripts and there has been some work done for it

**Comment by zarik5** [comment]
I'm the main maintainer. I work on ALVR mainly as my day job and we use Windows. Everything else is nice but a bonus.

As Vixea said, the main obstacle is SteamVR literally not supporting Linux direct mode drivers, and we have to rely on a imperfect hack. As for audio, there are people working on it, albeit with time availability issues.

**Comment by ShalokShalom** [comment]
Did we raise an issue about that on the SteamVR for Linux page?
Do they still develop that? As the repo seems unmaintained for years. Did they move it?

**Comment by Vixea** [comment]
It's just an issue repository doesn't really need to be maintained, and yes they know about it no issue needed other than maybe to show it's importance to users, it's not a priority for them

**Comment by ShalokShalom** [comment]
And did we raise an issue about the direct mode drivers?

**Comment by Vixea** [comment]
No one yet I don't really care to anyway

**Comment by Vixea** [comment]
Here's the issue
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/409

**Comment by peq42** [comment]
a new major version of steamVR dropped, seems to have fixed at least a couple of issues with Linux.

Does it change anything for this project?

**Comment by Vixea** [comment]
Nope it's completely on Valve's side other than the library bits but also half Valve's problem as it's completely broken on native
