### ISSUE TITLE
ALVR dashboard won’t open (3050 Ti/amd cpu)

### ISSUE THREAD

**Issue by AlexASDP** [alvr-org/ALVR#1855]
## Description
  the problem is that ALVR doesn’t work since the dashboard never launches it

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Ryzen 5 5600H (but has the performance of a better chip for some reason)

**GPU**: 3050 Ti (Laptop)

**GPU Driver Version**: (latest, I updated it yesterday

**Audio**: on board audio

### Installation
**ALVR Version**: 20.4.2

**ALVR Settings File**: don’t know how to get it

**SteamVR Version**: latest 

**Install Type**:
- [this ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): windows 10 22H2

**Comment by zarik5** [comment]
This is fixed in the nightly version

**Comment by AlexASDP** [comment]
Tested it and worked fine thanks now I can play pc vr on the go
