### ISSUE TITLE
[Suggestions] Support for OpenXR Toolkit to reduce performance requirements

### ISSUE THREAD

**Issue by NONAME-2121237** [alvr-org/ALVR#1856]
Can it be paired with OpenXR Toolkit to bypass Steam VR startup applications so that reduce CPU overhead during runtime? This is very important for my laptop, please

**Comment by zarik5** [comment]
I'm not sure why it shouldn't work. it seems OpenXR Toolkit acts between the application and the VR runtime.

**Comment by zarik5** [comment]
At work, we are successfully using [vrperfkit](https://github.com/fholger/vrperfkit).

**Comment by NONAME-2121237** [comment]
In fact, when I use OpenComposite, I can remove the steam VR startup, but alvr cannot capture the output and keeps asking me to start the steam VR

**Comment by zarik5** [comment]
If you are using OpenComposite, you can just use vrperfkit to skip OpenXR at all.

**Comment by NONAME-2121237** [comment]
I am using a Pico device and currently have no means to connect the screen to my device. Due to the special version system, I am unable to purchase VD

**Comment by NONAME-2121237** [comment]
So I hope AlVR can provide me with the possibility to abandon Steam VR, but the current experience is also excellent. Thank you for your contribution
