### ISSUE TITLE
Which model of smartphones are supported?

### ISSUE THREAD

**Issue by zdyang** [alvr-org/ALVR#1867]
Hello developers. I noticed in the readme page that ALVR now supports certain smartphones (with Monado). I would like to inquire about the specific models of smartphones that have been tested and are expected to work. Could you please provide this information?

**Comment by Vixea** [comment]
Probably anything other than Samsung, as long as it's within reason of course

**Comment by zarik5** [comment]
Maybe @ShootingKing-AM can give more info.

**Comment by ShootingKing-AM** [comment]
Monado is experimental, with no testing on development side.
PhoneVR client is much more stable, and much more tested. (https://github.com/PhoneVR-Developers/PhoneVR) use PhoneVR apk client with ALVR server (Instructions, the exact version of ALVR Server supported by PhoneVR is mentioned in PhoneVR's readme)

All Smartphone versions of Android > 8.0 are supported by PhoneVR. Issue is, PhoneVR lacks testing resources right now, for general android support we need to have many physical phones (atleast in order of Android version v9, v10, v11, v12, v13) which is absent with PhoneVR devs right now.

**Comment by zdyang** [comment]
Thank you for the reply. I will give PhoneVR a try.

Recently, I tested ALVR with a low-end Android phone (Redmi 10 Pro, Android 13, no build-in VR support) and shared my experience here. Unfortunately, this phone didn't work well in two aspects.

Firstly, the rendering process seemed to be problematic as it didn't display the correct scene. However, the streaming itself seemed to work fine (I discovered this from the Windows Task Manager).

Secondly, the performance was limited, which was expected considering the phone's capabilities. It appeared that the phone couldn't match the refresh rate (60Hz), resulting in stale frames in the buffer.

Thank you once again for your assistance. I will now close this issue.
