### ISSUE TITLE
Registered Steam Drivers are Cleared when using Restart SteamVR/launch SteamVR button

### ISSUE THREAD

**Issue by TheRealRanmaKei** [alvr-org/ALVR#1871]
## Description
When drivers are registered for SteamVR, (ALVR, Haritora). Restarting SteamVR using the "Restart SteamVR" appears to remove the other driver.

## General Troubleshooting
```
1) Register ALVR driver
2) Register Haritora driver
3) Launch SteamVR from ALVR (Removes the haritora driver on startup)

```
```
1) Register Haritora driver
2) Register ALVR driver
3) Launch SteamVR from HaritoraConfigurator (Removes the ALVR driver on startup)

```
```
1) Launch ALVR
2) Install Haritora driver
3) Let SteamVR start
4) Steam is running haritora driver
5) ALVR dashboard is still open and showing SteamVR as not running
6) Register ALVR driver
7) Restart SteamVR (Both drivers appear to be running and working) Sometimes it crashes on startup, but once running its stable.

```
### Hardware
**CPU**: AMD Ryzen 9 5900X 12-core processor

**GPU**: AMD Radeon RX 6600

**GPU Driver Version**: 23.9.3

**Audio**: VoiceMeeter & Steinberg UR44C

### Installation
**ALVR Version**: 20.4.3

**ALVR Settings File**:

**SteamVR Version**: 1.27.5

**Install Type**:
- [x] Packaged (`MSI)
- [x] Portable (`APK`)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

Windows 11 Enterprise 22H2
22621.2428

**Comment by zarik5** [comment]
If you want to use ALVR with external drivers, you need to set "Driver launch action" to "Unregister ALVR at shutdown". This will register/unregister the ALVR driver without touching other drivers.
