### ISSUE TITLE
Linux Desktop

### ISSUE THREAD

**Issue by ShalokShalom** [alvr-org/ALVR#1872]
Hi :)

I like to use ALVR for programming, and just casually use my Linux desktop. 
The README speaks about games only. 

Is this its main purpose, or does literally only SteamVR work?

Can I launch casual applications like Kate as well?
Thanks

**Comment by Vixea** [comment]
Are you asking like for ALVR to stream your desktop to your VR headset?

**Comment by Vixea** [comment]
If that's the case no-ish on windows we rely on SteamVR's desktop view to view the desktop on Linux that only works by using x11 and passing flags to Steam. I don't think anyone has any plans to integrate such functionality into ALVR. ALVR is for streaming PC VR apps not desktop apps so we rely on outside apps for that. Please look at wlxoverlay.

**Comment by galister** [comment]
@ShalokShalom 
You might want to check out these projects;

StardustXR allows to launch windows in a separate desktop env that lives entirely in VR. Works with Monado / WiVRn (not ALVR compatible as of now)
https://stardustxr.org/

WlxOverlay mirrors your existing desktop into VR. Works with SteamVR / ALVR.
https://github.com/galister/WlxOverlay

**Comment by ShalokShalom** [comment]
Thanks a lot

**Comment by ShalokShalom** [comment]
In case somebody else finds this helpful, there is another such project:
https://github.com/SimulaVR/Simula

I was considering ALVR more as a driver for the headset, and I assume this has to be done completely by Monado. 

Thanks
