### ISSUE TITLE
PICO 4 Quality Linux

### ISSUE THREAD

**Issue by kst21** [alvr-org/ALVR#1873]
Can someone tell me settings to improve the quality on Linux with PICO4?
I tried to use this https://github.com/alvr-org/ALVR/wiki/ALVR-in-distrobox. Yep, everything works quickly and clearly,but the quality is poor.
P.S. Maybe not for PICO4. Any of your settings with good quality

**Comment by thackel** [comment]
I am using ALVR with a Pico4 and Linux.
For my personal taste the quality is OK, using only the (appimage) default values. I changed recently from WIFI to wired connection, which made the overall result more stable.

I would need to know how you measure "good quality" then I could compare....

**Comment by kst21** [comment]
> I am using ALVR with a Pico4 and Linux. For my personal taste the quality is OK, using only the (appimage) default values. I changed recently from WIFI to wired connection, which made the overall result more stable.
> 
> I would need to know how you measure "good quality" then I could compare....

For example, with same settings or default settings i have very good quality on Windows ALVR.
The main problems are textures twitching, poor texture quality and the whole scene looks like I'm playing without antialising.
I have already set the "quality/or high quality" in all settings and tried all presets.

**Comment by Meister1593** [comment]
What gpu do you have?

**Comment by kst21** [comment]
> What gpu do you have?

Nvidia 3060ti

**Comment by Meister1593** [comment]
> > What gpu do you have?
> 
> Nvidia 3060ti

Can you check cpu usage while it is streaming?
Just in case it is using software encoding instead of nvenc.

**Comment by kst21** [comment]
> > > What gpu do you have?
> > 
> > 
> > Nvidia 3060ti
> 
> Can you check cpu usage while it is streaming? Just in case it is using software encoding instead of nvenc.

Integrated graphics processor is turned off in BIOS and software encoding turned off in ALVR settings

**Comment by Swinec** [comment]
> Integrated graphics processor is turned off in BIOS and software encoding turned off in ALVR settings
Buuuut what in  ALVR logs?
IT's MUST me like that:
**using VAAPI encoder**
Or some else.
May be u GPU+software don't compatibility whith resolution that u set.
And finally at the end, router and lags. More than 200Mbs bitrate is pointless. What router u use?

**Comment by Meister1593** [comment]
Disabling software encoding wouldn't disable it in case of fallback from everything else to it (so if everything fails, it will fallback to it)
And more than 200 mbps being pointless is highly dependent on encoder
HEVC - probably yes, most likely because xr2 g1 doesnt really perform well with it (only up to the point), 
h264 - definitely not, higher bitrate will help a ton on more complex scenes to not make a washed image because of small details.
