### ISSUE TITLE
My antivirus (my antivirus is trend micro maximum security) said it tried to encrypt my files 

### ISSUE THREAD

**Issue by Experiment9030** [alvr-org/ALVR#1876]
My windows version is windows 11 22h2

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Meister1593** [comment]
Im not sure who flagged it, or for what reason, but at best i think what it does is write 1-2 files (openvr config in appdata to register itself, session json) on windows. 
Otherwise it's pretty self-contained.

**Comment by Experiment9030** [comment]
Ok thank you i will click trust

**Comment by zarik5** [comment]
Please double check you downloaded ALVR from our Github organization and not from other Github repositories or random links.
