### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by ghpsk** [alvr-org/ALVR#1880]
Games Affected: All

## Description
In an IPv6-only network, the ALVR headset client cannot connect to the streamer.
This happens when following instructions for both TCP forwarding via ADB and normal wireless operation.

Regression? Not that I'm aware of

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Devuan Daedalus, running Linux 6.1.0-13-amd64

### Hardware
https://linux-hardware.org/?probe=21e7b53022

### Installation
**ALVR Version**:
v20.4.3

**ALVR Settings File**:
https://0x0.st/HyUe.json

**SteamVR Version**:
Build No. 12525421

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** 
Devuan GNU/Linux 5 (daedalus)

Please add IPv6 Support to this program if possible.

**Comment by Vixea** [comment]
Why not just re-enable ipv4 in your router?

**Comment by ghpsk** [comment]
IPv6 is the future of the internet.
IPv4 is more than deprecated - ARIN ran out of IPv4 addresses in 2015, and RIPE ran out in 2019. We were supposed to all start switching to IPv6 around 8 years ago, but some programs still use IPv4.

This is essentially a feature request. I *could* put my headset into hotspot mode and connect to it with IPv4, but just because ALVR is compatible with IPv4 doesn't mean it needs to be incompatible with IPv6, and that's why I'm making this issue.

I don't think I should have to enable IPv4 for my programs to work, so I'll make an issue first before I do.

**Comment by ghpsk** [comment]
So I've been looking into the code a bit, and I can see that both Rust's std::net
https://doc.rust-lang.org/std/net/index.html
and the crate
https://docs.rs/local-ip-address/latest/local_ip_address/
being used to handle IP addresses support IPv6.

I'm going to see if I can make a fork that can handle IPv6 from just
IpAddr::V4 -> IpAddr::V6
Ipv4Addr -> Ipv6Addr
local_ip -> local_ipv6

It's a bit naive, but I haven't really ever touched Rust code before.
If that works without a hitch I'll just use that for my own purposes until handling exists upstream for both.
If not, I'll work backward from there.

**Comment by xytovl** [comment]
Most things should work, but client discovery should be modified: in https://github.com/alvr-org/ALVR/blob/a42f673c75017afde05358dfaa073315735f05ea/alvr/client_core/src/sockets.rs#L25 we use IPV4 broadcast.
This does not exist anymore for IPv6.

The closest you can have is multicast, and you need to register on the server to receive it.

**Comment by ghpsk** [comment]
> Make a PR if you can, but please don't replace ipv4 support.

Wouldn't think of it. Just going to try some hacks for my needs. Upstream should have a handler if I make a working hack for IPv6.



> Most things should work, but client discovery should be modified: in
> 
> https://github.com/alvr-org/ALVR/blob/a42f673c75017afde05358dfaa073315735f05ea/alvr/client_core/src/sockets.rs#L25
> 
> we use IPV4 broadcast.
> This does not exist anymore for IPv6.
> The closest you can have is multicast, and you need to register on the server to receive it.

I'll look into IPv6 networking and try to find a solution.

**Comment by zarik5** [comment]
> The closest you can have is multicast, and you need to register on the server to receive it.

This is actually something I was thinking about when using multicast for another project at work. If this is what it takes to support IPv6 then I might work on it relatively soon. Since this is a breaking change for the client-server protocol, I think we should wait for the v21 stable release.

**Comment by zarik5** [comment]
#1888

**Comment by gdemontalivet** [comment]
Hi, I second this request, I am trying to connect my quest 2 to a r cloud pc over the internet, and even after switching off all the firewalls I couldn’t connect to my headset, and realised this is because my local modem router is on ipv6, and cannot be forced to ipv4… would be great to have this working
