### ISSUE TITLE
Can I integrate aar or jar

### ISSUE THREAD

**Issue by xujunjie12345** [alvr-org/ALVR#1884]
Currently, the code is entirely built using cargo, but my lib is aar. Can I integrate and use it? txs

**Comment by zarik5** [comment]
No, the client does not support aar archives. If the aar contains only a native shared library, unzip it and include it using build.rs. If it contains any Java bytecode, it will not work with ALVR.

**Comment by xujunjie12345** [comment]
> No, the client does not support aar archives. If the aar contains only a native shared library, unzip it and include it using build.rs. If it contains any Java bytecode, it will not work with ALVR.
 you mean that we can only reflect the system's java code, but us can't use your own java libraries？

**Comment by zarik5** [comment]
> you mean that we can only reflect the system's java code, but us can't use your own java libraries？

Exactly. You can access built-in android java objects/methods using JNI (with some caveats) but you can't add third party java libraries.

**Comment by xujunjie12345** [comment]
I see. Thank you very much.

**Comment by xujunjie12345** [comment]
close
