### ISSUE TITLE
How do I request external space permissions for my app and get a valid storage path?

### ISSUE THREAD

**Issue by Hope10086** [alvr-org/ALVR#1887]
I tried to save the OpenGL ES rendering results as png images, using a third-party library: [stb_image_write_rust](https://github.com/StbRust/stb_image_write_rust).
I defined the new function in `opengl.rs`:
```
#[no_mangle]
pub unsafe extern "C" fn png_create(filename: *const c_char ,width:i32 ,height:i32 ,comps: i32,data: *const u8){
    let filename_cstr = CStr::from_ptr(filename);
    let filename_str = filename_cstr.to_str().expect("Invalid filename");
    let c_full_path = CString::new(filename_str).expect("CString conversion failed");
    let mut writer = ImageWriter::new("output.png");
    writer.write_png(width, height, comps, data);
}
```

And It will be called from graphics.cpp  after   ` GL(glDrawElements(GL_TRIANGLES, renderer->Panel.IndexCount, GL_UNSIGNED_SHORT, NULL));`  

But  it showed this is a  read-only system when executing the file creation by
```
impl ImageWriter {
    pub fn new(path: &str) -> ImageWriter {
        ImageWriter {
            file: File::create(path).expect("could not create file"),
        }
    }
```
`Logcat:   panicked at 'could not create file: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }',C:\Users\Zhang\.cargo\git\checkouts\stb_image_write_rust-e6019e676b2d2614\c748c62\stb_image_write_rust\src\ImageWriter.rs:12:38`

So what should we do in this project to request read access to the external space for the alvr-client?  
This is my [source code.](https://github.com/Hope10086/MMCALVR20.0/commit/6fa0cd66c0373b4104c2ba4266cc009c4c07982a)

 Best Wish to you.

**Comment by Hope10086** [comment]
I try to get alvr-client's  internal  storage  path in Android OS by this: in `alvr\client_core\src\platform\android.rs`
```
pub fn get_internal_storage_path() ->String
{
    let vm = vm();
    let mut env = vm.attach_current_thread().unwrap();
    let files_dir = env
        .call_method(
            unsafe { JObject::from_raw(context()) },
            "getFilesDir",
            "()Ljava/io/File;",
            &[],
        )
        .unwrap()
        .l()
        .unwrap(); // 
    let path_jstring = env
        .call_method(files_dir, "getAbsolutePath", "Ljava/lang/String;", &[])
        .unwrap()
        .l()
        .unwrap(); //
    let path_string = env.get_string((&path_jstring).into()).unwrap(); // JString  turn toString
    
    let file_path = path_string.to_string_lossy().into_owned();
    file_path
}
```

However there is a bug about call_method's "Ljava/lang/String;" :

```
/alvr.client E/[ALVR NATIVE-RUST]: What happened:
    panicked at 'called `Result::unwrap()` on an `Err` value: ParseFailed(UnexpectedParse, "Ljava/lang/String;")', alvr\client_core\src\platform\android.rs:167:10
```

**Comment by zarik5** [comment]
You need to prefix the method signature with `()` if the method has no arguments. Check the JNI docs of other examples in ALVR.

**Comment by Hope10086** [comment]
> I try to get alvr-client's internal storage path in Android OS by this: in `alvr\client_core\src\platform\android.rs`
> 
> ```
> pub fn get_internal_storage_path() ->String
> {
>     let vm = vm();
>     let mut env = vm.attach_current_thread().unwrap();
>     let files_dir = env
>         .call_method(
>             unsafe { JObject::from_raw(context()) },
>             "getFilesDir",
>             "()Ljava/io/File;",
>             &[],
>         )
>         .unwrap()
>         .l()
>         .unwrap(); // 
>     let path_jstring = env
>         .call_method(files_dir, "getAbsolutePath", "Ljava/lang/String;", &[])
>         .unwrap()
>         .l()
>         .unwrap(); //
>     let path_string = env.get_string((&path_jstring).into()).unwrap(); // JString  turn toString
>     
>     let file_path = path_string.to_string_lossy().into_owned();
>     file_path
> }
> ```
> 
> However there is a bug about call_method's "Ljava/lang/String;" :
> 
> ```
> /alvr.client E/[ALVR NATIVE-RUST]: What happened:
>     panicked at 'called `Result::unwrap()` on an `Err` value: ParseFailed(UnexpectedParse, "Ljava/lang/String;")', alvr\client_core\src\platform\android.rs:167:10
> ```Missing `（）`    "（）Ljava/lang/String;"

**Comment by Hope10086** [comment]
> You need to prefix the method signature with `()` if the method has no arguments. Check the JNI docs of other examples in ALVR.

Yes, I I fixed this error yesterday though I forgot to share it.Issues with paths and access permissions have been resolved and I am now checking that the file was written correctly.

**Comment by Hope10086** [comment]
```
#[no_mangle]
pub unsafe extern "C" fn png_create(filename: *const c_char ,width:i32 ,height:i32 ,comps: i32,data: *const u8){
    let filename_str = CStr::from_ptr(filename)
                                    .to_str()
                                    .expect("Invalid filename");
    let c_full_path = CString::new(filename_str).expect("CString conversion failed");
    let dir_path =  platform::get_internal_storage_path();

    let full_path = format!("{}/{}", &*dir_path, c_full_path.to_str().expect("CString to_str failed"));
    info!("[ALVR Capture] path:{}", &*full_path);
    //let mut writer = ImageWriter::new(&*full_path);
    // save png by using  image "0.24.6"
    let pngbuffer :&[u8] = unsafe {
        slice::from_raw_parts(data, (width *height *4).try_into().unwrap())};
    let img = ImageBuffer::<Rgba<u8>, _>::from_raw(width as u32, height as u32, pngbuffer).unwrap();
    let save_result  = img.save(&*full_path);
    match save_result {
        Ok(_) => {
            // Image saved successfully
            info!("[ALVR Capture] Image saved successfully.");
        },
        Err(error) => {
            // Failed to save the image
            eprintln!("[ALVR Capture] Failed to save the image: {}", error);
        },
    }
}
```


Save PN flie to  storage path  by image "0.24.6"'s ImageBuffer
