### ISSUE TITLE
Switch from broadcast to multicast discovery

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#1888]
This is needed for IPv6 support. Since this is a breaking change, merge close to the v21 stable release.

**Comment by The-personified-devil** [comment]
This has been resolved by the switch to mdns, right?

**Comment by zarik5** [comment]
Yes, this has been merged, and version bumped to v21.0.0-dev01

**Comment by OlehSv** [comment]
@zmerp Does it mean that I can connect from remote PC to my VR headset by ipv6?
