### ISSUE TITLE
Pico 4 - Controller velocity is wrong

### ISSUE THREAD

**Issue by iam4k33m** [alvr-org/ALVR#1889]
Bug occours in Half Life Alyx, and likely any game that uses hand velocity in a similar way for throwing objects.

## Description

Objects are thrown with a 90 degree offset on velocity, which changes direction with different controller emulation selections

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:Intel I7 4770k

**GPU**:nVidia GeForce GTX 1660ti

**GPU Driver Version**:536.23

**Audio**:Voicemeeter banana

### Installation
**ALVR Version**: 20.43

**ALVR Settings File**: 
Attatched
[session.json](https://github.com/alvr-org/ALVR/files/13261040/session.json)

**SteamVR Version**:Beta 2.11

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10

**Comment by thackel** [comment]
I can confirm that right now in Alyx all grenades are thrown 90 degrees to the right.

But it worked somehow before in Alyx and it is still working as expected in H3VR. So i guess its more a Alyx and/or SteamVR problem than a general Pico4 or ALVR one.

ALVR 20.5.0

**Comment by iam4k33m** [comment]
I suspect it could be an issue with Pico OpenXR. Some unity standalone
games experience this issue too.

**Comment by thackel** [comment]
I restarted ALVR and SteamVR and could play Alyx again without this issue. When I encounter it again, I will preserve the log.
There was no update of any software in between.

**Comment by iam4k33m** [comment]
> I restarted ALVR and SteamVR and could play Alyx again without this issue. When I encounter it again, I will preserve the log. There was no update of any software in between.

In my experience, Half life alyx level loading leads to wrong throw direction.

**Comment by Vixea** [comment]
Then this just sounds like an Alyx bug then.
