### ISSUE TITLE
Controller disconnect and reconnect causes numerous issues

### ISSUE THREAD

**Issue by BirdyBlaze** [alvr-org/ALVR#1892]
## Description

When my controllers disconnect, and then try to reconnect them to the headset, steamvr will consistently take screenshots, and all the buttons will be pressed and held in the software, which can make software like bigscreen vr, and vrchat, to act improperly. And in vrchat's problem, it causes safe mode to be turned on, which can be annoying trying to fix.

Furthermore, the steamvr dashboard will no longer work properly, and the pointer light for the controllers will phase through the dashboard, causing me to need to close the dashboard and reopen it quickly in order for pass through to not happen.

On some occasions my computer will entirely freeze and lock up, causing me to need to do ctrl-alt-delete just to regain control.

For the first issue, it seems that closing ALVR from the oculus menu in the headset and reopening it fixes it.
Second issue it seems that a whole restart of steamvr is needed to fix it

this does not seem to happen with oculus airlink. it also didn't happen when steamvr was in 1.X so it may just be a bug that happened with 2.X being released.

## General Troubleshooting
- [✓ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [✓ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: AMD Ryzen 5 2600X

**GPU**: Radeon RX 580

**GPU Driver Version**: AMD radeon 23.10.2

**Audio**:AMD internal High defenition(unsure where to find this)

### Installation
**ALVR Version**: 20.4.3

**ALVR Settings File**:(do not know where to get)

**SteamVR Version**: 2.1.1

**Install Type**:
- [✓ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): 22H2

**Comment by zarik5** [comment]
You can disable hand tracking gestures in the settings under "Controllers".

**Comment by Mr-Zero88** [comment]
I have the exact same problem.
Every time I switch from Hand tracking to Controllers every button gets pressed, and I need to press every single one to release them, otherwise a lot of things break like the Dashboard as already described.
I can't just simply disable hand tracking gestures, since I am actively using them.
This is a really annoying bug which need attention.
