### ISSUE TITLE
ALVR in distrobox: "Cannot find container arch-alvr" after reboot

### ISSUE THREAD

**Issue by simoschip2000** [alvr-org/ALVR#1907]
## Description

I installed ALVR using the [ALVR in distrobox guide](https://github.com/alvr-org/ALVR/wiki/ALVR-in-distrobox) sucessfully.
I included the setup.log anyway. [setup.log](https://github.com/alvr-org/ALVR/files/13400334/setup.log)

I could execute the "start-alvr.sh" after the installation sucessfully, but after I rebooted it did not work anymore.

Running the "start-alvr.sh" after rebooting gives me the following output:
` : Using default installation with default name
localuser:simon being added to access control list
/home/simon/.local/bin/podman
/home/simon/.local/bin/distrobox
 : Using system podman and distrobox
 : Starting up Steam
 : Starting up ALVR
ERRO[0000] invalid internal status, try resetting the pause process with "/home/simon/.local/share/podman-static/bin/podman system migrate": could not find any running process: no such process 
Cannot find container arch-alvr
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:38? [Y/n]: 
`
I did not enter "Y".

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[https://linux-hardware.org/?probe=5e4c68c7cd](https://linux-hardware.org/?probe=5e4c68c7cd)

### Installation
**ALVR Version**:
Latest? Not sure what  [ALVR in distrobox guide](https://github.com/alvr-org/ALVR/wiki/ALVR-in-distrobox) is using.

**ALVR Settings File**:
[session.json](https://github.com/alvr-org/ALVR/files/13400339/session.json)

**SteamVR Version**:
Latest.

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

Installed with  [ALVR in distrobox guide](https://github.com/alvr-org/ALVR/wiki/ALVR-in-distrobox).

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Linux Mint 21.2

**Thanks in advance! :)**

**Comment by Meister1593** [comment]
i would recommend doing uninstall script from distrobox, checking if `~/.local/bin/` path is clear from distrobox, podman binaries and installing again.
Sometimes podman also likes to fluke because of some limitations on distributions around process count, so restarting might help, but in your case something must have gone wrong, i'm quite unsure if that's related to this issue..
Do the thing above and post setup.log again.

**Comment by 4evrplan** [comment]
I have the same issue. I've already uninstalled and reinstalled it once. But @Meister1593, what do you mean by checking for those binaries? If they're there, can we just delete them, or do we have to uninstall distrobox with apt-get remove? Sorry, I'm not great with Linux.

I went a step further than simoschip2000 and said "y" to create the arch-alvr container, because I assumed that was normal. Now when I run start-alvr.sh, I get:

```
 : Using default installation with default name
localuser:redacted being added to access control list
 : Starting up Steam
 : Starting up ALVR
Error: crun: executable file `alvr_dashboard` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

**Comment by Meister1593** [comment]
> I have the same issue. I've already uninstalled and reinstalled it once. But @Meister1593, what do you mean by checking for those binaries? If they're there, can we just delete them, or do we have to uninstall distrobox with apt-get remove? Sorry, I'm not great with Linux.
> 
> I went a step further than simoschip2000 and said "y" to create the arch-alvr container, because I assumed that was normal. Now when I run start-alvr.sh, I get:
> 
> ```
>  : Using default installation with default name
> localuser:redacted being added to access control list
>  : Starting up Steam
>  : Starting up ALVR
> Error: crun: executable file `alvr_dashboard` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
> ```

No it wasn't normal, saying y probably create undefined behaviour with containers and you probably need to reinstall container unfortunately...
I would recommend doing `uninstall.sh` and trying out my another branch https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/tree/lilipod
It doesn't use podman (uses minimal lilipod instead) and friend has been using it for past month, seems like it works good.

**Comment by 4evrplan** [comment]
> No it wasn't normal, saying y probably creates undefined behavior with containers and you probably need to reinstall container unfortunately... I would recommend doing `uninstall.sh` and trying out my another branch https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/tree/lilipod It doesn't use podman (uses minimal lilipod instead) and friend has been using it for past month, seems like it works good.

I did the uninstall and downloaded the lilipod version. The install script said it was successful, but when I run start-alvr.sh, I get this:
```
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ ./start-alvr.sh
 : Using default installation with default name
localuser:redacted being added to access control list
 : Starting up Steam
 : Starting up ALVR
failed to find dependency getsubids, can't recover.
2023/12/16 15:21:47 exec: "getsubids": executable file not found in $PATH
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:38? [Y/n]: n
Ok. For creating it, run this command:
	distrobox create <name-of-container> --image <remote>/<docker>:<tag>

```

**Comment by Meister1593** [comment]
> > No it wasn't normal, saying y probably creates undefined behavior with containers and you probably need to reinstall container unfortunately... I would recommend doing `uninstall.sh` and trying out my another branch https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/tree/lilipod It doesn't use podman (uses minimal lilipod instead) and friend has been using it for past month, seems like it works good.
> 
> I did the uninstall and downloaded the lilipod version. The install script said it was successful, but when I run start-alvr.sh, I get this:
> 
> ```
> redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ ./start-alvr.sh
>  : Using default installation with default name
> localuser:redacted being added to access control list
>  : Starting up Steam
>  : Starting up ALVR
> failed to find dependency getsubids, can't recover.
> 2023/12/16 15:21:47 exec: "getsubids": executable file not found in $PATH
> Create it now, out of image registry.fedoraproject.org/fedora-toolbox:38? [Y/n]: n
> Ok. For creating it, run this command:
> 	distrobox create <name-of-container> --image <remote>/<docker>:<tag>
> ```

Please follow dependencies installation on this page https://github.com/alvr-org/ALVR/wiki/ALVR-in-distrobox#installing-alvr-distrobox (more specifically, you're probably missing uidmap, or depending on distro something else)

**Comment by 4evrplan** [comment]
I'm not 100% sure, but I believe this shows all of those commands are installed on my system:
```
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ curl
curl: try 'curl --help' or 'curl --manual' for more information
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ xhost
access control enabled, only authorized clients can connect
SI:localuser:redacted
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ sed
Usage: sed [OPTION]... {script-only-if-no-other-script} [input-file]...

  -n, --quiet, --silent
                 suppress automatic printing of pattern space
      --debug
                 annotate program execution
  -e script, --expression=script
                 add the script to the commands to be executed
  -f script-file, --file=script-file
                 add the contents of script-file to the commands to be executed
  --follow-symlinks
                 follow symlinks when processing in place
  -i[SUFFIX], --in-place[=SUFFIX]
                 edit files in place (makes backup if SUFFIX supplied)
  -l N, --line-length=N
                 specify the desired line-wrap length for the `l' command
  --posix
                 disable all GNU extensions.
  -E, -r, --regexp-extended
                 use extended regular expressions in the script
                 (for portability use POSIX -E).
  -s, --separate
                 consider files as separate rather than as a single,
                 continuous long stream.
      --sandbox
                 operate in sandbox mode (disable e/r/w commands).
  -u, --unbuffered
                 load minimal amounts of data from the input files and flush
                 the output buffers more often
  -z, --null-data
                 separate lines by NUL characters
      --help     display this help and exit
      --version  output version information and exit

If no -e, --expression, -f, or --file option is given, then the first
non-option argument is taken as the sed script to interpret.  All
remaining arguments are names of input files; if no input files are
specified, then the standard input is read.

GNU sed home page: <https://www.gnu.org/software/sed/>.
General help using GNU software: <https://www.gnu.org/gethelp/>.
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ pipewire
[E][18934.670092] mod.protocol-native | [module-protocol-:  660 lock_socket()] server 0x55680126bc60: unable to lock lockfile '/run/user/1000/pipewire-0.lock': Resource temporarily unavailable (maybe another daemon is running)
[E][18934.670213] pw.conf      | [          conf.c:  560 load_module()] 0x556801251130: could not load mandatory module "libpipewire-module-protocol-native": Resource temporarily unavailable
[E][18934.670273] default      | [      pipewire.c:  123 main()] failed to create context: Resource temporarily unavailable
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
redacted@REDACTED:~/Downloads/ALVR-Distrobox-Linux-Guide-lilipod$ newgidmap
usage: newgidmap <pid> <gid> <lowergid> <count> [ <gid> <lowergid> <count> ] ... 

```

**Comment by Meister1593** [comment]
what about `getsubids` ?

**Comment by 4evrplan** [comment]
"command not found". What package is that a part of? I didn't see it listed in the instructions.

**Comment by Meister1593** [comment]
Yes it seems like it would be a new package... I'm not familiar with your distribution, can you share your `setup.log` from folder? It contains distribution info and i will check just to make sure if installation was okay

**Comment by 4evrplan** [comment]
It's just Ubuntu 22.04. I've attached a copy of the log file.

[setup (copy).log](https://github.com/alvr-org/ALVR/files/13694207/setup.copy.log)

**Comment by Meister1593** [comment]
It seems like installation did not even began working... do you have switching graphics by any chance?
If it's intel + nvidia laptop, i would highly advise using optimus manager and switch to just nvidia

**Comment by 4evrplan** [comment]
I _do_ have an Intel iGPU and a discreet Nvidia GPU. I'll see if I can figure out Optimus Manager.

**Comment by 4evrplan** [comment]
> It seems like installation did not even began working... do you have switching graphics by any chance? If it's intel + nvidia laptop, i would highly advise using optimus manager and switch to just nvidia

The documentation on the optimus-manager GitHub page says "Only Archlinux and Archlinux-based distributions (such as Manjaro) are supported for now", but I believe Ubuntu is Debian based.

**Comment by simoschip2000** [comment]
Hi,
just fyi: I switched to flatpak Steam and flatpak ALVR and since the release of Steam VR 2.18 it works for me. (Steam VR 2.15 gave me error 500 in Steam VR).

**Comment by Meister1593** [comment]
> > It seems like installation did not even began working... do you have switching graphics by any chance? If it's intel + nvidia laptop, i would highly advise using optimus manager and switch to just nvidia
> 
> The documentation on the optimus-manager GitHub page says "Only Archlinux and Archlinux-based distributions (such as Manjaro) are supported for now", but I believe Ubuntu is Debian based.
> 
> EDIT: My distro did come with nvidia-prime, so I did `sudo prime-select nvidia` and rebooted, uninstalled and attempted to reinstall ALVR (the lilipod version). It stopped in that same place with the "intel is not supported yet" message. I tried the other fork, the distrobox version, and got the same thing.
> 
> I managed to get the AppImage version to run, but it won't connect with the client.

i think scripts need modifying to actually work on dual graphics (to skip first gpu being detected)



> Hi, just fyi: I switched to flatpak Steam and flatpak ALVR and since the release of Steam VR 2.18 it works for me. (Steam VR 2.15 gave me error 500 in Steam VR).

that unfortunately is only gonna work on single gpu amd graphics, nvidia is unsupported with flatpak alvr
