### ISSUE TITLE
Inquiry about resolution

### ISSUE THREAD

**Issue by tyrionchen** [alvr-org/ALVR#1909]
Hello, I have a question regarding the resolution settings in the ALVR Dashboard. 
I noticed that there are six different resolution options available, and selecting each option changes the configuration for "Transcoding view resolution" and "Emulated headset view resolution."

I was wondering if ALVR takes into consideration the resolution of the HMD screen when choosing different resolution options. I am concerned that if the resolution ratio between the HMD screen and the "Transcoding view resolution" and "Emulated headset view resolution" configurations is inconsistent, it might result in a stretched image on the HMD. Could you please clarify if this is a potential issue?

Additionally, while going through the "https://github.com/alvr-org/ALVR/wiki/Settings-tutorial" link, I came across the recommendation to use the original resolution of the HMD for obtaining a clear image. In light of this, I was curious why the default setting does not directly configure the resolution on the ALVR server for the HMD.

Thank you for your attention to my inquiry, and I appreciate any insights you can provide on this matter.

**Comment by zarik5** [comment]
"Transcoding view resolution" and "Emulated headset view resolution" have two modes: Absolute or Scale. using Absolute you can explicitly set width and height, where if this doesn't match the texture ratio used by the client, pixels will not be square; height can be set to Default, in which case the client aspect ratio will be used to calculate it. Scale mode instead uses the preferred client resolution as base and you can scale up or down from it. This resolution varies from vendor to vendor and usually it's very conservative, 1.0 will result in a blurry image. I believe information in the wiki link you posted in not accurate.

**Comment by tyrionchen** [comment]
Thank you very much for your response! I have another unrelated question to ALVR. I noticed on the official Meta website's Oculus Quest 2 Tech specs that the single-eye resolution for Quest 2 is listed as 1832x1920. However, why does the "recommended" resolution queried from the OpenXR API show as 1440x1584? There seems to be a slight discrepancy in the aspect ratio between these two resolutions.

**Comment by zarik5** [comment]
The aspect ratio is strongly dependent on the IPD and optics. And as I said the image is reprojected so, the image is displayed with a barrel distortion, the corners a squished. I've seen that the Quest 2 prefers extending the image a bit outside the screen too, so that the screen is better utilized. all these factors make image resolution and screen resolution (and aspect ratio) completely unrelated to each other.

**Comment by tyrionchen** [comment]
Thank you for answering my questions and helping me understand better
