### ISSUE TITLE
"sudo: pacman: command not found"

### ISSUE THREAD

**Issue by sunsetteOS** [alvr-org/ALVR#1910]
## Description
I'm trying to install ALVR but I'm running into a very odd issue during phase 4 whenever it sets up the arch distrobox.  
` : Phase 4`
`1 : Installing packages for base functionality.`
`sudo: pacman: command not found`
` : Couldn't install distrobox container first time at phase 4, please report it as an issue with attached setup.log from the directory.`

## General Troubleshooting
I followed the instructions provided to the best of my ability, but at this point the log is telling me to report the issue so here I am.

### Hardware
https://linux-hardware.org/?probe=aed5686f55

Provided below is my full setup log.

[setup.log](https://github.com/alvr-org/ALVR/files/13464298/setup.log)

**Comment by Meister1593** [comment]
Don't run script as root

**Comment by sunsetteOS** [comment]
I'm not running the command as root, I'm running it as user, but the script has a bunch of sudo commands in it.  Should I go through and remove all of them?

**Comment by Meister1593** [comment]
Where are you getting script?
Also you don't have to use neither distrobox or podman from system they are probably causing the issues
Run uninstall.sh, remove distrobox/podman from system.

**Comment by sunsetteOS** [comment]
I got the script from this Github, or at least I assumed I did.

I can't remove distrobox, I use it to boot Vesktop through an arch container.

**Comment by Meister1593** [comment]
Did you use this guide?
https://github.com/alvr-org/ALVR/wiki/Installation-guide#semi-automatic-distrobox-installation-and-guidance

But in either case, for some reason your setup uses root podman, which is HIGHLY insecure, i'm not sure what's wrong with that, it shouldn't use root by default...

**Comment by sunsetteOS** [comment]
Yeah, that's the guide I used, and that's where I got the files and the setup script.  
![image](https://github.com/alvr-org/ALVR/assets/87560073/eeb1258f-c3eb-49d0-91d0-4434b85c3609)

I'm really not sure what's going on with it either, this is all greek to me. Would it be a _bad_ idea to try going through and removing all mentions of sudo?

**Comment by Meister1593** [comment]
All sudo mentions *inside* script are only for the insides of container, it's not related to outside.

**Comment by Meister1593** [comment]
I will close this issue as it's outdated by now, but if you have any other issues with new version - open issue here:
https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues
