### ISSUE TITLE
Screen too red

### ISSUE THREAD

**Issue by loikki** [alvr-org/ALVR#1914]
Hi,

Thanks for developing this software and to support linux :)

## Description
I have been using for a while ALVR with my phone (using https://github.com/PhoneVR-Developers/PhoneVR) but I realized that the image is too red in comparison to the image on my normal screen. I disabled all my "night modes" on my phone and computer and the image is still too red. I am not sure if the issue comes from PhoneVR or ALVR but I have the feeling that it is ALVR that might be badly configured for a phone screen. Do you have any suggestion on how to improve this? From what I have seen in the settings, there is nothing for RGB color correction. 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=0338afa4db

### Installation
**ALVR Version**: 20.4.3

**ALVR Settings File**:
[session.json](https://github.com/alvr-org/ALVR/files/13529566/session.json)

**SteamVR Version**: should be 2.1.8 (build ID 12835957)

**Install Type**: Appimage

**OS Name and Version**: Manjaro

**Comment by zarik5** [comment]
Can you take a screenshot?

**Comment by zarik5** [comment]
What are your color correction settings? In the ALVR dashboard.

**Comment by loikki** [comment]
I have uploaded my settings in the previous message. You can see a summary here:

```
"brightness": 0.0,
"contrast": 0.0,
"saturation": 0.5,
"gamma": 2.0,
"sharpening": 0.0
```

The image was relatively dark so I increased gamma but otherwise everything else is the default value. I tried to play a bit with them but it was not really successful.

**Comment by zarik5** [comment]
The gamma function has a specific curve and if the image was too dark, using this gamma slider does not ensure the colors will preserve the same saturation level. You could try reducing the saturation but again the result will not be perfect. IIRC the PhoneVR maintainer removed the sRGB correction pass. For smartphones, the hardware is unknown so we don't know when to apply or not the sRGB correction, so we would need to add a setting.

**Comment by loikki** [comment]
I tried to play again with the gamma and the saturation level but it was without success. Are you planning to provide some sRGB correction options or should I check with the PhoneVR people?

**Comment by zarik5** [comment]
I had the idea to add rgb spectrum correction but it's not on the roadmap for now you can ask @ShootingKing-AM for help with PhoneVR.

**Comment by loikki** [comment]
Thanks for your help

**Comment by rodrigoaantunes** [comment]
I have the same problem
