### ISSUE TITLE
High FPS shuttering

### ISSUE THREAD

**Issue by AnimeGangV1** [alvr-org/ALVR#1920]
Hello, unfortunately I have to open an issue and I have this problem. I have 60-72 FPS but unfortunately every time there are no frame drops but actually shattering. my internet is good though. I've tried everything but it hasn't helped. Every time I go into a game via alvr and start to run there I jerk along without frame drops I ask for help I am happy to provide further information Kind regards

**Comment by Xgames123** [comment]
I had something like this.
I enabled Optimize game render latency and it fixed it
