### ISSUE TITLE
[USB] Handshake error after update 20.4.3 -> 20.5.0

### ISSUE THREAD

**Issue by phobos2077** [alvr-org/ALVR#1923]
## Description
Unable to connect as normal with the latest release. Following USB guide on the wiki.
![image](https://github.com/alvr-org/ALVR/assets/4744345/996674b6-10df-4090-8a6e-d525ba8d60c2)

Uninstalling and reinstalling v20.4.3 from installer fixed the issue.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**:
AMD Ryzen 5600X

**GPU**:
NVidia RTX2070 Super

**GPU Driver Version**:
546.29

**Audio**:

### Installation
**ALVR Version**:
20.5.0

**ALVR Settings File**:
Default settings + changes from USB guide

**SteamVR Version**:
2.1.10

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 x64 22H2 OS build 19045.3570

**Comment by zk-wz** [comment]
I have the same issue, restarting alvr and vd may be helpful sometimes.

**Comment by aureliensoria** [comment]
Hello, same issue on my side.
![image](https://github.com/alvr-org/ALVR/assets/17644179/1b093949-a269-4c41-a6f6-e9c326dc9590)

**Comment by GrigoriyPeters** [comment]
Can confirm the issue. I have the same problem on linux.

**Comment by Goodguy140** [comment]
I have the same issue on Windows 11 (Version 10.0.22631.2861), SteamVR 2.1.10.
I tried on ALVR 2.5.0 Packaged. Also tried building from source and had the same results.

**Comment by Vesek** [comment]
Same problem here, by also forwarding ports `9942` and `8082` it stopped complaining about a handshake and my headset displayed that the stream will start shortly, but then it never does.

**Comment by waltercool** [comment]
Anyone found a workaround about this? I get the same error from WiFi, including the latest nightly

**Comment by aureliensoria** [comment]
I found no workaround on my side so I downgraded to 20.4.3 to avoid the issue.

**Comment by zarik5** [comment]
Have you tried the nightly builds?

**Comment by aureliensoria** [comment]
Hello ! I updated to the nightly build and the issue seems resolved.

**Comment by phobos2077** [comment]
No connection issues in 20.6.0.

**Comment by waltercool** [comment]
It does kind-of-a system crash on HTC Vive XR.

20.4.X: Works fine
20.5.X: Handshake error
20.6.X: Headset goes black screen and nothing happens, buttons make sounds but even HTC home interface seems dead. Pressing the power button makes a restart.

So, the handshake error seem resolved, but makes HTC Vive XR to not work.

Will create  a different ticket for that case.
