### ISSUE TITLE
What should I do to add support for Chinese Simplified in the new dashboard?

### ISSUE THREAD

**Issue by qdd1402956456** [alvr-org/ALVR#1927]
I want to add support for simplified Chinese in egui, but I don’t know where to add it.

**Comment by zarik5** [comment]
The new dashboard does not support translations. In case you want to maintain your fork, you can replace the strings in `alvr/session/src/settings.rs`

**Comment by qdd1402956456** [comment]
Yes, some of them are in the displayName, and some are in the text of the UI. It seems not easy to process them uniformly.

**Comment by qdd1402956456** [comment]
> 新仪表板不支持翻译。如果您想维护您的前叉，您可以更换仪表板箱中的字符串，并设置字符串`alvr/session/src/settings.rs`

是的，有些是在displayName中，有些是在UI的文本中。想要统一处理它们似乎并不容易。

**Comment by zarik5** [comment]
I could spend some time to move the dashboard strings (except settings) to a single page in the dashboard crate.
