### ISSUE TITLE
black screen with empty recording file

### ISSUE THREAD

**Issue by christopher317** [alvr-org/ALVR#1928]
## Description

when opening ALVR, steam VR opens and is rendering fine with the VR view on the pc looking normal, but when i go to put on the headset, i get a completely black screen.
when trying to record via debug menu, the resulting file is empty.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
[hw-probe database upload](https://linux-hardware.org/?probe=72a4579df1)
note that the headset is a original meta quest. ( not a meta quest 2 or 3 )
### Installation
**ALVR Version**:
20.5 ( also tested on nightly, same issue )
**ALVR Settings File**:
[session.json](https://github.com/alvr-org/ALVR/files/13666909/session.json)
if this is the wrong file, please point me to the correct one.
**SteamVR Version**:
2.2.1 beta
**Install Type**:
Appimage

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Linux Mint 21.2 x86_64

**Comment by zggzcgy** [comment]
same. When I accidentally connected the video cable to the motherboard interface, the streaming was successful unexpectedly, but the Steam VR view was blurred and the application was working properly. 

I guess CPU was used for rendering, with a CPU usage rate of 100%. I tried to configure it according to [method](https://github.com/alvr-org/ALVR/issues/1614), Assigning rendering drivers to AMD and Nvdia drivers will prevent rendering and displaying black screens.

**SteamVR Version**: 2.2.3
**ALVR Version**: v20.5.0
**Install Type**: Appimage
**OS Name and version**: Ubuntu 23.10 (X11 and Wanyland)
[Hardware](https://linux-hardware.org/?probe=136b8b5f83)

**Comment by Vixea** [comment]
For this latest comment SteamVR 2.5 broke alvr please just use the older version
