### ISSUE TITLE
AXLR not letting me remove local ip for using loopback for wired link

### ISSUE THREAD

**Issue by BartAgterbosch** [alvr-org/ALVR#1930]
So, using the nightly version of ALXR I'm now trying to remove the initially added local ip and add the loopback to the trusted client instead, because I'm attempting to run over usb..
However for some reason there is no longer an option to remove the "old" ip, as in the auto detected ip, I can add a new one, but cannot remove the local ip, meaning it will keep connecting over wifi no matter what I do, even when I kill the wifi connection on the headset.

I'm using the ALXR nightly build of the server on windows 10 22h2
The ALXR nightly client build on the quest 3 headset
Oculus link cable
ADBForwarder

I can tell it's not connecting over usb since when I kill the wifi connection in the headset, the ALVR connection drops also.
So essentially I let it connect over wifi, add it to trusted, click configure, add the loopback address, but then there's no longer an option to remove the old address

**Comment by BartAgterbosch** [comment]
> Just go ahead and copy the hostname of your headset then remove that client. Then make sure to turn off client discorvery and then add it back manually with the ip that you want.

Hm yea that's another issue, it doesn't show that anymore in the latest ALXR nightly either, not in the server app, but also not in the client app, the client side app now just shows an all blue background with only the controllers appearing, no hostname, ip, nothing. The server side now only shows the name and ip, like "Meta Quest 3 (192.168.178.10)" for example, if you press configure it doesn't show anything other than the ip.
It doesn't mention the hostname in the session.json file either

**Comment by 0Human0** [comment]
The remove client button is still here on my end inside of the latest nightly of the ALXR server also the client side behavior you are describing is expected there's no way to get the host name from inside the headset you have to let it connect to the server over wifi first and then turn off client discovery in the settings, add your 127.0.0.1 IP, and then restart the ALXR server

> > Just go ahead and copy the hostname of your headset then remove that client. Then make sure to turn off client discorvery and then add it back manually with the ip that you want.
> 
> Hm yea that's another issue, it doesn't show that anymore in the latest ALXR nightly either, not in the server app, but also not in the client app, the client side app now just shows an all blue background with only the controllers appearing, no hostname, ip, nothing. The server side now only shows the name and ip, like "Meta Quest 3 (192.168.178.10)" for example, if you press configure it doesn't show anything other than the ip. It doesn't mention the hostname in the session.json file either
> 
> Edit: I forgot to mention, I did not grab the nightly client build from the sidequest store, but rather I grabbed the latest one from github

The remove client button is still here on my end inside of the latest nightly of the ALXR server also the client side behavior you are describing is expected there's no way to get the host name from inside the headset you have to let it connect to the server over wifi first and then turn off client discovery in the settings, add your 127.0.0.1 IP, and then restart the ALXR server

**Comment by 0Human0** [comment]
> > Just go ahead and copy the hostname of your headset then remove that client. Then make sure to turn off client discorvery and then add it back manually with the ip that you want.
> 
> Hm yea that's another issue, it doesn't show that anymore in the latest ALXR nightly either, not in the server app, but also not in the client app, the client side app now just shows an all blue background with only the controllers appearing, no hostname, ip, nothing. The server side now only shows the name and ip, like "Meta Quest 3 (192.168.178.10)" for example, if you press configure it doesn't show anything other than the ip. It doesn't mention the hostname in the session.json file either
> 
> Edit: I forgot to mention, I did not grab the nightly client build from the sidequest store, but rather I grabbed the latest one from github

The remove client button is still here on my end inside of the latest nightly of the ALXR server also the client side behavior you are describing is expected there's no way to get the host name from inside the headset you have to let it connect to the server over wifi first and then turn off client discovery in the settings, add your 127.0.0.1 IP, and then restart the ALXR server.
