### ISSUE TITLE
Firewalld issue with SteamOS during installation/configuration

### ISSUE THREAD

**Issue by KonKube** [alvr-org/ALVR#1931]
## Description
During the installation process, i received with the normal deck and root user the same issues.
It just said, that the firewalld configuration step failed.
No connection from Meta Quest 3 with installed ALVR were possible.

Output from the firewalld:

Dec 16 15:11:00 steamdeck firewalld[680]: ERROR: INVALID_SERVICE: alvr
Dec 16 15:11:00 steamdeck firewalld[680]: ERROR: INVALID_SERVICE: Zone 'public': 'alvr' not among existing services

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) 
- [0]  successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Local SteamOS

### Hardware
Steam Deck OLED

### Installation
**ALVR Version**: v20.5.0

**ALVR Settings File**:

**SteamVR Version**:  2.0

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [0] Portable (`zip`)
- [0] Source

To fix the issue, i cloned the repository and changed to the tag v20.5.0.
I found the causing lines here. https://github.com/alvr-org/ALVR/blob/master/alvr/xtask/firewall/alvr_fw_config.sh
15                firewall-cmd --zone="${zone}"  --add-service='alvr'
20                firewall-cmd --zone="${zone}"  --add-service='alvr' --permanent

I used "firewall-cmd --zone="public" --permanent --new-service-from-file=alvr-firewalld.xml" within the ALVR/blob/master/alvr/xtask/firewall/ directory and it succeeded.

From this point on i could connect with the meta quest 3 without any issues.

**Comment by Vixea** [comment]
Thanks for the change if you would like to submit a pr for it also I have good news that whenever firewalld makes a new release ALVR will be automatically in its list of services that you can allow
