### ISSUE TITLE
Black screen since SteamVR update

### ISSUE THREAD

**Issue by sol8712** [alvr-org/ALVR#1934]
As of yesterdays steamvr update to 2.2.2 when launching ALVR all seems to work as expected except the screen on the quest stays black once connected. All audio works and controller/environments work(as seen in steams vr view), nothing out the ordinary in logs.

This was not the case before today/yesterdays steamvr update.

Tested on 
Manjaro Linux(Arch)
ALVR latest stable 20.5.0
and
ALVR nightly 12-17
.appimage

**Comment by sol8712** [comment]
Downgrading to 2.1.10 makes the issue go away. Here's to hoping Steam doesn't shove yet another broken beta update to their "stable" branch....

**Comment by perillamint** [comment]
Maybe related with #1928?

**Comment by Weetile** [comment]
How to downgrade or access the nightly AppImage? I'm having the same problem, none of the beta branches fix it for me

**Comment by sol8712** [comment]
This is the one that worked for me, on steamvr stable(2.2.1)

https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2023.12.17
