### ISSUE TITLE
Streamed frames are very low quality. (PICO 4 & Linux)

### ISSUE THREAD

**Issue by TheeStickmahn** [alvr-org/ALVR#1937]
## Description

Title is hopefully self-explanatory.
The frames coming from the ALVR streamer are very blurry, no matter how much I crank up the bitrate.
***Sorry if this question is stupid.***
![peen](https://github.com/alvr-org/ALVR/assets/105667019/80c3d112-7349-408d-88be-7d5d470ddb78)
*screenshot from headset*

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=9515cb0c90

**CPU**:
*AMD Ryzen 5 5600G*

**GPU**:
*NVIDIA GeForce RTX 2060* **(Rev. A)**

**GPU Driver Version**:
*545.29.02*

**Audio**:
*Pipewire*

### Installation
**ALVR Version**: *20.5.0*

**ALVR Settings File**: It's just the default settings.

**SteamVR Version**: 2.2.3

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc) *(appimage)*
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: *Pop!_OS 22.04 LTS*

**Comment by TheeStickmahn** [comment]
Closed due to hardware change.

**Comment by Vixea** [comment]
Might I ask what hardware changes 
(Side rant not targeted at you it's just on my mind but when has a bug tracker become support - like seriously people)

**Comment by TheeStickmahn** [comment]
> Might I ask what hardware changes (Side rant not targeted at you it's just on my mind but when has a bug tracker become support - like seriously people)

Changed from an RTX 2060 to a Radeon 6700XT.
Could just have been nvidia being nvidia, so I felt the report was not accurate to my situation any longer.
