### ISSUE TITLE
alvr_get_frame return 0 while I porting on New HMD devices,could you help me debug what's wrong

### ISSUE THREAD

**Issue by highyun** [alvr-org/ALVR#1938]
since my HMD device not support OpenXR, I use tag v19.1.1

I porting all the apis called by cpp_main.cpp ,the lobby view show rightly.
then I connected to PC,audio can play rightly but video cannot show while steaming.

1.in render function,the alvr_get_frame return 0,streamHardwareBuffer is not nullptr;
//cpp_main.cpp
{
        void *streamHardwareBuffer = nullptr;
        auto timestampNs = -1;
	timestampNs = alvr_get_frame(&streamHardwareBuffer);
}
2.add dbg info in dequeue_output_buffer,cannot get timestamp 
12-22 00:16:15.406  4088  4215 I avr_rus : alvr_client_core::platform::android: Decoder dequeue buffer: OutputBuffer { codec: MediaCodec { inner: 0x70fa26a9a0 }, index: 16, info: AMediaCodecBufferInfo { offset: 0, size: 8, presentationTimeUs: 0, flags: 1 } }
12-22 00:16:15.406  4088  4215 I avr_rus : alvr_client_core::decoder: target_timestamp 0ns

could you help me debug this issue?
thanks a lot

[an.zip](https://github.com/alvr-org/ALVR/files/13750788/an.zip)

**Comment by Vixea** [comment]
what is your headset?

**Comment by highyun** [comment]
the headset is Pimax Crystal

**Comment by zarik5** [comment]
@highyun you can port ALVR to non-OpenXR platforms too, like PhoneVR does. You are always encouraged to use the latest version.

**Comment by highyun** [comment]
@zarik5 sorry ，I haven't used the Rust language before，the v20.5 seems have removed the Android and jni code?how should I port it without OpenXR?

**Comment by highyun** [comment]
thanks, it's my fault,the root cause is vrapi_EnumerateInputDevices return with  wrong value 0,already fixed
