### ISSUE TITLE
ALVR dashboard can't connect to SteamVR unless system has specific libx264 version.

### ISSUE THREAD

**Issue by iritetr** [alvr-org/ALVR#1940]
## Description
When I'm using portable alvr_streamer_linux package if I press "Launch SteamVR", SteamVR starts, but the Dashboard can't connect to it and says: "SteamVR: Disconnected"/"The streamer is not connected! Clients Will not be discovered". When I look into SteamVR log (.local/share/Steam/logs/vrserver.txt), the following error is present:

> [Info] - Unable to load driver alvr_server from /home/player/vr/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (libx264.so.163: cannot open shared object file: No such file or directory)
> [Error] - ASSERT: "DriverManager alvr_server load error libx264.so.163: cannot open shared object file: No such file or directoryu" at /data/src/common/vrcommon/drivermanager.cpp:439

My system has **/usr/lib64/libx264.so.164** library, and **/usr/lib64/libx264.so** symlink that points to it. Version **libx264.so.163** is deprecated and there's no way to install it using package management system.
If I manually create **/usr/lib64/libx264.so.163** symlink pointing to **/usr/lib64/libx264.so.164**, the error changes to:

> [Info] - Unable to load driver alvr_server from /home/player/vr/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so (/home/player/vr/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so: undefined symbol: x264_encoder_open_163)
> [Error] - ASSERT: "DriverManager alvr_server load error /home/player/vr/alvr_streamer_linux/lib64/alvr/bin/linux64/driver_alvr_server.so: undefined symbol: x264_encoder_open_163u" at /data/src/common/vrcommon/drivermanager.cpp:439.
> [Error] - Unable to load driver alvr_server because of error VRInitError_Init_FileNotFound(103). Skipping.

If I download **libx264.so.163** from rpmfind.net and put it into /usr/lib64 - Dashboard correctly connects to SteamVR.

From what I can conclude that version 163 is more than just and option - it's a requirement for the current ALVR Dashboard.
This situation encourages me to propose to either make the ALVR code x264 version independent or to put the specific version in the requirements.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Gentoo (amd64/17.1/desktop/gnome profile)
Wayland 1.22.0
Sway 1.8.1 (despite having Gnome profile, I use Sway for gaming because Gnome + Wayland can't into SteamVR)

### Hardware
**CPU**:
i9-9900K

**GPU**:
AMD Vega 64

**GPU Driver Version**:
amdgpu

### Installation
**ALVR Version**:
portable alvr_streamer_linux.tar.gz 20.5.0
portable alvr_streamer_linux.tar.gz 21.0.0-dev00+nightly.2023.12.29

**ALVR Settings File**:
default

**SteamVR Version**:
2.2.3

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Gentoo Linux 6.1.60

**Comment by Vixea** [comment]
its an issue with the "portable" build not being portable. It is dependent on a specific Ubuntu version I'm pretty sure if you read our docs we don't recommend it. I don't think I got to tell you that in the original help request

**Comment by Vixea** [comment]
either you should compile by source or use appimage(I know packaging on linux sucks)
