### ISSUE TITLE
(Feature Request) Add a toggle to disable and enable trusted clients

### ISSUE THREAD

**Issue by 0Human0** [alvr-org/ALVR#1943]

**Comment by zarik5** [comment]
Thanks for the request. What is your use-case exactly?

**Comment by 0Human0** [comment]
Just realized that a USB toggle was already added, Well I'm sure it would be useful for something else.

**Comment by zarik5** [comment]
> Just realized that a USB toggle was already added, Well I'm sure it would be useful for something else.

It was added and then removed. The feature was not ready.

**Comment by 0Human0** [comment]
I see, so would this be a easier replacement for now?

**Comment by zarik5** [comment]
To disable USB mode, just re-enable client discovery. Then disable it again to use USB mode

**Comment by 0Human0** [comment]
Fair enough, though I think that requires a restart to take effect.
