### ISSUE TITLE
Can't build v20.5.0 from source

### ISSUE THREAD

**Issue by ykchong45** [alvr-org/ALVR#1949]
## Description
I tried to build the ALVR client from source, but I had issue preparing deps.

```
C:\yk\ALVR>git checkout tags/v20.5.0
Previous HEAD position was 68eb603c [Auto] Bump version
HEAD is now at 4e1c56f6 [Auto] Bump version

C:\yk\ALVR>cargo xtask prepare-deps --platform android
    Updating git repository `https://github.com/zarik5/openxrs`
error: failed to get `openxr` as a dependency of package `alvr_client_openxr v20.5.0 (C:\yk\ALVR\alvr\client_openxr)`

Caused by:
  failed to load source for dependency `openxr`

Caused by:
  Unable to update https://github.com/zarik5/openxrs#2f5eb99f

Caused by:
  object not found - no match for id (2f5eb99f84213e766cc205026a6e09557a3420d3); class=Odb (9); code=NotFound (-3)
```

Checking the id shown in the last line, it seems to be a commit in an unmerged pull request. 

### Potential Solution
I replaced that line with "git+https://github.com/galister/openxrs#54c257bf6f42d7fbc99e9ee7addf4669dbbabd9f" seems to fixed the issue. 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: 13th Gen Intel(R) Core(TM) i9-13900KF   3.00 GHz

**GPU**:  NVIDIA GeForce RTX 4090

**GPU Driver Version**:	31.0.15.3742

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): 22H2 OS Build 22621.2861

**Comment by Vixea** [comment]
yea we're working on getting a new release out soon please hold on for a moment
