### ISSUE TITLE
ALVR and SteamVR Crashed together

### ISSUE THREAD

**Issue by huanviptq** [alvr-org/ALVR#1950]
![image](https://github.com/alvr-org/ALVR/assets/93026487/95ad50f9-68d6-46b3-8fd8-fdd6b6c36a2a)
It crashed along with SteamVR, steamVR said critical error

**Comment by SkyHearn** [comment]
I am also experiencing this issue. Steam VR will crash shortly after start up.
[crash_log.txt](https://github.com/alvr-org/ALVR/files/14154646/crash_log.txt)

## Software 
- ALVR streamer v20.6.1
-  STEAMVR 2.2.3
- Windows 10
