### ISSUE TITLE
Lacking documentation

### ISSUE THREAD

**Issue by BinaryVigilante** [alvr-org/ALVR#1951]
Hello,

I have been trying to make sense of the documentation and trying to connect my Pico 4 VR headset for the past 2 days now, and I'm sorry to say that the documentation is really lacking in explanation and details.

Things are described as if it is a developer that needs to read it, not a user trying to get it to work.

It is impossible to wrap the head around what is going on, what is doing what.

I'm sure it's a great project with a lot of potential, but documentation needs to be cleared up.

**Comment by Vixea** [comment]
Well what part of the documentation have you looked at what's confusing you, have you set your firewall rules?
