### ISSUE TITLE
Trusted clients: 4343.client.alvr: Unknown IP

### ISSUE THREAD

**Issue by Castro-Fidel** [alvr-org/ALVR#1952]
## Description
Does not connect:

Trusted clients: 
Unknow - Disconnected
4343.client.alvr: Unknown IP

But the ip address is entered correctly. The translation from Pico 4 to the browser is working.

## General Troubleshooting
- [ +] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ +] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=e371e895ec

### Installation
**ALVR Version**: 20.6.2

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ +] Portable (`appimage`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
ALT Regular

**Comment by charliekempf** [comment]
How did you solve this? I am having the same issue with a Windows PC + Quest 3

I am using an eGPU, RTX 2060. Wired ethernet to 5Ghz AX enabled router, wireless to Quest 3. I am able to ping the device via the command prompt. And ALVR recognizes my client, but I get the same issue when adding it.
