### ISSUE TITLE
SteamVR Crash while playing Beat Saber

### ISSUE THREAD

**Issue by YaHa12** [alvr-org/ALVR#1957]
## Description
[crash_log.txt](https://github.com/alvr-org/ALVR/files/13929248/crash_log.txt)
I was playing Beat Saber when SteamVr crashed

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment
Windows 10 22H2

### Hardware
Pico 4

**CPU**:
AMD Ryzen 7 3700x

**GPU**:
Nvidia RTX 4070 Ti

**GPU Driver Version**:
Game Ready 546.33

**Audio**:
Wave Link

### Installation
**ALVR Version**:
v20.6.0

**ALVR Settings File**:
[session.json](https://github.com/alvr-org/ALVR/files/13929244/session.json)

**SteamVR Version**:
Build-ID: 13024612

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

Windows 10 Version 22H2 (Build 19045.3930)

**Comment by myghi63** [comment]
I had a lot of troubles with nvidia with VR on linux and since I also have a pico 4, with a way lower end AMD gpu (rx 5500xt 8gb), it's probably something related to nvidia, steam proton (maybe try proton-ge to see if it helps) or maybe some random data corruption on your steamvr / proton / alvr / game itself

**Comment by myghi63** [comment]
Please try using alvr-nightly to see if that helps

**Comment by Bixilon** [comment]
I am facing similar issues.  I am launching beat saber (latest release) and I can see the beat saber logo but it instantly but then it either freezes or black screens.

My setup is a bit different then yours, I do use an nvidia gpu, but I am running the whole thing on wine/proton.

When launching steam vr from steam (i.e. alvr disabled) the game starts up just fine (though I can not get through the menu without controllers).


@myghi63  I am using the latest version built from source just now. 

Another intersting thing is (as most wine users tell) the "beta" pre unity update works just fine.



In systemd the following is logged:
```
Mär 04 23:27:22 moritz-cyra kwin_wayland_wrapper[998008]: /tmp/dumps/assert_20240304232722_7.dmp
Mär 04 23:27:22 moritz-cyra assert_20240304232722_7.dmp[998008]: Uploading dump (out-of-process)
                                                                  /tmp/dumps/assert_20240304232722_7.dmp
Mär 04 23:27:22 moritz-cyra kwin_wayland_wrapper[998011]: crash_20240304232722_8.dmp[998011]: Uploading dump (out-of-process)
Mär 04 23:27:22 moritz-cyra kwin_wayland_wrapper[998011]: /tmp/dumps/crash_20240304232722_8.dmp
Mär 04 23:27:22 moritz-cyra crash_20240304232722_8.dmp[998011]: Uploading dump (out-of-process)
                                                                 /tmp/dumps/crash_20240304232722_8.dmp
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998008]: assert_20240304232722_7.dmp[998008]: Finished uploading minidump (out-of-process): success = yes
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998008]: assert_20240304232722_7.dmp[998008]: response: CrashID=bp-138120f2-d287-408f-bc50-c75042240304
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998008]: assert_20240304232722_7.dmp[998008]: file ''/tmp/dumps/assert_20240304232722_7.dmp'', upload yes: ''CrashID=bp-138120f2-d287-408f-bc50-c75042240304''
Mär 04 23:27:24 moritz-cyra assert_20240304232722_7.dmp[998008]: Finished uploading minidump (out-of-process): success = yes
Mär 04 23:27:24 moritz-cyra assert_20240304232722_7.dmp[998008]: response: CrashID=bp-138120f2-d287-408f-bc50-c75042240304
Mär 04 23:27:24 moritz-cyra assert_20240304232722_7.dmp[998008]: file ''/tmp/dumps/assert_20240304232722_7.dmp'', upload yes: ''CrashID=bp-138120f2-d287-408f-bc50-c75042240304''
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998011]: crash_20240304232722_8.dmp[998011]: Finished uploading minidump (out-of-process): success = yes
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998011]: crash_20240304232722_8.dmp[998011]: response: CrashID=bp-41298499-0596-4aa0-a5b6-8546e2240304
Mär 04 23:27:24 moritz-cyra kwin_wayland_wrapper[998011]: crash_20240304232722_8.dmp[998011]: file ''/tmp/dumps/crash_20240304232722_8.dmp'', upload yes: ''CrashID=bp-41298499-0596-4aa0-a5b6-8546e2240304''
Mär 04 23:27:24 moritz-cyra crash_20240304232722_8.dmp[998011]: Finished uploading minidump (out-of-process): success = yes
Mär 04 23:27:24 moritz-cyra crash_20240304232722_8.dmp[998011]: response: CrashID=bp-41298499-0596-4aa0-a5b6-8546e2240304
Mär 04 23:27:24 moritz-cyra crash_20240304232722_8.dmp[998011]: file ''/tmp/dumps/crash_20240304232722_8.dmp'', upload yes: ''CrashID=bp-41298499-0596-4aa0-a5b6-8546e2240304''
```

I am attaching the minidump.

[crash_20240304232722_8.zip](https://github.com/alvr-org/ALVR/files/14487902/crash_20240304232722_8.zip)

**Comment by Vixea** [comment]
On Linux Nvidia just doesn't work with OpenXR games which beat saber is one of. There's nothing we can do.

**Comment by Bixilon** [comment]
@Vixea Sorry, I don't get it. The old version is working? Was it not using OpenXR? All other games are working fine

**Comment by Vixea** [comment]
There is an older pre-openxr version of beat saber yes

**Comment by Vixea** [comment]
Anyway the lack of replies from op means I'm going to be closing this
