### ISSUE TITLE
No desktop on Wayland

### ISSUE THREAD

**Issue by benthetechguy** [alvr-org/ALVR#1963]
## Description
When I was using GNOME on X11, I could view and interact with my Linux desktop. Switching to Wayland, there is no desktop, only a mouse pointer (which doesn't move the acutal mouse on the desktop).

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=b08880045e

**CPU**: AMD Ryzen 5 5600X

**GPU**: Nvidia GTX 1060 6GB

**GPU Driver Version**: 545.29.06

**Audio**: Pipewire

### Installation
**ALVR Version**: 21.0.0_dev00.r2757.1b1ae10e

**ALVR Settings File**: [session.json](https://github.com/alvr-org/ALVR/files/13944427/session.json)

**SteamVR Version**: 2.2.3

**Install Type**:
- [x] Packaged (AUR)
- [ ] Portable
- [ ] Source

**OS Name and Version**: Arch Linux

**Comment by Vixea** [comment]
steamvr bug, closing

**Comment by Abigail-17** [comment]
I believe this is a known issue with Wayland on GNOME, it's on their end

**Comment by benthetechguy** [comment]
Thanks for letting me know
