### ISSUE TITLE
Black screen on Quest3's end

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [alvr-org/ALVR#1972]
## Description

Quest connects to the host with no problems, all data sans video is streamed. The video is just a black screen on the quests end.
steamVR throws the error, `-202: Make sure your headset's display is in full screen mode.`

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel i5-9300H (8) @ 4.100GHz

**GPU**: NVIDIA GeForce GTX 1650 Mobile

**GPU Driver Version**: Nvidia-driver-545

**Audio**: Pipewire ?

### Installation
**ALVR Version**: v20.6.0

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Pop!_OS 22.04 LTS

**Comment by Macjja** [comment]
I had the same issue (I have the same gpu), and given that it is the mobile gpu I’d assume you also have an igpu

If running an integrated GPU with an Nvidia GPU add this into the launch options of SteamVR:
`VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%`

**Comment by Kiwi-the-Cat** [comment]
> I had the same issue (I have the same gpu), and given that it is the mobile gpu I’d assume you also have an igpu
> 
> If running an integrated GPU with an Nvidia GPU add this into the launch options of SteamVR: `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%`
> 
> That should fix the black screen issue

Thank you, that works!
