### ISSUE TITLE
cannot find audio device which name contains "pipewire"

### ISSUE THREAD

**Issue by Kiwi-the-Cat** [alvr-org/ALVR#1976]
## Description

ALVR refuses to connect to headset with this error

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:Intel® Core™ i5-9300H CPU @ 2.40GHz × 8

**GPU**:Intel® Core™ i5-9300H CPU @ 2.40GHz × 8

**GPU Driver Version**: 545

**Audio**: pipewire?

### Installation
**ALVR Version**: 20.6.1

**ALVR Settings File**:

**SteamVR Version**: 2.3 (whatever is the most recent)

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Pop!_OS 22.04 LTS x86_64

**Comment by wsippel** [comment]
What Pipewire version do you use (`pipwire --version`). Pipewire 1.0.2 had a bug that breaks ALVR in this exact way, it's fixed in 1.0.3.

**Comment by Kiwi-the-Cat** [comment]
pipewire 1.0.2, it won't let me update it

**Comment by wsippel** [comment]
No idea how downgrading packages on Pop works, and it's potentially risky, so I'd suggest just waiting for System76 to fix the issue. Maybe file a bug report with them https://github.com/pop-os/pop/issues and refer to the upstream issue https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3830

**Comment by The-personified-devil** [comment]
In the meantime, if you have the pulseaudio compatibility layer for pipewire installed, you should be able to just use the default device named "pulseaudio".
