### ISSUE TITLE
Pass controller batteries to steamvr

### ISSUE THREAD

**Issue by art0007i** [alvr-org/ALVR#1988]
## Description

Currently in steam vr I cannot see what battery % my controllers are, this used to work on older versions of ALVR.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: i5-10400f

**GPU**: amd rx 6700 xt

**GPU Driver Version**: 23.12.1

**Audio**: (idk what this means)

### Installation
**ALVR Version**: v20.6.1

**ALVR Settings File**: [session.json](https://github.com/alvr-org/ALVR/files/14317515/session.json)

**SteamVR Version**: beta 2.4.1

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 10 Version 22H2 (OS Build 19045, 4046)

**Comment by zarik5** [comment]
This is not possible anymore because OpenXR does not provide controllers battery.

**Comment by art0007i** [comment]
that's unfortunate
