### ISSUE TITLE
Cannot Connect to my computer (Connection Timeout)

### ISSUE THREAD

**Issue by Veitaserum4** [alvr-org/ALVR#1989]
## Description
I get the error message "Connection Timeout" when connecting to my computer, the only error that shows up in the log is "Handshake Error 1277 for 1277.client.alvr: Adress is already in use (os error 98)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
-Yup
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
Yup
## Environment
Linux Mint
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=2b18c690f4
### Installation
**ALVR Version**:
Latest (v20.6.1)
**ALVR Settings File**:
[session.json](https://github.com/alvr-org/ALVR/files/14320286/session.json)

**SteamVR Version**:
Latest (2.3.5)
**Install Type**:
Appimage

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Linux Mint 21.3

**Comment by Veitaserum4** [comment]
Fixed by changing microphone input?

**Comment by afulle12** [comment]
What did you select as the microphone input? I think I ran into the same problem.

**Comment by sophisma** [comment]
It was happening to me, I rebooted my phone and it started connecting again.
