### ISSUE TITLE
Arch linux missing build dependency `pkgconf` cant build any aur version

### ISSUE THREAD

**Issue by filipagh** [alvr-org/ALVR#1990]
## Description

after clean Manjaro instalation and after wiki steps instal steam vr setup rustup with toolchain ... i was unable build aur version of alvr or alvr-git  

it fail with error `ERROR: libdrm not found using pkg-config`

but i have instaled libdrm 

then i try build from source and i get same error

then i try check what is pkg-confg  and found out that another package `pkgconf` which is not instaled

after install of that package i was able build aur alvr pakage 

i think pkgconf shoud be as dependency in aur  or mention in wiki 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment

other info is not needed for this issue  

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Vixea** [comment]
we don't support manjaro... it a broken distro.
