### ISSUE TITLE
[Quest 3/Pro] ERROR Handshake error for 5185.client: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by Mithras** [alvr-org/ALVR#1996]
## Description
https://aur.archlinux.org/packages/alvr-git + apk from https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.02.18 result in `ERROR Handshake error for 5185.client: EOF while parsing a value at line 1 column 0` on both Quest 3 and Pro.
Alvr v20 works on both.

### Installation
**ALVR Version**: https://aur.archlinux.org/packages/alvr-git + apk from https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.02.18

**ALVR Settings File**: default (after deleting)

**SteamVR Version**:  https://archlinux.org/packages/multilib/x86_64/steam/

6.7.5-arch1-1.
KDE Plasma 6 rc2.
NVidia 550 beta.

**Comment by filipagh** [comment]
same for me

**Comment by Mithras** [comment]
The latest build works for me.

**Comment by DevanWolf** [comment]
The bug returned on v20.0.7.0
