### ISSUE TITLE
Add Troubleshooting ➡ Hardware Encoding Wiki Page

### ISSUE THREAD

**Issue by damaestro** [alvr-org/ALVR#2000]
I didn't add any Vulkan examples yet because I have no way to test them yet. I will add that in a subsequent PR. The remaining AV1 testing is syntactically correct, I just don't have access to any hardware to be able to test that codec.

This has been tested on the following hardware:

- Nvidia GTX 3080ti using NVENC
- Nvidia GTX 4080 using NVENC (via makulski on discord)
- Intel Core i5-7360U using VA-API
- Intel Arc A770 using VA-API (via gumba on discord)
- AMD Radeon RX 7900 XTX using VA-API (via @mmproyer)

GPUS to test:

- [x] Nvidia Turing or later
- [x] Intel GEN or later
- [x] AMD VCN 1.0 or later

Codecs to test:

- [x] Nvidia AVC
- [x] Nvidia HEVC
- [x] Nvidia AV1
- [x] Intel AVC
- [x] Intel HEVC
- [x] Intel AV1
- [x] AMD AVC
- [x] AMD HEVC
- [x] AMD AV1

**Comment by zarik5** [comment]
You can PR to the wiki :) just add the file in the /wiki folder. Just pay attention to the file name and title. Check other files how that translates to the actual wiki.

**Comment by damaestro** [comment]
@zarik5 Sorry, I missed that. I'm just used to not being able to PR github wiki's. I'll work on a PR and reference this issue.

**Comment by damaestro** [comment]
https://github.com/alvr-org/ALVR/pull/2004 is the PR.
