### ISSUE TITLE
alvr_vrcompositor_wrapper compile error with gcc 10 on linux (includes fix)

### ISSUE THREAD

**Issue by ben-mkiv** [alvr-org/ALVR#2001]
## Description
```
error: failed to run custom build command for `alvr_vrcompositor_wrapper v20.6.1 (/opt/alvr/ALVR-20.6.1/alvr/vrcompositor_wrapper)`

Caused by:
  process didn't exit successfully: `/opt/alvr/ALVR-20.6.1/target/release/build/alvr_vrcompositor_wrapper-e2d402ed9c819b12/build-script-build` (exit status: 101)
  --- stderr
  $ bash -c "g++ -shared -fPIC $(pkg-config --cflags libdrm) drm-lease-shim.cpp -o /opt/alvr/ALVR-20.6.1/target/release/build/alvr_vrcompositor_wrapper-0209ba2599334275/out/../../../alvr_drm_lease_shim.so"
  drm-lease-shim.cpp: In function ‘void open_drm_fd()’:
  drm-lease-shim.cpp:70:35: error: ‘std::filesystem’ has not been declared
     70 |     for(auto cardCandidate : std::filesystem::directory_iterator("/dev/dri")) {
        |                                   ^~~~~~~~~~
  thread 'main' panicked at alvr/vrcompositor_wrapper/build.rs:11:41:
  called `Result::unwrap()` on an `Err` value: command exited with non-zero code `bash -c "g++ -shared -fPIC $(pkg-config --cflags libdrm) drm-lease-shim.cpp -o /opt/alvr/ALVR-20.6.1/target/release/build/alvr_vrcompositor_wrapper-0209ba2599334275/out/../../../alvr_drm_lease_shim.so"`: 1
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
irrelevant

**CPU**:
irrelevant

**GPU**:
irrelevant

**GPU Driver Version**:
irrelevant

**Audio**:
irrelevant

### Installation
20.6.1

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

Gentoo/Linux

Build fails with the error above with gcc (Gentoo 10.3.0-r2 p3) 10.3.0

adding ` -std=c++17` parameter to the g++ build command in `alvr/vrcompositor_wrapper/build.rs` fixed the issue for me and compiled fine

**Comment by ben-mkiv** [comment]
updated my system and on current Gentoo with GCC13 this isn't a problem anymore.

So i guess i'll mark this as closed.

**Comment by gijaeAhn** [comment]
I got a same problem on Ubuntu 20.04.6 LTS focal
Could you tell me what was the problem and solution of it?

**Comment by Vixea** [comment]
don't use a older than latests LTS would probably help

**Comment by ben-mkiv** [comment]
> I got a same problem on Ubuntu 20.04.6 LTS focal Could you tell me what was the problem and solution of it?

my solution is described in the last sentence of the first post
