### ISSUE TITLE
Valve Index Headset Emulation

### ISSUE THREAD

**Issue by Nathan66077** [alvr-org/ALVR#2002]
Hey ALVR, I just wanna suggest you to add valve index emulation, everyone would be happy about it, the most happy being me, I really just dont wanna find the index serial number, having almost 10 million possible combinations, hope you have a great day.

**Comment by zarik5** [comment]
We need someone to pull out the strings and we can build the Valve Index emulation mode.

**Comment by TAGMONKE** [comment]
Reply > Hey ALVR, I just wanna suggest you to add valve index emulation, everyone would be happy about it, the most happy being me, I really just dont wanna find the index serial number, having almost 10 million possible combinations, hope you have a great day.

Agreed

**Comment by Nathan66077** [comment]
Reply > 
We need someone to pull out the strings and we can build the Valve Index emulation mode.

wdym pull out the strings? (not to be dumb or anything)

**Comment by zarik5** [comment]
I mean decompile some SteamVR related binaries and look for strings. I never did that so I cannot help with that.

**Comment by TAGMONKE** [comment]
LHR-398613741

**Comment by TAGMONKE** [comment]
might work

**Comment by cheezygt** [comment]
> LHR-398613741

do you have oculus go serial numbers?
