### ISSUE TITLE
Audio haptics for the Pico 4

### ISSUE THREAD

**Issue by 0Human0** [alvr-org/ALVR#2006]
Add a mode that uses the audio for haptics for the Pico 4 controllers instead of normal haptics. Please this would be the actual use of the amazing haptics the Pico controllers have and would be great for Beat Saber

**Comment by Meister1593** [comment]
If only Pico provided those extensions before, alvr probably would have used it already

Fairly recently (in 5.9 pui) Pico started to expose various extensions (face, eye, body tracking, something with controllers) that they also use for Pico Connect, but they are completely undocumented and no headers available, so someone has to figure out how to use them.

**Comment by 0Human0** [comment]
Aw man, I was kind of hoping that OpenXR just supported playing frequencies through the vibration motors already
