### ISSUE TITLE
Linux: Rotated playspace breaks ALVR

### ISSUE THREAD

**Issue by galister** [alvr-org/ALVR#2013]
When SteamVR playspace is rotated, the headset image stutters heavily. During a stutter, the eye images freeze in place, in a way that the frozen image follows head movement.

![image](https://github.com/alvr-org/ALVR/assets/22305755/97cd369f-63a3-460f-8ff9-debf94c7f72d)

This happens when using `SetWorkingStandingZeroPoseToRawTrackingPose` or the Seated variant with a matrix where the basis is not identity.

Can also be triggered using OVR Advanced Settings' space rotate functionality.

Does not happen with wired headsets.

Some older titles use this as a way to recenter during gameplay, in some cases even automatically, so it's really hard to work around. For example, Subnautica does this when entering player-built structures.

Resetting the matrix's basis to identity fixes the issue. For example, if the game breaks your view, you can use [wlx-overlay-s](https://github.com/galister/wlx-overlay-s)'s `Reset Offset` button on the Settings panel and the views will be fixed instantly.

I have not tested on Windows, but I would expect this to be a well known issue by now if it broke the same way on Windows.

**Comment by galister** [comment]
I also found a very similar behavior when using ALVR in conjunction with lighthouse devices, and starting a lighthouse device before connecting the HMD for the first time. Once the HMD has been connected at least once, only then the trackers are safe to be powered on.

**Comment by XenoPL** [comment]
+1 on the matter, it causes stutters and small, but constant jumps of camera fov. For me it happens both on Linux and Windows when I'm  entering 3D world in Falcon BMS. The difference between Linux and Windows is: under Linux/Proton once it starts it happens all the time, under Windows it's visible when game goes back to 2D mode.

**Comment by Vixea** [comment]
So let's say we workaround this by just checking if the Matrix isn't an identity matrix and resetting it to one. Would this break playspace movers?

**Comment by galister** [comment]
if @XenoPL says they also had this on windows, i would test it further there. if it's broken on windows too, then it's likely not a steamvr bug

**Comment by galister** [comment]
@Vixea i was actually thinking to implement this in wlxoverlay for the time being. i think it'll be fine, but will definitely impact titles that rely on this working

**Comment by XenoPL** [comment]
Confirm. My test case is an app with 2D UI and 3D world with VR being initiated when 3D world is loading. App (for now) is using OpenVR, so SteamVR is mandatory here.
Under Windows when 3D world is loading but still not ready, I can see SteamVR player space starts those small jumps, ans stutters. Once I'm in 3D world it seems normal, ie no camera jumps, no stutters, no jumps in latency in ALVR statistics.
When I exit 3D world and go back to 2D UI it starts to be really bad, frozen picture in headset, blank background behind 2D window, playerspace jumps with almost every head movement huge, stuttering and frequent spikes of latency.
When the same game on the same hardware is running under Linux those jumps/stutters happen also when I'm in 3D world.

From my limited testing, if game is run on Windows with VirtualDesktop+SteamVR, it seem to be fine.
If this one could be fixed  could drop Windows  and be back to use Linux exclusively ... so my hopes are solution of some sort can be found.

**Comment by galister** [comment]
@XenoPL can you try this on windows?
- install [OpenVR-AdvancedSettings](https://store.steampowered.com/app/1009850/OVR_Advanced_Settings/)
- get in vr with alvr
- start OVR advanced settings via steam
- open OVR advanced settings panel from bottom of steamvr dashboard
- on offsets tab, change the y rotation
- see if it breaks the same way

this is known to work ok with VD and SteamLink

**Comment by XenoPL** [comment]
Rotating space in OVR AS under Windows didn't trigger the bug, but it's definitely there:
![ALVR_space_move_bug](https://github.com/alvr-org/ALVR/assets/61295718/3d1d4759-59ba-4bcd-a64d-d5e19fb0ea75)

**Comment by galister** [comment]
@XenoPL does the `Seated recenter` button on the same offsets page trigger it?

**Comment by XenoPL** [comment]
With OVR AS I coulnd't trigger the bug with any setting present on offset tab, rotating, moving space on x/y/z axis nor seated recenter option is unable to make alvr stutter. I've tried latest stable:  5.7.4 and 5.8.6 beta.

**Comment by galister** [comment]
if you have [subnautica](https://store.steampowered.com/app/264710/Subnautica/), i think that's also worth trying on windows with the [vr mod](https://github.com/Okabintaro/SubmersedVR). on linux, this breaks right on the main menu.

**Comment by XenoPL** [comment]
Falcon BMS itself https://www.falcon-bms.com/downloads/
For legal reason you need to have original Falcon 4 installed to proceed with installation of BMS.
Falcon 4 is available on
Steam: https://store.steampowered.com/app/429530/Falcon_40/
GoG: https://www.gog.com/pl/game/falcon_collection   Falcon 4 is in extra downloads

Short installation instruction:
 - install Falcon 4
 - if steam version is used, run it once to let steam installer create all the registry entries
 - install Falcon BMS

Steps to reproduce 
Use game shortcut  to start its Launcher,  enable VR with a switch/slider below Theater selection dropdown list and start actual game with Launch button
In main UI select Dogfight, then click commit in game type selection window. On next page click TAKEOFF button (bottom right) to enter 3D world. Exit 3D world with Esc then E to end mission. Once back to UI all the said problems should manifest themself quite clearly.

**Comment by galister** [comment]
@XenoPL we managed to track down the issue, but it is very Linux specific. Your BMS issue is caused by another bug and is not related to the original topic of this ticket. you might want to open a new ticket with the details.

**Comment by XenoPL** [comment]
Thanks for headsup, if it'll fix stutter, pov jumps and latency spikes under Linux, then I'd more than happy. Actually issues with running BMS under Linux are only reason I've installed Windows on my bare metal system first time for last 15 years.
But still, I'm gonna test t both on Linux and Windows. If issues will persist on any of those I'll report back :)

**Comment by XenoPL** [comment]
I did some testing with alvr-streamer build from today master. I'm happy to report changes made fixed my issues with Falcon BMS on Linux. Nice steady latency in 80-100ms range and no jumps or shifts in playerspace. Very pleasant experience in general.
I'll do more testing on Windows side once there'll be new nightly build available and report back.
