### ISSUE TITLE
Handshake error for 3965.client.alvr: Cannot find audio device which name contains "pipewire"

### ISSUE THREAD

**Issue by pawamoy** [alvr-org/ALVR#2019]
## Description

I get this error message when clicking "Trust" on the client:

```
Handshake error for 3965.client.alvr: Cannot find audio device which name contains "pipewire"
```

Note that clicking the Download and set... button logged a success message (successfully downloaded set On connect / On disconnect script).

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

None of these pages contain the word "pipewire". Searching for "audio" doesn't yield anything either.

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=d9dd8f8f33

### Installation
**ALVR Version**: v20.6.1

**ALVR Settings File**: am I supposed to copy/paste the settings file here? Where is it located? (archlinux)

**SteamVR Version**: 2.3.5

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source (probably, it compiled when I did `yay -S alvr`)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by pawamoy** [comment]
I needed to install `pipewire`, `pipewire-pulse`, and `pipewire-alsa` (maybe):

```bash
yay -S pipewire pipewire-pulse pipewire-alsa
```

**Comment by lividhen** [comment]
Had it working just fine fir a while then it broke in the way you have described. Reinstalled those packages and now I have a magical new issue of the vr audio coming out of my PC speakers and the quest mic audio coming out the quest speakers 🤣
So, still trying to figure it out 😓

**Comment by pawamoy** [comment]
Yes I have the same audio issues :/
