### ISSUE TITLE
Headset stays black

### ISSUE THREAD

**Issue by LuNeder** [alvr-org/ALVR#2024]
## Description

After ALVR is started and connects, the headset screen turns black and stays like that.  All tracking still works (if I open that steamvr window that lets you see the vr stuff I can see that everything works), but nothing is shown at the headset.

ALVR logs don't say anything interesting, dmesg also shows no errors

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=2db4f35401

**CPU**: AMD Ryzen 9 7950X3D

**GPU**: NVIDIA GeForce RTX 4090

**GPU Driver Version**: NVidia proprietary 550.54.14 (latest as of now)

**Audio**: pipewire 

### Installation
**ALVR Version**: v21.0.0-dev00+nightly.2024.03.05

**ALVR Settings File**: 
[session.json](https://github.com/alvr-org/ALVR/files/14547604/session.json)

**SteamVR Version**: beta 2.4.2 (1709662163)

**Install Type**: appimage

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): openSUSE Tumbleweed (latest update as of now)

**Comment by SunnyOd** [comment]
Exactly same issue here. Using 3090, on nobara with latest kernel and nvidia 550 driver,  ALVE v206.1 AppImage and quest 3. Using the latest steamvr beta I'm getting the same exact issue

**Comment by Wyfi0** [comment]
Same issue here  on Arch linux, https://linux-hardware.org/?probe=6f76b5bd1c, with ALVR v20.6.1 on both my Quest 2 and Appimage on pc. Also I am using steamvr beta 2.4.3.  I can run steamvr and see my controllers through the vr view and even start games, but nothing in the headset. I reinstalled ALVR on the Quest after deleting it and still have the issue.

Thanks!

**Comment by Veitaserum4** [comment]
Same issue on mint, using latest ALVR (v20.6.1) on quest 2, using appimage on pc, tried beta steamvr and non beta, displaying vr view on the computer works fine but black screen in the headset. I also reinstalled multiple times, both nightly and normal, nothing worked.
https://linux-hardware.org/?probe=f59b841fe1

**Comment by m2neral** [comment]
Try killing your compositor. That fixes the black display issue for me (picom in my case).

**Comment by Wyfi0** [comment]
> Try killing your compositor. That fixes the black display issue for me (picom in my case).

Sorry, I don't understand. I'm using kde-plasma on wayland and killing kwin_wayland closes all my apps. Could you explain?

**Comment by Veitaserum4** [comment]
> Try killing your compositor. That fixes the black display issue for me (picom in my case).

Killing "vrcompositor.re" (which is the only process called compositor, so i think that's what you're talking about) just crashes steamvr

**Comment by Wyfi0** [comment]
I believe they are talking about the display compositor (picom in their case and kwin_wayland for me). Either way it still doesn't work.

**Comment by LuNeder** [comment]
> Try killing your compositor. That fixes the black display issue for me (picom in my case).

I’ll try killing Compiz next time to see if it works, but then again it isn’t really a solution since stuff gets bugged af with no compositor xD

**Comment by Veitaserum4** [comment]
I see, well i looked it up for the past 30 minutes and i dont think you can even kill the compositor on mint, and LuNeder is right, things would get buggy, so not an optimal solution

**Comment by Wyfi0** [comment]
I've got it working on ALVR v20.7.0. I updated both server and client and it worked!

**Comment by Furdox** [comment]
Getting the same issue even after updating and killing picom

**Comment by m2neral** [comment]
> Try killing your compositor. That fixes the black display issue for me (picom in my case).

This doesn't work for me anymore either btw.

**Comment by toxicfox2491** [comment]
I managed to get it running again by downgrading the steamVR version to 1.27.5, it also works with oculus_win7and8 1.15.12
most VR games dont work on these tho

**Comment by The-personified-devil** [comment]
Reference solution: https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

**Comment by LuNeder** [comment]
> Reference solution: [Wiki: Linux Troubleshooting ()](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting)

Can confirm this works. Completely forgot about closing this issue, sorry
