### ISSUE TITLE
Audio outputting to mic stream

### ISSUE THREAD

**Issue by CraftMaster163** [alvr-org/ALVR#2029]
## Description

The audio sink has no sound but when i switch to the mic stream i hear my pc and myself

## General Troubleshooting
- [yes] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=1c1825d346

**CPU**:Ryzen 5800x

**GPU**:Radeon 7800xt

**GPU Driver Version**:Unknown

**Audio**:Unknown

### Installation
**ALVR Version**:v20.6.1

**ALVR Settings File**:

**SteamVR Version**:2.3.5

**Install Type**:
- [AppImage] Packaged (`exe`, `deb`, `rpm`, etc)
- [No] Portable (`zip`)
- [Github] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):Linux Mint Cinnamon

**Comment by ZGltYQ** [comment]
Same issue

**Comment by ZGltYQ** [comment]
Script audio-setup run every time i leave my game zone and i must choose output mic again, it is very annoying, as a stopgap you can change setup_audio function to:

```function setup_audio() {
  if [[ $USE_HEADSET_AUDIO == 1 ]]; then
    echo "Setting up audio"
    pactl load-module module-null-sink sink_name=ALVR-MIC-Sink media.class=Audio/Sink | tee -a /run/user/1000/alvr-audio
    pactl set-default-sink ALVR-MIC-Sink
    pactl move-source-output "$(get_playback_source_output_id alsa_capture.vrserver)" "$(get_sink_id_by_name ALVR-MIC-Sink)"
  fi
}```

This won't fix the way you can hear yourself, but you will be able to hear the game without manual adjustments.

**Comment by devurandom** [comment]
Could this be a duplicate of https://github.com/alvr-org/ALVR/issues/1821 ?

**Comment by ZGltYQ** [comment]
> Could this be a duplicate of #1821 ?

i have tried this solution but it doesn't work for me

**Comment by ZGltYQ** [comment]
@CraftMaster163 did you find solution ?

**Comment by CraftMaster163** [comment]
nope
