### ISSUE TITLE
Trusted client is incompatible when connect to vision pro

### ISSUE THREAD

**Issue by Atagoxx** [alvr-org/ALVR#2037]
I am trying to connect my vision pro to my windows 11 pc for the first time, and I got this warning: Trusted client is incompatible! Expected protocol ID: 1686174404061257063, found: 7466344377858005457
It turns up I can't connect my vision pro to my pc.
My ALVR is at Nightly.2024.03.20

**Comment by zarik5** [comment]
You need to use a nightly server for then nightly client build

**Comment by dblunk88** [comment]
I literally had the same issue. If it's the official ALVR from Testflight, grab the nightly from [ALVR v21.0.0-dev00+nightly.2024.03.24](https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.03.24).

After running the server, I still had that message. It went away after I restarted SteamVR from the ALVR gui

**Comment by Kacchan16** [comment]
Hello, @zarik5 @dblunk88 @Atagoxx 

Now, I am trying to connect my quest 3 ( ALVR ) to PC (Linux), but its showing
`Trusted client is incompatible! Expected protocol ID: 15569632614514957802, found: 1686174404061257063`

I am using "ALVR streamer v21.0.0-dev01+nightly.2024.08.21" in PC and "ALVR v20.10.0"
I tried previous versions of ALVR streams in PC, but no use. I thought of  using new updated ALVR in quest3, but its already updated. 

Can someone help me here to solve this, Thanks !

**Comment by zarik5** [comment]
@Kacchan16 you must always use compatible versions of server and client. in paricular, first number should match (v20 or v21) and -devXX number (or omitted).

**Comment by Kacchan16** [comment]
Hi @zarik5 

Thanks for your quick response, I tried with " ALVR v20.0.0-dev15+nightly.2023.06.01" just now. But when I use this old version, Its just not connecting to SteamVR and not detecting the headset.
![Screenshot from 2024-08-22 12-09-50](https://github.com/user-attachments/assets/c0dfc301-78a4-4d24-9ec8-b1bce84aa307)

Is there any way to install v21 in quest ??

**Comment by zarik5** [comment]
I said you have to use matching versions. v20.0.0-dev15+nightly.2023.06.01 and v20.10.0 do not match. matches the first number (v20) but not the -devXX version. the client version has no -devXX

**Comment by Kacchan16** [comment]
Thanks @zarik5

just for reference, can you tell me how to install the launcher in quest

**Comment by zarik5** [comment]
The launcher is a pc app. You can find it in the usual downloads page
