### ISSUE TITLE
Update flatpak SDK to org.freedesktop.Sdk//23.08

### ISSUE THREAD

**Issue by devurandom** [alvr-org/ALVR#2038]
## Description

The `com.valvesoftware.Steam.Utility.alvr` flatpak is currently being built using `org.freedesktop.Sdk//22.08`, cf. https://github.com/alvr-org/ALVR/blob/68ea265f7ac484588333cdeead01c0c287e040db/alvr/xtask/flatpak/com.valvesoftware.Steam.Utility.alvr.json#L4

The `com.valvesoftware.Steam` flatpak, however, is being built against `org.freedesktop.Platform//23.08`, cf. https://github.com/flathub/com.valvesoftware.Steam/blob/69514fe34f91ae1ee1b744fce2f3320c01a6d769/com.valvesoftware.Steam.yml#L2-L3

https://docs.flatpak.org/en/latest/extension.html#extension-manifest says the following about the versions that should be used to build an application extension:
> `runtime` should be the ID of the parent module where the extension point is defined.
> `sdk` should be the same SDK used to build the runtime, followed by its version.

Since `org.freedesktop.Sdk//22.08` is not the SDK used to build `com.valvesoftware.Steam`, which is instead built against `org.freedesktop.Platform//23.08`, which is built against `org.freedesktop.Sdk//23.08`, this can cause mismatches between GL / Vulkan driver libraries and the ALVR SteamVR driver.

Examples for crashes that can be caused by such version mismatches:
* https://github.com/ValveSoftware/Source-1-Games/issues/5043
* https://github.com/ValveSoftware/SteamVR-for-Linux/issues/647
* https://github.com/ValveSoftware/SteamVR-for-Linux/issues/579

It would be good to build `com.valvesoftware.Steam.Utility.alvr` against the current `org.freedesktop.Sdk//23.08`.

**Comment by Vixea** [comment]
#2039
