### ISSUE TITLE
Flatpak: pressure-vessel-wrap[9482]: W: Unable to look up resolved path "/app/share/vulkan/explicit_layer.d/../../../lib64/libalvr_vulkan_layer.so" in provider

### ISSUE THREAD

**Issue by devurandom** [alvr-org/ALVR#2043]
## Description

When run in a Flatpak with `com.valvesoftware.Steam.Utility.alvr`, cf. https://github.com/alvr-org/ALVR/wiki/Flatpak, Steam appears to have trouble loading [`/app/share/vulkan/explicit_layer.d/alvr_x86_64.json`](https://github.com/alvr-org/ALVR/blob/c2e864c41a4c2e5126fa797934c6f53360a0456b/alvr/vulkan_layer/layer/alvr_x86_64.json), because it cannot find `../../../lib64/libalvr_vulkan_layer.so`:
```
pressure-vessel-wrap[9482]: W: Unable to look up resolved path "/app/share/vulkan/explicit_layer.d/../../../lib64/libalvr_vulkan_layer.so" in provider
```

In the Flatpak, the library is located at `/app/utils/alvr/lib64/libalvr_vulkan_layer.so` and not `/app/lib64/libalvr_vulkan_layer.so`.

`sed -i s,../../../lib64/libalvr_vulkan_layer.so,/app/utils/alvr/lib64/libalvr_vulkan_layer.so, /app/share/vulkan/explicit_layer.d/alvr_x86_64.json` executed from within `flatpak enter com.valvesoftware.Steam /bin/bash` makes that error message no longer appear.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

```
❯ sudo inxi -CGmMSz
System:    Kernel: 6.7.7 x86_64 bits: 64 Desktop: KDE Plasma 6.0.0 Distro: NixOS 24.05 (Uakari)
Machine:   Type: Laptop System: ASUSTeK product: ROG Zephyrus G14 GA402RK_GA402RK v: 1.0 serial: <filter>
           Mobo: ASUSTeK model: GA402RK v: 1.0 serial: <filter> UEFI: American Megatrends LLC. v: GA402RK.319 date: 06/06/2023
Memory:    RAM: total: 30.59 GiB used: 17.7 GiB (57.9%)
           Array-1: capacity: 64 GiB slots: 2 EC: None
           Device-1: DIMM 0 size: 16 GiB speed: 4800 MT/s
           Device-2: DIMM 0 size: 16 GiB speed: 4800 MT/s
CPU:       Info: 8-Core model: AMD Ryzen 9 6900HS with Radeon Graphics bits: 64 type: MT MCP cache: L2: 4 MiB
           Speed: 4109 MHz min/max: 400/4935 MHz Core speeds (MHz): 1: 3041 2: 3697 3: 4562 4: 4555 5: 3044 6: 3043 7: 3035
           8: 3529 9: 3063 10: 3042 11: 4566 12: 3287 13: 3039 14: 400 15: 4566 16: 4562
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] driver: amdgpu v: kernel
           Device-2: Advanced Micro Devices [AMD/ATI] Rembrandt [Radeon 680M] driver: amdgpu v: kernel
           Device-3: Quanta USB2.0 HD UVC WebCam type: USB driver: uvcvideo
           Device-4: Logitech C920 HD Pro Webcam type: USB driver: snd-usb-audio,uvcvideo
           Display: server: X.org 1.21.1.11 driver: loaded: amdgpu note: n/a (using device driver)
           resolution: <missing: xdpyinfo>
           OpenGL: renderer: AMD Radeon Graphics (radeonsi rembrandt LLVM 16.0.6 DRM 3.57 6.7.7) v: 4.6 Mesa 24.0.1
```

### Installation

**ALVR Version**: https://github.com/alvr-org/ALVR-nightly/releases/tag/v21.0.0-dev00%2Bnightly.2024.03.25

**ALVR Settings File**:

**SteamVR Version**: 2.4.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**Comment by devurandom** [comment]
Debian appears to have similar issues: https://github.com/alvr-org/ALVR/issues/2124#issuecomment-2111771384

**Comment by The-personified-devil** [comment]
We now package the launcher in the flatpak instead, so this should no longer occur.
