### ISSUE TITLE
SteamVR Boots, but this isn't recognized

### ISSUE THREAD

**Issue by MouseKeyboardController** [alvr-org/ALVR#2048]
## Description
Can't connect to SteamVR, but SteamVR boots. It displays the error message "/home/[user]/.config/openvr/openvrpaths.vrpath does not exist, but SteamVR still boots up perfectly fine. Furthermore, when setting up ALVR, it said that it couldn't edit firewall paths, and never even asked for my sudo password.

### Hardware
Debian 12.0
AMD CPU
NVIDIA GPU (Proprietary Drivers, not Nouveau)

### Installation
**ALVR Version**:
Latest Release

**SteamVR Version**:
Latest Release

**Install Type**:
Packaged

**Comment by TrygveK** [comment]
same
