### ISSUE TITLE
Cant find appimage

### ISSUE THREAD

**Issue by AvenIsHere** [alvr-org/ALVR#2066]
## Description

I cannot find the AppImage for ALVR. The wiki says that if you are on Arch Linux and dont have the flatpak version of Steam, you need to use the AppImage, however i cant find it.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: N/A

**GPU**: N/A

**GPU Driver Version**: N/A

**Audio**: N/A

### Installation 
**ALVR Version**: N/A

**ALVR Settings File**: N/A

**SteamVR Version**: N/A

**Install Type**: N/A
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by kruemmelbande** [comment]
I think appimages for alvr are deprecated now. On arch, just install alvr from the aur.

**Comment by Vixea** [comment]
For flatpak you need to use flatpak steam.
Anyways what's your distro and what dependencies are you missing?

**Comment by infidelus** [comment]
I was just coming back to post that you also need to use the Flatpak version of Steam, which I don't particularly want.  It seems (to me) that removing the Appimage option just means a lot more work getting ALVR setup up as I have no real interest in using Flatpak.  Appimage was simple; you downloaded a file and marked it as executable.  That was it.  Flatpak requires advanced knowledge and a bunch of extra steps.

Linux Mint 21.3 Cinnamon btw.  I can't remember offhand what the dependencies were and am not currently in a position to check.

**Comment by AvenIsHere** [comment]
Yea sadly I can’t use the flatpak, since I use SteamOS, which comes with steam built in.

**Comment by AvenIsHere** [comment]
And SteamOS certainly makes it very difficult to use the AUR

**Comment by Vixea** [comment]
Or you could just install the dependencies

**Comment by infidelus** [comment]
I honestly don't understand why the Appimage was removed.  It was a perfectly good solution and did not require anyone to jump through hoops to get ALVR working.  Add to that that the instructions for building from source don't work/are outdated (which I believe I mentioned some time ago in the Discussion section), and I'm not particularly interested in installing extra dependencies that may or may not work when a single Appimage file was a perfect solution for me.

I wasn't intending this to be an argument on the pros and cons of the various options, just pointing out that removing the Appimage has hindered Linux users (@AvenIsHere for instance) who were relying on ALVR as the solution to PCVR.  While I do have a few PCVR games, most of mine are Quest native so it has less of an effect on me.  Obviously I'd like them all to work but if the developers deem that Appimages are not the future then I guess I just won't play PCVR until another solution is found.

**Comment by AvenIsHere** [comment]
> Or you could just install the dependencies

I believe this would be wiped with every SteamOS update, since SteamOS is immutable. (Correct me if I’m wrong)

**Comment by Vixea** [comment]
That doesn't sound correct but i don't know. I don't use immutable distros and it's not like you have to make it mutable for alvr to work(btw)

**Comment by AnOpenSauceDev** [comment]
I mean, you could just use an older version of ALVR with the appimage, and [aren't the libraries bundled now?](https://github.com/alvr-org/ALVR/pull/2056)

> I believe this would be wiped with every SteamOS update, since SteamOS is immutable. (Correct me if I’m wrong)

It is in fact immutable, but you _can_ revert that by running `sudo steamos-readonly disable`, but do be careful if you choose that route, as you can easily break SteamOS if you don't know what you're doing.

Honestly, if you're trying to use ALVR on the Steam Deck, it's not going to be a fun experience anyways. The GPU is not really capable of driving what in some cases is a 4K+ screen.

**Comment by kruemmelbande** [comment]
Last time i tried to use the aur on steamos it failed to compile at all. It seems to happen with lots and lots of things in the aur so i really think its steamos specific. Even just compiling random projects not from the aur seems to just fail all the time on steamos

**Comment by AvenIsHere** [comment]
> I mean, you could just use an older version of ALVR with the appimage, and [aren't the libraries bundled now?](https://github.com/alvr-org/ALVR/pull/2056)
> 
> > I believe this would be wiped with every SteamOS update, since SteamOS is immutable. (Correct me if I’m wrong)
> 
> It is in fact immutable, but you _can_ revert that by running `sudo steamos-readonly disable`, but do be careful if you choose that route, as you can easily break SteamOS if you don't know what you're doing.
> 
> Honestly, if you're trying to use ALVR on the Steam Deck, it's not going to be a fun experience anyways. The GPU is not really capable of driving what in some cases is a 4K+ screen.

It may not be fun, but it would be better than my current PC, which is really poor when it comes to VR; like to the point that most would consider it unplayable.
Unless they bring back the appimage, I’m probably gonna stick with an old version (like you suggested), cuz yea using the other methods sound like a nightmare on the Steam Deck lol

**Comment by infidelus** [comment]
Same unfortunately, though my PC is actually of a reasonable spec.  If Appimages are permanently gone I'll just keep using an old version for the games that do actually work and then just will have to hope Valve actually get Steam Link working on Linux.

**Comment by Vixea** [comment]
Could someone please do this? https://github.com/alvr-org/ALVR/pull/2056#issuecomment-2051520565
It might actually resolve your issues instead of what you're currently doing

**Comment by infidelus** [comment]
### ldd bin/alvr_dashboard
	linux-vdso.so.1 (0x00007ffda3750000)
	libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x0000718db27cf000)
	libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x0000718db3e16000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x0000718db26cc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000718db26ac000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000718db25c5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000718db2200000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x0000718db25af000)
	/lib64/ld-linux-x86-64.so.2 (0x0000718db3e38000)`

### ldd lib64/alvr/bin/linux64/driver_alvr_server.so
	linux-vdso.so.1 (0x00007ffd95ccb000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007dbcbf200000)
	libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007dbcc081c000)
	libva-x11.so.2 => /lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007dbcc0814000)
	libvdpau.so.1 => /lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007dbcc080e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007dbcc0727000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007dbcc070f000)
	libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x00007dbcc06de000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007dbcbf4c0000)
	libvulkan.so.1 => /lib/x86_64-linux-gnu/libvulkan.so.1 (0x00007dbcbf452000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007dbcbf0fd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007dbcc06be000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007dbcbee00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007dbcc083e000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007dbcc06a7000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007dbcbf44a000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007dbcbf0d3000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007dbcbf444000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007dbcbf43a000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007dbcbf0bb000)
	libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007dbcbf42d000)`

### System
```
Kernel: 6.5.0-27-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Micro-Star product: MS-7C02 v: 1.0 serial: <superuser required>
  Mobo: Micro-Star model: B450 TOMAHAWK MAX (MS-7C02) v: 1.0 serial: <superuser required>
    UEFI: American Megatrends LLC. v: 3.H0 date: 07/07/2023
Battery:
  ID-1: hidpp_battery_1 charge: 64% condition: N/A volts: 3.9 min: N/A
    model: Logitech G903 LIGHTSPEED Wireless Gaming Mouse w/ HERO type: N/A serial: <filter>
    status: Discharging
  Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard K270 serial: <filter>
    charge: 55% (should be ignored) rechargeable: yes status: Discharging
CPU:
  Info: 6-core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP smt: enabled arch: Zen 2 rev: 0
    cache: L1: 384 KiB L2: 3 MiB L3: 32 MiB
  Speed (MHz): avg: 2910 high: 4075 min/max: 2200/4208 boost: enabled cores: 1: 2200 2: 2200
    3: 2200 4: 4075 5: 2718 6: 4068 7: 2200 8: 2200 9: 2200 10: 4075 11: 2717 12: 4074
    bogomips: 86401
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA TU106 [GeForce RTX 2070] vendor: Gigabyte driver: nvidia v: 545.29.06 pcie:
    speed: 2.5 GT/s lanes: 16 ports: active: none off: DP-2 empty: DP-1, DP-3, HDMI-A-1, Unknown-1
    bus-ID: 26:00.0 chip-ID: 10de:1f02 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia gpu: nvidia display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 2560x1440 s-dpi: 110 s-size: 591x352mm (23.3x13.9") s-diag: 688mm (27.1")
  Monitor-1: DP-2 res: 2560x1440 hz: 144 dpi: 109 size: 597x336mm (23.5x13.2") diag: 685mm (27")
  OpenGL: renderer: NVIDIA GeForce RTX 2070/PCIe/SSE2 v: 4.6.0 NVIDIA 545.29.06
    direct render: Yes
Audio:
  Device-1: NVIDIA TU106 High Definition Audio vendor: Gigabyte driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 26:00.1 chip-ID: 10de:10f9 class-ID: 0403
  Device-2: AMD Starship/Matisse HD Audio vendor: Micro-Star MSI driver: snd_hda_intel v: kernel
    pcie: speed: 16 GT/s lanes: 16 bus-ID: 28:00.4 chip-ID: 1022:1487 class-ID: 0403
  Sound Server-1: ALSA v: k6.5.0-27-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: f000 bus-ID: 22:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp34s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Microsoft Xbox 360 Wireless Adapter type: USB driver: xpad bus-ID: 1-7:3
    chip-ID: 045e:0719 class-ID: ff00 serial: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
Drives:
  Local Storage: total: 2.48 TiB used: 1.35 TiB (54.3%)
  ID-1: /dev/nvme0n1 vendor: Western Digital model: WDS100T2B0C-00PXH0 size: 931.51 GiB
    speed: 31.6 Gb/s lanes: 4 type: SSD serial: <filter> rev: 211210WD temp: 36.9 C
  ID-2: /dev/sda vendor: Samsung model: SSD 840 Series size: 232.89 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: AB0Q scheme: GPT
  ID-3: /dev/sdb vendor: Kingston model: SA400S37480G size: 447.13 GiB speed: 6.0 Gb/s type: SSD
    serial: <filter> rev: B1D1 scheme: GPT
  ID-4: /dev/sdc vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 3B6Q scheme: GPT
  ID-5: /dev/sdd vendor: Samsung model: SSD 840 EVO 500GB size: 465.76 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: DB6Q scheme: GPT
Partition:
  ID-1: / size: 93.31 GiB used: 21.71 GiB (23.3%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 486 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
  ID-3: /home size: 133.83 GiB used: 7.55 GiB (5.6%) fs: ext4 dev: /dev/sda3
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 768 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 10 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Microdia Redragon Mitra RGB Keyboard type: Keyboard,Mouse
    driver: hid-generic,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 400mA chip-ID: 0c45:5004
    class-ID: 0301
  Device-2: 1-7:3 info: Microsoft Xbox 360 Wireless Adapter type: WiFi driver: xpad
    interfaces: 8 rev: 2.0 speed: 12 Mb/s power: 260mA chip-ID: 045e:0719 class-ID: ff00
    serial: <filter>
  Device-3: 1-8:4 info: Logitech Unifying Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c52b class-ID: 0300
  Device-4: 1-9:5 info: Logitech USB Receiver type: Keyboard,Mouse,HID
    driver: logitech-djreceiver,usbhid interfaces: 3 rev: 2.0 speed: 12 Mb/s power: 98mA
    chip-ID: 046d:c539 class-ID: 0300
  Device-5: 1-10:6 info: Logitech G29 Driving Force Racing Wheel [PS3] type: HID
    driver: logitech,usbhid interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 200mA chip-ID: 046d:c24f
    class-ID: 0300
  Hub-2: 2-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 3-0:1 info: Hi-speed hub with single TT ports: 2 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-4: 4-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-5: 5-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Hub-6: 6-0:1 info: Super-speed hub ports: 4 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: N/A mobo: N/A gpu: nvidia temp: 52 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 0%
Repos:
  Packages: 2924 apt: 2923 flatpak: 1
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/cdemu-ppa-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/cdemu-ppa-jammy.gpg] https: //ppa.launchpadcontent.net/cdemu/ppa/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/lutris.list
    1: deb https: //download.opensuse.org/repositories/home:/strycore/Debian_11/ ./
  Active apt repos in: /etc/apt/sources.list.d/obsproject-obs-studio-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/obsproject-obs-studio-jammy.gpg] https: //ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //fastly.linuxmint.io virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/signal-xenial.list
    1: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https: //updates.signal.org/desktop/apt xenial main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 417 Uptime: 7h 24m wakeups: 44 Memory: 15.53 GiB used: 5.45 GiB (35.1%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Unknown python3.10 client
  inxi: 3.3.13
```

**Comment by Meister1593** [comment]
AppImage did not include most of runtime dependencies that are actually required while it's running (those being, nvenc (cuda), va-api (mesa), etc), and x264 got bundled anyway.
Only dependencies that are not included into portable tar.gz are those that should be present on pretty much any (if not all) desktops by default (x11, possibly gtk libs, etc, common deps overall)

**Comment by infidelus** [comment]
I have now had a chance to test the portable version and it does seem to work now without extra dependencies (didn't used to), so that's a definite improvement assuming I haven't just forgotten that I installed extras :).

The only minor irritation I see now is, and this isn't purely related to this version as it's been going on for a while, is that I keep getting black windows that I can't close without rebooting when ALVR launches, and every time you relaunch ALVR you seem to get yet another one so you can end up with multiple black windows that don't do anything.

![Screenshot from 2024-04-20 22-26-27](https://github.com/alvr-org/ALVR/assets/39056969/b2b86b3e-565e-4688-a54d-491c9a777f83)

**Comment by Vixea** [comment]
Closing as won't fix, portable works, if you have any more issues make sure it's not the SLR(steam linux runtime) issue and see what's not being linked as suggested in this issue in the new one.
