### ISSUE TITLE
Error building from source code on Linux: failed to run custom build command for alvr_server v20.7.1

### ISSUE THREAD

**Issue by Spartanets174** [alvr-org/ALVR#2067]
## Description
I try build ALVR from source code and on this command `cargo xtask build-streamer --release` i get this error:
error: failed to run custom build command for `alvr_server v20.7.1 (/home/coder/alvr/ALVR-20.7.1/alvr/server)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/coder/alvr/ALVR-20.7.1/target/release/build/alvr_server-b34437a58ddc4a59/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at alvr/server/build.rs:92:9:
  assertion failed: ffmpeg_path.join("include").exists()

How can I fix this?
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**:
Amd ryzen 5 5600x 6-cores

**GPU**:
Nvidia Geforce RTX 3060

### Installation
**ALVR Version**:
ALVR v20.7.1

**Install Type**:
- [x] Source

**OS Name and Version** 
Astra Linux (Orel 2.12.46)

**Comment by Beyley** [comment]
+1

**Comment by The-personified-devil** [comment]
Can you show all commands used to build alvr?

**Comment by unknown321** [comment]
it fails due to missing `deps/linux/ffmpeg/alvr_build` directory
that happens if ffmpeg was downloaded but not built because of some error
you can remove `build` and `deps` directories, install all dependencies and try again
