### ISSUE TITLE
linux build and its crashing. I am not sure why, but this did not happen with the appimage

### ISSUE THREAD

**Issue by guysoft** [alvr-org/ALVR#2070]
## Description
as requested by @Meister1593 opening a separate issue on comment https://github.com/alvr-org/ALVR/pull/2056#issuecomment-2051467589

I downgraded for now to 20.6.1 where alvr does work for me (is there way to hold two versions on Quest 2? )

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=21882b12a8

**CPU**:

AMD Ryzen 9 4900HS with Radeon Graphics 

**GPU**:
TU106M [GeForce RTX 2060 Max-Q]

**GPU Driver Version**:
nvidia 535 (proprietary)
**Audio**:

### Installation
**20.7.1**:

**ALVR Settings File**:

**SteamVR Version**:
2.4.4
**Install Type**:
- [] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ununtu 23.10

might be related to this: https://github.com/alvr-org/ALVR/issues/2068

output of ``ldd bin/alvr_dashboard``:

```
$ ldd bin/alvr_dashboard 
        linux-vdso.so.1 (0x00007ffe4c5f1000)
        libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x00007f17d4328000)
        libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f17d4323000)
        libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007f17d421d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f17d2bdc000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f17d2af1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f17d2800000)
        libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f17d4204000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f17d4396000)
```

output of ``ldd lib64/alvr/bin/linux64/driver_alvr_server.so `` :

```
$ ldd lib64/alvr/bin/linux64/driver_alvr_server.so
        linux-vdso.so.1 (0x00007ffc9c451000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8c60a00000)
        libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f8c61f21000)
        libva-x11.so.2 => /lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007f8c61f19000)
        libvdpau.so.1 => /lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007f8c61f13000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8c60d15000)
        libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f8c61efa000)
        libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x00007f8c61ec9000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f8c608c2000)
        libvulkan.so.1 => /lib/x86_64-linux-gnu/libvulkan.so.1 (0x00007f8c60ca1000)
        libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007f8c607bc000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8c60c7d000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8c60400000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8c61f63000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8c61eb2000)
        libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f8c61eaa000)
        libX11-xcb.so.1 => /lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f8c60c78000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8c60792000)
        libxcb-dri3.so.0 => /lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f8c60c71000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8c6078c000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f8c60784000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f8c6076f000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007f8c60760000)

```

I also installed the flatpak and not sure where that went.

**Comment by AnOpenSauceDev** [comment]
Odd, i have a similar setup (Ryzen Processor, RTX card running proprietary, SteamVR 2.4.4) on an Ubuntu Based OS, but everything works perfectly for me. I wonder if it has anything to do with you running Wayland on Kwin, as I had to drop it for Gnome X11 due to my card hating it. I don't see any wayland natives here, so that might be one reason.

**Comment by guysoft** [comment]
Huh, I don't think I am on wayland:
```
echo "$XDG_SESSION_TYPE"
x11
```

**Comment by AnOpenSauceDev** [comment]
Your hardware probe said Wayland, odd.

**Comment by guysoft** [comment]
Perhaps its wayland only in sddm?
says:
```
KaDE5 (Wayland) - SDDM
```
SDDM is the login manager. perhaps its misreading.

Also tested xeyes. that also works. so its X for sure.

**Comment by guysoft** [comment]
Hey, updating that its fixed, I see that its released in
And guess the cause was this #2108 ALVR v20.8.1
