### ISSUE TITLE
How to run offline steamvr?

### ISSUE THREAD

**Issue by caozero** [alvr-org/ALVR#2080]
Because I developed the UE5vr program myself, there is no need to start steam.

By the way, how long will it take for the Green Screen Chroma Key Passthrough to be available?

**Comment by zarik5** [comment]
There is no readily available offline SteamVR available. Vive maintains offline SteamVR versions, but i think it's a business package.

**Comment by zarik5** [comment]
The chroma key feature is coming soon

**Comment by caozero** [comment]
> There is no readily available offline SteamVR available. Vive maintains offline SteamVR versions, but i think it's a business package.

SteamVR\bin\win64\vrstartup.exe
Is it okay to use?

**Comment by caozero** [comment]
> The chroma key feature is coming soon, but no ETA

hope and wait

**Comment by zarik5** [comment]
> Maybe you can make an additional option to automatically start　 steamVR

There is an option for this towards the end of the settings page
