### ISSUE TITLE
"Game already running" every time I restart SteamVR

### ISSUE THREAD

**Issue by WaveSmashies** [alvr-org/ALVR#2093]
Clicking Restart SteamVR results in "An error occurred while launching this game : Game already running -----"
I'm guessing ALVR is attempting to open SteamVR too quickly after closing it. That's all. It's kinda annoying because you are required to get back out of the headset to fix it if you restart SteamVR at all. All it would need to do is wait 2-4 seconds after closing and before opening SteamVR to fix this issue entirely.

**ALVR Version**:
20.7.1
**SteamVR Version**:
2.4.4

**Comment by guysoft** [comment]
Did you fix it?
