### ISSUE TITLE
PR #2090 Causing 308 Error

### ISSUE THREAD

**Issue by sol8712** [alvr-org/ALVR#2106]
Hi there, after some testing I found that after nightly 4.30.24(as well as on the latest stable) I get a 308 error and am unable to start steamvr. The issue seems to be from PR #2090.
Im on Manjaro linux (arch based) and im installing with the alvr-launcher from the latest nightly.
No relevent log entries in alvr or steam.

Thank you all for your hard work here!

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:
2.4.4 stable
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ X] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Manjaro(arch based)

**Comment by mAd-DaWg** [comment]
is this related to https://github.com/alvr-org/ALVR/issues/2069?

**Comment by sol8712** [comment]
Fixed with ALVR 20.8.1 stable(in Steamvr "previous" branch as stable is currently broken). Thanks!
