### ISSUE TITLE
Dedicated GPU not detected for hardware encoding, CPU encoding not working

### ISSUE THREAD

**Issue by grat2** [alvr-org/ALVR#2118]
## Description

I installed ALVR v20.8.1 from the linux tar.gz and it's not detecting my AMD GPU (hardware encoding not working, software encoding from Intel CPU also not enabled). The stream view in the headset is a black screen. SteamVR is detecting ALVR drivers and shows a headset. 

ALVR log:
10:39:45.383215200 WARN Failed to initialize arboard clipboard: Unknown error while interacting with the clipboard: X11 server connection timed out because it was unreachable
EVENT Session(SessionConfig { server_version: Version { major: 20, minor: 8, patch: 1 }, drivers_backup: None, openvr_config: OpenvrConfig { eye_resolution_width: 1792, eye_resolution_height: 1920, target_eye_resolution_width: 1792, target_eye_resolution_height: 1920, tracking_ref_only: false, enable_vive_tracker_proxy: false, aggressive_keyframe_resend: false, adapter_index: 0, codec: 1, h264_profile: 0, refresh_rate: 90, use_10bit_encoder: false, use_full_range_encoding: true, encoding_gamma: 1.0, enable_hdr: false, force_hdr_srgb_correction: false, clamp_hdr_extended_range: false, enable_pre_analysis: false, enable_vbaq: false, enable_hmqb: false, use_preproc: false, preproc_sigma: 4, preproc_tor: 7, amd_encoder_quality_preset: 1, rate_control_mode: 0, filler_data: false, entropy_coding: 1, force_sw_encoding: false, sw_thread_count: 0, controller_is_tracker: false, controllers_enabled: true, body_tracking_vive_enabled: false, body_tracking_has_legs: false, enable_foveated_encoding: true, foveation_center_size_x: 0.45, foveation_center_size_y: 0.4, foveation_center_shift_x: 0.4, foveation_center_shift_y: 0.1, foveation_edge_ratio_x: 4.0, foveation_edge_ratio_y: 5.0, enable_color_correction: true, brightness: 0.0, contrast: 0.0, saturation: 0.5, gamma: 1.0, sharpening: 0.5, linux_async_compute: false, linux_async_reprojection: false, nvenc_quality_preset: 3, nvenc_tuning_preset: 2, nvenc_multi_pass: 1, nvenc_adaptive_quantization_mode: 1, nvenc_low_delay_key_frame_scale: -1, nvenc_refresh_rate: -1, enable_intra_refresh: false, intra_refresh_period: -1, intra_refresh_count: -1, max_num_ref_frames: -1, gop_length: -1, p_frame_strategy: -1, nvenc_rate_control_mode: -1, rc_buffer_size: -1, rc_initial_delay: -1, rc_max_bitrate: -1, rc_average_bitrate: -1, nvenc_enable_weighted_prediction: false, capture_frame_dir: "", amd_bitrate_corruption_fix: false, _controller_profile: 1 }, client_connections: {"0341.client": ClientConnectionConfig { display_name: "Quest Pro", current_ip: None, manual_ips: {}, trusted: true, connection_state: Disconnected, cabled: false }}, session_settings: SettingsDefault { video: VideoConfigDefault { adapter_index: 0, transcoding_view_resolution: FrameSizeDefault { Scale: 1.0, Absolute: FrameSizeAbsoluteDefault { width: 1800, height: OptionalDefault { set: true, content: 1920 } }, variant: Absolute }, emulated_headset_view_resolution: FrameSizeDefault { Scale: 1.0, Absolute: FrameSizeAbsoluteDefault { width: 1800, height: OptionalDefault { set: true, content: 1920 } }, variant: Absolute }, preferred_fps: 90.0, max_buffering_frames: 2.0, buffering_history_weight: 0.9, optimize_game_render_latency: true, bitrate: BitrateConfigDefault { gui_collapsed: false, mode: BitrateModeDefault { ConstantMbps: 100, Adaptive: BitrateModeAdaptiveDefault { gui_collapsed: true, saturation_multiplier: 0.95, max_bitrate_mbps: SwitchDefault { enabled: false, content: 100 }, min_bitrate_mbps: SwitchDefault { enabled: false, content: 5 }, max_network_latency_ms: SwitchDefault { enabled: false, content: 8 }, encoder_latency_limiter: SwitchDefault { enabled: true, content: EncoderLatencyLimiterDefault { max_saturation_multiplier: 0.9 } }, decoder_latency_limiter: SwitchDefault { enabled: true, content: DecoderLatencyLimiterDefault { gui_collapsed: true, max_decoder_latency_ms: 30, latency_overstep_frames: 90, latency_overstep_multiplier: 0.99 } } }, variant: ConstantMbps }, adapt_to_framerate: SwitchDefault { enabled: true, content: BitrateAdaptiveFramerateConfigDefault { framerate_reset_threshold_multiplier: 2.0 } }, history_size: 256, image_corruption_fix: false }, preferred_codec: CodecTypeDefault { variant: Hevc }, encoder_config: EncoderConfigDefault { gui_collapsed: true, rate_control_mode: RateControlModeDefault { variant: Cbr }, filler_data: false, h264_profile: H264ProfileDefault { variant: High }, entropy_coding: EntropyCodingDefault { variant: Cavlc }, use_10bit: false, use_full_range: true, encoding_gamma: 1.0, enable_hdr: false, force_hdr_srgb_correction: false, clamp_hdr_extended_range: false, nvenc: NvencConfigDefault { gui_collapsed: true, quality_preset: EncoderQualityPresetNvidiaDefault { variant: P3 }, tuning_preset: NvencTuningPresetDefault { variant: LowLatency }, multi_pass: NvencMultiPassDefault { variant: QuarterResolution }, adaptive_quantization_mode: NvencAdaptiveQuantizationModeDefault { variant: Spatial }, low_delay_key_frame_scale: -1, refresh_rate: -1, enable_intra_refresh: false, intra_refresh_period: -1, intra_refresh_count: -1, max_num_ref_frames: -1, gop_length: -1, p_frame_strategy: -1, rate_control_mode: -1, rc_buffer_size: -1, rc_initial_delay: -1, rc_max_bitrate: -1, rc_average_bitrate: -1, enable_weighted_prediction: false }, amf: AmfConfigDefault { gui_collapsed: true, quality_preset: EncoderQualityPresetAmdDefault { variant: Balanced }, enable_vbaq: false, enable_hmqb: false, use_preproc: false, preproc_sigma: 4, preproc_tor: 7, enable_pre_analysis: false }, software: SoftwareEncodingConfigDefault { force_software_encoding: false, thread_count: 0 } }, force_software_decoder: false, mediacodec_extra_options: DictionaryDefault { gui_collapsed: true, key: "", value: MediacodecDataTypeDefault { Float: 0.0, Int32: 0, Int64: 0, String: "", variant: Int32 }, content: [("operating-rate", MediacodecDataTypeDefault { Float: 0.0, Int32: 2147483647, Int64: 0, String: "", variant: Int32 }), ("priority", MediacodecDataTypeDefault { Float: 0.0, Int32: 0, Int64: 0, String: "", variant: Int32 }), ("vendor.qti-ext-dec-low-latency.enable", MediacodecDataTypeDefault { Float: 0.0, Int32: 1, Int64: 0, String: "", variant: Int32 })] }, foveated_encoding: SwitchDefault { enabled: true, content: FoveatedEncodingConfigDefault { gui_collapsed: true, force_enable: false, center_size_x: 0.45, center_size_y: 0.4, center_shift_x: 0.4, center_shift_y: 0.1, edge_ratio_x: 4.0, edge_ratio_y: 5.0 } }, clientside_foveation: SwitchDefault { enabled: true, content: ClientsideFoveationConfigDefault { gui_collapsed: true, mode: ClientsideFoveationModeDefault { Static: ClientsideFoveationModeStaticDefault { level: ClientsideFoveationLevelDefault { variant: High } }, Dynamic: ClientsideFoveationModeDynamicDefault { max_level: ClientsideFoveationLevelDefault { variant: High } }, variant: Dynamic }, vertical_offset_deg: 0.0 } }, color_correction: SwitchDefault { enabled: true, content: ColorCorrectionConfigDefault { gui_collapsed: false, brightness: 0.0, contrast: 0.0, saturation: 0.5, gamma: 1.0, sharpening: 0.5 } } }, audio: AudioConfigDefault { linux_backend: LinuxAudioBackendDefault { variant: Alsa }, game_audio: SwitchDefault { enabled: true, content: GameAudioConfigDefault { gui_collapsed: false, device: OptionalDefault { set: false, content: CustomAudioDeviceConfigDefault { NameSubstring: "pipewire", Index: 0, variant: NameSubstring } }, mute_when_streaming: true, buffering: AudioBufferingConfigDefault { gui_collapsed: true, average_buffering_ms: 50, batch_ms: 10 } } }, microphone: SwitchDefault { enabled: true, content: MicrophoneConfigDefault { gui_collapsed: false, devices: MicrophoneDevicesConfigDefault { Custom: MicrophoneDevicesConfigCustomDefault { sink: CustomAudioDeviceConfigDefault { NameSubstring: "default", Index: 0, variant: NameSubstring }, source: CustomAudioDeviceConfigDefault { NameSubstring: "default", Index: 0, variant: NameSubstring } }, variant: Custom }, buffering: AudioBufferingConfigDefault { gui_collapsed: true, average_buffering_ms: 50, batch_ms: 10 } } } }, headset: HeadsetConfigDefault { emulation_mode: HeadsetEmulationModeDefault { Custom: HeadsetEmulationModeCustomDefault { serial_number: "Unknown" }, variant: Quest2 }, extra_openvr_props: VectorDefault { gui_collapsed: true, element: OpenvrPropertyDefault { TrackingSystemName: "", ModelNumber: "", SerialNumber: "", RenderModelName: "", WillDriftInYaw: false, ManufacturerName: "", TrackingFirmwareVersion: "", HardwareRevisionString: "", AllWirelessDongleDescriptions: "", ConnectedWirelessDongle: "", DeviceIsWireless: false, DeviceIsCharging: false, DeviceBatteryPercentage: 0.0, FirmwareUpdateAvailable: false, FirmwareManualUpdate: false, FirmwareManualUpdateURL: "", HardwareRevisionUint64: 0, FirmwareVersion: 0, FPGAVersion: 0, VRCVersion: 0, RadioVersion: 0, DongleVersion: 0, BlockServerShutdown: false, CanUnifyCoordinateSystemWithHmd: false, ContainsProximitySensor: false, DeviceProvidesBatteryStatus: false, DeviceCanPowerOff: false, FirmwareProgrammingTarget: "", DeviceClass: 0, HasCamera: false, DriverVersion: "", FirmwareForceUpdateRequired: false, ViveSystemButtonFixRequired: false, ParentDriver: 0, ResourceRoot: "", RegisteredDeviceType: "", InputProfilePath: "", NeverTracked: false, NumCameras: 0, CameraFrameLayout: 0, CameraStreamFormat: 0, AdditionalDeviceSettingsPath: "", Identifiable: false, BootloaderVersion: 0, AdditionalSystemReportData: "", CompositeFirmwareVersion: "", FirmwareRemindUpdate: false, PeripheralApplicationVersion: 0, ManufacturerSerialNumber: "", ComputedSerialNumber: "", EstimatedDeviceFirstUseTime: 0, ReportsTimeSinceVSync: false, SecondsFromVsyncToPhotons: 0.0, DisplayFrequency: 0.0, UserIpdMeters: 0.0, CurrentUniverseId: 0, PreviousUniverseId: 0, DisplayFirmwareVersion: 0, IsOnDesktop: false, DisplayMCType: 0, DisplayMCOffset: 0.0, DisplayMCScale: 0.0, EdidVendorID: 0, DisplayMCImageLeft: "", DisplayMCImageRight: "", DisplayGCBlackClamp: 0.0, EdidProductID: 0, DisplayGCType: 0, DisplayGCOffset: 0.0, DisplayGCScale: 0.0, DisplayGCPrescale: 0.0, DisplayGCImage: "", LensCenterLeftU: 0.0, LensCenterLeftV: 0.0, LensCenterRightU: 0.0, LensCenterRightV: 0.0, UserHeadToEyeDepthMeters: 0.0, CameraFirmwareVersion: 0, CameraFirmwareDescription: "", DisplayFPGAVersion: 0, DisplayBootloaderVersion: 0, DisplayHardwareVersion: 0, AudioFirmwareVersion: 0, CameraCompatibilityMode: 0, ScreenshotHorizontalFieldOfViewDegrees: 0.0, ScreenshotVerticalFieldOfViewDegrees: 0.0, DisplaySuppressed: false, DisplayAllowNightMode: false, DisplayMCImageWidth: 0, DisplayMCImageHeight: 0, DisplayMCImageNumChannels: 0, SecondsFromPhotonsToVblank: 0.0, DriverDirectModeSendsVsyncEvents: false, DisplayDebugMode: false, GraphicsAdapterLuid: 0, DriverProvidedChaperonePath: "", ExpectedTrackingReferenceCount: 0, ExpectedControllerCount: 0, NamedIconPathControllerLeftDeviceOff: "", NamedIconPathControllerRightDeviceOff: "", NamedIconPathTrackingReferenceDeviceOff: "", DoNotApplyPrediction: false, DistortionMeshResolution: 0, DriverIsDrawingControllers: false, DriverRequestsApplicationPause: false, DriverRequestsReducedRendering: false, MinimumIpdStepMeters: 0.0, AudioBridgeFirmwareVersion: 0, ImageBridgeFirmwareVersion: 0, ImuFactoryGyroBias: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryGyroScale: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryAccelerometerBias: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryAccelerometerScale: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ConfigurationIncludesLighthouse20Features: false, AdditionalRadioFeatures: 0, ExpectedControllerType: "", HmdTrackingStyle: 0, DriverProvidedChaperoneVisibility: false, HmdColumnCorrectionSettingPrefix: "", CameraSupportsCompatibilityModes: false, SupportsRoomViewDepthProjection: false, DisplaySupportsMultipleFramerates: false, DisplayColorMultLeft: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, DisplayColorMultRight: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, DisplaySupportsRuntimeFramerateChange: false, DisplaySupportsAnalogGain: false, DisplayMinAnalogGain: 0.0, DisplayMaxAnalogGain: 0.0, DashboardScale: 0.0, IpdUIRangeMinMeters: 0.0, IpdUIRangeMaxMeters: 0.0, HmdSupportsHDCP14LegacyCompat: false, HmdSupportsMicMonitoring: false, DriverRequestedMuraCorrectionMode: 0, DriverRequestedMuraFeatherInnerLeft: 0, DriverRequestedMuraFeatherInnerRight: 0, DriverRequestedMuraFeatherInnerTop: 0, DriverRequestedMuraFeatherInnerBottom: 0, DriverRequestedMuraFeatherOuterLeft: 0, DriverRequestedMuraFeatherOuterRight: 0, DriverRequestedMuraFeatherOuterTop: 0, DriverRequestedMuraFeatherOuterBottom: 0, AudioDefaultPlaybackDeviceId: "", AudioDefaultRecordingDeviceId: "", AudioDefaultPlaybackDeviceVolume: 0.0, AudioSupportsDualSpeakerAndJackOutput: false, AttachedDeviceId: "", SupportedButtons: 0, Axis0Type: 0, Axis1Type: 0, Axis2Type: 0, Axis3Type: 0, Axis4Type: 0, ControllerRoleHint: 0, FieldOfViewLeftDegrees: 0.0, FieldOfViewRightDegrees: 0.0, FieldOfViewTopDegrees: 0.0, FieldOfViewBottomDegrees: 0.0, TrackingRangeMinimumMeters: 0.0, TrackingRangeMaximumMeters: 0.0, ModeLabel: "", CanWirelessIdentify: false, Nonce: 0, IconPathName: "", NamedIconPathDeviceOff: "", NamedIconPathDeviceSearching: "", NamedIconPathDeviceSearchingAlert: "", NamedIconPathDeviceReady: "", NamedIconPathDeviceReadyAlert: "", NamedIconPathDeviceNotReady: "", NamedIconPathDeviceStandby: "", NamedIconPathDeviceAlertLow: "", NamedIconPathDeviceStandbyAlert: "", OverrideContainer: 0, UserConfigPath: "", InstallPath: "", HasDisplayComponent: false, HasControllerComponent: false, HasCameraComponent: false, HasDriverDirectModeComponent: false, HasVirtualDisplayComponent: false, HasSpatialAnchorsSupport: false, ControllerType: "", ControllerHandSelectionPriority: 0, variant: TrackingSystemName }, content: [] }, tracking_ref_only: false, enable_vive_tracker_proxy: false, face_tracking: SwitchDefault { enabled: true, content: FaceTrackingConfigDefault { gui_collapsed: true, sources: FaceTrackingSourcesConfigDefault { combined_eye_gaze: true, eye_tracking_fb: true, face_tracking_fb: true, eye_expressions_htc: true, lip_expressions_htc: true }, sink: FaceTrackingSinkConfigDefault { VrchatEyeOsc: FaceTrackingSinkConfigVrchatEyeOscDefault { port: 9000 }, variant: VrcFaceTracking } } }, body_tracking: SwitchDefault { enabled: false, content: BodyTrackingConfigDefault { gui_collapsed: true, sources: BodyTrackingSourcesConfigDefault { body_tracking_full_body_meta: SwitchDefault { enabled: true, content: BodyTrackingFullBodyMETAConfigDefault { gui_collapsed: true, enable_full_body: true } } }, sink: BodyTrackingSinkConfigDefault { VrchatBodyOsc: BodyTrackingSinkConfigVrchatBodyOscDefault { port: 9000 }, variant: FakeViveTracker }, tracked: true } }, controllers: SwitchDefault { enabled: true, content: ControllersConfigDefault { gui_collapsed: false, tracked: true, enable_skeleton: true, emulation_mode: ControllersEmulationModeDefault { Custom: ControllersEmulationModeCustomDefault { serial_number: "ALVR Controller", button_set: VectorDefault { gui_collapsed: false, element: "/user/hand/left/input/a/click", content: [] } }, variant: Quest2Touch }, extra_openvr_props: VectorDefault { gui_collapsed: true, element: OpenvrPropertyDefault { TrackingSystemName: "", ModelNumber: "", SerialNumber: "", RenderModelName: "", WillDriftInYaw: false, ManufacturerName: "", TrackingFirmwareVersion: "", HardwareRevisionString: "", AllWirelessDongleDescriptions: "", ConnectedWirelessDongle: "", DeviceIsWireless: false, DeviceIsCharging: false, DeviceBatteryPercentage: 0.0, FirmwareUpdateAvailable: false, FirmwareManualUpdate: false, FirmwareManualUpdateURL: "", HardwareRevisionUint64: 0, FirmwareVersion: 0, FPGAVersion: 0, VRCVersion: 0, RadioVersion: 0, DongleVersion: 0, BlockServerShutdown: false, CanUnifyCoordinateSystemWithHmd: false, ContainsProximitySensor: false, DeviceProvidesBatteryStatus: false, DeviceCanPowerOff: false, FirmwareProgrammingTarget: "", DeviceClass: 0, HasCamera: false, DriverVersion: "", FirmwareForceUpdateRequired: false, ViveSystemButtonFixRequired: false, ParentDriver: 0, ResourceRoot: "", RegisteredDeviceType: "", InputProfilePath: "", NeverTracked: false, NumCameras: 0, CameraFrameLayout: 0, CameraStreamFormat: 0, AdditionalDeviceSettingsPath: "", Identifiable: false, BootloaderVersion: 0, AdditionalSystemReportData: "", CompositeFirmwareVersion: "", FirmwareRemindUpdate: false, PeripheralApplicationVersion: 0, ManufacturerSerialNumber: "", ComputedSerialNumber: "", EstimatedDeviceFirstUseTime: 0, ReportsTimeSinceVSync: false, SecondsFromVsyncToPhotons: 0.0, DisplayFrequency: 0.0, UserIpdMeters: 0.0, CurrentUniverseId: 0, PreviousUniverseId: 0, DisplayFirmwareVersion: 0, IsOnDesktop: false, DisplayMCType: 0, DisplayMCOffset: 0.0, DisplayMCScale: 0.0, EdidVendorID: 0, DisplayMCImageLeft: "", DisplayMCImageRight: "", DisplayGCBlackClamp: 0.0, EdidProductID: 0, DisplayGCType: 0, DisplayGCOffset: 0.0, DisplayGCScale: 0.0, DisplayGCPrescale: 0.0, DisplayGCImage: "", LensCenterLeftU: 0.0, LensCenterLeftV: 0.0, LensCenterRightU: 0.0, LensCenterRightV: 0.0, UserHeadToEyeDepthMeters: 0.0, CameraFirmwareVersion: 0, CameraFirmwareDescription: "", DisplayFPGAVersion: 0, DisplayBootloaderVersion: 0, DisplayHardwareVersion: 0, AudioFirmwareVersion: 0, CameraCompatibilityMode: 0, ScreenshotHorizontalFieldOfViewDegrees: 0.0, ScreenshotVerticalFieldOfViewDegrees: 0.0, DisplaySuppressed: false, DisplayAllowNightMode: false, DisplayMCImageWidth: 0, DisplayMCImageHeight: 0, DisplayMCImageNumChannels: 0, SecondsFromPhotonsToVblank: 0.0, DriverDirectModeSendsVsyncEvents: false, DisplayDebugMode: false, GraphicsAdapterLuid: 0, DriverProvidedChaperonePath: "", ExpectedTrackingReferenceCount: 0, ExpectedControllerCount: 0, NamedIconPathControllerLeftDeviceOff: "", NamedIconPathControllerRightDeviceOff: "", NamedIconPathTrackingReferenceDeviceOff: "", DoNotApplyPrediction: false, DistortionMeshResolution: 0, DriverIsDrawingControllers: false, DriverRequestsApplicationPause: false, DriverRequestsReducedRendering: false, MinimumIpdStepMeters: 0.0, AudioBridgeFirmwareVersion: 0, ImageBridgeFirmwareVersion: 0, ImuFactoryGyroBias: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryGyroScale: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryAccelerometerBias: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ImuFactoryAccelerometerScale: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, ConfigurationIncludesLighthouse20Features: false, AdditionalRadioFeatures: 0, ExpectedControllerType: "", HmdTrackingStyle: 0, DriverProvidedChaperoneVisibility: false, HmdColumnCorrectionSettingPrefix: "", CameraSupportsCompatibilityModes: false, SupportsRoomViewDepthProjection: false, DisplaySupportsMultipleFramerates: false, DisplayColorMultLeft: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, DisplayColorMultRight: ArrayDefault { gui_collapsed: false, content: [0.0, 0.0, 0.0] }, DisplaySupportsRuntimeFramerateChange: false, DisplaySupportsAnalogGain: false, DisplayMinAnalogGain: 0.0, DisplayMaxAnalogGain: 0.0, DashboardScale: 0.0, IpdUIRangeMinMeters: 0.0, IpdUIRangeMaxMeters: 0.0, HmdSupportsHDCP14LegacyCompat: false, HmdSupportsMicMonitoring: false, DriverRequestedMuraCorrectionMode: 0, DriverRequestedMuraFeatherInnerLeft: 0, DriverRequestedMuraFeatherInnerRight: 0, DriverRequestedMuraFeatherInnerTop: 0, DriverRequestedMuraFeatherInnerBottom: 0, DriverRequestedMuraFeatherOuterLeft: 0, DriverRequestedMuraFeatherOuterRight: 0, DriverRequestedMuraFeatherOuterTop: 0, DriverRequestedMuraFeatherOuterBottom: 0, AudioDefaultPlaybackDeviceId: "", AudioDefaultRecordingDeviceId: "", AudioDefaultPlaybackDeviceVolume: 0.0, AudioSupportsDualSpeakerAndJackOutput: false, AttachedDeviceId: "", SupportedButtons: 0, Axis0Type: 0, Axis1Type: 0, Axis2Type: 0, Axis3Type: 0, Axis4Type: 0, ControllerRoleHint: 0, FieldOfViewLeftDegrees: 0.0, FieldOfViewRightDegrees: 0.0, FieldOfViewTopDegrees: 0.0, FieldOfViewBottomDegrees: 0.0, TrackingRangeMinimumMeters: 0.0, TrackingRangeMaximumMeters: 0.0, ModeLabel: "", CanWirelessIdentify: false, Nonce: 0, IconPathName: "", NamedIconPathDeviceOff: "", NamedIconPathDeviceSearching: "", NamedIconPathDeviceSearchingAlert: "", NamedIconPathDeviceReady: "", NamedIconPathDeviceReadyAlert: "", NamedIconPathDeviceNotReady: "", NamedIconPathDeviceStandby: "", NamedIconPathDeviceAlertLow: "", NamedIconPathDeviceStandbyAlert: "", OverrideContainer: 0, UserConfigPath: "", InstallPath: "", HasDisplayComponent: false, HasControllerComponent: false, HasCameraComponent: false, HasDriverDirectModeComponent: false, HasVirtualDisplayComponent: false, HasSpatialAnchorsSupport: false, ControllerType: "", ControllerHandSelectionPriority: 0, variant: TrackingSystemName }, content: [] }, button_mappings: OptionalDefault { set: false, content: DictionaryDefault { gui_collapsed: false, key: "/user/hand/left/input/a/click", value: VectorDefault { gui_collapsed: false, element: ButtonBindingTargetDefault { destination: "/user/hand/left/input/a/click", mapping_type: ButtonMappingTypeDefault { HysteresisThreshold: HysteresisThresholdDefault { value: 0.5, deviation: 0.05 }, BinaryToScalar: BinaryToScalarStatesDefault { off: 0.0, on: 1.0 }, Remap: RangeDefault { min: 0.0, max: 1.0 }, variant: Passthrough }, binary_conditions: VectorDefault { gui_collapsed: true, element: "/user/hand/left/input/trigger/touch", content: [] } }, content: [] }, content: [] } }, button_mapping_config: AutomaticButtonMappingConfigDefault { gui_collapsed: true, click_threshold: HysteresisThresholdDefault { value: 0.5, deviation: 0.05 }, touch_threshold: HysteresisThresholdDefault { value: 0.1, deviation: 0.05 }, force_threshold: 0.8 }, gestures: SwitchDefault { enabled: true, content: HandGestureConfigDefault { gui_collapsed: true, only_touch: true, pinch_touch_distance: 0.0, pinch_trigger_distance: 0.25, curl_touch_distance: 2.0, curl_trigger_distance: 2.5, joystick_deadzone: 40.0, joystick_offset_horizontal: 0.0, joystick_offset_vertical: 0.0, joystick_range: 1.0, activation_delay: 50, deactivation_delay: 100, repeat_delay: 100 } }, steamvr_pipeline_frames: 3.0, linear_velocity_cutoff: 0.05, angular_velocity_cutoff: 10.0, left_controller_position_offset: ArrayDefault { gui_collapsed: true, content: [0.0, 0.0, -0.11] }, left_controller_rotation_offset: ArrayDefault { gui_collapsed: true, content: [-20.0, 0.0, 0.0] }, left_hand_tracking_position_offset: ArrayDefault { gui_collapsed: true, content: [0.04, -0.02, -0.13] }, left_hand_tracking_rotation_offset: ArrayDefault { gui_collapsed: true, content: [0.0, -45.0, -90.0] }, haptics: SwitchDefault { enabled: true, content: HapticsConfigDefault { gui_collapsed: true, intensity_multiplier: 1.0, amplitude_curve: 1.0, min_duration_s: 0.01 } } } }, position_recentering_mode: PositionRecenteringModeDefault { Local: PositionRecenteringModeLocalDefault { view_height: 1.5 }, variant: LocalFloor }, rotation_recentering_mode: RotationRecenteringModeDefault { variant: Yaw } }, connection: ConnectionConfigDefault { stream_protocol: SocketProtocolDefault { variant: Udp }, client_discovery: SwitchDefault { enabled: true, content: DiscoveryConfigDefault { auto_trust_clients: false } }, stream_port: 9944, web_server_port: 8082, osc_local_port: 9942, dscp: OptionalDefault { set: false, content: DscpTosDefault { ClassSelector: 7, AssuredForwarding: DscpTosAssuredForwardingDefault { class: 4, drop_probability: DropProbabilityDefault { variant: Low } }, variant: ExpeditedForwarding } }, server_send_buffer_bytes: SocketBufferSizeDefault { Custom: 100000, variant: Maximum }, server_recv_buffer_bytes: SocketBufferSizeDefault { Custom: 100000, variant: Maximum }, client_send_buffer_bytes: SocketBufferSizeDefault { Custom: 100000, variant: Maximum }, client_recv_buffer_bytes: SocketBufferSizeDefault { Custom: 100000, variant: Maximum }, max_queued_server_video_frames: 1024, avoid_video_glitching: false, aggressive_keyframe_resend: false, on_connect_script: "/home/gfox/.config/alvr/audio-setup.sh", on_disconnect_script: "/home/gfox/.config/alvr/audio-setup.sh", packet_size: 1400, statistics_history_size: 256 }, extra: ExtraConfigDefault { logging: LoggingConfigDefault { gui_collapsed: false, client_log_report_level: SwitchDefault { enabled: true, content: LogSeverityDefault { variant: Error } }, log_to_disk: false, log_tracking: false, log_button_presses: false, log_haptics: false, notification_level: LogSeverityDefault { variant: Warning }, show_raw_events: SwitchDefault { enabled: false, content: RawEventsConfigDefault { hide_spammy_events: false } }, prefer_backtrace: false, show_notification_tip: true }, steamvr_launcher: SteamvrLauncherDefault { gui_collapsed: false, driver_launch_action: DriverLaunchActionDefault { variant: UnregisterOtherDriversAtStartup }, open_close_steamvr_with_dashboard: false }, capture: CaptureConfigDefault { gui_collapsed: false, startup_video_recording: false, rolling_video_files: SwitchDefault { enabled: false, content: RollingVideoFilesConfigDefault { duration_s: 5 } }, capture_frame_dir: "" }, patches: PatchesDefault { gui_collapsed: false, linux_async_compute: false, linux_async_reprojection: false }, open_setup_wizard: false } } })
10:39:57.205896719 INFO GPU Encoder vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.1.5 ()
10:39:57.205909849 ERROR Couldn't find H264 profile. You unlikely to have hardware encoding for it.
10:39:57.205911697 ERROR Couldn't find HEVC profile. You unlikely to have hardware encoding for it.
10:39:57.205913132 INFO AV1 profile does not contain encoding entrypoint. You unlikely to have hardware encoding for it.
10:39:57.207455977 INFO GPU Encoder vendor: Intel iHD driver for Intel(R) Gen Graphics - 24.1.5 ()
10:39:57.207462237 ERROR Couldn't find H264 profile. You unlikely to have hardware encoding for it.
10:39:57.207463965 ERROR Couldn't find HEVC profile. You unlikely to have hardware encoding for it.
10:39:57.207465469 INFO AV1 profile does not contain encoding entrypoint. You unlikely to have hardware encoding for it.
10:40:05.475751991 INFO Server connected

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [polygraphene's ALVR GitHub Wiki](https://github.com/polygraphene/ALVR/wiki) and [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
Quest Pro

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
[HW Probe Results](https://linux-hardware.org/?probe=696f24aed0)

**CPU**:
Intel i7 12700k

**GPU**:
AMD Radeon RX 6900 XT

**GPU Driver Version**:
amdgpu 24.0.6

**Audio**:
Pipewire

### Installation
**ALVR Version**:
20.8.1

**ALVR Settings File**:

**SteamVR Version**: 
2.5.4

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`tar.gz`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Fedora Linux 40 (KDE Plasma)

**Comment by Wyfi0** [comment]
Have you tried setting LIBVA_DRIVER_NAME=radeonsi to specify the driver? This works for me on arch with amd gpu.

**Comment by grat2** [comment]
Closing issue, found out that because I have an iGPU in my Intel processor (with no drivers installed, see GPU encoder vendor lines near the end), ALVR was prioritizing using that for encoding. I disabled the iGPU in BIOS and it looks like ALVR is working now.
