### ISSUE TITLE
Issues installing flatpak

### ISSUE THREAD

**Issue by SunnyOd** [alvr-org/ALVR#2127]
After downloading the flatpak and trying to install it, it succeeds but fails when I try to run it:

```
sunny@nobara# flatpak install com.valvesoftware.Steam.Utility.alvr.flatpak

        ID                                               Branch            Op            Remote                  Download
 1. [|] com.valvesoftware.Steam.Utility.alvr             stable            i             alvr4-origin            0 bytes

Installing…

        ID                                               Branch            Op            Remote                  Download
 1. [✓] com.valvesoftware.Steam.Utility.alvr             stable            i             alvr5-origin            0 bytes

Installation complete.
/tmp
sunny@nobara# flatpak run com.valvesoftware.Steam.Utility.alvr
bwrap: execvp /bin/sh: No such file or directory
```
## Environment
Nobara (fedora 39), kernel `6.8.7-201.fsync.fc39.x86_64`

### Hardware
nvidia 3090 + AMD 5900x + 64GB RAM. Lots of disk space where flatpak is installed on root or home

Nvidia driver 550.67
ALVR version 20.8.1

---

Btw, any plans to add this to Flathub?

**Comment by toasterrepairman** [comment]
Also seeing this issue on NixOS. Flatpak installs fine, but doesn't register any runnable in my deskop or in the terminal.

**Comment by tobico** [comment]
I'm also experiencing this issue on Ubuntu 24.04.

**Comment by VoidSentient** [comment]
Experiencing on Mint 21.3 as well. No instructions for Flatpak could be found on my end at https://github.com/alvr-org/ALVR/wiki/Flatpak

**Comment by raviboth** [comment]
experiencing this on Bazzite-nvidia as well

**Comment by Meister1593** [comment]
Not sure if it's related, but soon #2207 will be done and might be better way to use it instead of current flatpak, also should work with nvidia
