### ISSUE TITLE
Controller buttons stay pressed/touched forever (refactor regression)

### ISSUE THREAD

**Issue by abb128** [alvr-org/ALVR#2140]
On/after the latest commit 71185e2cd2dbd5cfb318e77354af7174a38b6732, when I press or touch a controller button it stays pressed or touched forever (checked with the test controllers option in steamvr settings). It also happens with 05ccaf32a7e42be2659268e277f5b9d781699f24. The issue does not occur if I use 1a1220aaec20cd136451a1350310830555923d2a. I am running on Arch Linux with a Quest 3

**Comment by The-personified-devil** [comment]
Does your issue persist after 08370b0?

**Comment by l33tlinuxh4x0r** [comment]
I too was having this issue with Nightly builds.. It has however been fixed.
