### ISSUE TITLE
ALVR not displaying to quest 2 Linux mint

### ISSUE THREAD

**Issue by Uefi-celes** [alvr-org/ALVR#2145]
## Description
I had to reinstall alvr and now when my headset connects it goes black

## General Troubleshooting
I see that this is a known problem with the newer Linux versions, But downgrading steam does nothing. 

## Environment
Linux mint 21.3
Linux kernel 6.5.0-35
### Hardware

Ryzen 7 5800x

Nvidia 4060ti

545

disabled

### Installation
6.8.1

**ALVR Settings File**:

2.4, 2.5,2.6

**Install Type**:

- [ ] Portable (`zip`)

PRETTY_NAME="Linux Mint 21.3"

**Comment by FoxbitDreamtail** [comment]
Same issue here including nightly, I even went through the hassle of installing pipe wire at one point to try getting audio working and it worked for a little bit but everything stopped working the instant I decided to try updating to the non-appimage version of alvr...

**Comment by Jackrenders** [comment]
same here, i use alvr v20.6.1 appimage

**Comment by zggzcgy** [comment]
I'm guessing this might be related to the SteamVR update, and it's recommended to follow [#2115](https://github.com/alvr-org/ALVR/issues/2115#issuecomment-2104671308) to try and verify if it's available.

**Comment by Uefi-celes** [comment]
I got it to work, follow the guide zggzcyg linked and don’t forget to force compatibility after you use the guide, I forgot to which led me here.
