### ISSUE TITLE
Quest games on alvr+steam when???

### ISSUE THREAD

**Issue by KrispTheCocoNut** [alvr-org/ALVR#2154]
is there any way you guys could make it so using steamVR with alvr would work with quest pc games??? 

i bought some games on the meta quest link and i cant play them because alvr only supports steamvr and it dosnt let u use the controllers if u launch it while in steamVR.

(i have virtual desktop which uses steamVR to play the quest games but imo virtual desktop is kinda bad compared to alvr bc less performance options for my potato pc)

**Comment by Not-Shadow** [comment]
Isn't this what [Revive](https://github.com/LibreVR/Revive) was made for? To play Meta Quest Link titles through SteamVR?

**Comment by Vixea** [comment]
It's not the goal of this project. It's simply a pcvr to standalone streamer
