### ISSUE TITLE
ALVR has a generic application icon on quest 3

### ISSUE THREAD

**Issue by l33tlinuxh4x0r** [alvr-org/ALVR#2157]
ALVR has a generic icon on quest 3 instead of the ALVR icon when looking at the app in quest 3 tray area.

**Comment by The-personified-devil** [comment]
The applab release features the icon now so I don't know how relevant this is

**Comment by l33tlinuxh4x0r** [comment]
I believe that this can be closed now as the Applab/meta store version is out now and the icon works in that version.
