### ISSUE TITLE
ALVR installer not appearing under assets on the latest download page? 

### ISSUE THREAD

**Issue by pingholm** [alvr-org/ALVR#2158]
Hi everyone! 

I cannot seem to find the AlVR installer under latest download page? I have also tried looking under nightly releases but it does not appear. I am using Windows 11. Perhaps, I need to look elsewhere? 

![Skærmbillede 2024-05-30 104059](https://github.com/alvr-org/ALVR/assets/168178669/392623ae-a2ef-4e0b-9067-561d1265997e)

**Comment by pingholm** [comment]
![Skærmbillede 2024-05-30 104829_001](https://github.com/alvr-org/ALVR/assets/168178669/66c4b38f-7a06-43e3-ae8f-a957aedcfc2a)

**Comment by zarik5** [comment]
The installer is deprecated and removed. You should download the zip file

**Comment by pingholm** [comment]
Okay thank you for your reply, so double checking the only thing I am getting is the dashboard app, license and bin folder. Is this correct? 

Because when I try launch SteamVR through ALVR it does nothing but disappears completely and when trying to reopen it I have to go through the set up wizard again, like starting over. I find this very strange. Sorry for my extended questions, I am very new to this, I have been trying to get it to work for two days now. However I cannot seem to connect to the Oculus Quest 2.
