### ISSUE TITLE
Keep getting Cannot find audio device which name contains "pipewire"

### ISSUE THREAD

**Issue by NitroDIon** [alvr-org/ALVR#2160]
## Description
Every time I try and use ALVR with my Quest 2 Headset I keep getting the Cannot find audio device which name contains "pipewire" even though I am using pipewire
As a note i have tried both stable and nightly versions.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [polygraphene's ALVR GitHub Wiki](https://github.com/polygraphene/ALVR/wiki) and [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
- X11

### Hardware
**CPU**:
Intel Core i7-10700k
**GPU**:
Nvidia RTX 3050
**GPU Driver Version**:
Nvidia 545.29.06
**Audio**:
PulseAudio (on PipeWire 1.0.7)
### Installation
**ALVR Version**:
v21.0.0-dev01+nightly.2024.05.31
**ALVR Settings File**:
[Patebin to make post not a massive wall of text](https://pastebin.com/kqKawkCd)
**SteamVR Version**:
SteamVR Version 2.5.5
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Linux Mint 21.3

Note: sorry if i've filed this out wrong this is my first time filling out a report like this

**Comment by l33tlinuxh4x0r** [comment]
Try using "system default" instead of pipewire

![image](https://github.com/alvr-org/ALVR/assets/1632838/b24bebbd-ef0d-4fce-8352-a29db49d823a)

**Comment by NitroDIon** [comment]
this worked however now i'm getting an issue with no video showing

**Comment by MorrisBA** [comment]
> this worked however now i'm getting an issue with no video showing

I had the same issue with pipewire. Setting to default has worked but I also have no video on the headset. I can see the screen view and tracking is working but the headset shows black. I am on Pop OS running 3600x 1080ti and 32gb ram.

**Comment by minepoof** [comment]
I'm getting this as well on my arch linux install....

**Comment by The-personified-devil** [comment]
Pipewire kind of broke the device name "pipewire" for it's default device, use "pulseaudio" instead if you have pipewire-pulse installed.

**Comment by snagar** [comment]
Same here, black screen although it is tracked on the "VR View" window.

**Comment by The-personified-devil** [comment]
If you're getting the black screen on client error you should check https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

**Comment by snagar** [comment]
@The-personified-devil 
Thanks for the input.

At last I was able to stream VR into the QUEST head set.
In my case, for now, I disabled the audio settings, since anything I chose from the "drop down list" caused for a continues "whine" sound in the headset.

I hope to continue and investigate this issue, but for now I can't stream the audio to the headset.

**Comment by MorrisBA** [comment]
> If you're getting the black screen on client issue you should check https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

The command in the steps provided worked to get video. Thank you for this. Now my games are incredibly slow to launch or don't launch in vr, but I will look into this further and update if I find a solution

**Comment by svidlak** [comment]
> If you're getting the black screen on client issue you should check https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

Seems like it solved the issue for other people. Sorry for the dumb question but where can I find the SteamVR commandline options? is it like right click on SteamVR in Steam -> Properties -> Launch options?

**Comment by The-personified-devil** [comment]
See #2242
