### ISSUE TITLE
ALVR Cant launch steamvr

### ISSUE THREAD

**Issue by Ncarauj012** [alvr-org/ALVR#2187]
## Description
ALVR suddenly stopped working, nothing happened to cause this, now it wont open steamvr and opening it manually results in nothing, all i get is "AV1 profile does not contain encoding entrypoint. You unlikely to have hardware encoding for it." which was a warning which was displayed before but had no effect.

completely wiping it from my computer and reinstalling did not fix the issue, neither did trying to change to a different version

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[System]
OS:              Linux Mint 21.3 Virginia
Arch:            x86_64
Kernel:          5.15.0-107-generic
Desktop:         X-Cinnamon
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 5 5600X 6-Core Processor
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             23.4 GB
Swap:            2.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.42, 5.15.0-107-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1 22.04.1
OpenGL Core:     4.6 (Core Profile) Mesa 23.0.4-0ubuntu1 22.04.1
OpenGL ES:       OpenGL ES 3.2 Mesa 23.0.4-0ubuntu1 22.04.1
Vulkan Version:  1.3.204
Vulkan Drivers:  AMD Radeon RX 6700 XT (RADV NAVI22) (1.3.238)

### Installation
**ALVR Version**:
v21.0.0-dev01+nightly.2024.06.10
**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Vixea** [comment]
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

**Comment by Ncarauj012** [comment]
i have already followed this guide and, as said before, it was working perfectly fine before this. i am now trying to find out why exactly.

**Comment by Vixea** [comment]
Just to make sure we've updated the guide you did look at the newest one?
