### ISSUE TITLE
Linux bitrate jumps from 10 to 900 and kills performance

### ISSUE THREAD

**Issue by endemiq2** [alvr-org/ALVR#2188]
The bug is affecting all games. The bug does not affect Steam void for some reason.

## Description
Encoder bitrate is set to constant, but with both "adopt to framerate" On and Off bitrate is not constant.
Encoder bitrate jumps form 10 to 600 on 5G wifi. from 10 to 300 on 2.4G wifi and from 10 to 900 on usb-thunderbolt. Bitrate jumps multiple times a second and encoder practically kills gpu performance down to 23-25 fps. Using slower wifi limits encoder jumps and actually improves framerate to 30-35 fps. With the lowest in-game graphics settings framerate is expected to be locked at 90fps.
Lowering HDM resolution and encoding resolution to sub 800x800 pixels with the lowest in-game settings improves fps from 30-35 only up to 35-45 fps in every game. 

Same total resolution with the same lowest in-game settings without alvr streaming results in 144fps locked.
Same total resolution with the the high-epic in-game settings without alvr streaming results in 144fps locked.
Higher total resolution with the the high-epic in-game settings without alvr streaming results in 144fps locked.
The systems are properly configured and perform as expected outside of ALVR.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment

**CPU**:
Intel 11600, 12900
**GPU**:
3060, 3070ti
**GPU Driver Version**:
535, 545, 555

**ALVR Version**:
latest and nightly

**ALVR Settings File**:
multiple settings tested, same results

**SteamVR Version**:
every one from legacy 1.27 up to beta 2.6.2

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable 
- [x] Source

**OS Name and Version** 
Ubuntu, Mint, latest kernels, Plasma X11 and Plasma Wayland (on both distros)

 Feature Requests:
Feature to hard cap encoder bitrate needed.

**Comment by papuSpartan** [comment]
For whatever reason the requested bitrate, even when set constant, is far exceeded which seems to cause low performance:
![bitrate](https://github.com/user-attachments/assets/41918706-088b-4ab3-90f2-7c9da9af11f6)

**Comment by momanx** [comment]
Similar issue on similar setup, although I'm on Manjaro; also on Nvidia (RTX 4070), Wayland Plasma and 555 drivers. Identical situation, playback very stuttery regardless of buffered frame settings, also have slight audio crackling and frames sometimes replay/bleed into one another. Over Wi-Fi, Wi-Fi 6 router with only the 5 GHz band active.
![image](https://github.com/user-attachments/assets/dc3c134f-f0f5-4a67-8c17-3af6fdbbfe2e)

**Comment by Dekomoro** [comment]
Same issue but on an amd 7700 xt. Doesn't appear to matter what codec I use.

**Comment by FoxbitDreamtail** [comment]
For some ungodly reason, it works fine on my 500 megabit per second router from 2015 But I still get those major spikes when using a USB C to C cable. I'm running a similar system to what they're running with Linux Mint 21.3 because I haven't been offered the upgrade yet, But I have upgraded my GPU from an RTX 2060 to an AMD Radeon RX 6800.
