### ISSUE TITLE
No video in headset (LINUX STEAM DECK)

### ISSUE THREAD

**Issue by VSjnk** [alvr-org/ALVR#2199]
## Description 
When i connect to my Quest 2, my headset can give all its controller and headset data, but can't display anything inside the headset.

## General Troubleshooting
I did all the steps in the wizard, and tried changing the video format, but nothing worked, i tried downgrading, nothing
I even tried disabling my firewall completly still with no luck, there were a bunch of other stiff i tried, all failing.
### Hardware
My steam deck, An Oculus quest 2 256gb launch model.
**CPU**:
Steam deck built in Amd CPU
**GPU**:
Integrated graphics, (Very powerfull, but lacks VRAM)
**GPU Driver Version**:
Latest
**Audio**:
None (I use bluetooth headphones)
### Installation
**ALVR Version**:
Latest
**ALVR Settings File**:
Default
**SteamVR Version**:
Latest, previous builds
**Install Type**:
- [ ] Portable (`zip`)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Steam OS

**Comment by Raezroth** [comment]
Did you  add ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% to the commandline options of SteamVR (SteamVR -> Manage/Right Click -> Properties -> General -> Launch Options) ?

**Comment by Raezroth** [comment]
Also please keep in mind 

> Will Steam Deck work with PC VR headsets?
> While technically a PC VR headset can be connected, the Steam Deck is not optimized for PC VR experiences.

Quote from [Steamdeck.com](https://www.steamdeck.com/en/faq#:~:text=Will%20Steam%20Deck%20work%20with,optimized%20for%20PC%20VR%20experiences.)

**Comment by ronaldng070116-glitch** [comment]
Facing same problem with pico 4 ultra
