### ISSUE TITLE
Client's screen is black

### ISSUE THREAD

**Issue by marshallovski** [alvr-org/ALVR#2201]
## Description

I'm using my [Quest 1](https://vr-compare.com/headset/oculusquest). For short, on Quest's-side ALVR displays nothing, just black screen, but on PC (SteamVR -> Display VR preview) works fine, display isn't black. As I said in my [prev. issue](https://github.com/alvr-org/ALVR/issues/2200), after I restarted my PC, everything broke for some reason. I haven't changed any of ALVR/SteamVR settings.

Oh, and also, I already tried to do [this thing](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#fix) as described in "Linux Troubleshooting" in Wiki, before restarting PC, it worked. 

![зображення](https://github.com/alvr-org/ALVR/assets/68496774/14df0329-d401-4b17-b911-b1b79164e856)

I tried already to re-register the ALVR drivers, etc. but it doesn't affect anything. 
[This](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#amdvlkamd) returns me nothing, so this isn't a graphics driver-related problem.

![зображення](https://github.com/alvr-org/ALVR/assets/68496774/ef1eae5b-3c88-47df-83a7-2d205fa35959)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU:**
Intel Core i3-10100F
**GPU:**
AMD ATI Radeon RX 470/480/570/570X/580/580X/590 (RX580)
**GPU Driver Version:**
Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev e7)
**Audio:**
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere HDMI Audio [Radeon RX 470/480 / 570/580/590]
00:1f.3 Audio device: Intel Corporation Comet Lake PCH-V cAVS
(I'm using my Astro MixAmp Pro headphones, device name: Astro MixAmp Pro Mono)

### Installation
**ALVR Version**:
v.20.8.1

**ALVR Settings File**:
 sorry, I don't know where exactly this file is located

**SteamVR Version**:
latest,  v2.7.1

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Debian GNU/Linux 12 (bookworm) (stable)

**Comment by Popcake480** [comment]
Me to

**Comment by MagicRB** [comment]
Same here on NixOS and Nvidia graphics

**Comment by MeatH00k** [comment]
+1, Arch KDE, 3060 ti, nvidia proprietary drivers - 555

**Comment by The-personified-devil** [comment]
This seems to be a duplicate report of a known issue, though this known issue wasn't necessarily clearly documented. I went ahead and documented it in #2242, which also contains an explanation. If this isn't actually the case and the workaround doesn't actually fix this particular instance then feel free to comment and I'll reopen this issue.

**Comment by MagicRB** [comment]
For me the black screen was a firewall issue, a `vrmonitor.sh` being needed issue and `vrcompositor` crashing if more than one ICD are available, i used one of the vulkan env variables to restrict it to only nvidia's ICD. The last issue might be NixOS specific though, it also manifested as a crash in the quest and a white screen in the steamvr preview

**Comment by lavenderdotpet** [comment]
> For me the black screen was a firewall issue, a `vrmonitor.sh` being needed issue and `vrcompositor` crashing if more than one ICD are available, i used one of the vulkan env variables to restrict it to only nvidia's ICD. The last issue might be NixOS specific though, it also manifested as a crash in the quest and a white screen in the steamvr preview

what exactly did u do to fix it im having the same issue on nix

**Comment by MagicRB** [comment]
I have my notes somewhere, ill find then, clean up, post, notnsure when, ill prioritize it though.

**Comment by The-personified-devil** [comment]
> what exactly did u do to fix it im having the same issue on nix

there are already some notes about that in the wiki, not for nix specifically but should still help with the issue you're experiencing
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#amdintel-integrated-gpu--nvidia-discrete-gpu

**Comment by lavenderdotpet** [comment]
> > what exactly did u do to fix it im having the same issue on nix
> 
> there are already some notes about that in the wiki, not for nix specifically but should still help with the issue you're experiencing https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#amdintel-integrated-gpu--nvidia-discrete-gpu

i dont have intigrated gpu and im on a amd graphics card

**Comment by The-personified-devil** [comment]
> i dont have intigrated gpu and im on a amd graphics card

then you probably have multiple different drivers installed (which is also mentioned in the wiki btw)

**Comment by lavenderdotpet** [comment]
disregard this fixed it ``~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%``

**Comment by kimjongbing** [comment]
I have the same issue currently on NixOS with a Quest 3. I am unable to run the shell script since it does not exist: 
``~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%``

I have tried ``WAYLAND_DISPLAY="" %command%`` but this does not solve the issue.

**Info**
OS: NixOS 24.11.20240916.99dc878 (Vicuna) x86_64
WM: Mutter (Wayland)
DE: GNOME 46.4
Kernel: Linux 6.11.0-cachyos


Thank you in advance.

**Comment by The-personified-devil** [comment]
@kimjongbing Theres a linux troubleshooting page on the wiki that contains the vrmonitor fix with instructions on how to adapt it to various installations.

**Comment by kimjongbing** [comment]
> @kimjongbing Theres a linux troubleshooting page on the wiki that contains the vrmonitor fix with instructions on how to adapt it to various installations.

Hi, are you referring to [this](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting)? Can you point me to exactly which part of it would be relevant to troubleshooting my issue? I have tried the content under the ``Black screen even when SteamVR shows movement`` heading, and under the ``Wayland`` heading.
