### ISSUE TITLE
ALVR Completely broken over cable.

### ISSUE THREAD

**Issue by CactusBoy3** [alvr-org/ALVR#2208]
## Description
ALVR connects but with SteamVR flashing the headset and controller icons, display in headset is black

## General Troubleshooting
Reinstalled ALVR on headset and PC, restarted both, disabled firewall, started fresh with new config

### Hardware

**GPU**: GTX 1660

**GPU Driver Version**: 555.99 (newest)

### Installation
**ALVR Version**: 20.8.1

**ALVR Settings File**: https://drive.google.com/file/d/1gDZ3qfgGX0ppmcb0V6ALT_t7tTHOf3_f/view?usp=drive_link

**SteamVR Version**:  2.7.1

**Install Type**:
-  Packaged (`exe`, `deb`, `rpm`, etc)

**OS Name and Version**: Win 11 Build 26231.5000

Videos of issue: https://drive.google.com/file/d/1-z18fp5Amopun8qqdZ9B9pAFmHmMh1YB/view?usp=sharing (headset view) 
                        https://drive.google.com/file/d/185ny7CliHkK7cUu6T2mZLYPX4qwb9hUB/view?usp=sharing (pc view until 0:35)

**Comment by The-personified-devil** [comment]
Have you checked https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting yet?
Or is the behavior similar to https://github.com/alvr-org/ALVR/issues/2185?

**Comment by CactusBoy3** [comment]
No, does not seem similar to #2185 but that did happen to me before though

**Comment by The-personified-devil** [comment]
Have you checked the wiki entry I linked?

**Comment by CactusBoy3** [comment]
Yeah, I've checked it but everything listed in that wiki entry is for Linux, not Windows

**Comment by The-personified-devil** [comment]
My bad, I missed where you specified the OS

**Comment by Meister1593** [comment]
```
  "connection": {
      "stream_protocol": {
        "variant": "Udp"
      },
```

You're using udp, which doesn't work with cabled. Switch to TCP

https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB)

First entry on wired mode wiki page notes about this

**Comment by CactusBoy3** [comment]
Thanks! Don't know how I didn't catch this 🤦
