### ISSUE TITLE
Incorrect ipd in one eye Beat Saber

### ISSUE THREAD

**Issue by lividhen** [alvr-org/ALVR#2216]
## Description

When running Beat Saber the right eye is incorrect. I suspect the ipd settings are funky but I'm not 100% sure. I have not had time to see if it happens with other games but I will in a few hours. The steam UI overlay and steam home look normal. The left eye looks correct, seems to be facing the correct direction, no warping. The right eye feels as if its pointed outward away from the bridge of my nose and there is significant warping.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
https://linux-hardware.org/?probe=4752729a61

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 9 7900X
**GPU**:
AMD RX 7900 XT
**GPU Driver Version**:
AMDGPU 24.1.2
**Audio**:
Pipewire
### Installation
**ALVR Version**:
v20.8.1
**ALVR Settings File**:
[session.json](https://github.com/user-attachments/files/16046881/session.json)
(is this the right file?)
**SteamVR Version**:
2.6.2
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by Vixea** [comment]
This is a beat saber bug.
