### ISSUE TITLE
SteamVR is Restarting loop unless ALVR is closed on connect.

### ISSUE THREAD

**Issue by Xentha** [alvr-org/ALVR#2222]
### Issue
When connecting to my computer, ALVR will I guess deem the process too unstable and attempt to restart SteamVR. Problem is, it keeps doing this over and over unless I close its' interface after connecting. I can then re-open it without that issue continuing however.

### Hardware
**CPU**: Intel i5-12400F 2.50GHz
**GPU**: AMD RX 6750XT
**GPU Driver Version**: 24.4.1 (up to date version is 24.6.1, but this does not appear to be a graphical issue.)
**Audio**:
Realtek Audio
VB-Audio Virtual Cable

### Installation
**ALVR Version**: v20.8.1
**ALVR Settings File**: ?
**SteamVR Version**: Current Non-Beta Release
**OS Name and Version**:
Windows 11
Version 23H2

### Solution/Feature Request
Simply a setting that determines how long ALVR should wait on connect before deeming the connection unstable enough to restart SteamVR.

**Comment by Xentha** [comment]
It seems this issue was caused by attempting to use AV1 encoding. I have an AMD card, as listed, but AV1 is 'not supported by the client'. Switching to HEVC stopped the restart loops.

I'm now wondering however, why would there be an option if it's not supported by the client?

**Comment by Germanreddragon94** [comment]
> It seems this issue was caused by attempting to use AV1 encoding. I have an AMD card, as listed, but AV1 is 'not supported by the client'. Switching to HEVC stopped the restart loops.
> 
> I'm now wondering however, why would there be an option if it's not supported by the client?

Your issue seems interesting I am using the AV1 with my Nvidia RTX 4080 with no issues. I get a slight better stream quality with the same transfer rate. But I would say HEVC or even H264 is not doing that much of a difference and I guess the latency would be slightly better too.

**Comment by Xentha** [comment]
At this point I'm honestly not sure what was actually causing the restarts, as they have not returned even after returning to H264 due to HEVC causing graphic driver crashes of some kind.
However apparently AV1 not working is due to it being incompatible with Quest 2 specifically. Apparently it would have worked if I was on Quest 3.

**Comment by Germanreddragon94** [comment]
This could really be the case. I read AV1 is working with the Nvidia RTX series and the Quest 3 which I am using so it makes sense why it is working for me
