### ISSUE TITLE
ALVR linking to nonrxistant OpenVR directory.

### ISSUE THREAD

**Issue by Failure191** [alvr-org/ALVR#2225]
When searching for the OpenVR path, ALVR looks for /root/.config/openvr/openvrpaths.vrpath
Not only does this make the app require root access to run, it's also not an existent directory on my drive.
My OpenVR path lies in /home/{USER}/.config/openvr/openvrpaths.vrpath
While I would usually link the necessary folder to the needed spot in the drive, I found that there is no way to link folders into my root directory.

**Comment by The-personified-devil** [comment]
Do you have the XDG standard environment variables set?

**Comment by Failure191** [comment]
My variables are currently set to their default values as far as I'm aware.
XDG_CONFIG_HOME defaults to $HOME/.config, assuming that ALVR uses XDG_CONFIG_HOME, it should link to my OpenVR path without issue, which means I probably messed with the file at some point (or my distro managers did). I think I would've noticed if there was an issue earlier if my paths were wrong though.

The contents of my /etc/profile.d/locale.sh script are below

#!/bin/sh

# load locale.conf in XDG paths.
# /etc/locale.conf loads and overrides by kernel command line is done by systemd
# But we override it here, see FS#56688
if [ -z "$LANG" ]; then
  if [ -n "$XDG_CONFIG_HOME" ] && [ -r "$XDG_CONFIG_HOME/locale.conf" ]; then
    . "$XDG_CONFIG_HOME/locale.conf"
  elif [ -n "$HOME" ] && [ -r "$HOME/.config/locale.conf" ]; then
    . "$HOME/.config/locale.conf"
  elif [ -r /etc/locale.conf ]; then
    . /etc/locale.conf
  fi
fi

# define default LANG to C.UTF-8 if not already defined
LANG=${LANG:-C.UTF-8}

# export all locale (7) variables when they exist
export LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY \
       LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT \
       LC_IDENTIFICATION

**Comment by Failure191** [comment]
Sorry, forgot to give it the code format.
It should be easier to read here. 
`#!/bin/sh

# load locale.conf in XDG paths.
# /etc/locale.conf loads and overrides by kernel command line is done by systemd
# But we override it here, see FS#56688
if [ -z "$LANG" ]; then
  if [ -n "$XDG_CONFIG_HOME" ] && [ -r "$XDG_CONFIG_HOME/locale.conf" ]; then
    . "$XDG_CONFIG_HOME/locale.conf"
  elif [ -n "$HOME" ] && [ -r "$HOME/.config/locale.conf" ]; then
    . "$HOME/.config/locale.conf"
  elif [ -r /etc/locale.conf ]; then
    . /etc/locale.conf
  fi
fi

# define default LANG to C.UTF-8 if not already defined
LANG=${LANG:-C.UTF-8}

# export all locale (7) variables when they exist
export LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY \
       LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT \
       LC_IDENTIFICATION
`

**Comment by Failure191** [comment]
My variables are currently set to their default values as far as I'm aware.
XDG_CONFIG_HOME defaults to $HOME/.config, assuming that ALVR uses XDG_CONFIG_HOME, it should link to my OpenVR path without issue, which means I probably messed with the file at some point (or my distro managers did). I think I would've noticed if there was an issue earlier if my paths were wrong though.

The contents of my /etc/profile.d/locale.sh script are below

```
#!/bin/sh

# load locale.conf in XDG paths.
# /etc/locale.conf loads and overrides by kernel command line is done by systemd
# But we override it here, see FS#56688
if [ -z "$LANG" ]; then
  if [ -n "$XDG_CONFIG_HOME" ] && [ -r "$XDG_CONFIG_HOME/locale.conf" ]; then
    . "$XDG_CONFIG_HOME/locale.conf"
  elif [ -n "$HOME" ] && [ -r "$HOME/.config/locale.conf" ]; then
    . "$HOME/.config/locale.conf"
  elif [ -r /etc/locale.conf ]; then
    . /etc/locale.conf
  fi
fi

# define default LANG to C.UTF-8 if not already defined
LANG=${LANG:-C.UTF-8}

# export all locale (7) variables when they exist
export LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY \
       LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT \
       LC_IDENTIFICATION
```

**Comment by The-personified-devil** [comment]
This example is how the code determines the config path for Linux`$XDG_CONFIG_HOME or $HOME/.config|/home/alice/.config`. Only real explanation that I have is that you're somehow running as root, running alvr as root or have `$HOME` set incorrectly. Can you verify the actual values of the `XDG_CONFIG_HOME` and `HOME` and show us how exactly you're launching the alvr dashboard?

**Comment by Failure191** [comment]
I ran it as root to see if that would make it detect when SteamVR was open. I wasn't aware that that messed with XDG paths. I'll find another way to do that.
