### ISSUE TITLE
Support for ARC GPU's on Linux

### ISSUE THREAD

**Issue by Failure191** [alvr-org/ALVR#2226]
## Description

ALVR does not detect any of the three encoding entrypoints for my GPU when running on Linux. (It worked fine on Windows)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
KWin

### Hardware

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: PRO Z690-A WIFI DDR4(MS-7D25)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: GenuineIntel
CPU Brand: 12th Gen Intel(R) Core(TM) i5-12600K
CPU Family: 0x6
CPU Model: 0x97
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 4900 MHz
16 logical processors
10 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"Manjaro Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.6.34-1-MANJARO
X Server Vendor: The X.Org Foundation
X Server Release: 12401000
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240610.91380
Video Card:
Driver: Intel Mesa Intel(R) Arc(tm) A770 Graphics (DG2)
Driver Version: 4.6 (Compatibility Profile) Mesa 24.1.1-manjaro1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x8086
DeviceID: 0x56a0
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 27.56" x 15.35" (31.54" diag), 70.0cm x 39.0cm (80.1cm diag)
Primary VRAM: 16288 MB
Sound card:
Audio device: Realtek ALC897
Memory:
RAM: 31873 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB
Total Hard Disk Space Available: 928627 MB
Largest Free Hard Disk Block: 142201 MB
Storage:
Number of SSDs: 2
SSD sizes: 1000G,960G
Number of HDDs: 0
Number of removable drives: 0

**CPU**:
Intel core i5-12600k

**GPU**:
Intel ARC A770

**GPU Driver Version**:
Mesa 24.1.1

**Audio**:
Pipewire

### Installation
**ALVR Version**:
20.8.1

**ALVR Settings File**:
Settings are all on defaults

**SteamVR Version**:
2.6

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source
I tried multiple.

**OS Name and Version**:
Manjaro Linux
6.6.34-1

**Comment by The-personified-devil** [comment]
What does `vainfo` output?

**Comment by Failure191** [comment]
> What does `vainfo` output?

Trying display: wayland
vainfo: VA-API version: 1.21 (libva 2.21.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.2.3 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileNone                   : VAEntrypointStats
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSliceLP
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSliceLP
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSliceLP
      VAProfileVP9Profile1            : VAEntrypointVLD
      VAProfileVP9Profile1            : VAEntrypointEncSliceLP
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointEncSliceLP
      VAProfileVP9Profile3            : VAEntrypointVLD
      VAProfileVP9Profile3            : VAEntrypointEncSliceLP
      VAProfileHEVCMain12             : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointVLD
      VAProfileHEVCMain422_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain422_12         : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointVLD
      VAProfileHEVCMain444            : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         : VAEntrypointVLD
      VAProfileHEVCMain444_10         : VAEntrypointEncSliceLP
      VAProfileHEVCMain444_12         : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointVLD
      VAProfileHEVCSccMain            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain10          : VAEntrypointVLD
      VAProfileHEVCSccMain10          : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444         : VAEntrypointVLD
      VAProfileHEVCSccMain444         : VAEntrypointEncSliceLP
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointEncSliceLP
      VAProfileHEVCSccMain444_10      : VAEntrypointVLD
      VAProfileHEVCSccMain444_10      : VAEntrypointEncSliceLP

**Comment by Vixea** [comment]
It's possible the dudes running a too new driver Intel broke things more

**Comment by Vixea** [comment]
Oh I completely missed that, yea looking at the mesa version that's what it seems to be. Create a bug report to Intel if theirs none as I've already told multiple people to do so

**Comment by Chiffon-Pudding** [comment]
So which version of Mesa does ALVR currently work?
I am also seeing the same errors.

Arch Linux
Intel ARC A770
mesa 1:23.2.1-2
intel-media-driver 22.6.6-1

**Comment by EstebanPowEngi** [comment]
I am having the same issue as of October 2025
