### ISSUE TITLE
pipewire default device

### ISSUE THREAD

**Issue by ergo3d** [alvr-org/ALVR#2234]
## Description
no audio until you have at least one audio output enabled
![Screenshot from 2024-07-07 22-33-41](https://github.com/alvr-org/ALVR/assets/76014697/c83c9952-08e8-42c5-9b33-13cf9c3aae1b)
![Screenshot from 2024-07-07 22-35-52](https://github.com/alvr-org/ALVR/assets/76014697/38fc5ca6-bceb-4cf3-a71f-ea2d885fd919)
![Screenshot from 2024-07-07 22-34-42](https://github.com/alvr-org/ALVR/assets/76014697/4f7b2d86-06fa-4f11-9b63-90813979af41)
after manually disabling all outputs sound in headset works fine

### Hardware

CPU: AMD Ryzen 9 3950X
GPU: RTX 4080 
GPU DRIVER: 555.58.02 
AUDIO: pipewire
https://linux-hardware.org/?probe=6741744852

### Installation
ALVR Version:  20.9.1
SteamVR Version: 2.7.2

Install Type:  launcher from GitHub and aur version (same result)

OS Name and Version archlinux 6.9.7-arch1-1

**Comment by The-personified-devil** [comment]
Not really a bug, it acts like any other speaker, you have to configure your os to output to it. However a button to set the alvr device as the default output device (as long as it exists, but that's given) would be helpful, though I'm not sure how feasible

**Comment by ergo3d** [comment]
> Not really a bug, it acts like any other speaker, you have to configure your os to output to it. However a button to set the alvr device as the default output device (as long as it exists, but that's given) would be helpful, though I'm not sure how feasible

my bad, found how to do it, now all works perfectly. thanks!
