### ISSUE TITLE
NVML Engine Error

### ISSUE THREAD

**Issue by Germanreddragon94** [alvr-org/ALVR#2235]
Hello,
I switched from Windows to Linux and want to use my Quest 3. I installed the ALVR software and it starts without any issues.
If I start SteamVR via ALVR I get the error

"Can't initialize NVML engine, error: a libloading error occurred: libnvidia-ml.so: cannot open shared object file: No such file or directory."

I did some research but I cant find the problem. The Librarys and the CUDA Kernels are all working fine. I can play very well in desktop mode and I installed the librarys.

I am using Linux Nobara which is based on Fedora. The installer says in the window Software Requirements "Unsupported OS" but I am sure I am not the only one using Nobara with VR.

My Hardware:
AMD Ryzen 5 7600X

Nvidia RTX 4080
Driver Version 555.42.02

ALVR Version 20.9.1
Installed via tar.gz file from this website.

I hope someone can help with this issue.

**Comment by Germanreddragon94** [comment]
I solved the issue. The reason is that Nobara is using his own Driver Manager and the driver links are set different which causes this problem.

The solution is simple You need to install the original Nvidia graphics driver over the graphics driver from the Nobara driver Manager. So You only need to download the run file and start it with "sudo sh *filepath*" and then install the driver via terminal.

I didnt see any problems with installing the driver over the driver from the driver manager in nobara yet so I guess there will be no errors.

**Comment by EmersonBiggons** [comment]
You don't have to reinstall any drivers. 

ALVR Expects `libnvidia-ml.so` to be named exactly as so, but on nobara it gets renamed to `libnvidia-ml.so.#currentdriverversion#` E.G `libnvidia-ml.so.565.57.01` All you have to do is just make a symlink of it and name the link `libnvidia-ml.so`

As follows for my driver version of 565.57.01,

`sudo ln -s /usr/lib/libnvidia-ml.so.565.57.01 /usr/lib/libnvidia-ml.so && sudo ln -s /usr/lib64/libnvidia-ml.so.565.57.01 /usr/lib64/libnvidia-ml.so`

Depending on your version just replace the (insert here) values with your version;

`sudo ln -s /usr/lib/libnvidia-ml.so.(insert here) /usr/lib/libnvidia-ml.so && sudo ln -s /usr/lib64/libnvidia-ml.so.(insert here) /usr/lib64/libnvidia-ml.so`

To check what version, you can check in various ways, googling it will give you a way. I just found it by searching for the libnvidia-ml.so file and found it was renamed after my driver version.

**Comment by The-personified-devil** [comment]
That's broken behavior on Nobara's side to not have a symlink from `libnvidia-ml.so` to the exact so. Because linking against every (major) driver version is idiotic. Perhaps you should raise an issue with them to fix it.

**Comment by Vixea** [comment]
Yea, I'm reporting to their discord as we speak actually

**Comment by Germanreddragon94** [comment]
I can confirm that this problem is no longer a thing after a certain update from Nobara. Maybe they already fixed it.
But it cant hurt to let the Nobara team know about the issue.
