### ISSUE TITLE
[Recommend change to the README] Drop Windows XP from the README.MD file

### ISSUE THREAD

**Issue by OzzyHelix** [alvr-org/ALVR#2237]
Windows XP is long dead and has not been supported by Microsoft since 2014. On top of that it is no longer supported by Steam. Perhaps we should remove it from the readme file and maybe have it list 7/8/10 instead considering Windows 10 will be out of support in October 2025

**Comment by Vixea** [comment]
I can see XP but 10 still got a year

**Comment by The-personified-devil** [comment]
We should add Windows 95 tbh

**Comment by OzzyHelix** [comment]
I'm just saying that XP doesn't make a lot of sense to keep in the readme because of how out of support it is now

**Comment by OzzyHelix** [comment]
> We should add Windows 95 tbh

and as much as I'd love to play VR on DOS its a pipe dream
