### ISSUE TITLE
Pico 4 issues

### ISSUE THREAD

**Issue by renegade2k82** [alvr-org/ALVR#2238]
## Description

Can not use my internal mic on my pico 4 enterprise 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
Room
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:i9 14th gen

**GPU**:asus strix 4090 OC

**GPU Driver Version**:latest 

**Audio**:built in on mobo 

### Installation
**ALVR Version**:latest nightly 

**ALVR Settings File**:?

**SteamVR Version**:latest stable 

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`) portable couldn’t find install version 
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):windows 11 pro

**Comment by The-personified-devil** [comment]
Are you sure that the alvr app has permissions to access the internal microphone?
