### ISSUE TITLE
bug: Setup wizard says Unsupported OS

### ISSUE THREAD

**Issue by Meister1593** [alvr-org/ALVR#2245]
Caused by removed on connect/disconnect script assignment, Software requirements section probably should mention pipewire version, hybrid graphics, etc requirement compliance

![Image](https://github.com/user-attachments/assets/4321b798-d921-401b-8e24-fbb364843c88)

**Comment by traklo68** [comment]
do u know maybe what supported OS'es are?

**Comment by zarik5** [comment]
Windows and Linux

**Comment by zarik5** [comment]
This issue was already solved in v20.10

**Comment by traklo68** [comment]
> Windows and Linux

i know windows and linux but what distros and ect bcz i want get the app running on linux or even switch to deffirnet linux distro to just use alvr, idk if its my problem or what but in endavour os based on arch i see this 
![Zrzut ekranu_20240820_172059](https://github.com/user-attachments/assets/10b45374-d7c0-47c9-9a3e-63d79d03e106)
