### ISSUE TITLE
Can't install alvr-nvidia on Arch

### ISSUE THREAD

**Issue by pflavio** [alvr-org/ALVR#2246]
Hello guys

I'm receiving the following error when trying to install alvr-nvidia via the AUR (using yay):
```ERROR: failed checking for nvcc.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
thread 'main' panicked at alvr/xtask/src/dependencies.rs:277:49:
called `Result::unwrap()` on an `Err` value: command exited with non-zero code `bash -c "PKG_CONFIG_PATH=\'/home/pflavio/.cache/yay/alvr-nvidia/src/alvr/deps/linux/nv-codec-headers/build/lib/pkgconfig\' ./configure --prefix=/home/pflavio/.cache/yay/alvr-nvidia/src/alvr/deps/linux/ffmpeg/alvr_build --enable-gpl --enable-version3 --enable-static --disable-programs --disable-doc --disable-avdevice --disable-avformat --disable-swresample --disable-swscale --disable-postproc --disable-network --disable-everything --enable-encoder=h264_vaapi --enable-encoder=hevc_vaapi --enable-encoder=av1_vaapi --enable-hwaccel=h264_vaapi --enable-hwaccel=hevc_vaapi --enable-hwaccel=av1_vaapi --enable-filter=scale_vaapi --enable-vulkan --enable-libdrm --enable-pic --enable-rpath --fatal-warnings --enable-encoder=h264_nvenc --enable-encoder=hevc_nvenc --enable-encoder=av1_nvenc --enable-nonfree --enable-cuda-nvcc --enable-libnpp --nvccflags=\"-gencode arch=compute_52,code=sm_52 -O2\" --extra-cflags=\"-I/opt/cuda/targets/x86_64-linux/include\" --extra-ldflags=\"-L/opt/cuda/targets/x86_64-linux/lib\""`: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: alvr-nvidia-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
alvr-nvidia - exit status 4
```

Someone else has also posted the same issue in the comments on the AUR page [here](https://aur.archlinux.org/packages/alvr-nvidia). Is there a way to fix it? I was able to install the regular ALVR from the AUR just fine (but it didn't work for me so I wanted to try the NVIDIA version for my RTX 3060).

**Comment by Vixea** [comment]
Please send the full loga

**Comment by pflavio** [comment]
Well it kinda fixed itself I guess. I tried running it again to get you a fresh pair of logs and now it went through. Before opening the ticket I tried it three times with the same error each time however.

In any case my Quest 2 isn't getting discovered by alvr-nvidia either so I'm guessing no VR on Linux for me unfortunately. :(

**Comment by Vixea** [comment]
Read our troubleshooting wiki

**Comment by pflavio** [comment]
@Vixea I did and compared screenshots and I noticed that SteamVR is not showing the ALVR addon! Everything from the toubleshooting guide (especially the Linux one) should be alright though.

**Comment by Vixea** [comment]
Are you launching using the button in the dashboard? Have you checked that it isnt the flatpak version of steam? Maybe try installing steam-native-runtime

**Comment by pflavio** [comment]
No it wasn't Steam error but AVLR from AUR (specifically the NVIDIA version). I initially got that one since I have a 3060. Based on the recommendation in the text I downloaded the tar.gz version from releases and there it works as designed (so far). I can launch it, stream Steam and I'm currently downloading Pavlov to see if I can play, too.

**Comment by pflavio** [comment]
So I managed to get it to work and run Half Life Alyx, but without sound. Pavlov says it's starting but nothing happens unfortunately...

**Comment by cerealbowlsystem** [comment]
For future reference, I found what the fix was: after installing CUDA, you **must** log out, and then log back in (or reboot). This is so that CUDA gets added to PATH. Hope this helps others!

**Comment by pflavio** [comment]
Great good to know! That would have never occurred to me. I just attributed it to it fixing itself. :D Next time I'll keep that in mind (or maybe run a command to update the path directly?)

-------- Original Message --------

**Comment by Horange321** [comment]
`export NVCC_APPEND_FLAGS+='-std=c++14'`
