### ISSUE TITLE
Can't install apk

### ISSUE THREAD

**Issue by max-allan** [alvr-org/ALVR#2249]
## Description
I ran the launcher, downloaded v20.9.1 and press "Install APK". It downloads android stuff and then:
```
ADB install failed: adb.exe: no devices/emulators found
```

I tried with and without USB C cable to the headset (Quest Pro) with the headset off and on

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**: Intel Core i9

**GPU**: Nvidia 4080 Super

**GPU Driver Version**: 556.12

**Audio**: Built in

### Installation
**ALVR Version**: v20.9.1

**ALVR Settings File**: none yet

**SteamVR Version**: none I have Oculus Meta Quest.

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 10 22H2

**Comment by komunre** [comment]
Same issue, Pop!_OS 22.04 LTS, ALVR 20.10.0.

**Comment by Frexium** [comment]
Same issue here, same OS as previous comment.

**Comment by CoreoftheEarth** [comment]
Same here except it just says "Installing APK" and the loading wheel spins for a few seconds and the progress bar doesnt move then goes back to the version screen

**Comment by komunre** [comment]
I believe that `ADB install failed: adb.exe: no devices/emulators found` is occuring due to oculus not even enabling ADB, as apparent by lack of such in adb devices list, and I believe enabling it requires developer mode, which is not stated in installation instructions, which I find odd.
