### ISSUE TITLE
Video stuttering / quality drops on AMD Radeon, great to see UI selection of priority / encoding profiles / pixel depths

### ISSUE THREAD

**Issue by NikoSquare** [alvr-org/ALVR#225]
There's discussions about the same issue with ReLive: 
https://community.amd.com/thread/224090
https://www.reddit.com/r/Amd/comments/8pseic/my_relive_recordings_have_video_stutter/

There's one work-around: is to increase ALVR task process priority to 'Realtime"/"Very High", maybe it can implemented in the code. Seems like extreme GPU utilization (to be expected in VR) skips encoding task due to lower or same priority over rendering, it cause visual distortions in video feed. Tinkering with ALVR process priority against process priorities of other renderers can make difference.

Encoding profile (such as main_0) introduces low quality distortions, optional  higher quality profiles would be nice to try.

Pixel depth selection (if any options other than 8/422) may reduce packet size, additionally to bitrate.

Edit: I've found an extra possible reason:
According to discussion here: https://steamcommunity.com/sharedfiles/filedetails/?id=870308572
(in combination with comments I've read over discussions)
Controller polling rate may affect video encoding and it is noted in comments to discussions above that 100hz is enough and seems smooth.
Great to see an option to change controller polling rate.

P.S. I’ve found out that problem is solved by AMD already with their own ReLive streaming app for Oculus sideloading.
https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR
I’ve tried, it works, but enabling it is riddling.
It’s built-in into Drivers Control Panel, ReLive VR panel appears when control panel detects running SteamVR, otherwise it’s hidden and not a hint about it. After selection of emulated headset, it installs driver into steam VR, and after than it become discoverable and capable to connect with Oculus. Basically driver installed into SteamVR connects with headset app.

After testing, I conclude, that it does not work any better than ALVR, therefore, improvements suggested in this post make sense. And seems like it’s extremely difficult to find the menu, but files are in AMD Control Panel files in Program Files/AMD/.../WVR

AMD OpenVR utilize Remote Play, it installs virtual PnP Monitor driver and renders there, most probably to avoid sync problems.

**Comment by JackD83** [comment]
A setting for the ALVR GPU priority is already implemented but requires you to launch SteamVR as administrator. This is not a good idea, as all games will then run as administrator. 

The AMF Encoder is using "Profile High and Level 5.1 for H264". Most of the developers are using Nvidia GPUs which makes testing very difficult. 

I read the link to the polling rate, but that has nothing to do how SteamVR works.

**Comment by zarik5** [comment]
There has been a lot of progress on this front, I think this can be closed.
