### ISSUE TITLE
Feature Request: Controller Offset Separation & Profiles

### ISSUE THREAD

**Issue by Xentha** [alvr-org/ALVR#2254]
Hopefully not too troublesome of functions to consider;
I find it odd that controller offset is labeled 'Left Controller' when it affects both. Would it be too much hassle to have two separate sets, one for each controller?
Likewise, not every game has internal offset adjustment, nor necessarily has the same default as another. It would be nice to be able to save offsets as a profile to swap between when necessary. At the moment the best way to do that is to write down the values and manually enter them.

**Comment by zarik5** [comment]
The controller offset is used to correct for alignment issuesin SteamVR, which are always symmetric on the forward/up plane. So basically for linear offset the x axis is flipped, and angular offset the y and z axes are flipped

**Comment by Xentha** [comment]
Ah, alright. I was using OpenVR Input Emulator to adjust controller offsets before, which could do them individually, But if that's not simple to do, then I won't fuss. Unfortunate on both fronts, but I shall make due.
I unfortunately wouldn't know the first thing about coding it myself. I have very basic coding experience but probably not the language that this uses. I don't have a lot of space to work on such a thing either - too many projects of my own.
None the less, thank you for your reply. I may still contact you one day, but I wouldn't be able to put any significant time into it for the time being.
