### ISSUE TITLE
Handshake error for 4318.client: VB-CABLE or Voice Meeter not found. Please install or reinstall either one this pops up every time i try to start the link can i get help

### ISSUE THREAD

**Issue by rasse1231** [alvr-org/ALVR#2256]
## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by Vixea** [comment]
You've filled out no details closing as invalid

**Comment by tofixddd** [comment]
this  is also happening to me have you found a way to fix it?

**Comment by Vixea** [comment]
Please create your own **valid** issue
