### ISSUE TITLE
When In gorilla tag in steamvr, right eye is glitchy and black.

### ISSUE THREAD

**Issue by RoofusTG** [alvr-org/ALVR#2257]
## Description
When I'm in the steamvr home, I both of the lenses display correctly, but when I open gorilla tag, the right eye gets glitchy and goes black, but the left eye works fine.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**:

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by portal2707070** [comment]
try to disable mods, this can be mods issue or beipnex or idk

**Comment by The-personified-devil** [comment]
Alvr doesn't really do anything that could cause it to render most things fine but not gorilla tag, probably a game bug
