### ISSUE TITLE
[linux] Encoder: failed to reconfigure nvenc: invalid param (8), Encoder: Unable to parse option value "high" and Encoder: Undefined constant or missing '(' in 'high'

### ISSUE THREAD

**Issue by playX18** [alvr-org/ALVR#2258]
## Description
Whenever I try to use ALVR either through a cable or WiFi I get the errors:
```
Encoder: failed to reconfigure nvenc: invalid param (8):
Encoder: Undefined constant or missing '(' in 'high'
Encoder: Unable to parse option value "high"
```
## General Troubleshooting
- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=8786c187fc)

**CPU**: i5-13400F

**GPU**: NVIDIA GeForce RTX 4060 

**GPU Driver Version**: 555.58.02

**Audio**: Headphones, pipewire

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: (Where do I get the file if using launcher?) Default except changed encoding to HEVC

**SteamVR Version**: Beta SteamVR version, get the same errors with stable

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x ] Portable (`zip`)
- [ ] Source

**OS Name and Version** CachyOS

**Comment by Doloro1978** [comment]
that happens when you have HEVC selected and are using a h264 profile selected as well, it should be fine
