### ISSUE TITLE
ALVR Dashboard fails to start: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by FlorisTheBeast** [alvr-org/ALVR#2262]
## Description
When trying to launch the alvr_dashboard binary it shows up for a second and then crashes returning in the console "Segmentation fault (core dumped)" the alvr dashboard used to do this all the time but i just had to start it multiple times back to back and then it worked but since I last updated ALVR it has stopped working for me. I've tested it with the latest nightly build and stable build both showing the same error. I have also tried building the packages from the AUR both stable and nightly and the same issue occurs

## General Troubleshooting
-  [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
This is a Arch Linux system running the latest as of writting KDE desktop environment on Wayland

### Hardware
[Hardware](https://linux-hardware.org/?probe=c147fa74f7)
the NVIDIA GPU with no driver is for my Windows virtual machine
### Installation
**ALVR Version**:v20.9.1 and v21.0.0-dev01+nightly.2024.07.16

**ALVR Settings File**: I was unable to find my setting file

**SteamVR Version**: 2.6.2 

**Install Type**:
I have tried compiling from source(from the AUR) i have tried to use the binaries on the github and I have tried the ALVR launcher. all with nightly and stable

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch Linux

**Backtraces**
I got these with the RUST_BACKTRACE=1 variable using the ALVR launcher
*Stable*
[stable.log](https://github.com/user-attachments/files/16266988/stable.log)

*Nightly*
[nightly.log](https://github.com/user-attachments/files/16266993/nightly.log)

Feel free to ask me if there is any more information you require
Edit: I have been able to build both packages from the AUR (because I forgot to remove the debug version of alvr) but the same error still occurs and the main text has been updated to reflect that

**Comment by FlorisTheBeast** [comment]
I have now been able to build the alvr-git package from the AUR without any problems occuring but it still fails to launch with the same "Segmentation fault (core dumped)" error

**Comment by Meister1593** [comment]
(resolved in discord)
Issue was related to some vulkan-radeon-git package, which forced alvr dashboard to launch through llvmpipe and fail to do so, dumping core.
