### ISSUE TITLE
ALVR doesnt detect's quest 2

### ISSUE THREAD

**Issue by portal2707070** [alvr-org/ALVR#2263]
## Description

I downloaded alvr for linux , extract it, run it, downloaded streamer from launcher, launnched it, configure it, and when i try to connect device with wifi or usb cable with alvr app latest version installed and launched it

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
hw-probe link: https://linux-hardware.org/?probe=74e7033924

**CPU**:
amd ryzen 3 pro 220GE
**GPU**:
intergrated
**GPU Driver Version**:
latest
**Audio**:
hd-audio ( i think )

### Installation
**ALVR Version**:  latest

**ALVR Settings File**: default settings with firewall

**SteamVR Version**: latest 

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Kali GNU/Linux Rolling latest

**Comment by portal2707070** [comment]
idk why it doesnt see device, i created hw-probe when meta quest 2 was not connected, but it is can be seen by adb

**Comment by The-personified-devil** [comment]
Have you verified that you actually launched SteamVR through the alvr dashboard? If SteamVR isn't running then alvr won't discover devices. Have you also verified that the headset is on the same network? And for wired usage have you followed the [guide](https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB))?

**Comment by portal2707070** [comment]
Have you also verified that the headset is on the same network? yes
And for wired usage have you followed the [guide](https://github.com/alvr-org/ALVR/wiki/ALVR-wired-setup-(ALVR-over-USB))? yes
Have you verified that you actually launched SteamVR through the alvr dashboard?  no
