### ISSUE TITLE
Wiki for Installing ALVR with Flatpak is kinda broken right now

### ISSUE THREAD

**Issue by waltercool** [alvr-org/ALVR#2264]
Hi there,

I'm not using the template because this is not a bug of ALVR, but about the github Wiki.

If you see this wiki page https://github.com/alvr-org/ALVR/wiki/Installing-ALVR-and-using-SteamVR-on-Linux-through-Flatpak , you can see it's entirely broken, the words "Installing-ALVR-and-using-SteamVR-on-Linux-through-Flatpak" are repeated everywhere by some reason and breaking CLI steps.

Screenshot:

![Screenshot_20240718_112120](https://github.com/user-attachments/assets/c84fd5e7-60f9-49d9-b7e0-66301d07187a)

--
Kind regards.

**Comment by zarik5** [comment]
Oh no, it's the funny bug @Meister1593
