### ISSUE TITLE
General questions about compatibility (especially ProtonGE)

### ISSUE THREAD

**Issue by rabejens** [alvr-org/ALVR#2287]
I don't know if that's the right place to ask or if that's more of a general SteamVR issue.

I am running Steam with SteamVR 2.6 on NixOS Unstable, using ALVR 20.6.1 (as I couldn't get any other version to work and 20.6.1 is the newest one in nixpkgs). I set it up with my Meta Quest 1.

My machine is an I7 9770K with RTX2080, using the nVidia driver 550.

For now, I have only got the SteamVR void and SteamVR home to work, and that only in Wayland mode. With X11, as soon as starting SteamVR,k it opens a black window that stays stuck even after SteamVR is closed, and after clicking the close button in the title bar for several times, I get a message that I have to log out and back in.

When starting any VR game, either SteamVR is not detected or it loads and silently crashes. Without SteamVR running, launching the game in SteamVR mode starts it in normal mode instead. With SteamVR started before, the `Launch` button becomes `Stop` and after about a minute or so, it reverts back to `launch`. When launching the game from inside SteamVR, the `Up Next` badge appears floating in the void, which then disappears after about a minute or so and nothing happens.

The games I tried were all Windows, running in Proton. Especially, I tried No Man's Sky with the newest ProtonGE Experimental and VRChat.

Do VR games work in general via Proton and do I just have bad luck or which ones are compatible and which ones not?

**Comment by momanx** [comment]
I didn't have any issues with getting games themselves running on Proton or running the current ALVR release. I am also on Nvidia (RTX 4070), running Manjaro, although my driver version is 555/NFB. Have you tried running newer drivers?

**Comment by rabejens** [comment]
Maybe it has to do with the special way how NixOS is laid out and how mine is set up (I am using Impermanence with only a select number of folders not being reset across reboots). This is handled by bind-mounts via FUSE and I also had problems setting the caps which I remedied by doing the setcap thing directly on the source directory that is bind-mounted into my home.

My next try will be using Distrobox with Ubuntu inside for Steam and ALVR. I think I can then use the launcher.

**Comment by Vixea** [comment]
From what I understand depending on what protonge version you install you may not have the openvr bindings needed to run Windows gsmes
