### ISSUE TITLE
Warped Left eye duplicated on Right (Beat Saber)

### ISSUE THREAD

**Issue by remivamp** [alvr-org/ALVR#2292]
## Description

The left eye is duplicated onto the right eye and warped

## General Troubleshooting
- [ Y] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ Y] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=5ab0ffc9aa

### Installation
**ALVR Version**:
2.8.1,2.9.1,nightly
**ALVR Settings File**:

**SteamVR Version**:
Previous branch, None, Beta Branch
**Install Type**:
- [ ] Source (ALVR-Launcher)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by The-personified-devil** [comment]
This is a Proton/SteamVR issue, not an alvr one. See https://github.com/ValveSoftware/Proton/issues/6638
