### ISSUE TITLE
Audio shenanigans with dashboard

### ISSUE THREAD

**Issue by The-personified-devil** [alvr-org/ALVR#2299]
The dashboard tries to query audio devices or something even though pipewire makes this obsolete. Should be removed

**Comment by zarik5** [comment]
Ive discussed this with @Meister1593 and he said it's fine. I was the one insisteing in keeping it like it is because it minimizes platform specific code divergence

**Comment by Meister1593** [comment]
> The changes would be incredibly minor only though and it improves compatibility with people that only have pipewire installed and not the translation layers for alsa or jack (although that won't be a lot of people). But yea it isn't important and we could probably just ignore it.

If you can do it better, go for it but when i tried it myself, i started to use a ton of platform platform specific code blocks and it was starting to get very messy

Will be happy to see if it can be improved
