### ISSUE TITLE
Controller not recognized

### ISSUE THREAD

**Issue by rtlnut** [alvr-org/ALVR#2302]
## Description
When I open the alvr client on Quest2, it doesn't recognize my controller, and it seems that all the controller buttons are disabled. I can't open the system menu, and I can only reset the view by long pressing the Menu button.
This bug does not affect me connecting to the computer and entering Steam Home, but my controller is still not recognized after entering.
I don't have a specific way to reproduce this bug. It seems to disappear after a few retries, but it will also appear again.
![9c60245f2b4366631b5e34fa76a7c7d](https://github.com/user-attachments/assets/a879c960-9bb9-4d8d-9aca-dc57db5047a5)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
idk

### Hardware
**CPU**: i5 7300HQ

**GPU**: GTX 1060

**GPU Driver Version**:  32.0.15.5612

**Audio**:

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: [session.json](https://github.com/user-attachments/files/16451710/session.json)

**SteamVR Version**: 2.7.4

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** : Windows 10 64-bit (10.0, Build 19045)

**Comment by The-personified-devil** [comment]
In v20.9.1 your controllers should only be simple stars made out of wires. But not being able to open system view really sounds like a quest issue, since alvr doesn't really have the ability to influence that

**Comment by rtlnut** [comment]
> In v20.9.1 your controllers should only be simple stars made out of wires. But not being able to open system view really sounds like a quest issue, since alvr doesn't really have the ability to influence that

The report screen can be opened by clicking the menu button five times, which is the only way to open the menu after a bug has appeared, after which the controller can return to normal. But I couldn't shut down the device properly, because the controller was still disabled on the screen where I chose to shut down or restart the device.

**Comment by zarik5** [comment]
This is very odd, it wasn't uncommon to have ALVR lock up the whole OS, but this was years ago on the Quest 1.
