### ISSUE TITLE
High decode latency

### ISSUE THREAD

**Issue by AngelBePro** [alvr-org/ALVR#2305]
## Description

Randomly getting over 100 ms in decode latency

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=f8bcd51ea3

### Installation
**ALVR Version**:
v20.9.1

**ALVR Settings File**:
[session.json](https://github.com/user-attachments/files/16476814/session.json)

**SteamVR Version**:
SteamVR 2.7.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by AngelBePro** [comment]
I forgot to point out this only happenes in high bitrate, after more than 60 mbps or so. With a Quest 2.

**Comment by The-personified-devil** [comment]
The hardware decoders only support a certain amount of bitrate. Now 60 mbps seems pretty low depending on the codec used, but have you checked actual vs expected bitrate? If the actual is a lot higher then it's probably just maxxing out the hardware decoder. At that point it's basically just a configuration issue and you need to turn down the bitrate or check if you can achieve a better looking configuration with a different encoder.

**Comment by AngelBePro** [comment]
Here is the statistics tab while I'm playing at 85mbps constant in beat saber. I'm just not sure if the actual bitrate is too high since its always lower than expected.
![image](https://github.com/user-attachments/assets/ffc94fd1-eb58-46f8-b61d-3d0b416c8ef8)

**Comment by AngelBePro** [comment]
I also find out this happens when I rotate at a position but I could be wrong https://imgur.com/a/JP6O0MB

**Comment by The-personified-devil** [comment]
That's actually really weird. Iirc people reported that decoder latency increases after about 150Mbps for Hevc, but your actual bitrate is still comfortably below that. And the bitrate doesn't seem to increase when decoder latency increases. The only thing I can recommend is using h264 with a higher bitrate for the time being. But this should probably be looked into further.

**Comment by failboat78** [comment]
I noticed this as well. It seemed like the bitrate slider was not being respected - and some multiplier was being applied. 

Depending on headset HEVC works well if you stay below a certain limit. Seems to be about 200Mbit for quest2/3  - after that it struggles - the symptom of which is huge decode latency. 

My fix was to leave the slider alone and not increase it to 200! And to try disable all adaptive stuff.

**Comment by AngelBePro** [comment]
My friend also uses ALVR via USB (he is using a really good cable) and he is experiencing the same issue at the same bitrate values. Just to point out not sure if it helps

**Comment by AngelBePro** [comment]
What i just learned was that I was on a very low resolution before, 1440 p and now when I use 2144 p no matter the bitrate it just gets to 100 ms. If it is possible im linking my current config, try it out if you have a quest 2 so I can know if its just me or someone else.

**Comment by failboat78** [comment]
If you set things too high it will cause this. Look at the acual bitrate being sent in the statistics screen - if this goes over 200 you will have problems. 

When you say latency is 100ms break that down by looking at statistics - where does most of it come from? If it's decode latency then you are overloading the headset.

**Comment by The-personified-devil** [comment]
Did you read the rest of the issue?

**Comment by failboat78** [comment]
The framerate graph above looks very strange - why does the framerate go so high? What target rate is set on headset?

I use 90 and it seems to be stable around that:
![image](https://github.com/user-attachments/assets/a9b50261-c118-408e-9e41-513fe4a58309)

**Comment by The-personified-devil** [comment]
> The framerate graph above looks very strange - why does the framerate go so high? Client is set at 120 but streamer is at 90? Try setting them both to 90.

The streamer framerate goes rather high, but that doesn't matter, it's a factor that's already included in the bitrate. And both are set at 120, you can literally see the streamer framerate dip below 120 to somewhere around 90 in the graph, it's just one of the low spots. If it were actually at 90 then that would be the middle of the pack, not the bottom. (and that's regardless of the fact that it's impossible to configure deviating framerates and basically impossible for something to fail for them to end up set to deviating values)

**Comment by AngelBePro** [comment]
What helped me so far is foveated encoding, which I normally disable since I find it ruining the quality

**Comment by AngelBePro** [comment]
HDR also made the client fps really bad, but that's only with the foveated encoding. I'm no scientist and I guess that the foveation messes with it somehow. Im going to stick to foveated encoding for now.

**Comment by zarik5** [comment]
@AngelBePro if you're using latest release or master, foveated encoding uses the old client renderer. There is a new renderer but we ported over only the HDR/color range code. So when you use foveated encoding you're also using the old HDR/color range code.

**Comment by FoxbitDreamtail** [comment]
Just FYI, this is still an issue. I tested it the other day and the latest nightly. I think it was from two days ago and it still had this issue.

**Comment by AngelBePro** [comment]
I just want to say that there is a limit to how much data you can use as I was using 120 hz with medium res, which isn't that stable without foeviated encoding. My question is is it possible to get stable latency without foeviated encoding? Because when I was testing I needed very low res to get it working.
