### ISSUE TITLE
Does ALVR also support wired VR headsets with an HDMI or DisplayPort cable

### ISSUE THREAD

**Issue by comsyspro** [alvr-org/ALVR#2306]
Not all VR headsets have a wireless connection and have a USB data cable together with an HDMI or DisplayPort cable. Normally you connect these HDMI or DisplayPort cables to the GPU on the local PC. Is it also possible to use ALVR for these VR headsets? If not, would there be a solution to support this?

And can you use ALVR for self developped VR apps (Unreal Engine, Unity etc.) or is it only usable for Steam VR?

**Comment by zarik5** [comment]
No, ALVR cannot support video cables. In the headsets that don't advertise this functionality simply the USB controller doesn't support video in.

**Comment by zarik5** [comment]
> And can you use ALVR for self developped VR apps (Unreal Engine, Unity etc.) or is it only usable for Steam VR?

Currently ALVR requires SteamVR. SteamVR is a VR runtime that takes care for talking with the display driver and games to make the whole thing possible. We are working on adding support with Monado, which is another VR runtime.

**Comment by comsyspro** [comment]
Thank you for the clarification. I'm looking for a remote VR solution which also supports wired VR Headsets for an universal usage.

**Comment by zarik5** [comment]
The only solution I know of is the Pico Neo 3 Link, but it's quite old at this point.

**Comment by comsyspro** [comment]
Probably I have to begin to develop something similiar like ALVR but for wired headsets.

**Comment by zarik5** [comment]
Maybe I misunderstood your question. You want to use ALVR with a PCVR wired headset? But what's the point? ALVR is lke a bridge to play PCVR games, but PCVR headset can already do that natively without ALVR.

**Comment by The-personified-devil** [comment]
I'm pretty sure they mean streaming to a wired device via an extra dongle that connects to the headset

**Comment by zarik5** [comment]
Technically ALVR could be ported to something like a Raspberry Pi that provides hdmi out but performance would not be great

**Comment by comsyspro** [comment]
I want to stream VR applications from remote GPU servers (in datacenter) to a VR headset which is connected an a small computer. ALVR can help here for wifi headset. But there are also professional VR headsets which do not have an airlink or wifi connection (only HDMI or DisplayPort). I found this project here and asked if this could be done with AVLR. Do you know if there exists a github project for this kind of use case? Or would it be possible to extend AVLR for wired VR headsets?

**Comment by zarik5** [comment]
You can look into [ALXR](https://github.com/korejan/ALVR) which is a fork of ALVR supporting your usecase. We plan to add PC client when we implemented the decoder. Someone may be working towards this.

**Comment by comsyspro** [comment]
Thank you for this link. I'll try it out.
