### ISSUE TITLE
Glitched video in headset for every game (tested with Superhot VR) 

### ISSUE THREAD

**Issue by vibudh007** [alvr-org/ALVR#2315]
## Description
All games have glitched/corrupted video in the Quest 2 (ALVR installed via Quest store) as shown in the included screenshot.
SteamVR Home, and the waiting area are not glitched, but the steam menu brought up by the menu button is also glitched.
Tracking works fine though.

I should mention I switched to Fedora from Arch to fix this exact issue. In Arch, I was using mesa-tkg-git (which I installed a long time ago and forgot about), and reinstalling upstream mesa, vulkan-radeon and va-api drivers fixed the issue mostly. The menu was still glitched, which is what prompted me to try a "more stable" OS, which ended up having the same exact issue.

Till now I have only tried using the freeworld alternatives of the va-api drivers, but I read somewhere that va-api is not even supported by Quest 2, so that's probably not the problem. I feel there's something wrong with video drivers, but as this is a fresh Fedora install, and a fresh everything install basically, I think the issue is beyond the OS.

![Screenshot from 2024-08-06 16-09-24](https://github.com/user-attachments/assets/215068f5-6c9a-4366-ba8e-f5ddf5293181)
The Waiting Area screen looks fine
![Screenshot from 2024-08-06 16-10-44](https://github.com/user-attachments/assets/52738e98-e763-4fb7-a20c-dfab44e62825)
The Menu is glitched
![Screenshot from 2024-08-06 16-09-34](https://github.com/user-attachments/assets/dbd95565-236c-4fa1-bfcf-ab6374d16c72)
The game loading heads up looks fine as well
![Screenshot from 2024-08-06 16-10-03](https://github.com/user-attachments/assets/574c167a-31b4-49e8-9961-ae91b973d289)
![Screenshot from 2024-08-06 16-09-55](https://github.com/user-attachments/assets/d5a2b435-f203-45b5-8698-80a44ceb2fb0)
Once I enter the game (SuperHot VR in this case), everything is corrupted beyond recognition.
![Screenshot from 2024-08-06 16-10-20](https://github.com/user-attachments/assets/9b5f2074-df5f-43f6-aeca-9e275f7af735)
When in game, the main screen of the menu is fine but the rest is glitched.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: https://linux-hardware.org/?probe=fd9d1ea7b8

**CPU**: AMD Ryzen 9 5900HX 

**GPU**: AMD Radeon 6800M

**GPU Driver Version**: mesa-vulkan-drivers 24.1.5-2.fc40, mesa-va-drivers-freeworld 24.1.5-1.fc40

**Audio**: Pipewire

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: All the settings are at default.

**SteamVR Version**: 2.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Fedora Linux 40 (Workstation Edition)

**Comment by Macjja** [comment]
Do other games have that rendering issue? Specifically a game that would be running in vulkan, like VRChat? I find that OpenGL games tend to not render correctly in the steamvr runtime, and give me the aforementioned glitchiness in game. As for the menu afaik that hasn’t been rendering correctly for most people

**Comment by vibudh007** [comment]
@Macjja 

![Screenshot from 2024-08-06 18-43-49](https://github.com/user-attachments/assets/fef9d900-d48f-45ba-9b0a-21c93b599f48)
PC view of the VRChat Login Screen
![Screenshot from 2024-08-06 18-43-52](https://github.com/user-attachments/assets/718fa4bd-2c21-44c4-ad48-f600e2d6efd0)
Quest 2 View.

All games seem to have this issue.

Could you link me some comments about other people's menus being glitched like this?

Also, the whole alvr portable binary thing seems to be very finicky. I heard that the appimage is discontinued, the flatpak takes time to build instead of just installing it from flathub, and I don't see anything other than the binary in the releases. Is alvr in any distro's main repo?

**Comment by Macjja** [comment]
>Could you link me some comments about other people's menus being glitched like this? 

This was anecdotal, and related to [this image you sent](https://private-user-images.githubusercontent.com/69423099/355483531-52738e98-e763-4fb7-a20c-dfab44e62825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjU0NzEsIm5iZiI6MTcyMjk2NTE3MSwicGF0aCI6Ii82OTQyMzA5OS8zNTU0ODM1MzEtNTI3MzhlOTgtZTc2My00ZmI3LWEyMGMtZGZhYjQ0ZTYyODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE3MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNzY0ZDQ2ZWZkZGFiNWExNTk0YzBjMzhjYTc4ZjM1YzgxMGUwYjcxOTdlNTg2ZGEyMTM4ZmRhM2I3ODBiZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C_fXHirdGP1s7ldC9d64vzqWPOySwm6DNEtHKY1pTw4)

**Comment by vibudh007** [comment]
@Macjja  DRI_PRIME=1 fixed the glitching in-game, which now feels like a silly mistake on my part.

There's still the issue of the glitchy menus, which are obviously unusable. Running Steam with DRI_PRIME has its own issues (the window doesn't wanna render at all, for me) so I can't try that as a fix. 

Also, is there a way to permanently add the ALVR add-on to SteamVR? It seems like every time I launch SteamVR without going through ALVR, I get a "Headset not Detected" error.

**Comment by Macjja** [comment]
@vibudh007 
> DRI_PRIME=1 fixed the glitching in-game, which now feels like a silly mistake on my part.

Didn’t notice you had a mobile config, should’ve mentioned that as well since I also have a mobile config😅

>Also, is there a way to permanently add the ALVR add-on to SteamVR? It seems like every time I launch SteamVR without going through ALVR, I get a "Headset not Detected" error.

Not as far as I’m aware, you have to launch steamVR through ALVR every time you want to use ALVR with it; but since the ALVR server needs to be running anyways it shouldn’t be too much of a hassle
