### ISSUE TITLE
SteamVR crashes upon PhoneVR client connecting to ALVR

### ISSUE THREAD

**Issue by TheUnknownHack3r** [alvr-org/ALVR#2316]
## Description
The SteamVR software crashes shortly after a PhoneVR client (a Motorola G32) is paired to ALVR. The view also freezes in PhoneVR until SteamVR closes.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: `hw-probe -all -upload` at https://linux-hardware.org/?probe=ae2c7e70bf

**CPU**: Intel i5-5200U (4) @ 2.7GHz

**GPU**: Intel HD Graphics 5500

**GPU Driver Version**: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.5-arch1.1

**Audio**: PulseAudio (on PipeWire 1.2.2)

### Installation
**ALVR Version**: v20.8.0

**ALVR Settings File**: Unable to locate

**SteamVR Version**: 2.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch Linux

**Comment by TheUnknownHack3r** [comment]
(I'm using PhoneVR since the ALVR android client is just a black screen that apparently doesn't do anything...)

**Comment by TheUnknownHack3r** [comment]
Here's the [vrserver.txt](https://github.com/user-attachments/files/16534966/vrserver.txt) file if anyone wants to take a look.

**Comment by The-personified-devil** [comment]
Could you try this?
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#bindings-not-workinghigh-cpu-usage-due-to-bindings-ui

**Comment by TheUnknownHack3r** [comment]
Alright, I just tried it, and it looks like it patched. Still crashes though.
[Here's the logs after the patch.](https://github.com/user-attachments/files/16536404/vrserver.txt)

**Comment by TheUnknownHack3r** [comment]
Using ALVR v20.8.1 solves the crashing and you can get to "steaming". But I think PhoneVR has an issue as the video doesn't work.
