### ISSUE TITLE
Change hand tracking controller bindings

### ISSUE THREAD

**Issue by nomlasvrc** [alvr-org/ALVR#2318]
(This issue was translated by DeepL translation)
When I play VRChat, the hand tracking controller often malfunctions.
However, when I turn on Only touch, it is inconvenient because I cannot move.
So I would like to add a setting to change the bindings or disable unwanted bindings.
This will prevent accidental jumps and mutes.

**Comment by The-personified-devil** [comment]
The vrchat beta has a feature where it has it's own handtracking gestures. If you use nightly alvr (the alvr feature needed sadly isn't in a release yet) you could try that out and see if that works for you

**Comment by nomlasvrc** [comment]
I tried nightly alvr and it worked as I expected. Thank you!
