### ISSUE TITLE
Linux, ALVR fails to use discrete Nvidia GPU

### ISSUE THREAD

**Issue by oxygencamera** [alvr-org/ALVR#2325]
## Description
I have the latest version of ALVR and my SteamVR is on the stable branch. My Quest 2 properly connects to ALVR and SteamVR also launches properly. There are two issues - ALVR isn't detecting my discrete Nvidia GPU and instead always uses my integrated AMD CPU to launch everything (for Nvidia, I have the latest available main and cuda drivers installed). And after I launch ALVR inside of my headset, it connects me, and it's just a black screen. Applying some fixes from "Linux Troubleshooting" page, (VAAPI encoder fix, and some other launch options command for SteamVR) I was previously able to get to the SteamVR grid, but the overlay of it wasn't visible.

At this moment, I have 3 launch options in SteamVR properties in this order - 
WAYLAND_DISPLAY='' %command% ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% __GLX_VENDOR_LIBRARY_NAME=nvidia __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json %command%

## General Troubleshooting
- [+] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [+] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

## Environment
-

### Hardware
https://linux-hardware.org/?probe=720075365b

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: -

**SteamVR Version**: latest stable release, version.txt says 1721847232

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [+] Portable (`zip`) (i'm not sure, it was tar.gz of a launcher)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Fedora 40

**Comment by Meister1593** [comment]
Dashboard will warn about this constantly because it doesn't have same GLX/optimus variables set

**Comment by failboat78** [comment]
Look at the statistics graph to find cause of latency. If its decode latency then you are overloading the headset - turn your settings down. 200Mbit hevc is a reasonable maximum for quest2/quest3 - if you go above this latency spikes. 

The bitrate slider is not behaving as expected either, don't move it to 200. Leave it at 50 then test, then increase small bit and test again.
