### ISSUE TITLE
[HELP] Using H264 doesn't work

### ISSUE THREAD

**Issue by AngelBePro** [alvr-org/ALVR#2327]
## Description

Whenever I try to use h264 I end up with `Encoder: Provided device doesn't support required NVENC features` I do not see any other error other than this.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=f8bcd51ea3
### Installation

**ALVR Version**:
20.9.1

**ALVR Settings File**:
20.9.1

**SteamVR Version**:
2.7.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by failboat78** [comment]
Test that your nvidia drivers are working by running "nvidia-smi".

**Comment by AngelBePro** [comment]
That's not it as using HEVC works fine with nvenc. It only appears with h264. Using obs for example with h264 nvenc works fine, so its not a issue with the drivers.

**Comment by AngelBePro** [comment]
Using the nightly build fixed my issue.
