### ISSUE TITLE
No network ports open on server

### ISSUE THREAD

**Issue by theailer** [alvr-org/ALVR#2333]
## Description
The streamer application won't open any of the network ports

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
Yes
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)
Yes
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=f3434cd685

### Installation
**ALVR Version**:
20.9.1
**ALVR Settings File**:
[session.json](https://github.com/user-attachments/files/16636239/session.json)

**SteamVR Version**:
Build id
15141130

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source
Tried all of the above more or less. 

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
`PRETTY_NAME="CachyOS"`

**Comment by The-personified-devil** [comment]
Are there any steps to reproduce? Did you take a look at alvrs firewall settings?

**Comment by theailer** [comment]
Ran the setup to add the firewall settings.
I've disabled my firewall completely.
But it does not open any ports on the server, at all. And nothing in ALVR log files about it either.

**Comment by The-personified-devil** [comment]
Are you actually starting steamvr through alvr? Like does the dashboard say that its connected?

**Comment by theailer** [comment]
Sorry, it was not connected to steamvr. Once i added ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command% to the steamvr command line it connects
