### ISSUE TITLE
Audio and Microphone doesnt work

### ISSUE THREAD

**Issue by Molwi** [alvr-org/ALVR#2342]
## Description

I just can't get audio and microphone working, I've tried everything.

**NOTE**: I am using the wired method with ADBForwarder

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: Intel(R) Core(TM) i3-10100F (8) @ 4,30 GHz

**GPU**: NVIDIA GeForce GTX 1650

**GPU Driver Version**: 555.58.02

**Audio**: PulseAudio (on PipeWire 1.2.2)

### Installation
**ALVR Version**: 20.9.1

**ALVR Settings File**: *?*

**SteamVR Version**: 2.8.3 *(Latest)*

**Install Type**:
- [x] ALVR Launcher (`tar.gz`)
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Arch Linux (Kernel: 6.10.5-arch1-1)

**Comment by The-personified-devil** [comment]
You need to set the alvr devices as default using the audio settings application of your choice. Note that you can only do this when the stream is connected, so it can be a tad bit annoying.

**Comment by Molwi** [comment]
> You need to set the alvr devices as default using the audio settings application of your choice. Note that you can only do this when the stream is connected, so it can be a tad bit annoying.

Thank you so much, I didn't think of that
