### ISSUE TITLE
Issue as described in Linux Troubleshooting about Failed to Create VAAPI encoder, but I'm on amdgpu not mesa-va.

### ISSUE THREAD

**Issue by TH3C4V** [alvr-org/ALVR#2345]
Im trying to use ALVR on Nobara Linux (fedora40) but am getting the VAAPI encoder issue on AMDGPU and not mesa-va drivers. The troubleshooting guide links to a page with dnf install and swap commands, but the mesa-va-drivers and vdpau-drivers aren't there so it says "Nothing to do. Job complete;" on the swap commands. I launch alvr and same thing. I see nothing in the troubleshooting guide regarding this. What do I do?

**Comment by TH3C4V** [comment]
Fixed with resetting settings.

**Comment by buddha314** [comment]
Can you be more specific?

**Comment by TH3C4V** [comment]
> Can you be more specific?

I'm sorry man this was too long ago, and considering I got it fixed by just resetting to default settings in ALVR, I wouldn't worry about it man. This issue is closed for a reason.

That said you probably commented knowing that and might have an issue of your own, could you be more specific?
I don't know exactly what you want from me being more specific. I'm sorry.

Also I can't test anything here because I'm on a manual Arch install now.
