### ISSUE TITLE
USB ADB Forwarder integration into the launcher

### ISSUE THREAD

**Issue by WaveSmashies** [alvr-org/ALVR#2349]
I'd like to see a setting which adds a simple button that pushes the proper ADB commands needed for USB connection with ALVR. Just because it's kinda hard for people new to ALVR to figure out ADB Forwarder. Especially since it's slightly broken. You have to plug in the headset and accept the prompt before even opening ADBForwarder, there's no "Press Space to retry" or anything.

I always help people get ALVR because it's free and in my experience is far more stable than the Oculus PC app, Steam Link, and Virtual Desktop. Plus it works over USB unlike those last 2. So it would be easier and more convenient overall if USB connections didn't require external scripts and dealing with ADB commands.

**Comment by vosk** [comment]
Can we use this?
https://docs.rs/adb_client/latest/adb_client/
