### ISSUE TITLE
Hostname "xxxx.client" doesn't match network configuration

### ISSUE THREAD

**Issue by zatricky** [alvr-org/ALVR#2360]
## Description

**ALVR Version**: v20.9.1

The client on the device refers to itself as having a hostname of "xxxx.client". I noticed before in a previous version of ALVR that it used to be "xxxx.client.alvr". Hostname has a very specific meaning in networking. In my network I have configured a domain, so my desktop for example can be reached by pinging "tricky-desktop.private.example.com". Devices getting IP addresses on the network get a full hostname. Most consumers get a basic local network configuration on their routers, with the local network being set as "xyz.local", for example.

If I ping the headset I get responses from "quest.private.example.com". Pinging "1818.client", as it currently shows, gets nothing.

I suppose then the question/request here is, where does this "xxxx.client" convention come from? Is it a bug in the headset (Quest 3 in this case) or is it something ALVR does? And, of course, if it is something in ALVR, can it be fixed to use the real hostname? The other option is that maybe it is just a device name that anyway doesn't need the "hostname" label attached.

**Comment by zarik5** [comment]
The original idea was to add TLS authentication, but then we didn't implement it. Now in the master branch, the hostname is used for mDNS and needs to end with `.local.`.

**Comment by The-personified-devil** [comment]
The currently carries no meaning at all, so it doesn't matter and it'll match up and actually carry meaning on the next major release.
