### ISSUE TITLE
Unable to select older versions using ALVR Launcher

### ISSUE THREAD

**Issue by Alkemist0** [alvr-org/ALVR#2362]
## Description

When using ALVR Launcher, I am trying to install an older version, but the version selector does not allow me to click any of the options. Tabbing into the dropdown does not work either.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[HW probe](https://linux-hardware.org/?probe=86652e28dc)

**CPU**:
Ryzen 9 5900X
**GPU**:
RTX 3070
**GPU Driver Version**:
560.35.03

### Installation
**ALVR Version**:
Not installed yet

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
EndeavourOS

**Comment by The-personified-devil** [comment]
Known bug, fixed by 404e7bbff11f6fa0acf90bccc8c6890146c03e39 already
