### ISSUE TITLE
Steam VR space instead of VR Regatta

### ISSUE THREAD

**Issue by vlad-cool** [alvr-org/ALVR#2364]
## Description

I am trying to play VR Regatta. Game launches only in window, it gets input and movement from headset and controllers, but in headset I only see steamvr space like when game isn't launched. Other games (at least beat saber works as should). Similar game from same developer (MarineVerse Cup) does not work too.

## General Troubleshooting
- [✅ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [✅ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=74cc53bc31

**CPU**: Ryzen 9 6900HS

**GPU**: RTX 3080 Mobile / Max-Q

**GPU Driver Version**: 555.58.02

**Audio**:

### Installation
**ALVR Version**: 20.10.0

**SteamVR Version**: 2.7.4

**Install Type**:
- [✅ ] Portable (`zip`) (From ALVR Launcher)

**OS Name and Version**: Fedora Linux 40 (KDE Plasma)

**Comment by vlad-cool** [comment]
Works with latest nightly build

**Comment by failboat78** [comment]
How is this related to alvr?
