### ISSUE TITLE
Encoder reports device missing features

### ISSUE THREAD

**Issue by MasterDomino** [alvr-org/ALVR#2365]
## Description
ALVR reports: Encoder: Provided device doesn't support required NVENC features
this is hard to get out of, some settings when changed cause this, this wont allow to progress further.
this is reproducible on my setup 100% of the time, so i can gather even more detailed logs if this can help.

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**HW-PROBE**: https://linux-hardware.org/?probe=a816da0c6b

**CPU**: Ryzen 7 5800X

**GPU**: Nvidia RTX 3070 FE

**GPU Driver Version**: Driver Version: 535.183.01   CUDA Version: 12.2

**Audio**: onboard

### Installation
**ALVR Version**: v21.0.0-dev01+nightly.2024.08.25

**ALVR Settings File**: [session.json](https://github.com/user-attachments/files/16820914/session.json)

**SteamVR Version**: Beta v2.8.4 and Stable 2.7.4

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [X] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Debian GNU/Linux 12 (bookworm)

**Comment by The-personified-devil** [comment]
Nvenc only supports a vertical resolution of 4096. You have your per image width set to 2144, which doubled up ends up being larger than the 4096.

**Comment by MasterDomino** [comment]
![obraz](https://github.com/user-attachments/assets/f3a6c1a7-9769-4c6c-9371-1350c8f0fe14)
![obraz](https://github.com/user-attachments/assets/81210a1a-906b-48b5-a279-4adadaaa6810)
those are default settings, the only thing i adjusted from those is that i disabled optimize game render latency and adapt to framerate, and selected HEVC as a codec

**Comment by The-personified-devil** [comment]
A) have you tried actually just decreasing the resolution and checked if it works
B) Foveated encoding should be enabled ny default and would bring the resolution actually processed by the encoder back in bounds, but it seems its turned off for you

**Comment by MasterDomino** [comment]
Okay that is on me, although this behavior isnt documented well enough, wasnt able to find this on wiki or in the notes, therefore id look into adding that there, might look into this today.

suggested change would be to add a note stating that if foveated encoding is disabled it makes encoder work with twice the eye size, or another way around the problem is introducing a check or a limit to the resolution size to what nvenc allows but thats not up to me to decide.

**Comment by cowshu** [comment]
Still happening on my system. 
Occurs on my Arch Linux and my Pop OS system.
Throws this error whenever it starts streaming to my Quest 2 with foveated encoding turned off.

Sucks because I hate foveated encoding because my headset doesnt have face tracking.
