### ISSUE TITLE
alvr opens, but when opening steam vr it crashes gnome on fedora 40.

### ISSUE THREAD

**Issue by NoSadBeHappy** [alvr-org/ALVR#2370]
## Description

When starting steam vr through alvr on fedora 40, it attempts to open, but ends up just crashing gnome.

## General Troubleshooting
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=b465342a08

- fedora 40
- gnome 46.4
- let me know if there is something else I can let you know.
**CPU**:
Ryzen 5 5500
**GPU**:
rx 580
**GPU Driver Version**:
how do I find this?
**Audio**:

### Installation
**ALVR Version**:
v20.10.0
**ALVR Settings File**:
where do I find this?
**SteamVR Version**:
2.7
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Fedora Linux 40 (Workstation Edition)

I ran `journamctl` and found this error, which lead me to disable the color correction settings. This seemed to fix it once, but after relaunching it faild with the same error. This log is with color correction disabled.

https://gist.github.com/NoSadBeHappy/de654f6a6038fca4d246b60d1c5dfc98

**Comment by The-personified-devil** [comment]
See https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting#wayland
Also note that you currently always need the first entry on that page to get alvr working on linux

**Comment by NoSadBeHappy** [comment]
Sorry I forgot to mention. I already did this fix, as well as the VAAPI driver fix. I didn't try the first one listed previously, but I just tried it, and now steamvr just doesn't open at all, sometimes causing steam itself to crash. 

Here is my steamVR launch options:
`WAYLAND_DISPLAY='' %command%, /home/trevorchung/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%`

**Comment by failboat78** [comment]
> Sorry I forgot to mention. I already did this fix, as well as the VAAPI driver fix. I didn't try the first one listed previously, but I just tried it, and now steamvr just doesn't open at all, sometimes causing steam itself to crash.
> 
> Here is my steamVR launch options: `WAYLAND_DISPLAY='' %command%, /home/trevorchung/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%` (I also tried it with the default one, which should be the right path)
> 
> I also did read that steamVR not opening is caused by the wrong path, and I tripple checked that I had it right.

Your launch options are incorrect. Change them to this "QT_QPA_PLATFORM=xcb ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%"

The %command% part should be there only once - at the end.

**Comment by NoSadBeHappy** [comment]
Ohh, thanks for the help. Out of curiousity, why use QT_QPA_PLATFORM=xcb instead of WAYLAND_DISPLAY=''.

As for the %command%, sorry about that I totally did that wrong, my bad.
