### ISSUE TITLE
Launcher v20.10 cannot download nightlies

### ISSUE THREAD

**Issue by failboat78** [alvr-org/ALVR#2379]
As subject. Older version did allow nightly downloads. 

Same behavior on both windows and linux. Dropdown box won't let you pick "nightly".

This is a bug right?

bad launcher - https://github.com/alvr-org/ALVR/releases/tag/v20.10.0
good launcher - https://github.com/alvr-org/ALVR/releases/tag/v20.9.1

**Comment by zarik5** [comment]
lready fixed in nightly launcher

**Comment by The-personified-devil** [comment]
Duplicate of #2377 and #2362 btw

**Comment by failboat78** [comment]
Damnit I even searched for dups >.<
