### ISSUE TITLE
Linux libc version 

### ISSUE THREAD

**Issue by 934647971** [alvr-org/ALVR#2386]
Hello, this is not a question, this is just a question. The ALVR Luncher application runs on Linux and relies on GLIBC_2.29\GLIBC_2.31\GLIBC_2.32\GLIBC_2.33\GLIBC_2.34\GLIBC_2.35. I would like to know if this is necessary, and whether this version can be lowered appropriately?

**Comment by 934647971** [comment]
Is it possible to consider putting the glibc library in the local reference of the project file, and not letting the program go to the system to query?

**Comment by The-personified-devil** [comment]
That's entirely out of the scope of the alvr project, that's an issue with/question about the rust compiler itself, you'd have to go looking on your own. But the normal way is just to use a container with an older libc.

**Comment by 934647971** [comment]
Ok, thank you for your answer
