### ISSUE TITLE
foveated encoding off --> right eye shows a black image

### ISSUE THREAD

**Issue by miscrtnone** [alvr-org/ALVR#2393]
## Description
if i turn off foveated encoding the right eye shows a black image.
it only shows an image if i turn on foveated encoding

## General Troubleshooting
tried different (lower) encodingresolutions if it makes a difference, always same behavior

### Hardware
quest 3

**CPU**:
zen 3 

**GPU**:
nvidia rtx 4090

**GPU Driver Version**:
560.81

### Installation
**ALVR Version**:
v20.11.0
**ALVR Settings File**:
[session.json](https://github.com/user-attachments/files/16993424/session.json)

**SteamVR Version**:
Version 2.7.4 (1721847232)

**Install Type**:
manually install via apk

**OS Name and Version** 
win10 latest

**Comment by The-personified-devil** [comment]
Likely related to/caused by: 87c32f5afea4dea221b79774ad1086ec68b59b2c
