### ISSUE TITLE
Enabling "VRCFaceTracking" Causes Client to Hang and Disconnect

### ISSUE THREAD

**Issue by PaintThinnerAddict** [alvr-org/ALVR#2395]
## Description

On V20.11.0, whenever "VRCFaceTracking" is selected on the Presets settings tab for "Eye and face tracking", when a client tries to connect, ALVR reports the client to be disconnected, and the client is left on a black screen with loading dots. I am unsure if this only affects Quest Pro or if other headsets with eye or face tracking features.

This problem does not occur when setting  the "Eye and face tracking" to "Disable".

## Steps to Reproduce

1.  Set "Eye and face tracking" to "VRCFaceTracking".
2.  Attempt to connect to ALVR Server with client on the headset.

Expected Result: Headset connects successfully and displays VR content.

Actual Result: ALVR Dashboard states that the headset has disconnected and shows no warning about why. Client is stuck on a black screen with loading dots, not progressing past it.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=e746d8e01c

**CPU**:
AMD Ryzen 9 5900X
**GPU**:
Nvidia Geforce RTX 3090
**GPU Driver Version**:
560.35.05
**Audio**:
Motu M2 (Disconnected when running ALVR)
### Installation
**ALVR Version**:
v20.11.0
**ALVR Settings File**:
[session.json](https://github.com/user-attachments/files/16995513/session.json)
**SteamVR Version**:
2.7.4
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by The-personified-devil** [comment]
Could you try out vrchat osc and see if it behaves the same? Also do you have vrcfacetracking up and running when using eye tracking? And if you can you could use `adb logcat | grep "ALVR NATIVE-RUST"` to view the logs from the alvr client when connected over adb.

**Comment by Vixea** [comment]
This has already been tested as resolved in nightly

**Comment by PaintThinnerAddict** [comment]
Issue has already been resolved in nightly. Just awaiting a stable release fixing. In the mean time I will be using nightly.
