### ISSUE TITLE
High latency ingame. What am I doing wrong??

### ISSUE THREAD

**Issue by vibudh007** [alvr-org/ALVR#2396]
I play Half-Life Alyx on my gaming laptop and Quest 2.
The laptop has a Ryzen 9 5900HZ and a Radeon 6800M.
I'm on Fedora Workstation, with everything constantly updated.

Half-Life Alyx is run with the following launch options
`DRI_PRIME=1 gamemoderun %command% -novid -console -vconsole +vr_fidelity_level_auto 0 +vr_fidelity_level 3 +vr_render_scale 1.0 `

ALVR streamer on the laptop is the latest binary, and the client on the Quest 2 is from the Quest store.

I connect my laptop to my Quest 2 through a [Tenda V12](https://www.tendacn.com/product/v12.html). The router, laptop and the headset are all in the same room. The WiFi is 5GHz 867Mbps. Unfortunately connecting the laptop to the router via LAN is just too annoying to do, and doesn't help the situation much.

Here are my settings
![Screenshot from 2024-09-13 18-45-59](https://github.com/user-attachments/assets/a38e3b94-b2d8-48b5-a6c6-a94251a0fed4)
![Screenshot from 2024-09-13 18-46-08](https://github.com/user-attachments/assets/9f3e2c22-c2e3-4edf-9da2-05088e208d57)
![Screenshot from 2024-09-13 18-46-17](https://github.com/user-attachments/assets/c2535276-6031-4f07-ae8f-cd46387eb266)

And here are some statistics
![Screenshot from 2024-09-13 18-13-01](https://github.com/user-attachments/assets/fae954a5-a6bc-4db7-94da-f32497abc58a)
![Screenshot from 2024-09-13 18-11-33](https://github.com/user-attachments/assets/a383ec8e-92a8-47e6-8dc0-137cfea990b6)
![Screenshot from 2024-09-13 18-12-21](https://github.com/user-attachments/assets/660a23c6-c2f1-4180-b3a5-f15302678ace)

I constantly get bad compression-like pixellation, or slowdowns that make the game lag behind my movements. When this happens, I close the client and reopen it, and it usually gets better, but not for long.
Can anyone please help me get a smoother experience?

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: https://linux-hardware.org/?probe=fd9d1ea7b8

**CPU**: AMD Ryzen 9 5900HX 

**GPU**: AMD Radeon 6800M

**GPU Driver Version**: mesa-vulkan-drivers 24.1.5-2.fc40, mesa-va-drivers-freeworld 24.1.5-1.fc40

**Audio**: Pipewire

### Installation
**ALVR Version**: 20.10.0

**ALVR Settings File**: All the settings are at default.

**SteamVR Version**: 2.7

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Fedora Linux 40 (Workstation Edition)

**Comment by dyargici** [comment]
You say you are using the latest but in the issue you also specify v20.10.0 which is not the latest.  There was an important change made in v20.11.0 which will benefit you greatly if you are running on a laptop (assuming you have audio enabled).

Also...

I would start by setting your resolution to "Very Low", turn off "Adapt to Framerate" and set it to 30 to begin with.  Also use h264 to begin with.  Once you have it working, try switching to HEVC and messing about with the bitrate.

Afaik 120hz is not supported, switch that to 90. 

Good luck!

**Comment by vibudh007** [comment]
@dyargici 20.11is really new and I didn't notice it.

Thanks for all the info, I'll try it out tomorrow and report back :)

**Comment by failboat78** [comment]
Don't use 120 - you cannot have high quality at this setting in my experience.

**Comment by dyargici** [comment]
@vibudh007 - how did you get on?

**Comment by vibudh007** [comment]
@dyargici Sorry for the late reply.

Not sure if it was the 90Hz setting, the low resolution setting or the 30-50Mbps bitrate, but Half-Life Alyx is orders of magnitude better to play. Thank you for your advice, it should be visible to all new users.

Anyone who comes across this issue should do what dyargici says. It works.
