### ISSUE TITLE
PICO 4 Emulation / Serial number

### ISSUE THREAD

**Issue by MARK2580** [alvr-org/ALVR#2407]
## Description
Hello, I can't figure out how to use this program to tell SteamVR that I'm playing on PICO 4, and not Quest 2 or other VR headsets? There is a "custom" option, but I have no idea what the serial number of PICO 4 is. I tried entering A8110, but it doesn't work. I have the most common PICO 4 on 128gb.
![scr_16_09_2024_10_57_21](https://github.com/user-attachments/assets/92ce55d7-20c4-463f-bad5-faebd773e347)

**Comment by Mhowser** [comment]
I believe ALVR doesnt have the virtual 3D controller models for the Pico 4 yet, they are available here https://github.com/WiVRn/WiVRn/tree/master/assets/controllers/pico-4

**Comment by MARK2580** [comment]
> I believe ALVR doesnt have the virtual 3D controller models for the Pico 4 yet, they are available here https://github.com/WiVRn/WiVRn/tree/master/assets/controllers/pico-4

I'm more interested in SteamVR seeing my headset as a Pico 4, rather than as a Quest 2 for example...

**Comment by Timocop** [comment]
> > I believe ALVR doesnt have the virtual 3D controller models for the Pico 4 yet, they are available here https://github.com/WiVRn/WiVRn/tree/master/assets/controllers/pico-4
> 
> I'm more interested in SteamVR seeing my headset as a Pico 4, rather than as a Quest 2 for example...

SteamVR does not have the required files to fully emulate Pico 4. HTC Vive, Index, Quest are build-in already in SteamVR including models and bindings. (You can even find emulation settings in the SteamVR bindings without ALVR). ALVR has to ship with all required files to fully emulated Pico 4 devices, but i doubt that will happen.

**Comment by MARK2580** [comment]
That is, I will always see controllers from Quest 2 or 3 in my hands, instead of PIco controllers, as it happens with VD or standard software???

**Comment by aaaaaaa9beeep** [comment]
yall he means the headset emulation not the controllers
