### ISSUE TITLE
Question: Can ALVR be used with a SteamVR installation but without a Steam installation?

### ISSUE THREAD

**Issue by gkarpa** [alvr-org/ALVR#2411]
Hi,

as per the title, I'm interested in running OpenXR apps with the SteamVR runtime but in an environment that doesn't allow full Steam installations. We can, however, have a portable installation of SteamVR (the contents of steamapps\common\SteamVR) something like the procedure described [in this Valve article](https://partner.steamgames.com/doc/features/steamvr/enterprise). I gave ALVR a try since it seemed like a possible solution, but I noticed that it needs to launch Steam in its entirety at some points. Is this how it is or have I missed something around some advanced parameterizing?

Thanks in advance!

**Comment by The-personified-devil** [comment]
It is how it is, however it shouldn't be too hard to just rewrite those sections of the code. Beware that you'll lack steam's process reaper in that case and that steamvr likes to not close all it's processes nicely if something even slightly goes wrong. Also if you only need openxr, integration with the open source monado runtime is in the works for alvr (see https://github.com/alvr-org/Monado-ALVR), but there's no ETA when it will be in a actually usable state.

**Comment by zarik5** [comment]
It is possible. I know that my company uses offline-mode SteamVR packages, what have no Steam or cloud dependencies. These packages are distributed by HTC and are few and far apart. I think they don't have a SteamVR 2.0 package yet. Also unfortunately these packages are only for businesses, so you would have to contact HTC directly.

**Comment by gkarpa** [comment]
> It is how it is, however it shouldn't be too hard to just rewrite those sections of the code. Beware that you'll lack steam's process reaper in that case and that steamvr likes to not close all it's processes nicely if something even slightly goes wrong (this is the main blocker to adding a feature to optionally just launch a steamvr executable directly) (actually not sure about that, there exists some process reaping code in alvr).

We would happily welcome such a feature, even as experimental with its potential stability risks. Also ALVR with Monado sounds like a very attractive combo choice so I'll definitely keep an eye on that for the future.


> It is possible. I know that my company uses offline-mode SteamVR packages, what have no Steam or cloud dependencies. These packages are distributed by HTC and are few and far apart. I think they don't have a SteamVR 2.0 package yet. Also unfortunately these packages are only for businesses, so you would have to contact HTC directly.

Interesting info and we'll have to explore to that direction as well, sounds good.

@The-personified-devil and @zarik5 , great help and information, thank you so much both!

**Comment by gkarpa** [comment]
Actually, bringing back the subject, after some more searching I noticed that if I manually "Register the ALVR driver" in the installation tab of the Dashboard, and then run manually the standalone SteamVR (via vrstartup.exe), the dashboard seems to be detecting it and connecting to it successfully. Same steps as in https://github.com/alvr-org/ALVR/issues/2080 .

Then I was able to run the ALVR app in the headset (Quest3) and it seems to be working. One difference I noticed is that the SteamVR main menu looked different than what I've used to when running through Steam (looked older and was rendering different controllers than the Quest3's). Finally I was also able to run my app which, except from this error at the start

![alvr-error](https://github.com/user-attachments/assets/50942980-fe52-47fe-b21f-9d081efa6f90)

seemed to be running ok afterwards? I don't know if I'm neglecting something important from the registration process, but it looks encouraging nonetheless.

**Comment by Iemand005** [comment]
@The-personified-devil I don't think Steam reaper is a big deal and I find the tradeoff for having the much greater performance over having Steam try to kill SteamVR a very good deal. Steam has two issues. Sometimes it claims "app already running" while none of the steamvr related exes are actually running, ad sometimes SteamVR gets killed without it closing the TCP socket, leaving port 27062 "in use" by a non existent process and the only way to close the TCP socket is by signing off the user or rebooting, so you cannot launch SteamVR anymore which is incredibly annoying.

It wouldn't be difficult to make ALVR itself kill remaining SteamVR processes that are running when they shouldn't if necessary like when restarting SteamVR though I've never seen it do that with my own eyes. I don't expect it to even be a problem if SteamVR is launched while one of it's processes is somehow already running, if that ever even  happens. I can implement an ALVR reaper for SteamVR if you think it'd come in handy, but I don't think that'd be necessary, I'll keep using my implementation until I encounter a problem but it's very seamless for now, much better and more stable than using Steam actually.

I only saw you posted the reason why directly launching SteamVR isn't implemented after implementing it myself. I added it as an optional toggle for those who want to use SteamVR offline or want extra performance. My implementation doesn't affect ALVR by default, just opt-in which I believe is a good way to at least allow it even if there's somehow a risk in doing that.


As an answer to the question of this issue, yes you can use SteamVR without Steam. Vive gives Enterprise builds, but if you can't get a copy of those, just copy the SteamVR files from an installation downloaded by Steam and use that you don't need the entire pile of Steam garbage to use SteamVR and SteamVR responds way faster without Steam monitoring and controlling it.
