### ISSUE TITLE
Network rewrite

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#242]
* [X] ControlSocket
* [X] StreamSocket (UDP + TCP + QUIC)
* [x] Define packets and streams
* [ ] Integration
  * [x] Rewrite ClientConnection
  * [ ] Rewrite ServerConnection

**Comment by DavisNT** [comment]
I am still not sure whether using TCP is a good idea - whether TCP won't lead to buffering and delayed delivery of buffered data ("strange effects after network glitches" from user's perspective) in case of packetsloss.

**Comment by zarik5** [comment]
TCP will be the fallback option where UDP packets are blocked by some networks for some reasons. TCP will be used anyway for establishing the connection, for ping and shutdown signals.

**Comment by DavisNT** [comment]
I think it would be worth documenting the required open UDP and TCP ports (the PC ports that need to be accessible from Oculus Quest and Oculus Quest ports that need to be accessible from the PC) in a Wiki page (and probably in README.md as well). 

There is a Wiki page about running ALVR client and server on separate networks: https://github.com/JackD83/ALVR/wiki/ALVR-client-and-server-on-separate-networks 
however it mentions only opening UDP ports 9943 and 9944 on the server (to be accessible from the client). I guess on ALVR v12+ TCP port 8082 on server needs to be opened for web configuration to work from Oculus Quest. Is this port used for anything else? Do any other ports need to be opened on the server? 
Does the new network implementation also require server to client connections (if yes, I guess it will make harder to use ALVR over NAT, however I am not sure how common is such scenario)? 

As far as I remember the new implementation prevents connections from non-RFC1918 (non-private) IP addresses. That is a very good thing, assuming the new web-GUI also removes the need to click "Connect" on the PC to allow a connection from a new ALVR client (Oculus Quest) IP address. 
This raises a question about ALVR use over the public internet. I think the best long term solution would be some kind of encryption (at least of the traffic from headset to PC as Steam allows to control the desktop), however that is a complex subject... In the old network implementation it was technically possible to run ALVR over the public internet (and it was recommended not to do it). There are some scenarios (e.g. cloud gaming where somebody sets up a virtual machine dedicated for Steam and connects ALVR to it) where this might be useful, however there are scenarios where this could be extremely dangerous. Maybe it could be worth to allow additional ALVR client IP addresses/subnets to be specified in the config file?

**Comment by zarik5** [comment]
ALVR client cannot access the dashboard (web GUI) until it has been trusted from the PC.
Opening the port 8082 (that grants access to the dashboard) would not be wise because there is the risk that someone can run code or access the file system remotely though ALVR webserver.

**Comment by zarik5** [comment]
Everything has been integrated except for the QUIC socket backend (that is still only on the sockets-rewrite branch). This issue can be closed for now.
