### ISSUE TITLE
ALVR Picking up headset, Sending Controller Tracking/Input And creating a vr enviorment. (Headset is still black with no audio.)

### ISSUE THREAD

**Issue by TheRealFame** [alvr-org/ALVR#2428]
## Description

When I load alvr, Everything with the software works. It detects my quest 2, It loads steamvr when I press the button to load the software, And it even start's a proper VR view for my headset, Taking no inputs but still picking up tracking for my controllers, Now. On the quest side, Nothing appears. It's just an all black void as the quest has no display sent over to it.

(Yes, I have read [https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting) And no, It did not work. Steamvr refused to launch after I added the launch command. And changing it any further did not do anything.) 

## General Troubleshooting
- [✅ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [✅] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[https://linux-hardware.org/?probe=d61ab868f5](https://linux-hardware.org/?probe=d61ab868f5)

### Installation
ALVR v20.11.1/Same Version For Oculus Quest 2.

**ALVR Settings File**:
(Would this even be needed..? If so, I'll send it later, But the default setting's don't work either.)

**SteamVR Version**:
STEAMVR (Previous)

**Install Type**:
alvr_streamer_linux.tar.gz 

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
PRETTY_NAME="KDE neon 6.1"

**Comment by TheRealFame** [comment]
If there's anymore info i can give out to help, Let me know! Again, This is a kde plasma operating system, That is on kernal 6.5, (With all it's latest updates.)

**Comment by The-personified-devil** [comment]
https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting

**Comment by The-personified-devil** [comment]
> (Yes, I have read https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting And no, It did not work. Steamvr refused to launch after I added the launch command. And changing it any further did not do anything.)

The first fix is sadly required as of now, so you'll need to use it. But have you checked that steamvr is actually installed there? When in doubt you can `ls path-to-vrmonitor.sh` and if it doesn't error the file is actually there and it should work. If it does error you'll have to modify the path to fit. You should probably also stick to using the normal version of steamvr.

Also if you use audio note that you'll need to set the alvr audio devices as default in the audio manager when alvr has established a connection so that audio actually gets routed to them.

**Comment by TheRealFame** [comment]
> > (Yes, I have read https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting And no, It did not work. Steamvr refused to launch after I added the launch command. And changing it any further did not do anything.)
> 
> The first fix is sadly required as of now, so you'll need to use it. But have you checked that steamvr is actually installed there? When in doubt you can `ls path-to-vrmonitor.sh` and if it doesn't error the file is actually there and it should work. If it does error you'll have to modify the path to fit. You should probably also stick to using the normal version of steamvr.
> 
> Also if you use audio note that you'll need to set the alvr audio devices as default in the audio manager when alvr has established a connection so that audio actually gets routed to them.

Hmmmm, Alright.. So, I had just directly taken the command. But the install path for my steam vr is
/home/fame/.steam/debian-installation/steamapps/common/SteamVR/

And the command being.
~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%

**Comment by The-personified-devil** [comment]
So you'll need `/home/fame/.steam/debian-installation/steamapps/common/SteamVR/bin/vrmonitor.sh %command%`

**Comment by TheRealFame** [comment]
> So you'll need `/home/fame/.steam/debian-installation/steamapps/common/SteamVR/bin/vrmonitor.sh %command%`

This did the trick! Thank you
