### ISSUE TITLE
Every time my HDMI (TV) screen goes into standby 

### ISSUE THREAD

**Issue by djginge** [alvr-org/ALVR#2429]
This is a recurring issue on VRChat - it may be the same on other games but VRChat is the only game I play.

## Description

I use a HDMI TV as my main PC screen .
The TV has an automatic timeout / standby mode thing (set to 6 hours)
It gives a warning and if you press a button on the TV remote, the standby goes away but when I have the headset on, I can't see the warning.

As soon as it goes into standby, I lose audio in the headset and can't get it back without restarting SteamVR

This is the error showing in the ALVR log
_Audio record error: The requested device is no longer available. For example, it has been unplugged._

I have the microphone routed through VB Cable.  Maybe something toggles when the screen goes into standby?

The fix would be to make the audio carry on even after the screen goes into standby.

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
I5-12400F
**GPU**:
RTX3060
**GPU Driver Version**:
32.0.15.5585
**Audio**:
CABLE Input (VB-Audio Virtual Cable)
### Installation
**ALVR Version**:
20.7.1
**ALVR Settings File**:

**SteamVR Version**:
2.7.4
**Install Type**:
- [X ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 Pro 64-bit (10.0, Build 22631)

**Comment by 0Human0** [comment]
You need to set it to another audio device in ALVR that isn't related to that TV. What's likely happening is that when the TV turns off the audio device within windows gets removed at the same time and bugs ALVR's audio.

**Comment by djginge** [comment]
I'm not sure I understand what you are suggesting.
The documentation states that the only way to use the mic via ALVR is to set the audio to VB Cable.
When you say set it to another audio device. What do you mean?

Also - it's worth pointing out that this is on the audio output only - the mic input carries on working fine (other users are able to continuing hearing what I say after the headset speakers stop outputting).

**Comment by 0Human0** [comment]
I mean set your audio output in Windows to anything else that is not that TV output, and leave the microphone the same. If you don't have another audio device other than the TV, create one by adding another VB cable https://vb-audio.com/Cable/ scroll down until you see the A+B options.

https://github.com/user-attachments/assets/6b70f432-18de-4c76-9f8b-337a48b6c565
