### ISSUE TITLE
Rewrite video encoder (Windows)

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#243]
* [ ] FFmpeg encoder with D3D11VA (first with RGB texture format)
* [ ] Integration

**Comment by NoUserNameForYou** [comment]
Issue is closed but is this added? I'm on p4600p/p4700 (haswell xeon) and couldn't get it to work when I set adapter to either 1 or 0.

Offloading valuable dGPU resources to this would be really good.

**Comment by zarik5** [comment]
Superseded by #817
