### ISSUE TITLE
Cannot start openxr client in debug build

### ISSUE THREAD

**Issue by vosk** [alvr-org/ALVR#2446]
## Description
Getting a rust panic about graphics, somehow it runs fine in --release
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]: ALVR panicked: What happened:
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]: panicked at alvr/client_core/src/graphics/mod.rs:204:65:
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]: removal index (is 0) should be < len (is 0)
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]: 
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]: Backtrace:
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    0: alvr_common::logging::set_panic_hook::{{closure}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /media/large/ALVR/alvr/common/src/logging.rs:191:13
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2084:9
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:       std::panicking::rust_panic_with_hook
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:808:13
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    2: std::panicking::begin_panic_handler::{{closure}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    3: std::sys::backtrace::__rust_end_short_backtrace
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    4: rust_begin_unwind
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    5: core::panicking::panic_fmt
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    6: alloc::vec::Vec<T,A>::remove::assert_failed
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:1633:13
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    7: alloc::vec::Vec<T,A>::remove
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/vec/mod.rs:1638:13
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    8: alvr_client_core::graphics::GraphicsContext::new_gl
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /media/large/ALVR/alvr/client_core/src/graphics/mod.rs:204:23
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:    9: alvr_client_openxr::entry_point
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /media/large/ALVR/alvr/client_openxr/src/lib.rs:190:36
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   10: alvr_client_openxr::android_main::{{closure}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /media/large/ALVR/alvr/client_openxr/src/lib.rs:478:9
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   11: std::sys::backtrace::__rust_begin_short_backtrace
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   12: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:538:17
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   13: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panic/unwind_safe.rs:272:9
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   14: std::panicking::try::do_call
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   15: __rust_try
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   16: std::panicking::try
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:       std::panic::catch_unwind
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:       std::thread::Builder::spawn_unchecked_::{{closure}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/thread/mod.rs:537:30
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/alloc/src/boxed.rs:2070:9
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:       std::sys::pal::unix::thread::Thread::new::thread_start
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:              at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/pal/unix/thread.rs:108:17
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   19: _ZL15__pthread_startPv
10-08 10:53:21.710 15311 15356 E [ALVR NATIVE-RUST]:   20: __start_thread

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**GPU Driver Version**:

**Audio**:

### Installation
**ALVR Version**: master

**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by vosk** [comment]
Somehow the flags mess things up. if i use empty flags it runs fine

```

        let flags = if cfg!(debug_assertions) {
            InstanceFlags::DEBUG | InstanceFlags::VALIDATION
        } else {
            InstanceFlags::empty()
        };
```

**Comment by zarik5** [comment]
This is strange, it runs fine for me in debug

**Comment by vosk** [comment]
This must be related to Monado. (Yes I am an idiot who forgets to plug the correct thing up)
