### ISSUE TITLE
Sliced encoding

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#246]
Fixes #574.

**Comment by thehhmdb** [comment]
Once complete, in the settings for this, would it be possible to have a slider for the amount of sessions that NVENC can use?

There are patches to unlock more sessions for consumer cards and that might potentially reduce encoding latency even more:
https://github.com/keylase/nvidia-patch/blob/master/win/README.md

**Comment by zarik5** [comment]
For sure! Also I was aware of the patch.

**Comment by zarik5** [comment]
Grouped into #817
