### ISSUE TITLE
Suggestion  / Question: Lossless / No compression mode for testing?

### ISSUE THREAD

**Issue by ej7819** [alvr-org/ALVR#2467]
## Description

Hi, I was wondering whether there's any way to configure ALVR to use no compression or some sort of lossless compression?  Even if you only get 1 frame per second or worse, I am interested in such a mode as a way of testing headset image quality, getting screenshots, etc.

If there isn't currently any way to do this, I hope you might please consider such a feature in the future?

**Comment by The-personified-devil** [comment]
See also #2175

**Comment by The-personified-devil** [comment]
Closing this in favor of the existing issue, if works ever gets done on it, this will be referenced there.
