### ISSUE TITLE
SteamVR crashes when opened through ALVR on kernel 6.11

### ISSUE THREAD

**Issue by LuNeder** [alvr-org/ALVR#2476]
## Description
Whenever a headset is connected to SteamVR through ALVR on Linux Kernel 6.11.6, SteamVR will crash as soon as the headset connects.

If I launch SteamVR without the "~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%"  launch args, the crash won't happen! But then there's the known issue of the vr view window showing the image correctly but the headset showing nothing (actually it shows a monochromatic yellow static screen in one eye and nothing on the other now lol)...

Unsure if helpful, but [steam-logs-kernel611-still-broken-with-launch-args.tar.gz](https://github.com/user-attachments/files/17787102/steam-logs-kernel611-still-broken-with-launch-args.tar.gz)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=bb8f80dc95

**CPU**: 7950X3D

**GPU**: RTX 4090

**GPU Driver Version**: 560.35.03

### Installation
**ALVR Version**: 20.11.0 and 20.11.1 

**ALVR Settings File**: just retested to default, problem persists.

**SteamVR Version**: 2.8.6, as well as previous 2.5.5 and beta 2.8.6

**Install Type**:
- [x]  https://github.com/NixOS/nixpkgs/pull/308097 (used to work until few weeks ago)
- [x]  exact same problem happens with alvr from the tar file ([from here](https://github.com/NixOS/nixpkgs/pull/308097#issuecomment-2365500655)) (which also used to work)

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): NixOS 24.11 (Vicuna)

**Comment by LuNeder** [comment]
Returning to an older nixos generation (which had the same nvidia drivers, so that's not at blame) fixes this. I'll try to figure out what exactly changed between working and not working, but it's possible some random library broke this - maybe on other rolling release distros too.

**Comment by LuNeder** [comment]
I know this is not entirely helpful, but here's what changed between my newest working alvr system and my oldest not working alvr system: [alvr-gen-diff.txt](https://github.com/user-attachments/files/17534383/alvr-gen-diff.txt). I'll do some more precise testing later today to try to discover exactly what was the problematic package update.

Aditionally, here's a diff between the above not working alvr system and my latest also not working alvr system (just so you know what changes/rollbacks did not fix the problem): [alvr-gen-diff2.txt](https://github.com/user-attachments/files/17534395/alvr-gen-diff2.txt)

I'll try to come up with something more specific and useful later today.

**Comment by thevinter** [comment]
Just FYI I'm getting the same issue on Arch Linux. Funny thing is that I launched SteamVR and it was working for 5 minutes, then crashed and now I'm getting the same issue. Let me know if providing some logs would be helpful.

**Comment by DrearyDreams** [comment]
Don't know if this is related but I'm getting these same exact issues here on Ubuntu 24.10 and it happens more frequently when I have add-ons installed like Galister's OVR-Space Calibrator.

**Comment by LuNeder** [comment]
> it happens more frequently

We’re not talking about the same problem then

My problem happens every time, not sometimes 

It might be, and it probably is, a nix-specific problem, however somehow a nixpkgs PR fixed it for everyone else while keeping it broken for me so I have no idea

**Comment by LuNeder** [comment]
Found the culprit, it's the kernel version

If I use Linux 6.6.59, everything works fine. 
If I use 6.11.6, SteamVR will crash as soon as the headset is connected to ALVR.

**Comment by LuNeder** [comment]
I'll test some kernels to try to pinpoint exactly which version breaks it

**Comment by LuNeder** [comment]
Fixed on Kernel 6.11.7
(what a fucking timing lmao)

**Comment by LuNeder** [comment]
Ugh nvm it broke again just like a day after I closed this
