### ISSUE TITLE
Feature request: Minimal compression mode (for testing)

### ISSUE THREAD

**Issue by ej7819** [alvr-org/ALVR#2487]
## Description

Hi, I think it would be useful for comparison, testing and troubleshooting if there was a mode / profile that maximizes image quality to as near lossless quality as possible?  At the expense of everything else, even if you only get  1 frame per second or whatever.

I think people would find it valuable to be able to compare what image quality they could theoretically get, how well they are optimising their network and bitrate, etc.

**Comment by The-personified-devil** [comment]
Duplicate of #2467
