### ISSUE TITLE
Rewrite audio code

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#250]
Rewrite with CPAL and Oboe library.
* [x] Add AudioSession, ~~AudioRecorder, AudioPlayer~~ for server and web client with CPAL
* ~~[ ] Add corresponding structures for native client with Oboe~~
* [x] Integration with server and client

UPDATE: Work has started to integrate Oboe into CPAL. Waiting for progress to be made.

UPDATE 2: Oboe support in CPAL has been merged. This issue has been unblocked.

**Comment by JackD83** [comment]
With this libraries, do we still need a virtual mic on windows?

**Comment by zarik5** [comment]
Yes. On windows you need to create a separate kernel mode driver (with the native windows API) that is somewhat difficult to do.

**Comment by zarik5** [comment]
Audio had a few rewrites. The latest implementation uses CPAL for server recording, Rodio for server microphone rendering and Oboe for audio capturing and rendering on client. CPAL and Rodio are ready for a future web build for the client.
