### ISSUE TITLE
Is this supports oculus rifts?

### ISSUE THREAD

**Issue by Edassap** [alvr-org/ALVR#2502]
I saw the wiki. It says "Stream VR games from your PC to your headset via Wi-Fi.". I wonder if it also support oculus rift(connect with hdmi and usb3.0) like virtual desktop does! By the way, can someone tell me a  another software works like virtual desktop or infuse vr(alvr).

**Comment by The-personified-devil** [comment]
No, it's designed to stream to standalone vr headsets. How does virtual desktop even work with the rift, is it cabled or connected over wifi? Also can't you just use normal steamvr?

**Comment by spectrino2077** [comment]
Virtual desktop does not stream games on the rift

**Comment by The-personified-devil** [comment]
Alvr is designed for headsets that have an openxr runtime running on the headset itself. Headsets intended to only be used in a cabled configuration do not have that (and also don't have the hardware for streaming). If you wanted to do streaming over wifi you'd have to look into proprietary hardware from the manufacturer. If you just want to use it in a cabled configuration just use steamvr.
