### ISSUE TITLE
Dashboard with graphical bug

### ISSUE THREAD

**Issue by eHonnef** [alvr-org/ALVR#2541]
## Description

Hello all,

When I open the ALVR dashboard it has a weird graphical bug, then I cannot start anything.

The image below shows the bug:

![2024-11-29_19-14](https://github.com/user-attachments/assets/13941baf-9787-4fd5-a852-f5cd2f1140a6)

## General Troubleshooting
- [ x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ x ] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware

[hw-probe link](https://linux-hardware.org/?probe=341c2709d8)

### Installation
**ALVR Version**: 20.11.1

**ALVR Settings File**: [session.json](https://github.com/user-attachments/files/17962284/session.json)

**SteamVR Version**: 2.8.7

**Launch options**: STEAM_RUNTIME_HEAVY="~/.steam/bin64/steam-runtime-heavy" DRI_PRIME=1 ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ x ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Fedora Linux 40 (KDE Plasma)

**Comment by Vixea** [comment]
Looks like your not using radv please read the wiki

**Comment by Vixea** [comment]
I'm going to close the issue because its not our bug and its not our dashboard but steamvr's but we can continue to try and resolve it. Keep in mind using discord or matrix is better and where support questions should go

**Comment by eHonnef** [comment]
Sorry that I've used the wrong channel, and thanks for the reply :D 

So... I've managed to fix it, on my [hw-probe info](https://linux-hardware.org/?probe=341c2709d8&log=vulkaninfo), I am using `radv`:

```
VkPhysicalDeviceVulkan12Properties:
-----------------------------------
	driverID                                             = DRIVER_ID_MESA_RADV
	driverName                                           = radv
	driverInfo                                           = Mesa 24.1.7
	conformanceVersion:
		major    = 1
		minor    = 3
		subminor = 0
		patch    = 0
```

What solved was to disable the integrated GPU in the bios.

And I've updated the launch options to this: `WAYLAND_DISPLAY='' DRI_PRIME=1 ~/.local/share/Steam/steamapps/common/SteamVR/bin/vrmonitor.sh %command%`

**Comment by Vixea** [comment]
Awesome thanks for posting your solution too
