### ISSUE TITLE
No audio devices appearing after headset connection

### ISSUE THREAD

**Issue by TernaryC** [alvr-org/ALVR#2544]
## Description
Even after connecting my headset and streaming to PC, no audio devices appear, and thus I cannot use headset microphone or output.
![image](https://github.com/user-attachments/assets/73fe25f3-7baa-478a-9a36-275261006c30)
![image](https://github.com/user-attachments/assets/5b7872bd-5e4e-4104-a689-1a50eaef246c)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)
- [x] I followed the [Linux Troubleshooting](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting) instructions to fix broken audio

### Hardware
**hw-probe**: https://linux-hardware.org/?probe=ff1182600d

**CPU**: AMD Ryzen 5 5600G

**GPU**: NVIDIA GeForce RTX 3060

**GPU Driver Version**: nvidia-driver-550 (550.120-0ubuntu0.22.04.1)

**Audio**: libpipewire 1.0.7

### Installation
**ALVR Version**: v20.11.1

**ALVR Settings File**: Unaltered from default settings.

**SteamVR Version**: 2.8.7

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Linux Mint 21.3

**Comment by The-personified-devil** [comment]
Have you verified that you're actually running pipewire as the main audio system? It's possible to run both pulsemixer and pipewire at the same time due to certain usecases, but for alvr's audio to function you need to have pipewire as the main audio system.
To check that you can run `pactl info` and send us the output. If the server name contains pipewire you're good if it doesn't you'll need to switch to pipewire.

**Comment by TernaryC** [comment]
Running `pactl info`, my server name is `PulseAudio (on PipeWire 1.0.7)`. It _does_ have pipewire in the name, but it does seem to imply that pulseaudio is still the main system.

**Comment by The-personified-devil** [comment]
> It does have pipewire in the name, but it does seem to imply that pulseaudio is still the main system.

No, `pactl` is a tool for pulseaudio so it uses the pulseaudio api, but pipewire has a compatibility layer for pulseaudio and that's what's being used, so at the core you're still using pipewire. This is actually odd tho because it means you have pipewire and it's somehow not working regardless

**Comment by TernaryC** [comment]
Hmm. I reinstalled pipewire and it has suddenly begun working. I don't think I did anything different (especially seeing as this is the third time I've reinstalled it while trying to troubleshoot this issue), so I unfortunately have no idea what has caused it to begin working. Same pipewire version, same `pactl` details. I wish I had more information, but at least it's working?
