### ISSUE TITLE
Use OpenXR instead of Oculus Mobile SDK

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#255]
This is needed to support future non Oculus headsets

**Comment by ronthecookie** [comment]
This will resolve the following issues:
- Quest 2 thumb rest sensors don't do anything (#591)
- Disable hand tracking when using gamepad (#127)

**Comment by zarik5** [comment]
@ronthecookie No, I don't think they will solve either of those issues. #591 is just a matter of adding a new field to the tracking data packet, About #127, the problem is fundamental, there is no solution other than disabling handtracking in the quest settings.

**Comment by ronthecookie** [comment]
@zarik5 I am just following your own words:

in #591: 
> This is planned. Currently we are using an older SDK to support the Oculus Go (so the thumb rest is not supported), but this will change after we switch to OpenXR.

In #127:
> This is a limitation of the SDK so no action can be taken now. I opened this issue just as a reminder for when a future SDK update will allow this to be fixed.

This one is a bit more borderline but better keep track of the issue *somewhere*.

**Comment by zarik5** [comment]
#591: I just said that I preferred waiting for implementing OpenXR for implementing the thumb rest support, but it is not a requirement and the issues should better stay separated because the things they track are on separate levels.

#127: This is unactionable, it doesn't matter if it stays open or closed.

**Comment by ronthecookie** [comment]
Ah, fair enough, I've reopened #591.

**Comment by fangguanya** [comment]
Is there any updates about OpenXR support?

**Comment by zarik5** [comment]
@fangguanya I'm working on it but I don't have an ETA.

**Comment by fangguanya** [comment]
> @fangguanya I'm working on it but I don't have an ETA.

Great news! I also dig a lot about it, I found Open XR use asynchronous event poll process, which I don't know how to integrate with ALVR, did you have any idea about this?

**Comment by fangguanya** [comment]
Okay，I'll take a look later. Thanks for all your work.

**Comment by zarik5** [comment]
Done! finally :)
