### ISSUE TITLE
Enhancement: Separate settings for USB vs WiFi

### ISSUE THREAD

**Issue by Fmstrat** [alvr-org/ALVR#2550]
## Description

Since bitrate/etc can be much higher over USB, it would be great if there were separate profiles for usb and wired, or per-headset with them treated independently.

A good example of the value here is Elite Dangerous and Half Life: Alyx. The former you are always stationary and can benefit from wired, where the latter is better in wireless mode, however a user would rarely take the time to adjust all the settings.

**Comment by The-personified-devil** [comment]
See #259. Already planned as a full user-defined presets system for everything, but there's currently no one working on it.
