### ISSUE TITLE
Change the Wired Setup Wiki page so it is correct

### ISSUE THREAD

**Issue by AliceKawanami** [alvr-org/ALVR#2557]
## Description

The current page says:

"If your headset is not detected, click "Add device manually" and use the IP address 127.0.0.1. Use the hostname displayed on your headset screen." 

This is not correct it should be hostname and add .local at the end.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

**Comment by The-personified-devil** [comment]
Fwiw there are no checks being done on the hostname, so it could just be whatever. But yea the wiki should probably reflect that fact. I'm closing this tho because the next release will have a built-in wired mode and then we'll get rid of that wiki page anyway.
