### ISSUE TITLE
Remote desktop streaming

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#258]
The remote desktop client can be implemented in Javascript inside the dashboard. VNC is preferred.

**Comment by JackD83** [comment]
You mean stream the desktop ALVR is running on?

**Comment by zarik5** [comment]
I didn't define the details. Ideally you would be able to toggle the monitors. Or let the VNC server create a new virtual monitor and stream that one. For the VNC client I thought of this library: https://novnc.com/info.html. That client should be compatible with any third party VNC server.

**Comment by ronthecookie** [comment]
Do we really want this? It feels like [scope creep](https://en.wikipedia.org/wiki/Scope_creep) to me and looking at the SteamVR desktop view works well enough for me.

**Comment by xytovl** [comment]
I agree: I don't see why alvr would need to do more than providing a n openVR/openXR driver.

**Comment by zarik5** [comment]
I also agree. This issue was in response to multiple feature requests we had in the past.

**Comment by lmarianski** [comment]
Yep, you can just use the steam version of VRDesktop if you need more than the default steam desktop view
