### ISSUE TITLE
How do I turn on passthrough in the latest version?

### ISSUE THREAD

**Issue by your1236958** [alvr-org/ALVR#2591]
The passthrough function of left menu key + right B key doesn't seem to work!
Sorry I'm just a regular Pico 4 user.
I updated straight from version 18.4 to the latest 20.11.1
All other functions are working fine.
I carefully followed the instructions in the README and successfully completed the setup wizard
 I read the ALVR GitHub Wiki
I don't seem to be able to find an update on this.
Does anyone know how the passthrough feature is turned on now and can you pls let me know.
Thanks a lot!

**Comment by The-personified-devil** [comment]
There is a setting in the alvr dashboard.

**Comment by 0Human0** [comment]
And it's not available in the latest you'll have to download one of the nightly's. https://github.com/alvr-org/ALVR-nightly/releases
Keep in mind there's a bug currently with the Pico 4 with the head prediction so it's going to feel off, It's not too bad but recentering will make it worse so don't do that.

**Comment by your1236958** [comment]
> There is a setting in the alvr dashboard.

I've searched and searched, but I can't find it.

**Comment by your1236958** [comment]
> And it's not available in the latest you'll have to download one of the nightly's. https://github.com/alvr-org/ALVR-nightly/releases Keep in mind there's a bug currently with the Pico 4 with the head prediction so it's going to feel off, It's not too bad but recentering will make it worse so don't do that.

Finally found the passthrough switch, thanks for the help bro, this problem is solved!
