### ISSUE TITLE
While in VR the dashboard tries to connect to the wrong IP address

### ISSUE THREAD

**Issue by zingmars** [alvr-org/ALVR#267]
# Please follow the general troubleshooting steps first:

- [X] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

When trying to open the new web menu in VR I'm greeted with an ERR_ADDRESS_UNREACHABLE error. 

Image:

![image](https://user-images.githubusercontent.com/917126/89124433-94f37480-d4df-11ea-9e51-37a206edd84b.png)

 (excuse the low quality, I'm using the Oculus app to cast the view).

The problem seems that it's trying to use the wrong IP. The displayed IP is assigned to my computer's WiFi adapter which is not in use (the adapter is enabled, but WiFi is disabled). I'm not sure how ALVR even picked up the IP considering I hadn't connected to my network using wifi for months now and it shouldn't be in any caches at this point. I can't connect to that IP from any other device on the network since it obviously isn't connected, but using my actual IP works and I see the dashboard from other devices.

I might be missing something, but I couldn't find a setting in ALVR that lets me select which IP the web server should listen to.

#### Environement

What version of ALVR and SteamVR have you tried:  
* ALVR v12.0 beta 3 
* SteamVR 1.13.10

**Comment by zarik5** [comment]
It's a known problem for some people. It will be fixed in v13.

**Comment by lyndonguitar** [comment]
Just wanted to say, i have this issue as well. while reseting the "steam VR" overlay aka left controller

**Comment by zarik5** [comment]
The dashboard has been removed, but now long pressing the menu button will correctly open the dashboard on the Oculus browser.
