### ISSUE TITLE
VR driver rewrite / Linux support

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#269]
Add support for Vulkan and Linux.
This should be the last step of the Rust rewrite. By the time this issue is reached, Valve could have added an OpenXR driver interface. In that case that should be preferred in place of OpenVR. Another option is implementing an OpenHMD driver.

Can someone provide a simple VR driver example for Linux? It doesn't need to be integrated in ALVR just yet.

EDIT: You can follow the development progress here: https://github.com/alvr-org/ALVR/wiki/Linux-Support-development-progress

**Comment by revan1611** [comment]
Please please please 🙏🙏🙏

**Comment by zarik5** [comment]
Update: it seems that the IVRDriverDirectModeComponent interface that ALVR uses is not supported on Linux (https://github.com/ValveSoftware/openvr/issues/749) and we still don't know anything about the IVRVirtualDisplay interface (https://github.com/ValveSoftware/virtual_display/issues/5)

**Comment by jarrard** [comment]
I was hopeful that someday Oculus would release a Linux version of their app, if that happened would it in some way help projects like this?  (assuming Link support would work under Linux)

**Comment by The-Bob** [comment]
An oculus app on linux wouldn't really help ALVR afaik, because ALVR doesn't use the oculus app. On the PC it only interacts with steamvr, and the client on the headset is installed and managed via sidequest, which is crossplatform

**Comment by jarrard** [comment]
Oh, :(
I guess ALVR is our only hope for WiFi VR under Linux then. 
I remember talking to the Virtual Desktop dev about support for Linux and he pretty much gave me the middle finger! :( _obviously not a fan of Linux ._ 

Its quite hard finding developers for VR software whom are ALSO fans of Linux! it seems everyone is firmly kissing Microsoft's butt when it comes to VR development, except for Valve.

**Comment by zarik5** [comment]
Update 2: by looking through https://github.com/ValveSoftware/SteamVR-for-Linux issues I see logs of built in SteamVR drivers (like for the Lighthouses) that implement IVRVirtualDisplay, so writing a driver using that interface could be theoretically possible.

**Comment by zarik5** [comment]
@jarrard Sidequest has nothing to do with this. Sideqest uses adb, that is compatible with every android device. We need support for a feature specific to SteamVR.

**Comment by jarrard** [comment]
> 
> 
> @jarrard Sidequest has nothing to do with this.

Oh ok, I just thought maybe it had something going on because it can stream video and such to the Quest from what I know so its not just basic ADB commands?

**Comment by zarik5** [comment]
As I said, ADB streaming feature works in the wrong direction, and there are not many parameters we can control. But this is not even the matter of this issue. The question here is how do we obtain the images in the first place, before streaming them. I already found a possible solution with IVRVirtualDisplay, now someone could try implementing it and seeing if it works.

**Comment by sandersr** [comment]
Is it worth looking at:

https://monado.freedesktop.org/

As an alternative to SteamVR?

**Comment by zarik5** [comment]
@sandersr AFAIK it doesn't have a device driver API.

**Comment by lunarcloud** [comment]
> @sandersr AFAIK it doesn't have a device driver API.

https://monado.pages.freedesktop.org/monado/md_writing-a-new-driver.html

**Comment by zarik5** [comment]
@lunarcloud Thanks! apparently I didn't look hard enough. Let's hope it supports something like OpenVR virtual mode.

**Comment by jarrard** [comment]
Apparently AMD has a VR streaming app you can use under Linux. However I haven't tried it out yet.

**Comment by fezboy** [comment]
@jarrard do you have a link? DuckDuckGo gave me [ReLive VR](https://www.amd.com/en/technologies/radeon-software-relive-vr), which as far as I can tell is Windows only.

**Comment by jarrard** [comment]
Yeah sorry I was mistaken, the Quest installs a package which connects to the windows app atm. Github link below with requests for Linux support, which should be possible as it does not rely on Oculus APP.

Its open source so might help with this project on some level? 

https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR

**Comment by AmmarkoV** [comment]
Hello guys, so for the Oculus Quest2 if you download the [Oculus Mobile SDK](https://developer.oculus.com/downloads/package/oculus-mobile-sdk/) it comes with several VRSamples like the VrCubeWorld_Framework. Compiling it from linux works after setting up android studio

adding a rule for the Oculus device in /etc/udev/rules.d/51-android.rules 
 
```
SUBSYSTEM=="usb", ATTR{idVendor}=="2833", ATTR{idProduct}=="0186", MODE="0666", GROUP="plugdev"
```

Setting up the correct .bashrc exports 

```
export JAVA_HOME=/path/Programs/android-studio/jre
export ANDROID_HOME=/path/Android/Sdk/
export ANDROID_NDK_HOME=/path/Android/Sdk/ndk-bundle
export ANDROID_NDK_ROOT=/path/Android/Sdk/ndk-bundle
export ANDROID_NDK=/path/Android/Sdk/ndk-bundle
export OCULUS_SDK_PATH=/path/Documents/3dParty/OculusVRSDK/ovr_sdk_mobile_1.37.0_my/
export OVR_PROJ_ROOT=/path/Documents/3dParty/OculusVRSDK/ovr_sdk_mobile_1.37.0_my/VrSamples
```

adding some extra flags on cflags.mk of the  [Oculus Mobile SDK](https://developer.oculus.com/downloads/package/oculus-mobile-sdk/)

```
LOCAL_CFLAGS    += -Wno-strict-aliasing         # TODO: need to rewrite some code
LOCAL_CFLAGS	+= -Wno-unused-parameter
LOCAL_CFLAGS	+= -Wno-missing-field-initializers	# warns on this: SwipeAction	ret = {}
```

you can run the build.py python scripts  for example VrSamples/VrCubeWorld_Framework/Projects/Android/build.py

So given that you can actually use Linux compile a native application to render to the left/right eye and send back the 6-dof pose of the head and controllers what is the best format to transmit the image?
Should it be on an image to image basis ? as a mpeg stream or what ?

Having the Oculus connected and running 

```
adb exec-out "while true; do screenrecord --bit-rate=2m --output-format=h264 --time-limit 180 -; done" | cvlc --demux h264 --h264-fps=60 --clock-jitter=0 -
 ```
for example can stream from the oculus to the linux PC but it works pretty badly, especially in a non USBC connection

**Comment by zarik5** [comment]
Oculus Mobile SDK is a game facing API, not a driver API. The only VR driver API is OpenVR, but doesn't seem to work with non wired headsets. The best solution so far seems to emulate a virtual hmd display and then screen capture it, but no test had been made yet with this.

**Comment by AmmarkoV** [comment]
Yes *but* what is the reason why a driver can't be written as a "game".
For example if you adb install [Steam Link.apk](https://apkpure.com/steam-link/com.valvesoftware.steamlink/download?from=details) as a "game" you can connect to Steam as a 2D streaming solution.

A "screenshot" from my phone ( since actual screenshots are disabled for this application ) of Steam Link playing Monkey Island 2 on the Quest2 
![130162306_2851317058421741_8630424209765170702_n](https://user-images.githubusercontent.com/97630/101278654-956d8600-37c5-11eb-90fc-c6bdc02faaf7.jpg)

**Comment by zarik5** [comment]
The problem here is how to get game frames in the first place. You could search in the GPU memory or inject games but that is very difficult and error prone. OpenVR was supposed to return the game frames but it does not work on Linux.

**Comment by AmmarkoV** [comment]
Well I have code to set up a [GLX3 context](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/System/glx3.c)  then [render to p-buffer textures](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/System/glx_testRenderToTexture.c)   then [download the image ](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/opengl_acquisition_shared_library/opengl_depth_and_color_renderer/src/Library/Rendering/downloadFromRenderer.c#L31) then i.e. write a [jpeg image in memory](https://github.com/AmmarkoV/RGBDAcquisition/blob/master/tools/Codecs/jpgInput.c#L161) and [sending it through a socket is trivial](https://github.com/AmmarkoV/AmmarServer/blob/master/src/AmmClient/network.c#L168)

**Comment by scalway** [comment]
I hope there will be some way to use it on linux... but I know how hard such stuff can be.

**Comment by jarrard** [comment]
Yeah transferring to a OS agnostics coding echo-system is very hard for allot of Windows only developers. 
But its for the better really. Opens up many doors. 

Allot of people also really want to use something like Linux for VR, just such a shame its so incredibly limited atm, even the tethered Valve Index etc options have quirks about them under Linux. (stuff like steamplays proton doesn't always play nice with VR)

**Comment by Geo25rey** [comment]
@zarik5 (This)[https://github.com/ValveSoftware/openvr/blob/master/samples/driver_sample/driver_sample.cpp] at the very least compiles on Linux. 

The main issue with the changing to a crossplatform architecture is the dependencies of Windows only libraries such as `wil.h` (Windows Implementation Library) and `d3drender.h` (DirectX). 

Do you have a branch for the crossplatform rewrite, or should PR's just be directed to the master branch?

**Comment by zarik5** [comment]
@Geo25rey The sample in the first link doesn't use any interface to obtain game frames, and the second link is for the game facing API, not the driver facing API. We already moved on from OpenVR. We thought we could use something like a Vulkan validation layer to extract frame data directly from the SteamVR runtime internals. No tests have been done on this method yet.

https://github.com/alvr-org/ALVR/wiki/Linux-Support-development-progress

**Comment by Geo25rey** [comment]
@zarik5 What if I get [the virtual display driver example](https://github.com/ValveSoftware/virtual_display/blob/master/driver_virtual_display/driver_virtual_display.cpp) working on Linux with Vulkan?

**Comment by zarik5** [comment]
We tried. It crashed on Nvidia and does nothing on AMD

**Comment by hedmo** [comment]
I like to help to with porting ALVR to Linux. I am not a coder but i have been checking vr in Linux for quite som Time now . What is the problem with drives? How about openHMD?

**Comment by zarik5** [comment]
OpenHMD does not have an API to query game frames, so basically it's restricted to use only with wired headset.

**Comment by xytovl** [comment]
I don't understand why you need to grab frames.

Are they not provided by steamVR in IVRDriverDirectModeComponent::SubmitLayer ?
From what I gathered, the buffer format depends on platform, D3D11 on Windows and Vulkan on Linux.

Is there any branch that at least compiles?

**Comment by zarik5** [comment]
IVRDriverDirectModeComponent does not work on Linux. We searched a lot but there are no working samples online.

**Comment by jarrard** [comment]
I only know of this, but its windows to linux, don't know of it working the other way.

https://forum.level1techs.com/t/looking-glass-guides-help-and-support/122387

**Comment by xytovl** [comment]
And in IVRVirtualDisplay::Present waht does the pPresentInfo->backbufferTextureHandle contain ?

**Comment by zarik5** [comment]
We didn't get that far. Present gets never called, the driver crashes before or does nothing.

**Comment by FeckingPotato** [comment]
`Valve could have added an OpenXR driver interface`
They did add an OpenXR driver interface: https://store.steampowered.com/news/app/250820/view/3044967019267211914

**Comment by xytovl** [comment]
I understand it as the opposite: on Windows only, an application can use openXR to talk to SteamVR. But SteamVR still uses OpenVR driver interface.

For a Linux port, it could be interesting to be a driver of [monado](https://monado.dev/), which would require to implement a mechanism in monado to replace the output inside a driver.
Unfortunately this would only cover Linux, and Windows would still need the OpenVR driver.

**Comment by zarik5** [comment]
@FeckingPotato That is still only for the game facing API. We never got any news of VR runtimes starting to support a driver facing API, not even with OpenXR. OpenVR is the only one out there. For Linux the only possibility seems to inject games to replace their openvr.so with our custom one. It will be very time consuming and error prone (we need to make a different injected .so for every published OpenVR version x graphics library), but I don't see other alternatives.

**Comment by omigeot** [comment]
I'm pretty sure you guys have already looked into the Relativty project, but since I don't see it mentionned yet. 

They're said to have SteamVR support for their opensource (wired) headset : https://github.com/relativty/Relativty

**Comment by frostworx** [comment]
Just stumbled over this:
https://github.com/alvr-org/ALVR/wiki/Linux-Support-development-progress

**Comment by nfl0** [comment]
[ALVR discord](https://discord.gg/ALVR)

**Comment by Geo25rey** [comment]
@xytovl @zarik5 Looks like progress is being made on a Linux driver. Are you looking for testers?

**Comment by xytovl** [comment]
> @xytovl @zarik5 Looks like progress is being made on a Linux driver. Are you looking for testers?

I am not actively working on alvr at the moment, I will resume in 2 weeks I hope. The current version has severe known limitations (instability, poor GPU support, hardware requirements) so testing alone is not needed at the moment.

You are free to test, but currently we are more looking for patches for the 2 solutions under discussion (acquire images through https://github.com/ValveSoftware/openvr/blob/master/headers/openvr.h#L3431 GetMirrorTextureGL, or through a vulkan layer to be developed)

**Comment by ronthecookie** [comment]
Resolved by #604.

**Comment by jarrard** [comment]
Resolved? so Quest2 now works on Linux? it plugs into SteamVR correctly under Linux???

**Comment by lmarianski** [comment]
> Resolved? so Quest2 now works on Linux? it plugs into SteamVR correctly under Linux???

Yes, and no, there's an experimental version that mostly works but it still has a few issues (mostly NVIDIA exclusive ones afaik), you can test it out for yourself though https://github.com/alvr-org/ALVR/wiki/Linux-Support-development-progress, also join the discord for updates (and a version of the client which you'll need to test if you have an nvidia card/official drivers)

**Comment by jarrard** [comment]
Cool, I have a 6800XT.

UNFORTUNATELY I sold my Q1 and Q2 earlier this year. Waiting for next next gen VR to arrive.

**Comment by ronthecookie** [comment]
@jarrard There are still many problems but, as @lmarianski said, it does work:
- audio streaming is not working
- foveated encoding is not implemented
- position is stuttering on nVidia (WIP fix exists in [#linux-dev](https://discord.gg/alvr) by CoffeeKat)
- it is not packaged for mainstream distros

**Comment by lmarianski** [comment]
Well, microphone streaming, I was able to stream game audio to the headset

Wysłano z aplikacji ProtonMail

-------- Oryginalna wiadomość --------
‎ 18 maj 2021, 02:53, Ron B napisał(a):

**Comment by ronthecookie** [comment]
@lmarianski That isn't supposed to work! We haven't worked on that at all yet and no one has gotten it running before you so I have some questions:

- What audio server are you running? (PulseAudio, PipeWire, pure ALSA)
- Did you perform any extra steps in your audio server to get it to work?
- If you're on PulseAudio, can you run `pactl info` and `pactl list` and send the output?
  + `pw-cli info all` for PipeWire.
- Did you patch any code?

**Comment by frostworx** [comment]
I gave ALVR a quick try with a Quest 2 these days on my Arch Linux system. The system should handle this easily _(RX 6900 XT, AMD Ryzen 9 5900X, 32gb ram, 5ghz wifi  as AP)_, setup is straightforward and works very fine, but SteamVR in the Quest hmd is slower than a slideshow.
fps shown in the gui are fine though `(somewhere around 55-60fps)`. Do you have a clue what the reason could be?
I usually use my Valve Index, which of course works fine. Is it maybe possible that some Index configuration left-overs conflict with ALVR? I built the server component manually with bundled-ffmpeg, because system ffmpeg isn't compatible currently. Tried both nightly and latest stable apk without a difference, and nightly ubuntu server binary doesn't work.
To be honest I haven't checked for any debug output or even logs, so maybe it is something obvious I simply missed.

Different topic, but configuration switch back to using the Index is not too seamless _(might require a restart as else the index video is drawn in a window, vrpathreg.sh removedriver might be needed, and the `~/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor` symlink needs to be set back to the original vrcompositor)_ 
This is no bug-report or complain, but it might be a good idea to mention this somewhere.
I'll test a bit more, but I thought it might be a good idea to already open an issue, maybe also to encourage others who test the linux build.

**Comment by xytovl** [comment]
Thanks for the feedback, are you running at full resolution? It might be the decoder in the headset that can't keep up with the high definition stream. We have not implemented foveated encoding yet, which would reduce the number of pixels to decode.

You are the first to come by with both a quest and an Index, on Linux. If you want to join the [discord](https://discord.gg/ALVR), there are sometimes discussions where we don't know if something is an ALVR bug or a SteamVR limitation (such as crash on amdvlk, corrupted menus in grid view).

For the symlink, it is supposed to not break the Index, but I guess there are many bugs as nobody could test.

**Comment by ronthecookie** [comment]
@frostworx 

> setup is straightforward and works very fine, but SteamVR in the Quest hmd is slower than a slideshow.
> fps shown in the gui are fine though `(somewhere around 55-60fps)`. Do you have a clue what the reason could be?

Are you monitoring the FPS through the ALVR dashboard? (go to `http://localhost:8082` in your browser if it doesn't open on it's own)
Is it just the client FPS that is bad?



>  Is it maybe possible that some Index configuration left-overs conflict with ALVR?

I don't think so.


> Different topic, but configuration switch back to using the Index is not too seamless _(might require a restart as else the index video is drawn in a window, vrpathreg.sh removedriver might be needed, and the `~/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor` symlink needs to be set back to the original vrcompositor)_

Let's keep track of this in https://github.com/alvr-org/ALVR/issues/665. (low priority though)

> The system should handle this easily _(RX 6900 XT, AMD Ryzen 9 5900X, 32gb ram, 5ghz wifi as AP)_

Fancy specs but how close is your AP to the Quest? Is the PC connected via Ethernet?
You can always try [using ALVR wired](https://github.com/alvr-org/ALVR/wiki/Use-ALVR-through-a-USB-connection).

<hr>
We have a channel where we discuss this stuff in the [Discord server](https://discord.gg/alvr).

**Comment by frostworx** [comment]
Hello,
thank you very much both @xytovl and @ronthecookie for your friendly and quick help!
I haven't changed the resolution, so I assume it is running at full resolution. Will test more soon and report back if I find out something useful. IIRC I also tried x265, but will test that again to be sure.
amdvlk is not installed, only using mesa-21.1.0-1 here.
No big deal with the vrcompositor symlink, only wanted to mention it somewhere. Thank you very much for even opening an extra issue for it :)

Haven't checked localhost:8082 yet and only checked the fps in the ALVR gui. Will check this as well and report back.
I did not carefully look at the SteamVR window ony my desktop, but I'd say its fps were normal.
I bought an awus1900 just for this setup, as the previously used wifi stick was using 2.4ghz and I thought that was the bottleneck.
I use the awus directly as AP, so the Quest directly registers as client at the pc. The Quest is not allowed to connect to the internet, so it very likely doesn't have the newest firmware and can't reach anything it wants to autoconnect with.
Using ALVR wired is a good idea , will try that as well.
Thanks again for your friendly support. I'll report back, when I have something useful to tell :)
I try to avoid discord when possible, but might join later.

**Comment by frostworx** [comment]
Hi again,
just a quick update:
http://localhost:8082 fps and everything else look fine. Depending on the used resolution it has up to 60fps on client and 60fps server. Zero packet loss.
The view in the Quest kind of looks like if it is rendered twice: A smaller window showing the whole view and in the surrounding border another view, which kind of looks like the resolution it should have. The controllers can be particularly seen though also on the upper border and not only at the bottom one. Maybe that is the main problem, and it kind of renders everything twice?
I also had the feeling that it worked a bit better today than on the last try, but the core problem remains.
When showing the hmd view as desktop window it looks normal and runs almost smooth, so I guess as expected.
Haven't tested wired mode yet.

**Comment by frostworx** [comment]
Just tested in wired mode and the problem persists.
I guess this scrcpy screenshot explains better what it looks like than my attempt above: 
![alvr-linux](https://user-images.githubusercontent.com/8840590/118772573-3340a300-b884-11eb-9844-33835013d324.jpg)

ALVR settings when taking the scrot:
**Video:**
* Video resolution: 100% _(the smaller window mentioned above was probably with a lower resolution)_
* 60hz
* h264
* video bitrate 30
* foveated rendering checked
* strength: 2
* vertical correction (german gui here, so just guessing the name): 0
* color correction not checked

**Headset:**
* Oculus Quest 2
* force 3Dof not checked
* controller checked
* controller simulation: oculus quest 2 no handtracking pinch
* tracking speed oculus projection
* vibrationstrength 1
* tracking zone local

If there's anything else which could help, please let me know.

**Comment by xytovl** [comment]
Foveated encoding is not implemented on Linux (but decoding is on the headset, which shuffles around the image). You should leave it disabled for the moment.

I mentionned it because at 100% Quest 2 resolution your are probably hitting the limits of the hardware decoder, and foveated encoding is a technique used to reduce the size of the image.

**Comment by frostworx** [comment]
Thanks will try this. Can't remember that I have touched it though. Maybe the initial wizard set it, when choosing some preset option?

**Comment by frostworx** [comment]
Unfortunately, disabling it didn't fix it completely, but the resolution looks correct now.
Input (moving controllers) lags 5-8 seconds and head tracking lags about 1 second.
So when moving the head I see the not rendered part _(black)_ until the video arrives a second later.

statistics from the last try:
```
Alle Packets:	144592 Packets
Packetrate:	3091 Packets/sek
Gesamter Packet-Verlust:	0 Packets
Packets verloren pro sekunde:	0 Packets/sek
Alle gesendeten:	201 MB
Gesendete Rate:	34.508368 Mbps
Gesamte Verzögerung:	4537.491 ms
Encodierungsverzögerung:	15.066 ms
Maximale Encodierungsverzögerung:	35.248 ms
Transportverzögerung:	2316.711 ms
Entschlüsselungsverzögerung:	14.214 ms
Fec Prozentsatz:	5 %
Fec Verlust gesamt:	0 Packets
Fec Verlust pro sekunde:	0 Packets/sek
Client FPS:	52 fps
Server FPS:	54 fps
```
If there's anything else which could help, please let me know.

**Comment by ronthecookie** [comment]
>  I try to avoid discord when possible, but might join later.

@frostworx I've been guessing this might be the case for some people; maybe we can get an IRC or [Matrix](https://matrix.org) bridge going if more people are comfortable with that. (@xytovl, yay or nay?)

**Comment by xytovl** [comment]
I don't care the protocol as long as we don't fragment discussions. If someone wants to to the setup it's fine.

**Comment by lmarianski** [comment]
> @lmarianski [That isn't supposed to work!](https://www.youtube.com/watch?v=My0lzMuNcHI) We haven't worked on that at all yet and no one has gotten it running before you so I have some questions:
> 
> * What audio server are you running? (PulseAudio, PipeWire, pure ALSA)
> * Did you perform any extra steps in your audio server to get it to work?
> * If you're on PulseAudio, can you run `pactl info` and `pactl list` and send the output?
>   
>   * `pw-cli info all` for PipeWire.
> * Did you patch any code?

@ronthecookie 
I'm running PipeWire as a replacement for both PulseAudio and JACK, on Arch Linux.
IIRC i didn't mess with the PW config at all, here's the output of pw-cli while i'm hearing VRChat audio from the headset: https://pastebin.com/Z40hLytR
For the audio settings i have Stream game audio selected (enabling microphone streaming does cause a error on connection), and "jack" as the audio device ("pipewire" and "pulse" cause it to crash, the rest do nothing, iirc).
And nope i haven't edited any code

**Comment by ronthecookie** [comment]
Oops, forgot to @lmarianski. Sorry!

**Comment by IlyaMZP** [comment]
> Update: it seems that the IVRDriverDirectModeComponent interface that ALVR uses is not supported on Linux ([ValveSoftware/openvr#749](https://github.com/ValveSoftware/openvr/issues/749)) and we still don't know anything about the IVRVirtualDisplay interface ([ValveSoftware/virtual_display#5](https://github.com/ValveSoftware/virtual_display/issues/5))

Good news! SteamVR beta 2.5.1 seems to add IVRDriverDirectModeComponent support to Linux: https://store.steampowered.com/news/app/250820/view/4146199229186243608

**Comment by Vixea** [comment]
yep I'm already working on it
