### ISSUE TITLE
Add dashboard translation to more languages

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#281]
Languages added so far:
* Italian (by @zarik5)
* Spanish (by @jonathanhecl)
* French (by @phileas0408)
* Japanese (by @KawaSwitch)
* Simplified Chinese (by @k7Ysh5A41)
* Russian (by @5he1n and @Agantor)
* German (by @Caligo-Immortalem and @Noel-Sa)
* Bulgarian (by @pyvelkov)
* Dutch (by gman and @Armarr)
* Slovenian (by @CathodeXT)
* Korean (by @wonjj0317)

The text to translate is defined by the files in `server_release_template/web_gui/js/app/nls`. In all the English files, add a line with `"xx": true,` where `xx` is the language code. Create a folder named with the same language code and add the translation files inside. For `settings.js` you can omit the translation for strings marked with `//adv` (the advanced settings). Make sure to change the links to the correct locale.
Look at other translations for reference.
If you decided to add a language (or add missing parts), fork this repository, make your changes and then submit a PR.

If you would like the "translator" role on Discord please DM me (I often cannot find you if you have a different user tag).

**EDIT: translations are on hold. We are working on a new dashboard. You can let us know on Discord your availability and we will ping you once you can start working on the translation.**

**Comment by KawaSwitch** [comment]
Hi. I'm currently working on Japanese translation and had a problem.

OS: Windows 10 pro
Server version: 12.2.0

Once I registered driver on the directory containing a Japanese path, I cannot delete it even if I press delete afterwards.
It just says "Driver successfully unregistred" but nothing happens on UI.
And what's worse, it shows garbled characters as shown below.

![alvr_character_corruption](https://user-images.githubusercontent.com/41296626/92199704-dd24fe80-eeb2-11ea-8e41-66eb89eb557c.PNG)

Or should I make another issue post for this?

**Comment by zarik5** [comment]
Thanks for your work! Yes, the driver registration bug is unrelated, you can open a new issue.
You can open a pull request for the translation.

**Comment by KawaSwitch** [comment]
Ok, I'll post the new issue with more details attached and a pull request when I'm done.

**Comment by pyvelkov** [comment]
Hello, 
Could I add a translation for Bulgarian?
I will most likely have a PR for you tomorrow latest.

**Comment by zarik5** [comment]
@pyvelkov Sure, thanks!

**Comment by zarik5** [comment]
There is a new dashboard in the works. Language localization will not be supported anymore.
