### ISSUE TITLE
Check for updates on client and server

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#283]
Optionally, create an autoupdater for the server.

**Comment by zarik5** [comment]
Anyone can self assign this issue if you want

**Comment by zarik5** [comment]
@JackD83 When you have time I think you can help me here: first of all we could add a check on the UI that queries the GitHub release page (with web scraping or using the GitHub API). If there is a new server version, we can show a persistent notification box or a banner, that when clicked it redirects to the releases page.
The current server version can be queried with `/version` on javascript.

**Comment by evanmalmud** [comment]
Are server clients ever linked? Or are all servers backwards compatible for minor versions?

**Comment by zarik5** [comment]
@evanmalmud Client and server are compatible if they have the same first number for the version, like v13.0.0 <-> v13.5.1.

**Comment by zarik5** [comment]
On the server the autoupdater has been implemented. On the client, Oculus will offer a service for installing apps outside the official store without requiring developer mode. This system will probably support auto updates. I'm keeping the issue open until this system has been released.

**Comment by Ekristoffe** [comment]
> 
> 
> On the server the autoupdater has been implemented. On the client, Oculus will offer a service for installing apps outside the official store without requiring developer mode. This system will probably support auto updates. I'm keeping the issue open until this system has been released.

Wow Oculus will enable another way to install app !!! Snow will fall tomorrow ...

**Comment by zarik5** [comment]
This issue can be closed. ALVR will gain automatic updates support for the client if it gets accepted on Oculus App Lab.
