### ISSUE TITLE
Full body tracking

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#313]
For people that bought the Quest 2 but also still have the Quest 1 laying around, we could use the Quest 1 as a hip tracker that also tracks the controllers strapped to the feet.
For people that don't have a spare Quest or don't want to strap it to the waist, we could implement a hip tracker using just the 3dof sensors of a smartphone.

**Comment by xcloudx01** [comment]
Is it even possible to pair an extra pair of controllers to the headset?

**Comment by zarik5** [comment]
No, the tracking system of the Oculus Quest is hardcoded for only two controllers, at the chip level.

**Comment by AmmarkoV** [comment]
You can perform Body pose estimation using an RGB camera and neural networks like https://github.com/FORTH-ModelBasedTracker/MocapNET however there is no "bridge" for VR yet

**Comment by zarik5** [comment]
@AmmarkoV Thanks for the link. I know there are methods with outside-in tracking like with a Kinect, but I wanted to make something that does not require external sensors, to keep the standalone nature of the Quest.

**Comment by AmmarkoV** [comment]
@zarik5  Yeah I understand, in any case for full body tracking I think the way to go currently is via an external body tracker that beams 3D body poses to the Quest  -> http://ammar.gr/oculus/elixir.webm

**Comment by korejan** [comment]
This can be closed, [it was done and merged sometime ago](https://github.com/alvr-org/ALVR/pull/650)
