### ISSUE TITLE
Cannot see desktop in SteamVR

### ISSUE THREAD

**Issue by lesmo** [alvr-org/ALVR#330]
# Please follow the general troubleshooting steps first:

- [x] I ran "add_firewall_rules.bat" as adimistrator and checked that the ports are open in the firewall
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Bug reports:

Attempting to view the desktop(s) through SteamVR's menu results in no video from desktop (just transparent background). Everything else works as expected, though.

#### Environement

* What hardware do you have:
  Intel i7-8750H CPU, RTX 2070 Max-Q
* What version of ALVR and SteamVR have you tried:
  ALVR v12.4.1 with SteamVR v1.14.16
* Do you have the latest Windows updates:
  Yes, Windows 10 v2004

**Comment by Nexite** [comment]
I don't believe that this issue is due to ALVR, take a look at https://www.reddit.com/r/SteamVR/comments/fdatfp/steamvr_desktop_not_working/fztxeqn/?context=8&depth=9, it could help.

**Comment by lesmo** [comment]
Thanks for the suggestion! I thought it could be something with ALVR since Oculus Link showed the desktop just fine. I tried the steps in that Reddit post but it didn't seem to make much difference.

**Comment by ScottESanDiego** [comment]
FWIW, showing the desktop works for me in ALVR (2700X, 2080Ti, Win10 20H2, ALVR 12.5.0).

My only point being that it doesn't seem to be a wholesale ALVR/Desktop issue.

**Comment by loongenix** [comment]
I have this problem too

**Comment by lesmo** [comment]
> I have this problem too

Virtual Desktop works fine, so... if you really need it, just switch to Virtual Desktop.

**Comment by mortifia** [comment]
@lesmo if you pay for ok

same issue in pico4  vwith steam vr desktop invisible
