### ISSUE TITLE
Stuttering issue on Quest 2

### ISSUE THREAD

**Issue by xcloudx01** [alvr-org/ALVR#341]
https://www.youtube.com/watch?v=PK4FzEoneu8

I'm having this issue where the image will suddenly stutter for a few frames, or sometimes it flickers and then there's like video encoding garbage as shown in the video. I've tried adjusting all the settings but it keeps happening. Any ideas?
I'm using:
v12.5.0 APK and Windows client.
Win 10 version: 2004
GPU: RTX 2070 Super
CPU: i5-8600K

**Comment by stephenc87** [comment]
This appears to happen on the Quest 1 as well as on the Quest 2
The fact that this also occurs in other streaming solutions with SteamVR makes me think it's SteamVR causing it
VD on Oculus doesn't get this, however VD on steamvr does

**Comment by tobias7an** [comment]
I'm experiencing the same issue, which has led to some nausea, but it only began a few days ago for me. 
It occurs consistently at all times in all applications including steamvr home, but does not affect either menu.
I have tried rebooting both headset and the host computer with no effect.
There is zero frame drop and packet loss.

**Comment by evanmalmud** [comment]
I have some stuttering whenever I turn my head on the quest 2 in the steamVR menu. 
Once I'm in a game it seems to run a bit smoother, but then as the OP said will get random sections of stuttering. 
No warnings or errors in the logs for ALVR.

I just set this up today so no comment on prior builds.

**Comment by evanmalmud** [comment]
> https://www.youtube.com/watch?v=PK4FzEoneu8

link doesn't seem to work
