### ISSUE TITLE
Connect to client behind second router 

### ISSUE THREAD

**Issue by trubrek** [alvr-org/ALVR#349]
So i have two routers, one from my internet provider and second is tenda ac1200 and my idea is to connect my quest 2 to WiFi of my second router and the rest devices in my household to the first router from my internet provider..

My connection route is:  PC (192.168.0.51) > Ethernet to first router > Ethernet to second router > 5g WiFi to my quest 2 (192.168.1.121 q2 ip)

But problem is i cant see my quest 2 in server list on pc. i mean it not connect to the stream server.
so i tried command adb shell am startservice -n "com.polygraphene.alvr/.ChangeSettings" --es "targetServers" "192.168.0.51"

that give me error below:
Starting service: Intent { cmp=com.polygraphene.alvr/.ChangeSettings (has extras) }
Error: Not found; no service started.

if i connect my quest to to WiFi of my first router then everything is working

**Comment by Nexite** [comment]
What version of ALVR are you using?

**Comment by trubrek** [comment]
its latest version , ALVR server v12.6.1 and client is 12.5

**Comment by Nexite** [comment]
I'm not sure that this is possible as the second router has its own closed system and probably can't connect to devices that are connected to the first router. Try pinging your quest from your pc.

**Comment by trubrek** [comment]
i tried that already and request timed out, but i was thinking that ALVR client and server on separate networks guide is for this specific use

**Comment by trubrek** [comment]
i think there is issue with that command adb shell am startservice -n .... error is is not found, no service started
and if i run only adb shell am startservice -n there is not com.polygraphene.alvr in list

**Comment by Nexite** [comment]
First try pinging your quest, it says at the bottom "ALVR does NOT provide any kind of tunnel, NAT traversal etc. UDP ports 9943 and 9944 of ALVR server (VR gaming PC) must be accessible from ALVR client (Oculus Quest) otherwise this won't work." which means that you probably have to set IP a tunnel for this to work. It's pointless to try to debug this if you can't even ping your quest in the first place.

**Comment by zarik5** [comment]
@trubrek that ADB command does not work on ALVR v12, you need to use v11 or prior, but v11 is not compatible with the Quest 2. During the v13 release cycle we will re-add a way to setup remote connections.

**Comment by trubrek** [comment]
Oh good, thank you @zarik5  it sorted all then for now. i will wait till new release thank you

**Comment by einsz** [comment]
Since v13 was released a few days ago, is it now possible to specify a ip address again? I my wifi and lan in different subnets and die Quest is ping-able from my pc, but no way to connect them :(

**Comment by zarik5** [comment]
@einsz Unfortunately no. You have to wait for v14 when we rewrite the connection code.

**Comment by jorgeazevedo** [comment]
@zarik5 in old versions of ALVR it was possible to patch the android source code to hardcode the IP address it connects to. Do you know if that would work now? If so, any chance you could link to the method that needs to be patched?

My cloud gaming setup requires ALVR and I was hoping to use it to play moh. Without ChangeSettings or a way to patch the code, I’m stuck :-/

**Comment by christovic** [comment]
Following this as would be great to manually specify the IP.

**Comment by zarik5** [comment]
@christovic We are really close! We just need to make the user interface for it

**Comment by christovic** [comment]
Amazing! Look forward to seeing it :)

**Comment by zarik5** [comment]
This should be now possible with v14.1.0. I would really like to know if you manage to make it works! We also need to write a guide

**Comment by SniperIII** [comment]
I have the same routers problem.
Does someone has an answer?

**Comment by zarik5** [comment]
You can use ALVR across subnets if you use TCP and specify the client IP and hostname manually.
