### ISSUE TITLE
ALVR settings screen is all black (when long pressing menu button)

### ISSUE THREAD

**Issue by jjgh** [alvr-org/ALVR#351]
Suddenly the ALVR setting screen that pops un in VR when long pressing the menu button became all black and I can't see anything on it anymore 
The screen correctly pops up, just it's all black.
I tried restarting every single component: the ALVR client, the ALVR server, SteamVR but nothing worked. 
In the end I also rebooted my system and restarted my Quest 2 but with no result.
What could it be?
Again, it was showing up just fine for some time... but then it became just a black rectangle.

**Comment by pepfof** [comment]
I think reinstalling (maybe cleaning session.js) fixed this for me.

**Comment by jjgh** [comment]
@pepfof I tried reinstalling to a completely clean folder but the problem in my case persists...

**Comment by ratozumbi** [comment]
Is this issue fixed with the latest release of AVLR? What version where you using?

**Comment by jjgh** [comment]
I am using latest versions of both client and server.
Please see https://github.com/alvr-org/ALVR/issues/356 for a more generic description of this issue (also affecting short-press of the menu button) which I documented in much more detail.

**Comment by DocMAX** [comment]
Same for me, but only Quest 2 is black. Quest 1 ist ok. (WTF?)

**Comment by zarik5** [comment]
@DocMAX I see the same thing. I think they removed the webview engine (Q1 still runs on android 7.1, Q2 runs on android 10, so under the hood is completely different).

**Comment by zarik5** [comment]
I worked around the problem by removing the webview altogether.

**Comment by jjgh** [comment]
Will you please make a new release with this? Thanks

Il Dom 6 Dic 2020, 20:43 Riccardo Zaglia <notifications@github.com> ha
scritto:

**Comment by maxer456** [comment]
There already is a release that includes this change: [v13.1.0+client](https://github.com/alvr-org/ALVR/releases/tag/v13.1.0%2Bclient)

**Comment by jjgh** [comment]
thanks a lot
