### ISSUE TITLE
Picture freezes on connection

### ISSUE THREAD

**Issue by xenoliferttv** [alvr-org/ALVR#352]
[SteamVR-2020-11-18-PM_07_57_31.txt](https://github.com/JackD83/ALVR/files/5562231/SteamVR-2020-11-18-PM_07_57_31.txt)
`

Alright.` Im mentally exhausted by now, one day it works the other it doesnt. Im super pissed at how unreliable this software seems to be

Ryzen5 3600x
RX 580
16gb ddr3
Windows 10
everything on latest release
cat 6 lan 1gb, 40mhz 802.11ac router tplink archer smth
everything worked stable with relive vr for some reason... 

Tried:
Reinstalling SteamVR (clean, used guide), oculus software and alvr several times. 
Turning off firewall
trying every possible setting in basic alvr setup menus (<buffers size, lowering and increasing video resoultion and bitrate, disable throttling, suppress frame drops, agressive keyframe resend etc...) 
rerunning alvr setup, putting it in different locations (simply desktop now) 
untrusting and trusting headset again
restarting everything
making sure relive is uninstalled, resetting firmware

strangely enough i can run room setup on steam just fine connected over alvr, but frames freeze no matter what i do. 

[1117/235422.097:ERROR:directory_reader_win.cc(43)] FindFirstFile: Das System kann den angegebenen Pfad nicht finden. (0x3)

19:32:55.508822200 [INFO] Failed to send log with websocket: IO error: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen. (os error 10053)
(after IO error: The established connection got discontinued by software on hostcomputer. (os error 10053) 

Which fucking software would that be? I have 0 clue. 
Please help me, im mad. Other then that id pick ALVR over ReLive everyday, love your work. 

cheers

**Comment by ratozumbi** [comment]
What frame freezes? The ALVR screen, some frame from Steam VR or other screen?
Does ALVR shows the Oculus as disconnected?
Does other connections with the Oculus are also breaking? (exemple: if you keep pinging Oculus, will it stop when ALVR freezes?)

**Comment by tyrel** [comment]
I'm having the same problem. In my case, I see the Steam VR screen come up and then it freezes after a few frames. It was working the day before. I can collect more data if necessary, it's pretty frustrating.

**Comment by domacikolaci** [comment]
Used to have same issue but so far V14.0 has resolved problem. My issue was as ALVR was connecting to the server, the frame would freeze and only show that white environment asking you to run the server.

**Comment by tyrel** [comment]
It does seem to be fixed for me in 14.0.0 as well.

**Comment by zarik5** [comment]
On v14 we have more control over the IDR frame request (that unfreezes the screen on the client). I guess I can close the issue.
