### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by UncoupledHorse5** [alvr-org/ALVR#355]
ALVR Launcher.exe when ran, will get stuck on the spinning dots loading screen. This is a consistent problem and I can't figure out how to fix it. Im on version 13.0 by the way.

**Comment by ratozumbi** [comment]
Please respond even if you already fixed the problem.

Is your computer and the Oculus on the same 5G wifi network?
Do you have google chrome installed?
Can you click on anything else on the server? (can you browse the configurations and etc?)
