### ISSUE TITLE
Freezing and crashing when pressing the menu button

### ISSUE THREAD

**Issue by jjgh** [alvr-org/ALVR#356]
- [x] I carefully followed the instructions in the [README](https://github.com/JackD83/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/JackD83/ALVR/wiki)

### Environment

VR Device: Oculus Quest 2 (with latest software updates)
CPU: Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz 
GPU: GeForce GTX 1050
RAM: 16,0 GB
OS: Windows 10 Education 20H2 build 19042.630
Steam and SteamVR: latest versions
ALVR Server and Client: latest versions (but I had the problems documented below with previous versions as well)

### Bug reports:

Hi, I have problems with the menu button, both when short pressed and long pressed.

If I short press it (when in SteamVR) the SteamVR dialog shows up, but after a few seconds everything freezes and SteamVR on Windows says: "SteamVR error, SteamVR had an unexpected problem, please restart SteamVR (-203)".

If I long press it (when in SteamVR) the ALVR dialog does not appear and in place of it a black rectangle appears (I previously documented this in https://github.com/JackD83/ALVR/issues/351, but it seems that was only a more specific case of the generic issue with the menu button I am documenting here).

I remember that when I first installed ALVR (like one month ago) I could correctly see the ALVR setting screen when long pressing the menu button, but then after some time it begun to act like I said above.

### Things I tried:

- I reset all ALVR parameters to default by deleting session.js
- in ALVR server I unregistered all listed drivers and only registered the ALVR driver 
- I deleted the AVLR folder completely and installed somewhere else (in a short path without UTF-8 chars)
- In new ALVR server I did NOT register ALVR drivers (as recommended). In this case the only registered driver is: "C:\Program Files\Virtual Desktop Streamer\OpenVRDriver"
- Uninstalled and reinstalled Steam and SteamVR
- Reinstalled GPU drivers
- I restarted my system multiple times in the middle of the above processes 

I think that another important thing to note I think is that in Virtual Desktop the menu button works correctly, either when short pressing (to open SteamVR dialog) or long pressing (to open Virtual Desktop dialogue) and it does not cause any freezing, even after long time of use.
However ALVR seems to run much smoother on my system (less stuttering) than Virtual Desktop so that's why I am here...

Except from the menu button I would say that ALVR works fine, but since mine is not exactly a top notch machine I definitely need the ALVR screen to tweak parameters here and there and make it run smoother (but again, as I said the above problems also happen with default settings).

Can you guys please help? If you need to know any other info just ask!
Thanks!

**Comment by zarik5** [comment]
I'm also experiencing a black ALVR dashboard on my Quest 2. But also i'm having a CONNECTION REFUSED on my Quest 1. I will first fix the connection problem on v14, but unfortunately it seems that the black screen on Q2 is caused by the v23 firmware update. I never seen SteamVR crashing like that but I experienced heavy stuttering when I open the SteamVR menu.
