### ISSUE TITLE
13.2.0 causing SteamVR to start in safe mode

### ISSUE THREAD

**Issue by DocMAX** [alvr-org/ALVR#358]
When i start ALVR it runs SteamVR but in save mode, telling me alvr_server is disabled. If i let it restart it's still the same.
I hadn't this problem with 13.1.0!

**Comment by JosNun** [comment]
If you re-enable the ALVR add-on for SteamVR (details [here](https://github.com/alvr-org/ALVR/wiki/Troubleshooting-(for-ALVR-13.1.0-and-later)#steamvr-says-headset-not-detected)), does is still crash? If so, please attach the SteamVR logs for review (it tells you how to get the logs on the troubleshooting page).

**Comment by DocMAX** [comment]
I allready re-enabled the plugin and restart. I don't see any crash. It just disables alvr_server (and Gamepad) again, over and over again. I have to check for the log.

**Comment by DocMAX** [comment]
Strange after some restarts and driver (un)registration it finally works. I don't know exactly how i did this. So never mind at the moment - thanks!
