### ISSUE TITLE
Feature Request: Auto-Mute PC Audio on Connect

### ISSUE THREAD

**Issue by DocMAX** [alvr-org/ALVR#359]
Could you implement this feature please? The pc audio should be muted ONLY when actially streaming. Not when SteamVR is running.

**Comment by zarik5** [comment]
This is a bit hard to do, since ALVR uses the system audio device. If you mute it you mute also the audio stream to the Quest.

**Comment by DocMAX** [comment]
If i mute the PC audio i still hear the Quest audio

**Comment by zarik5** [comment]
Probably you are using a different audio device for streaming. In this case we need to figure out how to change windows settings for audio. It could be done.

**Comment by DocMAX** [comment]
The selected audio device in ALVR is the same default audio device used by windows (NVIDIA HD Audio).

**Comment by maxer456** [comment]
I usually mute PC audio through SteamVR overlay - that doesn't affect volume of the audio stream to the headset (though I've only ever did this with one audio interface).
So I think this should be doable.

**Comment by zarik5** [comment]
> The question is whether to do it before the audio streaming rewrite, or after.

I don't think there is a cross-platform way of muting an audio device (CPAL is not help), we could implement it sooner in C++ (or Rust+winapi, as you prefer).

**Comment by evanmalmud** [comment]
@maxer456 Wouldnt this cause the PC to not play sound so if you are using it to cast for people it will now be muted? This seems like an optional thing to set. And seems fairly easy to just do yourself on windows with the mute button.

**Comment by maxer456** [comment]
Muting the Windows audio endpoint shouldn't affect software that captures the stream to that endpoint. So speakers will be muted but software like OBS should still be able to capture sound.
It will be optional, yes. It's just a convenience option so you don't have to remember to mute your speakers every time.

**Comment by maxer456** [comment]
Implemented as of v14.0.0.
