### ISSUE TITLE
Headset is not detected

### ISSUE THREAD

**Issue by davidcian** [alvr-org/ALVR#360]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

The New Clients list remains empty despite both the ALVR server and client running.

#### Environment

What hardware do you have: CPU, GPU, Audio

I have an Intel Core i7-8750H with integrated graphics Intel UHD Graphics 630. The discrete GPU is an NVIDIA GeForce GTX 1060 with Max-Q Design.  

What version of ALVR and SteamVR have you tried. 

I have downloaded the ALVR 13.2.1 release and have SteamVR version 1.15.12.

Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number

I have version 1909, build 18363.1198 of Windows 10.

#### Troubleshooting attempts

I believe AP isolation to be disabled, as I followed the steps outlined [here](https://superuser.com/questions/1458646/how-can-i-as-a-user-check-if-ap-isolation-is-enabled-for-a-wi-fi-network) and I can see the correct IP and MAC for the headset in the ARP table. I installed the APK of the same release using SideQuest. I have installed the Visual C++ redistributable as specified in the README. I have manually enabled inbound connections on UDP ports 9943 and 9944, even disabled the firewall completely a couple of times.

SteamVR does ask me to do a room setup, which I cannot do as I have no sensors, so I just close the window. Following this, the headset is always shown as "Standing by" in SteamVR.

I have also tried switching to the HEVC (h265) video codec and restarting SteamVR, to no avail.

**Comment by ratozumbi** [comment]
Can you ping your headset using the host computer? Can you avoid using an AP?

**Comment by JosNun** [comment]
Also, give [these](https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-client-list-is-empty) troubleshooting steps a try when you get a chance.

Another troubleshooting step is to set up a hotspot on your computer if it has a wireless card, and connect your Quest directly to that. That'll help eliminate any issues with the network blocking traffic.

**Comment by davidcian** [comment]
> Can you ping your headset using the host computer?
> What is between your computer and the Quest besides the router?
> Can you confirm ALVR is been used by the GTX 1060?

Pinging the headset works almost perfectly, both when it is unplugged, using WiFi, as well as when it is connected to my computer using the USB C cable. There is nothing between the computer and the Quest, other than the router, according to traceroute.

I've no clue how to rigorously check whether ALVR is using the GPU, but Task Manager does show 0% utilization for `ALVR Launcher.exe`, so I believe it isn't used, but the Steam Client Bootstrapper does start using the GPU when I run the ALVR Launcher.

**Comment by davidcian** [comment]
I believe a problem lies in the fact that I cannot do the SteamVR room setup (if I understand correctly SteamVR should just pick up the Oculus Quest 2 Guardian boundary, not ask for a setup using base stations). Another possibility might be that I'm connected on the 2.4GHz band to my router, not the 5GHz one (although I can't connect to the admin interface to check...).

**Comment by omeryagmurlu** [comment]
I have the same problem (on a 2.4 GHz band, can't test it with 5GHz unfortunately)

**Comment by davidcian** [comment]
Quick update: the headset does appear when connecting to a 5GHz connection. It could be a good idea to not mark this as resolved unless there is a warning somewhere that a 5GHz connection is required.

**Comment by zarik5** [comment]
The 5Ghz connection is only a recommendation, it is not mandatory to connect to the headset.
