### ISSUE TITLE
Extremely slow send speeds

### ISSUE THREAD

**Issue by kevinnmark** [alvr-org/ALVR#361]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Packet send rate is terribly slow. 1.5Mbps
<img width="575" alt="Capture" src="https://user-images.githubusercontent.com/23639503/101280906-33fce580-37cc-11eb-8ea9-ef8ed1664c21.PNG">

#### Environment

**What hardware do you have: CPU, GPU, Audio**
Processor	Intel(R) Core(TM) i7 CPU         940  @ 2.93GHz, 2934 Mhz, 4 Core(s), 8 Logical Processor(s)
AMD Radeon HD 7900 Series

**What version of ALVR and SteamVR have you tried.** 
ALVR: ALVR server v13.2.1
SteamVR: STEAMVR 1.15.12

**Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number**
Yes, Windows 10 Pro Version	10.0.19041 Build 19041

### Troubleshooting Attempts:
I've checked all my router settings and all other devices on the 5ghz network (channel 40) and they seem to have decent speeds. ~750Mbps

My Desktop PC running the server reaches up to 900Mbps.

Tried turning off all devices to reduce the amount of traffic on the 5ghz network. 1.5Mbps speeds from ALVR

Ran a fast.com speed test using the Oculus browser and got 600Mbps, so the internet connection from the Quest 2 isn't bad.
I've disabled all antivirus and even turned off the firewall to try (exceptions were installed anyways), but to no avail.

It's just for some reason, whenever I launch ALVR from the oculus I never see anything. I can see it connects to the server because it starts to display all the statistics, but in the Quest 2 it is just black. The steam home doesn't load, nothing. Then I look at the speed and it just won't surpass 1.6Mbps so I assume it isn't loading anything.

Is there anything else I can try?

**Comment by kevinnmark** [comment]
Attaching a session log to see if that helps
[session_log.txt](https://github.com/alvr-org/ALVR/files/5648809/session_log.txt)

**Comment by maxer456** [comment]
That slow speed you're seeing is ALVR sending just the audio stream. Video stream isn't running, likely because the video resolution is set too high for the encoder, considering your AMD card. Lower the video resolution scale in ALVR settings.

Also note that internet speed is irrelevant for ALVR, since it operates only on the local network, but it's ideal to have the Quest as the only device on the 5Ghz network.

**Comment by kevinnmark** [comment]
That did the trick! Thank you maxer for the clarification and explanation 👍
