### ISSUE TITLE
ALVR installed succesfull but won't open again

### ISSUE THREAD

**Issue by LouisIsBescht** [alvr-org/ALVR#364]
I uninstalled the old Version of ALVR and intalled the newest Version v13.5.1. The intallation was succesfull but when I want to open the program it opens for a very short moment and then runs in the background. I also tried other versions but the problem stays the same.

Environement

Intel i7 10700k
Nvidea 2060 
Windows 10 (latest version)

**Comment by Ekristoffe** [comment]
@LouisIsBescht hello,
Have you tried with the latest version ?
Thanks
