### ISSUE TITLE
Controllers Tracking so bad

### ISSUE THREAD

**Issue by Master-Antonio** [alvr-org/ALVR#366]
CPU: AMD RYZEN 5900x
GPU: NVIDIA GTX 3080
RAM : 16 GB RAM
WIFI: 5GHZ 
VR : QUEST 2

I installed alvr, but the controllers do not work at all, it seems that the environmental sensors do not work, I tried to do the room setup via steam vr, but it is really buggy, the controllers of my quest 2 can only move them left and right on 1 axis, it does not recognize when I go up with my hand, that is, it does not exceed my chest, the controllers as soon as they arrive under my viewer do not go further, that is, I can not put them frontally, what should I do?

**Comment by zarik5** [comment]
It looks like you disabled positional tracking. This could happen when the room is not lit enough. Go in the settings on the Quest and re-enable positional tracking.
