### ISSUE TITLE
 Wrong floor height

### ISSUE THREAD

**Issue by Master-Antonio** [alvr-org/ALVR#369]
OS : WINDOWS 10
CPU: AMD 5900X
GPU: Nvidia 3080
OCULUS QUEST 2

Hi guys, i have a problem with the floor height, i followed the tutorial of steam vr, 
I put the viewer on the floor, and I left at 0 centimeters, but in the game they are very high from the floor, about 10 centimeters difference, this causes problems in games like half life, that I can't catch objects on the ground or I hit the floor of my house. What should I do?

**Comment by zarik5** [comment]
If you need to calibrate the floor this means you are using an old version of ALVR. Please download the latest version in the releases page.

**Comment by Master-Antonio** [comment]
I have already last version. I configured the room via Steam VR to play.

**Comment by evanmalmud** [comment]
At least with the quest 2 I had to set to floor height in the guardian settings on the quest interface not the steamVR one.

**Comment by Master-Antonio** [comment]
Yeah, there isnt match, i had used OVR ADVANCED , no perfect result but better ...

**Comment by dantecsm** [comment]
same question, strange

**Comment by BulletinMatches** [comment]
> same question, strange

I've had this problem but it was minor (like 2ish cm) and all I use is OVR advanced settings, interestingly I also got the floor issues when I used to play with a link cable
