### ISSUE TITLE
Oculus Rift and Rift_S in native mode

### ISSUE THREAD

**Issue by Master-Antonio** [alvr-org/ALVR#370]
hi, i bought The Walking Dead Saints and Sinner on Steam.
But i cant play with ALVR because give me this error.
![image](https://user-images.githubusercontent.com/9674957/103156507-72713900-47a9-11eb-83d5-698d6197c61d.png)

**Comment by maxer456** [comment]
For TWD:SS specifically, you can make it work just through SteamVR, without installing the Oculus software.
You need to open GameUserSettings.ini in `%localappdata%\TWD\Saved\Config\WindowsNoEditor` and put
`bEnableOculusSteamVR=True`
under
`[/Script/TWD.TWDGameUserSettings]`

Then you either use Rift S headset/controllers mode, but you need to bind the "resethmd" action to joystick click.
Or use Vive headset/controller emulation, which I think works without rebinding (but has awkward movement controls).

For other "Oculus native" games (from the Oculus store), you can use [Revive](https://github.com/LibreVR/Revive).

**Comment by Master-Antonio** [comment]
bEnableOculusSteamVR=True in what file?

**Comment by maxer456** [comment]
From your response I'm guessing the solution worked, so I'm closing the issue.
