### ISSUE TITLE
Dashboard crash

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#371]
When connecting and then disconnecting from a client, the dashboard on ALVR window will crash after some minutes. The crash happens even when the dashboard is opened in a browser (on PC or on the headset).

**Comment by Ekristoffe** [comment]
Do you need to disconnect from the headset ? like closing the oculus app ? to have this problem happening ?

**Comment by zarik5** [comment]
This problem seems to be gone. Maybe fixed with #373.
