### ISSUE TITLE
Virtual microphone not detected

### ISSUE THREAD

**Issue by Xinurval** [alvr-org/ALVR#374]
Hey there, firstly thanks so much for the project, its brilliant and much appreciated.

The issue i have noticed is that the microphone does not work, as ALVR detects the output devices for both microphone and audio streaming. Please see the picture for details
![ALVR](https://user-images.githubusercontent.com/56453160/103159138-9b032e00-47bd-11eb-821e-75576cc00274.jpg)

**Comment by maxer456** [comment]
This is the expected result. ALVR itself doesn't play directly to an audio input device or create a device of its own, hence the need for the VB-Audio CABLE driver or similar software.

ALVR only plays the microphone audio streamed from the headset to the selected output device. The CABLE driver then does the actual routing from CABLE Input to CABLE Output. So if you select CABLE Input as the microphone device in ALVR, you should see the streamed microphone audio coming out through CABLE Output.

**Comment by Xinurval** [comment]
Brilliant thanks so much for the clarification!
