### ISSUE TITLE
Rework of UI code

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#375]
Currently the javascript code autonomously checks for updates to the client list and uses some logic to break an infinite feedback loop of session save<->session updated when more than one web client is connected.

Background: the server communicates with the web UI through log commands sent though a websocket. Log lines can contain data delimited by `#{ }#` in the form of json. All possible commands can be found here: https://github.com/alvr-org/ALVR/blob/master/alvr/common/src/logging.rs#L110 (fields are converted to camelCase).

* Update the UI in response to `#{ "type": "sessionUpdated", "data": { "webClientId": ..., ...} }` only when the `webClientId` is different from the own one.
* Make the UI update the client list only in response to `#{ "type": "sessionUpdated", "data": { ..., "updateType": "clientList"} }`
* Enter and exit stream statistics mode only in response to `clientConnected` and `clientDisconnected`.
* Other log commands like `clientFoundWrongVersion` should be intercepted and produce a custom and localized notification message.

(A few of these things may already be fixed but i did not thoroughly check the code)

Another thing (that doesn't regard the interop with the server): it would be better to hide the startup spinner only when the UI finished loading, to avoid seeing the UI flashing and snapping into place.

**Comment by Armarr** [comment]
I might be missing some background here but why even allow multiple web clients to run simultaneously?
You could disallow multiple instances of the executable to run:
https://users.rust-lang.org/t/how-to-ensure-there-is-only-one-instance-of-the-application/5170/18
Or just don't allow more than 1 TCP connection from the server side.

**Comment by zarik5** [comment]
The dashboard can be open in the ALVR launcher window and in the Oculus Browser or a smartphone.

**Comment by Ekristoffe** [comment]
if I may I would like to add
- Use let and const instead of var, if externat access needed create setter and getter function.

**Comment by zarik5** [comment]
@Ekristoffe I agree completely. I already encountered a nasty bug solved by switching from var to let

**Comment by zarik5** [comment]
Beside optimization and better integration with the server, there are other things we could consider to make the code maintainable and easy to extend:
* For translations: merge translation files into one per language (not sure if this could cause slower loading times);
* For logic code: witch to a framework like React and/or to TypeScript;
* All in one rewrite: switch to Rust + webassembly (use the Elm-like Iced library for the UI) or to Elm
