### ISSUE TITLE
Correct controller in steam vr home, but not in game (eg the wizards)?

### ISSUE THREAD

**Issue by tokke100** [alvr-org/ALVR#378]
I have been looking for a solution with this issue:

Steam vr home will show the correct quest/rift s controller.
But once I start the wizards (game on steam), the controllers are messed up.

To move or rotate around my position I have to click the joystick in that direction. Any fix out there?
Not all games have this issue.

**Comment by zarik5** [comment]
Try to switch to Vive or Valve Index emulation mode for the controllers

**Comment by tokke100** [comment]
Thank you for the response, I'll try this out.
