### ISSUE TITLE
Encoder error

### ISSUE THREAD

**Issue by Xinurval** [alvr-org/ALVR#379]
Strange error when using HEVC 265. Shows up only for a second before disappearing, yet alvr does not work.
![Screenshot 2020-12-27 175842](https://user-images.githubusercontent.com/56453160/103176857-2daed600-486d-11eb-9ee7-00e4773277dc.jpg)

**Comment by maxer456** [comment]
From the contents of the error message I assume you're using an AMD card. Only cards with VCE 3.0 or later can encode using HEVC, so depending on what GPU you're using, yours might only support H.264.
Unfortunately that error message isn't really clear (and can mean several different things, either an unsupported card, unsupported codec or using too high video resolution). Sorry about the confusion.

**Comment by Xinurval** [comment]
It was indeed a high video resolution, ty so much!
