### ISSUE TITLE
Adding back run command on connect/disconnect

### ISSUE THREAD

**Issue by DavisNT** [alvr-org/ALVR#385]
Can/should we add back "run command on connect" and "run command on disconnect" options (as advanced Connection settings)? 
I can do the coding for this. 

P.S. I know these options were non-functional on ALVR v11 (I had fixed and used those).

**Comment by zarik5** [comment]
Sure, that seems like a useful addition.

**Comment by zarik5** [comment]
The feature is on master and the issue can be closed.
