### ISSUE TITLE
Need to restart

### ISSUE THREAD

**Issue by BulletinMatches** [alvr-org/ALVR#387]
I'm not sure if this is an issue exclusive to me but each time I close ALVR and try to reopen it it will load unless I restart my computer otherwise everything else works well.

**Comment by Ekristoffe** [comment]
Hello, if I understand right, after closing ALVR you can't reopen it ?
do you have anything on the screen about ALVR ? like a white window or a loading window ?

**Comment by BulletinMatches** [comment]
> Hello, if I understand right, after closing ALVR you can't reopen it ?
> do you have anything on the screen about ALVR ? like a white window or a loading window ?
> 

When I close it and then try to open it it loads for about 30 seconds then it says that the server couldn't be loaded and if I click retry it just keeps loading I've left it on for about 10 minutes and it just keeps loading.

**Comment by Ekristoffe** [comment]
Your problem seems more to be with steam vr.
When you close ALVR, can you check on the task manager if SteamVR is also closed ?

**Comment by BulletinMatches** [comment]
I have tried completely even closing down steam and the same issue still occurs, also if I restart the server I cannot reconnect the headset.

**Comment by BulletinMatches** [comment]
> I have tried completely even closing down steam and the same issue still occurs, also if I restart the server I cannot reconnect the headset.

I just tried launching steam vr while the server is loading manually and it seems to connect fine.

**Comment by Ekristoffe** [comment]
what version of alvr have you tried ?
have you used the portable version or installer one ?
could you do a test with those version:
v14.1.0
v14.2.0-beta.3
v14.2.0 stable
Thanks.
