### ISSUE TITLE
Force disconnect the headset

### ISSUE THREAD

**Issue by grzegorz-dzikowski** [alvr-org/ALVR#389]
Sometimes, I have an issue, after closing alvr in the headset (because for example network problems or microphone problems) ALVR server don't want to disconnect. The process is still sending data to headset with 100% packet loss. I would like an option to force close all connections for reconnecting the headset, so I don't have to restart SteamVR and everything

**Comment by Ekristoffe** [comment]
hello could you try with the version:
v14.1.1
v14.2.1
And see if it has been fixed ?
On my headset if I close the app the stream stop and steam VR goes into headset disconnected some second after.
