### ISSUE TITLE
(Critical problem) Error stacking, why???

### ISSUE THREAD

**Issue by Riverface** [alvr-org/ALVR#397]
# Please follow the general troubleshooting steps first:

- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

When a wireless card is unplugged or disabled, or anything like that, ALVR has a fit and sends out enough errors to stack up and break the DPC watchdog. **IN SECONDS**. This killed a hard drive and new network card of mine, and I'm pretty mad at y'all to tell the truth.

#### Environement

What hardware do you have: Ryzen 3700X, Nvidia RTX 2060, realtek onboard audio card
What version of ALVR and SteamVR have you tried. The latest. 
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number 

(19041.685)

**Comment by BulletinMatches** [comment]
I have had a similar experience but all I had to do was restart windows and it was fine. I don't think something like that could kill a hard drive unless it was already on its way out.

**Comment by Ekristoffe** [comment]
fixed January 8 (i think also in v14.1.0)
