### ISSUE TITLE
If someone can not connect with pc,may becouse of vpn on quest

### ISSUE THREAD

**Issue by xzkeee** [alvr-org/ALVR#407]
It troubled me for days. 
When I turn off the VPN on quest,problem solves.

**Comment by Ekristoffe** [comment]
@xzkeee thanks for the information. I don’t have a quest myself... could you explain to me what are the step needed to disable this VPN?

**Comment by xzkeee** [comment]
> @xzkeee thanks for the information. I don’t have a quest myself... could you explain to me what are the step needed to disable this VPN?

this VPN is set up by myself, so turn off is just the same as set it up.
to set up a vpn on quest ,simply install the VPN you use apk file vie sidequest(pc) to quest(need open delvelpor account first), find it in unknown app on the quest;(just same as install alvr to quest)
then everything is just like an android phone.

**Comment by virtself** [comment]
Are you sure you have enabled local discovery in your vpn client?

**Comment by xzkeee** [comment]
> Are you sure you have enabled local discovery in your vpn client?

maybe my vpn client doesn't have this feature, or not set as default.
