### ISSUE TITLE
This is a problem when changing to Quest 2 controller index controller.

### ISSUE THREAD

**Issue by KMM1292** [alvr-org/ALVR#408]
After ALVR recognizes Quest 2 and changes it to the index controller in the settings, the grip does not work when used.
There's hand motion, but it doesn't work.

I think it's because the index controller is under pressure.

<PC>
CPU: Ryzen 3 3100
GPU: GTX 1660
RAM: DDR4 16G

**Comment by ronthecookie** [comment]
Closing as no one has followed up on this in 126 days.
