### ISSUE TITLE
Implement autoupdater inside the dashboard

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#419]
The autoupdater has been removed from the launcher. Now we need to reimplement it into the dashboard (the reason for this is aggregating functionality into the driver and making a nicer UI with more info)

The UI should check at startup if there is an update, using the GitHub API. The URI is: `https://api.github.com/repos/alvr-org/ALVR/releases/latest`. From the response collect the name, tag, changelog, installer URL and binary size, then show all the info in a modal box if the current version and tag from github are different (also the settings about update prompt and channel should be respected). When the user accepts the update, send a request to the webserver at `/update` with the installer URL as the body. Optionally, we can listen for the log id `updateDownloadedBytesCount`, calculate the progress status and show a progress bar. In case of error, the server returns 502 BAD_GATEWAY; if the error happens during the download, also the `updateDownloadError` log id is sent.

EDIT: To clarify, to compare tag and current version we need to:
* remove the "v" prefix from the tag
* If on the beta channel accept both stable and beta releases. Beta releases contain the substring "-beta"
* latest nightly release must be queried with `https://api.github.com/repos/alvr-org/ALVR-nightly/releases/latest`

**Comment by Ekristoffe** [comment]
On it

**Comment by zarik5** [comment]
This is done! Thank you @Ekristoffe!
