### ISSUE TITLE
Massive decode latency on Quest 1

### ISSUE THREAD

**Issue by Pesoen** [alvr-org/ALVR#424]
# Please follow the general troubleshooting steps first:

- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

no matter what settings i change, after updating to the latest 14.1.0 of the server and client(from version 12.4.1) it has massive decoding latency. this was not an issue previously, and has only started happening after the upgrade. i have tried resetting all settings and completely reinstalling alvr on both quest and pc..

what i have tried so far:
Change bitrate(was at 35 i think, set it to 14, did not help)
Change video resolution(was 75%, set it to 25%, did not help)
Change codec(was H264, set it to H265, did not help)

what i am going to try:
going back to 12.4.1 and see if that works, and slowly inch my way up and see if there is a particular version that causes the issue to start.
clearing out EVERYTHING that has to do with alvr from my quest(folders and files and everything after uninstalling it)

Streaming Statistics:
Total Packets: | 93044 Packets
PacketRate: | 1991 Packets / s
Total packets lost: | 24736 Packets
Packets lost / s: | 0 Packets / s
Total sent: | 128Mb
Sent rate: | 21.951 Mbps
Total latency: | 60.028 ms
Encoder Latency: | 2.948 ms
Encode latency max: | 3.472 ms
Transport latency: | 15.035 ms
Decoder latency: | 6.715 ms
Fec percentage: | 10 %
Fec failure total: | 84 Packets
Fec failure / s: | 0 Packets / s
Client FPS: | 59 fps
Server FPS: | 72 fps

#### Environement

What hardware do you have: I7-6700k, GTX 1070 8GB, Onboard Audio.
What version of ALVR and SteamVR have you tried. 
ALVR: 14.1.0, gonna try going back to 12.4.1.
SteamVR: 1.15.19
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number
20H2(Build 19042.685)

**Comment by Pesoen** [comment]
i am such an idiot.. restarting my quest fixed the issue.. it also happened in the older version(12.4.1) so i tried restarting my quest, and bam it works as expected now.. sorry to bother you with my stupidity..

**Comment by zarik5** [comment]
You're not stupid. If ALVR worked right it should fix this problem on it own, without requiring you to restart. But ALVR has still many bugs and it takes time to fix them.

**Comment by Pesoen** [comment]
while somewhat true, that fact that restarting my oculus quest fixed the issue, means its something i did somehow(i think at least) but still kinda odd. i suspect an app was running in the background, after some tinkering closed the app earlier, and since then it felt a bit slower(playing games took much longer to load and had slight lag at times) but i did not think anything of it, after a restart it works flawlessly, and games load faster without any lag.. so yeah, i am the idiot in this case.. should have known something was wrong when it closed the app without telling me it closed(the usual error screen saying something went wrong)
