### ISSUE TITLE
SteamVR addons are disabled when SteamVR starts.

### ISSUE THREAD

**Issue by Xefise** [alvr-org/ALVR#425]
### Bug reports:

ALVR on the headset stuck on Searching for server also SteamVR add-ons are disabled when SteamVR starts. (Steam says something like "addons are disabled because of crash")

I have solved the problem by changing the Steam interface language to English. The problem did not appear again even when I changed the language to Russian.
(I tried reinstall SteamVR(including configs). It have not solve the problem)

#### Environment

What hardware do you have: **_Ryzen 1600(3.4GHz), GTX 1080, Bloody G501_**
What version of ALVR and SteamVR have you tried. **_I tried versions: 13.1.0-14.1.0_**
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number: **_1903_**

**Comment by zarik5** [comment]
If the problem presets itself again:
* use the installer
* delete the session.json
* Restart ALVR with the button on the launcher.

**Comment by Xefise** [comment]
@zarik5, I did it all but the solutions do not help. And I installed ALVR versions: 14.1.0, 13.1.0, 13.6.1. The problem exists in all of them.

Sorry for my English. It may be bad.

**Comment by Ekristoffe** [comment]
Hello @Xefise if I am right: your pc language was in Russian and it had something which was blocking ALVR from working.

I may be able to test with virtual machines on non wester Europe language ...
Maybe it was a path problem ...

**Comment by Xefise** [comment]
Hello @Ekristoffe. My Steam, Windows and ALVR was in Russian. I have changed the Steam language to English and in next SteamVR startup ALVR has found the server. 
I had reloaded Steam before (for reinstalling SteamVR). So I think the language was the problem.

**Comment by 1orest** [comment]
Учите русский, а то Женя напрягся
