### ISSUE TITLE
Quest 2 stuck at searching for server

### ISSUE THREAD

**Issue by BinaryBreaker** [alvr-org/ALVR#426]
[vrserver.txt](https://github.com/alvr-org/ALVR/files/5821793/vrserver.txt)

### Bug reports:
The ALVR app in the Quest 2 is stuck at the hostname and searching for sever even though ALVR is properly configured
I have already asked for support in the discord

I have already tried many troubleshooting measures, I believe this is not user error.

#### Environement

AMD Ryzen 7 2700X
NVIDIA Geforce GTX 1660 TI
Windows 10 2004 19041.685

**Comment by zarik5** [comment]
I'm sorry but I cannot help you if you don't give me any kind of clue on where to search for the bug. Probably you just have a misconfigured network.

**Comment by BinaryBreaker** [comment]
> 
> 
> I'm sorry but I cannot help you if you don't give me any kind of clue on where to search for the bug. Probably you just have a misconfigured network.

how may I check that

**Comment by BinaryBreaker** [comment]
> 
> 
> I'm sorry but I cannot help you if you don't give me any kind of clue on where to search for the bug. Probably you just have a misconfigured network.

I have been able to setup ADB servers on the quest 2 in the past

**Comment by zarik5** [comment]
Try to ping for the client. https://github.com/alvr-org/ALVR/wiki/Troubleshooting#alvr-cant-see-my-headset

Anyway, I prefer to close this issue since it's too generic and not helpful.
