### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by GilbertzRivi** [alvr-org/ALVR#429]
### Bug reports:

When I connect my headset to ALVR server, it restarts and shows up the following errors:
"Failed to start audio capture. Thread aborted before starting to loop-back capture.
message=IMMDevice::Activate(IAucioClient) failed: hr = 0x99980004"
And then right after:
"Exception on sound capture.
message=IMMDevice::Activate(IAucioClient) failed: hr = 0x99980004"
Audio on headset from steamvr isn't working.

I've already tried reinstalling steamvr, alvr, downgrading it to 14.0 and reinstalling windows. I have disabled all audio enchantments and on windows, steamvr and alvr, the audio device is set to my integrated sound card with my headphones plugged in. I have  "Mute output when streaming" set in my alvr and despite this the sound is coming out of my headphones, but nothing is playing on headset. Audio outside the ALVR application (on headset) works fine and it also does when I'm using a cable connection. I've tried changing the audio device to dedicated sound card and monitor (which has the audio connected from the graphics card), but neither of them worked. 

#### Environment

Hardware:
Intel i5=8600K, RTX2070, xonar AE/realtek HD audio. 
Software:
ALVR 14.0.0 and 14.1.0, steamvr the newest one on date 16.01.2021
My windows compilation is: 20H2 19042.746

**Comment by Hashnoob** [comment]
I tried all the same things as you, including trying a portable audio sound card dongle. And I still have the same problem.

`"Exception on sound capture. message=IMMDevice::Activate(IAudioClient) failed: hr = 0x88890004"`

`"Failed to start audio capture. Thread aborted before starting to loopback capture. message=IMMDevice::Activate(IAudioClient) failed: hr = 0x88890004"`

Everything else has been great. Does anyone have any workarounds?

**Comment by zarik5** [comment]
A quick google search says that you unplugged the audio device that ALVR selected. Try selecting again the default device and try again.

**Comment by GilbertzRivi** [comment]
It didn't help

**Comment by Hashnoob** [comment]
I disabled all enhancements, and spatial sound, set each to 16bit 48000 Hz. I have tried several playback devices enabled them one at a time and manually set the device in ALVR, SteamVR and Windows.

**Comment by zarik5** [comment]
I'm sorry but I don't know how to solve this issue. I'm working on rewriting the audio code, maybe the problem will go away after that.

**Comment by Hashnoob** [comment]
No worries man, I hope the rewrite can work things out. Thanks for all the work.

I did some more testing this morning and I got audio working in an odd manner.

Current Solution:
Install the Windows version of VirtualDesktop and use the VirtualDesktop audio device as the default in Windows, ALVR and SteamVR. 

And now the audio capture works great in ALVR on the Quest 2. >.>

**Comment by thehhmdb** [comment]
Could ALVR be distributed with it's own audio driver like Virtual Desktop to get around these type of problems?

I don't know too much about how the audio works in ALVR, but would an open source low latency driver like this help:
https://github.com/spotify/NFDriver

**Comment by zarik5** [comment]
In the last beta I removed some resampling code, and this cause an usability regression (since now the user might need to change the audio settings in the control panel). For this reason I plan to develop a virtual audio driver before the next stable version.
