### ISSUE TITLE
Implement assisted manual hole-punching for connection across NATs

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#431]
The current connection system works only on local networks. There is a feature for adding client IPs manually that handles the case where server and client are on different subnets but not the case where they are behind different NATs.
To connect client and server across NATs we need to use the hole-punching technique, commonly used in p2p applications. Usually hole-punching is performed with the help of a public central server (which is not behind a NAT). Since we do not have one we either need to rely on third party services like ZeroTier, or we can get help from the user to take the role of the central server.

The manual hole-punching is performed as follows:
- Client and server obtain their own public IP and ports using a STUN server. They must obtain the public ports corresponding to local TCP 9943 and UDP 9944.
- Public IP and ports are read by the user and entered on the other side (client data into server and server data into client)
- With the help of a global clock, server and client will simultaneously send UDP packets to each other and try to initiate a TCP connection, but only the client will listen for packets and connections. After one or two tries the connection should establish successfully.
- Both UDP and TCP connections must be kept alive by sending packets periodically.

Regarding the user interface, there should be a setting for enabling remote connections (for the synchronized sending of packets). A button in the connection tab should be used to interrogate the STUN server and then display the public IP and ports. The client requires a user interface to enter the server data. On the server, the configuration view for each client should allow to enter the client public UDP and TCP ports.

This procedure is quite burdening for the user just to initiate a connection. Also the public IPs and ports might expire frequently and must be re-entered to initiate a new connection. Ultimately the best decision might be to rely on services like ZeroTier to connect client and server remotely. In that case no special consideration must be taken on ALVR part.

**Comment by ilmatematico** [comment]
I would also argue about the fact that is maybe better to flip the connection listening direction, or at least adding an option for it.

That is to say that to have the listener  on the server side (PC). So  we can specify the IP to connect on the quest side (IP of the pc), instead of setting the IP of the client from the server side as it is now.

**Comment by zarik5** [comment]
@ilmatematico For now this is problematic:
1) The client does not have a user interface. There are no VR UI toolkits for native. There was an attempt to use a webview to render the UI but from firmware v23 on Quest 2 the webview does not work anymore.
2) The old method for specifying the server address using ADB has been removed as part of the ongoing rewrite. Since it was bound to Android and we want to move towards cross-platform compatibility, there is no intention to re-add this method.

**Comment by ilmatematico** [comment]
I see, maybe it is possible to think about a thin bridge app (even just a command line one) to be run on the same network of the Quest to set these parameters  client-side, so it will not broke cross-platform and is easy to implement from the "UI" perspective.

**Comment by zarik5** [comment]
That is an interesting idea. We could integrate this directly into the server app.

**Comment by ronthecookie** [comment]
IIRC this kind of hole-punching is [quite hard to implement correctly](https://tailscale.com/blog/how-nat-traversal-works/), there are a lot of edge cases.
