### ISSUE TITLE
Client build fails when looking for dependencies

### ISSUE THREAD

**Issue by salvolannister** [alvr-org/ALVR#442]
### Bug reports:

I tried to build the app client thorugh Android Studio but I have this error:

```
Build file '_C:\Users\salvolannister\Downloads\ALVR-14.1.0\alvr\client\android\app\build.gradle_' line: 2

A problem occurred evaluating project ':app'.
> Plugin with id 'org.mozilla.rust-android-gradle.rust-android' not found.
```

Thus I run in a terminal **_C:\Users\salvolannister\Downloads\ALVR-14.1.0>xtask install-deps**
this is the result that I have with no .jar in folder "deps" : 

```
   Compiling alvr_xtask v1.0.0 (C:\Users\s.gurzi\Downloads\ALVR-14.1.0\alvr\xtask)
    Finished dev [unoptimized + debuginfo] target(s) in 4.04s
     Running `target\debug\alvr_xtask.exe install-deps`

rustup target add aarch64-linux-android
info: component 'rust-std' for target 'aarch64-linux-android' is up to date


C:\Users\S23A4~1.GUR\AppData\Local\Temp\cache\a0a5d248e72534ab8ec57584946c09641f719cc14bb34fefc598fb1f578eb4e5.02c313d9556e338574cdf53ec05ddd73d215208b6e94ba5eaeeaf7e8aa3027cc-extracted\rust-android-gradle-6e553c13ef2d9bb40b58a7675b96e0757d1b0443\gradlew.bat publish
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Impossibile trovare il file specificato." }', alvr\xtask\src\dependencies.rs:30:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\alvr_xtask.exe install-deps` (exit code: 101) 
```

I guess my problem could be the file path that is too long ( I saw that in _dependencies.rs_ a workaround is used for the path of "**plugin_path**". Trying to do  

`let download_path = download_path.canonicalize().unwrap();`

just before dependencies.rs:30 doesn't help tough

#### Environement

HARDWARE: Oculus Quest 
ALVR: 14.1.0 client 

WINDOWS: 20H2

**Comment by zarik5** [comment]
The canonicalized path may still be too long. Try changing it to a different path.

> Thus I run in a terminal _C:\Users\salvolannister\Downloads\ALVR-14.1.0>xtask install-deps

Also I assume you executed `cargo xtask install-deps` on the project root folder here.

**Comment by salvolannister** [comment]
I tried to move it to c:\ and to execute `cargo xtask install-deps` in ### C:\ALVR-14.1.0\alvr\client\android> but still no luck

**Comment by zarik5** [comment]
@salvolannister Yesterday on master I added the prebuilt rust-android gradle extension, so you don't have to call `cargo xtask install-deps` anymore.

**Comment by salvolannister** [comment]
Sorry I haven't see this, I am able to build now. What I have done to solve the problem was deleting the content of Temp in AppData, then it worked.
I still cannot debug it says " Install successfully finished in 2 s 246 ms.
**Could not identify launch activity: Default Activity not found
Error while Launching activity**"

**Comment by zarik5** [comment]
Try with a clean clone. Launch the build directly from Android Studio.

**Comment by salvolannister** [comment]
In Android Studio I went in "**Run>EditConfigurations**" and then I selected  in Launch Options "specified activity" and then I put underneath _com.polygraphene..._
