### ISSUE TITLE
Packets not reaching Client in external mobile network

### ISSUE THREAD

**Issue by salvolannister** [alvr-org/ALVR#443]
### Bug reports:

When attempting to connect ALVR client inside a separate mobile network with a **Huawei B525s-23a** router to a remote network server, we realized that the server is able to see the client and trust it, but then the client is unable to receive any other information.

We analyzed the packets sent by the server with Wireshark and we saw that the server keeps sending video frame (first byte of data frame were 09 ) but the client is stuck with the intro view ( "trust your client") 

We also tried to send packets with **iperf** from the client to the server and the opposite.
From client to server we saw that we have no trouble when sending packet long less than 1500 bytes but a lot of losses when this treshold is exceeded.
While sending from server to client we have no network problems.

#### Environement

HARDWARE: oculus quest 2,1 
STEAMVR: 1.14.16
ALVR client: 12.5.0
ALVR server: 12.6.1
WINDOWS version: 10 version 20H2 (OS Build 19042.685)

**Comment by zarik5** [comment]
Unfortunately I didn't have the chance of testing the manual clients over the network. Actually we saw that without hole-punching or any special handling, client and server cannot establish a connection, without port forwarding on both ends. Also we currently don't have control of the size of packets, or to be precise, that code is old and I don't have the knowledge to make adjustments. We are gradually rewriting the code and taking control of the whole streaming pipeline.

**Comment by salvolannister** [comment]
I still didn't test it with the new version, but I will try and let you know soon. The connection between user and server in separate networks works fine unless you don't put one of them in a mobile one.

We used the old version of the client to specify the public ip of the server
