### ISSUE TITLE
Use without installing Chrome/Chromium

### ISSUE THREAD

**Issue by xchellx** [alvr-org/ALVR#446]
- [ ✔️] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [✔️ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

I cannot successfully install ALVR due to the requirement of Chrome/Chromium for WebView support. I do have Vivaldi installed, which is Chromium-based but the installer does not detect it. After ignoring the error (refusing to install Chrome/Chromium), ALVR will open and immediately close when ran. Please add support for other Chromium-based browsers such as Vivaldi.
crash_log.txt:
```
15:14:23.164332100 [ERROR] At alvr\server\src\lib.rs:179: Error in locating chrome: An installation of chrome/chromium could not be found

```

Windows 10 Enterprise LTSC 2019 64-bit, Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 CPUs), ~2.4GHz, and 4095MB NVIDIA GeForce GTX 1650 with Max-Q Design (MSI).

ALVR v14.2.0-beta.1, SteamVR 1.15.19

I am running from Windows 10 LTSC 2019, which is locked to one version of Windows 10, however, I do get monthly updates. Windows Update says I am up to date. My build version is 1809.

**Comment by zarik5** [comment]
We are currently limited by the library we are using for the webview, but we already submitted a couple of pull request for adding functionality needed by ALVR and the original author was quite responsive. So what we can do is adding a way of specifying custom paths for chromium executables. I'm quite busy with other things, but maybe @maxer456 or @Nexite can do this.

**Comment by Ekristoffe** [comment]
hello, by looking at the library repo i have found this:
https://github.com/Srinivasa314/alcro/issues/11
ALCRO_BROWSER_PATH can be set to your browser of choice. 
maybe you can try this for the moment and see if it make things work ?

**Comment by zarik5** [comment]
Thanks @Ekristoffe, I forgot about that.

**Comment by xchellx** [comment]
The `ALCRO_BROWSER_PATH` environment variable worked fine. It has to point to the executable though, not the directory. Mine is set as `C:\Program Files\Vivaldi\Application\vivaldi.exe` for reference here. Also, with this I see much less memory usage from ALVR -  138.3MB compared to the 2GB a Chromium process used (and that was the de-google-fied version). Thanks very much for mentioning this workaround!

**Comment by 1337haXXor** [comment]
Does this not work with portable browser installs? I tried setting the ALCRO_BROWSER_PATH environment variable to my portable vivaldi and chromium installs, verified by running "echo ALCRO_BROWSER_PATH" in cmd, but neither work. I get an error at alvr\server\src\dashboard.rs:38, saying chrome/chromium cannot be found.

**Comment by nermur** [comment]
Can this issue be re-opened? It's still a usability issue. along with what was mentioned in #966.
