### ISSUE TITLE
oculus go xbox controller

### ISSUE THREAD

**Issue by Kenjiftw** [alvr-org/ALVR#460]
Can you use steamvr with alvr using just the oculus go controller and an xbox controller? It seems that i can't navigate in the steamvr dashboard because the oculus go controller isn't being recognized.

**Comment by Ekristoffe** [comment]
hello, the oculus go controller is not functionnal: right in the main page of ALVR:

Headset | Support
-- | --
Oculus Quest | ✔️
Oculus Quest 2 | ✔️
Oculus Go | ✔️ (no controller)
GearVR | ❌ (use this)
