### ISSUE TITLE
ALVR Linux returns errors during Build

### ISSUE THREAD

**Issue by nfl0** [alvr-org/ALVR#461]
### **Description**
***

When I try to build for v14.2.0 release it fails

**Steps to reproduce**

    apt install libssl-dev libasound2-dev libgtk-3-dev
    cargo xtask build-server --release (it fails)

Project fails when trying to build with error

       Compiling libc v0.2.84
       Compiling cfg-if v1.0.0
       Compiling autocfg v1.0.1
       Compiling proc-macro2 v1.0.24
       Compiling unicode-xid v0.2.1
       Compiling cc v1.0.66
       Compiling syn v1.0.60
       Compiling memchr v2.3.4
       Compiling pkg-config v0.3.19
       Compiling log v0.4.14
       Compiling lazy_static v1.4.0
       Compiling version_check v0.9.2
       Compiling cfg-if v0.1.10
       Compiling once_cell v1.5.2
       Compiling futures-core v0.3.12
       Compiling fnv v1.0.7
       Compiling slab v0.4.2
       Compiling itoa v0.4.7
       Compiling pin-project-internal v0.4.27
       Compiling bytes v0.5.6
       Compiling bitflags v1.2.1
       Compiling pin-project-lite v0.1.11
       Compiling pin-project-lite v0.2.4
       Compiling openssl v0.10.32
       Compiling bytes v1.0.1
       Compiling typenum v1.12.0
       Compiling foreign-types-shared v0.1.1
       Compiling matches v0.1.8
       Compiling serde_derive v1.0.123
       Compiling getrandom v0.2.2
       Compiling native-tls v0.2.7
       Compiling futures-io v0.3.12
       Compiling tinyvec_macros v0.1.0
       Compiling getrandom v0.1.16
       Compiling serde v1.0.123
       Compiling hashbrown v0.9.1
       Compiling crc32fast v1.2.1
       Compiling httparse v1.3.4
       Compiling ppv-lite86 v0.2.10
       Compiling pin-utils v0.1.0
       Compiling futures-sink v0.3.12
       Compiling ryu v1.0.5
       Compiling adler32 v1.2.0
       Compiling adler v0.2.3
       Compiling gimli v0.23.0
       Compiling openssl-probe v0.1.2
       Compiling percent-encoding v2.1.0
       Compiling try-lock v0.2.3
       Compiling byteorder v1.4.2
       Compiling rustc-demangle v0.1.18
       Compiling regex-syntax v0.6.22
       Compiling tower-service v0.3.1
       Compiling encoding_rs v0.8.26
       Compiling httpdate v0.3.2
       Compiling object v0.23.0
       Compiling serde_json v1.0.61
       Compiling void v1.0.2
       Compiling ucd-trie v0.1.3
       Compiling mime v0.3.16
       Compiling unicode-width v0.1.8
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:162:41
        |
    162 |             [0x7f, b'E', b'L', b'F', 1, ..] => FileKind::Elf32,
        |                                         ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:164:41
        |
    164 |             [0x7f, b'E', b'L', b'F', 2, ..] => FileKind::Elf64,
        |                                         ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:166:38
        |
    166 |             [0xfe, 0xed, 0xfa, 0xce, ..]
        |                                      ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:167:40
        |
    167 |             | [0xce, 0xfa, 0xed, 0xfe, ..] => FileKind::MachO32,
        |                                        ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:169:40
        |
    169 |             | [0xfe, 0xed, 0xfa, 0xcf, ..]
        |                                        ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:170:40
        |
    170 |             | [0xcf, 0xfa, 0xed, 0xfe, ..] => FileKind::MachO64,
        |                                        ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:172:38
        |
    172 |             [0xca, 0xfe, 0xba, 0xbe, ..] => FileKind::MachOFat32,
        |                                      ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:174:38
        |
    174 |             [0xca, 0xfe, 0xba, 0xbf, ..] => FileKind::MachOFat64,
        |                                      ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:178:26
        |
    178 |             [b'M', b'Z', ..] => {
        |                          ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:194:26
        |
    194 |             [0x4c, 0x01, ..]
        |                          ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
    error[E0658]: subslice patterns are unstable
       --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:196:28
        |
    196 |             | [0x64, 0x86, ..] => FileKind::Coff,
        |                            ^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/62254
    
       Compiling opaque-debug v0.3.0
       Compiling ipnet v2.3.0
       Compiling remove_dir_all v0.5.3
       Compiling number_prefix v0.3.0
       Compiling either v1.6.1
       Compiling base64 v0.13.0
       Compiling ascii v0.9.3
       Compiling cpuid-bool v0.1.2
       Compiling linked-hash-map v0.5.4
       Compiling same-file v1.0.6
       Compiling glob v0.3.0
       Compiling fs_extra v1.2.0
       Compiling pico-args v0.4.0
       Compiling tracing-core v0.1.17
       Compiling futures-task v0.3.12
       Compiling thread_local v1.1.2
       Compiling futures-channel v0.3.12
       Compiling indexmap v1.6.1
       Compiling miniz_oxide v0.4.3
       Compiling num-traits v0.2.14
       Compiling num-integer v0.1.44
       Compiling unicase v2.6.0
       Compiling generic-array v0.14.4
       Compiling foreign-types v0.3.2
       Compiling unicode-bidi v0.3.4
       Compiling http v0.2.3
       Compiling tinyvec v1.1.1
       Compiling miniz_oxide v0.3.7
       Compiling form_urlencoded v1.0.0
       Compiling unreachable v1.0.0
       Compiling pest v2.1.3
       Compiling openssl-sys v0.9.60
       Compiling bzip2-sys v0.1.9+1.0.8
       Compiling runas v0.2.1
       Compiling walkdir v2.3.1
    error: aborting due to 11 previous errors
    
    For more information about this error, try `rustc --explain E0658`.
    error: could not compile `object`.
    warning: build failed, waiting for other jobs to finish...
    error: build failed

**Comment by zarik5** [comment]
It seems you are using an old version of Rust. Some Linux distributions ship with a version of Rust, but ALVR requires v1.49. Install the latest version with rustup.

**Comment by nfl0** [comment]
Current output:

  warning: unused imports: `AtomicUsize`, `CStr`, `Once`, `Ordering`, `c_void`, `os::raw::c_char`
    --> alvr/server/src/lib.rs:21:11
     |
  21 |     ffi::{c_void, CStr, CString},
     |           ^^^^^^  ^^^^
  22 |     net::IpAddr,
  23 |     os::raw::c_char,
     |     ^^^^^^^^^^^^^^^
  ...
  26 |         atomic::{AtomicUsize, Ordering},
     |                  ^^^^^^^^^^^  ^^^^^^^^
  27 |         Arc, Once,
     |              ^^^^
     |
     = note: `#[warn(unused_imports)]` on by default
  
  error[E0282]: type annotations needed for `std::option::Option<T>`
     --> alvr/server/src/connection.rs:429:48
      |
  429 |             let mut maybe_muted_device_index = None;
      |                 ----------------------------   ^^^^ cannot infer type for type parameter `T` declared on the enum `Option`
      |                 |
      |                 consider giving `maybe_muted_device_index` the explicit type `std::option::Option<T>`, where the type parameter `T` is specified
  
  error: aborting due to previous error; 1 warning emitted
  
  For more information about this error, try `rustc --explain E0282`.
  error: could not compile `alvr_server`

**Comment by zarik5** [comment]
Sorry, It's a bit hard for me to keep track of errors on linux, since I only work on windows for convenience. I can fix that error but in the future I need to setup a linux CI.

**Comment by nfl0** [comment]
Thank you. Issue fixed on v14.2.1
