### ISSUE TITLE
Ringing audio

### ISSUE THREAD

**Issue by Dal1ster** [alvr-org/ALVR#462]
When i start ALVR V14.2.0, it works like normal except the audio whenever i did something in the headset would make a corrupted ringing like sound. Has anyone else had this issue?

**Comment by zarik5** [comment]
Can you send an audio file?

**Comment by Dal1ster** [comment]
https://user-images.githubusercontent.com/76823236/106372774-faf27480-6327-11eb-8047-6ad03e7eb908.mp4

**Comment by zarik5** [comment]
I don't have time to work on this. I converted the last two releases to prerelease, you should stay on ALVR v14.1.0.
