### ISSUE TITLE
[ERROR] Client discovery failed: At alvr\common\src\sockets\mod.rs:23:

### ISSUE THREAD

**Issue by NOodle512** [alvr-org/ALVR#466]
Anyone have a fix for this? honestly idk what's going on, i downloaded the newest version and this keeps popping up.

Even when i reinstall it, same thing every time ...

Crash Log : 12:52:56.834669600 [ERROR] Client discovery failed: At alvr\common\src\sockets\mod.rs:23: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)

**Comment by NOodle512** [comment]
Anyone have a fix for this? honestly idk what's going on, i downloaded the newest version and this keeps popping up.

**Comment by Noel-Sa** [comment]
I had the same error, rebooting my quest fixed it.

**Comment by NOodle512** [comment]
did it? ill try that i guess
