### ISSUE TITLE
15:23:27.469185800 [ERROR] At alvr\server\src\connection.rs:327, Client discovery failed: At alvr\common\src\sockets\mod.rs:69: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)

### ISSUE THREAD

**Issue by NOodle512** [alvr-org/ALVR#467]
the other error from before was fixed but now there's another one and rebooting did not fix it ... ;w;

Pls help ;w;

**Comment by Noel-Sa** [comment]
I don't know exactly, but all that port stuff sounds like a firewall issue. Maybe some ppl in the discord can help you...

**Comment by NOodle512** [comment]
im dumb and didnt think about this i restarted my pc xD and it fixed the issue

**Comment by zarik5** [comment]
By looking at the code, it seems this error was already fixed in ALVR v14.2.0, but I set is as beta because people had other problems with it.

**Comment by NOodle512** [comment]
for some reason restarting my pc fixed the issue , so im happy : D
