### ISSUE TITLE
Alvr v14.2.1 Oculus Quest 2 not working

### ISSUE THREAD

**Issue by SeanYo9229** [alvr-org/ALVR#468]
Every time I try to use ALVR v14.2.1 on my Oculus Quest 2, this message pops up and Steam VR just doesn't work. Can someone please help! I have attached the error message and my computer stuff.
![System 1_31_2021 11_40_00 AM (2)](https://user-images.githubusercontent.com/78313965/106403129-f9de4780-63fa-11eb-9e33-4654fbb64da4.png)

![thing](https://user-images.githubusercontent.com/78313965/106403107-e206c380-63fa-11eb-93b1-2bb713d1abc2.PNG)

**Comment by Ekristoffe** [comment]
hello what graphic card do you have ?

**Comment by SeanYo9229** [comment]
> hello what graphic card do you have ?

How do I find this on Windows 10?

**Comment by SeanYo9229** [comment]
> hello what graphic card do you have ?

Nevermind, I found it, it is an "Intel(R) UHD Graphics 620"

**Comment by Ekristoffe** [comment]
does ALVR crash on launch or on connect ? is there any log on the log file (crash.log or something like this).

**Comment by zarik5** [comment]
ALVR does not support Intel GPUs.

**Comment by SeanYo9229** [comment]
> does ALVR crash on launch or on connect ? is there any log on the log file (crash.log or something like this).

It crashes when I start the server.

**Comment by SeanYo9229** [comment]
> ALVR does not support Intel GPUs.

Oh. well that stinks, but thanks!

**Comment by SeanYo9229** [comment]
> > ALVR does not support Intel GPUs.
> 
> Oh. well that stinks, but thanks!

**Comment by Ekristoffe** [comment]
we know ... it is a decoder problem.
