### ISSUE TITLE
ALVR Desktop client refuses to launch - "Visual C Redist (x64) NOT installed"

### ISSUE THREAD

**Issue by Binksmann** [alvr-org/ALVR#480]
Upon installing ALVR and installing the provided Microsoft Visual C Redistributable, ALVR continues to stop launching and alert that Visual C Redist x64 is not installed. Checking Windows indicates that the redist is installed correctly and is recognized by the operating system. There appears to be no way to use the application like this.
 
 Things I tried:

-Older Version
-Reinstalling ALVR
-Reinstalling the Visual C package
-Ensuring proper permissions are in place
-Making sure that ALVR installs to the default directory

Have not tried
-Uninstalling other versions of Visual C (for sake of not breaking some random program I go to use in a month or two.) 

If you need more information let me know.

**Comment by Ekristoffe** [comment]
what version of alvr have you tried ?
have you used the portable version or installer one ?
could you do a test with those version:
v14.1.0
v14.2.0-beta.3
v14.2.0 stable
Thanks.

**Comment by Binksmann** [comment]
The version I tried was 14.1.1; This is what had the issue. Version 13 also had the problem.

I just now installed version 14.2.0, and It launched successfully.

**Comment by Ekristoffe** [comment]
Thanks.
Those data are really precious for us to understand the problem and solve it quickly.

**Comment by zarik5** [comment]
v14.2.0 just removed the check. We are now bundling the dlls in the driver directory but this may cause problems for other people (we didn't have the chance to test this thoroughly).
