### ISSUE TITLE
Center of room is shifted.

### ISSUE THREAD

**Issue by Xefise** [alvr-org/ALVR#482]
### Bug reports:

Center of room moves to left/right 1 meter at Steam VR and it does not locate correctly when I hold down the "Oculus" button. But at the lobby of ALVR the center locates correctly. My friend has the same problem.

#### Environments

What hardware do you have: Oculus Quest, Ryzen 1600 (OC to 3.4GHz), GTX 1080, RAM: 16GB, 2666 MHz
My friend has: MD FX(tm)-8320 Eight-Core Processor 3.50 GHz, GTX 960, RAM: 20 GB
The problem exists only at versions: v14.x 
Our Windows 10 versions numbers: 1903, 20h2

**Comment by zarik5** [comment]
I'll work on this before the next release.

**Comment by Xefise** [comment]
It looks something like this. 
https://youtu.be/yPEjnw3agE0
I have only turned around on the spot a few times in the video.

**Comment by Ekristoffe** [comment]
hello are you using oculus prediction ? 
for the hand tracking ? 
I had also this trouble (unwanted warp/teleport). 
I think some parameter need to be adjusted.

**Comment by Xefise** [comment]
@Ekristoffe, hello I do not use oculus prediction because of bad tracking. My friend can send session.json

**Comment by Xefise** [comment]
[session.zip](https://github.com/alvr-org/ALVR/files/5943918/session.zip)

**Comment by zarik5** [comment]
@Xefise don't worry, I think I have everything I need to debug this. To see the fix you have to wait until the next release. I first need to fix the issues with the audio introduced with v14.2.0.

**Comment by zarik5** [comment]
Can you test ALVR v15.0.0 beta and check if this has been fixed?

**Comment by RickAndTired** [comment]
15.0.0 beta fixed this issue for me. Sometimes it starts off rotated for a second, but it quickly fixes
