### ISSUE TITLE
Steam VR does not restart by ALVR

### ISSUE THREAD

**Issue by Xefise** [alvr-org/ALVR#483]
### Bug reports:

Steam VR does not restart by ALVR. The problem exists since version 13.0. My friend has the same problem.

Probably it does not restart because Steam VR does not have time to close.

#### Environement

What hardware do you have: Oculus Quest 1, Ryzen 1600 (OC to 3.4GHz), GTX 1080, RAM: 16GB, 2666 MHz, SSD NVMe PCI-E x2
My friend has: MD FX(tm)-8320 Eight-Core Processor 3.50 GHz, GTX 960, RAM: 20 GB
What version of ALVR and SteamVR have you tried: v13-14
Our Windows 10 versions numbers: 1903, 20h2

**Comment by zarik5** [comment]
Did you use the "Restart SteamVR" button? SteamVR cannot be restarted from the menu on the HUD

**Comment by Xefise** [comment]
@zarik5 Yes. (May be I mistranslated the second sentence but I do not understand what HUD did you say.) 

https://youtu.be/efE4Hg6WsR4 (I am sorry for russian interface)
I closed SteamVR in the video but it does not make sence, it does not start SteamVR even it was not closed.

**Comment by zarik5** [comment]
From the video I see that you are doing the correct steps but SteamVR is not starting. I don't know why that isn't working. We have already so many problems with SteamVR and i'm not sure where to start, since I already tried so many things.

**Comment by Xefise** [comment]
@zarik5 at new version the problem has solved but.. It works VERY strange xD
https://youtu.be/5Y2HcnyANBk

**Comment by zarik5** [comment]
The "Restart SteamVR" button is mostly useless. To apply settings you should put the headset to sleep and wake it again with the power button. This way SteamVR is restarted only once.
