### ISSUE TITLE
Add/move some buttons in the dashboard

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#486]
* Move the "Restart SteamVR" button into the sidebar.
* In the Settings tab footer, add "Export settings" button which just takes the session JSON, removes all top level elements except for "sessionSettings", then submits the file to a save file dialog.
* In the Settings tab footer, add "Reset all settings" button. This needs additional functionality in the web server.

**Comment by ronthecookie** [comment]
Merged into #674.
