### ISSUE TITLE
Unable to start audio capture

### ISSUE THREAD

**Issue by sem8588** [alvr-org/ALVR#505]
Hello, whenever I try and use ALVR, I'm unable to start audio capture as soon as the headset connects. I get the error: 21:53:29.872108200 [ERROR] Failed to start audio capture. Could not find a device id {0.0.0.00000000}.{22ad4ca4-3ac1-4632-81c5-007b0837c8f9}. hr = 0x80070490

I have a Ryzen 7 2700X, and a GTX 1060 6GB

**Comment by JosNun** [comment]
For future reference, this is covered in the troubleshooting guide [here](https://github.com/alvr-org/ALVR/wiki/Troubleshooting#failed-to-start-audio-capture).
