### ISSUE TITLE
ALVR attempting to use HEVC encoding when H264 is selected

### ISSUE THREAD

**Issue by davwheat** [alvr-org/ALVR#507]
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

When starting ALVR, it attempts to use H265 instead of H264, even when H264 is explicitly stated in the config.

![](https://u.davwheat.dev/q9koMX.png)

**session.json**
```jsonc
      "adapterIndex": 0,
      "renderResolution": {
        "scale": 1.25,
        "absolute": {
          "width": 2880,
          "height": 1600
        },
        "variant": "scale"
      },
      "recommendedTargetResolution": {
        "scale": 1.25,
        "absolute": {
          "width": 2880,
          "height": 1600
        },
        "variant": "scale"
      },
      "preferredFps": 90.0,
      "codec": {
        "variant": "H264" // <---
      },
```

#### Environment

What hardware do you have: 
i5 9600K
GTX 970

ALVR Version: 15.0.0
SteamVR version: 1.16.8

**Comment by zarik5** [comment]
The error message is wrong.

**Comment by davwheat** [comment]
Ah, right, thanks.

Maybe these issues could be caught and, instead of crashing the entire server, boot into a "safe mode" and allow users to modify the server settings instead of manually through the JSON.

Is there a record of where I can find what the highest combo allowed is?

**Comment by zarik5** [comment]
It takes time to develop safe mode. It would be easier to just rewrite the encoder implementation, but that also takes time.

There is no tool for finding the best settings for your setup. I plan to introduce some automatic tuning but that has to be done setting by setting (I will first start with audio buffering, then video frame timing, then bitrate).
