### ISSUE TITLE
ALVR changes the default playback device on launch

### ISSUE THREAD

**Issue by alterNERDtive** [alvr-org/ALVR#509]
When I start ALVR, it overrides the default playback device and sets a new one.

If I setup mic streaming from the headset to the PC it will set the Output Device configured there.

If I do not setup mic streaming it will set the Game Audio device.

It should _not_ fiddle with default device settings _at all_.

**Comment by zarik5** [comment]
ALVR should not change the default audio device. It doesn't have even the code to do that. But ALVR IS changing the device that SteamVR uses to output audio. So maybe it's SteamVR that is changing the system default device.

**Comment by alterNERDtive** [comment]
14.2 most definitely didn’t do that. I’m going to check my SteamVR settings, but it would be great if the entire “ALVR sets SteamVR devices” would be optional.

**Comment by alterNERDtive** [comment]
So, 2 findings:

1. I had SteamVR’s audio settings on “Headset”. No idea if that was recently changed, I definitely never went into the Audio settings and changed anything myself. Putting it on “manual” seems to have solved this particular issue.
2. Funnily enough, ALVR only sets the device once the headset connects, not when ALVR starts. No idea if that’s relevant, just something I noticed.

My personal problem is solved now though, so feel free to close unless you want to make changes to the process.

**Comment by zarik5** [comment]
For the second point, this is how it is supposes to work. I did it this way to simplify the code.

I'll keep the issue open if someone wants to add his experience. It till be closed automatically in a month.

**Comment by alterNERDtive** [comment]
Oh btw, this

> If I setup mic streaming from the headset to the PC it will set the Output Device configured there.

Is probably a bug, no? Or I’m misunderstanding how this entire thing is supposed to work. But setting the input of the cable used for mic streaming as the default output device system-wide seems to not be the thing you want to do there.

**Comment by zarik5** [comment]
Yes, but the but is not at ALVR level. It's probably a bug of SteamVR.

**Comment by A3yuu** [comment]
me to
I also encountered a similar spec when updating from v14 to v15.
Looking at the release notes, I see the following, which is probably working.
It was cured by returning to v14.

Automatic SteamVR audio configuration (by @zarik5)
This works only if input and output audio device is set to "Headset" in SteamVR settings

https://github.com/alvr-org/ALVR/releases/tag/v15.0.0

**Comment by A3yuu** [comment]
Right-click on the SteamVR icon and click "設定"
It was also cured by setting "オーディオ出力デバイス" and "オーディオ入力デバイス" on the "オーディオ" tab of SteamVR settings to "システムデフォルト". 
(I don't know the English original text, so I will write it in Japanese.)

**Comment by alterNERDtive** [comment]
I _suspect_ that ALVR 15 sets SteamVR audio settings to “Headset” on initial config, which then causes SteamVR to mess with system audio settings every time it detects said “Headset”.
