### ISSUE TITLE
Better support wired usecase / port forwarding

### ISSUE THREAD

**Issue by Drakulix** [alvr-org/ALVR#517]
This is more a feature request then a bug report and I am interested in implementing it myself,
but I wanted to check in with you at first, if this feature would be wanted and which approach seems to be the most feasible.

To explain my use-case, I need to explain my current setup:

I am using a Quest 1 almost exclusively for PC VR. I am playing a lot of Beat Saber and for latency reasons, I was using Oculus Link. (I am playing via PC for easier/better mod support.)  However the connection crashes frequently and can only be fixed by a complete headset restart. With the latest Quest System Update the experience got a lot worse, because now I am suffering frequent micro-stutters while playing (just perfect for a rhythm game)... So I was looking for alternatives. Preferably something I can control, debug and fix myself and stumbled upon ALVR.

Since I want the best possible and stable latency I wanted to use ALVR through a wired connection. However the Quest is not accepting any connected USB-Ethernet Adapters, so I am currently using a USB connection to my PC and ADB to do port forwarding. The good news is: it works. But I have stumbled upon some issues, because this use case was probably never tested.

#### Bug Report

1. Assuming I have already forwarded ports 9943 and 9944 via ADB the connection fails.
2. Connections on the control-port succeed, but as soon as the stream is supposed to start the quest reports a timeout and the PC logs "client disconnected", then the whole process starts again.

I have tried to figure out what happens by reading the code and starring at wireshark for a bit. The best explanation I can come up with is, that the current stream_socket connection setup is racy:
1. The [client sends the StartStream package](https://github.com/alvr-org/ALVR/blob/master/alvr/server/src/connection.rs#L388) and
2. [immediately tries to connect to the stream socket](https://github.com/alvr-org/ALVR/blob/master/alvr/server/src/connection.rs#L394)
3. This succeeds as ADB is listening locally on the socket.
4. ADB tries to open the connection on the quest itself, where the socket is not yet established and gives up, closing the socket on the host side.
5. The Quest starts listening on 9944 and eventually times out.

To fix this, I can establish the port forwarding just when the quest shows "Stream should start shortly".
If the timing is right, the streams starts immediately and is rock solid compared to Oculus link.
I have created a little batch-script to automate this process and currently my best bet is to wait around 3 seconds after starting ALVR to establish the port forwarding with a success rate of about 33%. Of course the whole process breaks when SteamVR needs to be restarted or anything takes slightly longer then usual, so it is far from perfect.

#### Suggested Fixes

1. Add a pre-connect script.
   - This is the most lazy workaround I could come up with.
   - An additional script that would be called after "StartStream" is send, but before the connection was established, would allow me to inject the port forwarding at just the right moment.
2. Do not fail when the first connection on the stream socket does not succeed:
   - Increase the client side timeout to 10 seconds, lower the timeout on the server side to 3 seconds and do two retries.
   - Still rather lazy, but probably enough to fix the issue
3. Ack the StartStream package before trying to connect on the server side.
   - A proper fix: We introduce a new packet, that is send after the client starts listening to signal the server, that it may try connecting now.
4. Support USB-connections in general through the Android Open Accessory Protocol
   - This would likely require a good chunk of refactoring to re-use code from the network layer.
   - But if there is interest in this approach, I would maybe give it a shot to implement a proper USB protocol for ALVR.
   - This should be achievable with something like WinUSB/libUSBk.
   - This would also remove the need for an active WiFi connection on the Quest as ALVR seems to be unable to listen on localhost only.

I would like to implement solution 3 and if there is enough interest give solution 4 a try.
I have worked on a good amount of rust-projects in the past and feel confident in implementing the proposed changes.
Is this something that would be accepted as a pull request?

"Oculus Link"-like functionality was obviously never an intended use case for ALVR, but is very easily achievable via ADB. It would be nice, if this could be considered a supported - albeit niche - use case. Or at least something that is not tested, but should work in theory and for which fixes (like the ones I am proposing) are accepted.

#### Environment

What hardware do you have: Ryzen 5 3600, RTX 3060 Ti, Oculus Quest 1
What version of ALVR and SteamVR have you tried: Newest stable
Do you have the latest Windows updates? yes, just installed all optional updates as well

Given the recent developments of Oculus and the latest system update, I am very happy that this open source software exists and makes it possible to use my headset without the Oculus software stack. ALVR will likely prevent this device of becoming an out-dated brick in the near feature. Also cudos for working on linux supprt! :)

Thank you for your time.

**Comment by zarik5** [comment]
I would be glad to accept a PR on this. Always happy to see a fellow Rustacean interested in ALVR 🙂

Sorry for my ignorance in the matter, most of my knowledge of network sockets comes just from working with ALVR. I don't understand how ADB could bind to the socket opened by ALVR server. The steam socket on the server server tries to connect to the specific IP and port of the client. Also the steam socket on the client listens for connections and rejects any that doesn't come from the specified IP and port of the server.

**Comment by Drakulix** [comment]
> I would be glad to accept a PR on this. Always happy to see a fellow Rustacean interested in ALVR slightly_smiling_face
> 
:+1:
Glad to hear that. From what I have gathered, the client/server are exchanging version information, right? So this could likely be implemented in a backwards-compatible fashion, where the server would only be waiting for the ACK packet, if the client is at least version x.y. Can you give me some pointers, where I need to change that version information in the source code?

> Sorry for my ignorance in the matter, most of my knowledge of network sockets comes just from working with ALVR. I don't understand how ADB could bind to the socket opened by ALVR server. The steam socket on the server server tries to connect to the specific IP and port of the client. Also the steam socket on the client listens for connections and rejects any that doesn't come from the specified IP and port of the server.
> 

Because both sides of the usb-connection are establishing local connections, so the IP is 127.0.0.1 in all cases.
ADB listening on the host side is running on the same machine, that is streaming, so I manually added the headset with "127.0.0.1" as the IP. The adb-daemon on the quest establishes the connecting to a locally running program, so it also uses "127.0.0.1". As a result the IP check passes. ADB does not establish a new network adapter, it rather functions as a proxy for given tcp-ports.

> Also I wonder, could the lack of an ACK packet for StartStream be a problem for a normal wireless connection? I thought TCP would send that automatically. I'm seeing a lot of people on Discord having problems with the stream socket connection failing and I wonder those are correlated with this.

It could theoretically. If the connection request for the stream socket reaches the headset before the StartStream packet is fully processed and the listening socket is created, the headset should drop the incoming connection and timeout as a result. However it would be pretty weird, if that would happen constantly on a given network. I would expect the connection would be established eventually, when the ordering randomly matches.

TCP does indeed ACK the StartStream package to make sure it is received by the client eventually, but the server-side code is not waiting explicitly for that ACK (there is no api to do that, I think, maybe "flushing" could have that effect). In fact it would be pretty bad, if every send-operation would be blocking the application until the corresponding packet was delivered. TCP does establish correct packet ordering and transmission for a single connection (if the stack is unable to uphold these guarantees, the connection fails), but since ALVR is establishing a second communication channel through another TCP/UDP connection there is no synchronization or ordering taking place. ALVR needs to do that manually, if we want to synchronize two unrelated (from the systems point of view) network connections.

**Comment by zarik5** [comment]
> So this could likely be implemented in a backwards-compatible fashion, where the server would only be waiting for the ACK packet, if the client is at least version x.y.

Oh yeah, this would be great, so we don't have to bump the major version. We'll simplify this for v16. (Actually, respecting semver compatibility rules for a end product is completely unnecessary, but I do that just so people don't have to upgrade both server and client apps if they don't want to).
You don't have to bump the version manually, CI takes care of that. You can use the constant `alvr_common::data::ALVR_VERSION` to add the ACK check conditionally. It's a `semver::Version` instance so you can use comparison operators.

> Because both sides of the usb-connection are establishing local connections, so the IP is 127.0.0.1 in all cases.

Maybe we should use different ports for server and client. We can add the option on the server (the setting will be transferred to the client through the control_socket first). We can keep 9944 as default for both peers for v15, then we'll change that for v16.

> TCP does indeed ACK the StartStream package to make sure it is received by the client eventually, but the server-side code is not waiting explicitly for that ACK (there is no api to do that, I think, maybe "flushing" could have that effect). In fact it would be pretty bad, if every send-operation would be blocking the application until the corresponding packet was delivered. TCP does establish correct packet ordering and transmission for a single connection (if the stack is unable to uphold these guarantees, the connection fails), but since ALVR is establishing a second communication channel through another TCP/UDP connection there is no synchronization or ordering taking place. ALVR needs to do that manually, if we want to synchronize two unrelated (from the systems point of view) network connections.

Thank you for the insightful explanation. So what we should do is: the client receives the StreamStart packet, it starts listening on the stream socket, right after it sends the explicit ACK to the server and at that point the server can attempt the connection to the stream socket.

So in the end, what do you think of the current code? Even after these changes, is there something we can do to streamline the connection process, or just to refactor the current code to be more clear?

Anyway if you didn't you can read [this document](https://github.com/alvr-org/ALVR/wiki/How-ALVR-works) where I explain (among other things) the connection process, although you seem to already have a good understanding.

**Comment by Drakulix** [comment]
> > Because both sides of the usb-connection are establishing local connections, so the IP is 127.0.0.1 in all cases.
> 
> Maybe we should use different ports for server and client. We can add the option on the server (the setting will be transferred to the client through the control_socket first). We can keep 9944 as default for both peers for v15, then we'll change that for v16.

I think I am not getting the point here. What would the benefit of using a different port then 9944 here be? The port the server uses to connect to the client needs to match and said port can already be configured in the settings?

I was indeed a little confused by the port choices at first, but that was because it took me some time to realize, that 9943 is used two times. Once for the discovery process via UDP and once for the TCP control_socket (which is not a problem at all, as they are separate protocols). But the stream is just using TCP (or UDP) over 9944.

Also was has that to do with the usb-connection?
ADB on the host is listening on 9944 and the server connects locally to that port. On the quest the android app is listening on 9944 and the adb client is connecting to that port. There is no way to have independent ports on either side here without messing up normal network connections (which cannot have different ports, as that is the common identifier).


> Thank you for the insightful explanation. So what we should do is: the client receives the StreamStart packet, it starts listening on the stream socket, right after it sends the explicit ACK to the server and at that point the server can attempt the connection to the stream socket.

Exactly. I should have a PR up for that over the weekend, but I want to take the time to test this properly and likely need to setup a development environment on windows at first.


> So in the end, what do you think of the current code? Even after these changes, is there something we can do to streamline the connection process, or just to refactor the current code to be more clear?

I found reading the code a little confusing. because I had to jump around a lot between different source files. I think having a common crate is really helpful, but I do not get, why a lot of server- and client-specific logic is in there. I think either most of all code should be in the common crate or there should be a clear separation between client-, server- and truly common responsibilities and I would favor the later.

Another thing I noticed (but that is mostly personal preference) is that there are a lot of wildcard imports. Frequently I was searching for the definition of a called function, but it was impossible to know from looking at the imports, because there were multiple wildcard-imports. I could also not pin point a single logical location, because every time there were at least two possible crates (client/common or server/common). Mostly I just used `grep` on the whole code base, which gets the job done but feels unnecessarily cumbersome to find a single function definition.
I would prefer importing either the functions by name or importing the containing module and calling functions via the module name. That way I could easily trace the imports.

That said the overall code looks absolutely fine. I have not worked on a lot of async/tokio-style code before, so I might have missed something there nor have I looked at everything (especially not at the actual capture->streaming code). I wanted to find out if port forwarding could work with ALVR and I am quite happy, that this took me just a single evening to figure it out. Which in and of itself is a statement on the quality of the code.

> Anyway if you didn't you can read [this document](https://github.com/alvr-org/ALVR/wiki/How-ALVR-works) where I explain (among other things) the connection process, although you seem to already have a good understanding.

Yeah I had found this document and it helped me a lot in the beginning. I was trying to figure out, if I had to emulate the discovery process somehow and was pleased to see, that I can just skip it as the android-app is listening on the TCP port already. However it gets a little fuzzy when it comes to explaining the switch to the stream socket, which is why I choose to setup wireshark in the end to take a look myself. I might add some explanation, if you are okay with that.

**Comment by zarik5** [comment]
> There is no way to have independent ports on either side here without messing up normal network connections (which cannot have different ports, as that is the common identifier).

AFAIK you can use different ports between peers in the same TCP connection, but now I realize it wouldn't help here.

> I found reading the code a little confusing. because I had to jump around a lot between different source files. I think having a common crate is really helpful, but I do not get, why a lot of server- and client-specific logic is in there. I think either most of all code should be in the common crate or there should be a clear separation between client-, server- and truly common responsibilities and I would favor the later.

I agree. ControlSocket (at least the creation part) should be split and moved into server and client crates. In particular I would like to remove the need for the temporary PendingSocket object. StreamSocket also has some client/server specific code but IMO it's not worth splitting the definition.

> Another thing I noticed (but that is mostly personal preference) is that there are a lot of wildcard imports. Frequently I was searching for the definition of a called function, but it was impossible to know from looking at the imports, because there were multiple wildcard-imports. I could also not pin point a single logical location, because every time there were at least two possible crates (client/common or server/common). Mostly I just used grep on the whole code base, which gets the job done but feels unnecessarily cumbersome to find a single function definition.
I would prefer importing either the functions by name or importing the containing module and calling functions via the module name. That way I could easily trace the imports.

Personally I rely on the "go to definition" and inlay hints provided by vscode and the the extension rust-analyzer. But I agree that removing wildcards help people read code when those tools are not available, like on the GitHub website.

> That said the overall code looks absolutely fine. I have not worked on a lot of async/tokio-style code before, so I might have missed something there nor have I looked at everything (especially not at the actual capture->streaming code). I wanted to find out if port forwarding could work with ALVR and I am quite happy, that this took me just a single evening to figure it out. Which in and of itself is a statement on the quality of the code.

Thank you 🙂

> Yeah I had found this document and it helped me a lot in the beginning. I was trying to figure out, if I had to emulate the discovery process somehow and was pleased to see, that I can just skip it as the android-app is listening on the TCP port already. However it gets a little fuzzy when it comes to explaining the switch to the stream socket, which is why I choose to setup wireshark in the end to take a look myself. I might add some explanation, if you are okay with that.

You're welcome to contribute to the wiki! I wrote that document top down all in one go, I didn't spent too much time on it, especially since I know that the code would still evolve quickly.

**Comment by Drakulix** [comment]
> > There is no way to have independent ports on either side here without messing up normal network connections (which cannot have different ports, as that is the common identifier).
> 
> AFAIK you can use different ports between peers in the same TCP connection, but now I realize it wouldn't help here.

Well yes, the port we have been talking about is the port of the incoming connection. The port that is used to listen for connections and that is specified when sending the connection request. Of course we could also set the outgoing port, but outside of some special cases like hole-punching, there is no benefit from doing so. The default is, that the system chooses a random free port, which is why I choose to ignore this detail in my explanation. ALVR does not need to know about the outgoing port, setting it just opens the door for more conflicts.

> I agree. ControlSocket (at least the creation part) should be split and moved into server and client crates. In particular I would like to remove the need for the temporary PendingSocket object. StreamSocket also has some client/server specific code but IMO it's not worth splitting the definition.

I agree on the StreamSocket, it is mostly the ControlSocket / connection setup, that was annoying to deal with.

> Personally I rely on the "go to definition" and inlay hints provided by vscode and the the extension rust-analyzer. But I agree that removing wildcards help people read code when those tools are not available, like on the GitHub website.

I absolutely get that, but not every IDE has the tooling rust-analyzer provides nor did I want to clone the project to take a look at the source code at the time.

> You're welcome to contribute to the wiki! I wrote that document top down all in one go, I didn't spent too much time on it, especially since I know that the code would still evolve quickly.
> 
> Once I merged your PR i'll work on the refactoring following your suggestions.

:+1:
