### ISSUE TITLE
Cannot choose English language.

### ISSUE THREAD

**Issue by Xefise** [alvr-org/ALVR#525]
My system language is Russian. I wanted change ALVR language to English but there is not English language in the language selector.

ALVR version: 15.0.0

![image](https://user-images.githubusercontent.com/45072628/110216073-28e64e00-7ebe-11eb-88d9-6c6908399b3c.png)

**Comment by Ekristoffe** [comment]
Hello should be solved when #527 is merged and published.
thanks for the report.
