### ISSUE TITLE
[ERROR] No device found with specified name

### ISSUE THREAD

**Issue by 5236987410** [alvr-org/ALVR#540]
Wanted to connect my Quest 2 with my Windows 7 PC. But it keeps showing error "No device found with specified name" a few from the ALVR dashboard (v 15.1.0), and followed by a appcrash of vrserver.exe.
From the headset ALVR side, it also shows "The server has disconnected" multiple times.
May I know what is the issue and how can I solve this? Thanks!

**Comment by zarik5** [comment]
Windows 7 support has been dropped since ALVR v12. You need Windows 8 or greater.
