### ISSUE TITLE
Running Virtual Desktop appears to fix multiple network issues related and unrelated to ALVR

### ISSUE THREAD

**Issue by BinaryBreaker** [alvr-org/ALVR#548]
### Bug reports:

For a few months now, everytime I've tried ALVR I have had network issues, particularly what will happen is, I will install ALVR on my PC and on my Quest 2 **properly** and everything will work up to the part where I must connect my headset to my PC. The headset *will* appear on the new clients list, but trusting it does not cause it to connect; the headset gets stuck at Searching for Server and ALVR never switches to the performance tab. During some troubleshooting I noticed that the headset could not be pinged.

About a week ago I caved and bought VD and found that VD worked fine, but after a few days I decided to try ALVR again only to find that ALVR suddenly worked properly. However, the next day, I tried using ALVR without trying VD first and found myself with the same issue as listed above. After about an hour of troubleshooting I decided to try VD to see if that worked, VD still worked, after I exited VD I entered ALVR again I found that it suddenly worked again.

I decided to see if VD was solution, I powered off my headset and closed everything related to sidequest, ALVR, and VD on my PC. After an hour, I tried again only to find myself with the same issue. I made sure ALVR didn't work and that I couldn't ping my headset. This time, all I did as a troubleshooting measure was to connect to my PC using VD then, once I had a working connection, disconnect then exit VD. This seemed to fix the issue with ALVR and allowed my headset to be pinged. (Just opening VD was not enough, I had to connect to my PC)

#### Environement
I am using a Ryzen 2700X, 1660 Ti, Virtual Cable is installed

This has been a problem since I first tried ALVR with 14.X, but these issues were tested with ALVR 15.1 and SteamVR 1.16.10

I am running the latest version of Windows
Version 20H2 (Build 19042.867)

and if it wasn't already obvious, I am using an Oculus Quest 2

#### Troubleshooting I already tried

I have already tried these troubleshooting measures

rebooting my Quest 2
connecting my headset to sidequest
attempting to start an ADB server on my quest (it didn't work)
reinstalling ALVR on both my PC and my Quest
Changing network type from Public to Private
Changing the IP on the quest to a static one

I also installed Termux (a terminal emulator and linux environment) onto my Quest 2 so I could use tools such as ifconfig. I found that I could ping the local IP my headset was using from within Termux. As a test I decided to install nginx from within termux to see if it was possible that ALVR was just having issues  (I've done the same thing on a chromebook and found that Termux does have network access and allowed nginx to work and be connected to externally). I could not access port 80 and thus the nginx website internally on my quest in termux and externally on my PC. I ran an nmap scan on my Quest only to find that the IP was listed as down.

**Comment by BinaryBreaker** [comment]
After some more messing around, it appears that just waiting around for a while will cause the network issues to disappear, but connecting to a PC via VD still fixes the issue without having to wait.

**Comment by zarik5** [comment]
Can you try some older versions of ALVR? Just to have some more data points to diagnose the problem.

**Comment by BinaryBreaker** [comment]
> 
> 
> Can you try some older versions of ALVR? Just to have some more data points to diagnose the problem.

The issue with ALVR not working has been an issue for me since 14.X, But sure, I'll try this again on, 15.1.0 (control group), 14.1.1 , 13.5.0, 13.0.0, and 12.5.0

**Comment by hpenney2** [comment]
I'm having this same issue on my Quest 1 (can't test if VD fixes it since I don't have it though), however starting an ADB wireless connection via SideQuest seems to fix the connection issues and allows the video stream to start successfully. Running ALVR 15.1.0.

**Comment by BinaryBreaker** [comment]
> 
> 
> I'm having this same issue on my Quest 1 (can't test if VD fixes it since I don't have it though), however starting an ADB wireless connection via SideQuest seems to fix the connection issues and allows the video stream to start successfully. Running ALVR 15.1.0.

In my case, the Quest can't even be pinged and _adb tcpip 5000_ doesn't do anything. But I never tried using SideQuest to start the adb server because, to me, SideQuest is just an adb client for people who don't want to use a command line

**Comment by hpenney2** [comment]
> SideQuest is just an adb client for people who don't want to use a command line

Pretty much >>
For some reason, I do have to put my Quest into sleep mode before starting the server (I think it's something related to Oculus Link stuff?), but after that I can unplug it and it works fine as long as it stays connected.

> In my case, the Quest can't even be pinged

Same thing here, I haven't checked after running the ADB server though (I'd assume that works fine since I can use ALVR).

**Comment by BinaryBreaker** [comment]
> 
> 
> Can you try some older versions of ALVR? Just to have some more data points to diagnose the problem.

I attempted to try some older versions.
- [ ] 15.1.0 (control group)
- [ ] 14.1.1

(lack of a checked box = not working)

I experienced an issue when downgrading to 13.5.0, the portable server would not launch the 13.5.0 version but rather, the 14.1.1 version causing me to be unable to test 13.5 and lower. (No configuration files were written to the directory where 13.5.0's server was stored)

A quick side note:
I noticed that Virtual Desktop's drivers were automatically being registered and listed in ALVR, removing them did not fix the issue.

I would test more but what I have found is just waiting around will eventually fix the network issues and after about 20 minutes of testing the issues fixed themselves, not exactly a permanent solution for someone like me who only uses their Quest for PC VR and leaves it completely shutdown when not in use.

**Comment by hpenney2** [comment]
After no changes (to my knowledge), I suddenly have no connection issues and can run ALVR without starting an ADB server. Not sure what's up with this...

**Comment by BinaryBreaker** [comment]
> 
> 
> After no changes (to my knowledge), I suddenly have no connection issues and can run ALVR without starting an ADB server, even after a restart. Not sure what's up with this...

Do you happen to know if there was a firmware update?

**Comment by hpenney2** [comment]
It doesn't appear so, my Quest is still on v25, the same as it was previously.

**Comment by BinaryBreaker** [comment]
> 
> 
> It doesn't appear so, my Quest is still on v25, the same as it was previously.

huh, weird

This whole issue feels like an issue with the Quest and not ALVR and with this level of unpredictability is this issue even worth keeping open.

**Comment by MrKinauJr** [comment]
Just for more data points, what Router do you have?

**Comment by BinaryBreaker** [comment]
> 
> 
> Just for more data points, what Router do you have?

I may be unable to find this, but what I can say is that this has never been issue with any other device on my network. Everything from garbage running on my raspberry pi to homebrew FTP servers that run on my Wii

**Comment by MrKinauJr** [comment]
Same actually but sometimes if i for example choose UDP instead of TCP my whole Networks crashes.

**Comment by maurixyz** [comment]
Hi, I have the same problem the ALVR client remaning in searching status for very long maybe more that 15min and only after taht time it starts to stream the steamvr home ecc. Is there a way to make ALVR work as soon as i conect the headset, a way different than connect sidequest by wifi? I also have the problem that while using ALVR the quest drop the connections and I have to restart the router  to be albe to reconnect the quest to the wifi, because if I try to connect without restarting the router the quest don't reconnect (While the other device connected to the router continue to work with the wifi).  Thanks in advance to everybody will help me with those problems.

**Comment by BinaryBreaker** [comment]
When a USB connection using port forwarding is used, everything works fine without the need for this wait period for the network to start working

**Comment by BinaryBreaker** [comment]
Ok, using the hotspot feature under Windows allows me to use ALVR wireless just fine, I hesitate to close this issue though as VD was able to fix this issue under my normal network. But for now, I would recommend checking your network configuration to make sure there isn't a weird security measure that prevents the Oculus Quest 2 from interacting with other devices.
