### ISSUE TITLE
"Genuine Adobe Service" By "Adobe" was Installed and didn't even look convincing...

### ISSUE THREAD

**Issue by dummyacc5445** [alvr-org/ALVR#550]
You might be thinking well... where's the proof it was ALVR that installed this Genuine Adobe Service. In short I immediately uninstalled it and ended all tasks not related to Window's core, so I don't have any photos or videos of this unknown app, but let's just say this' the only app I've downloaded in months besides the Oculus Link app... and I'm very paranoid about what runs on my pc, so all my main apps have been downloaded via official links, with valid certificates, and secure https only sites. Except ALVR.

**Comment by hpenney2** [comment]
If you have any Adobe apps, you'll have the "Genuine Adobe Service" from my recollection (at least if you've been pirating it, which is what it's meant to stop :eyes:). This isn't an ALVR issue.

**Comment by xxValiumxx** [comment]
The funny thing about Open Source software possibly containing malware, or drive-by installs of unwanted software, is that the code is visible.

This is a non-issue as far as ALVR goes.
