### ISSUE TITLE
Rock N Roll to Middlefinger problem in Valve Index emulation with Oculus Quest Controller

### ISSUE THREAD

**Issue by togacat** [alvr-org/ALVR#551]
Hi all,

I'm really enjoyed about ALVR index controller emulation with Oculus Quest finger tracking. It's almost working in VRChat and makes communication rich. It is also useful that I can change both finger-tracking mode and Oculus Quest controller mode. 
But I've one problem for the emulation in Oculus Quest controller mode.

Originally, Oculus Quest controller makes Rock N Roll Hand Sign when pushing right and left triggers. But when ALVR emulates vive index controller with Oculus controller, it produces middle finger hand sign instead of RockNRoll. This is just a specification and may not be a bug. But in VRChat, Rock N Roll hand sign is usually used as animation override for positive expression like smile. So, this specification causes lot of problem for communication. When I want to make greeting to someone, I often misuse middle finger gesture for them. I really want to change the emulation in ALVR, but there is no option.

Is it possible to change default emulation of Oculus Quest emulation from middlefinger to Rock N Roll, or is it possible to include customize mode for ALVR?

**Comment by xxValiumxx** [comment]
rock n roll, at least in VRChat, is thumb resting on the top buttons/stick, and pulling the trigger, not touching grip at all. you may want to check the specific avatar you're using to make sure that this is indeed an ALVR issue; many avatars actually have the middle finger gesture in place of the rock n roll.

**Comment by togacat** [comment]
>rock n roll, at least in VRChat, is thumb resting on the top buttons/stick, and pulling the trigger, not touching grip at all. 
Right. And, all of my VRC avatar properly produce Rock N Roll by above command in ALVR with Oculus Quest 2 Controller emulation. However, it produces middlefinger gesture in ALVR with Valve Index controller emulation (Actually, it produces weak middlefinger gesture with bending index finger half if I touch the trigger, and produces perfect middlefinger gesture with pulling the trigger). So I think it is not my avatar problem at least.

Also, other users find same problem for using ALVR. So I think it is not just my environment.
https://twitter.com/VRkaho/status/1366405849199955969
> Using the valve index controller in ALVR would make rock 'n' roll as fuxx you.
> Where did you control the fingers that bend with the buttons?

https://twitter.com/yuzu_hik0/status/1320008983902445568
> Thanks to this blog, I can now use VRChat for PC on Quest 2!!
> Comes with a free gift that can hold the middle finger up!!!!
> I don't need to care about the delay.
> I wonder if the reason why RocknRoll can't do it is because of the my environment?
