### ISSUE TITLE
The Room VR

### ISSUE THREAD

**Issue by jirian** [alvr-org/ALVR#552]
### Bug reports:

Hi,
I have trouble running The Room VR. When starting the game from an .exe file, the game for some reason doesn't bind into Steam VR. Steam doesn't register the game at all and stays in SteamVR home.
The game itself shows just black screen on the PC, but I can hear its music in the headset.
Any idea what's wrong?

#### Environement

SteamVR 1.16.10
ALVR server v15.1.0
Windows 20H2 build 19042.867

**Comment by MrKinauJr** [comment]
As long as Steam does not pick up the Game, it won't stream it to the Headset. Kinda sounds like a Gamebug rather then a ALVR bug. Try starting it from SteamVR directly.

**Comment by jirian** [comment]
So it apparently is a Oculus-only game. Revive works. Thanks.
