### ISSUE TITLE
Driver4vr

### ISSUE THREAD

**Issue by BulletinMatches** [alvr-org/ALVR#555]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki)  and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

I am trying to use driver4vr with alvr when I try running alvr driver4vr does not appear in the startup section. If I run steam vr manually driver4vr does show up and launches properly.

#### Environement

Ryzen 5 3600, Nvidia 2070s
Alvr 15.1.0, beta and non beta of steam vr
Version 2004

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by JosNun** [comment]
In order to use additional drivers with ALVR, you need to register the ALVR driver. Instructions at the bottom of the installation instructions. [See here.](https://github.com/alvr-org/ALVR/wiki/Installation#use-alvr-together-with-third-party-drivers)

**Comment by BulletinMatches** [comment]
> In order to use additional drivers with ALVR, you need to register the ALVR driver. Instructions at the bottom of the installation instructions. [See here.](https://github.com/alvr-org/ALVR/wiki/Installation#use-alvr-together-with-third-party-drivers)

Thanks for that
