### ISSUE TITLE
Parallels Desktop eGPU Issues

### ISSUE THREAD

**Issue by MisutaaUrufu** [alvr-org/ALVR#556]
#### Hardware
Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
16GB RAM (8GB assigned)
AMD Radeon RX570 4GB [eGPU] (Thunderbolt 3 PCIe)
Intel Iris Plus 640 [iGPU] (CPU)

#### Software
Windows 10 Enterprise 20H2
Parallels Desktop 16
Parallels Display Adapter (WDDM) (Direct X11)
Latest SteamVR Release as of 03/23/2021

## Issue

ALVR cannot start, throwing the `Failed to initialize CEncoder. All VideoEncoder are not available. VCE: AMF Error 1. g_AMFFactory.Init(), NVENC: NvEnc NvEncoderD3D11 failed. Code=1 NvEncoder::LoadNvEncApi : NVENC library file is not found. Please ensure NV driver is installed at c:\src\alvr\alvr_server\nvencoder.cpp:70` issue in the Wiki. The graphics card is reported as likely compatible by the wizard, however, during first time setup.

SteamVR on launch reports error 461, which according to SteamVR support, is related to an issue between the headset driver and the GPU, likely attributable to this error.

#### Details
As Windows is running alongside another OS, through Parallels, it does not have direct access to the GPU. As such, whilst it has access to DirectX11 and OpenGL, it cannot access hardware specific features, such as NVENC, CUDA, AMF, etc. This prevents applications from using hardware encoding for video; Software encoding is still provided, as Windows supports both HEVC & H264.

Parallels Desktop does support SteamVR, as well as DirectX 11 applications, [with significantly improved support for DirectX 11 over previous versions as of version 15](https://www.parallels.com/blogs/parallels-desktop-15-directx-11-and-metal/). However, the reliance on AMF/NVENC prevents Quest users from running ALVR and using Quest headsets with the system.

## Suggestion:
Add support for software based encoding between ALVR and the headset, to allow VR ready eGPU and VM configurations to connect with Quest devices wirelessly.

**Comment by JosNun** [comment]
There is work in progress to support using ffmpeg for encoding (mostly for linux support atm), which does have a software encoder for h265. So this _may_ be possible in the future. Unfortunately, I don't expect a software encoding implementation to perform well enough to be able to handle the resolution / framerate requirements of VR.

**Comment by zarik5** [comment]
I'm having the same error, running on Parallels Desktop. I don't think this is related to ALVR, unfortunately

**Comment by ScriptsYouTube** [comment]
switch to vmware fusion. parallels cant work with your gpu so you cant play vr games on parallels. or if you have some vr headset you can download steamvr beta version for macos
