### ISSUE TITLE
window not show after steamvr  started,15.1 and 15.0,need alt+space maxwindowsize to show up.

### ISSUE THREAD

**Issue by xzkeee** [alvr-org/ALVR#558]
only show up at alt+space
Click on the alvr icon can not open the alvr window

win10 20H2

**Comment by zarik5** [comment]
Do you have a dual monitor setup? Where is the secondary monitor located relative to the primary one?

**Comment by thegforcian** [comment]
I'm getting this in 15.1 as well.  Do not have a secondary monitor.  It also pins the Edge app to my taskbar every time I open it since I don't have Chrome installed rather than running through Firefox which is just super annoying.

**Comment by eximer168** [comment]
SOLUTION! 
Turn resolution down on the monitor below the recommended 3840x1260 to something smaller, 1900x1200.

Prior to this I had to use 14.1 to get window, or ALT-SPACE, ALT-M and then drag pane to get normal window.

**Comment by xzkeee** [comment]
> Do you have a dual monitor setup? Where is the secondary monitor located relative to the primary one?

I do have 2 monitor setup, but when I use alvr, only 1 monitor is running, it is in only pc screen mode.
Also, have a 300% UI scale, screen resolution is 5120x2880.

**Comment by zarik5** [comment]
Thanks guys, I found the bug, I didn't take into account the DPI. You can try the new nightly now.

**Comment by xzkeee** [comment]
> Thanks guys, I found the bug, I didn't take into account the DPI. You can try the new nightly now.

problem fixed, thank you!
