### ISSUE TITLE
After ALVR installation WMR don't work anymore with SteamVR

### ISSUE THREAD

**Issue by maurixyz** [alvr-org/ALVR#559]
Hi, after I installed ALVR and used it with my Oculus Quest and SteamVR now when I connect my WMR Lenovo Explorer to my pc, the WMR software start mormally and the headset and the controolers work fine in ther but when I lunch the WMR Steam biridge app from WMR, steamVR start but only looks for Oculus Quest and my WMR headset is not seen. Before the installation of ALVR my WMR Lenovo  Explorer was working fine using the bridge with SteamVR. Now I would like to know what I should do to make SteamVR to see again my WMR Lenovo Explorer. This is wath I can Read in my steamvr.vrsettings after I tride to use my WMR under the LastKnown
   "LastKnown" : {
      "HMDManufacturer" : "Oculus",
      "HMDModel" : "Miramar"
   },
I would like also to know if is it possible to have a setting that let me to use SteamVR sometimes with my WMR Lenovo Explorer and sometimes with ALVR and the Quest. My ALVR version is the last one, my W10 is Updated. Thanks in advance to everybody will helpme.

**Comment by JosNun** [comment]
Sounds like you may have registered the ALVR driver in SteamVR, which was only required in older versions, or if you need additional addons. You should be able to disable / remove the ALVR driver (you can disable it from within the steamVR settings, or remove it from the ALVR dashboard). If that doesn't fix it, hop into the [ALVR Discord server](https://discord.com/invite/ALVR), and we'd be happy to give you a hand.

**Comment by maurixyz** [comment]
Thanks, removing the alvr drivers did work.
