### ISSUE TITLE
I cannot start the ALVR

### ISSUE THREAD

**Issue by fecent** [alvr-org/ALVR#563]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

I cannot start the ALVR, white screen flashes when starting the software. I have installed chrome browser

#### Environement
win10 18363.1440
i7 6700HQ GTX1070

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by JosNun** [comment]
Hey, @fecent thanks for reporting an issue! Can you provide any more details about what's happening? Currently, we don't have enough info to help diagnose your issue. If you need a hand collecting details, join [our Discord server](https://discord.com/invite/alvr) and we'd be more than happy to help get you up and running!

**Comment by Pesoen** [comment]
same problem here, but crash_log is empty.. sometimes manage to get it working by repairing using the installer, and launching steamvr manually, but not always working..

the main window that shows it's loading(i think, cannot remember) shows up, pure white for about 5-6 seconds, before going away, sometimes i am lucky and i can start steamvr and alvr starts up with it, and works as expected, but it will no longer just keep the alvr window open when launching, and sometimes it fails entirely, at which point a repair works 2/10 times.. deleting session.json does not fix it, nor does it fix it to run as admin, or any compatibility setting..

i too use the chrome browser. doubt that is the issue, but a good note to include.

**Comment by fecent** [comment]
Yes, I have the same problem as Pesoen. Sometimes I have to start the software immediately after restarting the computer to run. And crash_log is empty

**Comment by fecent** [comment]
I have tried it on some computers, even if the software is opened immediately after restarting the computer, it will display pure white for about 5-6 seconds, and then automatically close the program.

**Comment by Pesoen** [comment]
just got it working, disable fullscreen optimization, and set compatibility mode to windows 8. currently working for me three times in a row.

not sure if both are needed, but i have both set.

**Comment by Pesoen** [comment]
and now after a system restart, it fails again..

**Comment by fecent** [comment]
@JosNun @Pesoen The problem seems to be solved. After installing the latest version 15.1.2, registering the ALVR driver to SteamVR, and launching SteamVR separately, the ALVR panel can be automatically opened, but it still cannot be started directly through the ALVR shortcut, and it still crashes.

**Comment by pepepper** [comment]
I'm experiencing crash at ALVR 15.1.2
I found if I launch ALVR Launcher.exe with WinDbg, it stops because of break instruction(int 3)
And I continue the debugger, ALVR launches successfully
![スクリーンショット 2021-04-10 234147](https://user-images.githubusercontent.com/35837918/114273785-73775f00-9a56-11eb-81fb-28308c63f32d.png)
 
I think someone left a breakpoint in releases...

**Comment by zarik5** [comment]
@pepepper The release binaries are compiled with optimizations turned on and no debug info. There can't be any breakpoints, we are not even using a debugger.

**Comment by pepepper** [comment]
@zarik5 I checked machine code of the launcher and I can't found INT 3 code. I'm sorry.
I'm going to research more. For now, I share this stacktrace.
![unknown](https://user-images.githubusercontent.com/35837918/114281735-0d510300-9a7b-11eb-934e-1437543f0750.png)

**Comment by ronthecookie** [comment]
@pepepper Can you also reproduce this crash if you compile ALVR with debug symbols? If you can then that could be more useful as currently we can't see what function triggers the crash.

**Comment by pepepper** [comment]
@ronthecookie Even debug build crashes
This file is stack trace
[message.txt](https://github.com/alvr-org/ALVR/files/6291345/message.txt)

This looks like IME related problem... Actually, if I disable IME, ALVR launches succsessfully.

**Comment by ronthecookie** [comment]
That's interesting. Maybe it's related to https://github.com/linebender/druid/issues/1652. If you run it in a terminal do you get anything on stderr?

**Comment by pepepper** [comment]
This file contains two logs. One is normal and another is with RUST_BACKTRACE=1
[message (1).txt](https://github.com/alvr-org/ALVR/files/6291439/message.1.txt)

**Comment by ronthecookie** [comment]
Okay so it seems it's crashing [here](https://github.com/linebender/druid/blob/v0.7.0/druid-shell/src/platform/windows/window.rs#L374). I don't know if there's any reason we're not on the latest druid version but maybe you could try updating druid to see if they fixed it, the version number is here: https://github.com/alvr-org/ALVR/blob/master/alvr/launcher/Cargo.toml#L10.

**Comment by ronthecookie** [comment]
Feel free to reopen this if you try to fix this.

**Comment by Jimi-James** [comment]
Can someone please tell me how to manually register the driver into SteamVR on Linux? I had it working one night, but now it's just the blank screen every single time. I want to see what happens if the driver is registered and I just launch SteamVR on its own and let it launch ALVR, except I can't do that because I need ALVR to not be blank in order to click its "Register driver" button.
