### ISSUE TITLE
Linux server build fails

### ISSUE THREAD

**Issue by AKDub** [alvr-org/ALVR#565]
Trying to build the server gives me the error below, following the method found here under linux experimental build - https://github.com/alvr-org/ALVR/wiki/Build-from-source

`error: build failed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr/xtask/src/main.rs:216:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

#### Environement

What hardware do you have: AMD Ryzen 3600, AMD 5500XT, Audio
PopOS 20.10

**Comment by zarik5** [comment]
I just pushed a commit to enable backtrace support in xtask, try again and post the new error. I actually never tried to build ALVR locally on Linux, but I setup CI for build checks. You can take a look at the workflow file to see if you are missing some steps https://github.com/alvr-org/ALVR/blob/master/.github/workflows/rust.yml#L75

**Comment by AKDub** [comment]
Seemed to build but with lots of warnings.

This was already a little out of my comfort zone so I think I will just wait for the proper linux release. Looking forward to it! (I have been following the chat in linux-dev on discord)

Feel free to close this.

**Comment by zarik5** [comment]
Warnings should not be a problem. They should be mostly about unused windows code

**Comment by AKDub** [comment]
Where will the actual executable that I should launch be?

**Comment by zarik5** [comment]
It should be `ALVR Launcher` in the directory `build/alvr_server_linux

**Comment by AKDub** [comment]
No ALVR Launcher

~/Downloads/ALVR/build/alvr_server_linux/bin
~/Downloads/ALVR/build/alvr_server_linux/presets
~/Downloads/ALVR/build/alvr_server_linux/driver.vrdrivermanifest

**Comment by zarik5** [comment]
Then the build failed.

**Comment by SuperKooks** [comment]
Getting the same issue after following the steps at [https://github.com/alvr-org/ALVR/wiki/Build-from-source#linux-experimental-build](https://github.com/alvr-org/ALVR/wiki/Build-from-source#linux-experimental-build). I assume there was no solution?

`cargo xtask build-server --release`
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Command failed: "', alvr/xtask/src/main.rs:214:10
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /build/rust/src/rustc-1.51.0-src/library/core/src/option.rs:1300:5
   3: core::result::Result<T,E>::unwrap
             at /build/rust/src/rustc-1.51.0-src/library/core/src/result.rs:1037:23
   4: alvr_xtask::build_server
             at ./alvr/xtask/src/main.rs:210:9
   5: alvr_xtask::main
             at ./alvr/xtask/src/main.rs:490:35
   6: core::ops::function::FnOnce::call_once
             at /build/rust/src/rustc-1.51.0-src/library/core/src/ops/function.rs:227:5`

**Comment by xytovl** [comment]
99% of the time it is because of ffmpeg (libavutil in fact) not compiled with vulkan support.

None of the Linux devs is using Ubuntu so we didn't check instructions on how to get the correct build of ffmpeg.

**Comment by SuperKooks** [comment]
Do you know how I would go about compiling ffmpeg / libavutil with vulkan support. I looked around online but didn't find much.

**Comment by ArthurCose** [comment]
There's a new `--bundle-ffmpeg` flag that takes care of that for you

**Comment by superkooks** [comment]
Cool! I'll it out again.

**Comment by superkooks** [comment]
Alright, I tried compiling the server again with the flag. Worked perfectly. However, when trying to use ALVR, it crashes SteamVR. I suspect it has something to do with this message from the ALVR dashboard:

`failed to create VAAPI encoder: Failed to create a VAAPI device: Input/output error`

I have installed libva. That is the only thing that I could think of.

**Comment by xytovl** [comment]
I will try to get rid of that message, if you have an nvidia card the message is expected and automatic fallback should happen.

Can you provide more details on the crash? Which process exactly (could be vrserver, vrcompositor)? Logs from ~/.steam/steam/logs/vr{server,compositor}.txt, stack trace from the crashed process, ideally with debug symbols activated (compile without `--release`).
Also, details on the hardware and software in use can help, especially GPU, graphic drivers and distribution version.

**Comment by superkooks** [comment]
Linux 5.12.1-2-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux
Majaro Version: Ornara 21.0.4
CPU: AMD Ryzen 5 5600X
GPU: Nvidia GTX 1050Ti
Driver Version: 460.73.01

Compiling without `--release` seems to have fixed the VAAPI issue (maybe it just needed to recompile?). However now, when the ALVR client connects, it freezes on the `The stream will begin soon` message, allowing me to look around and see the floating screen (not sure what else to call it).

Searching around led me to #463, so I guess, issue solved. Thanks.

**Comment by lmarianski** [comment]
Not sure if its related, but i crash on the release build too (altho everything works fine on the dev build, and i do get the VAAPI message)
```
OS: Arch Linux x86_64
Kernel: 5.12.1-zen2-1-zen
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz
GPU: NVIDIA GeForce GTX 1660
Driver Version: 465.27
```
FYI the current version of the linux port is actually semi playable, the only major issues are all NVIDIA specific (Hardware acceleration is missing, jittery position due to a problem that's too big to explain here, and looks like this)
@superkooks

**Comment by lmarianski** [comment]
Oh if you're using the standard alvr client you need to join the discord and download the version with software encoding added in (since apparently that requires some change in the client too) @superkooks

**Comment by superkooks** [comment]
I'll try it out tomorrow. Thanks!

**Comment by superkooks** [comment]
Cool! Finally got it to work. The client (for those who don't want to join the discord server the client is [here](https://cdn.discordapp.com/attachments/776913132672516106/837965161653469184/alvr_client_oculus_quest.apk.xz)) works, not well I guess. With my current-gen cpu I got about 30fps at most (make sure to switch to h264 to get higher than 1 fps). I guess this is beside the point though. Looking forwards to hardware encoding on NVIDIA!

**Comment by ronthecookie** [comment]
It sounds like everyone in this issue has had their issues resolved, closing.
