### ISSUE TITLE
Integrate ADB script for initiating a USB connection

### ISSUE THREAD

**Issue by zmerp** [alvr-org/ALVR#567]

**Comment by jacklul** [comment]
I'm posting a script I've been using to simplify launching: [**ALVR USB Connection.bat**](https://pastebin.com/TzJZ0MmK)

It waits for specific ADB device (in this case - headset) to become connected, runs the `adb forward tcp:port` commands and then launches ALVR.
In case for some reason the ADB connection is lost it will wait for device to be connected again - this process kills ADB server and restarts the script while keeping ALVR (and any running game) open, when device gets plugged back in it should reconnect automatically on the headset.

Requirements:
- Followed instructions in **PC** part of [this guide](https://github.com/alvr-org/ALVR/wiki/Use-ALVR-through-a-USB-connection), and verified that it all works.
- The script has to be placed in the same directory where `ALVR Launcher.exe` is.
- ADB executable has to be globally available, if it's not put a path to it into `adbpath.txt`, e.g.: `C:\ADB`.
- You have to run `adb devices` from the command prompt to obtain your device id and then create a file called `adbdevice.txt` and put the name inside - use notepad, no extra spaces, no extra lines.

_Note:  `adbpath.txt` and  `adbdevice.txt` must be placed where `ALVR USB Connection.bat`/`ALVR Launcher.exe` is!_

Hopefully something similar could be implemented into the dashboard directly.

**Comment by ronthecookie** [comment]
I think we could use the [mozdevice](https://lib.rs/crates/mozdevice) crate.

**Comment by mittorn** [comment]
Maybe use udev rule for this?
It also may enable adb tcp which useful for sidequest
