### ISSUE TITLE
Controllers orientation in some games

### ISSUE THREAD

**Issue by cetygamer** [alvr-org/ALVR#577]
Hi, all.

This is just a question about setting up VR environment for some games using ALVR. My hardware is Oculus Quest 1.

Some games have issues with player height and controller orientation recognition when using ALVR. While player height (and floor level) can be adjusted using OpenVR Advanced Settings, I am struggling to find any means to correct controller orientation.

For example, in The Wizards - Enhanced Edition and The Wizards - Dark Times virtual hands have this unnatural position, it almost like hands are titled 90 degrees up and to the left.

In additon, The Wizards - Dark Times doesn't detect the controllers at all, until I set headset emulation to Oculus Rift S and controllers to Oculus Rift S.

So, are there any ALVR settings / third-party application to adjust controllers orientation in-game?
Thanks.

**Comment by zarik5** [comment]
I never seen the pose of the controllers to be this wrong, dis you messed something with OpenVR Advanced Settings? Anyway you can change position offset and rotation offset of controllers in ALVR in the Headset tab (advanced mode).

**Comment by cetygamer** [comment]
No, haven't installed OpenVR Advanced Settings yet, but is is reported to help with floor offset issues. This issues are game specific. I will try to prepare some screenshots to better explain the situation.

**Comment by cetygamer** [comment]
@zarik5, sorry for the late follow up. Here are the screenshots.

![ALVR_vs_Link_Wizards](https://user-images.githubusercontent.com/14858753/113395086-fc7cff00-93a1-11eb-9e55-ed363938e5c6.jpg)

The first picture shows, how I hold my hands during the experiment (both ALVR and Link).
The second shows how game renders hands while using ALVR.
And the third one is via Oculus Link Cable.

Notice, how in case of ALVR hands are pointing directly upwards and twisted, so the thumbs appear closer to each other.
As for Oculus link, the hands are pointing slighly away from the camera and are not tilted, exacly how I hold the controllers.

**Comment by zarik5** [comment]
If only some games are wrong then it might be SteamVR's fault. SteamVR has a bug with some games where normally you have to tilt the hands 30deg and offset them to 5mm (or something like that) to make them look normal. Some games that target some older VR runtimes may try to overcompensate, but ALVR has no mechanism to detect which runtime version the game expects. Your best bet is to offset the controllers pose with the ALVR advanced settings and revert it to default when you want to play other games.

**Comment by cetygamer** [comment]
Thanks, I'll give it a try. BTW, I laucnhed the game both times through Steam VR (first run Steam VR and then launch the game from there in case of Oculus Link).

**Comment by cetygamer** [comment]
Ok, I have figure out a set up which somewhat works for me.

1. Set Tracking speed to Medium / Fast (overwise the game sometines won't register wrist movements).
2. Each time ALVR starts (ALVR doesn't seem to be saving this setting): Headset / Controllers / Position rotation / X - change the default 36 to 0.
   This makes it awkward to use SteamVR, but seems to be fixing in-game hand orientation.
3. Each time game starts: go to OpenVR Advanced Settings and set Floor Y offset to 1.60.

Oculus prediction Tracking speed seems to be not working for me, the game can't ever recognize controllers and in SteamVR controllers bounce around and it is hard to even start the game (hit the Launch button).
