### ISSUE TITLE
Provide better linux documentation

### ISSUE THREAD

**Issue by senpl** [alvr-org/ALVR#583]
I tried build in arch, but Wiki is not clear enough for me.
Lines from https://github.com/alvr-org/ALVR/wiki/Build-from-source#build-server  that I would like more clarity:

> The following lines need to be ran as root, and 0/DP-1 must be replaced by the index of the GPU you want to use, and a display that is not currently in use

This is completly not clear for me. I got 0 but no other subfolders. Should I create them? Why not DP-9 (does it has to be screen currently avaliable, or any?)

> #for a Quest 1 and default rendering settings, it will be 2112x1184 72 Hz

From where this values are take from? How would they look for Quest 2 ?

**Comment by xytovl** [comment]
I am currently working on a different mechanism, on https://github.com/alvr-org/ALVR/pull/569
The Linux instructions will be totally deprecated once the vulkan base approach is working.

With all the instability, limited hardware support and error-prone steps, I won't encourage people to try the version currently on master.
