### ISSUE TITLE
Guide to connect PC to LAN router separate from WAN

### ISSUE THREAD

**Issue by nrgapple** [alvr-org/ALVR#586]
Is there a current guide to use a dedicated router to just run ALVR off of?

For example:

- Computer is wired to **router 1** connected to the internet
- Computer is wired to **router 2** for streaming to ALVR headset (Quest)

![image](https://i.imgur.com/z1FpZ89.png)

**Comment by Ekristoffe** [comment]
I don't understand, does your PC have 2 different network card with 2 different IP Address ?
Normally everything is automatically handed by your PC ARP tables...

**Comment by nrgapple** [comment]
Idk. I was wondering if there was a solution for this. 

Lets say for example that you have a gaming laptop and do not have control of the wifi you will be connected to. So you would like to have a system where you could bring a router with you to create a local network with your laptop and vr device. But you would also like your laptop to be connected to the wifi around you for internet connection

**Comment by JosNun** [comment]
It's somewhat supported. There's a guide here [https://github.com/alvr-org/ALVR/wiki/ALVR-client-and-server-on-separate-networks]()
