### ISSUE TITLE
Quest 2 thumb rest sensors don't do anything

### ISSUE THREAD

**Issue by art0007i** [alvr-org/ALVR#591]
It would be nice to have them work

**Comment by zarik5** [comment]
This is planned. Currently we are using an older SDK to support the Oculus Go (so the thumb rest is not supported), but this will change after we switch to OpenXR.

**Comment by ronthecookie** [comment]
Duplicate of #255.

**Comment by ckiee** [comment]
(This shouldn't have been auto-closed.)
