### ISSUE TITLE
RTX 3090 ALVR panickedMessage error.

### ISSUE THREAD

**Issue by dyart1989** [alvr-org/ALVR#592]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Unable to open ALVR error.

#### Environement

CPU:AMD 3950X
GPU:RTX 3090
WIN10 2004

### Features:

Unable to open ALVR error.

ALVR panickedMessage: "Unavailable' Backtrace:0: HmdDriverFactory 1: HmdDriverFactory 2: HmdDriverFactory 3: HmdDriverFactory4: HmdDriverFactory 5: HmdDriverFactory6: HmdDriverFactory7: rust eh personality 8: rust eh_personality 9: HmdDriverFactory0: HmdDriverFactory 11: <unknown>12: HmdDriverFactory 13: HmdDriverFactory 14: HmdDriverFactory 15: BaseThreadInitThunk 16: RtlUserThreadStart

**Comment by ronthecookie** [comment]
This error is inside legacy code and we don't know exactly why it happens. I think you might be able to see what other people have done to try to fix it in the [Discord server](https://discord.gg/alvr).

**Comment by WEsualizeLLC** [comment]
Stopping all Steam-realted processes in Task Manager fixed it for me.
