### ISSUE TITLE
Move the server out of the SteamVR driver

### ISSUE THREAD

**Issue by revanmj** [alvr-org/ALVR#599]
As title says, I wish ALVR would be able to work like VD - autorun with Windows in a "listening" mode without starting SteamVR and launching it only once client connects to a host.

Then, when client disconnects (by exiting SteamVR on a headset) revert back to listening mode instead of closing entire app.

The way things work now, you have to remember to manually launch ALVR on a computer before running it on headset each time, which is a little bit annoying.

**Original Title:** Start ALVR in "listening" mode and revert to it once session is closed instead of exiting application

**Comment by zarik5** [comment]
I plan to split the server into server + SteamVR driver but right now there is still too much legacy code to do so.

**Comment by ronthecookie** [comment]
If we do end up doing this, we'll need to discuss what the exact responsibilities of each newly minted part would be.

**Comment by zarik5** [comment]
Ideally the SteamVR driver should only worry about the OpenVR API and maybe also a bit of glue for DirectX. The encoder should be moved to the main executable. The communication should happen through IPC, similarly how it works with the Vulkan layer on Linux

**Comment by zarik5** [comment]
As discussed a while ago on Discord, this is not the preferred way forward.
