### ISSUE TITLE
Idea: Ability to force connection though USB or WIFI

### ISSUE THREAD

**Issue by grzegorz-dzikowski** [alvr-org/ALVR#601]
I've observed some things
1. You need to have a connection to any Wifi in Quest 2 in order to ADB-USB TCP to work
2. ALVR prefers connecting over WIFI to connecting over USB
3. "Trust" trustes both Wifi and USB connection

I don't have 2 WIFi networks in home, so when I try to connect ALVR via USB, but simultaneously I'm connected to same WIFI network in both computer and quest, ALVR then connects via Wifi (which is bad in terms of latency) rather then by USB. I have to make some system rules to stop this behaviour.

Is there a way to prevent that? if not, Is it possible to add some kind of switch, or lock, that f.e. block connection over wifi, or force connection over adb usb tcp socket?
Thanks

**Comment by grzegorz-dzikowski** [comment]
Never mind, added in recent update

**Comment by likeproblem** [comment]
> Never mind, added in recent update

Man, how to use it? I have the same problem, I need to throw this thing through USB.
