### ISSUE TITLE
Quest1 V20  client apk crash

### ISSUE THREAD

**Issue by foreversos** [alvr-org/ALVR#613]
my quest1 only run 1.3.2 client
all greater version(1.4,1.5 and subVersion) run must crash
quest1 is v20

**Comment by zarik5** [comment]
Please update your Quest firmware.

**Comment by foreversos** [comment]
thanks. i will try




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Riccardo ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alvr-org/ALVR] Quest1 V20  client apk crash (#613)





 
Please update your Quest firmware.

**Comment by foreversos** [comment]
update v25.
it work
