### ISSUE TITLE
Debug alvr_server using break points

### ISSUE THREAD

**Issue by Mr-Crab** [alvr-org/ALVR#616]
Hi, recently I have tried to debug alvr_server in CLion, but the alvr_server.dll seems not easy to debug using break points. I have tried the "Attach to Process" to steamVR, but it doesn't work. I don't know if there are any suggestions or methods to solve this. And how do you debug the alvr_server, using log or breakpoints?:grinning:

By the way, I have found the [Simple-OpenVR-Driver-Tutorial](https://github.com/terminal29/Simple-OpenVR-Driver-Tutorial) project provides [a way to use break points](https://github.com/terminal29/Simple-OpenVR-Driver-Tutorial#debugging). But this is implemented using Visual Studio and CMake.

**Comment by zarik5** [comment]
In ALVR C++ code is not built with Cmake or Vistual Studio, instead the `cc` Rust library is used inside a Rust build script. This makes things harder to debug but it was necessary to be able to bridge Rust and C++ as nicely as possible.

**Comment by Mr-Crab** [comment]
> In ALVR C++ code is not built with Cmake or Vistual Studio, instead the `cc` Rust library is used inside a Rust build script. This makes things harder to debug but it was necessary to be able to bridge Rust and C++ as nicely as possible.

So the most convenient way to watch variables is using the log in Rust and C++, right?

**Comment by xytovl** [comment]
For my developments on Linux, I did not have issues attaching to the running process.

The windows build does not enable debug symbols, for some link reason (see alvr/server/build.rs file), this might prevent placing breakpoints.

**Comment by Mr-Crab** [comment]
I have tried to add the ["debug" function](https://docs.rs/cc/1.0.10/cc/struct.Build.html#method.debug) in cc::Build in build.rs of alvr_server module (image below), and now I can debug into the C++ code.
![image](https://user-images.githubusercontent.com/25704687/116050384-f977e480-a6a9-11eb-994c-949a3bda124b.png)

**Comment by zarik5** [comment]
There is also the pdb file in nightly releases, that can be used to debug the prebuilt driver dll (but I never tried that).

**Comment by Mr-Crab** [comment]
I just tried modifying the build.rs file in alvr_server module (the first image below), and the program could stop at the break points in C++ source file, It seems the debug label is successful, because the "Exception" is related to steamVR (the second image below), not the msvcrtd.

![Alt text](https://user-images.githubusercontent.com/25704687/116054202-05fe3c00-a6ae-11eb-96a9-45c5f3ad6cb7.png)


![Alt text](https://user-images.githubusercontent.com/25704687/116054519-54abd600-a6ae-11eb-874b-170d43b48de5.png)

**Comment by ronthecookie** [comment]
@Mr-Crab That error looks like a side-effect of the actual error, maybe check the various log files? I'm not sure where they are on windows but on Linux they reside in `~/.steam/root/logs` so perhaps they will be in a similar location on Windows.
