### ISSUE TITLE
SteamVR won't work properly

### ISSUE THREAD

**Issue by pwtoothless** [alvr-org/ALVR#618]
So when I start ALVR it Starts SteamVR but when it gets here it says either 1 please reinstall SteamVR 2 it spams boxes that the address says 127.0.0.1_/ 3 it also says that I don't have 2 gpu's on adapter 0 please help me I have been trying to do this for 4 days now if you need any info to help me on this problem i can give it to you to help fix this problem

**Comment by pwtoothless** [comment]
![broken ALVR](https://user-images.githubusercontent.com/70607768/116004468-99087a80-a5b7-11eb-8701-4650358322fe.PNG)

**Comment by pwtoothless** [comment]
also I'm using a laptop

**Comment by ronthecookie** [comment]
Issues are for bug reports, not troubleshooting. You can join our [discord server](https://discord.com/invite/alvr) here for help.
