### ISSUE TITLE
Quest ALVR apk crashed on OvrActivity.onDestroy() method

### ISSUE THREAD

**Issue by Mr-Crab** [alvr-org/ALVR#622]
## Bug reports:

The ALVR apk will crash on the onDestroy() method in OvrActivity class. The relevant logcat is:

--------- beginning of crash
04-28 11:21:12.079  3862  3862 E AndroidRuntime: FATAL EXCEPTION: main
04-28 11:21:12.079  3862  3862 E AndroidRuntime: Process: flyvr.client.quest, PID: 3862
04-28 11:21:12.079  3862  3862 E AndroidRuntime: **java.lang.RuntimeException: Unable to destroy activity {flyvr.client.quest/com.polygraphene.alvr.OvrActivity}: java.lang.IllegalMonitorStateException: object not locked by thread before wait()**
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4949)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4978)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2024)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7385)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: **Caused by: java.lang.IllegalMonitorStateException: object not locked by thread before wait()**
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at java.lang.Object.wait(Native Method)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at java.lang.Object.wait(Object.java:442)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at java.lang.Object.wait(Object.java:568)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	**at com.polygraphene.alvr.OvrActivity.onDestroy(OvrActivity.java:289)**
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:8048)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1341)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4934)
04-28 11:21:12.079  3862  3862 E AndroidRuntime: 	... 11 more

## Cause && Fix try

I have checked the code, It seems that the OvrActivity.onDestroy() method doesn't lock the Object sync before call the 'mRenderingHandler.post()' method and 'sync.wait()' method. I have tried fixing the issue by adding the 'synchronized(sync)' statements like the image below. However, I'm a newer to Java, I am not sure this is an absolutely correct way to fix this problem. 

![image](https://user-images.githubusercontent.com/25704687/116357940-acbe1600-a82f-11eb-9f1b-165b76a58444.png)

**Comment by zarik5** [comment]
Thanks for the report! I'm also not an expert in Java but the code seems correct to me. Have you tested it? Does your fix gets rid of the crash?

**Comment by Mr-Crab** [comment]
> Thanks for the report! I'm also not an expert in Java but the code seems correct to me. Have you tested it? Does your fix gets rid of the crash?

It haven't. Though this trial reduced the number of FATAL EXCEPTIONs, there is still a related Exception remaining. I plan to take some time on this problem.

**Comment by zarik5** [comment]
Reasoning a bit more on your code it seems the race condition is still there. I pushed a fix on master.
