### ISSUE TITLE
Server Program crashes a few seconds after opening.

### ISSUE THREAD

**Issue by kokoropaint** [alvr-org/ALVR#644]
# Please follow the general troubleshooting steps first:

- ✅ I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- ✅ I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Bug reports:

The program closes a few seconds after I open it. This has happened with both the installer version and portable version (extracted to the root of my C:/system drive with read-only turned off), after a computer restart, with and without my headset connected to my computer via a USB-C cable, etc. The crash log is empty.
The apk on my Quest 2 works fine, it just has nothing to connect to because of this.

#### Environment

I wasn't sure of the best way to share my specs so, [my DxDiag results can be found here](https://pastebin.com/7C6508jM) (with some information redacted)
ALVR version v15.2.1
SteamVR version: Build ID 6369009 (? I don't know where to find version information otherwise, but it's the newest one at the time of posting this)
Windows 10 version 2004 (OS Build 19041.928)

**Comment by ronthecookie** [comment]
I don't use the Windows build so I'm not sure what's going on here but you will probably be able to get more help in our [Discord server](https://discord.gg/alvr).

You haven't provided a lot of information so I'm going to close this for now but feel free to re-open it if you do not wish to use Discord.
