### ISSUE TITLE
ALVR Server not loading in ubuntu

### ISSUE THREAD

**Issue by tensu36** [alvr-org/ALVR#669]
on the linux version it says waiting for server to load but the server never loads

**Comment by wangling12** [comment]
> Install SteamVR, launch it once then close it. This is to make sure it sets the environment correctly for ALVR.

**Comment by tensu36** [comment]
> Install SteamVR, launch it once then close it. This is to make sure it sets the environment correctly for ALVR.

i already have steam vr installed and launched it beforehand

**Comment by bjoern-tantau** [comment]
I have the same issue. I removed `~/.steam/` to get a clean environment. I started steam, logged in, installed Steam VR, ran Steam VR, closed Steam VR and then started ALVR.

Steam CLI output:
```
$ steam
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/bjoern/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2021-06-13 15:29:14] Startup - updater built Jun  8 2021 22:23:36
[2021-06-13 15:29:14] Using the following download hosts for Public, Realm steamglobal
[2021-06-13 15:29:14] 1. https://cdn.cloudflare.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-13 15:29:14] 2. https://cdn.akamai.steamstatic.com, /client/, Realm 'steamglobal', weight was 100, source = 'update_hosts_cached.vdf'
[2021-06-13 15:29:14] 3. http://media.steampowered.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2021-06-13 15:29:14] Verifying installation...
[2021-06-13 15:29:14] Verification complete
STEAM_RUNTIME_HEAVY: ./steam-runtime-heavy
VR Server (v1623188486)

VR Server (v1623188486)
```

ALVR output:

```
$ ./alvr_launcher 
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
Running Steam on ubuntu 20.04 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Steam client's requirements are satisfied
WARNING: Using default/fallback debugger launch
/home/bjoern/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad steam://rungameid/250820
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
```

The last line of ALVR output continues indefinitely.

**Comment by bjoern-tantau** [comment]
I found two mentions of alvr in the logs.

https://pastebin.com/hJps0kFd vrclient_steam.txt

```
Fri Jul 09 2021 13:13:45.095593 - Unable to load driver alvr_server. Primary driver shared library not found on filesystem (for this architecture): /home/bjoern/Packages/alvr_server_linux/lib64/alvr/bin/linux32/driver_alvr_server.so.
Fri Jul 09 2021 13:13:45.095623 - Unable to init watchdog mode for driver alvr_server: VRInitError_Init_FileNotFound
```

https://pastebin.com/pK89sncu vrserver.txt

```
Fri Jul 09 2021 13:14:39.070409 - Unable to load driver shared library alvr_server from /home/bjoern/Packages/alvr_server_linux/lib64/alvr/bin/linux64/driver_alvr_server.so. Error Code (1)
Fri Jul 09 2021 13:14:39.070456 - ASSERT: "DriverManager alvr_server load error 1" at /data/src/common/vrcommon/drivermanager.cpp:404.
Fri Jul 09 2021 13:14:39.104261 - Unable to load driver alvr_server because of error VRInitError_Init_FileNotFound(103). Skipping.
```

**Comment by ckiee** [comment]
@bjoern-tantau You are either missing a library or you have the wrong version of it; you can enable the debug output for the dynamic linker by setting [LD_DEBUG](http://www.bnikolic.co.uk/blog/linux-ld-debug.html).

**Comment by ckiee** [comment]
Closing since this is basically a duplicate of the discussion in https://github.com/alvr-org/ALVR/pull/604#issuecomment-824063159.

There are people in our [discord server](https://discord.com/invite/alvr) who can help you if you're still having this problem.

**Comment by bestlinuxgamers** [comment]
Since the error was not solved for me in the pull request and it is now closed, I will continue writing here.

The solution approach in the pullrequest is to use Steam-native. However this is far away from an optimal solution.

`Warning: Using the Steam native runtime is not recommended as it might break some games due to binary incompatibility and it might miss some libraries present in the Steam runtime.` ([Arch Wiki](https://wiki.archlinux.org/title/Steam/Troubleshooting))

So I wanted to ask if there is a way to fix this error without disabling the steam runtime.

**Comment by mefisto74** [comment]
last version of ALVR dont running for me as well in ubuntu. 
18.2.2 works. still no news about this issue? only steam native?
