### ISSUE TITLE
Linux Audio Streaming

### ISSUE THREAD

**Issue by ckiee** [alvr-org/ALVR#673]
Even though no one tried to make any changes for audio streaming on Linux, with the power of cool abstractions, it already works: https://github.com/alvr-org/ALVR/issues/269#issuecomment-842978186!

Microphone streaming (i.e. headset -> PC) does not currently work.

**Comment by lmarianski** [comment]
Here's the pw-cli output, again: `https://gist.github.com/lmarianski/46dca0e23884868fc6b73f6687c64f9d`
:p

**Comment by yackaro** [comment]
For me, Audio streaming (running PipeWire for my system) is working, but not properly.
Some devices in the list crash ALVR or SteamVR in various ways, and others stream one of the microphones on the computer, resulting in a feedback loop between the PC microphone and my quest's speakers. I cannot get it to stream system audio at all.

**Comment by lmarianski** [comment]
@yackaro yea some options from the list crash for me too, try installing `pipewire-jack` and select the `jack` device on the list

**Comment by Killrmemz** [comment]
@lmarianski already set it up with that, started the JACK server and it's still not working. all that JACK is able to pick up is my laptop microphone, which results in the same feedback loop as ever.

**Comment by mittorn** [comment]
Microphone streaming works perfectly with jackd server + alsa jack plugin.
I added 3 alsa-jack devices in asoundrc, one is default, and two for ALVR with fixed names, with plug devices for each one. cal seems to require non-empty hint on device to show it in list
first device selected to capture audio, second as microphone in and default as microphone out.
And simple rule in qjackctl router which connects all outputs to capture in and all inputs to microphone in. The only issue that i hear real PC microphone in ALVR client (i do not know how to make rule that disconnects alvr capture from system capture device), but it may be fixed by calling jack_disconnect after every ALVR launch
I think, it should be possible to make same configuration with alsa + 2 loopback devices without jack server

**Comment by mittorn** [comment]
Also, i removed jack library from steam runtime, because it was incompatible with system jack server

**Comment by Kirottu** [comment]
For me using `pipewire-media-session` this does not work at all, it only crashes with `At alvr/audio/src/lib.rs:382: A backend-specific error has occurred: ALSA function 'snd_pcm_hw_params' failed with error 'EIO: I/O error'`. With `wireplumber` I only hear static and many of my other utilities break.

**Comment by Kirottu** [comment]
Update on my discoveries:

Apparently the jack option tried to record audio from my headset microphone, which was disabled. This caused the I/O errors and re-enabling the microphone input allowed for ALVR to start. The static was apparently simply due to the microphone being really bad. After ALVR had started I could use helvum to re-route the audio to properly stream audio to the headset.

**Comment by LuNeder** [comment]
> Update on my discoveries:
> 
> Apparently the jack option tried to record audio from my headset microphone, which was disabled. This caused the I/O errors and re-enabling the microphone input allowed for ALVR to start. The static was apparently simply due to the microphone being really bad. After ALVR had started I could use helvum to re-route the audio to properly stream audio to the headset.

Did you find a way to automatically reroute the audio?
Choosing "pipewire" on ALVR and then using Helvum to manually reroute audio to "pipewire alsa" makes it work, but I have to manually reroute the audio for every single app I open, every single time I open them.

**Comment by mittorn** [comment]
JACK has many routing utilities, it might help with pipewire

**Comment by DocMAX** [comment]
On arch i installed the pipewire-jack package. But i dont see any jack device in Helvum?!?

**Comment by Meister1593** [comment]
Didn't know about this issue, but I guess this can be posted
Alvr kinda already had it in docs, anyway:
https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/blob/main/audio-setup.sh
Its supposed to be portable, no additional stuff aside from pipewire in settings required, and would move playback/recording to required sinks.

**Comment by GrigoriyPeters** [comment]
> Didn't know about this issue, but I guess this can be posted Alvr kinda already had it in docs, anyway: https://github.com/alvr-org/ALVR/wiki/Installation-guide#automatic-audio--microphone-setup Its supposed to be portable, no additional stuff aside from pipewire in settings and setting this script as on connect/on disconnect required, and it would move playback/recording to required sinks.

Welp. It looks like the thing I did. But mine loops every second and automatically connects the sound to the headset if  it is connected, and connects back to the default sink otherwise.
My Pico 4 disconnects after about 10 seconds of inactivity (proximity sensor) and it works for me.

**Comment by Meister1593** [comment]
That script doesn't loop, it's passive and doesn't need any background activity.
It essentially does what you would do in pavucontrol when you change playback/recording sinks in first tab, but programmatically.

**Comment by GrigoriyPeters** [comment]
> That script doesn't loop, it's passive and doesn't need any background activity. It essentially does what you would do in pavucontrol when you change playback/recording sinks in first tab, but programmatically. Works fine with pico 4, or any other headset

Thanks. I've tested this script and it works well.
Perhaps it should come by default.

**Comment by Meister1593** [comment]
> > That script doesn't loop, it's passive and doesn't need any background activity. It essentially does what you would do in pavucontrol when you change playback/recording sinks in first tab, but programmatically. Works fine with pico 4, or any other headset
> 
> Thanks. I've tested this script and it works well. Perhaps it should come by default.

Technically nightly already has automatic script setup and set, but (proper) native pipewire without cpal through alsa, without scripts is currently in active development.
