### ISSUE TITLE
Client upload from launcher/server

### ISSUE THREAD

**Issue by xytovl** [alvr-org/ALVR#677]
In order to facilitate initial setup, we could add an apk upload feature using `adb install`.

On packaged Linux installation, this would facilitate the process: user installs package from distribution, executes the launcher, is prompted to activate developer mode, connect headset via usb and setup is done.

**Comment by ckiee** [comment]
We could also automatically open the ALVR app: (at least for the first use)
```
[nix-shell:~/git/ALVR]$ history | grep monkey | head -n1
 9694  adb shell monkey -p alvr.client.quest 1
```

**Comment by Vixea** [comment]
Can this be closed now that we have the launcher (different from the old binary named that)?

**Comment by zarik5** [comment]
It's not yet implemented.

**Comment by zmerp** [comment]
Done with new launcher
