### ISSUE TITLE
Does not compile with deps installed. 

### ISSUE THREAD

**Issue by bplx** [alvr-org/ALVR#691]
Log: https://bpa.st/HRPA
----->
System: Ubuntu 18.04 (actually Elementary OS Hera, it's just based off that)
----->
Things i've done to get this to happen: Install the deps with the Apt command in the build guide // Build with Cargo (failed!)
----->
Command used to build:  cargo xtask build-server --release --bundle-ffmpeg

**Comment by xytovl** [comment]
Do you have gcc 8?

It seems your compiler does not have https://en.cppreference.com/w/cpp/filesystem

**Comment by bplx** [comment]
Aha! https://bpa.st/KVUA is the new log. GCC 8 got past that specific error, but new errors must strike!

**Comment by xytovl** [comment]
It seems ffmpeg build system fails if you change compiler version. I do not plan on supporting this automatically, try to clean the deps build and retry.

**Comment by bplx** [comment]
Silly question, but how do i clean the deps build?

**Comment by bplx** [comment]
Oof, new issue: (Log): http://0x0.st/-2_6.txt
