### ISSUE TITLE
ALVR Exits on Startup when Dashboard Appears

### ISSUE THREAD

**Issue by mreithan1** [alvr-org/ALVR#693]
ALVR waits for the server to start, then exits within seconds of the dashboard coming up.

I've tried uninstalling, reinstalling, restarting my computer, different versions.
I tried checking the crash report but it's completely empty...
I tried running through a command prompt and this is what I get before the dashboard appears, then quickly disappears:
```
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [druid_shell::platform::windows::window] dxgi factory pointer = 0x1ffdc0ed970
DEBUG [druid_shell::platform::windows::window] 0x1ffdc0f0170: desc = Some("NVIDIA GeForce GTX 1060 6GB"), vram = 6345981952
DEBUG [druid_shell::platform::windows::window] 0x1ffdc0f0600: desc = Some("Microsoft Basic Render Driver"), vram = 0
DEBUG [druid_shell::platform::windows::window] adapter = 0x1ffdc0f0170
DEBUG [druid_shell::platform::windows::window] swap chain res = 0x0, pointer = 0x1ffdc17fbf0
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] created stream: TcpStream { addr: 127.0.0.1:62783, peer: 127.0.0.1:8082, socket: 2096 }
INFO  [ureq::unit] sending request GET http://127.0.0.1:8082/favicon.png
DEBUG [ureq::unit] writing prelude: GET /favicon.png HTTP/1.1
Host: 127.0.0.1:8082
User-Agent: ureq/2.0.2
Accept: */*


DEBUG [ureq::unit] response 200 to GET http://127.0.0.1:8082/favicon.png
DEBUG [ureq::stream] dropping stream: TcpStream { addr: 127.0.0.1:62783, peer: 127.0.0.1:8082, socket: 2096 }
```

I can't set up firewall rules or anything like that as the server exits before I can interact with the setup.
Running with administrator privileges does nothing to remedy this either. I even reinstalled Chrome in an attempt to fix this, reinstalled ALVR, and rebooted, no change. No change with clicking the "Restart Drivers and Try Again" button either.
However, I did notice that when I first start up my computer ALVR works fine on the first launch, but if I close it and want to reopen it later, the issue returns and I cannot get it to start.

I can confirm the server is not running as the quest cannot connect to ALVR nor can my browser pull up the dashboard.

Relevant Specs:
CPU: AMD Ryzen 7
GPU: GTX 1060 6GB
ALVR Versions Attempted: Latest (15.2.1) and 15.0.0
Windows Version: 2004

**Comment by mreithan1** [comment]
I should also mention that I have SteamVR on a second drive, in case that might be the issue. I've noticed that on these bugged launches, Steam says it's starting SteamVR, then closes afterward, not launching SteamVR.

**Comment by matterofact** [comment]
Hey I'm having a similar issue to this, did you manage to get this working in the end? Thanks!

**Comment by mreithan1** [comment]
> Hey I'm having a similar issue to this, did you manage to get this working in the end? Thanks!

Unfortunately not yet.

**Comment by QmanRocks** [comment]
> ALVR waits for the server to start, then exits within seconds of the dashboard coming up.
> 
> I've tried uninstalling, reinstalling, restarting my computer, different versions.
> I tried checking the crash report but it's completely empty...
> I tried running through a command prompt and this is what I get before the dashboard appears, then quickly disappears:
> 
> ```
> DEBUG [druid::localization] available locales [], current en-US
> DEBUG [druid::localization] resolved: [en-US]
> DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
> DEBUG [druid_shell::platform::windows::window] dxgi factory pointer = 0x1ffdc0ed970
> DEBUG [druid_shell::platform::windows::window] 0x1ffdc0f0170: desc = Some("NVIDIA GeForce GTX 1060 6GB"), vram = 6345981952
> DEBUG [druid_shell::platform::windows::window] 0x1ffdc0f0600: desc = Some("Microsoft Basic Render Driver"), vram = 0
> DEBUG [druid_shell::platform::windows::window] adapter = 0x1ffdc0f0170
> DEBUG [druid_shell::platform::windows::window] swap chain res = 0x0, pointer = 0x1ffdc17fbf0
> DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
> DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
> DEBUG [ureq::stream] created stream: TcpStream { addr: 127.0.0.1:62783, peer: 127.0.0.1:8082, socket: 2096 }
> INFO  [ureq::unit] sending request GET http://127.0.0.1:8082/favicon.png
> DEBUG [ureq::unit] writing prelude: GET /favicon.png HTTP/1.1
> Host: 127.0.0.1:8082
> User-Agent: ureq/2.0.2
> Accept: */*
> 
> 
> DEBUG [ureq::unit] response 200 to GET http://127.0.0.1:8082/favicon.png
> DEBUG [ureq::stream] dropping stream: TcpStream { addr: 127.0.0.1:62783, peer: 127.0.0.1:8082, socket: 2096 }
> ```
> 
> I can't set up firewall rules or anything like that as the server exits before I can interact with the setup.
> Running with administrator privileges does nothing to remedy this either. I even reinstalled Chrome in an attempt to fix this, reinstalled ALVR, and rebooted, no change. No change with clicking the "Restart Drivers and Try Again" button either.
> However, I did notice that when I first start up my computer ALVR works fine on the first launch, but if I close it and want to reopen it later, the issue returns and I cannot get it to start.
> 
> I can confirm the server is not running as the quest cannot connect to ALVR nor can my browser pull up the dashboard.
> 
> Relevant Specs:
> CPU: AMD Ryzen 7
> GPU: GTX 1060 6GB
> ALVR Versions Attempted: Latest (15.2.1) and 15.0.0
> Windows Version: 2004

I had this same issue, and the way I fixed it was to have it work once (> However, I did notice that when I first start up my computer ALVR works fine on the first launch,) and then go into the Installation tab and register to firewall AND register the SteamVR driver. Let me know if this helps. Also, make sure you have all the Add-Ons enabled beforehand (this helped me for some reason)

**Comment by sctanf** [comment]
If ALVR runs fine after registering the SteamVR driver, you can try registering it without having to launch ALVR first.

In cmd, navigate to your steam install path, and go here `\Steam\steamapps\common\SteamVR\bin\win64` and run `vrpathreg adddriver "C:\Program Files\ALVR` (or wherever you installed ALVR) 

Then open SteamVR and see if ALVR starts with it.

**Comment by mreithan1** [comment]
> If ALVR runs fine after registering the SteamVR driver, you can try registering it without having to launch ALVR first.
> 
> In cmd, navigate to your steam install path, and go here `\Steam\steamapps\common\SteamVR\bin\win64` and run `vrpathreg adddriver "C:\Program Files\ALVR` (or wherever you installed ALVR)
> 
> Then open SteamVR and see if ALVR starts with it.

This fixed thje issue
