### ISSUE TITLE
Running alvr_launcher does nothing on kubuntu 21.04

### ISSUE THREAD

**Issue by Ulquiro** [alvr-org/ALVR#700]
After building from source, launching `alvr_launcher` in the `build/alvr_server_linux/bin/` folder simply does nothing. Not even an error code is returned...

I have reproduced this issue on release 15.2.1 and on [this commit](https://github.com/alvr-org/ALVR/tree/813b8b792289c093c5c3495ede9b1467e0e549c7)

According to the wiki the Linux build _should_ be working on Ubuntu 20.04.
I have Kubuntu 21.04

Any idea how i could debug this ?

```
$ ./alvr_launcher # does absolutely nothing
$ echo $? # prints 0
```

Besides unused functions and imports warnings i only had this one thing
```
warning: In file included from src/bindings.cpp:1:
warning: src/openvr_driver_capi.h: In member function ‘virtual void DriverDirectModeComponent::GetNextSwapTextureSetIndex(vr::SharedTextureHandle_t*, uint32_t (*)[2])’:
warning: src/openvr_driver_capi.h:172:67: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:   172 |             callbacks.context, (const SharedTextureHandle_t(&)[2])sharedTextureHandles, pIndices);
warning:       |                                                                   ^~~~~~~~~~~~~~~~~~~~
warning: src/openvr_driver_capi.h:73:9: note: in definition of macro ‘CLASS_C_INTERFACE’
warning:    73 |         interface;                                                          \
warning:       |         ^~~~~~~~~
```

**Comment by Ulquiro** [comment]
Also I did try to build with and without the  `--release` flag. And I have already started SteamVR several times

**Comment by ckiee** [comment]
Hi! You can try `ss -elx | grep alvr` to see if there's an `alvr_launcher_mutex` sticking around from a launcher crash. You can reboot your system or use [`rg(1)`](https://github.com/BurntSushi/ripgrep) to change the instance where it's defined .

**Comment by ckiee** [comment]
Thinking a bit more about this, it'd be nice if we had a message instead of silently exiting if this is, in fact, what my last comment theorized it is.

**Comment by chutaklee** [comment]
Same issue here, pretty sure it's not about locked mutex. After I commented out [this block of code](https://github.com/alvr-org/ALVR/blob/master/alvr/launcher/src/main.rs#L197-L205) a window appeared. Then
```
lee@hp ~/A/t/debug (master) [SIGINT]> ./alvr_launcher
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
ERROR [alvr_common::logging] failed to get alvr dir from /home/lee/ALVR/target/debug/alvr_launcher compared to bin/alvr_launcher, path do not match
DEBUG [druid::localization] available locales [], current en-US
DEBUG [druid::localization] resolved: [en-US]
INFO  [druid_shell::platform::gtk::application] gtk: Activated application
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
DEBUG [ureq::stream] connecting to 127.0.0.1:8082 at 127.0.0.1:8082
```

**Comment by ckiee** [comment]
@chutaklee You need to compile with `cargo xtask build-server --release` and run the binary in the `build` folder, not `target`.

**Comment by chutaklee** [comment]
> @chutaklee You need to compile with `cargo xtask build-server --release` and run the binary in the `build` folder, not `target`.

Thanks that works!
