### ISSUE TITLE
Bug or me messing up

### ISSUE THREAD

**Issue by GrazePossum** [alvr-org/ALVR#704]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

My headset is not tracked at all however Controllers are and it works perfectly outside of ALVR 

#### Environement

I have an APU AMD Athlon 200GE with Vega 3 graphics (I know it's listed under speck but it can run VR as I have before using ALVR)

**Comment by ckiee** [comment]
You can join our [discord server](https://discord.com/invite/alvr) for help, there are more people who have experience with issues like this there.

**Comment by ckiee** [comment]
Closing as the stale bot would've probably already done if I didn't comment.
