### ISSUE TITLE
Help running alvr server

### ISSUE THREAD

**Issue by matterofact** [alvr-org/ALVR#707]
When I try to compile from source, I get this error without the --release flag:

error: failed to run custom build command for `alvr_server v15.2.1 (/home/matt/ALVR/alvr/server)`

Caused by:
  process didn't exit successfully: `/home/matt/ALVR/target/debug/build/alvr_server-7084341e52e2ee65/build-script-build` (exit status: 1)

With the release flag I get an error saying libdrm cannot be found by pkg-config.

I have downloaded the .zip file alvr_server_ubuntu_20_04.zip, and have installed the apk using sidequest, but I just cannot get the server to run on my linux machine.

Please help!!!

**Comment by octinhuh** [comment]
Make sure `libdrm` is installed. You can do this by running `pkg-config --modversion libdrm`. It should give you something like `2.4.102` or similar. If it's not installed, be sure to install it through your package manager (for ubuntu, that would be `sudo apt install libdrm-dev`)

If it *is* installed and still gives the error, run `pkg-config --print-errors libdrm` and see if there are any problems with it

I could be wrong but I think you only ever want to run the build script **with** the `--release` flag as well

**Comment by matterofact** [comment]
> Make sure `libdrm` is installed. You can do this by running `pkg-config --modversion libdrm`. It should give you something like `2.4.102` or similar. If it's not installed, be sure to install it through your package manager (for ubuntu, that would be `sudo apt install libdrm-dev`)
> 
> If it _is_ installed and still gives the error, run `pkg-config --print-errors libdrm` and see if there are any problems with it
> 
> I could be wrong but I think you only ever want to run the build script **with** the `--release` flag as well

Thanks this fixed that issue! I'm still getting other errors but I think I'll just have to go through the documentation and check i have all the dependencies

**Comment by ckiee** [comment]
Closing as resolved.
