### ISSUE TITLE
Stationary Guardian causes jitter on AMD.

### ISSUE THREAD

**Issue by andy-d1969** [alvr-org/ALVR#708]
Roomscale Guardian is smooth. Until 8146ff1c it was the other way around.
Hope there is an easy way to fix the jitter for stationary Guardian setups.

**Comment by Espionage724** [comment]
Could you please clarify this more? How do you switch between Stationary and Roomscale guardians? Do you need to set-up a Guardian through SteamVR at all?

**Comment by zarik5** [comment]
The playspace sync has been rewritten. It is not the cause of the jitter. This is a problem at SteamVR level, which will be fixed upstream.
