### ISSUE TITLE
ALVR Windows client closes itself after a few seconds

### ISSUE THREAD

**Issue by 5TXdYWK** [alvr-org/ALVR#710]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Seems to be the same issue as #644. Installed ALVR for Windows, open it, it opens and closes after just a few seconds, no matter what I do in it.
Tried registering it with SteamVR, and it does open when I launch SteamVR, but doesn't solve the issue.
Crash log is empty.

#### Environement

3700X, 2070S, Quest 2
Latest stable and nightly ALVR, latest SteamVR. Also tried ALVR portable, same issue.
Win10 19042

**Comment by xzkeee** [comment]
have this issue too
