### ISSUE TITLE
IpropertyStore:GetValue error

### ISSUE THREAD

**Issue by jordex69** [alvr-org/ALVR#723]
[
![screenshot](https://user-images.githubusercontent.com/82546058/124009985-7c176b80-d99b-11eb-8e16-acbbe90a1011.png)
](url)

my buddy keeps getting this error

**Comment by ckiee** [comment]
You can join our [discord server](https://discord.com/invite/alvr) for help but I've never seen this before and I searched channel history in Discord and there's nothing.
