### ISSUE TITLE
Nightly server attempts to send video to the (now incompatible) stable client

### ISSUE THREAD

**Issue by demencia89** [alvr-org/ALVR#727]
[ALVR log](https://github.com/alvr-org/ALVR/files/6765122/ALVR.log)
I installed ALVR from git on Manjaro, Installed Steam VR, set everything up, my device successfuly connects to ALVR but then gets stuck on "The Stream will begin soon. Please wait..."

ALVR Log Attached

**Comment by yackaro** [comment]
Same issue, Are you using an NVidia GPU?
The Linux section of the build guide says that NVidia works with software encoding, but to me it looks like ALVR is trying to use hardware encoding with no option to change it, given it detects that I'm using an NVidia card, with a "This card is most likely compatible" on the OOBE popup.
The other possibility I'm thinking of, is that SteamVR might be trying to load the native ffmpeg, which in Manjaro, doesn't seem to be compiled with vulkan support as I found out the hard way in my own troubleshooting.
I'm not sure which of the two options it is.
Reading your log, what stands out to me the most is line 10: `[INFO]	failed to create VAAPI encoder`. I just looked at the logging on my computer, same issue crops up.
Chances are that I may be missing the mark completely, but I'm trying to connect the dots.
I'm going to try to figure out how to compile my own ffmpeg with vulkan enabled to install at a system level, and I'll see what it does.

**Comment by demencia89** [comment]
That makes a lot of sense. I'll try what you you're gonna try as well and update

**Comment by xytovl** [comment]
The Linux build always tries vaapi first, which fails on nvidia with the info message, then tries software encoding.
The attached log doesn't provide enough information to know which component is failing.

Are you using the nightly client? Stable is not yet able to decode the stream from software encoder.

**Comment by demencia89** [comment]
That could be it too. I'm using the aur package alvr-git.

**Comment by yackaro** [comment]
I've used both the alvr-git and the latest cloned nightly, both have the same problem and the same log.

**Comment by Firobe** [comment]
Can confirm: had the same issue but using the Android client built from source fixed the issue.

**Comment by ckiee** [comment]
Marking as a bug since the server on `master`/nightly thinks it's backwards compatible with the stable client when it is, in fact, not.

**Comment by Killrmemz** [comment]
recent nightly builds and git builds have started showing a behaviour that would suggest that this issue is fixed; I now get an "incompatible client" error when connecting from a stable client to a nightly server, have not tested the other way around though.

**Comment by ckiee** [comment]
@Killrmemz Yep, forgot to close this issue, this was fixed here https://github.com/alvr-org/ALVR/commit/cc3fa3be34b59ad05c4737abe5214d01c59dbda8 :P
