### ISSUE TITLE
MS Edge keep getting pinned to taskbar on launch

### ISSUE THREAD

**Issue by RexTheCapt** [alvr-org/ALVR#735]
# Please follow the general troubleshooting steps first:

- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:
Every single time ALVR is started, MS Edge gets pinned on my taskbar. Does not happen with any other software.

#### Environement

What hardware do you have: CPU, GPU, Audio
  GPU: GTX 1080
  CPU: i7-9900K
  Audio: Razer Kraken TE 7.1
What version of ALVR and SteamVR have you tried. 
 15.2.1
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number
  Version 21H1 (OS Build 19043.1110)

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by ckiee** [comment]
I think this has been documented somewhere but it's been a while since this came up so I'm not sure where, the [Discord server](https://discord.gg/alvr) might have more knowledgeable people on this.

Feel free to reopen if you don't/cannot use Discord.
