### ISSUE TITLE
Option to force or manually switch to software encoding mode

### ISSUE THREAD

**Issue by Killrmemz** [alvr-org/ALVR#742]
In my Nvidia Optimus laptop, on Linux, after installing optimus-manager as mentioned in issue #741 , I have come across another issue.
ALVR does not support hardware encoding on Nvidia GPUs currently, and as a result VAAPI should report a failure on startup before it falls back to software encoding.
Unfortunately for my system, it seems like VAAPI has found some way to not fail, at least according to the lack of reporting it in the logs, and as a result I am getting a black screen to the headset.
I suspect it is trying to render on the Intel GPU even though it is disabled, although even when I switch to Intel graphics only it does the same thing, so it must be a general Intel issue.
A simple solution, at least for until hardware encoding can be properly supported on these GPUs, would be to add an option to bypass hardware encoding.

**Comment by ckiee** [comment]
A temporary patch to work around this issue:

```diff
diff --git a/alvr/server/cpp/platform/linux/EncodePipeline.cpp b/alvr/server/cpp/platform/linux/EncodePipeline.cpp
index a0c1ca08..537fb13d 100644
--- a/alvr/server/cpp/platform/linux/EncodePipeline.cpp
+++ b/alvr/server/cpp/platform/linux/EncodePipeline.cpp
@@ -65,12 +65,6 @@ void filter_NAL(const uint8_t* input, size_t input_size, std::vector<uint8_t> &o

 std::unique_ptr<alvr::EncodePipeline> alvr::EncodePipeline::Create(std::vector<VkFrame> &input_frames, VkFrameCtx &vk_frame_ctx)
 {
-  try {
-    return std::make_unique<alvr::EncodePipelineVAAPI>(input_frames, vk_frame_ctx);
-  } catch (...)
-  {
-    Info("failed to create VAAPI encoder");
-  }
   return std::make_unique<alvr::EncodePipelineSW>(input_frames, vk_frame_ctx);
 }

```
