### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by zero199o** [alvr-org/ALVR#744]
# Please follow the general troubleshooting steps first:

- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Please replace this line with a brief summary of your issue

#### Environement

What hardware do you have: CPU, GPU, Audio
What version of ALVR and SteamVR have you tried. 
Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.
<img width="333" alt="螢幕擷取畫面 2021-07-19 223755" src="https://user-images.githubusercontent.com/87776088/126530008-db56d60a-bf39-4b0f-bb41-377b3d40a112.png">

**Comment by JosNun** [comment]
@zero199o Please provide us with some more information by filling out the issue template so we can help you better. If you'd like, you can drop in our [discord server](https://discord.com/alvr), and we'd be happy to help you find a solution.

**Comment by zero199o** [comment]
> # Please follow the general troubleshooting steps first:
> * [ ]  I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
> * [ ]  I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
> 
> If your issue is about games not working, please open an issue for every game and list the game in the title.
> 
> ### Bug reports:
> Please replace this line with a brief summary of your issue
> 
> #### Environement
> What hardware do you have: CPU, GPU, Audio
> What version of ALVR and SteamVR have you tried.
> Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number
> 
> ### Features:
> **Please note by far the quickest way to get a new feature is to file a Pull Request.**
> 
> We will consider your request but it may be closed if it's something we're not actively planning to work on.
> <img alt="螢幕擷取畫面 2021-07-19 223755" width="333" src="https://user-images.githubusercontent.com/87776088/126530008-db56d60a-bf39-4b0f-bb41-377b3d40a112.png">
