### ISSUE TITLE
[16.0.0-rc1] [Windows] Intermittent client crashing on server disconnect/restart

### ISSUE THREAD

**Issue by Killrmemz** [alvr-org/ALVR#748]
I don't know where to get client logs, so you just have to take my word. Sometimes it crashes, sometimes it doesn't, but only on disconnect. Will post logs if the log directory is pointed out to me, assuming the client does log to a file.

**Comment by ckiee** [comment]
Can you reproduce this on 15.2.1? Also, you can use `adb logcat` to get the log firehose that is in Android.

**Comment by mittorn** [comment]
Client crashes sometimes when disconnecting on linux too

**Comment by ckiee** [comment]
@mittorn Can you provide logs? `adb logcat`

**Comment by mittorn** [comment]
Crashed again after tracking failure
https://pastebin.com/yvynN4UY

**Comment by ckiee** [comment]
@mittorn I reverted https://github.com/alvr-org/ALVR/commit/16a08d97a49cead5c517b6b0c2c96eb5d3c33bfa which I think is a likely suspect. A nightly build is [now running](https://github.com/alvr-org/ALVR-nightly/actions/runs/1069503691).

**Comment by mittorn** [comment]
Crash seems to be fixed, but manual build from git become incompatible with nightly client. I temporary disabled version check
