### ISSUE TITLE
Major latancey issue

### ISSUE THREAD

**Issue by coolbossinator** [alvr-org/ALVR#749]
### Bug reports:

Whenever I open a game it runs fine, but when something loads or a lot of rendering goes on the latency goes through the roof (in the millions) and if I restart the ALVR app (on quest) it crashes on the first launch but on the second it goes back to the delay. 

--------------------------------------------------------------------------------

#### Environement:

CPU: Intel core ih-9400, GPU: GeForce RTX 2060, 16 GB Memory
Version 15.2.1 and the latest version of Steam VR
I am on the latest windows version.

--------------------------------------------------------------------------------

Logs:

#{ "id": "Statistics", "data": {"totalPackets": 1613988, "packetRate": 2708, "packetsLostTotal": 0, "packetsLostPerSecond": 0, "totalSent": 2244, "sentRate": 30.158328, "totalLatency": 2950109.499000, "encodeLatency": 4.563000, "encodeLatencyMax": 6.105000, "transportLatency": 15227.191000, "decodeLatency": 5.051000, "fecPercentage": 5, "fecFailureTotal": 0, "fecFailureInSecond": 0, "clientFPS": 24, "serverFPS": 59} }#

#{"id":"ClientDisconnected"}#

Client disconnected. Cause: At alvr\common\src\sockets\control_socket.rs:32

--------------------------------------------------------------------------------

There would be more but it just repeats that /\

**Comment by JakeDevs** [comment]
Also having this issue
