### ISSUE TITLE
ALVR Freezes/Crashes KDE Plasma.

### ISSUE THREAD

**Issue by MathiewMay** [alvr-org/ALVR#755]
Sometimes after closing SteamVR or the ALVR web app, it will Freeze/Crash KDE Plasma to the point where i need to restart my entire computer to fix it. 
I am not actually sure if its Freezing/Crashing KDE Plasma or just my entire PC to be honest.

Also another small issues on arch, after restarting my pc the ALVR web app will be white (empty) until your rebuild the pkg.

Here is more info about my setup
Distro: Manjaro 5.10.53-1
KDE Plasma Version: 5.22.4
ALVR Version: v16.0.0-rc2 
SteamVR Version: 1.18.7

**Comment by mittorn** [comment]
what GPU used? mesa version? kernel version?

**Comment by MathiewMay** [comment]
> what GPU used? mesa version? kernel version?

 I have a RTX 3080 and the kernel version is stated above, also i have no such thing as mesa if i do i have no idea what it is.

**Comment by Kirottu** [comment]
For me I have to make sure to disable compositor before ALVR, failing to do so causes a lot of issues. Restarting kwin is also sometimes required to make stuff work again.
