### ISSUE TITLE
H264 encoding doesn't work with AMD GPU

### ISSUE THREAD

**Issue by Valneo** [alvr-org/ALVR#764]
Hi,

I've got an AMD 5600XT GPU that I can seem to make work with H264 encoding (HEVC works fine but for some other reason the encoding bitrate is stuck around 20ish MBps whatever the value I put in settings -> video looks like poop)

What's weird is that on older driver it does work but not on the Adrenalin ones. When starting streaming with the current latest stable drivers (21.6.1) it immediately crashes on the headset.

#### Environement

GPU : AMD 5600XT
CPU : Ryzen 5 3600XT
MB : ASUS B550M-A Wifi
Steam VR beta 1.19.6
ALVR 15.2.1 (tried on latest beta, same issue)

**Comment by hyperboy124** [comment]
looks like a similar issue is also present on an RX 580 gpu ... rolling driver version back to 21.3.2 seems to fix it
