### ISSUE TITLE
error: ‘const struct alvr::VkContext::dispatch’ has no member named ‘getVkHeaderVersion’

### ISSUE THREAD

**Issue by matteoturini** [alvr-org/ALVR#768]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

ALVR isn't building, complaining about missing member named `getVkHeaderVersion`.

Log: https://paste.gg/p/anonymous/aefe2bce42824ce5b461f68e0e21a6fe

#### Environement

What hardware do you have: i7 8086k, GTK 1060, Arch Linux
What version of ALVR and SteamVR have you tried. latest git
Do you have the latest Windows updates?: N/A

**Comment by reedlove** [comment]
It has something to do with "NDEBUG" not being defined during the build process which is preventing "vulkan.hpp" from creating the wrapper function/method "getVkHeaderVersion". I am unfamiliar with Rust, outside of a quick tutorial I tried when it first came out a million years ago, so I don't know how they're scripting their build process. I assume that passing "-DNDEBUG" to the compiler command "Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "cpp/openvr/headers" "-I" "cpp" "-I" "/home/reedlove/Downloads/ALVR/alvr/server/../../deps/ubuntu/FFmpeg-n4.4/" "-Wall" "-Wextra" "-isystemcpp/openvr/headers" "-std=c++17" "-DAVCODEC_MAJOR=58" "-DAVUTIL_MAJOR=56" "-DAVFILTER_MAJOR=7" "-DSWSCALE_MAJOR=5" "-DLIBRARY_LOADER_AVCODEC_LOADER_H_DLOPEN" "-DLIBRARY_LOADER_AVUTIL_LOADER_H_DLOPEN" "-DLIBRARY_LOADER_AVFILTER_LOADER_H_DLOPEN" "-DLIBRARY_LOADER_SWSCALE_LOADER_H_DLOPEN" "-o" "/home/reedlove/Downloads/ALVR/target/release/build/alvr_server-2d4362503638ae72/out/cpp/platform/linux/ffmpeg_helper.o" "-c" "cpp/platform/linux/ffmpeg_helper.cpp" with args "c++" did not execute successfully (status code exit status: 1)." might fix the problem without having to actually modify "vulkan.hpp" header files to force NDEBUG to be declared.

Anyway. I'm having the same problem and am trying to fix it myself, unfortunately I won't have time until tonight to really dig in to it.

**Comment by matteoturini** [comment]
> It has something to do with "NDEBUG" being defined during the build process which is preventing "vulkan.hpp" from creating the wrapper function/method "getVkHeaderVersion". I am unfamiliar with Rust, outside of a quick tutorial I tried when it first came out a million years ago, so I don't know how they're scripting their build process.
> 
> Anyway. I'm having the same problem and am trying to fix it myself, unfortunately I won't have time until tonight to really dig in to it.
> 
> PS
> When I first posted my comment here, I accidentally reversed my position on what I thought the problem was (coffee hadn't hit the bloodstream yet). I have now revised my comment to reflect what I was trying to say.

fixed by downgrading

quick workaround for the moment

**Comment by samoylenkodmitry** [comment]
> fixed by downgrading
@matteoturini what are you downgraded? I'm also on Arch (btw) and have the same problem :)

**Comment by matteoturini** [comment]
Earliest 1.2.X version did it for me.

**Comment by samoylenkodmitry** [comment]
@matteoturini 
> Earliest 1.2.X version did it for me.
1.2.X of what? :)

**Comment by matteoturini** [comment]
> @matteoturini 
> > Earliest 1.2.X version did it for me.
> 1.2.X of what? :)
> 

Sorry, 1.2.X version of Vulkan-headers.

**Comment by samoylenkodmitry** [comment]
> 1.2.X version of Vulkan-headers.
Thanks! 
I can't build with the same error message.

My system has:
```
rustc -V
rustc 1.54.0 (a178d0322 2021-07-26)
```
And `vulkan-headers`:
```
 extra/vulkan-headers 1:1.2.186-1 (733.3 KiB 12.6 MiB) [vulkan-devel] (Installed)
```
I tried also with `vulkan-headers-git` with same result...
@matteoturini do you build a custom release of vulkan-headers from its repository? https://github.com/KhronosGroup/Vulkan-Headers

**Comment by matteoturini** [comment]
No, I used standard Arch packages. To downgrade, I used the `downgrade` script from the AUR.

**Comment by samoylenkodmitry** [comment]
> No, I used standard Arch packages. To downgrade, I used the `downgrade` script from the AUR.

Finally, It worked:

1. `sudo downgrade vulkan-headers`
2. choose version `1.2.131`
3. `yay alvr`

Thank you!

**Comment by matteoturini** [comment]
Now the REAL question is: why does it not work on the new versions of vulkan-headers?

**Comment by cooperra** [comment]
Fellow Arch user reporting in. This update broke it for me:
[2021-08-20T23:23:20-0400] [ALPM] upgraded vulkan-headers (1:1.2.184-1 -> 1:1.2.187-1)

Since that span of versions was so small, I went ahead and did some testing. Here are the results:
1.2.184 -- good
**1.2.185 -- good**
1.2.186 -- broken
1.2.187 -- broken

That should narrow it down.

In case there's more to it, here're my other vulkan packages:
```
$ pacman -Qs vulkan
local/lib32-vulkan-icd-loader 1.2.184-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/lib32-vulkan-radeon 21.2.1-1
    Radeon's Vulkan mesa driver (32-bit)
local/lib32-vulkan-validation-layers 1.2.184-1
    Vulkan Validation Layers (32-bit)
local/spirv-tools 2021.1-1 (vulkan-devel)
    API and commands for processing SPIR-V modules
local/vulkan-headers 1:1.2.185-1 (vulkan-devel)
    Vulkan header files
local/vulkan-icd-loader 1.2.187-1
    Vulkan Installable Client Driver (ICD) Loader
local/vulkan-radeon 21.2.1-1
    Radeon's Vulkan mesa driver
local/vulkan-tools 1.2.184-1 (vulkan-devel)
    Vulkan Utilities and Tools
```

**Comment by cooperra** [comment]
@matteoturini, @samoylenkodmitry Did you all get ALVR running properly after using the downgrade workaround? I'm still having major problems even though it compiled successfully. Not sure if it's the workaround or just my environment. This is my first time actually running ALVR.

**Comment by matteoturini** [comment]
> @matteoturini, @samoylenkodmitry Did you all get ALVR running properly after using the downgrade workaround? I'm still having major problems even though it compiled successfully. Not sure if it's the workaround or just my environment. This is my first time actually running ALVR.

It doesn't have hardware acceleration. That's where most of your problems might be coming from.

**Comment by reedlove** [comment]
Honestly. I ended up returning my Oculus Quest 2 because the 128 GB model was on the horizon for the same price. Then, I decided to go for broke and get a valve index. The only thing that I can say is that The conditions in which "getVkHeaderVersion" gets defined has changed. Either "vulkan.hpp" needs to be modified or the ALVR code needs to not use that function to determine the version.

**Comment by samoylenkodmitry** [comment]
> @matteoturini, @samoylenkodmitry Did you all get ALVR running properly after using the downgrade workaround? 
For me it works mostly great: image quality and fps is good. The main remaining issue is that head tracking is somewhat jittery and too sensitive.
https://media.discordapp.net/attachments/720639114705240135/881127641707606026/head_track_steam_vr.mp4

**Comment by matteoturini** [comment]
> > @matteoturini, @samoylenkodmitry Did you all get ALVR running properly after using the downgrade workaround?
> 
>  
> For me it works mostly great: image quality and fps is good. The main remaining issue is that head tracking is somewhat jittery and too sensitive.
> https://media.discordapp.net/attachments/720639114705240135/881127641707606026/head_track_steam_vr.mp4

Oh, your GPU probably supports VAAPI then.

**Comment by samoylenkodmitry** [comment]
> @matteoturini
> Oh, your GPU probably supports VAAPI then.

Fyi, my system config is:

```
Kernel: x86_64 Linux 5.13.13-xanmod1-1
CPU: AMD Ryzen 9 3950X 16-Core @ 32x 3.5GHz
GPU: NVIDIA GeForce RTX 2070

➜  ~ pacman -Qs vulkan
local/ffmpeg-vulkan 2:4.4-4
    Complete solution to record, convert and stream audio and video
local/lib32-nvidia-utils 470.63.01-1
    NVIDIA drivers utilities (32-bit)
local/lib32-vulkan-icd-loader 1.2.184-1
    Vulkan Installable Client Driver (ICD) Loader (32-bit)
local/nvidia-utils-performance 470.63.01-3
    NVIDIA drivers utilities and libraries
local/spirv-tools 2021.1-1 (vulkan-devel)
    API and commands for processing SPIR-V modules
local/vulkan-headers 1:1.2.188-1 (vulkan-devel)
    Vulkan header files
local/vulkan-icd-loader 1.2.188-1
    Vulkan Installable Client Driver (ICD) Loader

```

**Comment by samoylenkodmitry** [comment]
Also, I think the problem `‘const struct alvr::VkContext::dispatch’ has no member named ‘getVkHeaderVersion’` is more likely problem of the Vulkan library itself. 

Comparing files `/usr/include/vulkan/vulkan_funcs.hpp` from version `1.2.185` with the same file of `1.2.188` makes it clear there is a new assertion in this file: `VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );` that is absent in `185` version.

**Comment by matteoturini** [comment]
> Also, I think the problem `‘const struct alvr::VkContext::dispatch’ has no member named ‘getVkHeaderVersion’` is more likely problem of the Vulkan library itself. 
> 
> Comparing files `/usr/include/vulkan/vulkan_funcs.hpp` from version `1.2.185` with the same file of `1.2.188` makes it clear there is a new assertion in this file: `VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );` that is absent in `185` version.

Hmm, could it also be because ALVR is not defining something?

**Comment by cooperra** [comment]
So, the package maintainer finally updated all the Arch Vulkan packages to 190 (except 191 for vulkan-headers). This still didn't fix the problem like I thought it would, so I poked around in the code. I found that the struct with the missing `getVkHeaderVersion` method was actually defined in ALVR, so I added the method myself. Now everything compiles and runs. The patch is in #789.

**Comment by samoylenkodmitry** [comment]
@cooperra finally! Now, we can install alvr without downgrading vulkan-headers.
