### ISSUE TITLE
Low client fps. 

### ISSUE THREAD

**Issue by MotyaRolla** [alvr-org/ALVR#769]
Using Wifi6 5ghz with Quest 2.

Impossible to play. Game on screen is stable but in the helmet picture laggy and unplayable.

Trying to use different bitrate, restarting computer and quest.

#### Environement

What hardware do you have: Ryzen 5 3600x, Rtx 3060ti, Windows 11
What version of ALVR and SteamVR have you tried. Latest version
Do you have the latest Windows updates? Windows 11 21H1

![image](https://user-images.githubusercontent.com/65126216/129593298-af8cd868-ea92-408a-a1e0-34725be123bd.png)

**Comment by chiwangnvp** [comment]
Could you change the graph language into English?

**Comment by Firepal** [comment]
- "Transport latency" is 21000ms (or rather 21 seconds)
- Unlisted latency is 21000 - 151400 = 130400ms (or 2 minutes)
- Server FPS is perfect, client (Quest) FPS is really low
- Bitrate seems to be ~100Mbps

Try lowering the bitrate to something like 30Mbps, or switching to `Throttled UDP` in "Connection" tab.

**Comment by Firepal** [comment]
Probably a Wi-Fi connection issue. Possibly Windows 11 too
