### ISSUE TITLE
Error Building in arch linux from aur package list.

### ISSUE THREAD

**Issue by Andreas711** [alvr-org/ALVR#770]
I git cloned the pkgbuild version and every time I go to build it, it just spits out an error saying:

*
Compiling alvr_server v16.0.0-rc2 (/home/andreas/alvr-git/src/alvr/alvr/server)
The following warnings were emitted during compilation:

warning: In file included from /usr/include/c++/11.1.0/cassert:44,
warning:                  from /usr/include/vulkan/vulkan.hpp:75,
warning:                  from cpp/platform/linux/ffmpeg_helper.h:3,
warning:                  from cpp/platform/linux/ffmpeg_helper.cpp:1:
warning: /usr/include/vulkan/vulkan_funcs.hpp: In instantiation of ‘vk::ResultValueType<void>::type vk::Device::importSemaphoreFdKHR(const vk::ImportSemaphoreFdInfoKHR&, const Dispatch&) const [with Dispatch = alvr::VkContext::dispatch; vk::ResultValueType<void>::type = void]’:
warning: cpp/platform/linux/ffmpeg_helper.cpp:143:30:   required from here
warning: /usr/include/vulkan/vulkan_funcs.hpp:11062:5: error: ‘const struct alvr::VkContext::dispatch’ has no member named ‘getVkHeaderVersion’
warning: 11062 |     VULKAN_HPP_ASSERT( d.getVkHeaderVersion() == VK_HEADER_VERSION );
warning:       |     ^~~~~~~~~~~~~~~~~

error: failed to run custom build command for `alvr_server v16.0.0-rc2 (/home/andreas/alvr-git/src/alvr/alvr/server)`

Caused by:
  process didn't exit successfully: `/home/andreas/alvr-git/src/alvr/target/release/build/alvr_server-bedd184912272fe5/build-script-build` (exit status: 1) 
*

I honestly have no idea what to do.
please help.

**Comment by lmarianski** [comment]
Did you install ffmpeg-vulkan from the AUR?

**Comment by matteoturini** [comment]
Downgrade vulkan-headers to earliest 1.2 version.

You can use `downgrade` script from the aur.

**Comment by Andreas711** [comment]
> Did you install ffmpeg-vulkan from the AUR?

Every time I do that I get an error with that saying ERROR: libglslang not found whenever I go to install that.

Everything I do I just hit a bloody roadblock and it's so infuriating. ffmpeg-vulkan just doesn't install.

**Comment by Andreas711** [comment]
Ok I got the same error but I actually managed to install ffmpeg-vulkan I installed the git version of the glslang library and that worked. Still stuck, im going to try and downgrade vulkan-headers now.

**Comment by matteoturini** [comment]
Edit the PKGBUILD and remove bundle ffmpeg flag

**Comment by Andreas711** [comment]
> Downgrade vulkan-headers to earliest 1.2 version.
> 
> You can use `downgrade` script from the aur.

I tried this and IT WORKS right now as i type this it's prompting to install meaning it worked!
