### ISSUE TITLE
 We had adapted our project compatible with ALVR, can we upload it?

### ISSUE THREAD

**Issue by chengzeyuan** [alvr-org/ALVR#775]
Hello, we are a vr company in China. We had compatible with our products for the ALVR. The stability is similar to quest2. The delay is about 50-60ms. The network transmission and codec use the logic of ALVR. Pay attention to the PC-side game stream. At present, the optimization of the performance and stability of ALVR is in progress. The professional team will continue to update it, mainly in the following directions:
1. The time delay is currently 50-60ms, optimized for the depth of the codec direction, the goal is about 40ms (we plan to cut the current picture of the left and right eyes into two frames for transmission<see the picture for details>, because the images of the left and right eyes are very similar , The buffer can be reduced by about 50% through inter-frame prediction, and the network transmission delay will be greatly improved at the same time)
![image](https://user-images.githubusercontent.com/86513446/130895820-c39a0098-f1a2-4acf-bb76-adddbadadcc3.png)
2. The network, it is currently 2.4G/5G, we may consider stronger wifi modules in the wifi module selection, for example, the protocol 802.11 ad, 802.11 ay, the frequency is 60G
3. Optimized for stability, the target can quickly and automatically connect after opening the apk;
If you have better optimization directions or suggestions, we can discuss them together, thank you!

**Comment by yingtian991221** [comment]
@zarik5 @chengzeyuan 
Hi, you have mentioned the encoder/decoder idle time, which is now taking a large fraction of my latency (15ms/50ms). Could you explain more about what is this idle time? Since things should work in a pipeline strategy, even one component have to wait for another component (like decode wait for transfer), as long as the transfer is working, the decoder shouldn't be counted as idle?

**Comment by zarik5** [comment]
Idle time is controlled by the VR runtime, to sync with the display refresh, aka vsync. In ALVR v18 stable there is a server idle time and that is wrongly counted. Actually the server sends the images to the encoder as soon as they are received from the VR game. The client idle time instead is correctly counted. Once we switch to OpenXR we should be able to drastically reduce the client idle time with phase sync, basically we get some help from OpenXR to time frames so they align more with the vsyncs and reduce queue latency.
