### ISSUE TITLE
Massive slowdowns since v.16.0.0

### ISSUE THREAD

**Issue by orty** [alvr-org/ALVR#791]
# Please follow the general troubleshooting steps first:

- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

I experience massive slowdowns in both Steam VR virtual environment and games since I downloaded the latest stable v.16.0.0. This was seamlessly working with the v.15.2.1 (and I downgraded my ALVR server/client to this version again to validate it was version-related and it works great with this old one).
The slowdowns seem to be consistently coming each every 10 seconds. i.e. in Steam VR home, I can see my hands moving in a fluid way, and then there is a huge frame rate drop for 2-3 seconds with a delay between my real moves and the virtual hands, then it goes back to normal for around 10 seconds, and so on.
Also, in the client (within the headset, the white grid environment) while it is waiting for the server to start, head moves are not tracked realtime. I can see dark on sides if I move my head to fast, then the focus goes back on center.

Again, all of this just disappears if I downgrade back to v.15.2.1.

#### Environement

What hardware do you have: CPU, GPU, Audio

- AMD FX(tm)-8350 Eight-Core Processor 4.00 GHz
- 16 Gb RAM (2x DDR3L)
- GeForce TX 1060 6GB
- ASRock 970M Pro3 integrated audio (Realtek ALC892)

What version of ALVR and SteamVR have you tried. 

- SteamVR - up-to-date
- ALVR - 15.2.1 & 16.0.0

Do you have the latest Windows updates? Run "winver" in Windows 10 to get the version number

- Windows - up-to-date (v 20H2 - 19042.1165)

**Comment by rubjonny** [comment]
I had the same issue and also had to roll back to an earlier version to fix it, hardware:
Ryzen 5 3600
Asus X570-P
16GB RAM
Geforce GTX 1060 6GB

**Comment by Yang-PM** [comment]
The reconnection was slow when USING V.16.0.0, but when I switched back to V.15.1.1, the quest reconnection was quick before it was restored.

**Comment by sctanf** [comment]
What does the latency graph show?
Is there any improvement if you switch to nightly? (reset your settings if you test nightly)

**Comment by rubjonny** [comment]
sorry I never got round to trying this till now, but just downloaded the latest nightly and seems to be fixed :)
