### ISSUE TITLE
why I can see four different threads to get tracking info in the client side

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#804]
![image](https://user-images.githubusercontent.com/45933755/134854239-3a37474d-7358-42e3-b212-c40d2f26a381.png)
_**Time spent total**_ is log I added in the setControllerInfo func in the client. Here we got four different thread ID 2994 / 2992 / 2991 / 2995

**Comment by chiwangnvp** [comment]
The need to get tracking info is started by Rust below:
<img width="346" alt="lALPDhJzxtPgWMjMus0Csw_691_186" src="https://user-images.githubusercontent.com/45933755/134855292-23e3b019-3996-4503-8ff8-b713fc615586.png">
<img width="395" alt="lALPDhJzxtPZZpnM5s0DFg_790_230" src="https://user-images.githubusercontent.com/45933755/134855305-63534343-abbc-4940-bbc1-a2daad4202bf.png">

**Comment by zarik5** [comment]
That spaghetti code is gonna go as soon as we finish the OpenXR client.

**Comment by zarik5** [comment]
That's because Tokio (the async runtime) runs the code in the thread it wants. Once we rewrite the client to OpenXR we are going to limit async code and have more control of the threads.

**Comment by chiwangnvp** [comment]
Thanks a lot
