### ISSUE TITLE
Logcat renderLatency2 is too big in the alvr client side, why ?

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#819]
![image](https://user-images.githubusercontent.com/45933755/136363569-cd8ebebc-27a2-4686-a4ad-35ca9ea79e3d.png)

**Comment by chiwangnvp** [comment]
Our own platform, is there a problem ?

**Comment by sctanf** [comment]
Maybe the value is too near zero and causes issues to display. renderLatency2 is (submit - rendered2) in the code, and they are placed closely together that the difference is too small.

**Comment by chiwangnvp** [comment]
Thank you, we will check that
