### ISSUE TITLE
[Linux] ALVR server random freezes

### ISSUE THREAD

**Issue by Mantas-2155X** [alvr-org/ALVR#823]
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Issue:

Random server freezes happen while using ALVR. There are no exact steps which can be used to replicate the freeze. It is purely random - freezes just when you connect to the server, randomly in the game, sometimes does not freeze for a good while. 
The only way to recover from it is to restart the ALVR server entirely, which means you have to close the game and restart SteamVR.

Affected versions: `ALVR v16.0.0-rc1` and up

#### Cause:

After [doing some testing](https://discord.com/channels/720612397580025886/776913132672516106/896494110771400754) I found that the problem is caused by commit [a984720](https://github.com/alvr-org/ALVR/commit/a9847202fa0035018442a20f0da6cb867f758b90). 
Xytovl on discord indicated that it might be caused by the swapchain being recreated, new shared memory structure being created and ALVR not being aware of it ([message](https://discord.com/channels/720612397580025886/776913132672516106/896665402703224883)).

#### Temporary solution:
As of right now, I have tried messing around with the shm commit but was unable to resolve the issue. 
Until it is properly fixed, I think that reverting the shm commit is a possible solution to this as it does not seem to cause problems and resolves the random freezes that make gameplay very annoying.

To test the solution, patch [revert-shm-patch.zip](https://github.com/alvr-org/ALVR/files/7323749/revert-shm-patch.zip) to ALVR v16.0.0

#### Environment:

Ryzen 5 5600X,
AMD RX 5700 XT

ALVR v16.0.0 (all versions after [a984720](https://github.com/alvr-org/ALVR/commit/a9847202fa0035018442a20f0da6cb867f758b90)),
Kubuntu 21.04

#### Possibly related:
#811 
#782

**Comment by andy-d1969** [comment]
I can confirm the freezes and they are the most annoying issue in ALVR for me. The revert-shm-patch works fine here and my first impression after a few hours is that ALVR runs much more stable with it. It should be merged until a better solution is found.
Manjaro, Ryzen 3900X, RX 6900 XT

**Comment by Mantas-2155X** [comment]
Fixed by #838
