### ISSUE TITLE
Oculus Quest 1 Controller Models

### ISSUE THREAD

**Issue by max-lv** [alvr-org/ALVR#828]
Right now you can choose between several "Controller Emulation Modes".
Is it possible to add Quest 1 controllers option (model). So it shows up in Steam VR home?

**Comment by sctanf** [comment]
SteamVR home only shows CV1 controllers, the models should be correct in SteamVR void

**Comment by max-lv** [comment]
Sorry for my late response.
Here are some screenshots:

I might be wrong in my terminology is this SteamVR void? I thought this was Steam VR home. 
<img src="https://user-images.githubusercontent.com/8313771/137620110-de0e623e-3aaa-42e2-96e2-624c263b2a1e.jpg" width="50%" height="50%">

And here how it looks in Oculus Quest UI (I guess just to prove it is indeed Q1):
<img src="https://user-images.githubusercontent.com/8313771/137620114-79ef5c5a-f89b-4a6d-8426-ec72ddff1f79.jpg" width="50%" height="50%">

This is ALVR v15.2.1, but I get same result in v16.0.0

I've attached my session.json (v15.2.1), maybe it will help.
PS: I had to zip it as github won't allow me to attach *.json file.
[session.zip](https://github.com/alvr-org/ALVR/files/7359528/session.zip)

**Comment by sctanf** [comment]
Ah okay. Then Rift S controller emulation should work (Same touch controllers as Quest 1)

**Comment by max-lv** [comment]
Thanks! That solved my issue:
<img src="https://user-images.githubusercontent.com/8313771/137636669-a0702d25-1317-4271-8371-cf6e1fa7b526.jpg" width="50%" height="50%"/>

Maybe this option should be renamed to "Oculus Rift S / Quest 1" and "Oculus Rift S / Quest 1 (no handtracking pinch)"?

I see this can be changed at `./dashboard/js/app/customSettings.js`, but I also saw your are in a process of migrating to new UI (SixtyFPS). So I'm not sure if it makes sense to make changes to current UI.

If you approve renaming I can submit a PR ;)
