### ISSUE TITLE
Is there a reference table for encodeLatency ?

### ISSUE THREAD

**Issue by chengzeyuan** [alvr-org/ALVR#831]
I found that the encodeLatency is different on computers with different configurations. When the parameters are different on the same device, different encodeLatency  will be obtained. Is there a reference table for encodeLatency ?

**Comment by chiwangnvp** [comment]
Same question, and sometimes encodeLatency in the GTX 3070 is about 30-40ms, is too long, isn't it?

**Comment by sctanf** [comment]
There is a table of user-submitted performance statistics [here](https://docs.google.com/spreadsheets/d/1CYIyzQ2l-sZKSgOTp0iweR_lg716AbEktMUngwY--BQ)

However they might be a little outdated
