### ISSUE TITLE
Valve Index emulation still needs work.

### ISSUE THREAD

**Issue by IZZYGamez361** [alvr-org/ALVR#847]
After testing out finger tracking in VRChat, I have found some issues with how the controllers emulate the Valve Index.

The overall emulation is great, but grip does not work with the controllers in hand.

When I go to use the hand tracking alone, All buttons wok but the thumb sticks don't. The tracking itself is great, but it's the only thing stopping me from playing without the controllers.

**Comment by MaeiMaei** [comment]
Had a similar issue, there's a fix courtesy of BK54 on the Discord Server telling me.

Go into VRC, set SteamVR bindings and ![unknown-89.png](https://user-images.githubusercontent.com/36708517/139521157-8d2ae829-60e4-4784-bbe2-9a295ce3b594.png)
bind your controllers to this on each side.

Emphasis on
Use as Button
Click: Grab

**Comment by IZZYGamez361** [comment]
> Had a similar issue, there's a fix courtesy of BK54 on the Discord Server telling me.
> 
> Go into VRC, set SteamVR bindings and ![unknown-89.png](https://user-images.githubusercontent.com/36708517/139521157-8d2ae829-60e4-4784-bbe2-9a295ce3b594.png) bind your controllers to this on each side.

I'll set this up tomorrow. Is there a way to fix me not being able to move?
