### ISSUE TITLE
After ALVR client connected to server the client show only grey rectangle with grey border.

### ISSUE THREAD

**Issue by NTMan** [alvr-org/ALVR#849]
### Bug description:

After ALVR client connected to server the client show only grey rectangle with grey border.
I use binary client from here https://github.com/alvr-org/ALVR/releases/download/v16.0.0/alvr_client_oculus_quest.apk and server builded from master branch, because build from tag [ended with error](https://github.com/alvr-org/ALVR/issues/830).
Demonstration: https://youtu.be/K_ooTgAuFs8
[build.log](https://github.com/alvr-org/ALVR/files/7450205/build.log)

#### Environement

What hardware do you have:
- CPU: AMD Ryzen 3950X
- GPU: AMD Radeon 6900XT
- HMD: Oculus Quest 2

What version of ALVR and SteamVR have you tried. 
- ALVR client: v16.0.0
- ALVR server: master branch.
- SteamVR: 1.20.4

**Comment by Incuh** [comment]
I am having the same issue

This issue has only existed for at most, 1 - 2 weeks

I'm going down the commit list and trying all verified commits until I find a working one

**Comment by Incuh** [comment]
f8e1a21cc84f03e64ccd9a7eed3c6da79f467780 (https://github.com/alvr-org/ALVR/commit/f8e1a21cc84f03e64ccd9a7eed3c6da79f467780) is functional

Some commit after this caused this issue

**Comment by Incuh** [comment]
This was caused by using an old version of the ALVR Client

Use a newer version of ALVR Nightly client

**Comment by NTMan** [comment]
> This was caused by using an old version of the ALVR Client
> 
> Use a newer version of ALVR Nightly client

Nightly client said that it incompatible with server (Let me remind you that the server is built from the master branch)
Demonstration: https://youtu.be/HZcIU8eADg0

**Comment by sctanf** [comment]
If you build the server, you need to build the client as well.

**Comment by NTMan** [comment]
> If you build the server, you need to build the client as well.

As a Linux user, it is very easy for me to build a package for my distribution.
Only three commands
```
$ spectool -g -R packaging/rpm/alvr.spec
$ rpmbuild -bs packaging/rpm/alvr.spec
$ mock -r fedora-35-x86_64-rpmfusion_free --rebuild ~/rpmbuild/SRPMS/alvr-master-1.0.0.src.rpm --enable-network
```
And I don't even need to install any devel packages, since the build system itself downloads everything into the container and builds it.
I have never built packages for Android and I am not particularly interested in building apk.

Even if I figure out how to build apk, the next step is to add ALVR to the official repo of my distribution. But the distribution build system is definitely not designed to build apk. That is, I can, at least every day, automatically compile and out a new server package, but the client application I cannot build by distribution build system.

Therefore, I propose keep versioning of the API so linux users can easily install the client through SideQuest, and the server part via distribution package manager. It is the best practice for Linux users.

**Comment by NTMan** [comment]
It is very bad that Nightly version check compatibility by using the build date instead of API version.
Nevertheless, if I build the server part today, then tomorrow I could install the ALVR update via SideQuest, and such a bundle begins to work.
But now I am stuck with a new problem.
Please look at my video: https://youtu.be/otOrE9nOSkE
It can be seen that the picture received from the Steam VR very rarely updated. Because of this, everything lags and when I turn head I see there are trails behind the picture which are redrawing on the next picture update.
