### ISSUE TITLE
How to build ALVR server to a ALVR Installer?

### ISSUE THREAD

**Issue by Daktm** [alvr-org/ALVR#850]
Pls help,how to build ALVR server to a ALVR Installer?

**Comment by zarik5** [comment]
Use `cargo xtask publish-server`.

**Comment by Daktm** [comment]
Build Error.
![image](https://user-images.githubusercontent.com/20082687/139656072-f1b3b81c-d800-4f83-8d81-4ffdb6ce2efd.png)


> Use `cargo xtask publish-server`.

**Comment by zarik5** [comment]
This is fixed with the last commit on master.
