### ISSUE TITLE
RX 580 and Linux: SteamVR Home and Beat Saber are laggy, display driver crashes, jitter

### ISSUE THREAD

**Issue by Espionage724** [alvr-org/ALVR#855]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Quick description:

- SteamVR either crashes my display driver, or in the rare occasions it does work, FPS is low and everything (including SteamVR and Beat Saber) is jittery and laggy; basically unusable. I've been told a few times in Discord that this isn't expected.
- GItHub Discussion: https://github.com/alvr-org/ALVR/discussions/860

#### Environment:

- CPU: Ryzen 7 2700X
- GPU: RX 580 (8GB, POLARIS10, DRM 3.42.0, 5.14.15-300.fc35.x86_64, LLVM 13.0.0) (0x67df))
- Audio: Realtek ACL 1120 (ASUS PRIME-X470 PRO built-in, 4.0 speaker channels)
- Headset: Quest 2 (V34)
- OS: Fedora 35 (GNOME 41, tried both Xorg and Wayland)
- Kernel: 5.14.15-300.fc35.x86_64
- glxinfo: [Pastebin](https://pastebin.com/xZT25XhH)
- ALVR: alvr-16.0.0-1.0.0+1635915618+8dc973b6.x86_64 (trae32566)
- SteamVR: 1.20 and linux_v1.14.16

#### Description

- I start Steam (desktop launcher entry), and then launch ALVR (desktop launcher entry), which then automatically starts up SteamVR
- Dashboard is accessible from http://localhost:8082/
- Usually when launching ALVR on my Quest 2, it will say it's restarting the server, freeze the screen on the headset, and then my computer's display will go black, show some purple corruption all over everything for maybe 5-10 seconds, and then blank my display entirely.
- In the rare-event ALVR launches properly on both the headset and computer, SteamVR Home starts, and is jittery and low FPS. I launch Beat Saber on the PC and it appears in the HMD, but it too is a jittery low FPS mess. [Here is a short video showing the low FPS and slow drawing on the sides over USB](https://www.youtube.com/watch?v=Bg2I2xmG55A).
- I've had this happen on Fedora 34, openSUSE Tumbleweed, with the pre-compiled Ubuntu binaries on the Nightly repo, self-compiled, and trae32566's repo

#### Troubleshooting

- Tried different routers (one is known-good with Air Link and Virtual Desktop on Windows)
- Did USB forwarding ([Option 2 - SideQuest](https://github.com/alvr-org/ALVR/wiki/Use-ALVR-through-a-USB-connection#option-2---sidequest), although I typed the two commands as-is with my distro's adb package)
- Tried Xorg and Wayland on GNOME 40 and 41
- Tried stable, beta, and linux_1.14 SteamVR builds

**Comment by 143mailliw** [comment]
I have the same exact problem. Screen blanks, purple & green squares. Pretty normal driver crash for AMDGPU.

I'm on an RX 5700XT.

Occasionally after the crash, journald will log the following output:
```
Dec 25 13:43:30 compooter kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out!
Dec 25 13:43:35 compooter kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out!
Dec 25 13:43:35 compooter kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx_0.0.0 timeout, signaled seq=97985, emitted seq=97987
Dec 25 13:43:35 compooter kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process steamtours pid 23410 thread steamtours:cs0 pid 23535
Dec 25 13:43:35 compooter kernel: amdgpu 0000:2f:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Dec 25 13:43:35 compooter kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KGQ disable failed
Dec 25 13:43:36 compooter kernel: amdgpu 0000:2f:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Dec 25 13:43:36 compooter kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* KCQ disable failed
Dec 25 13:43:36 compooter kernel: [drm:gfx_v10_0_hw_fini [amdgpu]] *ERROR* failed to halt cp gfx
Dec 25 13:43:39 compooter kernel: amdgpu_cs_ioctl: 31 callbacks suppressed
Dec 25 13:43:39 compooter kernel: [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -125!
```

This is also a fairly standard AMDGPU crash log. Looks like the Steam Home is crashing our driver here. Might be something you have to reach out to valve about.
