### ISSUE TITLE
ALVR installer creates additional entries in add/remove programs

### ISSUE THREAD

**Issue by deiteris** [alvr-org/ALVR#856]
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

When updating ALVR (for example, to a new nightly version), the installer creates additional entries in add/remove programs every time I install new update.
![image](https://user-images.githubusercontent.com/6103913/140406285-c00b5781-6968-4682-9c88-8a3e9dcc3b7c.png)

#### Environment

ALVR version: any ALVR nightly
OS: Windows 10 21H1

**Comment by zarik5** [comment]
This is a known bug. We need to change the way the updated works.

**Comment by zarik5** [comment]
I'm thinking we should remove the autoupdater the next major version.

**Comment by Vixea** [comment]
Auto updated was removed correct so this can be closed?

**Comment by Vixea** [comment]
It's been removed, closing.
