### ISSUE TITLE
Everything is green

### ISSUE THREAD

**Issue by TonyGamer** [alvr-org/ALVR#857]
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

When using ALVR on Arch Linux installed from the alvr package on the AUR, the entire screen is green on my Quest 2 except for the very top, which is a light blue color. ALVR also display new frames very laggily, only one every second or two. 

Edit: After looking at the logs, I think that it may have to do with VAAPI hardware encoding, which I cannot seem to get working. Decoding works according to vainfo, but it doesn't show any formats as available for encoding

#### Environment

What hardware do you have: Intel i7 11700F, RTX 3070, Arch Linux, my computer is connected via Ethernet and my Quest device via 5GHz wifi.
ALVR Version: ALVR server v16.0.0
Steam VR Version: STEAMVR 1.20.4
NVidia Drivers: proprietary drivers, version 495.44-3

### Tested ALVR Settings:

Video Settings:
Refresh Rate: 72/90
Video Codec: H.264/HEVC
Video Bitrate: 50/60
Reduce Color Banding: Off/On
Adaptive Bitrate: Off/On
Color Correction: On

Audio Settings:
Stream game audio: Off (On causes an ALSA error)
Stream headset microphone: Off

Headset:
Headset emulation mode: Oculus Quest 2
Controller emulation mode: Valve Index (no handtracking pinch)
Tracking speed: Normal

Connection:
Streaming protocol: TCP/Throttled UDP

**Comment by explodingcamera** [comment]
Same issue happening to me too. Here's my system report if that might be useful too to narrow down the issue. https://gist.github.com/explodingcamera/5b8e64061ea26eefc03f54bf9be5ca2f . I'm running a Ryzen 5800x & RTX3060ti (and also tried it on a rx480).
Also, my logs are constantly spammed with `alvr_server: Setting new IPD to: 0.000000` (multiple times per second).
Happens both when starting through the ALVR app and through steam directly. My AP is known to be good with both Virtual Desktop and Quest Air Link. I don't get any packet loss, but steam vr crashes after about 10 seconds on the green screen.

<details>

![image](https://user-images.githubusercontent.com/10697536/141785492-1eb76a42-ddca-4b24-8720-c4662305a801.png)

</details>
