### ISSUE TITLE
How to build for a new version?

### ISSUE THREAD

**Issue by Daktm** [alvr-org/ALVR#858]
Now ALVR version is 16.0.0. What cargo’s command can change ALVR version?

**Comment by zarik5** [comment]
You can use `cargo xtask bump-versions --version X.X.X` or just change the version in `alvr/common/Cargo.toml`. Can I ask you why you need this?

**Comment by zarik5** [comment]
There have been inappropriate modifications in the wiki and now write access has been disabled. Issues like this will now be promptly closed. If you want to make questions like this, write on the Discord server at https://discord.gg/ALVR
