### ISSUE TITLE
Possible malware infection originating from ALVR

### ISSUE THREAD

**Issue by DigsDev** [alvr-org/ALVR#861]
I first downloaded ALVR v15.2.1 on November 7th, and then upgraded to the latest version through the client. On November 13th my computer was remote controlled after a couple hours of me being afk but nearby. The attackers opened a new chrome tab and typed in "paypal". I shut off my computer and restarted it without internet connection.

I believe the attack was from a program called "client32.exe" also called "NetSupport Client Application" located in a hidden folder called "WinSup" within my "Roaming" folder. I found it by noticing the unfamiliar program was enabled on startup. The remote control software had apparently been installed at the same time as I installed ALVR on November 7th.

**Comment by ckiee** [comment]
There were some [malicious edits](https://github.com/alvr-org/ALVR/wiki/Installation/_history) in the wiki recently: It could be that.

Additionally, there was an `alvr-vr` organization with non-official binaries. Can you check your browser history for the wiki page and `alvr-vr`?

**Comment by DigsDev** [comment]
These are the links I have from the day I downloaded:
https://github.com/alvr-vr
https://github.com/alvr-org/ALVR/wiki/Hand-tracking-controller-bindings
https://github.com/alvr-org/ALVR/wiki/Hand-tracking-controller-bindings
https://github.com/alvr-vr/ALVR/releases
https://github.com/alvr-org/ALVR
https://github.com/alvr-org/ALVR/issues
https://github.com/alvr-org/ALVR/wiki/Installation
https://github.com/alvr-vr/ALVR/releases/tag/v16.0.0
https://github.com/polygraphene/ALVR/issues/679
https://github.com/alvr-org/ALVR/releases
https://github.com/alvr-vr/ALVR/tags
https://github.com/alvr-vr/ALVR
https://github.com/alvr-org/ALVR/releases/tag/v15.1.2

I see the alvr-vr page has been taken down, and that is likely where it came from.

I thought I had removed the malicious software from my computer, but I must not have. My computer is still infected, so I'm working off my phone. Some of my passwords have been compromised, because they reset my Google password. I managed to regain access to my Gmail but don't know how to find or uninstall their remote control software.

**Comment by PaulIRL** [comment]
> These are the links I have from the day I downloaded: https://github.com/alvr-vr https://github.com/alvr-org/ALVR/wiki/Hand-tracking-controller-bindings https://github.com/alvr-org/ALVR/wiki/Hand-tracking-controller-bindings https://github.com/alvr-vr/ALVR/releases https://github.com/alvr-org/ALVR https://github.com/alvr-org/ALVR/issues https://github.com/alvr-org/ALVR/wiki/Installation https://github.com/alvr-vr/ALVR/releases/tag/v16.0.0 [polygraphene/ALVR#679](https://github.com/polygraphene/ALVR/issues/679) https://github.com/alvr-org/ALVR/releases https://github.com/alvr-vr/ALVR/tags https://github.com/alvr-vr/ALVR https://github.com/alvr-org/ALVR/releases/tag/v15.1.2
> 
> I see the alvr-vr page has been taken down, and that is likely where it came from.
> 
> I thought I had removed the malicious software from my computer, but I must not have. My computer is still infected, so I'm working off my phone. Some of my passwords have been compromised, because they reset my Google password. I managed to regain access to my Gmail but don't know how to find or uninstall their remote control software.

I did not get infected but I have a bit of experience with viruses, restart without networking and install something like ccleaner and check file that start up with the computer, check if any looks suspicious, you could also use netlimiter to see what programs connect to the internet, in my opinion, the best thing you can do is reinstall the os

**Comment by sctanf** [comment]
A few years ago I had success with getting rid of malicious software on an old laptop using Malwarebytes in offline mode.
Microsoft Defender should have an option to scan offline as well.

**Comment by Swyter** [comment]
Maybe having an easier to remember GitHub organization name would mitigate these phishing attemps. The differences were subtle.

**Comment by zarik5** [comment]
@Swyter The editing of the Wiki has already been locked to organization members since then.

**Comment by ckiee** [comment]
Seems to be resolved.
