### ISSUE TITLE
ALVR consistently crashing on launch after 5s (hasn't been fixed)

### ISSUE THREAD

**Issue by ItsMePale** [alvr-org/ALVR#862]
Application crashes after 5s after the GUI opens.
crash_log.txt empty.

Found a warning in event viewer
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
and APPID {15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user UMBRA\daleb SID (S-1-5-21-2483201085-4075341960-4090943041-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.

I tried poking around in Component Services but I couldn't find the reference it is pointing to (I guess it's due to the application crashing and Component Services only showing running services.

Could be an issue with services during the installation phase?

Restarting PC seems to remedy the issue for a single instance however if I close ALVR it will simply not remain open again.  Maybe a simple fix to have a minimise or temporarily disable the option to close the application to the system tray instead of the windows shutting down the application completely.

CPU: Ryzen5 3700x
GPU: GTX1070ti 
ALVR 16.0 for the quest 2
SteamVR: 1.20.4
OS: Windows 11 Build 22494.1000

**Comment by ItsMePale** [comment]
Manage to navigate into Settings -> Extra -> Log session to session_log.txt and found this
Failed to init OpenVR client to update Chaperone boundary! Error: 119

**Comment by VerneAsimov** [comment]
I get the same exact error. It's a SteamVR issue but in what way I don't know. The only reliable way to fix this is to restart my PC as of yet.

**Comment by phobos2077** [comment]
The same. App just closes after 5s every time. Any fix/workaround?

**Comment by phobos2077** [comment]
Reinstalling SteamVR fixed the crash on startup. Now I got the point of connecting to a server from headset but server crashes with following error:

Failed to init OpenVR client to update Chaperone boundary! Error: 119

**Comment by esturmovics** [comment]
Sometimes have same issue, as workaround you should try
1. complete system restart.
2. in \Steam\config delete "chaperone_info.vrchap" and "steamvr.vrsettings", note you may loose your SteamVR settings

**Comment by Swyter** [comment]
This is still a problem, marking issues as stale to tuck them away or sweep them under the rug just because there is no progress or new information is a pretty backwards practice.

**Comment by Swyter** [comment]
Still a problem.

**Comment by zarik5** [comment]
@Swyter It's just a bot that marks issues as stale. If no dev got to this issue yet is because no one had the time to.

**Comment by Swyter** [comment]
So far the workaround I'm using is just to create and use a different Windows account for this stuff. But that's not a fix.
There must be some per-user stale data or configuration/Registry key that breaks it. Absolutely bananas.

**Comment by jacklul** [comment]
FYI @zarik5 this issue happens on v19 nightly but does not on v18.2.3
Can get nightly to work because of it
