### ISSUE TITLE
ALVR linux unable to update to nightly

### ISSUE THREAD

**Issue by BuyMyMojo** [alvr-org/ALVR#864]
### Bug reports:

I'm running the latest normal build from apt (16.0.0) and even when I click update on the nightly thing it downloads the update and closes with no error or anything. when I open it next it is still on the same version

#### Environement

What hardware do you have: 5600x, 2070 super
What version of ALVR and SteamVR have you tried. 
16.0.0 and latest
OS: Pop!_OS 21.04 x86_64
Kernel: 5.14.18-xanmod1

**Comment by sctanf** [comment]
You can ignore the update prompts. If you like, they can be disabled in ALVR settings.

**Comment by BuyMyMojo** [comment]
I want to update to the latest version to try

**Comment by sctanf** [comment]
> I want to update to the latest version to try

There might be a package for nightly
Otherwise build yourself

**Comment by flipixwork** [comment]
I got update loop. How can i disable autoupdate from terminal?

**Comment by sctanf** [comment]
session.json is in the alvr installation folder, you can disable updates from there.

**Comment by flipixwork** [comment]
@sctanf tnx. I tried to reset steam in ~/.steam and ~/.local/share/Steam/ but it does not help. session.json was in ~/.config/alvr
