### ISSUE TITLE
a few questions about the latencies which the ALVR show

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#867]
1. sometimes we found receiveLatency is even bigger than sendLatency, is it reasonable ?
2. what does the exact idleLatency / waitLatency mean ? 

Thank you

**Comment by sctanf** [comment]
The latest nightly version of ALVR has corrected latency measurements, so I would check that first. 
1) receiveLatency can spike if there are some network instabilities so I would consider it normal.
2) idleLatency and waitLatency are part of SteamVR's frame timings, waitLatency is most likely vsync.

**Comment by chiwangnvp** [comment]
Thank you for your reply.
We tried to build the nightly version of alvr, but it failed somehow, and we will continued to try it. 
Before our success build, could you give us the alvr_server_windows
 exe package and alvr_client_oculus_quest.apk ?So we can check the latency measurement sooner.

**Comment by chiwangnvp** [comment]
Here is our build error message:

$ cargo xtask build-server --release
warning: C:\Users\ZEYUAN\workspace\gitalvr\ALVR\alvr\settings-schema-derive\Cargo.toml: the cargo feature `edition2021` has been stabilized in the 1.56 release and is no longer necessary to be listed in the manifest
  See https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-edition-field for more information about using this feature.
    Updating git repository `https://github.com/MarijnS95/android-ndk-rs`
warning: spurious network error (2 tries remaining): failed to send request: 操作超时
; class=Os (2)
error: failed to get `ndk` as a dependency of package `client v16.0.0-rc2 (C:\Users\ZEYUAN\workspace\gitalvr\ALVR\alvr\experiments\client)`

Caused by:
  failed to load source for dependency `ndk`

Caused by:
  Unable to update https://github.com/MarijnS95/android-ndk-rs?rev=7c1f9400cfec99eda693f84bd7465138bc086c97#7c1f9400

Caused by:
  object not found - no match for id (7c1f9400cfec99eda693f84bd7465138bc086c97); class=Odb (9); code=NotFound (-3)

**Comment by zarik5** [comment]
You need to update Rust with `rustup update`.

**Comment by chiwangnvp** [comment]
We have updated Rust already, now it has been blocked while we are "Updating git repository https://github.com/MarijnS95/android-ndk-rs"...

And we checked our network is fine...

**Comment by chengzeyuan** [comment]
![D5359DF7-5774-4915-9CA4-60B4B686E031](https://user-images.githubusercontent.com/86513446/143229853-b893d999-7082-4a08-ad87-49dbd136ca23.png)
It can not work anyway

**Comment by zarik5** [comment]
I can't really help you. You have to wait for the crates.io database to get fixed.

**Comment by zarik5** [comment]
I realized the problem was not because of the crates.io registry. There was a dependency somewhere to a fork of ndk, and the pinned commit was rebased away, to prepare for merging in the upstream repository. The branch has been merged and in the lastest commit I changed the git url to upstream.

**Comment by chiwangnvp** [comment]
We have compiled the nightly server / client, but we found the Latency is still very huge
![lALPJx8ZuSsEq04qzQQm_1062_42](https://user-images.githubusercontent.com/45933755/143548469-8a45bac4-3cac-41bc-948d-c5b2c5cc6164.png)

Actually, in the same network, the total latency is even worse... and we are not sure about the ClientIdleTime will take ~5ms, which is just the copyTexture operation, am I right ?

**Comment by sctanf** [comment]
Most of this latency is normal for ALVR until optimization can be done, but I see you have high "receiveLatency" (network ping) and "send" latency, which represents the network.

**Comment by chiwangnvp** [comment]
Got it, thank you.

**Comment by chiwangnvp** [comment]
By the way, our resolution is set to 125% ( Ffr is enabled ) and the bitrate is fixed to 50Mbps, so does our **receive / send latency** still have a network problem, or is just normal according to our high-resolution setting ? Thank you.
