### ISSUE TITLE
Extreme Latency and Image Stuttering

### ISSUE THREAD

**Issue by timm052** [alvr-org/ALVR#873]
### Bug reports:

When Using with steam VR titles the video appears to work fine at a number of bit rates but the image will occasionally hitch or have large digital artifacts when it's not doing this it runs extremely smoothly much better than Airlink. The steam VR performance graph also shows large latency spikes purple bars across the performance graph. I'm really not sure what's going but the intensity of the artifacts makes it pretty unusable as it's very jarring    

#### Environement

What hardware do you have: CPU, GPU, Audio
3900x RTX3080 32GB of RAM
V16 and V15.2.1 
Windows 11 Latest Update (Fresh Install)
ASUS RT-AX55 wireless router Directly Connected to PC

**Comment by KarlTheCool** [comment]
I managed to fix it for me by following [this guide](https://www.reddit.com/r/summonerschool/comments/4okzog/how_to_get_rid_of_ping_spikes_on_wireless_helped/).

`netsh wlan show settings` to check your wireless interface name and if "Auto configuration logic" is turned on

`netsh wlan set autoconfig enabled=no interface="[NAME OF INTERFACE]"` to turn it off.

The thread says this stops your wifi card from testing your signal quality and searching for nearby networks.

There's also a gui app to manage this called [WLAN Optimizer](http://www.martin-majowski.de/). I have autoconfig and background scan disabled. Enabling streaming mode cause the latency to be super stuttery for me.

Hope it helps!
