### ISSUE TITLE
No apk file for quest 2

### ISSUE THREAD

**Issue by TheNerdyTurd** [alvr-org/ALVR#880]
Hello, I was following the instructions for linux and when I got to the apk file for my quest 2, I found their is no hash file for my quest 2. My hash is 5259e1c3 however the apk file only exists for the go model. Will the go apk file work for the quest 2 or am I out of luck?

**Comment by TheNerdyTurd** [comment]
I got it working now but I'm presented with a new issue, it displays an error code 127...any suggestions?
![image](https://user-images.githubusercontent.com/20156675/144782608-070aca78-97b1-4d25-bc9a-0f4c01a07d43.png)

**Comment by TheNerdyTurd** [comment]
bypassing this (it's still an issue if I try to add firewall rules again) it's recognized and trusted my headset however, it's displaying distorted effects in the vr headset and it's displaying this in steamvr I assume this is because the router is in another room but I do not have a slow router so this is kinda confusing me...
![image](https://user-images.githubusercontent.com/20156675/144783355-22a5562a-861a-4d46-ada4-ee06ab7b11f3.png)

**Comment by zarik5** [comment]
> it's displaying distorted effects in the vr headset
Disable foveated rendering. All the issues you are encountering are already documented in the wiki. if you have any problem you don't find the answer in the wiki, please ask in the Discord server.
