### ISSUE TITLE
ALVR kill my driver registration in vrpathreg

### ISSUE THREAD

**Issue by PULSO-Gloves** [alvr-org/ALVR#881]
![Untitled](https://user-images.githubusercontent.com/92648483/145053565-64f803a5-f4bb-482a-b94e-04c314fd3770.png)

**Comment by PULSO-Gloves** [comment]
> The launcher is setup exactly for this not to happen, but it will wipe vrpathreg when clicking on "Reset driver and retry" or in rare instances where the launcher is killed at the wrong time.

do you think this guide is bad form in relation to the developers?

**Comment by PULSO-Gloves** [comment]
if you sometimes shoot yourself in the foot. you don't have to kill everyone around you. the problem is you.

**Comment by PULSO-Gloves** [comment]
pub fn fix_steamvr() {
    // If ALVR driver does not start use a more destructive approach: delete openvrpaths.vrpath then recreate it
    if let Ok(path) = alvr_commands::openvr_source_file_path() {
        fs::remove_file(path).ok();

        maybe_launch_steamvr();
        thread::sleep(Duration::from_secs(5));
        kill_steamvr();
        thread::sleep(Duration::from_secs(5));
    }

    unblock_alvr_addon().ok();
}

**Comment by zarik5** [comment]
@sctanf was going to update the launcher so it never erases the drivers list, and instead enable or disable the ALVR driver singularly or other interfering drivers. I also have planned a rewrite of the server that would remove the launcher entirely.
