### ISSUE TITLE
The picture freezes, mirrored from the back, torn at the edges

### ISSUE THREAD

**Issue by DygDyg** [alvr-org/ALVR#883]
The picture freezes, mirrored from the back, torn at the edges
Appears spontaneously during the game, often in VR chat when the world changes. The same happens when the helmet goes into sleep mode or exits the game area. Sometimes it helps to re-install the application on the helmet, sometimes you have to restart the client on the PC.

https://www.youtube.com/watch?v=A0Wkz-SRVkk
![image](https://user-images.githubusercontent.com/33259562/145565497-f5f93c00-ac9c-42dd-bb80-7c29d092b748.png)
![image](https://user-images.githubusercontent.com/33259562/145565526-34cf4270-cca5-403a-9fd3-fa009d838345.png)
![image](https://user-images.githubusercontent.com/33259562/145565543-754f8016-e3a7-4934-8ce3-f6e5bff450f7.png)
![image](https://user-images.githubusercontent.com/33259562/145565563-8c1a6b1b-4788-4a4b-b08d-a5fdf7ba38c6.png)
![image](https://user-images.githubusercontent.com/33259562/145565587-861bd35c-e25e-4630-87cb-5ac544e70830.png)
![image](https://user-images.githubusercontent.com/33259562/145565661-b8abf0bd-ab2f-4112-8456-f335a34c6d42.png)

**Comment by zarik5** [comment]
That GPU is too weak to run ALVR. The support status detection is just a "best effort" and sometimes misclassifies GPUs.

**Comment by DygDyg** [comment]
There is a friend who has an R9 380x. The problem is similar. On version 15, I did not encounter such a problem. Perhaps this is due to some options in the settings?

**Comment by zarik5** [comment]
You can try setting everything to the minimum and do some tests.

**Comment by DygDyg** [comment]
Changing the settings does not affect the bug. He appears after installing the application on the helmet. As a rule, this happens when leaving the playing area, turning on the helmet camera or falling asleep when removing the helmet. It looks very much like this is a reconnect problem. At the same time, tracking and sound continue to work

**Comment by DygDyg** [comment]
![image](https://user-images.githubusercontent.com/33259562/145657473-6f1f4f5f-01ff-4b12-879c-4bf3eedf9643.png)
![image](https://user-images.githubusercontent.com/33259562/145657478-46757c46-fe7a-414d-b1c6-cf90b1caa34f.png)
Perhaps this is related, he always swears that the GamePad support addon is blocked. This message appears even after completely reinstalled windows. p.s. I have windows 11 installed
