### ISSUE TITLE
Custom path to SteamVR

### ISSUE THREAD

**Issue by DygDyg** [alvr-org/ALVR#885]
Is it possible somehow to manually specify the path to SteamVR in the client in order to use it without starting Steam. If you start ALVR now, steam starts and offers to install SteamVR. In this case, steam can be closed and SteamVR can be started manually.
As I understand it, now something like steam is used to steam://run/250820

I need it for several reasons:
1) steam does not allow you to install steamvr on another disk.
2) it's inconvenient for me to keep steam open since I still run applications bypassing it.
3) I would like to make myself a portable version of the client so that you can run vr on any computer from a USB stick (I have an installed ALVR in my quest memory, I would like to put SteamVR there as well)

**Comment by sctanf** [comment]
Sort of
SteamVR will make a config file at `C:\Users\username\AppData\Local\openvr\openvrpaths.vrpath` (So you cannot do no. 3 I believe)
Under external drivers add your ALVR path, with proper escape characters:
```
	"external_drivers" : 
	[
		"C:\\Program Files (x86)\\Steam\\steamapps\\common\\SteamVR\\drivers\\alvr"
	],
```
