### ISSUE TITLE
Sockets rewrite v2

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#886]
The first rewrite (#242) moved sockets management from C++ code to Rust, added the StreamSocket interface with multiplexed streams over a single UDP or TCP socket. The user needs to choose between the reliability of TCP and the speed of UDP. Some kind of stream control was implemented: in case of packets out of order, the older packets gets discarded. A throttled UDP mode is introduced with some kind of congestion control but with poor performance with bandwidth too high or too low. The streaming infrastructure is based on the tokio async runtime.

The second rewrite should focus on a single socket protocol QUIC, that can deliver the speed of UDP and the reliability of TCP, if used correctly.

Background:
* QUIC is a protocol based on UDP that implements multiplexed streams natively. It uses ARQ for error control.
* ARQ uses ACK packets and so each packet needs a round trip before sending the next packet. Packet losses will block the queue.

QUIC can replace the UDP and throttled UDP backends on StreamSocket without changing much its interface. The TCP backend is kept for compatibility with USB and cross-NAT connections. QUIC has reliable streams and also a unreliable raw UDP stream. QUIC has integrated support for TLS encryption.

The management of QUIC streams is crucial for the efficiency and speed of the connection. ALVR requires some streams with low priority packets (haptics), some with no ordering requirement (tracking that uses timestamps for identification), some with causality requirement (audio), and some with complete reliability requirement (video). Haptics and tracking can be sent using the unreliable UDP stream. Audio and video can use reliable streams. While audio packets fit usually in one UDP datagram (and so it requires only one ACK) and the pacing is self-controlled, video packets require multiple datagrams and the transmission is bursty, normally causing congestion in a raw UDP socket. Sending entire video packets in one QUIC stream will be as slow as TCP because of the ARQ mechanism. The solution would be to manually split big packets into shards, use one stream for each, and reconstruct the packet in the end. Each stream is independent, so there will not be any head-of-line blocking and no waiting for ACKs between shards; retransmission of lost shards will happen normally. This should achieve near UDP speeds with TCP-level reliability.

The chosen crate for QUIC is [quiche](https://github.com/cloudflare/quiche) which is not async. Async code and tokio should be eliminated because they proved to cause many issues, dangling resources and threads when canceling execution branches, difficulty with debugging.

EDIT: in case the video is split in multiple slices, like Oculus Link implementation, to increase pipelining and reduce latency, we need to pay close attention at the threading. First of all it's important to understand that a socket will always be sequential. The pipelining will happen only if slices are sent sequentially and their shards are not interleaved. Shards from a single slice should also be sent one after the other, but without waiting for the ACKs, which requires some heuristics (in the simplest form we could have k threads/streams and each stream sends n/k shards, with n the total number of shards for the frame). Non-video packets are free to be sent whenever and to be interleaved with video packets, because they are so small and it's better overall for them to be sent immediately for lower latency.

EDIT2: DATAGRAM unreliable stream supports QUIC's congestion control. We can combine QUIC with FEC to cope with dropped packets. The objective is removing the need for ACK packets which decreases the throughput in the server->client direction on wireless connections. if the network is stable and QUIC can properly pace frames, FEC ECC percentage can be set very low to increase throughput.

**Comment by Vixea** [comment]
This should probably be closed as the plan has changed and we're no longer going to change to quick as most if not all problems have been solved with some upd changes.

**Comment by zarik5** [comment]
Yeah, I don't see any reason to continue with QUIC at the moment. (Context: increasing the send/receive buffer size of the sockets fixed the packet dropping issue without the need for congestion control. In case of over the internet streaming TCP will suffice)
