### ISSUE TITLE
GL_INVALID_VALUE

### ISSUE THREAD

**Issue by Daktm** [alvr-org/ALVR#889]
# Please follow the general troubleshooting steps first:

- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [ ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

I will get an error which is GL_INVALID_VALUE.
Steps:
1.Client first success connected to server;
2.Close client;
3.Open client try connect to server,this step will cause ALVR client crash and throw GL_INVALID_VALUE

#### Environement

VR Headest : Quest2
PC: Win10

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by chenjiang199404** [comment]
ALVR client will be oom and crash after I try many times;
