### ISSUE TITLE
Oculus Quest 1: View too small, Borders heavily distorted

### ISSUE THREAD

**Issue by Jonny999999** [alvr-org/ALVR#893]
## Description
I tried v16.0.0 and v16.0.0+nightly.2021.12.24 the same issue occurs:
The problem is that in the center the view is displayed correctly but too small (everything looks far away). Outside of the center the image looks repeated and stretched. See screenshot below:
![alvr client quest nightly-20211226-105539](https://user-images.githubusercontent.com/5196385/147404879-7430c67c-22d5-4ae3-a31b-f825659f6146.jpg)
This effects both, steam lobby and started games.

In the video you can see the effect in more detail:
https://user-images.githubusercontent.com/5196385/147404966-88327e57-e955-4f68-af9e-f7ee3a53fd60.mp4

The Steam preview looks totally normal:
![steam-vr-view](https://user-images.githubusercontent.com/5196385/147405382-f4f78c72-6de3-417d-b635-7b39c1fcb199.jpg)

### Hardware
hw-probe output: https://linux-hardware.org/?probe=5eedf51dce
Oculus Quest 1, runtime version: 35.0.0.140.341.339081697

### Installation
**ALVR Version**:
v16.0.0+nightly.2021.12.24
(i also tried v16.0.0, same issue)

**SteamVR Version**:
Version 1.20.4

**Install Type**:
Server:
- Portable (`zip`)  ( v16.0.0+nightly.2021.12.24)
- Source  (v16.0.0)

Client:
- apk from releases

**OS Name and Version** 
Arch Linux 5.15.10

**Comment by sctanf** [comment]
Turn off foveated encoding, it is not supported on Linux yet

**Comment by zarik5** [comment]
I'm going to conditionally ignore the foveated encoding setting on Linux, it should be ready for tonight's nightly.
