### ISSUE TITLE
[Linux] Computer crashes 4 seconds after alvr dashboard loads

### ISSUE THREAD

**Issue by davigamer987** [alvr-org/ALVR#896]
## Description

Arch linux crashes with graphical glitches (like artifacts) after a few seconds of the app opening, Journalctl reports amdgpu (driver) having a crash, [Hastebin Log Link (Only Error Part)](https://www.toptal.com/developers/hastebin/vicoxuyime.yaml)

## General Troubleshooting
- [ Yes] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ Yes] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)
### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=38aae760ab

**CPU**: Ryzen 5 1600

**GPU**: Rx 580

**Audio**: Pipewire

### Installation
**ALVR Version**: Can't open app to check, i used the one in the aur

**SteamVR Version**: 1.21.4

**Install Type**:
- [Aur] Packaged (`exe`, `deb`, `rpm`, etc) 
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Arch Linux (Rolling Release)

**Comment by EmilJacobs** [comment]
Can replicate the bug on Gentoo having installed 16.0.0 (I'm working on an ebuild for the GURU repository).

## Description
Having installed 16.0.0 on Gentoo and [the correct apk](https://github.com/alvr-org/ALVR/releases/tag/v16.0.0) in the headset I get graphical artifacts [shown in a short video](https://youtu.be/UXV3HHpeZ8Y) I made of the issue. 

[My syslog](https://pastebin.ubuntu.com/p/7yBwWK964n/) indicates a driver freeze.

The issue occurs both on Xorg and in Wayland.

# Environment 
## Hardware
https://linux-hardware.org/?probe=61e605e1d8

### Installation
**ALVR Version**: 16.0.0
**SteamVR Version**: 1.20.4
**Install Type**: Gentoo ebuild (build from the 16.0.0 source tarball, currently being written/tested by me for the GURU repository. [This is a link to the ebuild](https://pastebin.ubuntu.com/p/CSNXMd4C9Q/).)
**OS Name and Version** Gentoo

**Comment by betaRadiation** [comment]
I can confirm that this happens on marjaro linux with a 5700 XT gpu using the amdgpu driver.

**Comment by mittorn** [comment]
Try disable steamvr home. It should fix this crash, but it will possibly crash when connecting client, making it unuseful

**Comment by kacpi2442** [comment]
I can confirm this issue on manjaro.
CPU: Ryzen 5 3600x
GPU: Rx 580
Audio: Pipewire
ALVR: v17.0.0
SteamVR: beta 1.21.6

**Comment by arminask** [comment]
Any news on that?

**Comment by mittorn** [comment]
Disabling realtime capabilities and steamvr home should completely fix it on polaris and rdna2.
vega and rdna1 still potencially may crash
