### ISSUE TITLE
ALVR stuck on "Steam VR installed: Make sure you launched it at least once, then close it."

### ISSUE THREAD

**Issue by technodragon253** [alvr-org/ALVR#904]
## Description

After installing ALVR from source following this tutorial: https://www.youtube.com/watch?v=OtnsWxJ1FwY, I opened the "alvr_launcher" file to be greeted with this message:"Steam VR installed: Make sure you launched it at least once, then close it." A screenshot of this is attached below. Any other necessary information will be provided promptly.
![Screenshot from 2022-01-02 13-43-00](https://user-images.githubusercontent.com/70380275/147887784-afb4184c-9873-4620-94a4-633b2522fd55.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=ac32062ec1

### Installation
**ALVR Version**:
16.0.0

**SteamVR Version**:
1.21.4

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Pop!_OS 21.10

**Comment by spectreseven1138** [comment]
If you're using the Flatpak version of Steam, try using the standard version instead. That solved it for me.

**Comment by technodragon253** [comment]
Ah okay I'll try that

**Comment by technodragon253** [comment]
That fixed it tysm!
