### ISSUE TITLE
[LINUX] Alvr stuck on "The stream will begin soon"

### ISSUE THREAD

**Issue by Elpersonn** [alvr-org/ALVR#905]
## Description
ALVR is stuck on "The stream will begin soon" screen.
Note: I've never experienced this issue on windows where I used a slightly worse CPU.
Steam also sees the VR headset as standing by.
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware

**CPU**:
12th Gen Intel i5-12600K (16) @ 6.300GHz
**GPU**:
AMD ATI Radeon RX 570 8GB
**Audio**:
[HyperX Cloud Revolver S], device 0: USB Audio [USB Audio]
### Installation
**ALVR Version**:
v 16.0.0
**SteamVR Version**:
1.20.4
**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**:
Debian GNU/Linux 11 (bullseye)

**Comment by ShuangyiTong** [comment]
Had the same issue after upgrading to 16.0 on Windows.
