### ISSUE TITLE
alvr_launcher crashes on start on Ubuntu 20.04

### ISSUE THREAD

**Issue by jvetulani** [alvr-org/ALVR#908]
## Description
alvr_launcher crashes a few seconds after opening.
unable to even start on the setup wizard

terminal output:
https://pastebin.com/raw/caue69Xq

### Hardware
https://linux-hardware.org/?probe=52a27d926e

### Installation
**ALVR Version**:
16.0.0+1640412182+aee1fd32
**SteamVR Version**:
1.20.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**Comment by skulldsp** [comment]
You need to have chromium installed to keep ALVR from closing
