### ISSUE TITLE
[ Quest 2 ] Getting 307 error on Arch Linux 

### ISSUE THREAD

**Issue by chiboreache** [alvr-org/ALVR#909]
Everything is bleeding edge.

Connection screen is correct (fps, black theme), but then streaming is failing, picture having broken perspective.

### Hardware
https://linux-hardware.org/?probe=2ca9e42a3f

**CPU**:
AMD 5950X

**GPU**:
RADEON 5700XT

**Audio**:
mb

### Installation
**ALVR Version**: 16.0.0.r0.gece4d74c-4

**SteamVR Version**: multilib/steam 1.0.0.74-1 

**Install Type**: aur

**OS Name and Version** : Arch Linux

**Comment by toomuchcodehelp** [comment]
started having a similar issue, but on solus with an nvidia card.

**Comment by thevulturer** [comment]
Same thing, AMD (RX 570) and nVidia (GTX 1050 Ti), Oculus Quest 2, Arch Linux, tried ALVR 18 and 19, Wayland and Xorg, always getting error 307.

**Comment by toomuchcodehelp** [comment]
> Same thing, AMD (RX 570) and nVidia (GTX 1050 Ti), Oculus Quest 2, Arch Linux, tried ALVR 18 and 19, Wayland and Xorg, always getting error 307.

i managed to actually fix this by disabling llvmpipe (not reccomended) via [a script](https://github.com/toomuchcodehelp/llvmpipe-disabler)

**Comment by Vixea** [comment]
Should be fixed with the latest commits awaiting comment by author.

**Comment by Kieaer** [comment]
@Vixea I alreday tried mater branch source build but still 307 (3 hours ago)

**Comment by Vixea** [comment]
Wayland?
Also I asked for the author but I'll help you here anyway.

**Comment by Kieaer** [comment]
Yes. ubuntu 22.04.1 using wayland by default.

**Comment by Vixea** [comment]
Then this bug does not apply to you as he's using xorg and steamvr crashes with GPUs that support modifiers(not an ALVR bug)

**Comment by chiboreache** [comment]
> Should be fixed with the latest commits awaiting comment by author.

sorry it was so long ago that it broke in another place

i can't even connect it now

`Client disconnected. Cause: At alvr/sockets/src/control_socket.rs:36 (and 175)`

**Comment by chiboreache** [comment]
my video drivers is fine btw, no glitches whatsoever 

![2022-11-24x12:05:02](https://user-images.githubusercontent.com/16459251/203741084-b178ea84-9402-487f-b642-3c36ee50d37c.jpg)

**Comment by Kieaer** [comment]
I solved 307 error.
Build ALVR from source (master branch)
**You must build ffmpeg first**. Bundle build will make 307 error.

**Comment by chiboreache** [comment]
hm🤔 ok i will try

![2022-11-24x12:14:06](https://user-images.githubusercontent.com/16459251/203744074-a846d881-c077-47ef-976b-309fd2fc9381.jpg)

**Comment by Kieaer** [comment]
[alvr_linux_server_ubuntu_22.04.1.tar.gz](https://1drv.ms/u/s!AostYSE5fO5diaop5uJig2jRI8MPHg?e=ZZ2DJT)
If build fail, try to this version (I built it)

**Comment by chiboreache** [comment]
just fine, rebuilding alvr-git now

![2022-11-24x12:22:40](https://user-images.githubusercontent.com/16459251/203746189-8df419f8-4525-459b-9e46-f770d5a99936.jpg)

**Comment by Kieaer** [comment]
try to my built version lol

**Comment by chiboreache** [comment]
it's redundant for Arch users i guess

![2022-11-24x12:37:37](https://user-images.githubusercontent.com/16459251/203749723-05b22233-2b08-470a-84ee-0b84c2d4f141.jpg)

https://github.com/alvr-org/ALVR/wiki/Installation

**Comment by Vixea** [comment]
This issue is fine to close as it's seems to have been user error and has been resolved?
Please read the wiki!

**Comment by chiboreache** [comment]
it's not my fault! -_-

give me a link and i'll check

**Comment by Vixea** [comment]
https://github.com/alvr-org/ALVR/wiki/Building-From-Source
Try this or the appimage you should not have to use ffmpeg-git just the regular ffmpeg package in the arch repositories.

**Comment by chiboreache** [comment]
> regular ffmpeg package in the arch repositories.

i used from the beginning, watch at screenshot 😡 
https://github.com/alvr-org/ALVR/issues/909#issuecomment-1326160887

what difference of building from source and from aur's alvr-git !?

**Comment by Kirottu** [comment]
Try setting SteamVR launch options to `RADV_DEBUG=nodcc %command%`
