### ISSUE TITLE
Headset stuck on “the stream will begin soon”

### ISSUE THREAD

**Issue by Gcat101** [alvr-org/ALVR#910]
Hi, so my quest is stuck at “the stream will begin soon”

I tried:
1.Opening 9944
2.Connecting to a faster network
3.Selecting h265 in the settings

Still stuck

Gpu: NVDIA GeForce GTX 1650
Video settings: the standard ones (except h265)
OS: Pop os (latest)

**Comment by config-i1** [comment]
Same here.

GPU: Nvidia 2070
Standard settings
OS: Ubuntu Focal, 20.04.3
Gear: Oculus Quest 2

I haven't tried UDP yet. Not sure if it would fix it. But what I've noticed is that Steam VR detected the headset and was capturing the input from the headset. It's just there was no signal back to the Quest.

**Comment by config-i1** [comment]
Just to add to this. This was resolved by adding the libraries as mentioned here: https://github.com/alvr-org/ALVR/issues/872#issuecomment-991292352

The problem now is that the picture is wrong and there is no sound. But at least, something is working now :)

**Comment by Gcat101** [comment]
Fixed by downloading and compiling nightly version

**Comment by mtshrmn** [comment]
I'm using v17.0.0 and the issue still persists
