### ISSUE TITLE
Client disconnected. control_socket.rs:33: invalid length 3, expected a matrix array

### ISSUE THREAD

**Issue by FtK259** [alvr-org/ALVR#912]
Hi,

I installed ALVR on Linux Manjaro through the AUR package. Everything seems ok, but when connecting to the PC, I'm automatically disconnected. Take a look at the log:
`
16:46:13.078787719 | [INFO] | #{"id":"ClientConnected"}#
-- | -- | --
16:46:13.079065189 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:13.079161049 | [INFO] | Model Number: Miramar
16:46:13.079201715 | [INFO] | Render Target: 3648 1920
16:46:13.079248182 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:13.079306582 | [INFO] | Refresh Rate: 90
16:46:13.079685392 | [INFO] | CEncoder::Run
16:46:13.079787223 | [INFO] | CEncoder Listening
16:46:13.082059395 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:13.082093379 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:14.137612420 | [INFO] | #{"id":"ClientConnected"}#
16:46:14.137901643 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:14.137977234 | [INFO] | Model Number: Miramar
16:46:14.138033470 | [INFO] | Render Target: 3648 1920
16:46:14.138075929 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:14.138139769 | [INFO] | Refresh Rate: 90
16:46:14.140374881 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:14.140404617 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:15.253213790 | [INFO] | #{"id":"ClientConnected"}#
16:46:15.253493143 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:15.253595465 | [INFO] | Model Number: Miramar
16:46:15.253628407 | [INFO] | Render Target: 3648 1920
16:46:15.253658073 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:15.253698118 | [INFO] | Refresh Rate: 90
16:46:15.257499988 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:15.257554791 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:16.378724184 | [INFO] | #{"id":"ClientConnected"}#
16:46:16.379118544 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:16.379228079 | [INFO] | Model Number: Miramar
16:46:16.379288993 | [INFO] | Render Target: 3648 1920
16:46:16.379360427 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:16.379439796 | [INFO] | Refresh Rate: 90
16:46:16.381831532 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:16.381866467 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:17.509755092 | [INFO] | #{"id":"ClientConnected"}#
16:46:17.510046679 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:17.510145314 | [INFO] | Model Number: Miramar
16:46:17.510181171 | [INFO] | Render Target: 3648 1920
16:46:17.510234501 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:17.510291859 | [INFO] | Refresh Rate: 90
16:46:17.512992384 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:17.513021228 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:18.632852811 | [INFO] | #{"id":"ClientConnected"}#
16:46:18.633282747 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:18.633400368 | [INFO] | Model Number: Miramar
16:46:18.633449961 | [INFO] | Render Target: 3648 1920
16:46:18.633498472 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:18.633559987 | [INFO] | Refresh Rate: 90
16:46:18.635815828 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:18.635855232 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:19.755709007 | [INFO] | #{"id":"ClientConnected"}#
16:46:19.755967311 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:19.756036441 | [INFO] | Model Number: Miramar
16:46:19.756065656 | [INFO] | Render Target: 3648 1920
16:46:19.756095442 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:19.756148772 | [INFO] | Refresh Rate: 90
16:46:19.760568401 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:19.760634094 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:20.884684901 | [INFO] | #{"id":"ClientConnected"}#
16:46:20.884936833 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:20.885007416 | [INFO] | Model Number: Miramar
16:46:20.885036600 | [INFO] | Render Target: 3648 1920
16:46:20.885083418 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:20.885123293 | [INFO] | Refresh Rate: 90
16:46:20.887513295 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:20.887563880 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:22.012080651 | [INFO] | #{"id":"ClientConnected"}#
16:46:22.012521337 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:22.012630832 | [INFO] | Model Number: Miramar
16:46:22.012676278 | [INFO] | Render Target: 3648 1920
16:46:22.012732052 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:22.012796102 | [INFO] | Refresh Rate: 90
16:46:22.014349606 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:22.014390082 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:23.143379231 | [INFO] | #{"id":"ClientConnected"}#
16:46:23.143656521 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:23.143724669 | [INFO] | Model Number: Miramar
16:46:23.143761357 | [INFO] | Render Target: 3648 1920
16:46:23.143814096 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:23.143857428 | [INFO] | Refresh Rate: 90
16:46:23.146385619 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:23.146433109 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:24.276967204 | [INFO] | #{"id":"ClientConnected"}#
16:46:24.277220540 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:24.277312332 | [INFO] | Model Number: Miramar
16:46:24.277341226 | [INFO] | Render Target: 3648 1920
16:46:24.277372905 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:24.277411247 | [INFO] | Refresh Rate: 90
16:46:24.281251049 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:24.281294300 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:25.386531381 | [INFO] | #{"id":"ClientConnected"}#
16:46:25.386833467 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:25.386916773 | [INFO] | Model Number: Miramar
16:46:25.386951839 | [INFO] | Render Target: 3648 1920
16:46:25.386986404 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:25.387032010 | [INFO] | Refresh Rate: 90
16:46:25.389365316 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:25.389404479 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:26.516817462 | [INFO] | #{"id":"ClientConnected"}#
16:46:26.517054667 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:26.517119629 | [INFO] | Model Number: Miramar
16:46:26.517147000 | [INFO] | Render Target: 3648 1920
16:46:26.517173850 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:26.517217873 | [INFO] | Refresh Rate: 90
16:46:26.520304983 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:26.520346040 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:27.647458819 | [INFO] | #{"id":"ClientConnected"}#
16:46:27.647875821 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:27.647996227 | [INFO] | Model Number: Miramar
16:46:27.648053234 | [INFO] | Render Target: 3648 1920
16:46:27.648103017 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:27.648177938 | [INFO] | Refresh Rate: 90
16:46:27.650186926 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:27.650218285 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:28.771554369 | [INFO] | #{"id":"ClientConnected"}#
16:46:28.771955682 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:28.772066430 | [INFO] | Model Number: Miramar
16:46:28.772120010 | [INFO] | Render Target: 3648 1920
16:46:28.772175194 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:28.772247780 | [INFO] | Refresh Rate: 90
16:46:28.775515649 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:28.775557878 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:29.898030525 | [INFO] | #{"id":"ClientConnected"}#
16:46:29.898342069 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:29.898429433 | [INFO] | Model Number: Miramar
16:46:29.898458608 | [INFO] | Render Target: 3648 1920
16:46:29.898496519 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:29.898538498 | [INFO] | Refresh Rate: 90
16:46:29.902864612 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:29.902902673 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:31.024923291 | [INFO] | #{"id":"ClientConnected"}#
16:46:31.025210400 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:31.025283106 | [INFO] | Model Number: Miramar
16:46:31.025340193 | [INFO] | Render Target: 3648 1920
16:46:31.025386490 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:31.025447425 | [INFO] | Refresh Rate: 90
16:46:31.031578203 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:31.031607558 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:32.145684989 | [INFO] | #{"id":"ClientConnected"}#
16:46:32.146131787 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:32.146246011 | [INFO] | Model Number: Miramar
16:46:32.146314680 | [INFO] | Render Target: 3648 1920
16:46:32.146383369 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:32.146498505 | [INFO] | Refresh Rate: 90
16:46:32.148776608 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:32.148815000 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:33.277123271 | [INFO] | #{"id":"ClientConnected"}#
16:46:33.277404809 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:33.277476594 | [INFO] | Model Number: Miramar
16:46:33.277505037 | [INFO] | Render Target: 3648 1920
16:46:33.277533651 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:33.277587632 | [INFO] | Refresh Rate: 90
16:46:33.280592789 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:33.280631111 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:34.399367630 | [INFO] | #{"id":"ClientConnected"}#
16:46:34.399649017 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:34.399709391 | [INFO] | Model Number: Miramar
16:46:34.399741220 | [INFO] | Render Target: 3648 1920
16:46:34.399773110 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:34.399829406 | [INFO] | Refresh Rate: 90
16:46:34.402590525 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:34.402625059 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:35.527750421 | [INFO] | #{"id":"ClientConnected"}#
16:46:35.528045114 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:35.528124633 | [INFO] | Model Number: Miramar
16:46:35.528165179 | [INFO] | Render Target: 3648 1920
16:46:35.528208200 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:35.528276859 | [INFO] | Refresh Rate: 90
16:46:35.531157010 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:35.531185634 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:36.651479434 | [INFO] | #{"id":"ClientConnected"}#
16:46:36.651718272 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:36.651807239 | [INFO] | Model Number: Miramar
16:46:36.651843897 | [INFO] | Render Target: 3648 1920
16:46:36.651874575 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:36.651914790 | [INFO] | Refresh Rate: 90
16:46:36.655830545 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:36.655858337 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:37.791484764 | [INFO] | #{"id":"ClientConnected"}#
16:46:37.791765400 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:37.791868143 | [INFO] | Model Number: Miramar
16:46:37.791907707 | [INFO] | Render Target: 3648 1920
16:46:37.791948995 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:37.792018024 | [INFO] | Refresh Rate: 90
16:46:37.818942783 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:37.818973401 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:38.904773256 | [INFO] | #{"id":"ClientConnected"}#
16:46:38.905045967 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:38.905117431 | [INFO] | Model Number: Miramar
16:46:38.905172134 | [INFO] | Render Target: 3648 1920
16:46:38.905204164 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:38.905252475 | [INFO] | Refresh Rate: 90
16:46:38.907421933 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:38.907451639 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:40.033020002 | [INFO] | #{"id":"ClientConnected"}#
16:46:40.033297413 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:40.033392271 | [INFO] | Model Number: Miramar
16:46:40.033434139 | [INFO] | Render Target: 3648 1920
16:46:40.033478993 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:40.033537914 | [INFO] | Refresh Rate: 90
16:46:40.037959246 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:40.037993370 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:41.157403423 | [INFO] | #{"id":"ClientConnected"}#
16:46:41.157674080 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:41.157748069 | [INFO] | Model Number: Miramar
16:46:41.157797592 | [INFO] | Render Target: 3648 1920
16:46:41.157830013 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:41.157888713 | [INFO] | Refresh Rate: 90
16:46:41.270825782 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:41.270857021 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:42.395019246 | [INFO] | #{"id":"ClientConnected"}#
16:46:42.395470482 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:42.395590527 | [INFO] | Model Number: Miramar
16:46:42.395638467 | [INFO] | Render Target: 3648 1920
16:46:42.395684474 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:42.395750547 | [INFO] | Refresh Rate: 90
16:46:42.400995425 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:42.401023547 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:33: invalid length 3, expected a matrix array
16:46:44.327089235 | [INFO] | #{"id":"ClientConnected"}#
16:46:44.327344825 | [INFO] | Serial Number: 1WMGH000XX0000
16:46:44.327433631 | [INFO] | Model Number: Miramar
16:46:44.327463728 | [INFO] | Render Target: 3648 1920
16:46:44.327491490 | [INFO] | Seconds from Vsync to Photons: 0.005000
16:46:44.327534100 | [INFO] | Refresh Rate: 90
16:46:45.483571729 | [INFO] | #{"id":"ClientDisconnected"}#
16:46:45.483615291 | [INFO] | Client disconnected. Cause: At alvr/common/src/sockets/control_socket.rs:32
`

My Specs:
Operating System: Manjaro Linux
Kernel Version: 5.15.12-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: AMD Ryzen 5 2500U
Memory: 16 GB of RAM
Graphics Processor: AMD Radeon Vega 8 and Nvidia GTX 1050

**Comment by zarik5** [comment]
This sounds like a server-client version mismatch. Version checking should be fixed now.
