### ISSUE TITLE
HEVC horrible quality compared to Airlink. H264 glitch and freeze the client app.

### ISSUE THREAD

**Issue by DaiveeCZ** [alvr-org/ALVR#919]
## Description
HEVC got horrible compression aftifacts (compared to Airlink) mainly in fog areas. When i try switch to H264 it glitch and freeze the client app in Quest. I own OG Quest. Testing both versions (installer, portable).
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: AMD Ryzen 3950X

**GPU**: AMD Radeon RX6700 XT

**Audio**: Onboard, VB-CABLE driver for mic.

### Installation
**ALVR Version**: latest (v16.0.0)

**SteamVR Version**: latest - stable

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [x] Portable (`zip`)
- [ ] Source

**OS Name and Version**:
Windows 10 Pro 64bit

**Comment by ctaetcsh** [comment]
If you can continue to replicate the crashing/freezing bug on the Quest then if you can get logs that would definitely help.
As for image quality, the biggest things to check are your bitrate settings in ALVR and the capabilities of your network.
