### ISSUE TITLE
Oculus Quest 2 Handtracking First Day

### ISSUE THREAD

**Issue by LievreAI** [alvr-org/ALVR#921]
hey guys today i recived my brand quest 2 headset and i decided to play vrchat with handtracking but soon as i try it i discover that the hands not that accurate and i cannot move during the handtracking

**CPU**:
I9-11900F @2.50GHz 11 Gen Intel 2469 Mhz 8 Core 16 Logical 

**GPU**:
NVIDIA Quardro RTX 4000

**Audio**:
Realtek High Definition

### Installation
**ALVR Version**:
v16.0.0

**SteamVR Version**:
1.20.4

**Install Type**:
- [ ] Packaged (`exe`)

**OS Name and Version**
Microsoft Windows 11 Home Build 22000 Version 10.0.22000

<!-- Feature Requests
will be great if you can make the tool to allow more accutrate hand tracking
and during the handtracking i will be able to walk

**Comment by ctaetcsh** [comment]
The hand tracking is experimental function and as VRchat depends on the thumbstick to move it won't work.
