### ISSUE TITLE
[Enhancement] - Add Build Script NVIDIA Encoder Disablement Flag

### ISSUE THREAD

**Issue by ckiee** [alvr-org/ALVR#930]
> *2155X — Today at 8:18 PM*
> so a couple days ago I was building alvr server via `packaging/alvr_build_linux.sh` but it insisted on installing snap for rustup. I believe that it would be better if we allow the user to choose between snap (definitely don't want that) and the official rustup site and their installer https://rustup.rs/ (preferred)

> *trae32566 — Today at 9:14 PM*
> Can you do me a favor and create an issue for it so I don't forget / for tracking? It doesn't have to be detailed or anything, just a 'add > --nvidia-whatever' is fine and assign it to me or I can assign it to myself or whatever
> I only ask because I get sidetracked regularly, and chances are I'd forget

**Comment by Trae32566** [comment]
I'm pretty sure what we wanted here was actually the ability to disable the nvidia encoder so we don't have to pull in all the dependencies.

**Comment by Toxblh** [comment]
we has `--no-nvidia` like additional flag to `--bundle-ffmpeg` just need to pass it upper to build script

**Comment by Trae32566** [comment]
Yep, that's the plan, I am working on this in [draft] PR #962
