### ISSUE TITLE
SteamVR crashes on client connection

### ISSUE THREAD

**Issue by TonyGamer** [alvr-org/ALVR#931]
## Description
As soon as my headset connects to the ALVR server, SteamVR crashes with an "unexepected error"

### Hardware
hw-probe: https://linux-hardware.org/?probe=9c55da98c8 (note that the detected DE is incorrect, I am using OpenBox, although XFCE is installed)

### Installation
**ALVR Version**: 17.0.0

**SteamVR Version**: linux_v1.14

**Install Type**:
- [x] Packaged (AUR/alvr-bin)

**OS Name and Version**: Arch Linux

### Logs:
The ALVR log shows no errors or warnings. The last logged line before the crash is "[INFO] CEncoder client connected, pid 109443, cmdline"

vrclient_steam.txt:
- Unable to load driver alvr_server. Primary driver DLL not found on filesystem: /usr/lib//steamvr/alvr/bin/linux32/driver_alvr_server.so.
- Unable to load driver alvr_server. Primary driver DLL not found on filesystem: /usr/lib//steamvr/alvr/bin/linux32/driver_alvr_server.so.

vrmonitor.txt:
- [Dismissable Warning Added] DismissableWarning_OpenXRDefaultRuntimePrompt The OpenXR runtime is not currently set.
- [Status Alert] SteamVR Fail (-301)

**Comment by ctaetcsh** [comment]
Looking up the SteamVR 301 error doesn't point at a definitive solution, but it might be relating to the VR runtime not being set. Given the other message in the vrmonitor.txt log is saying that OpenXR is not currently set, you might want to open SteamVR settings and make sure the runtime is set to Steam.

**Comment by TonyGamer** [comment]
I managed to set the SteamVR runtime properly after switching to the SteamVR beta branch, as it refused to open settings otherwise. Changing to the correct runtime resulted in no change to the behavior. I am getting the same error and instant crash as I was before. If there are any other log files which might be useful, I can send them as well. I just sent the information which I thought might be relevant

**Comment by TonyGamer** [comment]
I have returned to trying to get ALVR working once again, and have been met with the exact same issue. After looking around and trying different things, I have made no progress. The moment my client connects, SteamVR crashes, according to journalctl, it is a core dump, which doesn't give much information. Just in case, however, I have attached the full crash report generated by journalctl, just in case there is any useful information in it
[journal.txt](https://github.com/alvr-org/ALVR/files/8195058/journal.txt)

**Comment by Tanza3D** [comment]
i'm facing the same issue on my system, running on manjaro. for a split second, the "VR View" window shows the SteamVR Home loading panel, then it instantly crashes with, similarly, error (-301). i'm trying to make it work and i'll post something if i can figure it out, though seeming unlikely

**Comment by Tanza3D** [comment]
okay! round two; if you compile the client, and server, manually from the git repo, it seems to fully work! steamvr no longer crashes, encoding works perfectly, and i can see it in the headset, controllers are aslo working! from my knowledge you can also install from arch aur using `alvr-git` but you still have to compile the client manually.
![image](https://user-images.githubusercontent.com/33783503/187702561-61053508-c41e-4468-a389-3a3c7a3651cf.png)
