### ISSUE TITLE
alvr opens and closes on ubuntu hirsuite

### ISSUE THREAD

**Issue by Alpha-404** [alvr-org/ALVR#934]
![image](https://user-images.githubusercontent.com/63340001/150735424-db6f851d-47ac-4cc8-82d5-ee6c212b4f2c.png)

**Comment by ctaetcsh** [comment]
To adequately help you, it would be useful to know information about your system. Can you reply with the following? 
* ALVR Version
* SteamVR Version
* Exact OS Version
* Hardware Information (CPU, GPU, GPU Driver, etc.)
