### ISSUE TITLE
Ubuntu heavy lags

### ISSUE THREAD

**Issue by Barmallini** [alvr-org/ALVR#935]
## Description
Lags in transcoding
Server was build with: cargo xtask build-server --no-nvidia --bundle-ffmpeg --release
Client was build with alvr_build_linux.sh
With h264 it'l lags heavily - check attached screen
![alvr_lags](https://user-images.githubusercontent.com/11353228/150880385-3c02b861-2995-4d60-bf40-92fdc9957be7.png)

With h265 no lags in statistic window, but picture in Oculus consist of random square artifacts (like old broken MPEG movie)

Also, ffmpeg give: 
ALVR$ ffmpeg 
ffmpeg: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0: undefined symbol: wl_proxy_get_tag

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 5 3600X 6-Core Processor
**GPU**:
Ellesmere [Radeon RX 580/580X/590]
**Audio**:

### Installation
**ALVR Version**:
ALVR server v17.0.0-dev.2
**SteamVR Version**:
1.20.4
**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
"Ubuntu 20.04.3 LTS"

**Comment by mittorn** [comment]
RX580 has VERY SLOW h.264 encoder and before 5.17 kernel it configured to work much slower (maybe even slower than software)
Try encode with 265 or install git kernel version. I not tried use rx580 after polaris performance fix, so i do not know if it really would be faster in this case. For me 0.7 resolution and 80fps worked good in non-heavy games on 265 after disabling rate control (remove rc_mode option from EncodePipelineVAAPI)

**Comment by mittorn** [comment]
Kernel fix for h.264:
https://www.phoronix.com/scan.php?page=news_item&px=AMD-VCE-Better-Speed
It os not ALVR issue

**Comment by Barmallini** [comment]
This shots with HEVC
One from Oculus (garbage), second from statistic
![alvr_hevc_oculus](https://user-images.githubusercontent.com/11353228/151058602-7a90e54a-ac65-4a58-8712-e74e4931c158.jpg)
![alvr_hevc](https://user-images.githubusercontent.com/11353228/151058620-2717da44-20b8-4f0a-bdfd-acc5568729b6.png)

**Comment by mittorn** [comment]
It looks like it failed to create vaapi encode pipeline (software hevc encode seems to produce garbage on quest)
