### ISSUE TITLE
Debian package  failed to create NvEnc encoder

### ISSUE THREAD

**Issue by mvvvv** [alvr-org/ALVR#937]
## Description

Installing Nightly Deb package on Ubuntu 21.10 with ffmpeg fully operational for CUDA encoding. 

11:36:37.137598114    [INFO]    ClientConnected
11:36:37.138588851    [INFO]    Serial Number: 1WMGH000XX0000
11:36:37.138611870    [INFO]    Model Number: Miramar
11:36:37.138622742    [INFO]    Render Target: 3648 1920
11:36:37.138635075    [INFO]    Seconds from Vsync to Photons: 0.005000
11:36:37.138644130    [INFO]    Refresh Rate: 72
11:36:37.139502857    [INFO]    CEncoder::Run
11:36:37.139650811    [INFO]    CEncoder Listening
11:36:37.155805383    [INFO]    Setting new IPD to: 0.068179
11:36:37.394837341    [INFO]    CEncoder client connected, pid 6368, cmdline /home/mv/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrcompositor
11:36:37.567521589    [INFO]    ClientDisconnected
11:36:37.567553365    [INFO]    Client disconnected. Cause: At alvr/sockets/src/control_socket.rs:32
11:36:37.927985170    [INFO]    failed to create VAAPI encoder
11:36:37.931522280    [INFO]    failed to create NvEnc encoder
11:36:37.962169765    [INFO]    using SW encoder

## General Troubleshooting
- [X ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=8574d37f58

### Installation
**ALVR Version**:
 ALVR v17.0.0-dev.2+nightly.2022.01.23

**SteamVR Version**:
1.21.6

**Install Type**:
- [X ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
PRETTY_NAME="Ubuntu 21.10"

**Comment by mvvvv** [comment]
Here is the test I successfully done to check that I have CUDA ffmpeg :
time ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i small.ogv -acodec copy -vcodec hevc_nvenc test.mp4

**Comment by Barmallini** [comment]
Did you have symbol lookup error?

time ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i small.ogv -acodec copy -vcodec hevc_nvenc test.mp4
ffmpeg: symbol lookup error: /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0: undefined symbol: wl_proxy_get_tag

real	0m0.035s
user	0m0.016s
sys	0m0.012s

**Comment by mvvvv** [comment]
No I don't have this error. I'm using the  ffmpeg/impish,now 7:4.4-6ubuntu5 provided by ubuntu

**Comment by Niroc** [comment]
Hi,
install cuda from your package manager (you said you already got this)

then run...
git clone https://git.videolan.org/git/ffmpeg/nv-codec-headers.git

and then 
cd nv-codec-headers && sudo make install && cd ..

and try to build ffmpeg again and see if that makes a difference?..

**Comment by Trae32566** [comment]
@mvvvv This should not require system ffmpeg libraries on `deb` packages, and that may actually cause the issue (though I don't think it should?). I would try uninstalling any ffmpeg libraries that exist; as you can see, ALVR bundles precompiled `ffmpeg` in the deb:
```
trae@build01-deb11:~/ALVR$ dpkg -c build/alvr_17.0.0-dev.3+1644798406+7d2c1045.deb | grep -P 'lib.*\.so'
-rwxr-xr-x root/root  10115792 2022-02-13 18:26 ./usr/lib64/alvr/bin/linux64/driver_alvr_server.so
-rwxr-xr-x root/root   1601496 2022-02-13 18:26 ./usr/lib64/alvr/libavcodec.so.58
-rwxr-xr-x root/root    570064 2022-02-13 18:26 ./usr/lib64/alvr/libavfilter.so.7
-rwxr-xr-x root/root   2713952 2022-02-13 18:26 ./usr/lib64/alvr/libavutil.so.56
-rwxr-xr-x root/root   3410720 2022-02-13 18:26 ./usr/lib64/alvr/libswscale.so.5
-rwxr-xr-x root/root    387272 2022-02-13 18:26 ./usr/lib64/libalvr_vulkan_layer.so
```

**Comment by mvvvv** [comment]
Ok  I'll test as soon as I see the alvr_17.0.0-dev.3+1644798406+7d2c1045.deb  in the repo. But do you mean you tweaked these libraries for alvr ?

**Comment by mvvvv** [comment]
I can't test right now cause I installed the stable deb which do not log the encoder use as it seems

**Comment by zarik5** [comment]
The deb package is not maintained anymore.
