### ISSUE TITLE
Can't access in-game menu (SteamVR dashboard opens instead)

### ISSUE THREAD

**Issue by Cleric-K** [alvr-org/ALVR#938]
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**CPU**: i5 4670

**GPU**: Radeon 560

**Audio**: Realtek

### Installation
**ALVR Version**: 17.0.0

**SteamVR Version**:  1.20.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**: Win 10 21H2

Hello,
this is a follow up to the old https://github.com/polygraphene/ALVR/issues/326

Is there any solution to this problem? I'm playing Lunar Flight with Oculus Quest 2. When I play through Air Link the menu button (left controller) works properly and brings up the game menu. With ALVR the SteamVR dashboard pops up instead and I can't access the game menu.

**Comment by ctaetcsh** [comment]
I've had this issue too in games like Beat Saber. Best suggestion is to open up the SteamVR bindings and tinker around with a combination that opens the in game menu instead of SteamVR. I usually use Y or XY together for this.

**Comment by Cleric-K** [comment]
Thanks. Actually I already did try to make bindings but probably didn't do it right. I was trying to map to `Left Application Menu Button` to `X` but it did nothing. I'll look at it again. Thanks!

**Comment by Toxblh** [comment]
Try Beta client SteamVR. Was the same for me, it just broke in current version of SteamVR

**Comment by ctaetcsh** [comment]
Switching to Beta fixed it. Thanks for the tip @Toxblh.

**Comment by Wild-Dog** [comment]
Same issue.

**Comment by basenc** [comment]
Same issue.
