### ISSUE TITLE
Can only install nightly

### ISSUE THREAD

**Issue by vladdeda** [alvr-org/ALVR#939]
## Description

For some reason I cannot install the release version of ALVR. It only lets me install the nightly version on my quest 2.
## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:

**SteamVR Version**:

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

**Comment by ctaetcsh** [comment]
Can you provide the error message you get when you try to install the regular version onto your Quest? If you're using SideQuest, you can click on the tasks page and it should tell you what the error was.
