### ISSUE TITLE
ALVR loses connection and is unable to regain it.

### ISSUE THREAD

**Issue by Kirottu** [alvr-org/ALVR#940]
## Description
ALVR after some time of playing completely freezes and the headset is unable to reconnect. The logs will say this on each attempt at reconnecting:

```
09:19:55.238679810 | [INFO] | ClientConnected
09:19:55.238867391 | [INFO] | Serial Number: 1WMGH000XX0000
09:19:55.238873562 | [INFO] | Model Number: Miramar
09:19:55.238877439 | [INFO] | Render Target: 2688 1440
09:19:55.238881928 | [INFO] | Seconds from Vsync to Photons: 0.005000
09:19:55.238885294 | [INFO] | Refresh Rate: 90
09:19:55.243840698 | [INFO] | Setting new IPD to: 0.063232
09:25:08.329056906 | [INFO] | ClientDisconnected
09:25:08.355546495 | [INFO] | Client disconnected. Cause: At alvr/sockets/src/control_socket.rs:32
```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=cf5823e07)

**Audio**:
`pipewire`

### Installation
**ALVR Version**:
Latest nightly, 2022.01.25

**SteamVR Version**:
1.21.6

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by ctaetcsh** [comment]
This might be a network issue. Make sure your computer is connected via Ethernet to your Router/AP and that your Quest has a 5 GHz WiFi connection. It's not advised to use a shared Router/AP for this application.

**Comment by Kirottu** [comment]
It is connected directly with usb to my computer, and the logs show the client tries to connect but immediately disconnects as shown in the log snippet I attached to the issue.

**Comment by ctaetcsh** [comment]
Are you using a USBC to Ethernet adapter on the Quest or just using a regular USBC cable plugged into the USB port of your PC? If it's the latter, I don't think that's a supported method.

**Comment by Kirottu** [comment]
It is the latter one and it is mentioned on the wiki, and as I said I do not think the actual connectivity is the issue. Especially as when the "disconnect" happens it just has the stream completely freeze but the client does not disconnect. When restarting the app it stays on "Searching for server" with those messages appearing in the log. A full SteamVR restart is required for it to start working again.

**Comment by ctaetcsh** [comment]
Apologies, I was unaware of the USB method.
Does SteamVR show any errors or does it continue working as expected, just disconnected from the Headset?

**Comment by Kirottu** [comment]
SteamVR does not display any errors, tracking is lost as expected due to the client being disconnected.

**Comment by Kirottu** [comment]
By looking at the source code, it seems like something goes wrong with receiving the packets at `ControlSocketReceiver::recv`.
