### ISSUE TITLE
Stuck in "Searching for Server ..." 

### ISSUE THREAD

**Issue by DanZer0z** [alvr-org/ALVR#941]
I'm following the steps of the installation guide, but when it comes to connecting the application to the server, I'm in trouble.

The server recognizes the Oculus Quest 2, I can click on the button "Trust", but the application, after I clicked "Trust", still continues in the same way "Searching Server ... Open ALVR on your PC "and I can not do anything.

I've tried older versions, but the same thing happens, do you have any solution?

**Comment by ctaetcsh** [comment]
This sounds like a networking issue. Here's a couple things to check for:
* Make sure the Quest and your PC are on the same network and not isolated in some weird way.
* Make sure your firewall settings are set correctly. **This was a prompt during setup.**
Failing that, a reboot has personally fixed a lot of my issues. Fully restart both your computer and headset and try again.
