### ISSUE TITLE
Removing ffmpeg breaks dependency

### ISSUE THREAD

**Issue by Cytomax55** [alvr-org/ALVR#944]
Manjaro 21.2.2 Qonos KDE
x86_64 Linux 5.16.2-1-MANJARO

On the AUR
When i try to run 
ALVR
or
ALVR-git 
i get

could not satisfy dependencies:
- removing ffmpeg breaks dependency 'libavcodec.so=58-64' required by chromaprint
- removing ffmpeg breaks dependency 'libavformat.so=58-64' required by chromaprint
- removing ffmpeg breaks dependency 'libavutil.so=56-64' required by chromaprint
- removing ffmpeg breaks dependency 'libswresample.so=3-64' required by chromaprint
- removing ffmpeg breaks dependency 'libswscale.so=5-64' required by freerdp

**Comment by Niroc** [comment]
Heya, 

I had that problem. Put "ffmpeg-compat" into Pamac or Yay and install the right one for compatibility with your legacy ffmpeg dependencies needs.

**Comment by kacpi2442** [comment]
AUR ffmpeg-vulcan actually builds version 5.0 of ffmpeg which breaks dependencies (instead of ffmpeg 4.4.1).
Use this patch on pkgbuild:
```
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -113,11 +113,6 @@
 prepare() {
   cd ffmpeg

-  git fetch --all --tags
-
-  # Get latest stable tag
-  # git checkout tags/$(git tag --list 'n*[!d][!e][!v]' | tail -n1)&>/dev/null
-
   git cherry-pick -n 988f2e9eb063db7c1a678729f58aab6eba59a55b # fix nvenc on older gpus
   patch -Np1 -i "${srcdir}"/vmaf-model-path.patch
 }
```

**Comment by LeadNoodle** [comment]
> 

Hi Niroc, I get this when I try to install ffmpeg-compat, not sure how to get around this :-(

conflicting files:
- ffmpeg-compat-58: /usr/lib/libavcodec.so.58 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavcodec.so.58.134.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavdevice.so.58 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavdevice.so.58.13.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavfilter.so.7 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavfilter.so.7.110.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavformat.so.58 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavformat.so.58.76.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavutil.so.56 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libavutil.so.56.70.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libpostproc.so.55 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libpostproc.so.55.9.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libswresample.so.3 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libswresample.so.3.9.100 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libswscale.so.5 already exists in filesystem (owned by ffmpeg-vulkan)
- ffmpeg-compat-58: /usr/lib/libswscale.so.5.9.100 already exists in filesystem (owned by ffmpeg-vulkan)

**Comment by Niroc** [comment]
That error means you've already got it. 

I believe ffmpeg-vulkan was patched to be backwards compatible so, you're software should just work. 

let me know if your other software doesn't work tho

**Comment by zarik5** [comment]
If you don't want to risk breaking your linux install or you just have problems having the system ffmpeg working with ALVR you can just use the portable build.

**Comment by m00nwtchr** [comment]
The actual solution is to use `paru/yay -S ffmpeg-vulkan --assume-installed ffmpeg`, IIRC

**Comment by AlanMauricioC** [comment]
yup, it seems that `ffmpeg-vulkan` has backwards compatibility  as @Niroc and @m00nwtchr mentioned,  that fixed the problem and now I was able to install it

**Comment by zarik5** [comment]
FFmpeg is now statically linked.
