### ISSUE TITLE
Reset the microphone to default

### ISSUE THREAD

**Issue by DygDyg** [alvr-org/ALVR#949]
Good afternoon, when the helmet is connected, the virtual cable is exposed by the microphone by default, but after disconnecting the helmet it does not come back, how can I fix it? Good afternoon, when the helmet is connected, the virtual cable is exposed by the microphone by default, but after disconnecting the helmet it does not come back, how can I fix it? After each game, I have to log into the recording devices and return my main microphone as the default communication device.

**Comment by SkySpnc** [comment]
do you mean that connecting a headset changed the default audio device in windows? if so; yeah this is pretty annoying tbh

**Comment by DygDyg** [comment]
The fact that the microphone from the helmet becomes the default when you turn it on is fine, but the fact that when you turn off the helmet, the microphone does not come back, that's annoying.
