### ISSUE TITLE
Add support for Upcoming Intel Arc Alchemist Graphics Cards

### ISSUE THREAD

**Issue by toby2006** [alvr-org/ALVR#950]
Intel arc will likely not be supported by the native oculus software on launch, if support for the Intel quick sync (Intel's video encoder) is added to alvr alongside nvidia's NVENC and amd's VCE will allow the use of the oculus quest with the alchemist GPU's

**Comment by zarik5** [comment]
Vulkan Video extensions are in the process of being stabilized. These extensions do not allow just portability between GPU models/vendors but also between Windows and Linux OSes. Once stable, we will rewrite the encoder with these extensions
