### ISSUE TITLE
Client freezes with Linux server

### ISSUE THREAD

**Issue by RyanGar46** [alvr-org/ALVR#953]
## Description
The client freezes with a Linux server. I know this is an issue with Linux since I dual boot Windows 11, and ALVR works just fine on there. I am using ALVR over the official Oculus link, but this issue occurs even wireless.

![alvr client quest-20220205-170428](https://user-images.githubusercontent.com/67124977/152660877-bdac471b-967b-4f80-9a90-7c5297f96d6f.jpg)

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
https://linux-hardware.org/?probe=145ea1361d

**CPU**:
AMD Ryzen 5 5600X (6-Core)

**GPU**:
RTX 2070 Super - Founders Edition

### Installation
**ALVR Version**:
17.0.1

**SteamVR Version**:
1.20.4

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version**:
Linux Mint 20.3

**Comment by Niroc** [comment]
can you post the log? (in ALVR dashboard, in the "logging" tab)
