### ISSUE TITLE
Firewall rule creation fails with exit code 127

### ISSUE THREAD

**Issue by tcrass** [alvr-org/ALVR#957]
## Description

When trying to set up the firewall rules, the execution fails with exit code 127. This might be caused by the script not being executable; after

`sudo chmod a+x /usr/libexec/alvr/alvr_fw_config.sh`

the script still fails, but with the expected exit code 99 (since there is no iptables on my system).

Corresponding Dashboard log entries:

```
11:40:52.380026187	[ERROR]	Setting firewall rules failed: code 127
11:43:35.344400025	[ERROR]	Setting firewall rules failed: code 99
```

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

https://linux-hardware.org/?probe=bc0462d8e3

**CPU**:

**GPU**:

**Audio**:

### Installation
**ALVR Version**:

17.0.1+1643781622+0541c19e on both client and server

**SteamVR Version**:

1.20.4

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):

Debian GNU/Linux 11 (bullseye) (up-to-date)

**Comment by Trae32566** [comment]
This will be fixed in PR #962

**Comment by Trae32566** [comment]
Just to verify @tcrass , I assume you don't have `ufw` or `firewalld` installed either? It should autodetect those.

**Comment by tcrass** [comment]
> Just to verify @tcrass , I assume you don't have `ufw` or `firewalld` installed either? It should autodetect those.

Nope, no firewall software whatsoever installed -- my computer is entirely unprotected... ;)
