### ISSUE TITLE
Documentation: On the Build from Source wiki page the Gentoo section

### ISSUE THREAD

**Issue by fergycool** [alvr-org/ALVR#960]
Apologies for a misplaced bug report. But I cannot edit the wiki.

For building from source (ALVR17.0.1) on Gentoo you need to have ffmpeg built with libdrm as well as the three other useflags that are listed:

`media-video/ffmpeg libdrm`

Without that useflag no video is output to the headset and you have video on the monitor but a green screen on the headset.

**Comment by Trae32566** [comment]
I've updated the documentation; thank you for the info!
