### ISSUE TITLE
Oculus Go - Crash during handshake

### ISSUE THREAD

**Issue by mjbarr** [alvr-org/ALVR#961]
Hi, every time I try to connect the Oculus Go to ALVR I get the error shown below and the Oculus Go client crashes.  If I go back to version 14 this error does not occur, (I think I traced this text in the source code as only appearing after that: "Audio devices with more than 2 channels are not supported. Please turn off surround audio.")

Any  idea how I can get past this on latest version would be great.

<html>
<body>

21:17:06.076881100 | [INFO] | Model Number: Miramar
-- | -- | --
21:17:06.076889300 | [INFO] | Render Target: 2560 1440
21:17:06.076900500 | [INFO] | Seconds from Vsync to Photons: 0.005000
21:17:06.076907500 | [INFO] | Refresh Rate: 72
21:17:07.213043700 | [INFO] | Setting new IPD to: 0.064000
21:17:08.382455000 | [ERROR] | Audio devices with more than 2 channels are not supported. Please turn off surround audio.
21:17:10.560884000 | [WARN] | Handshake: At alvr\server\src\connection.rs:117: At alvr\sockets\src\control_socket.rs:78: An existing connection was forcibly closed by the remote host. (os error 10054)

</body>
</html>

 Environement

I am running on Windows 11, Ryzen 5 2600 and 3060TI GPU, with RealTek onboard audio (MSI X470 motherboard)
**Audio**:

### Installation
ALVR version 17.0.1

**SteamVR Version**:
1.21.7

**Install Type**:
portable zip

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 11 version 21H2 build 22000.258

**Comment by Niroc** [comment]
Hey, 
is there any chance you can set your windows audio to stereo as the quest only has 2 speakers

**Comment by Ekristoffe** [comment]
Hello I have an Oculus go, i will do a test with my hardware

**Comment by Xgames123** [comment]
I have the same issue.
The only sort of thing that helps is resart steamvr over and over like 10 times and than randomly it works
I also tried disable-ling antivirus and firewall but that didn't do anything
