### ISSUE TITLE
Add support for Brave Browser

### ISSUE THREAD

**Issue by xdevilkillx** [alvr-org/ALVR#966]
Brave Browser is a chromium based browser, can you add support please?

**Comment by Niroc** [comment]
hey, in the meantime....

open brave and put "localhost:8082" in the address bar
or
you can set brave to be the browser by using "ALCRO_BROWSER_PATH" variable and point it to brave if your just use a shortcut or running it from the terminal

**Comment by SandDew** [comment]
As an alternative, you could download chromium. It's open source, and you never have to touch it.

**Comment by zarik5** [comment]
The solution is explained here: https://github.com/alvr-org/ALVR/issues/446#issuecomment-766530078
