### ISSUE TITLE
A and B buttons on right controller not working with v17.0.0-dev.6+nightly.2022.02.12 and after

### ISSUE THREAD

**Issue by vinicios-cervantes** [alvr-org/ALVR#969]
## Description

A and B buttons on right controller stopped working on v17.0.0-dev.6+nightly.2022.02.12 and after.
Im using a QUEST 2, with a wired connection, and tested with SteamVR stable and beta. 

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Intel I7 9750h
**GPU**:
GTX 1660Ti

**Audio**:
Notebook speakers with Realtek Audio Drivers.

### Installation
**ALVR Version**:
v17.0.0-dev.6+nightly.2022.02.14

**SteamVR Version**:
1.21.8(Beta)

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Windows 10 Ver. 21H2 Comp. 19044.1526

**Comment by thankjura** [comment]
Same problem on linux(build from source) and incorrect rotation of the controller

**Comment by andy-d1969** [comment]
I can confirm the issue with wired connection on Manjaro. The left controller works fine, the right one doesn't.

**Comment by zarik5** [comment]
I need help debugging this. The offending commit for the buttons not working should be this one: https://github.com/alvr-org/ALVR/commit/827b80fe766d4e9b2d735f1a44d92f9b9483a81d
The problem is that I touched only code that should be unreachable.

**Comment by andy-d1969** [comment]
I reverted that commit and rebuilt, but the buttons are still not working.

**Comment by zarik5** [comment]
Can you please go back in history to find the break point where buttons stop working?

**Comment by zarik5** [comment]
Maybe it's the previous commit: 4a593d11483068841dafcf4ed50cf75e4cd5534e

**Comment by andy-d1969** [comment]
Ok, I just rebuilt version f5b8dc3 and the buttons work.

**Comment by andy-d1969** [comment]
Master with https://github.com/alvr-org/ALVR/commit/827b80fe766d4e9b2d735f1a44d92f9b9483a81d and https://github.com/alvr-org/ALVR/commit/4a593d11483068841dafcf4ed50cf75e4cd5534e reverted works too.

**Comment by zarik5** [comment]
@andy-d1969 Great, thank you so much!

**Comment by zarik5** [comment]
By the way, I think I found the bug! I'm adding back the changes in those two commits, but split into multiple commits so it's less error prone.

**Comment by ColdIce1605** [comment]
May I ask what it was?

**Comment by zarik5** [comment]
To explain what I'm doing, I'm rewriting the code bit by bit to be more generic/flexible and to use OpenXR conventions when possible
