### ISSUE TITLE
Stuck on "Stream will start soon" after upgrading to ffmpeg 5.0

### ISSUE THREAD

**Issue by Kirottu** [alvr-org/ALVR#978]
## Description
After upgrading to ffmpeg 5.0 on a system level, it no longer begins streaming and stays stuck on "Stream will begin soon" with the traditional distorted view. Building from source with the `--bundle-ffmpeg` option does have the stream working, but the latency is horrible (multiple seconds), and controllers don't seem to be working. Keyword here is "seem" as I honestly have no clue as the latency is so bad.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
[hw-probe](https://linux-hardware.org/?probe=5fe85bba2e)

### Installation
**ALVR Version**: Latest master at the time of writing this

**SteamVR Version**:
1.21.8 beta

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by JacekJagosz** [comment]
I think it could be that FFMpeg 5.0 is somehow broken, not ALVR.
At least that is why ALVR package in AUR was broken for some time, they said the FFMpeg build broke with ubdate to 5.0 https://aur.archlinux.org/packages/ffmpeg-vulkan#comment-848485
