### ISSUE TITLE
AlVR is stuck at waiting

### ISSUE THREAD

**Issue by lrutjens** [alvr-org/ALVR#987]
Steam vr crashes and reloads while blocking the addons. They’ll briefly be unblocked before it crashes and blocks then when it starts again

**Comment by lrutjens** [comment]
This also happened on the nightly release too

**Comment by ColdIce1605** [comment]
Could you please add a little bit more info like idk, the alvr version, specs, distro etc.
Thank you

**Comment by lrutjens** [comment]
Windows 10, 3060ti, nightly release and v17.0.2

**Comment by lrutjens** [comment]
Is there anywhere I could get logs?

**Comment by lrutjens** [comment]
[crash_log.txt](https://github.com/alvr-org/ALVR/files/8145662/crash_log.txt)
Do i need to gpus?

**Comment by ColdIce1605** [comment]
Do you have anything else as a addon in steamvr?

**Comment by lrutjens** [comment]
game pad support, and occasionally VD support will appear

**Comment by lrutjens** [comment]
that is, thats all it says

**Comment by lrutjens** [comment]
> Something is fishy about that please paste the whole log

unless theres another log somewhere

**Comment by lrutjens** [comment]
I just tried on the new update and it’s still happening, can anyone tell me where I can find the logs?

**Comment by lrutjens** [comment]
Fixed it, reinstalled steam vr
