### ISSUE TITLE
HEVC codec not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by deividaspran** [alvr-org/ALVR#990]
## Description

When I set Video Codec to HEC (h265) I just get random glitching colors on the headset. Logs are showing:
17:43:43.925993258 | [INFO] | failed to create VAAPI encoder
-- | -- | --
17:43:43.926094905 | [INFO] | failed to create NvEnc encoder

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new
Encoding/decoding matrix shows that my RTX 2060 should support NVENC in all formats.

It works if switch back to h264 but the performance is rather low (~40 FPS with artifacts). Maybe I'm missing some libraries?

Huge thanks for everyone working on this! This is really the last piece of the puzzle to start daily driving Linux

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`
https://linux-hardware.org/?probe=2e06b2fed8

**CPU**: Ryzen 7 3700X

**GPU**: NVIDIA RTX 2060

**Audio**: None

### Installation
**ALVR Version**:  v18.0.0-dev00

**SteamVR Version**: 1.21.8

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Ubuntu 20.04.4 LTS

**Comment by mvvvv** [comment]
same for me, using the deb package

**Comment by timshannon** [comment]
I believe h264 is slow because it's not using hardware encoding.  I'm seeing the same issue when using h265, and when I switch to h264 I see the same slow performance, and my CPU usage skyrockets.

**Comment by deividaspran** [comment]
@timshannon  I believe so. The logs show that ASVR fallbacks to software encoding since hardware one failed to initialize. This in result uses quite a lot of CPU (hitting all the cores above 70%), hence decreased performance. How's your performance on h265? What fps/latency are you getting?

**Comment by timshannon** [comment]
@deividaspran I get a blurry garbled mess anytime I try to use h265.

**Comment by ColdIce1605** [comment]
@timshannon that's because software encoding is broken on x265

**Comment by timshannon** [comment]
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
```

I just installed the version out of the ubuntu repos.

**Comment by deividaspran** [comment]
Cuda:
```
cuda:
  Installed: 11.6.1-1
  Candidate: 11.6.1-1
  Version table:
 *** 11.6.1-1 600
        600 file:/var/cuda-repo-ubuntu2004-11-6-local  Packages
        100 /var/lib/dpkg/status
```

More detailed logs:
```
x265 [info]: HEVC encoder version 3.4
x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main profile, Level-5 (High tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(30 rows)
Message: {"method":"Runtime.consoleAPICalled","params":{"args":[{"type":"string","value":"10:16:18.244614912 [INFO] failed to create VAAPI encoder"}],"executionContextId":2,"stackTrace":{"callFrames":[{"columnNumber":20,"functionName":"addLogLine","lineNumber":333,"scriptId":"15","url":"http://127.0.0.1:8082/js/app/monitor.js"},{"columnNumber":16,"functionName":"","lineNumber":49,"scriptId":"15","url":"http://127.0.0.1:8082/js/app/monitor.js"}]},"timestamp":1646554578244.8809,"type":"log"}}
Message: {"method":"Runtime.consoleAPICalled","params":{"args":[{"type":"string","value":"10:16:18.244692978 [INFO] failed to create NvEnc encoder"}],"executionContextId":2,"stackTrace":{"callFrames":[{"columnNumber":20,"functionName":"addLogLine","lineNumber":333,"scriptId":"15","url":"http://127.0.0.1:8082/js/app/monitor.js"},{"columnNumber":16,"functionName":"","lineNumber":49,"scriptId":"15","url":"http://127.0.0.1:8082/js/app/monitor.js"}]},"timestamp":1646554578245.3389,"type":"log"}}
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Lookahead / bframes / badapt        : 0 / 0 / 0
x265 [info]: b-pyramid / weightp / weightb       : 0 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: Rate Control / qCompress            : ABR-30000 kbps / 0.60
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip mode=1 tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing lslices=6 deblock
```

**Comment by deividaspran** [comment]
Issue was likely caused by missing libnvidia-encode package. Hvec works now,  but rtx 2060 is having hard time with this encoding
