### ISSUE TITLE
(Linux) CEncoder.cpp not getting past "GetBestPoseMatch"

### ISSUE THREAD

**Issue by Niroc** [alvr-org/ALVR#991]
## Description
Since commit 57f3f6b [Set correct pts on Linux](https://github.com/alvr-org/ALVR/commit/57f3f6b102af52faafa01f64b5f08d20e8cf0fdf) ALVR server stuck within the while loop "while (not m_exiting)" in CEncoder.cpp.
The code cannot get past..
#####
        auto pose = m_poseHistory->GetBestPoseMatch((const vr::HmdMatrix34_t&)frame_info.pose);
        if (!pose)
        {
          continue;
        }
#####

within PoseHistory.cpp the following isn't being executed as the info messages aren't being outputted
#####
    for (auto it = m_poseBuffer.begin(); it != m_poseBuffer.end(); ++it) {
        float distance = 0;
        // Rotation matrix composes a part of ViewMatrix of TrackingInfo.
        // Be carefull of transpose.
        // And bottom side and right side of matrix should not be compared, because pPose does not contain that part of matrix.
        Info("PoseHistory.cpp -> doing for loop 'int i = 0; i < 3; i++'");
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                distance += pow(it->rotationMatrix.m[j][i] - pose.m[j][i], 2);
            }
        }
        Info("PoseHistory.cpp -> doing if 'minDiff > distance'");
        //LogDriver("diff %f %llu", distance, it->info.FrameIndex);
        if (minDiff > distance) {
            minIt = it;
            minDiff = distance;
        }
    }
######
the reason for it not executing seems to be because m_poseBuffer.size is zero

(bespoke logging info)
18:46:08.895300526 [INFO] CEncoder.cpp -> done read_latest
18:46:08.895362437 [INFO] CEncoder.cpp -> set bitrate, doing pose match
18:46:08.895375966 [INFO] PoseHistory.cpp -> starting get best pose match
18:46:08.895386017 [INFO] m_poseBuffer  size: 0
18:46:08.895405426 [INFO] PoseHistory.cpp -> starting for loop 'auto it = m_poseBuffer.begin()'
18:46:08.895428302 [INFO] PoseHistory.cpp -> doing if 'minIt != m_poseBuffer.end())'
18:46:08.895440284 [INFO] m_poseBuffer: 165633952
18:46:08.895457030 [INFO] PoseHistory.cpp -> returning
18:46:08.911712748 [INFO] CEncoder.cpp -> done read_latest
18:46:08.911762591 [INFO] CEncoder.cpp -> set bitrate, doing pose match

In OvrHMD.cpp I can't see "void OvrHmd::OnPoseUpdated(TrackingInfo info)" being called as it's not outputting Info messages 

in alvr_server.cpp I can't see void InputReceive(TrackingInfo data) being called as that's not outputting info messages to the log either 

## General Troubleshooting
- [ x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
64bit, XFCE4 (compositor disabled)

### Hardware
https://linux-hardware.org/?probe=dfe7b95d25

### Installation
**ALVR Version**: commit 57f3f6b 

**SteamVR Version**: beta 1.21.10

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [X ] Source

**OS Name and Version** 
PRETTY_NAME="Arch Linux"
5.17.0-rc5-246-tkg-pds

**Comment by zarik5** [comment]
If the server is not receiving tracking data it may be because server and client have different versions.

**Comment by Niroc** [comment]
I built from the same source but, I'll happily try again for certainty.

**Comment by Niroc** [comment]
no luck I'm afraid, still got the issue.

**Comment by ColdIce1605** [comment]
do you have a branch I could try this on

**Comment by Niroc** [comment]
I just used this https://github.com/alvr-org/ALVR/tree/57f3f6b102af52faafa01f64b5f08d20e8cf0fdf

**Comment by ColdIce1605** [comment]
With the logging

**Comment by Niroc** [comment]
I can give you the server files...
[server.zip](https://github.com/alvr-org/ALVR/files/8149470/server.zip)

if you're on the discord server then I've been working on this for a few hours

**Comment by ColdIce1605** [comment]
this doesn't seem to be updated its has one of the cargo.toml as 17.0.0

**Comment by ColdIce1605** [comment]
ok confirmed something else is going on I don't have this bug, tho I'm using a later commits but idk

**Comment by Niroc** [comment]
That's the exact commit where broke ALVR for me so, I've just been working with that personally.
The commits prior are working fine I can confirm so, I'm unsure how the pins would help me.
also, there are no pins in # linux-help

**Comment by ColdIce1605** [comment]
I said # help not # linux-help

**Comment by Niroc** [comment]
in commit   57f3f6b
alvr/server/cpp/platform/linux/CEncoder.cpp
![image](https://user-images.githubusercontent.com/12100786/155904005-420346b6-1d39-4237-996b-211545eba711.png)
the above if statement was repurposed in the commit I mentioned. removing this continue allows the stream to start as expected. but, in the discord it was stated that the if statement may need to be there...
