### ISSUE TITLE
Can Built-in browser be microsoft egde?

### ISSUE THREAD

**Issue by Terrificia** [alvr-org/ALVR#992]
Or is there any way to change chrome to edge in AlVR, I don't wanna download another browser in my PC, hope it can add a switch to let user change the browser what they want.

**Comment by zarik5** [comment]
You can use the chromium-based Edge browser of Windows 10/11.

**Comment by Terrificia** [comment]
> You can use the chromium-based Edge browser of Windows 10/11.

Oh.. my bad, it seems like the old version ALVR can't identify edge, I download 18.1.0, it works well, thank you
