### ISSUE TITLE
Slight annoyance, Edge pops up box to 'sync your profile' but workaround possible

### ISSUE THREAD

**Issue by rubjonny** [alvr-org/ALVR#994]
As title, after updating to newest release (could be unrelated though, maybe windows/edge did something in the mean time) when ALVR is loaded a popup box saying some thing like 'as you are signed into this device, edge will sync your profile' would appear every time, with only option 'got it'.

I tried disabling sync in edge settings but that didn't help, so I went into settings, accounts, email and accounts then removed the referenced account here which solved it. Since I dont actually need my account here its no problem for me, but may be an issue for others. Seems related to this issue, but unfortunately no solution given:
https://answers.microsoft.com/en-us/microsoftedge/forum/all/how-can-i-disable-sync-your-profile-dialog-box-in/881547b6-421b-4ad3-8b0c-0ec0a8e31803

**Comment by rubjonny** [comment]
still doing it with new release, added my account back in to test and grabbed a screenshot if it helps
![Clipboard01](https://user-images.githubusercontent.com/77489109/157229294-667b051e-58b7-4f00-8342-3b38e3093764.jpg)

**Comment by zarik5** [comment]
@rubjonny In the next nightly you should should find a new section Extra->patches with a toggle to fix the popup on Edge.

**Comment by rubjonny** [comment]
Nice :)

**Comment by rubjonny** [comment]
ok upgraded just now and that stops the popup, now it just has a message up top about edge being controlled by automated test software which when closed leaves you with an extra title bar inside the main window. less annoying so thanks for that :)

**Comment by zarik5** [comment]
Yeah, it's a compromise. We still plan to move away from the chromium webview (we will use a pure Rust GUI) but we don't have an ETA for now.

**Comment by rubjonny** [comment]
thats cool, so long as the annoying box is gone thats the main thing
