### ISSUE TITLE
Unable to build from source on Gentoo Linux without JACK

### ISSUE THREAD

**Issue by fergycool** [alvr-org/ALVR#995]
JACK was added to the v18.0.0 release.

Since then I have been unable to build from source on Gentoo as it fails:

`/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -ljack`

I'm assuming that this is happening as Gentoo is a peculiar distro as it only builds/installs dependencies into libraries when you specify them using a USEFLAG. I do not use JACK and so I do not have any JACK libraries etc. on my system.

I'm assuming that JACK is an optional audio output device and is not mandatory?

Is there a way of making this optional in building?

If not then I guess I have two options....

- Rebuild my Gentoo system using the JACK useflag.
- Alternatively I guess I could use a Docker container of a vanilla distro to build. If so what would be the most suitable?

**Comment by fergycool** [comment]
I would add that I can successfully build the latest nightly (pulled 28th Feb). Is there a difference in the JACK requirement?

**Comment by fergycool** [comment]
Turns there's a JACK compatibility USEFLAG for PIPEWIRE. Rebuilding Pipewire with that brings in some libraries and allows me to successfully build ALVR 18.0.1 on Gentoo.

The USEFLAG for Gentoo is:

`JACK-SDK`

So I would guess that's mandatory for any GENTOO user who uses Pipewire

**Comment by hedmo** [comment]
@fergycool 

yes you can add USE=jack-sdk to pipwire . but you wont get sound .

**Comment by fergycool** [comment]
Thanks. Up to now I've had sound coming through my external speakers from the system, rather than the headset.

**Comment by hedmo** [comment]
if you get sound working on the headset let me know.
