### ISSUE TITLE
Failed building server on Ubuntu 18.04

### ISSUE THREAD

**Issue by PyxAI** [alvr-org/ALVR#996]
Client build works fine, but on server build im getting:
`  cargo:warning=cpp/alvr_server/Settings.cpp:8:10: fatal error: filesystem: No such file or directory`

I'm on AMD, 3090 with cuda

**Comment by PyxAI** [comment]
Resolved by actually deleting the Settings file that was there

**Comment by silasalves** [comment]
After some tinkering, I was able to compile it on Ubuntu 18.04. Unfortunately I can't upgrade to 20.04, so I had to find a solution.

To summarize, I added new sources so I could get the latest version of `ffmpeg`, `gcc-9` and `g++ 9`. Then I downloaded the [latest ffmpeg binaries](https://github.com/BtbN/FFmpeg-Builds/releases) and extracted into `./deps/linux`.

Here is the detailed process:

```
sudo apt install software-properties-common
sudo add-apt-repository --yes ppa:jonathonf/ffmpeg-4
sudo apt update
sudo apt install ffmpeg libavutil -y

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-9 g++-9 clang -y

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 700 --slave /usr/bin/g++ g++ /usr/bin/g++-7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 900 --slave /usr/bin/g++ g++ /usr/bin/g++-9

# Confirm that gcc-9/g++-9 is being used
sudo update-alternatives --config gcc

git clone https://github.com/alvr-org/ALVR.git
cd ALVR
cargo update -p rhai --precise 1.6.0 # version 1.5.0 is broken
cargo update

mkdir deps deps/linux
```

At this point, I downloaded [ffmpeg-n5.0-latest-linux64-gpl-5.0.tar.xz](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-linux64-gpl-5.0.tar.xz) and extracted it to `deps/linux`, ensuring that the directory I extracted everythingo to is called `ffmpeg`, not `ffmpeg-n5.0-latest-linux64-gpl-5.0`.

Then I compiled everything with:

```
./packaging/alvr_build_linux.sh server --server-args='--release --gpl'
```
