### ISSUE TITLE
Gtx 1650

### ISSUE THREAD

**Issue by raimondg** [alvr-org/ALVR#999]
please make the gtx 1650 supportive again in alvr I can’t play pcvr games with my friends

**Comment by raimondg** [comment]
please

**Comment by ColdIce1605** [comment]
Can you describe the issue your having better(like a screenshot of what you're getting? Please don't open pointless issues like this your be much better supported in discord or the matrix chat.

**Comment by raimondg** [comment]
when the gtx 1650 was supported in Alvr I played the forest and Vrchat with good performance but now it says that my gpu is unknown and I only get 11 fps in vr chat

**Comment by ColdIce1605** [comment]
sounds like you are using the default windows drivers again a screenshot would be nice, also as said in my above comment this would be better addressed in discord or matrix

**Comment by raimondg** [comment]
can I have the discord link please?
